### PR TITLE
Add "unsafe-eval" to script-src CSP

### LINKED ISSUE #18750: OCR fails to load and Tesseract errors in console
### Steps to reproduce the problem

1. Upload an image with some text in the web-ui
2. Click 'Detect text from picture'
3. The text 'Preparing OCR' keeps showing 
4. In the browser console the following error message keeps showing:

`RuntimeError: abort(CompileError: call to WebAssembly.instantiate() blocked by CSP). Build with -s ASSERTIONS=1 for more info.            tesseract-core.wasm-e4db7f953ac7bcf9f67bd39031e42241.js:1:8515`

### Expected behaviour

Text should be detected

### Actual behaviour

Nothing happens and errors in browser console

### Specifications

Tested on three different Mastodon servers (incl. mastodon.social, all v3.5.3), on desktop (Linux Ubuntu 22.04 - latest Firefox, Chomium and Gnome Web) and on mobile (Android 11 - latest Firefox - via home wifi and mobile data).

### PR DESCRIPTION
**Pull request by prplecake**
Fixes #18750 

> Firefox now supports Content-Security-Policy (CSP) integration with WebAssembly. A document with a CSP that restricts scripts will no longer execute WebAssembly unless the policy uses 'unsafe-eval' or the new 'wasm-unsafe-eval' keyword."

https://connect.mozilla.org/t5/discussions/new-csp-enhancements-in-firefox-102/td-p/8816

### CODE REVIEW

**Comment by tribela** [comment]
isnt' `wasm-unsafe-eval` more strict?

**Comment by prplecake** [comment]
> isnt' `wasm-unsafe-eval` more strict?

I was seeing the same CSP errors shown in #18750 using that directive. I only got it working with `unsafe-eval`.

**Review by Gargron — APPROVED** [review]

**Comment by MarcelWaldvogel** [comment]
Agreeing with @tribela : Could you please change `unsafe-eval` to `wasm-unsafe-eval`? It is supported by all current platforms and avoids `eval` loopholes. https://caniuse.com/?search=wasm-unsafe-eval

**Comment by prplecake** [comment]
> Agreeing with @tribela : Could you please change `unsafe-eval` to `wasm-unsafe-eval`? It is supported by all current platforms and avoids `eval` loopholes. https://caniuse.com/?search=wasm-unsafe-eval

What the hell are you talking about @MarcelWaldvogel? loopholes? Did you miss [my comment from earlier](https://github.com/mastodon/mastodon/pull/18817#issuecomment-1186409405) where I say using 'wasm-unsafe-eval' produces the same errors? Did you get it working with 'wasm-unsafe-eval'?

Be helpful and address that instead of just giving am unnecessarily long-winded "+1".

**Comment by felixdoerre** [comment]
I've just tested `wasm-unsafe-eval` (FF 102.0.1) and it works flawlessly: Patching the CSP (in a clean 3.5.3 installation) to contain `wasm-unsafe-eval` I was able to load and use the OCR feature that didn't work before applying that fix.

**Comment by prplecake** [comment]
> I've just tested `wasm-unsafe-eval` (FF 102.0.1) and it works flawlessly: Patching the CSP (in a clean 3.5.3 installation) to contain `wasm-unsafe-eval` I was able to load and use the OCR feature that didn't work before applying that fix.

"Works for me" isn't a fix.

**Comment by tribela** [comment]
It was issued 4 months ago. How about re-testing with wasm-unsafe-eval now?

**Comment by felixdoerre** [comment]
> "Works for me" isn't a fix, or, put another way, why doesn't that work for me?

stating a browser version would be a start to figure out why it doesn't work for you.

**Comment by prplecake** [comment]
* Firefox 106.0.5
* Safari 16.1 (macOS 13.1)
* Chrome 109.0.5410.0 (Official Build) dev (x86_64)

In all browsers I see the following errors in the console:
```
tesseract-core.wasm-e4db7f953ac7bcf9f67bd39031e42241.js:1 CompileError: WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://compostintraining.club wasm-unsafe-eval"
tesseract-core.wasm-e4db7f953ac7bcf9f67bd39031e42241.js:1 CompileError: WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://compostintraining.club wasm-unsafe-eval"
```

The error messages literally state the issue is a lack of 'unsafe-eval' present in the policy...

**Comment by felixdoerre** [comment]
I can't tell why it doesn't work in your firefox (and why firefox would give the exact same error message, as they look slightly different in my firefox), but using chrome I was able to reproduce the exact error message. It looks like chrome requires to quote the `wasm-unsafe-eval`-token, just like it is done for `self`. Can you try changing the policy to `script-src 'self' https://compostintraining.club 'wasm-unsafe-eval'` and see if that works in chrome? For me it's now working both in FF and in chromium 107.0.5304.87 with this CSP: `script-src 'self' 'wasm-unsafe-eval' https://example.com;`

**Comment by prplecake** [comment]
> Can you try changing the policy to `script-src 'self' https://compostintraining.club 'wasm-unsafe-eval'`

Do you have suggestions on how? Currently I'm just doing a literal quote in Ruby:
```diff
diff --git a/config/initializers/content_security_policy.rb b/config/initializers/content_security_policy.rb
index 8b5c0d2b2..185651874 100644
--- a/config/initializers/content_security_policy.rb
+++ b/config/initializers/content_security_policy.rb
@@ -31,7 +31,7 @@ if Rails.env.production?
     p.base_uri        :none
     p.default_src     :none
     p.frame_ancestors :none
-    p.script_src      :self, assets_host, :unsafe_eval'
+    p.script_src      :self, assets_host, 'unsafe-wasm-eval'
     p.font_src        :self, assets_host
     p.img_src         :self, :data, :blob, *data_hosts, 'https://34.si', 'https://inst.ance.tk'
     p.style_src       :self, assets_host, :unsafe_inline, 'https://inst.ance.tk', 'https://compostintraining.github.io'
```

which results in an **unquoted** `unsafe-wasm-eval` in the CSP.

**Comment by felixdoerre** [comment]
I have this diff:
```diff
diff --git a/config/initializers/content_security_policy.rb b/config/initializers/content_security_policy.rb
index c113b0f8b..4e07200a9 100644
--- a/config/initializers/content_security_policy.rb
+++ b/config/initializers/content_security_policy.rb
@@ -36,7 +36,7 @@ Rails.application.config.content_security_policy do |p|
     p.worker_src  :self, :blob, assets_host
   else
     p.connect_src :self, :data, :blob, assets_host, media_host, Rails.configuration.x.streaming_api_base_url
-    p.script_src  :self, assets_host
+    p.script_src  :self, "'wasm-unsafe-eval'", assets_host
     p.child_src   :self, :blob, assets_host
     p.worker_src  :self, :blob, assets_host
   end
```

**Comment by prplecake** [comment]
Alright, I think I can confirm that works... as unintuitive as it is.

**Comment by prplecake** [comment]
#20606

**Pull request merged**
