### PR TITLE
add persistance to Postresql container

### PR DESCRIPTION
**Pull request by valentin2105**
Create a volume for Postgres datas. Because if you kill all containers without this volume, all users are losts.

### CODE REVIEW

**Comment by Wonderfall** [comment]
Same goes for redis : 

```
  volumes:
    - ./redis:/data
```

**Comment by Gargron** [comment]
Does docker-compose automatically create these folders on the host, or do you have to create them yourself? Or does docker-compose complain if they're not there?

For the record when this option is not specified, the contains still use volumes, they're just anonymous volumes that are hard to find later.

**Comment by Wonderfall** [comment]
@Gargron docker-compose is smart and does all the magic for you. :)

**Comment by Gargron** [comment]
In that case please add @Wonderfall's suggested addition and I will merge

**Comment by valentin2105** [comment]
I think it's a better idea to specify the path for volumes, for easy backup for example.

**Comment by krainboltgreene** [comment]
This will break on local development in a vm (aka mac), since they wont have the right permissions.

**Comment by valentin2105** [comment]
So why not create a specific dev compose file ?

**Review by krainboltgreene — APPROVED** [review]

**Comment by Gargron** [comment]
While this is a good change for new installations, I have realized (the hard way from an admin trying this out) that this will make docker-compose **break previous installations during update**.

I am reverting this until we can figure out how to not brick people's existing configurations.

**Comment by jemus42** [comment]
Is @Wonderfall's redis addition really necessary? Because I'm one of those admins who lost their db because of a `docker-compose down`, but after I found the old postgres volume in `var/lib/docker/volumes` and mounted that for postgres, my database was intact again.

**Comment by Wonderfall** [comment]
@jemus42 `/data` contains the dump.rdb file.

**Pull request merged**
