### PR TITLE
Create a script for easy backups on docker-compose installations

### PR DESCRIPTION
**Pull request by halest**
Suggesting to add an easy-backup script for docker-compose-installations.
Finds db-mountpoints, creates structure on configurable target and backs up db and folder structure

### CODE REVIEW

**Comment by expenses** [comment]
Could this be a rake task instead?

**Comment by halest** [comment]
@expenses I don't know, maybe? It's working pretty well as is and I know pretty much nothing about rake so I I'm the wrong person to ask.

**Comment by thurloat** [comment]
I'm all for easier backup methods, and helping users out with it -- but I think this method is a little too bash-y.

I think a rake task would work better / be more familiar, and allow users to be able to leverage their `.env.production` files instead of having to maintain edits to a shell script.

**Comment by Gargron** [comment]
Something [like this](https://backup.github.io/backup/v4/) would be more appropriate I think

**Comment by Gargron** [comment]
We want to perhaps add a rake method in the future, but not bash scripts. Thank you for your effort. You may distribute this as a gist or tutorial or a repository with useful bash scripts for Mastodon, but it's not for the main repository.

**Pull request closed without merging**
