### PR TITLE
Add language dropdown to compose in web UI

### LINKED ISSUE #3478: Add a button to choose toot lang
TL;DR: Please make the "choose your toot language" happen.

I've been browsing the issues list, it seems that the team choose to go with CLD2 for language detection… and closed this issue  #691 

But CLD2 detects only around 80 languages, there is more than 7000 out there. On top of that it can be wrong.

On the other hand, I totally agree that most people speak one of the top 50 languages spoken on Earth.

But there is still some weirdos to use regional dialects or conlang. I'm one of them. For the record, I toot in french, english, toki pona and kotava. I've also seen quite a lot of Esperanto and medieval french.

So I'm asking the team to consider a button allowing mastonauts to force language on a per-toot basis, with possibly a default language and CLD2 fallback if nothing was specified.

Thank you

### LINKED ISSUE #9550: [Feature Request] Post language selector in the compose view.
Many people post in two (or more) different language (English and their native language, mostly). Instead of a single "posting language", it would be nice to be able to select multiple ones and then get a drop-down selector between those in the compose view.

The "auto-detect language" feature doesn't seem to work in many cases. I personally get a lot of French and German posts of users telling me their setting is auto-detect. I only want to see their English posts, since I'm not fluent in French or German.

# Implementation

1. Support multi-select of posting language in Settings.
2. In the compose view, next to the "CW" tag, have a tag with the most recently used language from the list in the settings. F.e. "en"
3. When clicked, show a select box with the other languages in settings.
4. The box in the compose view could of course be hidden for users with only one language selected in settings.

### LINKED ISSUE #17073: Per-toot language
### Pitch

I propose that the language can be specified for individual toots. By default, the language is whatever you specified in your profile as your "toot language" but you can choose to select a different langauge for individual toots.

### Motivation

For example, when you mostly toot in English, but occasionally toot in German as well. Currently, all your toots are marked as being in the language you set in the profile.

### PR DESCRIPTION
**Pull request by Gargron**
Ref: #18241

https://user-images.githubusercontent.com/184731/168474881-39daf7f8-3ff9-49d7-8789-0f998bc92173.mp4

___

- Fix #17073
- Fix #9550
- Fix #3478

### CODE REVIEW

**Comment by tribela** [comment]
Finally!

**Review by ykzts — APPROVED** [review]

**Comment by Gargron** [comment]
Your frequently used languages appear at the top.

**Comment by vasilisvg** [comment]
I was wondering what the output is of this select. When I select Dutch, for instance, I would expect the `lang=nl` attribute to appear on the `<article>` tag that displays the post. This would indeed be very handy for people who use screen readers. But, as far as I can tell, this attribute doesn't appear in the HTML. Or is there another reason to use this select?

**Comment by Mart-Bogdan** [comment]
Wow. That's so great. I've started using Mastodon recently. And I thought this was old feture. But it was jsut added. And I really like this feature.

Thank you for making it possible.

**Pull request merged**
