### PR TITLE
Remove procps from Dockerfile

### PR DESCRIPTION
**Pull request by sinoru**
Remove `procps`(for `ps`) from `Dockerfile` and uses `bundle exec sidekiqmon processes` instead of `ps`.
This will remove unnecessary package installs on Docker, and health monitoring will be more accurate than `ps`.

### CODE REVIEW

**Comment by sinoru** [comment]
Rebased for fixing lint issue.

**Comment by lifeofguenter** [comment]
Won’t this make container also unhealthy on intermittent external issues? How much are we really saving with removing ps?

**Comment by sinoru** [comment]
> Won’t this make container also unhealthy on intermittent external issues?

Can be by redis connection problem, but this should be handled as unhealthy I think.

> How much are we really saving with removing ps?

I need to check it. But, I think it's better to remove packages that are not needed as much as possible.

**Comment by sinoru** [comment]
Based on f5778caa:

with-procps 1230.47MB
without-procps 1229.45MB (- 1.02MB)

**Pull request closed without merging**
