### PR TITLE
[WIP] Close modal by pressing navigating back

### LINKED ISSUE #3060: Android back button does not work on media overlay
STR:
* open mastodon UI on mobile
* switch to one of the timelines
* open the media attachment on a toot
* press Android device `<back>` button

Expected:
* media overlay closes and I am back on the timeline underneath

Actual:
* media overlay stays open
* timeline *underneath* goes back one step (to the previously visited column/page)

--> I suspect this can be fixed with a `pushState()` for the overlay state, so that the "back" behavior takes us to the timeline again.

Dismissing the overlay in any other way would then have to `popState()` too of course.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Closes #3060.

### CODE REVIEW

**Comment by sorin-davidoi** [comment]
While this work, I don't think it is a good solution (feels like a hack). The best way to go seems to be for the modals (and their content) to have their own routes.

**Comment by penduin** [comment]
...Is the verdict that this needs to be done in a specific way?  Is this still in the works?  I would love to use the main web client on mobile, but my brain is incompatible with the modal behaviour; hitting the back button when an image is being shown keeps the image up while navigation happens underneath.  Super confusing.  And I can't seem to train myself to hunt for a subtle "X" near the top of the display.

I'm happy to dig in and try to figure it out myself, but I'm not likely to come up with the "correct" or "clean" solution.  :^)  I very much want back-to-close-modals though.

**Comment by Gargron** [comment]
Hey, this doesn't look too bad to me. And it would be a very good addition, even I hit back on modals on mobile even though I should know better. Didn't see this until now

**Comment by yuntan** [comment]
Hi folks, is there any progress on the topic? I think this feature is essential to improve mobile experience of mastodon web. cc @Gargron @sorin-davidoi

**Comment by sorin-davidoi** [comment]
Not from my end.

**Comment by Gargron** [comment]
I can't reopen this PR because the branch has been deleted.

**Pull request closed without merging**
