### PR TITLE
[WIP] fix(status_list): Hide column header when scrolling down

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Collapses the header to make more space for the actual content. This is very poorly implemented right now, opened the PR to see if there is interest in this feature.

### CODE REVIEW

**Comment by DJSundog** [comment]
I'm generally not a fan of UI chrome that hides as a side effect of another UI interaction, but I think lots of folks like this, so my only request would be yet another toggle in the app settings allowing the end user to disable this functionality should it be implemented.

**Comment by Gargron** [comment]
I am against this change, the header gives a quick scroll-to-top link as well as the context of what you are scrolling through.

**Comment by sorin-davidoi** [comment]
Context is given by the tabs, but fair point - the scroll-to-top link disappears.

**Comment by rysiekpl** [comment]
Scroll to top could be placed somewhere else, screen real estate is very valuable on mobile.

**Comment by sorin-davidoi** [comment]
Perhaps I should have specified that this would only be enabled for specific media queries (`max-width: 600px; max-height: 800px` or whatever makes sense).

**Comment by tomfhowe** [comment]
What about just shrinking it? The font could get smaller, the padding could decrease? On most tabs it feels like a big waste of space... Also I had no idea it was a back to top link until now... maybe an actual back to top button that appears when you start scrolling up could be more obvious?

**Comment by tomfhowe** [comment]
The thing with scrolling back to the top is like I always used the tab buttons at the top to do that

**Comment by sorin-davidoi** [comment]
I'll leave it open for visibility, perhaps it will lead to a better solution.

**Comment by beatrix-bitrot** [comment]
Yeah if scroll to top is still possible even when the column head is hidden then I think it's ok?

**Comment by akihikodaki** [comment]
I think `*` (Getting Started button) could be replaced with the icon according to the content if the content is not listed in the navigation.
Users can still go to Getting Started column by clicking "Back" button shown on the column head. (Though that is less intuitive for the single-column layout, that is a different topic.)

**Pull request closed without merging**
