### PR TITLE
Update schema to reflect full `db:migrate` run results

### PR DESCRIPTION
**Pull request by mjankowski**
This includes two changes:

- First commit is an order change due to migrations
- Second is a change (seems like between PG 15 and 16) in how the view sql gets dumped to schema rb -- assuming the bulk of devs are on PG16 I think this is useful, and while the sql does change - it changes in a logically equivalent way and old servers are not going to run the old migrations. The changes here are closer to the source view sql as well.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]
I'm not exactly sure how the ordering has been messed up, but it's nothing new, and was already like that from at least v3.5. I see no issue whatsoever to this change.

The view thing seems tied to the PostgreSQL version indeed, which is very annoying, but considering most of the developers are using PostgreSQL 16 in their development environment, it seems best to accept this change indeed.

**Comment by oneiros** [comment]
I just ran a migration and it restored the old order :confused: 

I am not sure it is worth reverting this, as I could rebuild my development database if it really bothered me, but I am also not entirely sure what the motivation for this change was.

Please note that you are not expected to ever run the full migrations from scratch, especially with long-lived projects. See https://guides.rubyonrails.org/active_record_migrations.html#what-are-schema-files-for-questionmark

**Comment by mjankowski** [comment]
> I just ran a migration and it restored the old order 😕

Which portion did it restore? Timestamp columns? View sql? What PG version are you on?

> Please note that you are not expected to ever run the full migrations from scratch, especially with long-lived projects. See https://guides.rubyonrails.org/active_record_migrations.html#what-are-schema-files-for-questionmark

Agreed, and we attempted to make some headway on that - tons of background in https://github.com/mastodon/mastodon/pull/27514 and https://github.com/mastodon/mastodon/pull/27591 - and sort of landed on a policy of "since we've decided to support arbitrarily old update paths, we should preserve/maintain/lint/refactor/improve/etc our old migrations" - despite this generally speaking being somewhat of an anti-pattern.

The motivation here is to just reduce the diff when you make unrelated changes.

**Comment by oneiros** [comment]
> Which portion did it restore? Timestamp columns? View sql? What PG version are you on?

The order of the columns _and_ the view SQL. I did not mention the latter on purpose, as I am on PG 14 and agree that we can optimize for 16 here. 

But I do not believe the order of columns depends on the PG version, or does it?

**Comment by ClearlyClaire** [comment]
> But I do not believe the order of columns depends on the PG version, or does it?

No, I don't think so. It's probably more dependent on when you loaded the database schema. I think for development environments, we can expect it to reload from the schema more often, I suppose.

**Comment by mjankowski** [comment]
> The order of the columns _and_ the view SQL. I did not mention the latter on purpose, as I am on PG 14 and agree that we can optimize for 16 here.

Hmm...

- On all of PG 14/15/16 when I do a full drop/create/migrate I get no changes to the timestamp columns (that is to say, running on main with this PR in place, no changes happen)
- On 14/15 I see the old-style (ie, with `t0...` in view sql) in that portion, but on 16 I see no changes (again, after this PR is in) in the views dump portion

> But I do not believe the order of columns depends on the PG version, or does it?

I don't think so ... I'd have to dig deeper to know for sure, but my guess would be that, despite the migration versioning being in place, there was a change in how rails dumped the columns at some point (in this particular case, the timestamp columns for `ip_blocks` are added in a `[5.2]` era migration, and the timestamps are the last thing added in that migration, but they were (prior to this change) not the last thing in the schema table block). This may also be related to the introduction of versioning not just on migrations, but on the schema as well ... I'd have to dig more on that too, but I'm sort of content to assume it's vaguely something in that direction.

**Pull request merged**
