### PR TITLE
Change S2S POST/GET Content-Type to match ActivityPub spec

### LINKED ISSUE #22720: [ActivityPub] MUST use ld+json for S2S POST/GET
### Steps to reproduce the problem

https://github.com/mastodon/mastodon/blob/b1a48e05b6b24a1ae37b9bcbc6f767c949ff3d79/app/workers/activitypub/delivery_worker.rb#L13

### Expected behaviour

`Content-Type: application/ld+json; profile="https://www.w3.org/ns/activitystreams"`

### Actual behaviour

`Content-Type: application/activity+json`

### Detailed description

ActivityPub section 7:

> POST requests (eg. to the inbox) MUST be made with a Content-Type of application/ld+json; profile="https://www.w3.org/ns/activitystreams" and GET requests (see also [3.2 Retrieving objects](https://www.w3.org/TR/activitypub/#retrieving-objects)) with an Accept header of application/ld+json; profile="https://www.w3.org/ns/activitystreams".

> Servers SHOULD interpret a Content-Type or Accept header of application/activity+json as equivalent to application/ld+json; profile="https://www.w3.org/ns/activitystreams" for server-to-server interactions.

I'm not sure if Mastodon can handle ld+json for incoming activities, but it should be able to as this is a harder requirement than supporting incoming activity+json.

### Specifications

main

### PR DESCRIPTION
**Pull request by trwnh**
Fix #22720

- Request types changed to ld+json per ActivityPub requirement
- Response types kept as activity+json per ActivityStreams-Core description

### CODE REVIEW

**Comment by trwnh** [comment]
The linter is failing on code I didn't change... should I fix the errors anyway?

**Comment by nightpool** [comment]
This PR does not add any content types, and only removes them.  Therefore I don't think it's required for spec compliance and I don't think it'll have a positive impact on federation. If you do think removing Accept content types is important for federation, please explain why

**Comment by trwnh** [comment]
The motivation is that ActivityPub says you MUST use ld+json for S2S POST and GET, while activity+json is only a SHOULD be equivalent. It is therefore possible (and valid) for an ActivityPub implementation to exist where activity+json is not supported for S2S requests.

**Comment by silverpill** [comment]
@nightpool Incorrect Accept header is a big problem. Developers adjust their implementations to match Mastodon behavior and we end up with this:

- https://github.com/writefreely/writefreely/issues/564
- https://github.com/owncast/owncast/issues/1827
- https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/2021
- https://github.com/NicolasConstant/BirdsiteLive/issues/129

(an incomplete list)

Anyone who begins implementing ActivityPub server according to the spec quickly finds that almost all Fediverse platforms are not spec-conformant because

>The client MUST specify an Accept header with the application/ld+json; profile="https://www.w3.org/ns/activitystreams" media type in order to retrieve the activity.

**Pull request closed without merging**
