### PR TITLE
Add consistent interpolations check to CircleCI

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Comment by nightpool** [comment]
Can we also follow up with a check for #8554 ?

**Comment by Gargron** [comment]
@nightpool I wish, but that would take a completely separate command being implemented in i18n-tasks.

**Review by nightpool — APPROVED** [review]
approved when tests pass

maybe we need a MB translation though?

**Review by renatolond — COMMENTED** [review]
For pt br:
```
diff --git a/config/locales/devise.pt-BR.yml b/config/locales/devise.pt-BR.yml
index 5f47bc901..051329c20 100644
--- a/config/locales/devise.pt-BR.yml
+++ b/config/locales/devise.pt-BR.yml
@@ -20,7 +20,7 @@ pt-BR:
         action: Verificar endereço de e-mail
         explanation: Você criou uma conta em %{host} com esse endereço de e-mail. Você está a um clique de ativá-la. Se não foi você, por favor ignore esse e-mail.
         extra_html: Por favor confira também <a href="%{terms_path}">as regras da instância</a> e <a href="%{policy_path}">nossos termos de serviço</a>.
-        subject: 'Mastodon: Instruções de confirmação'
+        subject: 'Mastodon: Instruções de confirmação para %{instance}'
         title: Verifique o endereço de e-mail
       email_changed:
         explanation: 'O e-mail associado à sua conta será mudado para:'
```

**Pull request merged**
