### PR TITLE
Fix #21492 Add missing WebP hint in avatar/header localizations

### LINKED ISSUE #21492: Allow WebP images as Avatars
### Pitch

I think we should be able to use WebP images as avatars.

### Motivation

WebP images are already supported in toots.  The lossless mode of WebP offers significantly better compression than PNG on the same kinds of images, which would allow us to have more detailed avatars without increasing bandwidth demands.  WebP is already [supported in all major browsers](https://caniuse.com/webp).

### PR DESCRIPTION
**Pull request by pauloxnet**
Fix issue #21492

### CODE REVIEW

**Comment by ykzts** [comment]
Do not change anything other than en.yml to avoid conflicts with changes in Crowdin.

**Comment by pauloxnet** [comment]
> Do not change anything other than en.yml to avoid conflicts with changes in Crowdin.

Being a trivial change, I updated all the translations, but I'm going to remove all the changes except the `en.yml` file as you requested.

**Review by ykzts — DISMISSED** [review]

**Comment by mjankowski** [comment]
Can you rebase this?

**Comment by pauloxnet** [comment]
> Can you rebase this?

Done. Can you unlock the workflow?

**Review by mjankowski — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
