### PR TITLE
Fix posix-spawn to version 0.3.12

### LINKED ISSUE #7453: posix-spawn 0.3.13 causes build error in x86
cf. https://github.com/rtomayko/posix-spawn/issues/78

We migit as well fix the version to 0.3.12 or use master branch for workaround in Mastodon release.
I adopted the former method for my instances: https://js4.in/repo/gitweb.cgi?p=v6don;a=commitdiff;h=a50c459b8d234ee428dd022fe5f65af20ee7ae6a;hp=f798f52658c5aafc788102090e3c65ece2b6f4b7

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by hcmiya**
Because 0.3.13 causes build error in x86 or other ILP32 environments.
closes #7453

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Unfortunately this is spamming all logs with

>.../vendor/bundle/ruby/2.5.0/gems/posix-spawn-0.3.12/lib/posix/spawn.rb:467: warning: constant ::Fixnum is deprecated

**Comment by Gargron** [comment]
Last activity in posix-spawn was in Dec 2017. I suppose it's not worth installing this gem at all.

**Comment by hcmiya** [comment]
Of course, it is best to release posix-spawn as 0.3.14...

**Comment by Gargron** [comment]
Yes please! Although: last activity on the gem seems to be in Dec 2017, 5 months ago. Not sure why the fix hasn't been released for all that time.

**Pull request merged**
