### PR TITLE
add Mathjax support in your toots to enjoy pretty mathematical formulae in toots

### PR DESCRIPTION
**Pull request by mokjpn**
Using 'mathjax-rails' gem, every mastodon toots can contain beautiful mathematical formulae inside.
This PR has some of small codes to include mathjax-rails gem and apply that only when you write #math hashtag in your toots. I used setInterval() javascript to make new #math toots rendered periodically. 

Example screenshot:
https://m.okadajp.org/system/media_attachments/files/000/000/065/original/ba49c476fce42601.png?1492705908

One of Japanese mastodon community enjoyed this feature so much. They even innovated many new smileys using mathematical signs and fonts. The ideas of this PR were given from @EzoeRyou@friends.nico , @h_okumura@mstdn.jp , and other many community members.

### CODE REVIEW

**Comment by jemus42** [comment]
Love the idea, but slightly concerned about performance, especially on instances (or just long threads) with a bunch of math on them.  

Maybe this could be expanded to KaTeX, which can use server-side processing, which then could be a setting for instance admins to opt-in to?

**Comment by badosu** [comment]
Mathjax is [shutting down it's CDN](https://www.mathjax.org/cdn-shutting-down/).

It would be good to check if this is covered before merging, if this PR gets approved. So far it seems that the last update to this gem was made on Mar/2016.

**Comment by mokjpn** [comment]
I agree this implementation might affect performance on client due to setInterval().
I found another implementation that hooks MutationObserver. This would be nice but I do not tried on my instance yet.

http://qiita.com/DUxCA/items/766415eeb7b1cb330543

**Comment by Gargron** [comment]
I am not sure if the main repository should include support for MathJax..? It's cool, but very specialized.

**Comment by mokjpn** [comment]
I proposed this, because MathJax support is relatively easy to implement and allows users wide range of  text representation. But it have not attracted many developers in weeks. I would like to close this.

**Comment by nikolay** [comment]
@Gargron Except that Math is the roots of each and every department of science.

**Pull request closed without merging**
