### PR TITLE
Fix helm postgresql secret

### PR DESCRIPTION
**Pull request by deepy**
There's been a few fixes for this already #19537 #19504 #19502

These unfortunately switched to using the postgres admin user which is not needed, and by changing the keys it also ties this chart heavily to the bitnami postgres chart and breaks compatibility with the popular zalando postgres operator.

This reverts those and corrects the initial issue which was that the default username in `values.yaml` was the admin user (`postgresql`, now defaulting to `mastodon`).

This can be tested with the following `local.yml` (shamelessly copied from one of the PRs I'm reverting 😈)

```yaml
mastodon:
  createAdmin:
    enabled: true
    username: helmadmin
    email: admin@myexample.com
  local_domain: example.com
  web_domain: mastodon.example.com
  persistence:
    assets:
      accessMode: ReadWriteMany
      resources:
        requests:
          storage: 10Gi
    system:
      accessMode: ReadWriteMany
      resources:
        requests:
          storage: 10Gi
  smtp:
    auth_method: plain
    delivery_method: smtp
    enable_starttls_auto: true
    port: 587
    server: mail.example
    login: admin
    password: password
    from_address: matodon@example.com
  secrets:
    secret_key_base: secretbase
    otp_secret:  otpsecret
    vapid:
      private_key: secret
      public_key: notsecret
elasticsearch:
  enabled: false
ingress:
  annotations:
  tls:
  hosts:
  - host: mastodon.example.com
    paths:
    - path: '/'
postgresql:
  auth:
     password: postgrespassword
  primary:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
redis:
  password: secret
```

And this brings up a healthy instance:

```
NAME                                  READY   STATUS    RESTARTS       AGE
mastodon-postgresql-0                 1/1     Running   0              9m15s
mastodon-redis-master-0               1/1     Running   0              9m15s
mastodon-redis-replicas-0             1/1     Running   0              9m15s
mastodon-redis-replicas-1             1/1     Running   0              8m29s
mastodon-redis-replicas-2             1/1     Running   0              8m7s
mastodon-sidekiq-6bb495bdbd-czs48     1/1     Running   2 (9m4s ago)   9m15s
mastodon-streaming-564d78674f-krsgq   1/1     Running   0              9m15s
mastodon-web-7774876555-8x7kp         1/1     Running   2 (9m ago)     9m15s
```

### CODE REVIEW

**Comment by deepy** [comment]
Why is the postgresql 11 chart installing postgres 14?

**Comment by deepy** [comment]
This isn't working when testing with just installing the bitnami chart either, despite following their documentation

**Comment by deepy** [comment]
Ah nope, this *does* work. I just had a lingering `PersistentVolumeClaim` with old data as helm uninstall doesn't remove postgresql data 🤦‍♀️

**Comment by ykzts** [comment]
cc @pbzweihander

**Comment by deepy** [comment]
Note, if you've setup with the current version of the helm chart you're going to have to adjust the `username` to match your current one (postgres iirc)

**Comment by dunn** [comment]
works for me!

**Comment by dunn** [comment]
does the change to the secret key necessitate a major version bump to the chart, though?

**Comment by deepy** [comment]
major-wise it should be on the same level as after #18941, but all of this is coming because I missed changing one thing in `values.yaml` back then.
I don't think a major version bump is needed but instructions for upgrading those who have installed it after #19537 (and possibly before #18941) should set `postgresql.auth.username` to `postgres` and both `postgresql.auth.password` and `postgresql.auth.postgresPassword` to the same value

**Review by Gargron — APPROVED** [review]

**Pull request merged**
