### PR TITLE
Croatian translation - updated 

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Review by ykzts — DISMISSED** [review]

**Comment by Gargron** [comment]
There are conflicts (somehow).

**Review by nightpool — DISMISSED** [review]
needs review from another croatian translator/user.

**Comment by diomed** [comment]
I either need some serious help in resolving conflicts from you guys,
or I'm just gonna close this one and make new PR.

**Comment by ykzts** [comment]
@diomed It would be nice to delete the branch once and then pull the new upstream master branch.

**Comment by akihikodaki** [comment]
If you are really stuck at the issue, then close this and open another. That is fine.

**Comment by ykzts** [comment]
@diomed I resolved conflicts. Is this okay with this change?

@nightpool Currently only @diomed translates this locale.

**Comment by diomed** [comment]
yeah, I think it's all right. if something'll be off I'll just fix it in next commit. thanks for resolving. 
I constantly kept forgetting to close this :D and now it's fixed. I appreciate it.

**Review by ykzts — APPROVED** [review]

**Pull request merged**
