### PR TITLE
Bump version to v4.1.3

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Review by renchap — APPROVED** [review]

**Comment by renchap** [comment]
We will publish advisories in a few hours, once all the docker images have been built.

**Comment by hinricht** [comment]
> once all the docker images have been built.

I'm watching the container image build job (https://github.com/mastodon/mastodon/actions/runs/5475911427/jobs/9972682294)  which is running for over an hour now, is this expected ? I hope it's not stuck in any way, how long does it usually take ?

**Comment by renchap** [comment]
It is expected, we will work on improving our Docker build performance soon. It should not take very long now, it takes < 2 hours usually.

**Comment by kudos** [comment]
The `latest` tag on both Docker Hub and ghcr points to `v3.5.9`. That seems unintended to me, but `v4.1.3` is still missing and maybe it'll update then. Still probably undesired behaviour for it to point to an older major even temporarily.

**Comment by hinricht** [comment]
Same, still waiting for the v4.1.3 tag. Wonder why that is given the image build job is finished. 
@renchap  Any manual actions needed ?

**Comment by renchap** [comment]
v4.1.3 image is still building, this one is much slower than the others.

The `latest` tag is a mistake and we will need to fix it. But you should never use `latest`, always use a specific version tag.

**Comment by ClearlyClaire** [comment]
Images have all been built and security advisories published! More details will follow in a few weeks when people have gotten the time to update

**Comment by mackuba** [comment]
Hey, where can I find the security advisories?

**Comment by ruffy91** [comment]
> Hey, where can I find the security advisories?

Try it on the security page: https://github.com/mastodon/mastodon/security

**Pull request merged**
