### PR TITLE
helm: add option for external db

### PR DESCRIPTION
**Pull request by dunn**
When migrating an existing instance into K8s I found it easier to create the PSQL deployment first and separately, then hook it up to Mastodon.

cc @orangewolf on whether this is the best approach.

### CODE REVIEW

**Comment by Gargron** [comment]
Did this turn out to not be needed? I can’t really make the calls with helm stuff so i was hoping the person you tagged would chime in

**Comment by dunn** [comment]
Yeah, I think it was the wrong approach.

**Comment by synth3tk** [comment]
Is there an update on allowing external DBs? I'm having a hard time getting this working with the embedded chart, whereas I have an unrelated instance working just fine standalone. It'd be nice to just reuse my existing work than to troubleshoot this one.

**Comment by dunn** [comment]
@synth3tk i closed this because i figured a better solution would be an optional Job to import a db dump, but if you also went the external db route then maybe it's worth supporting; @orangewolf thoughts?

**Comment by synth3tk** [comment]
I haven't gone the external route yet, but I'll probably pull this PR and use it. My issue is that I'm using the nfs-client provisioner and my NAS is stubborn with permissions. Using a standalone database for Harbor allowed me to run it just fine. I'd like to do the same thing with Mastodon.

**Comment by dalehenries** [comment]
My team and I would like to use and external database. I forked the repo, modified the chart to work with an external db, and stood up and instance to test.  Everything seems to be working fine. I was about to create a PR for it, when I noticed this one. My implementation is very similar to yours, so I was wondering if you would still be open to merging this. 

After we have a solution for the external database, my team is looking at adding S3 support.

**Pull request closed without merging**
