### PR TITLE
Redesign public profiles

### PR DESCRIPTION
**Pull request by Gargron**
Functional changes:

- Public profiles now display only public/unlisted toots, regardless of access control
- By default, replies are filtered out
- "With replies" option to include them again
- "Media" option to display only toots with media attachments
- "Posts" renamed to "toots" on public profiles

Visual changes:

image

Mobile view:

screen shot 2017-08-16 at 16 43 12
screen shot 2017-08-16 at 16 43 18

Followers/following cards:

image

### CODE REVIEW

**Comment by m4sk1n** [comment]
How does it look on mobile devices?

**Comment by PaulFree14** [comment]
yes! I really like to have the "toots" and "toots with replies".

**Comment by mabkenar** [comment]
Now that you are at it, would you please make sure #2588 is taken care of? Thanks for the great work you do!

**Review by ykzts — APPROVED** [review]
looks good! I like this.

**Comment by ZiiX** [comment]
There have been requests to allow a user to set their default 'landing' view of others. For example, only show their toots (without boosts OR replies) as well as other wanted an option to default to land with their media toots only. SO that their mastodon profile is essentially all their forward-facing content.
This looks amazing though. I'm more of a fan of a centered background + profile but this is growing on me.

**Pull request merged**
