### PR TITLE
Wrong count in response when removing favourite/reblog

### PR DESCRIPTION
**Pull request by c960657**
When favouriting or reblogging a status, the `favourite_count`/`reblogs_count` field in the response to the POST request is incremented to the reflect the updated count. But when deleting the favourite/reblog, the count in the response has not been decremented.

We do have tests for this, but they pass, because we run all tests with the `Sidekiq::Testing.inline!` strategy. In production, the counts are updated asynchronously by `UnfavouriteWorker` and `RemovalWorker` _after_ the POST request has finished.

This PR uses the existing `StatusRelationshipsPresenter` mechanism to pass an overridden count to the REST serializer.

Handling this server-side removes the need for manually decrementing the count client-side. This allows us to handle favourite/unfavourite in a symmetric fashion client-side, and likewise for the other status bar actions, reblog/unreblog and bookmark/unbookmark. Currently some of them wait for `xxx_SUCCESS` and others do not.

### CODE REVIEW

**Comment by c960657** [comment]
Question:
The check for `action.status.get('id')) === undefined` was added in #9272. I don't understand how that can prevent the app from crashing. Why does the app crash when `id` is missing (I would assume it just adds a dummy status to the state with the key `"undefined"`), and how was an action with an invalid status dispatched in the first place?

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

**Comment by c960657** [comment]
> But you missed a parenthesis

Ah, yes, that explains a bit :-) Thank you for explaining. It would be cool if Immutable.js supported some kind of conditional operation, e.g. `setInIfExists`.

**Review by ClearlyClaire — COMMENTED** [review]
I am tentatively for this change as it's a bugfix, but it's also a breaking API change. Third-party apps will have incorrect counts if they decrement it themselves.

**Comment by c960657** [comment]
I have rerequested review just to clear the “changes requested” flag (I did address that request already).

**Review by ClearlyClaire — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me! Sorry it took so long to get merged!

**Review by rapidocuento — APPROVED** [review]

**Pull request merged**
