### PR TITLE
Remove trending hashtags

### PR DESCRIPTION
**Pull request by Gargron**
https://github.com/tootsuite/mastodon/issues/7702#issuecomment-394100570

### CODE REVIEW

**Comment by Thann** [comment]
I feel like this is reason enough to keep the index =[
screenshot from 2018-06-02 12-40-51

**Comment by Thann** [comment]
I'd like to suggest optionally sorting the search results by "popularity" but I fear starting another shitstorm ^.^

**Comment by Gargron** [comment]
I doubt that would be considered bad by anyone but since usage & trends are in redis, I can't use them to sort results coming from postgres without a lot of overhead. It would require changing some code.

**Comment by koyuawsmbrtn** [comment]
delet dis

**Comment by remram44** [comment]
Is the absence of spam from supporters of the feature on #7702 taken as non-support? 🙁 Removing the list from plain sight while other solutions are still available to get it (even for non-tech people!) seems like the worst of both worlds.

**Comment by mal0ki** [comment]
> The usage stats for the search results remain.

Will it also order them according to this? Instead of alphabetical? 

It's a good feature, and probably the better part of the original implementation. I'm glad you considered keeping it as part of a compromise.

**Comment by jebuskrust** [comment]
Strawpoll

**Pull request merged**
