### PR TITLE
Improve `robots.txt`

### PR DESCRIPTION
**Pull request by jhp0tter**
https://www.wired.com/2010/08/robot-laws

### CODE REVIEW

**Review by antimundo — COMMENTED** [review]
I don't see the need to explain the joke about the file name. I think it's best to keep it simple and not include unnecesary code.

**Comment by jhp0tter** [comment]
I do not know how to use Git.

**Comment by jhp0tter** [comment]
@PabloRubio21 @JMCQ87 Done :+1:

**Comment by ClearlyClaire** [comment]
Sorry, I don't think that's especially useful.

**Pull request closed without merging**
