### PR TITLE
Change public-facing UI to be the same as logged-in UI

### PR DESCRIPTION
**Pull request by Gargron**
:warning: **Work in progress**

This is a huge one. Having two UIs has always been a maintenance liability, but I've also received feedback from new users who were confused about the UX differences (e.g. not being able to click on the *body* of a post to open it on the public version because it's mostly a static page and not a rich application). I think it's a good idea to unify them. (Not to mention that one of the oldest complaints about Mastodon has been that you can't see the UI until you're logged in though we have sort of addressed that over time by adding a public version of the public timeline)

The changes include a new REST API that allows finding an account by its `acct` instead of `id` to support the adoption of previously public-facing URLs (like `/@username/123`) into the main web app, the removal of the `/web` prefix from the main web app, and renaming of web app routes that had public-facing equivalents into those versions, e.g. `/timelines/tag/foo` becomes `/tags/foo`.

Before the PR is done, the web app will need to become aware of when there is no logged in user to avoid sending API requests and show different navigation.

### CODE REVIEW

**Comment by ThibG** [comment]
As I said more privately, I'm not really in favor of this change, for two main reasons:
- JS-less pages are useful for a wide variety of reasons, it would be a shame to not have them anymore
- while I understand the desire for a more unified experience, I'm afraid this would make it even more confusing when users will land on a remote instance and not understand why they can't interact as they do on their own instance

**Comment by Gargron** [comment]
> JS-less pages are useful for a wide variety of reasons, it would be a shame to not have them anymore

Can you list some of the reasons? Programmatic uses did not rely on HTML, search engine indexing renders JS nowadays, people who disable JS in their browser are a minority. I get that rendering a self-contained HTML representation for every ActivityPub resource felt nice from a purist viewpoint but I highly doubt that the majority of our userbase cares or even knows about it so if it weights us down it should go.

> I'm afraid this would make it even more confusing when users will land on a remote instance and not understand why they can't interact as they do on their own instance

Well, right now they also get confused when they land *on their own* instance from a permalink and the UI doesn't work as expected. I don't see how a unified UX would make it worse. We can just as well integrate remote interaction dialogs into the main application when there is no logged in user, perhaps making it a smoother experience.

**Comment by Admicos** [comment]
I'd like to chime in as an end-user against requiring JS for viewing posts when logged out. I'd assume some kind of server-side rendering would be helpful to have the best of both worlds. (Aside from the JS issue, I'm totally behind this change)

Aside from just logged-out onlookers, those pages also have the advantage of listing all known replies/parents of a post. This is very important for small (possibly single-user) instances, as Mastodon seems to (in my experience, anyway) not consistently federate replies and parents of a thread. So, if a user from a small instance wishes to read through the entire conversation, they have to view the posts through the logged-out interface of the post's logged-out page. (Or miss out on possibly important parts of said conversation)

And since Mastodon can be hosted on various different domains, anybody selectively allowing JS would have to do the dance of going to the page, realize it requires JS, enable JS temporarily, and refresh again, which is a big usability issue and is one of my many pet peeves with Pleroma instances.

**Comment by ddolgov** [comment]
Count me in as a new user super-confused by the two interfaces. Would be great if they were unified and ultimately discussion threads on someone else's server could be opened and viewed via public interface (is it even possible now, maybe there is a PR for that?)

**Comment by Gargron** [comment]
> discussion threads on someone else's server could be opened and viewed via public interface

Do you mean viewing a thread from someone’s public profile? You gotta click on the timestamp of the post in that UI

**Comment by ddolgov** [comment]
> Do you mean viewing a thread from someone’s public profile? You gotta click on the timestamp of the post in that UI
Thanks! However, it seems I cannot see a thread unless I have an account and signed in on that host. I cannot possibly have to create account each time I want to see a discussion on other hosts. I guess this highlights the need for UI unification, unless there is a fundamental reason for that restriction

**Comment by ThibG** [comment]
> > Do you mean viewing a thread from someone’s public profile? You gotta click on the timestamp of the post in that UI
> 
> Thanks! However, it seems I cannot see a thread unless I have an account and signed in on that host. I cannot possibly have to create account each time I want to see a discussion on other hosts. I guess this highlights the need for UI unification, unless there is a fundamental reason for that restriction

Unless you are talking about private conversations, which, well, are private, threaded views for public conversations are generally public as well. In any case, unifying the UI will not change anything about that.

**Comment by Gargron** [comment]
Yeah, I think that sounds like you're browsing some alternative Mastodon frontend because ours does not require login to view public threads.

**Comment by ddolgov** [comment]
I think you are right, now it seems it works fine

**Pull request closed without merging**
