### PR TITLE
make account avatar and header image clearable

### PR DESCRIPTION
**Pull request by devkral**
This PR allows the removal of avatar and header images.
Before the way to go, was to replace the image.

### CODE REVIEW

**Comment by Sylvhem** [comment]
@devkral Can you post a screenshot of the interface here?

**Comment by MasterGroosha** [comment]
Site description (/about) needs this as well

**Comment by koyuawsmbrtn** [comment]
@MasterGroosha Well, you're able to clear the description. I would rather say the cover images...

**Comment by MasterGroosha** [comment]
@koyuawsmbrtn That's exactly what I said: cover images on `{site}/about` and `{site}/about/more`

**Comment by devkral** [comment]
democlear

sry for the delay.

**Comment by Sylvhem** [comment]
Thank you for posting it. I love the idea, but I think the execution is somehow wrong. Maybe it would be better to have a little cross in the corners of the images instead?

**Comment by sternenseemann** [comment]
This would resolve #4458. Probably useful to reference it.

**Comment by MasterGroosha** [comment]
This is still an issue...

**Comment by SuperSandro2000** [comment]
bump

**Comment by shleeable** [comment]
That huge button cannot stand. please make the tiny bin icon or something.

**Comment by sternenseemann** [comment]
I've "forked" this pull request to resolve the merge conflicts and improve the UI: #13234 

I believe this one can be closed now, since it is no longer being updated.

**Comment by sternenseemann** [comment]
Can be closed, I guess.

**Comment by nightpool** [comment]
thanks!

**Pull request closed without merging**
