### PR TITLE
Run migration tests against postgres 16 and 17 as well

### PR DESCRIPTION
**Pull request by jippi**
16 has been out quite a while and 17 has just been released

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]
Looks good but it would add ~4 minutes to the CI per PR.

**Comment by mjankowski** [comment]
> Looks good but it would add ~4 minutes to the CI per PR.

I wonder if we could get the migration test jobs to run on the norma setup-ruby config instead of our custom one? It seems like migrating and verifying data should not NEED any of the (vips, etc) things we need the custom build for, but it would be a question of could we get things to load in a way that can run w/out them and still preserve confidence.

**Comment by jippi** [comment]
> Looks good but it would add ~4 minutes to the CI per PR.

I think it would add ~4min of **cumulative** runtime, but not actually make the entire workflow / CI wait slower since a bunch of other pipelines are significantly slower

**Comment by mjankowski** [comment]
That's true for one single run at a time - but we also have a repo-wide cap on how much stuff can be done in parallel, so even if it's not the slowest portion of a given PR's CI run, the total minutes do wind up being a bottleneck (but only in times with lots of stuff merging/rebasing/etc all at same time).

That said - my pref is to include any useful coverage like this and find a better way to speed up the runs. I might take a stab at the ruby-setup idea and see if this job can be moved off the custom one onto the (must faster to setup) standard one.

**Comment by jippi** [comment]
could make the workflow conditional on specific paths being changed, containing the migrations, so they don't run for changes unrelated to DBs and/or migrations

**Comment by ClearlyClaire** [comment]
> could make the workflow conditional on specific paths being changed, containing the migrations, so they don't run for changes unrelated to DBs and/or migrations

We occasionally depend on application code in the database migrations (we try to avoid doing this for obvious reasons, but sometimes it's just orders of magnitude simpler to do it this way), so I wouldn't do that. Same with dependencies.

**Comment by mjankowski** [comment]
> I might take a stab at the ruby-setup idea and see if this job can be moved off the custom one onto the (must faster to setup) standard one.

I looked at this and remembered that I had looked at this before. In addition to vips, the idn-ruby requirement is hard to untangle. The adressable gem will detect it and use libidn if present and otherwise fallback, but the TwitterText gem was more entangled/dependent. I started to look at making that usage contingent on it being loaded, but theres a big sprawl of regexes and some monkey patching that I didnt feel good about that. If we ever migrate away from that gem into something more custom (maybe during any markdown or other formatting support work?), might be worth re-review. Might be more beneficial to continue to optimize the custom image rather than try to switch to standard one, for this run at least.

**Comment by shleeable** [comment]
PG generally supporting their releases for 5 years is wonderful, but might be worth us drawing a line somewhere.

**Pull request merged**
