### PR TITLE
Fixed move worker getting locale from remote account

### PR DESCRIPTION
**Pull request by noellabo**

### CODE REVIEW

**Comment by weex** [comment]
Seems simple enough to deal with missing data but I wonder why it would be missing. Is there an issue related to this?

**Comment by noellabo** [comment]
There are no related issues.

This is a port from Fedibird that fixes the actual error-prone worker found in sidekiq's dead jobs.

A remote account may be specified for MoveWorker. The remote account has no data in the associated user table. If you refer to this, it will be nil. I get an error because nil doesn't have a locale method.

**Comment by ClearlyClaire** [comment]
Hmmm, I actually don't understand how this could happen:
- `copy_account_notes!` only adds notes owned by accounts which already had notes
- `add_account_note_if_needed!` is only ever used with `Account.local` scope

**Review by ClearlyClaire — APPROVED** [review]
Oh, great catch! This may well be the issue I failed to diagnose a while ago when I wrote #16415

EDIT: even better might be to just return early and do nothing if `account.user` is `nil`.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
