### PR TITLE
Default to a non-animated version of oops.gif

### LINKED ISSUE #6060: Request: could the 500 page become non-blinking?
I'm sorry but I find the blinking 500 page (oops.gif) extremely annoying. Could it please be replaced by a non-blinking image? Thank you!

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #6060 

The new png is the first frame from the animated gif, with the orange bits removed since they only make sense in the animation.

screenshot_2018-12-17 this page is not correct - dev glitch social

### CODE REVIEW

**Comment by ashleyhull-versent** [comment]
image

**Comment by ashleyhull-versent** [comment]
RIP.

**Comment by koyuawsmbrtn** [comment]
What about trying to get the value from the settings saying "allow autoplay" and then animate it if the user wishes so? It's also disabled by default so it shouldn't bother anyone.

**Comment by ThibG** [comment]
I guess we could, for the non-static part. But most of the time, such pages will show up because the server itself is down, and that lookup cannot be done in such occasions.

**Comment by ThibG** [comment]
Updated the PR to respect the autoPlayGif setting when it's available (and default to the still image otherwise)

**Review by koyuawsmbrtn — APPROVED** [review]
Looks pretty good, I don't know if it's ready to merge, but I would approve it

**Review by renatolond — APPROVED** [review]

**Review by danhunsaker — APPROVED** [review]

**Comment by Kjwon15** [comment]
Noooo.... I loved that smashing friend

**Pull request closed without merging**
