### PR TITLE
Add webhook for status create

### PR DESCRIPTION
**Pull request by devsnek**
never touched rails before but this seems to do something

### CODE REVIEW

**Comment by devsnek** [comment]
@ykzts none of the lint errors seem to be on code i added, do i need to worry about it?

**Review by Gargron — CHANGES_REQUESTED** [review]

**Comment by sphinxc0re** [comment]
Any updates on this?

**Comment by ThisIsMissEm** [comment]
@Gargron I believe this is an old PR because I can see this webhook has been implemented on `main`

**Comment by devsnek** [comment]
https://github.com/mastodon/mastodon/pull/24133

**Pull request closed without merging**
