### PR TITLE
Pre-create and chown system volume in Dockerfile

### PR DESCRIPTION
**Pull request by BtbN**
Without explicitly doing this, the owner of the volume when using the provided compose file will very likely be wrong, resulting in permission issues involving writes to that directory.

### CODE REVIEW

**Comment by ineffyble** [comment]
Overlaps (and possibly conflicts or is made redundant by) #21137 and #21044.

**Comment by BtbN** [comment]
Not at all. Neither of those two PRs fix the issue that /opt/mastodon/public/system does not exist in the container (since it's in .dockerignore and initially does not even exist in the repo).
So when you then make it a volume, it'll just end up owned by either root or the userid who owns that directory on the host.
Neither of those are likely to overlap with the userid of the in-container mastodon user, so it will have no permissions to write there.

**Comment by ineffyble** [comment]
@BtbN I wasn't saying they make this unnecessary, I haven't fully checked them out. Just flagging that there's overlap and potential merge conflicts.

**Comment by ineffyble** [comment]
Generally I find it's useful for PR authors to be aware of other PRs touching the same files in similar ways (or opposite ways), to make integration smoother.

**Comment by BtbN** [comment]
Rebasing this one on those others, or vice very, should be fairly straight forward. There's almost no overlap despite them touching the same file.

**Comment by vmstan** [comment]
These changes have been incorporated with the merger of #26850 

Closing this PR, welcoming future improvements to the new version.

**Pull request closed without merging**
