### PR TITLE
Use `tt` extension for form scaffold template

### PR DESCRIPTION
**Pull request by mjankowski**
This file actually is a tt (thor template) file, not a haml file. Renaming extension will continue to work during rails generator runs, and lets use remove the entry from the haml lint exclusions.

I think that behind the scenes here, haml-rails is using the rails framework method which correctly understands/processes templates. I did a mock local run of a scaffold generator and the resulting `_form.html.haml` looks like the correctly processed version of this template (ie, same results as without the change).

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Is this something we should be bringing up to `simple_form` gem?

**Comment by mjankowski** [comment]
I think simple_form just supplies erb templates, and that this scaffold comes from haml-rails (though I'd have to double check this). My suspicions is that the relevant haml-rails code pre-dates the rails tt processing code.

**Comment by ClearlyClaire** [comment]
Looking at it, the file has been directly lifted from an older version of `simple_form`: https://github.com/heartcombo/simple_form/blob/991ca999941195ec24d8a48327df8a4b09993b5f/lib/generators/simple_form/templates/_form.html.haml

The current version uses the same templating syntax and still has the `.haml` extension: https://github.com/heartcombo/simple_form/blob/main/lib/generators/simple_form/templates/_form.html.haml

**Comment by mjankowski** [comment]
I'm not sure how maintained simple_form is. Rails itself uses `.tt` now - https://github.com/rails/rails/tree/7-1-stable/railties/lib/rails/generators/erb/scaffold/templates - but I guess the ecosystem of template/form gems is not caught up.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
