### PR TITLE
Change media modals look in web UI

### PR DESCRIPTION
**Pull request by Gargron**
image

- Change overlay background to match color of viewed image
- Add interactive reply/boost/favourite buttons to footer of modal
- Change ugly "View context" link to button among the action bar

### CODE REVIEW

**Comment by Gargron** [comment]
There's one issue that is not blocking but would be nice to solve at some point. ModalRoot restores focus on the element that had focus when the modal was opened after the modal is closed. When clicking reply, the focus should go to the textarea, but I believe the aforementioned behaviour restores the focus to the clicked media gallery item instead.

**Comment by Kjwon15** [comment]
pagination dot is useful for "how many pictures on this post". Please not remove that

**Comment by Gargron** [comment]
Hm, thanks for the feedback. The problem is that a line of dots and a line of buttons don't look good next to each other. It needs some kind of new design concept to look passable.

**Review by ykzts — APPROVED** [review]

**Comment by Gargron** [comment]
Dots restored

**Pull request merged**
