### PR TITLE
fix french translation with non-breaking spaces

### PR DESCRIPTION
**Pull request by smdgjmigop**
Hi,
I did this, I no nothing in web stuff, I hope non breakable spaces dont break any web thing

### CODE REVIEW

**Comment by ykzts** [comment]
cc @eramdam @Sylvhem @aaribaud (recent editors for fr.yml)

**Comment by nightpool** [comment]
I think this is correct, although I'm wondering if there's a better way to do it technically. &nbsp; isn't exactly right, because these translations might not all be rendered into html, but maybe there's a yml way to represent these?

should the .json files also be updated?

**Comment by aaribaud** [comment]
IIUC, this replaces narrow no-break spaces (Unicode e2 80 af) with "full-size" no-break spaces (c2 a0).

From a typographical / composition usage standpoint, this change should not be done: so-called "double punctuation" (question mark, colon, semicolon, exclamation mark) are supposed to be preceded by an "espace fine" (a narrow no-break space) in French typography, and that's what the current codebase does.

@smdgjmigop : from your commit/PR description, I _think_ you did witness cases where the space was actually broken and the punctuation rejected to the next line, and this is what prompted you to change what you saw as breaking spaces into (full-size) no-break spaces. Am I correct? If so, please describe how you witnessed it as precisely as possible (which OS, which browser or app, with versions ideally).

I'm asking this because the root cause could be in Mastodon code _or_ in a browser's (or app's) rendering engine failing to properly handle the narrow no-break spaces; being able to reproduce the issue may help directing it to the right project.

**Comment by smdgjmigop** [comment]
@aaribaud yes, you're right.  And my emacs white-space mode fooled me by showing the same glyphs for regular spaces and narrow non breaking spaces. Using hexl-mode I actually see the narrow non-break spaces (btw, thank you, I didn't knew those). I am glad my pull request wasn't blindly accepted :-)

I witnessed this on Arch Linux with firefox and chromium, and on ubuntu (17.04) with firefox.

**Comment by aaribaud** [comment]
@smdgjmigop Ok, I could act as if I were a Unicode guru, but the truth is, I just hexdumped your diff, noted the differing whitespace encodings, googled the hex byte sequences and discovered the Unicode narrow no-break space only 30 minutes before you. :innocent:

I can try and reproduce on Chromium or Firefox on my Xubuntu. What's the easiest/fastest way to cause text with a narrow no-break whitespace appear in my browser?

**Comment by smdgjmigop** [comment]
@aaribaud You can check my web designer skills : 
http://simon.archipoff.emi.u-bordeaux1.fr/narrow_space.html
:-p

**Comment by Sylvhem** [comment]
> so-called "double punctuation" (question mark, colon, semicolon, exclamation mark) are supposed to be preceded by an "espace fine" (a narrow no-break space) in French typography, and that's what the current codebase does

It does because I previously inserted narrow no-break space everywhere in this file ^^ (see #4107). But apparently, I missed some of them. Thanks @smdgjmigop for noticing!

**Comment by smdgjmigop** [comment]
@Sylvhem you're welcome, I made a mess in your work :-p
how do I retract my pull request ? can I do that ?
I'll do the bug report for the rendering problem. Those non-break spaces aren't in the final html document displayed by the web browser.

**Comment by smdgjmigop** [comment]
I made a bug report, see : https://github.com/tootsuite/mastodon/issues/4434 @aaribaud @Sylvhem @nightpool

**Comment by aaribaud** [comment]
@smdgjmigop :smile: That's enough at least to conclude that FF respects the no-break part of the narrow space but, incidentally, messes up computing the minimum required width: the colon in your page is never rejected to 2nd line (which is good), but is overflown and hidden on the right when reducing the FF width to a minimum. I'll run other tests.

But in fact that's beside the topic here, i.e. the PR itself, and should be an issue... In the right project, to be determined. I suggest we discuss it under https://github.com/smdgjmigop/mastodon/commit/a1748b25f340dcf8847eae95e7e39e08aa335242 (possibly placing an ad hoc branch on the commit and removing it from your master).

@ykzts or @nightpool, as per https://github.com/tootsuite/mastodon/pull/4404#issuecomment-318709358, @smdgjmigop agrees that this PR should be rejected.

**Comment by nightpool** [comment]
consensus is that this pull request should be closed, but can someone take the YML problem and work on it? Maybe a bug that we need to report to https://github.com/svenfuchs/i18n or https://github.com/svenfuchs/rails-i18n?

**Pull request closed without merging**
