### PR TITLE
Remove unused E2EE messaging code

### PR DESCRIPTION
**Pull request by mjankowski**
Not quite a full revert of https://github.com/mastodon/mastodon/pull/13820 - but close to it. Sort of a first pass which removes the bulk of what I think can safely be removed. There were a few areas where the underlying code changed a bit (ie, a straight revert wasn't possible) which may have room for more future refactor/cleanup after the initial attempt here.

This feature is the largest chunk of untested unused code in the app, I suspect - and (as far as I can tell) there's not an imminent plan to enable/activate it. I know there is separate work being done to formalize an AP-protocol-level E2EE standard, which we would presumably adopt if that is realized, so this is in some way prep/clean-out work in advance of that. 

If I'm wrong about this and there IS a plan to enable this feature using the current impl, there's a lot of coverage we should add in advance of that.

### CODE REVIEW

**Comment by shleeable** [comment]
The mantra wins again.

cossack-labs-dont-roll-your-crypto-gdpr-blockchain

**Comment by ThisIsMissEm** [comment]
We will need to either keep the `crypto` scope or do the database migration to quietly remove that scope from any applications, access tokens or access grants. If we remove the scope without the database migration, then I think we'll get 500 errors if we attempt to access an application using that scope.

**Comment by mjankowski** [comment]
RE: the `crypto` scope (configured via doorkeeper) - given the commented-out and disabled nature of the feature, it seems unlikely that there are purposefully created records with that scope, doesn't it? Is the concern that since it was a configured scope and there hypothetically could have been requests for that scope which were processed and saved that way, we should be conservative about handling that edge case via migration or other mitigation ... or am I missing something about the creation path and it's actually more likely to have some records?

**Comment by ThisIsMissEm** [comment]
We thought the same about the `read:me` scope which had only recently been merged, but in the month between there were many applications already using it. The `crypto` scope has existed for years, so, I'd expect there'd be at least some applications registered with it. Using the post migration should be enough:

```ruby
    Doorkeeper::Application.where("scopes LIKE '%crypto%'").in_batches do |applications|
      applications.update_all("scopes = replace(scopes, 'crypto', '')")
    end

    Doorkeeper::AccessToken.where("scopes LIKE '%crypto%'").in_batches do |access_tokens|
      access_tokens.update_all("scopes = replace(scopes, 'crypto', '')")
    end
```

Should be sufficient. Arguably we should trim whitespace, but the whitespace isn't meaningfully important.

I don't generally suggest doing `AccessGrant`s just because they're highly ephemeral, and the risk of breakage is very very minimal.

**Review by renchap — APPROVED** [review]
We decided to remove the unused E2EE code for now, as this code is unused and untested.

Adding E2EE to Mastodon is still something we could like some day, but this implementatin attempt was never conclusive. We will be following the various projects working on adding E2EE to ActivityPub, like https://github.com/swicg/activitypub-e2ee

If they end up with something that we can implement, we will see if it makes sense to add back this code for the new implementation.

**Comment by ThisIsMissEm** [comment]
@renchap fantastic news! The one thing this still absolutely needs is the migration to drop the OAuth Scopes for crypto, otherwise we'll be having errors & breakages: https://github.com/mastodon/mastodon/pull/31193#issuecomment-2263643823

**Comment by mjankowski** [comment]
Sorry, just saw this...

> We thought the same about the `read:me` scope which had only recently been merged, but in the month between there were many applications already using it. The `crypto` scope has existed for years, so, I'd expect there'd be at least some applications registered with it.

Are those cases the same though? In the case of the `read:me` scope, it was active and deployed in nightlies and running places ... so while it's reasonable to not expect it to have been super widely used, there's at least a viable path for it to have been used by whatever audience of nightly-running instances there is. Whereas in the `crypto` scope case, to the best of my understanding is has never actually been enabled anywhere? (or at least, in default unchanged non-forked deployment)

I'll add a migration here or as followup if necessary, but I still don't understand the path where it could have been used.

**Comment by ThisIsMissEm** [comment]
IMG_8150

**Comment by mjankowski** [comment]
Ah, I see ... I was thinking totally about the inbound permissions checking from the commented-out routes and couldnt see how they'd have created anything. Noted on that pathway/exposure.

I can work on that migration and either add here or as followup if this merges first.

Separately...

- That view could use a responsive once over at narrow width?
- I wonder if the "this application has a scope which the locales dont know about" could be handled more gracefully?

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
