### PR TITLE
[i18n] Occitan update

### PR DESCRIPTION
**Pull request by Quenty31**
Been busy lately but here's the spring edition :P La version prima :tulip:

### CODE REVIEW

**Comment by Quenty31** [comment]
Oh oh, I don't where to look at, to fix this =/

**Review by ykzts — APPROVED** [review]

**Comment by Quenty31** [comment]
@ykzts thanks for merging! What was blocking? So I know for later

**Comment by ykzts** [comment]
@Quenty31 remove unnecessary quotes! (85ea704255f641ed7fd739cd5a345554d7770596)

**Comment by Quenty31** [comment]
Many thanks!

**Pull request merged**
