### PR TITLE
Add list of lists component to web UI

### LINKED ISSUE #134: Support "twitter lists"
When this platform gets traction it will be really useful to be able to group users in different "lists". In general timelines are too verbose.

And to be able to continue where you left off later.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #134, follow-up to #5703, #5750

image

image

Video demonstration: https://mastodon.social/@Gargron/99118896110989062

- [x] List of lists
- [x] Create list
- [x] Edit list
- [x] Destroy list

### CODE REVIEW

**Comment by mattcoxonline** [comment]
@Gargron I just did a really quick run through of **Adding a new list** from within the List of lists column. See: https://invis.io/S6ENQXIQ5#/266083503_01_Main_UI_-_01_Added_Lists

There'll need to be an "Add to list" / Creation option tucked away on an individual user's profile somewhere, too, I guess.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Rejecting because of the `AccountSearchService` interface changes not reflected in the specs (I have a work-in-progress Pull Request for that).
Looks fine otherwise, although I'm far from a React.js expert. Have not tested it yet, but will do shortly.

**Comment by ThibG** [comment]
So, I have been testing this and have found no showstopper, but:
- The getting started menu is getting crowded and scrolling is now needed. This is annoying, especially since I also really want #4514 to be merged, and that PR also adds a menu item in the getting started menu…
- It may make sense in the list editing UI to show all followed users, in order to make it easier to populate lists.
- It may also make sense to search users while typing, not only when pressing enter.
- A list's statuses seem to also include replies from followed people in that list to people not in that list, which I'm not entirely sure is what we want.

**Comment by Wack0** [comment]
@ThibG scrolling of Getting Started was already needed when using a smaller screen (ie, 10" tablet)

**Comment by mattcoxonline** [comment]
> The getting started menu is getting crowded and scrolling is now needed. This is annoying, especially since I also really want #4514 to be merged, and that PR also adds a menu item in the getting started menu…

Might be a suggestion to remove "Muted users" and "Blocked users" from that navigation and hide the option away somewhere under settings or preferences. Is it really a priority to show users you've explicitly hidden?

**Comment by ThibG** [comment]
Hm, I've stumbled upon a bug: I've been adding a bunch of empty lists, and for some reason, the fourth one gets replaced by whatever list I create next. The javascript part stops sending POST requests and instead sends PUT requests changing the last list.

**Comment by ThibG** [comment]
Tried the latest changes, and at least one of the issues I reported is fixed. I also didn't experience a new list creation replacing another one, but I did experience another issue: when adding and removing numerous lists, server and client became out of sync at some point, with a list existing client-side but not server-side. Attempting to delete this list would 404 and not remove it on the client's side. (Of course, refreshing the page would fix it)

**Comment by Gargron** [comment]
>with a list existing client-side but not server-side

I don't feel like that is a problem, if you edit the state concurrently from multiple browsers there's no way by which it would sync without refreshing the page, that isn't new.

I have addressed all issues please approve

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
