### PR TITLE
Rename Image component to ServerHeroImage

### PR DESCRIPTION
**Pull request by takayamaki**
This PR renames Image component to ServerHeroImage.

This component is only used in ServerBanner and About.
However, this component is named Image. It is too generic.

### CODE REVIEW

**Comment by takayamaki** [comment]
duprecate with https://github.com/mastodon/mastodon/pull/24893 .
I comvert this PR to draft.

**Comment by renchap** [comment]
#24893 has been merged, should we close this PR?

**Comment by takayamaki** [comment]
> #24893 has been merged, should we close this PR?

I seems that name of this component is still too generic.
Therefore, I have rewritten it to a pull request that simply renames it.

**Review by renchap — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
