### PR TITLE
Simplify the test script

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Gargron** [comment]
>6699

Nice!

But I don't mind seeing at a glance which commands are going to be run instead of a wildcard...

**Comment by ykzts** [comment]
Unfortunately if you use wildcards, the order of run will be changed. You should run Jest after lint.

**Comment by Gargron** [comment]
Alright, I'm going to decline this PR, sorry.

**Comment by imncls** [comment]
no worries~!

**Pull request closed without merging**
