### PR TITLE
Enable webm tests in API media controller

### PR DESCRIPTION
**Pull request by jackjennings**
These tests were pending, but it was unclear to me why. The git blame suggests this might have been a mistake, as the enabled tests pass for me.

### CODE REVIEW

**Comment by Gargron** [comment]
They were disabled because they take super long comparatively, because webm files are large

**Comment by jackjennings** [comment]
Should a shorter webm clip be used as a fixture?

**Comment by jackjennings** [comment]
Or `MediaAttachment` could be stubbed.

**Comment by mjankowski** [comment]
We should stub out all the paperclip/imagemagick interactions, so that `identify` and `convert` are not actually executed in specs. Should be sufficient to speed up.

**Comment by jackjennings** [comment]
Sounds potentially dangerous to do globally—maybe some kind of opt-in per spec? I'm not familiar enough with RSpec to know what the options might be or if there is a standard way to do so.

**Comment by Gargron** [comment]
Tests run for a long time already, don't want to make them run even longer. Sorry.

**Pull request closed without merging**
