### PR TITLE
Fix `application_id` erroneous inclusion in `ScheduledStatusSerializer`

### LINKED ISSUE #21777: API: ScheduledStatus serializer returns application ID (as integer)
### Steps to reproduce the problem

GET /api/v1/scheduled_statuses or POST /api/v1/statuses?scheduled_at=...&...

### Expected behaviour

application ID is returned as a string or not at all

### Actual behaviour

application ID is returned as an integer

### Detailed description

https://github.com/mastodon/mastodon/blob/cec1e902e006730f68bde0a4334e5b819a12a475/app/serializers/rest/scheduled_status_serializer.rb#L13

The line above implies that the application_id should not be returned, but it is:

```json
{
    "id": "1",
    "scheduled_at": "2022-11-30T00:00:00.000Z",
    "params": {
        "text": "test post",
        "media_ids": null,
        "sensitive": null,
        "spoiler_text": null,
        "visibility": null,
        "language": null,
        "scheduled_at": null,
        "poll": null,
        "idempotency": null,
        "with_rate_limit": false,
        "in_reply_to_id": null,
        "application_id": 2
    },
    "media_attachments": []
}
```

### Specifications

main

### PR DESCRIPTION
**Pull request by mjankowski**
Resolves https://github.com/mastodon/mastodon/issues/21777

This is coming from a persisted <abbr title="Jetpack Sunday Ontario Network">JSON</abbr> column which has hash string indexes for the purposes of this serializer.

After doing this, I realized that..

- There's not really an explanation of why it was removed initially - https://github.com/mastodon/mastodon/pull/9725/files#diff-ddafdff74e1f9bcb54cc17d1a978f6691bf0a83ecd6e8bf3c9f8503ba936c0bbR13
- The docs all reference it - https://docs.joinmastodon.org/methods/scheduled_statuses/ - and reference it as an Integer

So, I think this change does fix the bug as described in the linked issue, but I could also see just accepting the reality of ~5 years of "wrong" API and the docs being like they are, and just call this not a bug ... in which case I'll close this PR, and do a followup to just add the specs and remove the currently-useless `without` call.

If we do accept this, we'll need doc update as well.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
`application_id` is fairly internal, there is no API to use it, and whenever an application is properly represented in the API, it's with `name` and `website`, without an identifier.

So it makes sense removing it.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by mjankowski** [comment]
Sounds good -- should probably be a doc update to remove as well?

**Comment by nikclayton** [comment]
@mjankowski I think this needs to be reverted. https://github.com/search?q=applicationId+language%3AJava+mastodon&type=code shows there are clients out there that expect this field to in the `ScheduledStatus` response. Removing it like this will -- probably -- cause those clients to crash, because from their perspective the server is now returning invalid data.

Given the difficulty of modifying a response type when the response type depends on the shape of the incoming data, I think the safest thing to do here is to:

**Immediate**

1. Revert this change.
2. Document the `application_id` parameter, and note that it is always included, to reflect current behaviour

**Future**

The mechanism for posting a scheduled status has a significant foot-gun. Specifically, if the server does not support scheduled statuses then the status is posted immediately (because the server will ignore the `scheduled_at` property in the request).

This is a general problem with any API surface that either accepts an object with optional/nullable properties, or is polymorphic in the return type.

To fix this, have two API endpoints, one for posting statuses, and one for posting scheduled statuses.

Rather than creating `POST /api/v2/statuses` and `POST /api/v1/scheduled_statuses` this would be an opportune time to introduce support for creating a thread, https://github.com/mastodon/mastodon/issues/32171.

**Comment by nikclayton** [comment]
Ping @ClearlyClaire @mjankowski

**Comment by mjankowski** [comment]
Are there cases of actual client issues (crash instead of graceful handle missing value), or just hypothetical?

**Comment by nikclayton** [comment]
I can safely hypothesise that some of those libraries will crash.

Even for the ones that won't, there is no "graceful" way for an app to handle this. Once the server starts returning (from the app's perspective) garbage data the only safe thing the app can do is disable the functionality and show an error to the user.

For example, if Pachli used `application_id` this is what the user would see when they try and view the list of scheduled statuses:



That's obviously unacceptable.

**Comment by ClearlyClaire** [comment]
I agree this is technically a breaking change, and we should not have done it this way. However, it has been live on mastodon.social for a while now, and we have not heard of any issue, so it is unlikely to be an issue in practice.

**Pull request merged**
