### PR TITLE
use existing inflections instead of custom helper

### PR DESCRIPTION
**Pull request by nightpool**
in #4622, we added an entirely new helper for something rails already does for us.

image

### CODE REVIEW

**Review by Gargron — DISMISSED** [review]

**Comment by nullkal** [comment]
`ActiveSupport::Inflector#humanize` translates `ostatus` into `Ostatus` while `OStatus` is more appropriate. This is the reason why I created an new helper method instead of using it.

**Comment by nightpool** [comment]
one sec, this doesn't work because the helper isn't included, for some reason.

**Comment by Gargron** [comment]
@nullkal We define some custom inflections in config/initializers/inflections.rb - I would assume the humanize method would use those definitions..?

**Comment by nullkal** [comment]
I understood. Thanks!

Ref: https://github.com/tootsuite/mastodon/blob/master/config/initializers/inflections.rb#L16-L17

**Comment by nightpool** [comment]
fixed.

**Comment by Gargron** [comment]
CI build is broken due to some unrelated thing, mind submitting an empty commit to bump it?

**Comment by nightpool** [comment]
@Gargron that's the /push build. I think travis got confused because I accidentally pushed this to tootsuite/mastodon instead of nightpool/mastodon. the /pr build is correct.

**Pull request merged**
