### PR TITLE
Change `source` attribute of `Suggestion` entity in `/api/v2/suggestions` back to a string

### LINKED ISSUE #29071: Regression: Suggestion.source is documented as a string, currently returns list of strings
### Steps to reproduce the problem

1. On `mastodon.social`, call [`/api/v2/suggestions`](https://docs.joinmastodon.org/methods/suggestions/#v2)
2. Attempt to decode output as documented, as an array of [`Suggestion`](https://docs.joinmastodon.org/entities/Suggestion/) objects
3. Decoding fails because object has changed from documented format

### Expected behaviour

`Suggestion.source` should be a string

### Actual behaviour

`Suggestion.source` is an array of strings

### Detailed description

I'm not sure when this changed, but it's not documented, or backwards compatible with existing clients. My suggestion for the fix would be to keep `source` as a string, populate it with the first or most important of the possible source strings, deprecate `source`, and return the full list of sources as a new `sources` property on `Suggestion`.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-02-02

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
The new array is now in the `sources` attribute.

Fixes #29071

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
cc @VyrCossont

**Comment by VyrCossont** [comment]
Thanks, this should work.

**Review by renchap — DISMISSED** [review]
Looks good, docs will need to be updated.

**Comment by ClearlyClaire** [comment]
Removed from the merge queue as I missed the necessary front-end changes.

**Review by renchap — APPROVED** [review]

**Pull request merged**
