### PR TITLE
Fix Doorkeeper error

### PR DESCRIPTION
**Pull request by ykzts**
revert https://github.com/tootsuite/mastodon/commit/88725d6ce85115ea3b0652007db5d40a1c069be3#diff-e621685ac1c2689eaedaedf334c6123bR39

### CODE REVIEW

**Comment by Gargron** [comment]
I am surprised these two things are related, but most importantly, that commit was a fix for a specific issue. Each load of the home controller created a new access token instead of reusing the existing one. That configuration option is *supposed* to be the answer to that. Why and what does it break? We need to find an alternative fix.

**Comment by Gargron** [comment]
Maybe `Doorkeeper::OAuth::Scopes.from_string('read write follow')` instead of `'read write follow'` in https://github.com/tootsuite/mastodon/blob/master/app/controllers/home_controller.rb#L21

**Comment by ykzts** [comment]
@Gargron 

> Maybe Doorkeeper::OAuth::Scopes.from_string('read write follow') instead of 'read write follow' in https://github.com/tootsuite/mastodon/blob/master/app/controllers/home_controller.rb#L21

oh! Great! The problem is resolved.

**Comment by ykzts** [comment]
Please re-review.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
