### PR TITLE
#1319 Specify local followers rather than all followers.

### PR DESCRIPTION
**Pull request by simonv3**
Addresses #1319, makes it clearer that Private means local followers only, rather than all followers across instances

### CODE REVIEW

**Comment by yiskah** [comment]
It seems this may not be true soon if #2111 is merged

**Comment by Gargron** [comment]
Indeed, that was a temporary limitation

**Comment by simonv3** [comment]
That works too!

**Comment by Gargron** [comment]
Current master federated private toots so I am closing this 👍

**Pull request closed without merging**
