### PR TITLE
Use native Docker Builder for arm64

### PR DESCRIPTION
**Pull request by renchap**
(Please do not merge yet)

This uses a Docker Builder running on a 4-core ARM64 Hetzner Cloud server, managed by the project.

Credentials are in Github Secrets.

If configure 2 docker builders:
- an `amd64` builder, running locally in the Github hosted runner, but accessed using TCP. It is started as a TCP runner manually, if you let the setup action do it, is used the `docker-container` driver, and you need the same driver everywhere
- an `arm64` remote runner over TCP, on the Hetzner cloud server

Container build time for both archs: 4 minutes.

We may be able to do it in a simpler way by exposing the Docker Daemon over TCP on the Hetzner Cloud Server (with mTLS auth) and use a remote `docker-container` endpoint, rather that using the `remote` driver.

Once we deploy Tailscale, we will probably want this to go through Tailscale, and maybe even use the `ssh` authentication method.

### CODE REVIEW

**Comment by renchap** [comment]
Ping @timetinytim for internal review

Ping @roobre and @jippi as this is related to your other PRs

**Comment by ykzts** [comment]
Since there are many duplicate actions, using [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) may make management easier.

**Comment by renchap** [comment]
I ran more tests, and you need to use the `remote` driver if you want any remote builder, you can use use multiple Docker daemons with `docker-container` driver.

So the only improvement here would be with Tailscale + switching to SSH authentication (using Tailscale's built-in SSH handling) so we dont have to manage any credentials apart of Tailscale.

**Comment by timetinytim** [comment]
This is fantastic, and the significantly-shortened build times are a huge bonus. Thank you for putting this together!

**Review by timetinytim — APPROVED** [review]

**Comment by roobre** [comment]
This is great and definitely the way to go. Huge thanks for getting this done @renchap!

**Comment by ClearlyClaire** [comment]
This would be an excellent improvement of build times, but I have a few concerns:
- not making forks' life more complicated by having to replicate the potentially onerous custom builder setup or having to manage significant diffs on those workflow files
- are the security guarantees the same as with Github's default builders (e.g. is there a way in which a custom builder could possibly get compromised by malicious PRs)? if not, the custom builders should most probably not be enabled on PRs

**Comment by rinsuki** [comment]
I think we should use cross compilation to decrease build times, since it also fork's build time makes faster, and keep transparency of build process.

more info: https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

e.g. you don't need to ...
* emulate Node.js for `assets:precompile`
* Ruby and Node.js should cross-compilable to AArch64 from x86_64 I think (you may still need to compile third-party libraries, though)

**Comment by roobre** [comment]
@rinsuki I gave exactly this a shot in https://github.com/mastodon/mastodon/pull/25829, thinking it would be easy. There was a hidden challenge in the fact that the arch-independent stage (`assets:precompile`) needs an arch-dependent stage to run (`bundle install`), so I had to duplicate a shitload of code to make that work.

It might be improvable with input from someone with more Ruby expertise than me (which is not hard as I have none).

**Comment by ClearlyClaire** [comment]
I think installing ruby dependencies is not strictly necessary for the bulk of assets building, but doing otherwise will duplicate some glue logic behind webpack invocation, so that may be inadvisable. And in any case, this will require installing nodejs dependencies, which is also currently necessary in the runtime part (in the future, we want to split the runtime nodejs dependencies from the build-time dependencies)

**Comment by renchap** [comment]
Replaced by #26007

**Pull request closed without merging**
