### PR TITLE
Change verification to only work for https links

### LINKED ISSUE #20242: require https:// for link verification
### Pitch

at the moment the profile link verification works with both http and https connections. I think it would be ideal to only validate https connections so that at the point of verification the server is checking for a valid ssl certificate.

### Motivation

Stops someone spoofing a website to verify them as someone else (fairly hard to arrange but it can be done) This gives a slightly higher level of assurance to the green mark.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #20242

### CODE REVIEW

**Review by ineffyble — APPROVED** [review]
LGTM. Should we update the Link Verification docs and/or the inline explanation to make this requirement clear?

**Comment by ianh** [comment]
I just came across this PR and felt compelled to mention—my personal website is http-only, so this change would cause me to lose my verification.

**Comment by Gargron** [comment]
Sorry, but it seems like arguments in favour are stronger. Adding https is not difficult nowadays.

**Comment by tathamoddie** [comment]
> LGTM. Should we update the Link Verification docs and/or the inline explanation to make this requirement clear?

I've proposed an aligned documentation change here: https://github.com/mastodon/documentation/pull/1022

**Pull request merged**
