### PR TITLE
Add missing word in pt and pt-BR (regression from #3564)

### PR DESCRIPTION
**Pull request by ykzts**
https://translate.google.com/#pt/en/Par%C3%A2metros%20da%20listagem%20Home

I feel I can not erase it.

cc @fvh-P

### CODE REVIEW

**Comment by ykzts** [comment]
cc @hugogameiro ? (#1966)

**Comment by hugogameiro** [comment]
@ykzts is your question about how to translate "home" or something else?

**Comment by ykzts** [comment]
@hugogameiro In #3564 the word "Home" has gone. Is this OK?

**Comment by hugogameiro** [comment]
@ykzts I removed it because I didn't find a proper word to translate it. Where I could not remove it, I just didn't translate it, in there it made sense to remove it because you would only see that text when you were already in the home column/feed.
But what you suggest here is ok and probably is better for future proof.

**Review by hugogameiro — APPROVED** [review]

**Comment by ykzts** [comment]
@hugogameiro thank you!

**Comment by Gargron** [comment]
That key is now used for settings on other timelines too. So it's good that the in-string specification is gone.

**Comment by ykzts** [comment]
@Gargron Hmm, I got it. I close this PR.

**Pull request closed without merging**
