### PR TITLE
Replace '貼' with '嘟' for 'toot'

### PR DESCRIPTION
**Pull request by caasi**
Replace '貼' with '嘟' so the web front-end looks more consistent.

### CODE REVIEW

**Comment by ykzts** [comment]
cc @Artoria2e5 @shouko @vidarlee

**Comment by MaciekBaron** [comment]
@caasi there seem to be some conflicts, could you have a look before we review? Thanks!

**Comment by caasi** [comment]
@MaciekBaron I resolved the conflict. I may translate those new strings later.

**Comment by ykzts** [comment]
merge ready?

**Review by MaciekBaron — APPROVED** [review]
LGTM

**Review by ykzts — APPROVED** [review]

**Pull request merged**
