### PR TITLE
Add form element on compose area

### PR DESCRIPTION
**Pull request by sunny**
To increase the accessibility of the compose area, use the semantic `<form>` tag and the `type="submit"` attribute for browsers and assistive technologies.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Is there something specific that this fixes? The form doesn't have an `onSubmit` handler so I don't think anything can trigger the submission in a way not already covered by the button's `onClick` handler or the `ctrl`+`enter` keyboard shortcut.

**Comment by sunny** [comment]
As far as I know this doesn’t fix any specific issue other than helping assistive technologies decide where the form starts and ends, linking the textarea to its submit button.

**Comment by sunny** [comment]
Thank you for the swift handling and maintaining Mastodon 💜

**Comment by shleeable** [comment]
@sunny this might have a regression. Every time I toot it prompts me to leave the site?
image

**Comment by ClearlyClaire** [comment]
For your information, this causes clicking the submit button to actually submitting the form and refreshing the page. Addressed in #19762.

**Comment by sunny** [comment]
Darn, sorry for not catching that 🤦🏻

**Pull request merged**
