### PR TITLE
Add `tootctl accounts migrate`

### LINKED ISSUE #22281: Add `MoveService` account.migrations.last to Tootctl to help with abandoned followers on remote instances
### Pitch

When migrating from one instance to another it is possible for followers to be abandoned or "left behind" on an original instance. I believe we can add a feature to `tootctl` that will allow operators of the instance in which the followers are "stuck" to manually renegotiate with the new instance. 

I believe this is because of the public key/private key negotiation that needs to happen between the 3 instances in consideration.

 - **Origin** Original host instance, the original home instance of the migrating user.
 - **Desired** New desired host instance, the intended new home for the migrating user.
 - **Remote** Remote "follower" instance, the 3rd instance that had originally followed **Origin** and after the migration should be following **Remote**.

Based off of https://github.com/mastodon/mastodon/issues/21442#issuecomment-1327954053 I believe we can add a feature to `tootctl` to call the following Ruby code:

```ruby
MoveService.new.call(account.migrations.last)
```

Which should make it easier for remote instance operators to run and fix the abandoned followers problem. Right now, unless something causes the missed followers to renegotiate, I believe they will be "stuck" forever.

### Motivation

The motivation is to give operators **something** they can do, in order to address the (what I believe is a very large) problem of followers being orphaned/abandoned during a migration when negotiation fails.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #22281

### CODE REVIEW

**Review by Gargron — COMMENTED** [review]
A bit hesitant on such a specific command as "replay-migration". How about a "migrate" command that would handle replays of previous migrations as well as new migrations?

**Review by Gargron — APPROVED** [review]

**Comment by ineffyble** [comment]
Would this have a secondary use of letting an instance admin allow a suspended user to migrate, without having to grant them any access in the process?

**Comment by ClearlyClaire** [comment]
> Would this have a secondary use of letting an instance admin allow a suspended user to migrate, without having to grant them any access in the process?

Hmmm… I think it *should* work.

**Comment by joenepraat** [comment]
> > Would this have a secondary use of letting an instance admin allow a suspended user to migrate, without having to grant them any access in the process?
> 
> Hmmm… I think it _should_ work.

I tried this, but it only migrates local users and after that the user is not able to migrate for 30 days (also not to the same account if I change the migration date in the `account_migrations` table).

**Pull request merged**
