### PR TITLE
Change form-action Content-Security-Policy directive to be more restrictive

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Since #31402, the Web UI should not need to submit any form, except perhaps through redirections when clicking the sign-in button when a SSO is enabled.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I'm not sure where the `http://example.com` comes from in the test suite… is that Capybara's `app_host`?

**Comment by mjankowski** [comment]
> I'm not sure where the `http://example.com` comes from in the test suite… is that Capybara's `app_host`?

Yes, thats likely coming from the default setting.

**Comment by ClearlyClaire** [comment]
Reviving this since #31402 has been merged, which makes things a bit simpler.

I think allowing any form at all is unnecessary even for the SSO, but I'm not sure about that bit, with the complex redirection flow and how massively painful SSO setups are to test.

That being said, now that I think about it, #31402 might have possibly broken one-click SSO log-out?

**Comment by ClearlyClaire** [comment]
cc @CSDUMMI since afaik you are one of the only people going all-in on SSO

**Comment by ClearlyClaire** [comment]
Thinking more about it, I don't think this change can break anything SSO-related. This would only affect redirects that occur after a form submission, but there is no form submission to begin with.

**Review by oneiros — DISMISSED** [review]

**Review by oneiros — APPROVED** [review]

**Pull request merged**
