### PR TITLE
Change "direct message" nomenclature to "private mention" in web UI

### PR DESCRIPTION
**Pull request by Gargron**
Private mention is a much better name for the feature that we have than direct message, because "message" has implications about threading and addressing that the feature does not fulfill. Credit for the idea goes to Ivory.

Screenshot 2023-03-25 at 09-32-10 Localhost

___

Fixes MAS-100

### CODE REVIEW

**Comment by trwnh** [comment]
this is a bit confusing especially when there are multiple mentions. functionally, it's important that users know first and foremost that it is a "status", and secondly that it goes to any *and all* "mentions". i can't help but think "mentions-only status" is better in that regard (mirroring "followers-only status").

**Comment by Gargron** [comment]
The PR no longer renames "Mentioned people only".

**Review by ClearlyClaire — COMMENTED** [review]
I am still slightly unsure about the “Private mention” wording of the post heading, which I still think might be misleading, but I don't have a better suggestion.

The code seems fine otherwise, and the main source of confusion from the previous version of the PR has been avoided by not renaming the “Mentioned people only” option.

**Comment by joenepraat** [comment]
Although in English this a good choice, for other languages (like Dutch and German) this doesn't look nice, but it is especially difficult in other construction (like privately mention ...).

**Comment by joenepraat** [comment]
During translation, I also found a few strings with 'direct messages*' in English. This should be fixed or people are even more confused.

**Pull request merged**
