### PR TITLE
Remove `tai` locale

### PR DESCRIPTION
**Pull request by c960657**
According to the [ISO 639-3 Registration Authority](https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab) there is no locale with the code `tai`.

Mastodon only has one YAML translation file for this locale, and it just contains strings in English. It was added in #13749 together with a lot of other translation files. I assume this was added by mistake. The language name was added in #23313, a general clean-up task.

I think we should remove this locale.

### CODE REVIEW

**Comment by nightpool** [comment]
>According to the [ISO 639-3 Registration Authority](https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab) there is no locale with the code tai.

Are you sure? I was able to find https://iso639-3.sil.org/code/tai with a little bit of Googling. Seems like maybe this is a family of languages and not a language in and of itself though (https://en.wikipedia.org/wiki/Tai_languages), and since nobody is using/translating for it, I don't think this is an obstacle to removal

**Comment by c960657** [comment]
I was wrong.

I do not have any knowledge about this language in particular. While working on #23587 I just noticed that `tai` is not mentioned in CLDR.

I was not aware that there are both ISO 639-2 3-letter codes and the ISO 639-3 3-letter codes. According to [this explanation of the relationship between these lists](https://iso639-3.sil.org/about/relationships), the 639-3 list is a subset of the 639-2 list, except that 639-2 includes language groups and 639-3 does not. The registration authority for ISO 639-2 is the [United States Library of Congress](https://www.loc.gov/standards/iso639-2/) and the registration authority for ISO 639-3 is [SIL International](https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab).

`tai` is a language group and is included in 639-2 codes but not in 639-3. So it _is_ a valid ISO 639-2 code.

I don't know if it makes sense to include language groups as supported languages in Mastodon. Probably not. But in any case, the locale is empty, so I think we should remove it for now.

**Review by Gargron — APPROVED** [review]
Makes sense to remove it if it's still empty after all this time.

**Comment by gunchleoc** [comment]
The languages is still listed in Crowdin and should be removed from there too https://crowdin.com/project/mastodon/tai

**Comment by Yoxem** [comment]
I've found that is one name for the ISO Code (ISO 639): nan-TW (aka Taiwanese [Hokkien]). Although I don't consider the ISO code is proper for the language, according to the rule, it's language code name should be "nan-TW".

**Comment by winstonsung** [comment]
Please note that the BCP 47 language subtag/ISO 639 language code "tai" is not referring to Taiwanese Hokkien "臺" (Tái, Tai²) but instead referring to Zhuang–Tai "壯傣" (Zhuàng–Tài, Zhuang⁴–Tai⁴).

**Pull request merged**
