### PR TITLE
Drop support for ruby 3.1

### PR DESCRIPTION
**Pull request by mjankowski**
Still not EOL for a bit, but opening now to work out any concerns.

Related to https://github.com/mastodon/mastodon/pull/32357 in that Rails 8.0 will require 3.2+

Related to https://github.com/mastodon/mastodon/pull/32332 in that they are both ruby versions, which is nice.

On a side note here - do we have any idea what portion of instance operators are stuck in a "my linux distribution has an outdated ruby version and I can't change it" sort of scenario? My understanding is that this persona is the main reason we support any old versions at all?

It seems like if the "I'm running from the Docker image" or "I'm copy and pasting `rbenv` commands" personas were ever all/most of the deployments, we could safely require one modern/current/latest version with each release? (which seems desirable from many perspectives - support, maintenance, performance, developer, CI, etc)

### CODE REVIEW

**Comment by mjankowski** [comment]
Sort of relevant, latest Rails CVE don't impact ruby 3.2+ - https://github.com/rails/rails/security/advisories/GHSA-x76w-6vjr-8xgj

**Comment by mjankowski** [comment]
Sort of relevant, zeitwerk 2.7.0 requires 3.2+ - https://github.com/fxn/zeitwerk/blob/main/CHANGELOG.md#270-11-october-2024

**Comment by mjankowski** [comment]
Possible followup https://github.com/mjankowski/mastodon/compare/drop-ruby-3-1...mjankowski:mastodon:drop-ruby-3-1-also-drop-3-2

**Review by renchap — APPROVED** [review]
Let's drop 3.1 support, but we will keep 3.2 for at least one release

**Pull request merged**
