### PR TITLE
Don't use "unfollow language" when cancelling follow requests

### LINKED ISSUE #19361: Cancelling a follow request says "unfollow" instead of "cancel"
### Steps to reproduce the problem

1. enable unfollow confirmation dialog
2. follow request someone
3. withdraw the request before it is approved

### Expected behaviour

The dialog should say something along the lines of "Are you sure you want to cancel your follow request?"

### Actual behaviour

The button says "unfollow" as if your request had already been approved and you were about to unfollow.

### Specifications

Mastodon 3.5.3 (reproduced on mastodon.art)

### PR DESCRIPTION
**Pull request by prplecake**
- Adds two new i18n keys: `confirmations.cancel_follow_request.confirm` and `confirmations.cancel_follow_request.message`
- Update the header container to use new language

Fixes #19361 

I didn't think I needed to change anything in [account_container.js](../blob/main/app/javascript/mastodon/containers/account_container.js). As far as I could tell that only lists accounts you're following, not accounts pending request approval.

image

It looks a little funky having two "cancel" buttons, but I tried to improve that by using "Cancel request" for the action confirmation.

### CODE REVIEW

**Comment by mxamber** [comment]
How about renaming "cancel" to "keep request" or "don't abort request" to reduce confusion? Or changing "cancel follow request" to "withdraw request" or "abort request".

**Comment by ClearlyClaire** [comment]
I remember one reason I did not tackle this is because I couldn't find non-confusing wording with the “Cancel” used to dismiss the modal. I think the suggestion to “withdraw the request” rather than “cancel it” makes sense!

**Comment by prplecake** [comment]
I think "Withdraw follow request" looks good. Note the button on the account header has changed!
Screenshot 2022-10-17 at 05 04 52

**Comment by ClearlyClaire** [comment]
> We should probably change the wording on the "Unfollow button" to match!
> 
> I'll update to use "Withdraw request". Can I get confirmation I don't need to touch `account_container.js`? I'm still wrapping my head around React and can't quite figure out how to tell if something is used without, like, making a typo and seeing what breaks.

Looking at it, it shouldn't be possible to reach the “withdraw follow request” path from it, as the action button will display an un-clickable hourglass in the event the account has been sent a follow request. That being said, it may make sense to make that hourglass clickable to withdraw the follow request, but I think it's best suited for another Pull Request.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
