### PR TITLE
Unread indicator was invisible behind column header, adjusted

### PR DESCRIPTION
**Pull request by Gargron**
image

### CODE REVIEW

**Comment by unarist** [comment]
It may be invisible, or may be visible on weird position (#3711).

And the indicator seems to move according to scroll. I've tested on Chrome 59 on Windows.

**Comment by Gargron** [comment]
@unarist Thank you for reporting. It behaves correctly on Firefox. I don't currently have Chrome to experiment with this. If you inspect the element, do you have any idea why it would behave that way instead of sticking to the .column which is position: relative? It should be position: absolute relative to .column. But what you are saying sounds like it's relative to some child element of .column like .scrollable.

**Comment by unarist** [comment]
@Gargron I've also confirmed that it works on Firefox...

> sounds like it's relative to some child element of .column like .scrollable.

I think so too.

Sadly, I haven't found CSS solution yet and I thought the only way to fix this is move the indicator to outside of the scrollable container.

**Comment by Gargron** [comment]
That sounds reasonable, I will try to do that

**Comment by Gargron** [comment]
@unarist I have tried

**Review by unarist — APPROVED** [review]
Great!

**Comment by unarist** [comment]
Oh wait, could you add `flex: 0 0 auto` to `.column-header__wrapper` and remove from `.column-collapsable`? (see #3313)

**Review by unarist — APPROVED** [review]

**Pull request merged**
