### PR TITLE
Minor Chinese check & jsx addition

### PR DESCRIPTION
**Pull request by Artoria2e5**
This pull request is a mixture of proofreading (plus woofreading + awooreading) and translation addition. Each chunk of edit is provided separately in commits.

### CODE REVIEW

**Comment by Artoria2e5** [comment]
Hmm, the CI build is bundling my l10n changes for caching. Is that intended…?

**Comment by ykzts** [comment]
cc @KenOokamiHoro @leopku @miuchan @vidarlee

**Review by Gargron — APPROVED** [review]

**Comment by leopku** [comment]
@AstroProfundis 
Maybe "收藏了你的嘟文" is better than "收藏了你的状态".
In `zh-CN.yml`, "嘟文" is general used.

**Comment by AstroProfundis** [comment]
@leopku That's fine, i was talking about the whole sentence been different from zh-TW and zh-HK, "嘟文" is good for me.

ps, if i remember right, OP introduced the translation "嘟文" in the first place...

**Comment by leopku** [comment]
@AstroProfundis sorry for misunderstanding:)

**Pull request merged**
