### PR TITLE
Change filtered notification banner design to take up less space

### PR DESCRIPTION
**Pull request by ClearlyClaire**
One of the issues with our “filtered notifications” feature is that the filtered notifications banner can take a lot of space (especially in horizontally-constrained layouts) and draw more attention than warranted.

This PR is an attempt at a small step towards fixing that.

The “mentions” text was inaccurate (it's not necessarily mentions, though maybe we should change the backend to only count mentions) and taking a lot of horizontal space. I am not sure how useful the color count badge is but I kept it for now.

There's a further proposal at https://github.com/mastodon/mastodon/issues/29723#issuecomment-2259152761

## Before

image

## After

image

### CODE REVIEW

**Comment by renchap** [comment]
This looks better, but we probably need to check how it will look like with more verbose languages and ensure that it does not revert to the weird 4 lines we had before?

**Comment by ClearlyClaire** [comment]
> This looks better, but we probably need to check how it will look like with more verbose languages and ensure that it does not revert to the weird 4 lines we had before?

I think we will have a hard time anticipating that (especially since the PR changes the string to be shorter), still, this is unlikely to spill over more than 3 lines.

**Comment by oneiros** [comment]
Maybe the text should be changed to "*From* one person you may know" even though that is longer.

I worry, this might be very misleading otherwise. Imagine the number of notifications would be much higher, then it would be possible to read this as "Hey, we filtered a bunch of notifications for you, but there is one person in there, that we think you might actually know."

**Comment by ClearlyClaire** [comment]
> Maybe the text should be changed to "_From_ one person you may know" even though that is longer.
> 
> I worry, this might be very misleading otherwise. Imagine the number of notifications would be much higher, then it would be possible to read this as "Hey, we filtered a bunch of notifications for you, but there is one person in there, that we think you might actually know."

This still fits in English, but may more easily spill over in other languages
image

**Review by oneiros — APPROVED** [review]

**Pull request merged**
