### PR TITLE
Docker-Compose Sidekiq Seperation

### PR DESCRIPTION
**Pull request by shleeable**
I'm running this on my instance.. the memory usage is about 220MB per sidekiq (If you're running this on a super lowend box - consider not?).

image

This is a non-breaking change... Anybody got an opinion on this?

### CODE REVIEW

**Comment by ThibG** [comment]
I don't get what's the point of this change? What do we gain by running multiple sidekiq processes in multiple containers?

**Comment by Gargron** [comment]
@ThibG I was explaining in admin chat how to guarantee that stalling jobs don't impact user experience, and that is by running multiple processes side by side instead of relying on a single process only.

Still my take is that it's deployment-specific customization that admins should do themselves.

**Comment by ThibG** [comment]
Alright, but would we even need one container per sidekiq process?

**Comment by Gargron** [comment]
Although it is possible to do otherwise, the Docker convention is one process per container. The user can then spin up more or less containers using `docker-compose scale`.

**Comment by shleeable** [comment]
> Still my take is that it's deployment-specific customization that admins should do themselves.

This is a solution to a common problem. So maybe it's worth an addition in the documentation instead. or a `docker-compose.yml.prod`

Depends who the target is for the out of the box `docker-compose.yml`...

**Comment by shleeable** [comment]
> Still my take is that it's deployment-specific customization that admins should do themselves.

Depends who the target is for the out of the box `docker-compose.yml`... 
Maybe it's worth moving this in the documentation instead. or a `docker-compose.yml.prod`

**Pull request closed without merging**
