### PR TITLE
Add public key declaration to actors

### PR DESCRIPTION
**Pull request by Gargron**
Reference: https://github.com/w3c/activitypub/issues/203#issuecomment-297553229

### CODE REVIEW

**Comment by Gargron** [comment]
cc @cwebber @puckipedia

**Comment by puckipedia** [comment]
LGTM, seems to correspond with what I implemented (except that I link to a key instead of embedding it). 👍

**Comment by puckipedia** [comment]
.. except, why not embed the publicKey if it isn't the root object?

**Comment by Gargron** [comment]
@puckipedia Verbosity mostly

**Comment by puckipedia** [comment]
so I would suggest at least having a `publicKey` pointer, else the acthor object you'd find embedded in an activity isn't the same as the object the id is pointing to...

**Comment by Gargron** [comment]
@puckipedia Okay, publicKey now always included

**Pull request merged**
