### PR TITLE
Fix accounts table long display name

### LINKED ISSUE #29259: Long display name rendering issue on /admin/accounts/ page
### Steps to reproduce the problem

1. With the correct permissions, go to the Moderation > Accounts (/admin/accounts/) page.
2. With an existing user that has a very long display name, find/look at it...

### Expected behaviour

Display name should truncate so that everything doesn't get pushed off (post count, follower count, last active time)

### Actual behaviour

The display name takes up all/the entire width

### Detailed description

Screenshot 2024-02-17 at 09 45 33

### Mastodon instance

birdbutt.com

### Mastodon version

v4.2.7

### Browser name and version

Firefox 122

### Operating system

macOS 14.3.1

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by WebCoder49**
Fixes #29259 ; Tested on Edge (121.0.2277.128 (Official build) (64-bit)) and Firefox

image

### CODE REVIEW

**Review by mjankowski — APPROVED** [review]

**Review by vmstan — APPROVED** [review]

**Review by ThisIsMissEm — APPROVED** [review]
This change looks good to me, hopefully the `.accounts-table` class isn't used anywhere it shouldn't be.

I see this used in tables of accounts for:
- Moderation > Accounts
- Recommendations & Trends > Follow recommendations
- Follows and Followers (visible to end-users)

Only for the last one, Follows and Followers, could this pose a problem, where we may need to have a title to view the full account username or name.

**Comment by WebCoder49** [comment]
@ThisIsMissEm thank you very much for this thoughtful review - I'd overlooked that, but it makes sense. I will look at these pages with my change applied.

**Comment by mjankowski** [comment]
@WebCoder49 did you ever review those other spots?

**Comment by WebCoder49** [comment]
Thanks for the reminder; I'll look at it and respond by around 5:30pm.

**Comment by WebCoder49** [comment]
Sorry for changing the commits - I was trying to delete the empty commit earlier but that invalidated your reviews! Please could you review my one-line change again, @mjankowski , @vmstan and @ThisIsMissEm ?

I am finding it difficult to get follow recommendations recalculated on demand, but the other 2 places this class is used work with the rendered HTML (commit 68c7782 without and with my commit):
image

**Comment by mjankowski** [comment]
Sort of related https://github.com/mastodon/mastodon/issues/32743

**Review by mjankowski — APPROVED** [review]

**Review by ThisIsMissEm — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
By itself, this unfortunately makes the moderation interface very hard to use on narrow widths (e.g. mobile), obscuring key information like username:
image

**Comment by WebCoder49** [comment]
Thanks for mentioning this, @ClearlyClaire . I'm sorry for the oversight... It probably needs something like the CSS `overflow-x: auto;` (untested).

**Comment by ClearlyClaire** [comment]
I am not sure where you suggest adding `overflow-x: auto` but I fail to see one place where it would work nicely.

**Comment by WebCoder49** [comment]
That's a good point, @clearlyclaire. I was basically noting down my very first thoughts. Shall I add the problem on small-screens moderation as an issue (if nobody's done it already)?

**Comment by ClearlyClaire** [comment]
I reverted this Pull Request and used another approach in #33064, but this definitely would use some redesign. I'm not sure how we should address all of this.

**Comment by WebCoder49** [comment]
Thank you for this! I do agree that neither my approach or yours is ideal, but yours is definitely better for usability...

**Pull request merged**
