### PR TITLE
Fix not actually connecting to the configured replica

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Review by krainboltgreene — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Comment by zunda** [comment]
I'd appreciate it if you could add a phrase like below to release notes:

> It is necessary to copy the content of the `DATABASE_URL` environment variable to the `READ_DATABASE_URL` environment variable if the database connection information is set in the `DATABASE_URL` environment variable.

Reading the definition for the `environment_value_for` method in `activerecord-7.0.6/lib/active_record/database_configurations.rb`, it looks like `DATABASE_URL` environment variable is only honored for the primary database while a separate environment variable `READ_DATABASE_URL` is required for the `read` database.

```ruby
      def environment_value_for(name)
        name_env_key = "#{name.upcase}_DATABASE_URL"
        url = ENV[name_env_key]
        url ||= ENV["DATABASE_URL"] if name == "primary"
        url
      end
```

**Comment by krainboltgreene** [comment]
@zunda I was unaware of that feature. Thanks for pointing it out.

**Comment by ClearlyClaire** [comment]
> I'd appreciate it if you could add a phrase like below to release notes:
> 
> > It is necessary to copy the content of the `DATABASE_URL` environment variable to the `READ_DATABASE_URL` environment variable if the database connection information is set in the `DATABASE_URL` environment variable.
> 
> Reading the definition for the `environment_value_for` method in `activerecord-7.0.6/lib/active_record/database_configurations.rb`, it looks like `DATABASE_URL` environment variable is only honored for the primary database while a separate environment variable `READ_DATABASE_URL` is required for the `read` database.
> 
> ```ruby
>       def environment_value_for(name)
>         name_env_key = "#{name.upcase}_DATABASE_URL"
>         url = ENV[name_env_key]
>         url ||= ENV["DATABASE_URL"] if name == "primary"
>         url
>       end
> ```

Trying to wrap my head around this. You don't currently use a replica, but use the `DATABASE_URL` to configure which database to use rather than the `config/database.yml`, and it worked fine until now, but `connects_to database: { writing: :primary, reading: :read }` requires a definition for the `read` database, but that is not covered by the use of `DATABASE_URL`?

Ideally, I do not think this change in the code should require admins to change anything. Can we conditionally `connect_to` the `primary` database even for `reading` when the `read` database is not defined, or perhaps copy `DATABASE_URL` into `READ_DATABASE_URL` if the latter is not defined?

**Comment by krainboltgreene** [comment]
>  but that is not covered by the use of DATABASE_URL?

For every role defined Rails now will look for `"#{role}_DATABASE_URL`.

> Ideally, I do not think this change in the code should require admins to change anything.

We don't have to, all we need to do is simply document: Hey if you're using DATABASE_URL, you'll also need to define READ_DATABASE_URL (it can be the same value)

**Comment by zunda** [comment]
The confusing bit is that `config/database.yml` already has the logic to use the primary as the read replica for `DB_*` and `DB_REPLICA_*` environment variables:

```yaml
production:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME'] || 'mastodon_production' %>
    username: <%= ENV['DB_USER'] || 'mastodon' %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] || 'localhost' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
    prepared_statements: <%= ENV['PREPARED_STATEMENTS'] || 'true' %>
  read:
    <<: *default
    database: <%= ENV['DB_REPLICA_NAME'] ||ENV['DB_NAME'] || 'mastodon_production' %>
    username: <%= ENV['DB_REPLICA_USER'] ||ENV['DB_USER'] || 'mastodon' %>
    password: <%= (ENV['DB_REPLICA_PASS'] || ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_REPLICA_HOST'] ||ENV['DB_HOST'] || 'localhost' %>
    port: <%= ENV['DB_REPLICA_PORT'] ||ENV['DB_PORT'] || 5432 %>
    prepared_statements: <%= ENV['PREPARED_STATEMENTS'] || 'true' %>
    replica: true
```

While I haven't had a chance to test it, #26074 might be something we want to make the behavior consistent between `DB_REPLICA_*` and `READ_DATABASE_URL` settings.

**Pull request merged**
