### PR TITLE
Some improvements in the Spanish translation

### PR DESCRIPTION
**Pull request by febrezo**

### CODE REVIEW

**Comment by ykzts** [comment]
cc @007lva @carlosjs23 @kant @victorhck

**Comment by victorhck** [comment]
I have reviewed and seems very necessary this improvements! :)
Ok, for me!

**Review by victorhck — COMMENTED** [review]
It's ok for me.

**Review by ykzts — APPROVED** [review]

**Comment by ykzts** [comment]
@victorhck thx!

**Comment by victorhck** [comment]
thanks to @febrezo ! :-)

**Pull request merged**
