### PR TITLE
Change post editing to be enabled in web UI

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by trwnh** [comment]
so if you mess up on the visibility or change your mind, you have to manually copy all the text, reupload all the attachments, re-add all the media descriptions?

**Comment by noellabo** [comment]
I understand the intent to avoid having similar functions lined up in the UI, but the functions that will be lost are irreplaceable. It is fine to remove them from the menu, but please consider other means of redrafting them.

For example, you can add a button to the composer that appears when you select Edit from the menu to "delete the post once and return to the state before posting".

**Comment by Izorkin** [comment]
Please return redraft!

**Comment by Gargron** [comment]
Maybe my file didn't save on last rebase, I brought redraft back on one of the dropdowns but not the other.

**Pull request merged**
