### PR TITLE
Remove cookie rotator

### PR DESCRIPTION
**Pull request by mjankowski**
Marked for post-4.3.0 removal

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Trying to wrap my head around it:
- prior to 4.2.0, cookies used the SHA1 digest algorithm and did not support the SHA256 digest algorithm
- 4.2.0 added support for reading SHA256-based cookies but still uses SHA1 on write
- 4.3.0 switched to use SHA256, while still supporting reading from SHA1 cookies

This means that:
- rolling updates are not possible from pre-4.2.0 to 4.3.0, as outlined in the release notes
- merging this PR would mean breaking rolling updates from pre-4.3.0 to the version this is merged
- non-rolling updates are unaffected in both cases

This looks safe to merge, though I suppose we could delay it a bit?

**Comment by mjankowski** [comment]
Yeah, I think that's correct re: the various interactions.

Is the reason for delay to look out for anyone who might switch to nightlies, and to keep that at least a little bit calendar separated from 4.3.0 release?

**Comment by ClearlyClaire** [comment]
> Is the reason for delay to look out for anyone who might switch to nightlies, and to keep that at least a little bit calendar separated from 4.3.0 release?

Yup

**Comment by mjankowski** [comment]
What's a reasonable post-4-3-release delay here?

**Review by ClearlyClaire — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
Re-examining this, I think this is about more than zero-downtime migrations. Servers with this PR cannot read cookies issued by pre-4.3.0 servers. This means if we ship this in 4.4, any server going from 4.2 to 4.4 will have all of their users logged out, and deploying 4.3 in-between won't help them much, as users need to visit the server while it is running 4.3 code.

**Pull request merged**
