### PR TITLE
Do not let mastodon own its files

### PR DESCRIPTION
**Pull request by bobrik**
Letting mastodon own its files allows it to overwrite them, which seems like a security risk. You don't expect postgres binary to be owned by postgres user, the same thing applies here.

I also reordered `COPY` directive to make copy from build image cacheable. Previously `--link` was not available, but it is now:

* https://github.com/moby/buildkit/issues/2987

### CODE REVIEW

**Comment by Eriner** [comment]
This is probably best handled by the orchestrator enforcing filesystem controls (Docker's `read_only`) rather than mucking with file permissions.

**Comment by bobrik** [comment]
I'm not sure how removing a wide `chown` is "mucking".

**Comment by Eriner** [comment]
I agree wholeheartedly with the premise of this PR. The change of the `chown` isn't strictly a problem, it just isn't the ideal solution. 

Rather than changing the permissions of the directory in the commit here, having the orchestrator mark the whole FS as read only and explicitly mount tmpfs volumes for the directories that are expected to be writeable is a more comprehensive solution to the issue.

**Comment by ineffyble** [comment]
@bobrik you may need to log in to CircleCI to let the build-and-test pipeline run.

**Comment by bobrik** [comment]
@ineffyble I have it marked as successfully completed in my circleci:

image

That's for my fork though, I'm now sure how it's supposed to work with circleci.

**Comment by moritzheiber** [comment]
So, generally, I'd agree with the user running the service (`mastodon`) not owning some (if not all) of the files necessary to run the service.

However, we're explicitly breaking user expectation here ("when I log into the container I can modify files") and it's not properly documented how to get around this limitation. Additionally, the user _does need_ access to certain files/directories (don't have a list handy right now) and this is neither covered by these instructions nor by the documentation.

I would either recommend adjusting the documentation _first_ (which works without the modifications, i.e. less restrictive with proper documentation works; more restrictive without documentation doesn't), or foregoing this change entirely and rather have a write-up ala "hardening Mastodon" where one can read up on all the necessary steps of dialing back access for the `mastodon` user without impacting the UX of the container in the process.

Either way, just changing this without any further action wouldn't do, in my opinion.

**Comment by bobrik** [comment]
> it's not properly documented how to get around this limitation

Could you link me to the docs that need to be updated? It's as simple as passing `--user root` to `docker exec` if you want to change stuff for whatever reason.

> Additionally, the user does need access to certain files/directories (don't have a list handy right now)

The only thing that required access in my tests is `/opt/mastodon/tmp` and it's allowed.

It would be great if you could come up with some examples.

**Comment by vmstan** [comment]
These changes have been incorporated with the merger of #26850 

Closing this PR, welcoming future improvements to the new version.

**Pull request closed without merging**
