### PR TITLE
Check media attachment size limit on client side before uploading

### LINKED ISSUE #16718: check filesize on UX client side "This file is too large"
### Pitch

image

### Motivation

I've uploaded a large file.. the message popup "too large" after the file has uploaded seems weird.

### PR DESCRIPTION
**Pull request by rgroothuijsen**
The user is informed whether a media attachment is too large after it has already been uploaded, which is inconvenient for the user as the faulty upload may take a long time before an error is returned. This adds the size limits from the backend (40MB for videos, 10MB for images) to the frontend as well, giving the user immediate feedback.

This might be an overly granular way of specifying whether or not an attachment is too large, but I wasn't quite sure yet.

Fixes #16718

### CODE REVIEW

**Comment by shleeable** [comment]
This is something I've raised with the mastodev before... so I'm all for this, but the value should be dynamic. 
Having a hardcoded value is going to stop instances like mine with higher upload limits.

**Comment by Gargron** [comment]
There is a `configuration` value in `/api/v1/instance` response containing all the limits. The web app currently does not load or use it, but if new limits are added, they should no longer be hardcoded.

**Comment by shleeable** [comment]
Thanks @rgroothuijsen

**Comment by smiba** [comment]
Just checking, why is this pull request gone stale? Because it looks to be a good fix for a somewhat common request

**Pull request closed without merging**
