### PR TITLE
Helm: assign unique set of labels to k8s deployments

### LINKED ISSUE #19703: Helm chart Deployments have identical labels
### Steps to reproduce the problem

Run helm template or inspect a running system to see that:

```yaml
# Source: mastodon/templates/deployment-streaming.yaml
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
```

```yaml
# Source: mastodon/templates/deployment-web.yaml
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
        component: rails
```

```yaml
# Source: mastodon/templates/deployment-sidekiq.yaml
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
        component: rails
```

This combined with the service selectors:
```yaml
# Source: mastodon/templates/service-web.yaml
spec:
  selector:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
```

```yaml
# Source: mastodon/templates/service-streaming.yaml
spec:
  selector:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
```

### Expected behaviour

pods from different systems have different labels

### Actual behaviour

nginx ingress breaks as service selector matches web, streaming, and sidekiq

### Detailed description

Since each service matches all the pods (web, streaming, and sidekiq) when using nginx ingress most of the requests fails as they're sent to the wrong service.
Traefik on the other hand seems to handle this well, but as nginx is one of the more popular ingresses this should be fixed.
This also breaks additional tooling like: `kubectl logs deployment/mastodon-sidekiq`:

```
$ kubectl logs deployment/mastodon-sidekiq --tail=2
Found 2 pods, using pod/mastodon-web-68c98d496f-nwwgk
[d3dabf98-1de7-4859-a35b-11731a91c949] method=GET path=/health format=*/* controller=HealthController action=show status=200 duration=0.26 view=0.13
[988c137e-bf4b-4e1a-a71f-95343a5a3b79] method=GET path=/health format=*/* controller=HealthController action=show status=200 duration=0.26 view=0.1
```

Unfortunately the selector is immutable, so changing this means breaking upgrades.
Kubernetes documentation has a set of [common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) in use and my suggestion is that each deployments gets a `app.kubernetes.io/component` matching their component.
That is: web, streaming, and sidekiq
And `app.kubernetes.io/part-of: rails` for the `podAffinity`

### Specifications

latest chart

### PR DESCRIPTION
**Pull request by deepy**
This fixes #19703 but is also a breaking change as Deployments have to be deleted or the upgrade forced as the fields are immutable

I don't know what the praxis regarding breaking changes is so it'd be great with an extra set of eyes here.

### CODE REVIEW

**Comment by winsmith** [comment]
I just tried to apply this in a fresh namespace and spinning up assets, sidekiq, streaming and web fail with this error:

```
Error: couldn't find key password in Secret mastodon/td-mastodon
```

I also got this error on the console when running `helm install --namespace mastodon --create-namespace td-mastodon ./ -f values.yaml`:

```
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
```

I'm not good enough with k8s to debug this or rule out that I'm doing anything wrong, so I'll leave this here in the hopes that it'll help the author.

**Comment by deepy** [comment]
@winsmith I think the best way to test this is by merging https://github.com/mastodon/mastodon/pull/19678 into your local checkout since the current state of postgres is... well, not quite broken not quite working.
Otherwise I think it should work if you set `postgresql.auth.username` to postgres and both `postgresql.auth.password` and `postgresql.auth.postgresPassword` to the same value

But I think the easiest way is by getting the other PRs changes

**Comment by winsmith** [comment]
Pulling fresh from the source and applying your patch has completely fixed all problems. (I have an existing Postgres instance that I use, so I didn't try out setting `postgresql.auth.username`). Thanks for your help!

**Review by Gargron — APPROVED** [review]

**Comment by dunn** [comment]
this was a breaking change, so we probably should have indicated that with a major version bump to the chart

**Pull request merged**
