### PR TITLE
Use explicit config loading from `bin/rubocop`

### PR DESCRIPTION
**Pull request by mjankowski**
Motivations for the binstub portion specifically:

- There's a slight perf gain from just telling it where to find config instead of running its search (this is pretty minor, but nice, esp given the husky git hook)
- Part of solution to the rubocop path relativity config issue - https://docs.rubocop.org/rubocop/configuration.html#path-relativity that we have currently.

The various linked PRs here were precursors to turn some things back on.

I had hoped to work through this via https://github.com/mastodon/mastodon/pull/30830 but that one sort of stalled without decision. I'd like to revive that approach some day, but for now we should get the current configuration activated correctly.

Other changes here:

- Trigger ruby lint on CI when bin/rubocop changes (this PR was initially a change to just that, but did not run)
- Remove the now-unneeded db/migrate config to explicitly turn on things which had been accidentally disabled (they will be on now w/out that file)
- Disable one last `Rails/NotNullColumn` violation not hit in previous PRs
- Move the rspec/described_class/block config to inline disable, allows us to remove our final nested directory config file, which makes the larger approach here work ... some of these might wind up ultimately replaced by system/request specs, others are prob fine as-is.

I did a little local verification that all of a) running `bin/rubocop`, b) running `bundle exec rubocop`, c) the vscode/rubocop/lsp integration -- all seem to work as expected with changes here.

_(This approach of putting config into binstub came out of the rails 8 PR when running `app:update` process...)_

### CODE REVIEW

**Comment by mjankowski** [comment]
Rebased after various other things merged, converted to ready, updated original description after those changes, etc.

**Comment by mjankowski** [comment]
I think https://github.com/mastodon/mastodon/pull/33283 will be fine with this, seems like bug-fix only release.

**Comment by ClearlyClaire** [comment]
Just checking, does it disable the following cops?

```
Rails/CreateTableWithTimestamps
Rails/ThreeStateBooleanColumn
Rails/ReversibleMigration
```

**Comment by mjankowski** [comment]
Yes, I think the history is something roughly like:

- They were at some point in the _todo file
- As an unintended side effect of another change, we wound up putting them into the path relativity condition by having a config in db/migrate
- On a subsequent todo regeneration they were cleaned up (despite not being resolved)
- Adding them back one by one recently to actively turn them back on (and then add inline disable to solve) got them reactivated
- Removing them here (while ALSO removing the file, which fixes the path relativity thing) keeps them activated

Verified by removing a few inline disables locally and seeing that they do indeed get flagged.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
