### PR TITLE
Do not scroll up when modal is opened

### LINKED ISSUE #8008: Modal regression with scrollable areas
After #7934, opening a modal makes the scrollable area in the not-pinned column jump to top. Once the modal is closed, it jumps back to the old position.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by ykzts**
Resolve #8008

### CODE REVIEW

**Comment by ThibG** [comment]
There are a few more uses of `ScrollContainer`, most notably the detailed status view and the account media timeline.

**Comment by ykzts** [comment]
@ThibG Thank you 👍

The account media timeline does not open modal so it has not been fixed.

**Comment by ThibG** [comment]
Right, however the modal can be opened from another column, and the account gallery will still scroll to top

**Comment by ykzts** [comment]
> Right, however the modal can be opened from another column, and the account gallery will still scroll to top

Ah, that's right.

**Review by Gargron — APPROVED** [review]

**Comment by ykzts** [comment]
dry

**Pull request merged**
