### PR TITLE
Add explore page to web UI

### LINKED ISSUE #17620: Blocking doesn't work on Explore posts
### Steps to reproduce the problem

1. Go to the Posts section of Explore
2. Try blocking the author of one of the posts listed there
3. Their posts are still visible on Explore
...

### Expected behaviour

Posts from blocked authors should disappear from Explore

### Actual behaviour

Posts from blocked authors do not disappear from Explore

### Specifications

Tested this on Mastodon.online

Mastodon v3.4.6

Linux, Firefox 97

### PR DESCRIPTION
**Pull request by Gargron**
The explore page allows browsing trending statuses (#17431), trending links (#16917), trending hashtags, and follow recommendations. Furthermore, on mobile, the explore page provides the search form and renders the search results, with a tab style that allows filtering between all results, accounts, hashtags and statuses.

Posts:

image

News:

image

Search form on mobile:

Search results on mobile:

___

Fix #17620

### CODE REVIEW

**Comment by koyuawsmbrtn** [comment]
I hope this is getting worked on in the future. It looks great! :+1:

**Review by ykzts — APPROVED** [review]

**Comment by koyuawsmbrtn** [comment]
hot.

**Comment by mstdn** [comment]
Amazing work on the UI on this one! Where does this fit in on the multi-column?

**Comment by Gargron** [comment]
It seems that I forgot to link it in the advanced web interface, though it does look and work acceptably if you access it

**Comment by mackiexx** [comment]
I have installed the version that has this. version 3.5.0 but i can't see the explore page, do i need to turn it on somewhere?

**Pull request merged**
