### PR TITLE
Add ability to reorder uploaded media before posting in web UI

### LINKED ISSUE #9635: [Feature request] Ability to reorder attached images after uploading but before posting
### Pitch

I'd like to be able to reorder images attached to a post before clicking "toot". You can do it on Tumblr so it'd be good for that crowd, too.

### Motivation

When I find that I have uploaded images in the wrong order after adding image descriptions, it is a pain to delete images and re-upload them in the right order and copy and paste the image descriptions in from a notepad and so on.

### LINKED ISSUE #26460: Drag and drop pictures to change the sequence of the pictures
### Pitch

Drag and drop the pictures to change their sequence when posting a toot with two or more pictures attached.
Here is a show-how for this feature.
 
trim D0FBD2A4-DC11-4F46-B84E-1D8F1C0F0DE3

### Motivation

In current, if I messed up the sequence of the photos, the only thing I can do is delete and reupload these photos to correct the sequence. It is not convenient and wastes bandwidth.

### LINKED ISSUE #28437: Rearrange images in post editor after bulk upload
### Pitch

So, this is a problem I have been facing since day one. Suppose I want to share a couple of images in a particular order and I select them in file picker in proper order… Mastodon post editor would never get them in right order forcing me to reupload one image at a time to get them in order. 

This highlights another annoyance. The editor size changes during and after upload moving the upload and post button up and down. If the images can be rearranged after upload, this resolves both the ux/ui issues. 

### Motivation

This would improve user experience. Anyone who post multi-image posts on a regular basis would benefit from such a change.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #28437, fix #9635, fix #26460

### CODE REVIEW

**Comment by vmstan** [comment]
Also #26460

**Comment by ClearlyClaire** [comment]
This isn't easily discoverable, and I don't think this works on mobile, so it doesn't completely fixes the issue, but it's a very nice step forward!

**Comment by ClearlyClaire** [comment]
I took the liberty to change the destination branch, so this PR does not end up like #18474 when #28119 gets merged (apparently it automatically close the PR, and does not allow re-opening it or changing the destination branch once it's closed)

**Review by ClearlyClaire — APPROVED** [review]
Oops! Sorry I missed this PR! LGTM although we probably have something more discoverable and address mobile as well

**Comment by Sieboldianus** [comment]
Can someone describe how this fix works? I am on 4.2.8 but I cannot reorder images after bulk upload. The documentation for this feature is missing.

**Comment by vmstan** [comment]
It was merged into the `main` codebase which would be reflective of installs of 4.3 alpha or nightly right now. It wouldn't be backported to 4.2

**Pull request merged**
