### PR TITLE
Redirect user profile page to short URL when HTML format (regression from #3844)

### PR DESCRIPTION
**Pull request by ykzts**
### v1.4.7

```console
$ curl -H 'Accept: text/html' -sSI http://localhost:3000/users/user1 | grep Location
Location: http://localhost:3000/@user1
```

### master (`4b4ea1f`)

```console
$ curl -H 'Accept: text/html' -sSI http://localhost:3000/users/user1 | grep Location
```

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
introduced in 8c45cd0e3683b528b65f416681c8272d5650f32d but why?

**Comment by nightpool** [comment]
the actual content of that commit conflicts with the commit message, which
was "do not redirect /users/:username route if format is empty"—that should
be *unless* format is empty, according to the logic introduced.

**Comment by beatrix-bitrot** [comment]
so... missing !

?

**Comment by ykzts** [comment]
[`ActionDispatch#format`](https://github.com/rails/rails/blob/v5.1.2/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L50-L58) returns `Mime[:html]` when it can not be returned. It returns `nil` only if `request.format = nil` was explicitly specified.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
