### PR TITLE
Change Dockerfile to use distribution-provided Ruby

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This switches to ubuntu 22.04 and use the distribution-provided ruby, which is Ruby 3.0.2. The main reason is to avoid having to compile Ruby, which takes forever when building arm64 images (they seem to be built using qemu…)

TODO:
- [ ] add back jemalloc somehow (probably using `LD_PRELOAD`)
- [ ] test

### CODE REVIEW

**Comment by Gargron** [comment]
Which Ruby is it then?

**Comment by ClearlyClaire** [comment]
On ubuntu 20.04, it's 2.7 by default.

**Comment by Sjors** [comment]
Fwiw I made the mistake of upgrading my Linux box to 22.04 and I'm running into similar difficulties. It seems to require compiling OpenSSL 1.1.1 somewhere and then build Ruby 3.0.4 (with Rbenv). Haven't made much progress...

**Comment by shleeable** [comment]
The new stable LTS Jammy is out now...  once the openssl issues are solved.

Worth testing with the new base image and seeing if the smoke comes out :)

**Comment by ClearlyClaire** [comment]
Unfortunately, it requires quite a few dependencies to get fixed, and so far there's been no activity… we might need to fork those dependencies eventually :/

**Pull request closed without merging**
