### PR TITLE
Update webpack and related dependencies (without extract-text-webpack-plugin)

### PR DESCRIPTION
**Pull request by ykzts**
only minor and patch releases.

### CODE REVIEW

**Review by nightpool — DISMISSED** [review]

**Comment by Gargron** [comment]
To make sure: this does not re-introduce the live reloading bug, does it?

**Comment by nightpool** [comment]
withdrawing my review b/c I didn't know we had downgraded webpack previously https://github.com/tootsuite/mastodon/pull/4250

**Comment by ykzts** [comment]
Yes, that bug is caused by extract-text-webpack-plugin v3.0.0.

**Review by nightpool — COMMENTED** [review]
.

**Comment by nightpool** [comment]
(someone else feel free to review, I just don't feel comfortable doing so)

**Review by Gargron — APPROVED** [review]

**Pull request merged**
