### PR TITLE
Revert "Change language detector threshold from 140 characters to 4 words (#10376)"

### PR DESCRIPTION
**Pull request by carbon-twelve**
This reverts commit e6cfa7ab897ac4fd6bf9bbcafe09fc42c4cc2c5d.

For the background of this pull request, please take a look at issue #10578.
This is meant to be a palliative fix until we contrive a better solution.

### CODE REVIEW

**Comment by Gargron** [comment]
This is the wrong commit to revert. Japanese and Chinese languages are affected by the line below, `RELIABLE_CHARACTERS_RE`. It's not possible to revert with git automatically, because some of the follow-up commits are good.

**Comment by carbon-twelve** [comment]
`RELIABLE_CHARACTERS_RE` is not a thing here because this regular expression just decides if an input text should be passed to the language detector or not.
The problem lies after that decision: the language detector is not reliable enough.

So, I'd suggest we stop showing the results from the detector for now (this pull request), and also remove the detector completely or exclude Japanese at least later.

**Comment by carbon-twelve** [comment]
What kind of solution do you have in your mind instead?

**Comment by Gargron** [comment]
- Remove Han character set from `RELIABLE_CHARACTERS_RE` or
- Enforce minimum number of characters even for "reliable" character sets

**Comment by carbon-twelve** [comment]
It makes sense to me to remove Han character set as well as Katakana and Hiragana ones.
(which means disabling automatic language detection for Chinese and Japanese. Do I get it right?)

> Enforce minimum number of characters even for "reliable" character sets
I wouldn't go this way.
From my observations, it's not rare the language detector fails to classify toots correctly even if they contain Hiragana or they're more than hundred characters long.

**Comment by Gargron** [comment]
> It makes sense to me to remove Han character set as well as Katakana and Hiragana ones.
> (which means disabling automatic language detection for Chinese and Japanese. Do I get it right?)

Han is shared between multiple languages, but are Katakana and Hiragana?

**Comment by carbon-twelve** [comment]
I suggested removing them as containing those characters doesn't necessarily mean the results of the language detector is reliable.
I'd say such situation is common if not often.

**Comment by ykzts** [comment]
Resolve with #12124

**Pull request closed without merging**
