### PR TITLE
Only offer translation for supported languages

### PR DESCRIPTION
**Pull request by c960657**
LibreTranslate and DeepL.com do not support all languages in the world. Both engines support ~30 languages.

Trying to translate an unsupported language with DeepL.com pops up a warning message, _503 Service Unavailable_.

Only show the _Translate_ link when the source language is supported or nil.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by c960657** [comment]
Hmm, probably not. I'll look into it. Thanks :-)

**Comment by c960657** [comment]
I have created PR #23982.

**Comment by tribela** [comment]
Statuses from streaming cannot be translatable after this pr

**Comment by ClearlyClaire** [comment]
This is a known issue that is aimed to be fixed by #24037

**Pull request merged**
