### PR TITLE
Fix threaded replies to non-federated statuses not being filtered from the timeline

### PR DESCRIPTION
**Pull request by nightpool**
bug discovered by @vahnj. If someone you follow replies to a status your instance doesn't know about, it gets filtered. but if they continue replying in that thread, further replies don't get filtered. This adds logic to cover that edge case.

This also refactors the feed manager code because it's super out of date, and doens't use the account interaction maps. (lots of Follow.where(target_id: blah, account_id: blah))

### CODE REVIEW

**Comment by nightpool** [comment]
codeclimate won't let me dismiss false positives, but in order:

 - empty line at beginning of method is for docs (not sure if they're useful now that the code is more readable, but they're there)
 - = operator spacing is to align with the +=/||= on the next line

**Comment by akihikodaki** [comment]
rubocop says line 120, around which there is no `+=`, has an extra space.

**Comment by nightpool** [comment]
@akihikodaki fixes

**Comment by Gargron** [comment]
See 6fd865c0004efbf11ee87c06fea9f48af567fabe

You're reverting deliberate optimizations - this code is a performance hot spot and we want it to handle as little information as possible, thus passing it an integer and not a full account, and using batched checks for mutes, blocks etc.

If I'm reading correctly the actual fix is the line `return true if status.in_reply_to_account.nil? || status.in_reply_to_id.nil?`, which in old code would be `return true if status.reply? && (status.in_reply_to_account.nil? || status.in_reply_to_id.nil?)`

**Comment by nightpool** [comment]
@Gargron Since that code was written, the performance of muting?, blocking?, and following? have all been changed, and now the two alternatives create identical SQL queries, but one is much more readable and maintainable.

I'm not sure how passing an integer vs. a full account would change the performance in this case at all, seeing as everywhere we call it we are explicitly taking an id from a full activerecord object.

**Pull request closed without merging**
