### PR TITLE
Fix performance regression in Account::Field#verifiable?

### PR DESCRIPTION
**Pull request by Gargron**
Regression from #8703

### CODE REVIEW

**Comment by malicioustoker** [comment]
Bump

**Review by ClearlyClaire — APPROVED** [review]
Minor improvement possible according to CodeClimate, but I'm otherwise ok with it.
I wonder if we need `verifiable?` to be used at all when serializing, though. A `null` `verified_at` would be fine, right?

**Comment by ThibG** [comment]
@malicioustoker this is very unlikely: this is about an inefficiency in serializing any account, regardless of the timeline it appears in

**Comment by Gargron** [comment]
@malicioustoker @ThibG I have experienced local timeline slowness on one instance I ran for someone, but that was pre-2.5.0. The PostgreSQL server used a HDD and not an SSD on that machine, that's all that jumps to mind. There might be some working memory related issue where the local timeline query doesn't fit in there and so is unusually slow.

**Comment by Gargron** [comment]
I recommend playing around with this tool for your PG configuration: https://pgtune.leopard.in.ua/ Maybe it will help.

**Comment by malicioustoker** [comment]
Oh wow, great, thanks! I’ll report back after playing around with it. I really appreciate it!

-- Reverend Glen

**Comment by malicioustoker** [comment]
All the changes have been made, yet it made no difference with the long load time for the local timeline :-/

-- Reverend Glen

**Pull request merged**
