### PR TITLE
Move filtered notifications bar in scrollable area

### PR DESCRIPTION
**Pull request by oneiros**
Fixes MAS-276

This is my totally naive attempt to fix the disparity between regular and advanced interface, where the new "filtered notifications bar" would scroll away in the former but not in the latter.

I have absolutely no idea how the different components that are affected here interact and so might have overlooked a lot of problems this change might create. Feel free to discard this :slightly_smiling_face:

### CODE REVIEW

**Review by ClearlyClaire — DISMISSED** [review]
Looks good to me! Feels a bit weird conceptually, but it helps de-emphasize filtered notifications, help reclaim some screen estate, and is more consistent with the single-column interface.

I think the way it's implemented is ok, though an alternative could be to have it in `prepend`. I think the main difference with `prepend` is how it behaves if `scrollableContent` is empty.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
> I think the way it's implemented is ok, though an alternative could be to have it in `prepend`. I think the main difference with `prepend` is how it behaves if `scrollableContent` is empty.

Yeah, one difference is actually that this PR crashes when there are no unfiltered notifications due to our weird way of memoizing `scrollableContents` :sweat_smile:

In addition, I think we may need a minor style modification to avoid double borders and only keep the `border-bottom` on `.filtered-notifications-banner`.

**Comment by oneiros** [comment]
Well, I had a hunch it could not be _that_ simple :grimacing:

**Comment by ClearlyClaire** [comment]
> Well, I had a hunch it could not be _that_ simple 😬

Well, it would have worked in most other places, where we don't do that weird memoization :sweat_smile:

**Comment by oneiros** [comment]
> Yeah, one difference is actually that this PR crashes when there are no unfiltered notifications due to our weird way of memoizing scrollableContents 😅

How exactly does it crash? I did not notice anything.

**Comment by oneiros** [comment]
> How exactly does it crash? I did not notice anything.

Never mind. I missed the "un" in "**un**filtered" notifications :facepalm:

**Comment by oneiros** [comment]
Still not sure if this is going in the right direction, but I think I may have fixed both concerns (border and empty state).

**Review by ClearlyClaire — DISMISSED** [review]
I think I would have moved the `FilteredNotificationsBanner` component to the `prepend` prop of `ScrollableList` but this looks fine to me.

**Comment by ClearlyClaire** [comment]
The difference between `FilteredNotificationsBanner` being inside `prepend` or a child of `ScrollableList` is the following. Not sure which makes the most sense.

## `FilteredNotificationsBanner` as a child of `ScrollableList` (current state of the PR)

image

## `FilteredNotificationsBanner` as part of the `prepend` of `ScrollableList`

image

**Review by renchap — APPROVED** [review]

**Pull request merged**
