### PR TITLE
Pin all dependencies in Gemfile / Gemfile.lock

### PR DESCRIPTION
**Pull request by shleeable**
Read https://before-you-ship.18f.gov/infrastructure/pinning-dependencies/ and figured this is a good match with the recent dependabot change.

* Updates all semver from X.X.X
* Adds missing semver on Gems.
* Fixed minor Gemfile mistake.. binding_of_caller lockfile being ahead of Gemfile 0.7/0.8

Generated with https://github.com/ridiculous/drg

----

Notes: fog-core is still <= 2.1.0 due to #8889

### CODE REVIEW

**Comment by shleeable** [comment]
I can obviously move the semver on the Gemfile to X.X -- if you have a perference

**Comment by shleeable** [comment]
this is just a demo PR for drg.. Big G can decide to run it himself I guess?

**Comment by ThibG** [comment]
Not sure what the benefits of that are, as we already make use of `Gemfile.lock`. Also, what does “the recent dependabot change” refer to?

**Comment by shleeable** [comment]
> Not sure what the benefits of that are, as we already make use of `Gemfile.lock`. Also, what does “the recent dependabot change” refer to?

My pitch is the fact this updates the Gemfile.lock with explicit semver.. as it stands now, the Gemfile.lock is a mix of empty version and major.minor but only a few of them have patch

So I think this is worth doing for consistency at least? because the dependabot is the thing doing the upgrades, it's a safe change.

It just looks cleaner and pins everything to exact versions.

**Comment by shleeable** [comment]
I mean. you devs are the masters. If this is something you and big G actively don't want. that's that.

**Comment by ThibG** [comment]
The versions locked in the `Gemfile.lock` are the exact versions (in the `GEM` section). The `DEPENDENCIES` section just recalls what is in the `Gemfile`.

To be honest I don't think the `Gemfile` should ever mention patch versions unless there is some known incompatibility (and while I'm writing that, I'm noticing we don't do that for Paperclip, although it's the only Gem I'm aware we have an incompatibility with a patch version…)

**Comment by shleeable** [comment]
I'll close this.. but I still think it's worth having a review of the Gemfile.
1) there are 12 gems with no versions in the Gemfile.
```
- gem 'browser'
+ gem 'browser', '~> 4.0'
```

2) we switch between semver X.X and X.X.X alot... :)

**Comment by shleeable** [comment]
@ThibG https://github.com/shleeable/mastodon/commit/f3f44c1b151f87d3164c6972d103dd5f20b32998

Would that make more sense?

**Pull request closed without merging**
