### PR TITLE
Setup Husky and lint-stage for commit fixing

### PR DESCRIPTION
**Pull request by nschonni**
For those developing locally, it will trying and autoformat code during the commit process to ease failures before they hit CI.
This could probably work with the Ruby files as it is just a generic git hook, but I'm less confident in what the accepted tooling/paramters would be for that

### CODE REVIEW

**Comment by renchap** [comment]
lint-staged works fine for Ruby as well in my experience.

I have a local setup where I use it for Rubocop and `prettier-ruby` without any issues. Once Rubocop runs fine on all the repo, what would be blocking to enable it there as well?

**Comment by nschonni** [comment]
Added the additional glob so Prettier gets called on the CSS/SCSS files to match the changes in https://github.com/mastodon/mastodon/pull/23558

**Comment by nschonni** [comment]
Updated now that ESLint is checking JSX files, and moved the prettier run for all files, since things that shouldn't get touched are covered by the `.prettierignore` now.
I could add a call to `bundle exec rubocop -a` for the `*.{rb,rake}` or leave that for a later thing

**Comment by renchap** [comment]
I think adding Rubocop as well is a good idea overall, so +1 on this from me!

**Comment by nschonni** [comment]
@Gargron are you interested in this one, or should I close it?

**Review by Gargron — APPROVED** [review]

**Comment by neatchee** [comment]
@Gargron @nschonni This needs a bugfix...
When yarn is used for dependencies, npx should not be used for lint-staged
Instead we need to install lint-staged via yarn and change the husky script to use yarn instead of npx

**Comment by nschonni** [comment]
Didn't think that would be an issue since NPX ships with Node, but I've submitted https://github.com/mastodon/mastodon/pull/24287 to swap it to Yarn

**Comment by neatchee** [comment]
> Didn't think that would be an issue since NPX ships with Node, but I've submitted #24287 to swap it to Yarn

I wouldn't have guessed it was a problem either, but it threw errors for me and research showed this was a known problem elsewhere 🤷

**Pull request merged**
