### PR TITLE
Add lines to threads in web UI

### PR DESCRIPTION
**Pull request by Gargron**
This adds connecting lines between replies to the thread view.

Screenshot 2023-04-24 at 02-07-08 Foo (@admin@localhost)

___

Fixes MAS-128

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by Cassolotl** [comment]
Pretty good! I feel like the contrast could be a bit more extreme?

**Comment by ClearlyClaire** [comment]
I'm a bit confused by the line connecting up to the disembodied border. I wonder if it wouldn't work better with something like that:
image

**Comment by kmhcreative** [comment]
The thread lines are a start, but I still think this userScript does a better job of making the hierarchy of sub-conversations clearer: [https://github.com/afontenot/userjs/blob/master/mastodon/mastodon-threaded-replies.user.js](https://github.com/afontenot/userjs/blob/master/mastodon/mastodon-threaded-replies.user.js).  Those of us customizing the UI with userStyles still have nothing (at least that I can see) to differentiate the depth of replies.  Some kind of "data-depth" attribute on the element or a "depth-n" class on the "status-wrapper" DIV would at least provide a handle for customizing it.

**Comment by AndreiSva** [comment]
> I'm a bit confused by the line connecting up to the disembodied border. I wonder if it wouldn't work better with something like that (mockup only): image

i second this

**Pull request merged**
