### PR TITLE
Add Catalan language

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ykzts — CHANGES_REQUESTED** [review]
Are you working on the basis of the old master?

**Comment by salvadorpla** [comment]
I've just followed the instructions of https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating-Github-Cheat-Sheet.md

**Comment by ykzts** [comment]
> ### 3. Sychronize your master branch with Mastodon's master branch
> 
> ```shell
> git reset --hard upstream/master
> ```

Did you run the above command?

**Comment by salvadorpla** [comment]
no. Seems I need to, right ?

**Comment by salvadorpla** [comment]
I ran git remote add upstream https://github.com/tootsuite/mastodon.git

**Comment by ykzts** [comment]
That is very important. `master` is changing all the time, so it is often that changes to the old one can not be reflected.

**Pull request closed without merging**
