### PR TITLE
Use explicit `offset` (required attribute) value in wordmark svg

### PR DESCRIPTION
**Pull request by mjankowski**
Discovered during unrelated css/validation thing ... I think appearance should be unaffected.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I don't think this change is needed? Afaik this defaults to 0 and omitting it is valid?

**Comment by mjankowski** [comment]
> I don't think this change is needed? Afaik this defaults to 0 and omitting it is valid?

Yes, defaults to zero if missing -- but showed up as a required attribute (and thus html validation failure ... noticed while using validator for the unused css thing).

Fine to drop if we don't care about the validation thing, but that was the intent.

**Comment by ClearlyClaire** [comment]
Which validator did you use? Because the specs imply it defaults to 0 and I have never seen it misbehave ever.

**Comment by ClearlyClaire** [comment]
Alright, I'd say we'll do without this change then.

**Pull request closed without merging**
