### PR TITLE
smtp delivery type fix

### PR DESCRIPTION
**Pull request by foozmeat**
# Conflicts:
#	config/environments/production.rb

### CODE REVIEW

**Comment by tcitworld** [comment]
You should add a `SMTP_DELIVERY_METHOD` entry in the `.env.production` template.

**Comment by foozmeat** [comment]
@tcitworld I added that stub entry in .env.production

**Comment by tcitworld** [comment]
Maybe add also a comment to tell that the value can be `smtp` or `sendmail` ? And put this line before the other smtp-related ones ?

**Comment by foozmeat** [comment]
@tcitworld alright I made those changes

**Review by gllmhyt — APPROVED** [review]
This would greatly improve the use of a local sendmail when we have a local send-only mail service.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
