### PR TITLE
Delete migrations created prior to version 3.0

### PR DESCRIPTION
**Pull request by mjankowski**
Opening this based on discussion in chat and in https://github.com/mastodon/mastodon/pull/24270#issue-1640971599

For first pass, I'm only deleting the old migrations. Will watch CI failures to see what scripts/checks need update as well and push more after that.

Will rebase against main after https://github.com/mastodon/mastodon/pull/27513 is merged and regenerate the rubocop todo to remove old migrations from that as well.

### CODE REVIEW

**Comment by mjankowski** [comment]
> Oh, I thought this would be straightforward because the CI tests only start with 2.0.0… but this means they don't have a schema to start with, hm :/

Yeah, I had same hope -- and if we werent worrying about upgrade path for old versions, and/or werent running these CI data checks ... we'd just have the CI suite use `db:schema:load` (for local dev as well) and be done with it. But if we're going to preserve the checks of the old runs, they need to start from that snapshot in time, not the current snapshot in time.

> It would probably make sense to remove some of the old migrations and tests (probably at least to 3.0.0), but I believe having tests even for updating from EOL'd versions is very useful to ease the update process for admins.

Another approach here would be to require the upgrade path be that you actually do upgrades one minor version bump at a time. So lets say there's some instance still running v2.9.2 and they want to upgrade ... instead of jumping straight to 4.2 and running all the migrations, they'd have to: update to 3.0.x, run migrations, update to 3.1.x, run migrations, 3.2x, migrate, 3.3, migrate, etc... until they got to 4.2. We could ensure that each tagged version retains at least enough migrations to go from the last minor versions end state up to itself ... and what we'd probably want to do there would be to make sure that all of the still-maintained non-EOLd stable version branches have whatever specs are relevant to ensuring those migrations still run and (if necessary) any related data checks still work.

With that approach, I think we could delete *a lot* of migrations from main to merge into 4.2.x or 4.3.x, but just leave the other stable branches as-is, and make sure those instructions are captured somewhere?

**Comment by renchap** [comment]
I dont like doing this with minor versions, especially if we manage to go with the 3-4 minor version per year schedule we want to have.

I think that if we go with such a required upgrade path, I would prefer to have people:
- first upgrade to the latest version of their current major
- then upgrade to the next major

This would allow to drop every < 4.0 migration, which would help here?

**Comment by mjankowski** [comment]
Yeah I think from a code change perspective, doing the pattern will work regardless of what the frequency of it is. You are correct that from an upgradability/velocity perspective it may be better to have the actual frequency just be major versions so you can step through them more easily.

So to think this through a bit, if we removed all migrations from pre-4.0 from main, and also removed the old data migration checks from main, then:

- We'd get the cleanup benefits from this change
- We'd have CI and local dev envs just use db:schema:load for setup
- Anyone already on 4.x would continue to get any new migrations we added and run them as normal
- In the event we identify any data cleanup/migration things worth adding specs for related to the 3.x->4.x transition, we'd add specs and/or CI tasks for them.
- Anyone on 3.x would be required to upgrade to latest 3.x first before upgrading to 4.x
- Anyone running 2.x would upgrade first to latest 3.x and then to a 4.x
- In the event we ever discovered a flaw in any of the older data migrations, and also wanted to fix it even though it's in an EOLd version, we would do work in the old `stable-3-x` branch, and release a new 3.x.x version which would contain those migration fixes, and then anyone doing an upgrade from 2.x would get that first before they bumped to 4.x

**Comment by ClearlyClaire** [comment]
I am definitely against requiring updating through minor or patch updates because versions can become uninstallable as e.g. dependencies are removed from npm or rubygems repositories, which has happened more than once in Mastodon's history.

> and also removed the old data migration checks from main, then

We don't want to remove them. We can remove some of them, but not all. It's still very useful to catch bugs, especially regressions, and has helped several times in the past.

> We'd have CI and local dev envs just use db:schema:load for setup

This is only part of a specific Github Action workflow, it does not need to be used for local dev envs.

**Comment by mjankowski** [comment]
> I am definitely against requiring updating through minor or patch updates because versions can become uninstallable as e.g. dependencies are removed from npm or rubygems repositories, which has happened more than once in Mastodon's history.

Makes sense, combined with renchap observation about release frequency as well. Are you ok with the idea of having thresholds for dropping old migration at each MAJOR release version instead?

> > and also removed the old data migration checks from main, then
> 
> We don't want to remove them. We can remove some of them, but not all. It's still very useful to catch bugs, especially regressions, and has helped several times in the past.

I may have overstated the intention. To clarify a bit here, my suggestion was not to totally remove the checks from everywhere -- but to only include the checks in maintained branches where they are actually useful to the relevant data checks. For example, if we did go the dropping-migrations-at-major-releases path, and the earlier migrations being checked in the current "one step" workflow were removed, I think it would make sense to remove (or at least remove some of, I'd have to look closer) those portions from the branches/releases which no longer have those migrations ... but it would make sense to keep them in place in prior version stable branches which would still be running those migrations in an upgrade path. If there were similar critical data updates in newer releases, it would absolutely make sense to add in similar checks to newer versions/branches.

> This is only part of a specific Github Action workflow, it does not need to be used for local dev envs.

Yeah, fair enough - GH Actions would use that approach, local devs could do whatever they are used to. The only caveat there is that if older migrations are removed, I think we would in fact lose the ability to totally migrate from scratch, and you would have to at least start with a `db:schema:load` (via setup script, or direct on CLI or whatever) even if you then subsequently just ran migrations as they were added. I think this approach is the framework-endorsed expectation for local dev.

**Comment by ClearlyClaire** [comment]
> Are you ok with the idea of having thresholds for dropping old migration at each MAJOR release version instead?

I'm ok with dropping at least some of them, I'm not completely sure about a more general policy yet, but considering the age and usage statistics, I think it's fairly reasonable to drop support for migrating from earlier than 3.0.0, but I'm not very comfortable with restricting further.

I think generally, the cost of maintaining the migration scripts is lower than the cost of making sure there exists a migration path.

> I may have overstated the intention. To clarify a bit here, my suggestion was not to totally remove the checks from everywhere -- but to only include the checks in maintained branches where they are actually useful to the relevant data checks. For example, if we did go the dropping-migrations-at-major-releases path, and the earlier migrations being checked in the current "one step" workflow were removed, I think it would make sense to remove (or at least remove some of, I'd have to look closer) those portions from the branches/releases which no longer have those migrations ... but it would make sense to keep them in place in prior version stable branches which would still be running those migrations in an upgrade path. If there were similar critical data updates in newer releases, it would absolutely make sense to add in similar checks to newer versions/branches.

I actually think this is more important in `main`, where new migrations are introduced, rather than in stable branches, where migrations are very rarely used.

> The only caveat there is that if older migrations are removed, I think we would in fact lose the ability to totally migrate from scratch, and you would have to at least start with a `db:schema:load` (via setup script, or direct on CLI or whatever) even if you then subsequently just ran migrations as they were added. I think this approach is the framework-endorsed expectation for local dev.

Ah, right. I usually do `db:reset`, which loads the schema dump, so I wouldn't run into issues, but other people might, depending on their workflow.

Also, if we do remove old migrations, and someone tries to update from a version earlier than supported, we also need to make sure they get a meaningful error message instead of having their database end up in a weird state.

**Comment by mjankowski** [comment]
> I think generally, the cost of maintaining the migration scripts is lower than the cost of making sure there exists a migration path.

Is that another way of saying to just not bother with the effort to remove old migrations here? ... or just that you want to be sure whatever we do does not create more burden without corresponding benefit?

> I actually think this is more important in `main`, where new migrations are introduced, rather than in stable branches, where migrations are very rarely used.

Yes, I simultaneously agree with both:

- Having these checks running in main is way more important b/c to the extent someone is going to accidentally break something, its almost certainly not going to be on a maintenance branch and is probably going to be on main so the benefit there is way more useful; but at the same time...
- If we delete the migrations which were relevant to the data integrity check scripts on CI, I'm not sure what it is we'd run on CI in main (until there are newer integrity checks to add).

> Also, if we do remove old migrations, and someone tries to update from a version earlier than supported, we also need to make sure they get a meaningful error message instead of having their database end up in a weird state.

Yup, I think we need to make sure we throw an error in that case, and we might also want to consider the extent to which this change itself (not being able to migrate from scratch) is a breaking change or not, and what version it lands in.

So I guess, not sure what direction to go here. For prior art, it looks like GitLab (which has the same problem of being a distributed package where they can never be sure that every production deployment is updated or not yet) has decided to just have a policy of never deleting - https://docs.gitlab.com/ee/development/database/deleting_migrations.html

**Comment by ClearlyClaire** [comment]
> Is that another way of saying to just not bother with the effort to remove old migrations here? ... or just that you want to be sure whatever we do does not create more burden without corresponding benefit?

I'm not opposed to removing very old migrations (as said earlier, I think it's safe to remove migrations earlier than 3.0), but I'd like to be sure it does bring benefits.

> If we delete the migrations which were relevant to the data integrity check scripts on CI, I'm not sure what it is we'd run on CI in main (until there are newer integrity checks to add).

I mean we'd at least keep the CI tasks for the migrations in the last supported X major releases.

**Comment by mjankowski** [comment]
Ok, I'll update this to remove things prior to 3.0, and attempt to clean up CI in a way that seems sensible.

We can re-review after that and see if this actually feels like an improvement once it's passing.

**Comment by mjankowski** [comment]
Updated, including:

- Removal of all migrations earlier than the latest one from 2.9.4, which I believe from looking at https://github.com/mastodon/mastodon/tree/v2.9.4/db/migrate is 20190529143559. The 3.0 tag has ~20 more recent than that - https://github.com/mastodon/mastodon/tree/v3.0.0/db/migrate
- Removed the CI workflows which were testing data migrations specific to the version 2.x series of migrations/data.

If this PR were merged and released as part of 4.3, it would require that anyone running a version older than 3.0 upgrade to 4.2 first and run migrations there to get all up to date before upgrading to 4.3. Anyone running 3.0 or newer could go straight (at least from perspective of migrations) to 4.3, because those are all still included and would be run.

I have not yet added a warning/error for the scenario where a database which is not yet up to or newer than the latest removed migration tries to migrate. Assuming we want to actually go this direction, I can add somthing here. I think the most obvious thing is that instead of deleting that very last migration, just update it (keep it's timestamp number) and have it raise a useful error.

**Comment by ClearlyClaire** [comment]
> Removed the CI workflows which were testing data migrations specific to the version 2.x series of migrations/data.

I strongly disagree with that, but I feel like I may not have given enough background into these tests.

They test both that the migrations run at all, and that the data migrations work as expected. We had cases of both breaking in the past, sometimes due to the migrations being plain wrong, sometimes due to `strong_migration` updates or updates to the Mastodon code, which the migrations have an over-reliance on.

Those things are definitely still worth checking.

As for the `populate_v*` tasks, they were written in this way for a mix of targetting explicit migrations, and limiting the number of `populate_v*` tasks, meaning test data is generally not populated right before migration involving them are run, but potentially much earlier. For instance, the `settings` stuff populated in the 2.4.3 task is mostly relevant for a 4.2 migration.

Therefore, I think the tests should be kept, and the `populate_v*` tasks lifted to a `populate_v3_0` task.

**Comment by ClearlyClaire** [comment]
I'm honestly fine with either:
1. keeping all migrations
2. occasionally removing old migrations (and v3.0.0 seems like a safe cutoff for now), as long as this is documented, fails in a meaningful way, and we still keep testing migrations from the earliest supported database schema

I'm afraid I'm not sure which of these two paths has the most benefits at the moment, although I suppose at some point in the project's lifetime, the second option will probably have clear benefits.

> Tangentially, in a world where "lets just keep all the migrations in place and adopt a policy that you should always be able to migrate from scratch" is the decision here, are you open to PRs which either a) reduce dependence on project code of old migrations, b) otherwise improve old migrations using newer methods, c) update things re: strong_migrations interaction -- provided that none of those changes alter the original behavior/purpose of the migration?

I'm open to those 3 options; I try to avoid dependency on project code in new migrations, and we fixed old migrations when issues have arisen, but it would also make sense to do it more proactively.

**Comment by mjankowski** [comment]
Closing this in favor of either a) just doing nothing at all, b) doing something like https://github.com/mastodon/mastodon/pull/27591 instead.

**Pull request closed without merging**
