### PR TITLE
Remove unneeded settings cleanup from specs

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Review by mjankowski — APPROVED** [review]
Is the idea here that we don't really care about the global state or default values of any of these within the spec runs -- and where it does matter we can just explicitly set it in a before and then not bother with teardown/cleanup?

**Comment by ClearlyClaire** [comment]
The idea is that we don't need our own teardown/cleanup code, it should be handled by rspec.

**Comment by mjankowski** [comment]
> The idea is that we don't need our own teardown/cleanup code, it should be handled by rspec.

Ah - I see that there's an `Rails.cache.clear` in an around block at the suite config level ... which is going to reset these all on each example?

**Comment by ClearlyClaire** [comment]
Yeah, those are stored both as a database column and as a Rails cache entry, so everything should be handled by the test transactions and the `Rails.cache.clear` call already.

**Comment by mjankowski** [comment]
Cool - I was confused at first because I had these mentally in the same bucket as the Rails.configuration settings -- but yes, given those details this is better and should be safe.

**Review by renchap — APPROVED** [review]

**Pull request merged**
