### PR TITLE
tootctl media remove: Add option for unscoped media only

### PR DESCRIPTION
**Pull request by smiba**
Prevent the removal of media that is referenced, similar to the media vacuum scheduler

Right now it removes content regardless of reference, which seems unwanted for most uses.
I've made this an optional setting to keep backwards compatibility, but I honestly would consider making this the default.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
`unscoped` does not mean what you think, it means the `default_scope` (here `order(id: :asc)` does not apply.

What you mean is probably `unattached`, but normally, remote unattached media files are deleted immediately, and local unattached media files are deleted after 24 hours (they are otherwise kept to allow the “delete & redraft” flow).

**Comment by smiba** [comment]
Possibly? I couldn't easily figure out what the meaning of `unscoped` was, other then that it was also used in the vacuum scheduler and in my dev environment using `unscoped` properly referenced the amount of accounts that were entirely unfollowed.

With this PR (+ a unfinished PR I'm working on to filter on domain, but it's unrelated to this) the amount of accounts affected accurately reflected the accounts that had no connections

```
$ RAILS_ENV=production bin/tootctl media remove --dry-run --prune-profiles --days -1 --domain panic.com
Visited 1 accounts and removed profile media totaling 190 KB (DRY RUN)
```

```
$ RAILS_ENV=production bin/tootctl media remove --dry-run --prune-profiles --days -1 --domain panic.com --unscoped-only
Visited 1 accounts and removed profile media totaling 0 Bytes (DRY RUN)
```

If you're confident this is wrong, I'll close this PR and make an issue instead. Because I don't think it's right that running `tootctl media remove --days 30` removes all cached content regardless of these posts being interacted with (bookmarked etc.), but maybe I'm entirely wrong in understanding how the vacuum scheduler for the "Media cache retention period" option works. But as far as I was able to read it should leave referenced items untouched, but it's hard to find documentation on how this function behaves exactly.

**Comment by ClearlyClaire** [comment]
Yes, `unscoped` is just to remove the `default_scope`, which isn't set for `Account` and is set to `order(id: :asc)` for `MediaAttachment`

```
irb(main):003:0> MediaAttachment.select(:id).explain
  MediaAttachment Load (0.5ms)  SELECT "media_attachments"."id" FROM "media_attachments" ORDER BY "media_attachments"."id" ASC
=>                                                                        
EXPLAIN for: SELECT "media_attachments"."id" FROM "media_attachments" ORDER BY "media_attachments"."id" ASC
                                QUERY PLAN                                
--------------------------------------------------------------------------
 Sort  (cost=18.54..18.99 rows=180 width=8)                               
   Sort Key: id                                     
   ->  Seq Scan on media_attachments  (cost=0.00..11.80 rows=180 width=8)
(3 rows)                                            
                                                    
irb(main):004:0> MediaAttachment.unscoped.select(:id).explain
  MediaAttachment Load (0.3ms)  SELECT "media_attachments"."id" FROM "media_attachments"
=>                                                                                                                   
EXPLAIN for: SELECT "media_attachments"."id" FROM "media_attachments"                                                
                             QUERY PLAN                                                                              
--------------------------------------------------------------------                                                 
 Seq Scan on media_attachments  (cost=0.00..11.80 rows=180 width=8)           
```

**Comment by ClearlyClaire** [comment]
> Because I don't think it's right that running `tootctl media remove --days 30` removes all cached content regardless of these posts being interacted with (bookmarked etc.).

This is indeed what they both do, but those should be re-downloaded as needed.

**Comment by ClearlyClaire** [comment]
No problem!

**Pull request closed without merging**
