### PR TITLE
Remove setting for unfollow confirmation modal, and make it unconditional

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by trwnh** [comment]
...why? this seems like a step backwards for no clear reason.

**Comment by ClearlyClaire** [comment]
Unfollowing is a socially loaded, potentially destructive action that is easy to do by mistake (e.g. misclicking), and the recent interface changes have made it more confusing (currently, the button just says “Mutual” if the person is following you back).

Furthermore, while this confirmation modal is now on by default, for a long time it has been opt-in, so long-time users may have it disabled without any conscious decision on their end.

I was the one to add this modal years ago, and I made it opt-in without a real rationale. I don't think there's much of a reason for it to be optional.

**Comment by ClearlyClaire** [comment]
> Having a confirmation for every single unfollow can be too much, especially if you want to clean out your follows.

There's a batch management page at `/relationships` for that.

**Comment by listerine420** [comment]
why would misclicks warrant forcing intrusive popups, users can just reclick? and if something is confusing causing mistakes, then the source of confusion should be fixed...

**Review by Gargron — APPROVED** [review]

**Pull request merged**
