### PR TITLE
Match ruby version in lockfile to version in `.ruby-version`

### PR DESCRIPTION
**Pull request by mjankowski**
I don't know if we can configure renovate to do this update as well when it bumps the `.ruby-version` ?

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Is there a benefit in doing that?

**Comment by mjankowski** [comment]
Keeping them in sync seems fun?

**Comment by vmstan** [comment]
> Keeping them in sync seems fun?

I like your style.

**Review by ClearlyClaire — APPROVED** [review]
I don't see the harm, but I don't see the need for the change either.

**Pull request merged**
