### PR TITLE
Use .dotextension to get .jpeg

### PR DESCRIPTION
**Pull request by saper**
Reported: https://discourse.joinmastodon.org/t/api-media-post-bug-on-jpg-jpe-extension/257/3

not tested at all yet

### CODE REVIEW

**Comment by akihikodaki** [comment]
Could you tell me what version you used to reproduce the bug?

**Comment by Gargron** [comment]
This might not be a fix. If dotextension uses the provided extension from the original filename, and merely checks if against content type, then it may allow empty extensions, which the original code is meant to fix. My question is: is "jpe" not a valid extension? And if so, why is it being returned by MIME::Types?

**Comment by mal0ki** [comment]
.jpe seems to be used as a JPEG file extension 
https://en.wikipedia.org/wiki/JPEG

> Filename extension	.jpg, .jpeg, .jpe .jif, .jfif, .jfi

**Comment by saper** [comment]
The problems is OP is sometimes getting .jpe, sometimes .jpeg - do I understand this correctly @cquest ?

**Comment by Gargron** [comment]
It sounds like .jpe is a valid extension and this fix undoes another fix, so I am closing this PR.

**Pull request closed without merging**
