### PR TITLE
Change from British to American way

### PR DESCRIPTION
**Pull request by ghost**
... It's the American way

### CODE REVIEW

**Comment by thurloat** [comment]
👎 I much prefer the British / Canadian version.

**Comment by Gargron** [comment]
Honestly the US spelling just looks strange to me.

**Comment by Spunkie** [comment]
@Gargron It doesn't really matter which way it is as long as it is consistent across the project. If you like the british spelling than everything should use `en-GB `spelling and vise versa for `en-US` spelling.

The project should formally pick one and then make it's use clear in [CONTRIBUTING.md](https://github.com/tootsuite/mastodon/blob/master/CONTRIBUTING.md)

**Comment by yiskah** [comment]
This is pedantic. If you want to create separate localizations for american versus UK english where the only difference is the existence of a "u" then be my guest but that would be a different pull request.

**Pull request closed without merging**
