### PR TITLE
Extended status and account search

### LINKED ISSUE #21627: Enable searching of all toots
### Pitch

Currently, searching on Mastodon in possible by linking an Elasticsearch instance. When enabled users are able to search the content of posts they have made, or have interacted with. Posts the user has no direct connection with are filtered out of the search results.

From other issues discussing it, the potential for searching to be abused is stated as an important reason this should never be implemented. In my view this is disproportionate and likely counter-productive. For example, I am an admin on my server and I am unable to use built-in search functions to identify violating content so cannot be proactive in identifying abuse.

As search is backed by elastic, I'm free to write my own frontend to search content without using the mastodon interface. This would be easy enough to do, but it fractures the user experience and creates security issues - particularly in exposing search functionality to other users.

### Motivation

As much as the potential to proactively identify abuse, the ability to search for content would be a big bonus for any user.

I think the idea that abuse might happen therefore it shouldn't be implemented it is patronising. Search functionality is already optional, and it would be better to fully support it within the application than lose control of user data through external integrations. If a server does experience abuse as a result of allowing search it should be able to deactivate it easily, or restrict the ability of individual user accounts to search content that isn't their own.

### PR DESCRIPTION
**Pull request by VyrCossont**
- ~~Extends status search to cover public discoverable statuses~~
- Sorts status search results by creation date
- Adds account ~~bio and~~ tag search for discoverable accounts
- Adds filter, sorting, and date range operators to search query syntax
- Fixes search parser to parse URLs correctly

Simplified from VyrCossont/mastodon#5

~~Fixes: mastodon/mastodon#21627~~

Related: mastodon/mastodon#23808 mastodon/mastodon#24046

### CODE REVIEW

**Comment by VyrCossont** [comment]
Draft because #23808 and #24046 are still open, `domain:` search for the local domain isn't implemented yet, and there's still some lint to clean up.

**Comment by ClearlyClaire** [comment]
> Extends status search to cover public discoverable statuses

I would personally leave that out until we have a consensus on how to express consent in a more explicit and robust way.

> Adds account bio

I'm a bit uncomfortable with that for the same reasons.

> Sorts status search results by creation date
> Adds filter, sorting, and date range operators to search query syntax

Those are really good and I'm excited to have them merged!

**Comment by VyrCossont** [comment]
> > Extends status search to cover public discoverable statuses
>  
> I would personally leave that out until we have a consensus on how to express consent in a more explicit and robust way.

Sure, it makes sense to split those into another PR to wait for #23808 and related discussions to finish.

> > Adds account bio
> 
> I'm a bit uncomfortable with that for the same reasons.

I can also split this out, but did I miss an issue with `discoverable` as the consent mechanism here? Non-discoverable profiles wouldn't have bio, tags, or custom emoji indexed, same as now.

**Comment by ClearlyClaire** [comment]
> I can also split this out, but did I miss an issue with `discoverable` as the consent mechanism here? Non-discoverable profiles wouldn't have bio, tags, or custom emoji indexed, same as now.

I think my issue is basically that it changes the current behavior in a way that users may not expect. One thing some users (incorrectly) expect is hashtags-in-bio to be searchable, for instance. I don't think such users expect their non-hashtag bio content to be searchable.

**Comment by VyrCossont** [comment]
Catching up from Discord discussion: I've removed full-text indexing of public statuses from discoverable accounts, and full-text indexing of all account bios, pending #23808 or something like it. This PR is now just additional non-text index fields, filter/sort operators that use them, and bug fixes.

**Comment by VyrCossont** [comment]
I'd appreciate some guidance on documenting the new operators. Adding them all to the search popover makes it very long:

image

**Comment by j-f1** [comment]
Some feedback / ways to filter it down:

- `-term` is already documented at the top so e.g. `-is:bot` doesn’t need to be documented
- It should say “posts” instead of “statuses” IMO
- I would move the `cat has:media` one up to the top (maybe below the `"John Mastodon"` one?) so it doesn’t get missed
- Consider replacing `sensitive:yes` and `sensitive:no` with `is:sensitive` and `-is:sensitive`; that combined with the first suggestion would remove one item from the list
- Maybe add a couple of words to explain the difference between sensitive content and content warning?
- If it’s easy, maybe add `to:` as an alias for `mentions:` for Twitter compatibility? I’m not sure if it’s actually a good name though.
- Similarly, maybe add `date:<2022-12-17` `date:>2022-12-17` `posted:<2022-12-17` `posted:>2022-12-17` as aliases? (I think it might be good to have a few more aliases than explicitly documented so that folks trying to search can easily find what they want with intuitive terms rather than having to guess the syntax) (e.g. `server:` instead of `domain:`, `is:following` for `scope:following`, `has:image/audio/video` for `has:media`, `has:url` for `has:link`, `mention:` for `mentions:`, `has:cw`, `has:spoiler` for `has:warning`)

**Comment by Gargron** [comment]
Discord's search popout is done really well. We could aim to replicate it. As a first pass I'd say the popout could be left out.

**Comment by VyrCossont** [comment]
> Discord's search popout is done really well. We could aim to replicate it. As a first pass I'd say the popout could be left out.

Discord's search popout also has a `(?)` button that links to the Discord help website for more detail. Looks like our equivalent would be an on-server help page like https://mastodon.social/keyboard-shortcuts; what if I moved the advanced section there?

**Comment by VyrCossont** [comment]
> Some feedback / ways to filter it down:

Thanks for taking a look!

>  * `-term` is already documented at the top so e.g. `-is:bot` doesn’t need to be documented

It might not be obvious that operators as well as search terms can be negated, so I wanted at least one example of that. Given that we're strapped for vertical space, though, I can remove it.

>  * It should say “posts” instead of “statuses” IMO

You're absolutely right. I accidentally matched the default messages, not the actual localized strings.
 
>  * I would move the `cat has:media` one up to the top (maybe below the `"John Mastodon"` one?) so it doesn’t get missed

Good idea.

>  * Consider replacing `sensitive:yes` and `sensitive:no` with `is:sensitive` and `-is:sensitive`; that combined with the first suggestion would remove one item from the list

Eugen asked for `sensitive:yes` and `sensitive:no` in his review comments on this patch's predecessor, VyrCossont/mastodon#5. `is:sensitive` and `-is:sensitive` are still supported as synonyms.

>  * Maybe add a couple of words to explain the difference between sensitive content and content warning?

Looking at the [user-facing docs](https://docs.joinmastodon.org/user/preferences/#sensitive), "sensitive media" seems to be the preferred phrasing.

>  * If it’s easy, maybe add `to:` as an alias for `mentions:` for Twitter compatibility? I’m not sure if it’s actually a good name though.

It's easy enough.

>  * Similarly, maybe add `date:<2022-12-17` `date:>2022-12-17` `posted:<2022-12-17` `posted:>2022-12-17` as aliases? (I think it might be good to have a few more aliases than explicitly documented so that folks trying to search can easily find what they want with intuitive terms rather than having to guess the syntax) (e.g. `server:` instead of `domain:`, `is:following` for `scope:following`, `has:image/audio/video` for `has:media`, `has:url` for `has:link`, `mention:` for `mentions:`, `has:cw`, `has:spoiler` for `has:warning`)

The original actually did use `has:cw`, and Eugen also suggested `has:spoiler` so maybe we just put all three in there so it's easy to guess. I don't know that we need *too* many synonyms, but the common ones users might expect from Twitter, Discord, etc. can definitely be added in a followup.

**Comment by shleeable** [comment]
`has:image` `has:audio` `has:video` would be interesting over `has:media`, if those values are stored anywhere.

**Comment by VyrCossont** [comment]
Added `to:` as a synonym for `mentions:` and `has:image`, `has:video`, etc.

I've also pulled search help out to its own page, leaving the popover alone for now:

search help displayed in a help page like keyboard shortcuts

**Comment by trwnh** [comment]
i'm concerned about `mentions:` as a filter. you could use this to stalk people's mentions even if they block you.

also would like to see a scope:personal that includes not only people you follow, but also posts you've interacted with (faved, bookmarked, boosted, replied to)

`-has:warning` seems redundant, it should be implied by operator negation

also wondering about the use-case of filtering for warning/sensitive, especially as two separate things, since one currently implies the other.

also also: why `sensitive:yes` and `sensitive:no` instead of `is:sensitive` and `-is:sensitive`?

**Comment by VyrCossont** [comment]
> i'm concerned about `mentions:` as a filter. you could use this to stalk people's mentions even if they block you.

Yeah, that's plausible. Right now you'd have to have interacted with posts containing mentions for them to come up in search, but that won't always be true.

You need to be logged in for search operators to work; what's the appropriate way to check if the account used in a mentions filter has the current account blocked?

> also would like to see a `scope:personal` that includes not only people you follow, but also your own posts and posts you've interacted with (faved, bookmarked, boosted, replied to). this approximates the "classic" scope while filling in a few gaps

This PR doesn't widen the search scope; I took that functionality out until we decide how to handle opt-in, so `scope:classic` or `scope:personal` aren't currently necessary but we could certainly add them when we widen the search scope.

> `-has:warning` seems redundant, it should be implied by operator negation

An earlier pass didn't have the explicit negation example. I can take it out.

> also wondering about the use-case of filtering for warning/sensitive, especially as two separate things, since one currently implies the other.

One implies the other but CWs are used for way more than just sensitive media. You might search for `-has:cw` to find posts without CWs to display on a video wall, `facebook has:cw` because you remember a long thread about the coming apocalypse that had a CW on it, or `maytag is:sensitive` to find the lewd art someone drew of your washing machine OC.

> also also: why `sensitive:yes` and `sensitive:no` instead of `is:sensitive` and `-is:sensitive`?

As I noted above, Eugen requested this in the comments to VyrCossont/mastodon#5. I'd personally prefer `is:sensitive` and `-is:sensitive` for consistency; currently, they're supported as synonyms.

**Comment by VyrCossont** [comment]
@trwnh 4ee1df7 prevents positive `from:` or `mentions:`/`to:` filters from being used with an account that blocks the searching account. `StatusFilter` would have already blocked any results from being shown for a `from:` query on a blocking account, but this stops the query before the search is even executed.

**Comment by trwnh** [comment]
> https://github.com/mastodon/mastodon/commit/6942d2699b3211c23d4ad8d7f2577e432eeb887a prevents positive from: or mentions:/to: filters from being used with an account that blocks the searching account.

this is an improvement, but i'm still uncomfortable with the general idea of stalking someone's mentions... the only real measure against this kind of stalking would be asking people to not mention you in a searchable context. but as long as it's limited to the "classic scope" where you have to interact with it, then a `mentions:` filter isn't that bad. so maybe it should be only usable with `scope:` or perhaps implies `scope:`? where `scope:` is either "following" or "personal". of course this is something that can be deferred until scope-widening is on the table.

**Comment by VyrCossont** [comment]
That's a reasonable privacy/functionality tradeoff. Let's include that `mentions:` dependency on a reasonable `scope:` when we do wider search.

**Comment by vivlim** [comment]
Why was this closed?

**Comment by vivlim** [comment]
@Gargron Why was this closed?

**Comment by Gargron** [comment]
Expanding search functionality and adding extra search syntax is still part of our public roadmap, however, due to hostile offsite behaviour by the author, we cannot collaborate any longer. The features will be completed by our own team.

**Pull request closed without merging**
