### PR TITLE
Add setting to explicitly consent to full-text search indexing of public posts

### PR DESCRIPTION
**Pull request by ClearlyClaire**
NOTE: This PR does not implement the search functionality itself, just a framework to express explicit consent for posts to be indexed

Mastodon has historically refused to provide full-text search functionality outside of interacted posts to avoid harassment, “reply guys” and other issues.

Since Mastodon users post in “public” under that assumption, a post being “public” cannot be understood as consent from the user for having their post indexed, and Mastodon currently lacks any framework for users to give their consent for a feature that would be useful and that some people are very adamant about.

This PR aims to add such an explicit consent option in the form of a new per-post `indexable` attribute on `Status` entities in the REST API and a `toot:indexable` (shortened as `indexable`) in the ActivityPub representation.

The API allows setting the information per-post, but the UI does not. Instead, the user is presented with the following option:
image

The option tries to highlight that not giving consent does not prevent bad actors from indexing the posts anyway.

## TODO

- [ ] make it visible in the Web UI whether a post is indexable or not
- [ ] add tests
- [ ] figure out if we should switch `toot:indexable` for something else
- [ ] (optional) add the option to override indexability per-post in the WebUI

### CODE REVIEW

**Comment by trwnh** [comment]
Is there a reason why we can't just re-use `toot:discoverable` but apply it to statuses instead of just accounts?

**Comment by supernovae** [comment]
If mastodon wants to have a security/permission-based system - **I am 100% behind this** - but it shouldn't assume that the fediverse will respect this unless such a system is part of the protocol and can be assured by the protocol.  

Benefits of search on public posts for my users

* User content discovery - new user abandonment has plummeted big time with search. After adding search, my monthly active users for the past 3 months recovered after a huge cliff/drop off.
* Hashtag search is better with full text search - the combination is a great UX (operators!)
* Search can improve people discovery if people opt in for people discovery (still a huge problem and a potential nightmare problem if/when twitter api for twitter searches are finally shut down)
* Search can provide benefits over other social systems.  Modifiers for media mean app developers can have media centric pages. Modifiers for instance types means lists can have saved searches.
* Advanced UI can have saved searches for columns to offer live search - this is expected behavior on other micro blogging systems  (missing features of similar platforms)

Benefits for operators/mods

* Auto moderator bot - we can catch bad actors much sooner or at least alert ourselves to abuse/spam in a programmatic way.
* Moderation discovery - sea-lioning is a huge problem with moderation. Search allows us to discern this much easier 
* Find users asking for help, talking about your instance, talking about your mods/teams (most in good light, but an eye opener as to how ignorant we are unless people intentionally tell you they're talking about you but most users don't know who/how)
* We're no longer blissfully ignorant operating on the assumption that every user is a power user and knows how to do everything - finding people/users who have been stuck, asking for help and yelling into a void.
* community team can really help boost people who are falling in the cracks because they're not power usrs and are trying to operate like every other platform operates with search foundational.

I invest a lot of time, money, and love into making our mastodon instance great. I pay a premium to have fast dedicated servers, fast dedicated internet, fast CDN.  I work hard to evangelize our community, grow our community, and expand the reach of our community while preserving everything that people love about mastodon. I spend money to promote, grow and manicure our community.  Not having search is a problem i could no longer live with.

My users love that mastodon is open source, that it's open protocols, that instances aren't owned by crazy billionaires with egos and if they ever were - users could migrate away because that is built into the platform. 

If i as an instance owner can't compete with the rest of the fediverse to provide the features my users expect I find that problematic. 

I'm *thrilled* that people are passionate about safety, privacy, and community (so am i).  This feature, as designed and implemented without any assurance on the protocol level, is just pulling a curtain over our heads and I'm disappointed we're not honest about this when speaking about SAFETY, PRIVACY and COMMUNITY because all of that must be built on TRUST and ASSURANCE.

**Comment by trwnh** [comment]
no protocol can "assure" anything once the data is visible to someone else. you need shared understanding and trust.

**Comment by supernovae** [comment]
BTW, I LOVE THIS PR.. MY RANT WASN'T POKING AT IT.  We'll be doing this...  i just want to be honest with people where a lot of the fediverse isn't mastodon and not even all mastodon is patched to same level.

**Comment by supernovae** [comment]
> 

as long as people know the behavior only exists on mastodon instances that update to these features. 

It would be great if some of this "ethos" were written down btw. is there a group that tries to get consensus across fediverse? It's the reason i asked about protocol since a lot of RFCs are extremely prescriptive here..

**Comment by supernovae** [comment]
Behavior questions - since a lot of the philosophy is unwritten - what is the expected behavior if not technical expectations for these scenarios:

1) what happens if someone changes this? one day on, one day off... and another day on - is it always per post from this day forward and never going back and changing what prior posts may be?

2) Is the expected behavior that enabling this is only for the future forward?  Is the prior time of fediverse off limits? Or would it mean sidekiq /tootctl could see someone opted in and re-index all their prior posts?  Index rebuilds happen with some frequency due to bugs with hashtags and other quirks - the permissions could/would change based on federated instances doing this at whatever intervals they may have to for whatever reasons and the 8-10% chance messages activities aren't fully received or acted upon means a guaranteed 100% variation between instances (known quirk)

3) BOT (web) indexing is controllable by admins, are we going to make users able to opt in/out of being web indexable? Right now, instance admins can set instance preference for noindex.

image

4) Public posts with tags can be found by tags. What happens if i reply to a public post and I have search allowed, do i get overruled? and would i have to exclude posts with hashtags from full text search to preserve opt-in boundary? replying to a public post with a hashtag already leaks it to hashtag search, wouldn't i leak it to normal search?  Essentially poisoning the well in whatever instance i reply from?

Beyond mastodon

5. How do all the *key and other fediverse tools adhere to this?   could unlisted be gibberish to non mastodon instances?

7. Google searches with "site:somemastodon.instance some keyword" will still return public posts even if users opt out.  Every mastodon instance would have to be noindex by default for nosearch to be a permission boundary by default or we're just saying yeah google sucks, but we don't want instance search too and the friction is a google search everyone can do anyway...


BTW, i see a lot of people using unlisted to get the expected behaviors we're talking about here - not in search, not in hashtags, not indexed by google.  Is there a reason we shouldn't stick to unlisted for these?   1-6 aren't a problem with unlisted and the current PRs for advanced search.

**Comment by supernovae** [comment]
another reason i wonder if something could be done at activitypub level... apparently, wildebeest just has no view model enforcement.

image

**Comment by shleeable** [comment]
As I've spoken about this concept previously. I am very happy to see it... but I'd love to see this concept expanded if suitable.

This is a bit of a brain storm, but I'd love to see people give complete control over their toots.

`toot:indexable` = full text search
`toot:blockquote` = allow people to block the toot being embeded in a quote toot.
`toot:blockreply` = allow people to replying to a toot
`toot:blockboost` = allow people to block boosting a toot
`toot:blockfavorable` = allow people to block liking a toot
`toot:blockreplicate` = allow people to stop media from being mirrored locally (NSFW or sex workers might want to limit files to their local media only)
``

Having a default for full text search in perferences is fine, but I'd also love to see the ability to tweak these on a per-toot basis as well.

**Comment by ClearlyClaire** [comment]
> Is there a reason why we can't just re-use `toot:discoverable` but apply it to statuses instead of just accounts?

To be honest, I kinda forgot it existed. But I think it serves different purposes:
- it controls whether the account is available in the profile directory feature
- it controls whether this account's public posts can appear in trends
- it does **not** control whether this account's profile appears in search (though currently Mastodon only searches using handle and display name, not bio content)

It would seem slightly odd that it would not control search on profiles, but would control search on posts. A tangential question is whether  the ability for a post to appear in trends and the ability for a post to be searchable should be controlled by the same flag.

> If mastodon wants to have a security/permission-based system - **I am 100% behind this** - but it shouldn't assume that the fediverse will respect this unless such a system is part of the protocol and can be assured by the protocol.

No protocol can ever prevent recipients from copying, sharing or indexing anything they receive. This doesn't mean we should ignore the users' consent. Search engines can technically ignore `robots.txt` and `noindex`, yet those mechanisms exist. You can technically make all the e-mails you receive publicly searchable even if the mail content explicitly asks you not to.

> I'm thrilled that people are passionate about safety, privacy, and community (so am i). This feature, as designed and implemented without any assurance on the protocol level, is just pulling a curtain over our heads and I'm disappointed we're not honest about this when speaking about SAFETY, PRIVACY and COMMUNITY because all of that must be built on TRUST and ASSURANCE.

Read my above paragraph. And I don't think stating “This does not technically prevent your posts from being indexed by other tools.” is misleading here.

> another reason i wonder if something could be done at activitypub level... apparently, wildebeest just has no view model enforcement.

Again, wildebeest was the legitimate recipient of the message, and they chose to redistribute a copy of the message without respecting its intended audience. Nothing you can do about that.

> This is a bit of a brain storm, but I'd love to see people give complete control over their every one of their toots. Having a default for full text search in preferences is fine, but I'd also love to see the ability to tweak these on a per-toot basis as well.

This is also considered, but I think this is off-topic for this issue. A lot of those are also something we may be able to do a little more enforcement at the protocol level (of course, bad actors would still be able to ignore these restrictions, but well-behaving third-parties could see that the bad actor is misbehaving and ignore or report their activity).

**Comment by supernovae** [comment]
> > another reason i wonder if something could be done at activitypub level... apparently, wildebeest just has no view model enforcement.
> 
> Again, wildebeest was the legitimate recipient of the message, and they chose to redistribute a copy of the message without respecting its intended audience. Nothing you can do about that.

Yes, so why do we infer otherwise?  Just have to defederate from everything that isn't some future version of mastodon?  Violate the premise of fediverse? Open source? Open Protocols? 

Take the email concept for example:

When I send someone an email, there is no control I can exude once that email is sent as to any expectations. I don't expect it to be public knowledge because its EMAIL (some form of communal trust here tbh) - which to me, is more a DM than a public post if its only sent to one person...  But.. Let's play along - We're saying this is true of fediverse by telling the community there are social construct expectations on behaviors and code that are neither documented nor codified universally true but are true because we say so. So handwavy to me - Infuriatingly handwavy.

As someone who chose Gmail, my emails are searchable and if everyone on gmail is on the CC list because they get the same public blasts (public posts) and they all have searchable emails - why are we saying this behavior is now bad and why would me as an email sender want to dictate what someone can search with? 

Permissions are great. Privacy is great. Controlling your target audience is great.  We have this capability today. Make unlisted a first-rate citizen and call it something better.

**Comment by Wisdom-Chicken** [comment]
Feel like there should be an option for server admins to set the default value of this setting, for new accounts specifically. Default settings are extremely powerful, as the large majority of users never change from the default settings. 

Some instances will want to have a culture of privacy, and only limited search. In which case, having the default value of this setting for new accounts to be off, makes a lot of sense. 

But there are some instances, for example servers that are themed around journalism, where it being indexed for search fits with the culture. In those case, it might make sense for the admin to put the default value (again, new accounts only) of this new setting on. Because we know that so many users never change the default setting, there is a serious risk that a lot of journalists forget to turn this setting on, accidentally opting themselves out of search unintentionally.

Furthermore, this is another small way in which servers can help distinguish themselves by creating unique cultures. Some servers should be privacy focused, with most members excluding from search. But there should also be more spaces on the fediverse that are explicitly pro-search.

Just to be clear, this admin setting should only impact new accounts. Admins being able to toggle this setting for current accounts is seriously uncool.

**Comment by VyrCossont** [comment]
From Discord discussion: if we want full-text account bio indexing to be opted into separately from the current `discoverable` flag, we're going to need another flag like this at the account level for that, possibly with the same name.

**Comment by trwnh** [comment]
> another flag

per discord as well:

> i am highly worried from a spec perspective, i don't think it's a good idea to have multiple vaguely-defined flags with unclear overlap. what if someone says they're `discoverable` but not `indexable`? what if someone says they're `indexable` but not `discoverable`? each new flag added will cause factorial explosion in complexity.
> 
> this is why i would prefer we have a generic definition that doesn't depend on what mastodon will be doing with the flags. make the language clear that the current checkbox will signal that your account is `discoverable` and may or may not be taken as opt-in for general discovery features. and then claire's consent pr [this one] could make it so that (new) posts are `discoverable` as well, since `discoverable` is not limited to actors in its definition. vyr's search pr [#24055 or a future one] would then operate only on posts and accounts marked `discoverable`.
> 
> the contentious part is whether or when to allow search on the natural-language properties of any object (posts and accounts both). i personally think it makes sense to allow it, but i can see arguments to not allow it. i just don't know what would be the best way to signal this, as i'm not really sure what the distinction is -- discovery necessarily requires "indexing" (storing a link or reference to something in a database) because you can't discover something you don't know about. "indexing" itself isn't defined in terms of full-text search, either; the recording in an index is the salient factor. so `indexable` is the wrong way to express this desire to be excluded from full-text search.

re: "opt-in for general discovery features" per https://github.com/mastodon/documentation/pull/1183#discussion_r1130578899

> relatedly, this is why i think `discoverable` should be attached to posts as well: to remove that kind of ambiguity. if we attach `discoverable` at the post level, you no longer need to check the account property. regardless, we might still (may or may not) consider a policy of deferring to the account property if the post doesn't declare whether it is `discoverable`. this basically creates the following states:
>
> - if the post is `discoverable: true`, it SHOULD be shown in discovery features
> - if the post is `discoverable: false`, it MUST NOT be shown in discovery features
> - if the post is `discoverable: null` or the property is missing:
>   - if the account is `discoverable: true`, the post MAY be shown in discovery features
>   - if the account is `discoverable: false`, the post SHOULD NOT be shown in discovery features
>   - if the account is `discoverable: null` or the property is missing, the post MAY be shown in discovery features if some other mechanism establishes consent, but SHOULD NOT be shown in lieu of any other mechanism

**Comment by supernovae** [comment]
I value the extreme care and regard for users and their privacy.  I love where Claire is thinking about this.  I just have different expectations of privacy and want privacy to do more (and provide that safety)

i struggled to convey why I keep asking for real privacy, but here is a simple use case. Me. (if i wanted my mastodon account private like my FB one for "reasons")

When I use facebook, I have my account set to a "private" friend only account - but everything i do is public with my friends (not a per post thingy - followers only if you will).  Google can't see this, no search can because its inside facebook authorization.  This is my "I don't want my place of work stalking me while i share photos of friends and family" approach. I am still extremely social with my trusted social network and it's just hidden from those who i don't want to be bothered with (I think this is the real feature people want)

This is what I'd consider "real privacy" - put it behind authorization and this is what I expect. There is no consent for my friends only posts to be searchable to public fb users or public google.

That isn't me saying trying to add consent functions to a public post is bad. I respect the intent.  But the outcome is not what *I* expect.  If google/bing/ddgo can continue to search my posts and continue to allow my place of work to google me if I'd be upset.   (I can only use this as an example, i don't post family pictures on mastodon so i have a public account - my alt is a private account where I am exclusive and expect exclusive behaviors)

The other boundary is that only mastodon sets this precedence. Other fediverse tools have other default behaviors.

One notion is to try and wield our weight to influence those behaviors on other systems. *I AM ALL FOR THIS* if it was for a valid approach that also solved the public (public being non instance) search.

I see that there is a text field there that tries to describe the intent but if I were a user, I would have no rhyme or reason to understand this or change it and if the default behavior everywhere is no index on public posts for mastodon, then the default behavior will be to use google for discovery.   

Which just seems bad.  As the second I tell people how to find stuff on mastodon on google, then the apparent friction for safety is no longer friction.  I either provide the solution or tell people how to find things... neither really are about safety - but we impose safety on top. (If we reach critical mass at all, i don't think friction of going to google will provide us the safety we say we have by not having search and we're better served by a real authorization mechanism there too)

Putting my "As an instance admin hat" on - I can't read the tea leaves of safety for every type of safety concern there is but what I can do is suggest that people have a "facebook like experience" of followers only and private account where the risk of safety is greatly reduced as matter of fact through authorization and controls.   The notion that people are safe only if their posts can't be found when public posts are extremely leaky suggests that I'm taking extreme risk with peoples posts they don't want me to have, and I don't want it.    (attack vectors)

I want my public users to still be public and I want public post history to be searchable and I want them to show up in public search (google et all).  This is the behavior i expect "in a social network" on public posts.  (my opinion obviously).

WIth a private/followers only circle of friends, i of course expect and should have the privacy and safety we're talking about.

**Comment by supernovae** [comment]
I value the extreme care and regard for users and their privacy.  I love where Claire is thinking about this.  I just have different expectations of privacy and want privacy to do more (and provide that safety)

i struggled to convey why I keep asking for real privacy, but here is a simple use case. Me. (if i wanted my mastodon account private like my FB one for "reasons")

When I use facebook, I have my account set to a "private" friend only account - but everything i do is public with my friends (not a per post thingy - followers only if you will).  Google can't see this, no search can because its inside facebook authorization.  This is my "I don't want my place of work stalking me while i share photos of friends and family" approach. I am still extremely social with my trusted social network and it's just hidden from those who i don't want to be bothered with (I think this is the real feature people want)

This is what I'd consider "real privacy" (declared/limited consent) - put it behind authorization and this is what I expect. There is no consent for my friends only posts to be searchable to public fb users or public google.

That isn't me saying trying to add consent functions to a public post is bad. I respect the intent.  But the outcome is not what *I* expect.  If google/bing/ddgo can continue to search my posts and continue to allow my place of work to google me if I'd be upset.   (I can only use this as an example, i don't post family pictures on mastodon so i have a public account - my alt is a private account where I am exclusive and expect exclusive behaviors)

The other boundary is that only mastodon sets this precedence. Other fediverse tools have other default behaviors.

One notion is to try and wield our weight to influence those behaviors on other systems. *I AM ALL FOR THIS* if it was for a valid approach that also solved the public (public being non instance) search.

I see that there is a text field there that tries to describe the intent but if I were a user, I would have no rhyme or reason to understand this or change it and if the default behavior everywhere is no index on public posts for mastodon, then the default behavior will be to use google for discovery.   

Which just seems bad.  As the second I tell people how to find stuff on mastodon on google, then the apparent friction for safety is no longer friction.  I either provide the solution or tell people how to find things... neither really are about safety - but we impose safety on top. (If we reach critical mass at all, i don't think friction of going to google will provide us the safety we say we have by not having search and we're better served by a real authorization mechanism there too)

Putting my "As an instance admin hat" on - I can't read the tea leaves of safety for every type of safety concern there is but what I can do is suggest that people have a "facebook like experience" of followers only and private account where the risk of safety is greatly reduced as matter of fact through authorization and controls.   The notion that people are safe only if their posts can't be found when public posts are extremely leaky suggests that I'm taking extreme risk with peoples posts they don't want me to have, and I don't want it.  

I want my public users to still be public and I want their history to be searchable and I want them to show up in public search (google et all).  This is the behavior i expect "in a social network".  (my opinion obviously) - just as they want their toots in the limelight themselves.

alas, nothing is perfect..  not even FB controls are perfect - i totally get it.

**Comment by saschanaz** [comment]
Can you provide some tl;dr? 🤯

**Comment by trwnh** [comment]
> This is what I'd consider "real privacy" - put it behind authorization and this is what I expect. There is no consent for my friends only posts to be searchable to public fb users or public google.

"who can see it" and "what they can do with it" are two separate concerns. consider: do you want your friends-only posts to be searchable by your friends? maybe, maybe not. you might signal such a preference completely orthogonally to deciding who can see it. your friends may or may not respect that preference, if they understand it. being able to see something does not grant you consent for anything else. you can still do whatever you want, but you are potentially doing so without consent. 

> the outcome is not what I expect. If google/bing/ddgo can continue to search my posts and continue to allow my place of work to google me if I'd be upset.

that's a separate checkbox. you can add `robots: noindex` to your permalinks' HTML to request that they aren't recorded by google/etc. but that doesn't do anything for the JSON.

> only mastodon sets this precedence. Other fediverse tools have other default behaviors

standards proliferate by having others adopt them. other fediverse tools are free to respect such advisory flags, or they might not. consider how a federated youtube might signal that a video is "unlisted". it should not be shown on profiles, and should not be shown in search, but should be accessible to anyone from the permalink, without authorization. if some other software showed such "unlisted" videos on profiles or in search results, you could say that this isn't preventable. but it is something you can choose to understand and respect.

`toot:discoverable` is what we currently use to indicate that *accounts* should be shown in the profile directory and in trends. we currently also defer to this account-level flag for including an account's *statuses* in the trends/explore tab, but this is somewhat contentious as claire or i might attest, and extending such a deferral to full-text search would be similarly contentious. therefore, it would be a good idea to start attaching this flag to *statuses*, to remove the ambiguity of deferring to the account, especially because the account might be outdated. this is what this PR does (although using `indexable` instead of `discoverable`, whereas i am arguing we re-use the latter instead of defining the former in very broadly similar terms)

**Comment by supernovae** [comment]
> > This is what I'd consider "real privacy" - put it behind authorization and this is what I expect. There is no consent for my friends only posts to be searchable to public fb users or public google.
> 
> "who can see it" and "what they can do with it" are two separate concerns. consider: do you want your friends-only posts to be searchable by your friends? maybe, maybe not. you might signal such a preference completely orthogonally to deciding who can see it. your friends may or may not respect that preference, if they understand it. being able to see something does not grant you consent for anything else. you can still do whatever you want, but you are potentially doing so without consent.

Search isn't separated by concerns; it's just filters on top of a corpus so you could allow search with the privacy filter of only amongst friends if you wanted to but i'm not sure that's in the scope here.  Let's just get search.

As mastodon scales, the notion of "Search" becomes gray.  I may remove redis and write my own front end where the only thing exposed to the internet is lucene indexes and "Search" and all the front end does is query these indexes for timelines/lists/filters/parsers.

I can't agree that the issue of "consent" is an implementationdetail.

My "Scaled mastodon running ES indexers on the edge" would be based on search, but if someone has a private account, they wouldn't be searchable because I'd satisfy the permission boundary. (or allow them to be searchable between friends.. let's cross that bridge when we get there)


> 
> > the outcome is not what I expect. If google/bing/ddgo can continue to search my posts and continue to allow my place of work to google me if I'd be upset.
> 
> that's a separate checkbox. you can add `<meta name="robots" content="noindex"/>` to your permalinks' HTML to request that they aren't recorded by google/etc. but that doesn't do anything for the JSON.

Right, this doesn't solve the problem and creates new ones.  (precedence, federation robustness and who wins the noindex battle on posts)


> 
> > only mastodon sets this precedence. Other fediverse tools have other default behaviors
> 
> standards proliferate by having others adopt them. other fediverse tools are free to respect such advisory flags, or they might not. consider how a federated youtube might signal that a video is "unlisted". it should not be shown on profiles, and should not be shown in search, but should be accessible to anyone from the permalink, without authorization. if some other software showed such "unlisted" videos on profiles or in search results, you could say that this isn't preventable. but it is something you can choose to understand and respect.

I'm holding back so many leaky points that i'm having to pick my battles.   With an unlisted post, it's generally the safest post type - ditto with followers only.  That's our reality even though imperfect.

I wish the protocol was better here

> 
> `discoverable` is what we currently use to indicate that _accounts_ should be shown in the profile directory and in trends. we currently also defer to this account-level flag for including an account's _statuses_ in the trends/explore tab, but this is somewhat contentious as claire or i might attest, and extending such a deferral to full-text search would be similarly contentious. therefore, it would be a good idea to start attaching this flag to _statuses_, to remove the ambiguity of deferring to the account, especially because the account might be outdated. this is what this PR does (although using `indexable` instead of `discoverable`, whereas i am arguing we re-use the latter instead of defining the former in very broadly similar terms)

Splitting hairs. Indexable is implementation detail. One can offer advanced search using postgres stemming and it would be a sql query.

In my brain, search is an API

We use the API to enhance discoverability

People don't want to be discovered, let them not be discovered.

But defining implementation details around public posts under the premise of safety? nah.

Perhaps i'm not being clear enough. If people post things that they feel can make them unsafe if people see it, I don't want those posts on my public system because I can't do anything to assure their safety no matter *what* we choose to do here.

The *only* way for their safety to be true is if their posts are behind authorization. Period.

Consent is permissions. We can't control the permissions of public posts no matter how hard we try.

**Comment by supernovae** [comment]
> no protocol can "assure" anything once the data is visible to someone else. you need shared understanding and trust.

We can declare boundaries behind authorization and enforce what is or isn't public where consent is by explicit permission.

It's one thing to be bad actor violating permissions even if explicit.  Bad humans are bad.

**Comment by SkyMTF** [comment]
I have read this pull request but I fail to recognize if it is being pushed or not?

**Comment by noellabo** [comment]
Fedibird (my fork) is doing something similar.
It has already been implemented and has been in operation since August 2022.

- The ability to specify the searchability you want to allow for your account and posts is granted.
- Make representations in ActivityPub and federate with other servers/implementations.
- It is reflected in the full-text search, and it is possible to search according to this specification.
- The searcher can specify the target searchability.
- We have an endpoint for external search engines using searchability

I started small with my implementation, but over time I've found it to work well and wanted to spread it around.

Is there anything I can do?
I'll go into a little more detail if needed.

I'll try to make it compatible with this pull request in the end anyway.

**Comment by ClearlyClaire** [comment]
> - The ability to specify the searchability you want to allow for your account and posts is granted.
> - Make representations in ActivityPub and federate with other servers/implementations.

Can you elaborate on how this works in your implementation? How is it represented over ActivityPub? Do you have anything to ensure that when the user changes their mind, the searchability of their posts is accordingly updated on remote servers?

**Comment by noellabo** [comment]
ActivityPub looks like this
```
{
  @context: [
    {
      fedibird: "http://fedibird.com/ns#",
      searchableBy: {
        @id: "fedibird:searchableBy",
        @type: "@id"
      }
    }
  ],
```

```
searchableBy: [
  "https://www.w3.org/ns/activitystreams#Public"
],
```
Same as to and cc.
Included in Actor and Note.

Account searchability represents the default if post searchability does not exist. Past posts before searchability was introduced apply this default.

Interpreted internally as public, private, direct. unlisted doesn't seem to make sense. Mastodon defaults to direct. Private posts are visible only to followers' search results. Public posts will appear in search results for everyone.

In either case, people who reacted to your post in any way act to include it in search results.

Fedibird doesn't yet support editing posts, so if you change your mind later, you won't be able to change it, but it would be nice to be able to do it in the Update Activity for Actors and Notes.

image
for Post

image
for Account

There is a feature to filter by searchability on purpose when a user searches.

Searching for public may be noisy. If you only target the followees, the noise will be much less. If you use it only for yourself, the conventional results are better.

image

Encourage agreements not to use local or federated timelines for search services outside of ActivityPub to crawl, instead providing explicit indexing endpoints.

Only those with searchability public can be indexed here, as follow relationships are never taken into account.

Although there are challenges such as tracking deletions, it will be a rule to prevent the search service from being subjected to unnecessary criticism. (A number of search services have been shut down after being accused of being bad.)

In Elasticsearch we are adding a searchability field.

**Comment by ClearlyClaire** [comment]
I like this! Although similar to my own proposal, I'm worried about updates to the actor's default search policy not reaching widely enough.

**Comment by noellabo** [comment]
The per-post search policy is more important. The default search policy for actors should be ignored if it is difficult to implement outside of Mastodon. An optional fallback for cases where the post does not explicitly state a search policy. If you can't find a search policy, promise not to search it.

Distribute an Update - Actor Activity immediately after changing the actor search policy. A somewhat verbose approach is to resend a day later to ensure delivery.

**Comment by ThisIsMissEm** [comment]
I'd be inclined to suggest that we shouldn't invent our own vocabulary for data access and privacy, and instead reuse existing vocabularies such as ODRL and DPV, which have had a lot of research go into their development.

**Comment by renchap** [comment]
This has been implemented, closing

**Pull request closed without merging**
