### PR TITLE
Add search options to search popout in web UI

### PR DESCRIPTION
**Pull request by Gargron**
https://github.com/mastodon/mastodon/assets/184731/df5e4957-9123-4898-b721-c83c74cfae2f

### CODE REVIEW

**Comment by renchap** [comment]
Looks good, but I would prefer the items where a user-entered value are needed to display an example of such a value, so the expected format can be more easily understood

**Comment by renchap** [comment]
Also it would be good to indicate that `-` is the negation operator (and maybe that results must match all terms = uses `AND`?)

**Comment by Gargron** [comment]
I believe this can be expanded upon in future patches.

**Review by ClearlyClaire — APPROVED** [review]
Looks ok to me, although it's both a little busy and a little light on details. We may want to move to a specific advanced search view in the future.

**Pull request merged**
