### PR TITLE
changed defaults

### PR DESCRIPTION
**Pull request by LottieVixen**
These changes are to reflect the documentation in production-guide.md

reason? I believe setting up a default instance should be possible with minimal changes to config files.

### CODE REVIEW

**Review by KellerFuchs — APPROVED** [review]
Yay!
Thanks for trying to make running instances easier.

**Review by akihikodaki — APPROVED** [review]

**Comment by Gargron** [comment]
Okay, hold up. The previous defaults aren't random either. They facilitate the docker-compose deployment method. Should we really change it around? Documentation would need to be updated too. The way I see it, if Docker is the "easier" way of deploying, we're making it easier with fitting default configuration. When someone wants to deploy standalone, they have the technical prowess to know to adjust these values in the config.

**Comment by beatrix-bitrot** [comment]
@Gargron since the docker one is more automated can it have its own .env file?

**Comment by akihikodaki** [comment]
So we could have `.env.production.docker.sample` and `.env.production.standalone.sample`, or something sort of?

**Comment by nightpool** [comment]
yeah i'm gonna throw my opinion behind gargron here. the "default" way to deploy mastodon should be using docker.

**Comment by beatrix-bitrot** [comment]
in that case the docker stuff could stay in the file as is and like @akihikodaki said we could add a new file that matches what's in the documentation perhaps?

**Review by nightpool — CHANGES_REQUESTED** [review]
see consensus above

**Pull request closed without merging**
