### PR TITLE
add Vagrant short guide to readme

### PR DESCRIPTION
**Pull request by Grawl**
#10283

### CODE REVIEW

**Comment by Grawl** [comment]
maybe we should run `foreman` on `vagrant up`?

**Review by ykzts — APPROVED** [review]

**Comment by umonaca** [comment]
Please do not close this.

**Comment by SuperSandro2000** [comment]
Bump

**Review by ClearlyClaire — APPROVED** [review]

**Review by weex — APPROVED** [review]
vagrant worked for me recently and this seems a simple update

**Pull request merged**
