### PR TITLE
Add `tootctl feeds vacuum`

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Background: we have been investigating high Redis memory usage on mastodon.social, and most of it is due to feeds storage.

One thing we have noticed is that some feeds that should have been removed hadn't been. One reason for this has been fixed in #33018, but this does not retroactively clean up feeds from deleted accounts, hence this task.

### CODE REVIEW

**Review by oneiros — DISMISSED** [review]

**Comment by oneiros** [comment]
I think the code is fine, but not having followed _all_ the redis memory usage related findings of the last days, I wonder if this is still sufficient or if it should be expanded to other cases you identified in the meantime.

**Comment by vmstan** [comment]
Tested on vmst.io, runs without error. Not a lot of feedback when it runs on what was cleaned up and memory impact for me was minuscule but I'm likely just not as impacted by this issue.

**Comment by renchap** [comment]
FYI so this is noted somewhere, on mastodon.social we went from 21 GB to 14.5 GB of used memory for the app Redis process after those clean ups (and fixing the sources in the other related commits)

**Comment by vmstan** [comment]
Mine went from 38.9% utilization to 38.3% 😄

**Review by oneiros — APPROVED** [review]

**Comment by renchap** [comment]
We need a documentation update for this

**Pull request merged**
