### PR TITLE
Regenerate lint todos

### PR DESCRIPTION
**Pull request by mjankowski**
For haml-lint:

- As discussed in side conversation here - https://github.com/mastodon/mastodon/pull/26042 - we had contemplated regenerating this with higher issues limit (I used 50 here) and then working through some of the larger groups. I plan on tackling the UnnecessaryStringOutput and Rubocop violations next.
- With the merging of https://github.com/mastodon/mastodon/pull/26042 and https://github.com/mastodon/mastodon/pull/27428 and https://github.com/mastodon/mastodon/pull/27427 I did not included the removal of the fixed issue in the PR, this adds that as well.

For rubocop, this captures some changes from a version bump, and some things fixed as side effects of other unrelated changes.

### CODE REVIEW

**Comment by renchap** [comment]
Do we really want to enable `ViewLength`?

**Comment by mjankowski** [comment]
> Do we really want to enable `ViewLength`?

It's already enabled, but has zero violations. You may be misreading the diff (?) which is mostly adding Rubocop violations in that area...?

**Review by nschonni — APPROVED** [review]

**Review by renchap — APPROVED** [review]

**Comment by renchap** [comment]
I am not sure why, but this broke HAML linting after being merged: https://github.com/mastodon/mastodon/actions/runs/6624075506/job/17992328566

**Comment by mjankowski** [comment]
Looks like a view that changed in another commit after I ran the regeneration. Will open something else to either ignore it, or fix that specific issue.

**Pull request merged**
