### PR TITLE
Fix installed PWA logo

### PR DESCRIPTION
**Pull request by atjn**
Hello and thanks for making this awesome project!

The current Mastodon PWA provides a single icon in its web app manifest, which does not follow the standard for web app icons. Therefore, when I install the PWA on my phone, it forces my browser to guess how it should display the icon, and it comes up with this mess:
image

This PR adds a maskable icon to the manifest, which allows the browser to render the icon properly:
image

The new web app manifest is still not 100% valid. It should ideally also provide 512x512 PNGs along with SVG versions of the logo, but I couldn't find a high definition source to produce those icons from, so this change was the best I could do :)

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by atjn** [comment]
You have let this PR hang for long enough that it is now incompatible with newer changes in #18592

The changes in #18592 seem to be a big improvement to the general quality of the app's icons, and I will happily adapt my PR to work with this new system, but I am not interested in doing a lot of work again, only to have it be ignored again.

Can I have some sort of feedback either from @ykzts or @Gargron to confirm/deny that you will merge my PR if I spend the time adapting it to the new system?

**Comment by Gargron** [comment]
You did not consult anyone about branding changes. As far as I am aware, current icons do follow the standard for web app icons.

**Comment by atjn** [comment]
@Gargron Current icons do not follow the standard for web app icons. You need `maskable` icons, like the one this PR adds. Your new icons look like this when installed:

Firefox on Android:
image

Chrome on Android:
image

(I don't have an iPhone handy to test on, but assume similar issues)

In the original message, I mention that it is not possible to be 100% compliant given missing image sizes, but with the new build system, it is possible to make the `maskable` icons completely compliant.

> You did not consult anyone about branding changes.

I was not aware that I was making branding changes. From my point of view, I was simply fixing a bug, and I thought you guys agreed, given that my PR was approved with no further comments.

**Comment by atjn** [comment]
I will create an issue for it instead, and let you fix it in a way that works for you.

**Pull request closed without merging**
