### PR TITLE
Minor fix regarding domain blocks

### PR DESCRIPTION
**Pull request by ClearlyClaire**
~~~Minor refactoring of the backend for consistency, and a~~~ small fix avoiding a spurious error in the front-end.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by ThibG** [comment]
Uh, I thought the backend change was sound, but apparently it doesn't work? I don't understand why, though.

**Comment by Gargron** [comment]
The destroy route generated for "resources" is based on ID. That's why I used "resource" instead.

**Comment by ThibG** [comment]
Ok, I think I got it now!

**Comment by Gargron** [comment]
The URL *is* different and therefore this is a breaking API change FYI.

Instead of `DELETE /api/v1/domain_blocks` it's now `DELETE /api/v1/domain_blocks/:domain`

**Comment by ThibG** [comment]
And the tests don't catch that?
Anyway, nevermind, I'll just drop the server-side changes

Le 14 juillet 2018 23:15:34 GMT+02:00, Eugen Rochko <notifications@github.com> a écrit :
>The URL *is* different and therefore this is a breaking API change FYI.
>
>Instead of `DELETE /api/v1/domain_blocks` it's now `DELETE
>/api/v1/domain_blocks/:domain`
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tootsuite/mastodon/pull/8021#issuecomment-405050350

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Gargron** [comment]
The tests don't test the URL string, they test the controller method invocation. In-path params and query string / form / body params are all inside the same variable in there.

**Pull request merged**
