### PR TITLE
don't display any descendants of .invisible

### PR DESCRIPTION
**Pull request by hcmiya**
This is an alternative to #5558 for resolving #5553, #5554.
#5558 will break when `span` is nested. Also, if images is inserted into the `.invisible` by another bug, It will be displayed.
Using `!important` rule is generally considered a bad practice. However, it's rare to apply other styles to hidden elements, so this is OK, probably...

### CODE REVIEW

**Comment by nightpool** [comment]
* selector is really bad for performance. Can we use a more specific selector instead?

**Comment by hcmiya** [comment]
Like img or svg?

**Comment by kyrias** [comment]
While it's not optimal when there are more specific options, the fear of `*` is mostly a leftover from the IE6 era, and it's been shown to be pretty insignificant performance-wise for browsers newer than that,[¹](http://www.stevesouders.com/blog/2009/03/10/performance-impact-of-css-selectors/)[²](https://www.telerik.com/blogs/css-tip-star-selector-not-that-bad), and it's not really "really bad for performance" anymore.

**Comment by nightpool** [comment]
@kyrias I'm more concerned about unwanted side-effects rather then performance.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
