### PR TITLE
Rename media to avoid exposing filename (fixes #207)

### LINKED ISSUE #207: Image filename is remembered
Probably minor: Mastodon remembers, and makes public the filename of avatars and banners uploaded. This might be sensitive in some cases.

### PR DESCRIPTION
**Pull request by hikari-no-yume**

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Since I am unfamiliar with Ruby and Rails, my friend @alyssais refactored my code to be a bit neater, so thanks to her for that. :)

**Comment by Gargron** [comment]
This doesn't break backwards compatibility, does it?

**Comment by TazeTSchnitzel** [comment]
Nope, no BC break, thus the workaround. Paperclip continues to serve old media without trouble.

**Comment by TazeTSchnitzel** [comment]
So far as Paperclip cares, all that's changed is that every new upload is apparently of a file called `media.png`/`.jpg`/etc on the user's local machine. This is of course not true, but it doesn't need to know that.

**Comment by TazeTSchnitzel** [comment]
More specifically: Paperclip doesn't store the generated URIs of media in the database, for some reason. Instead it stores the data it needs to generate a URI. One of these items is the original filename of the attachment, as reported by the browser.

What this patch does is replace that filename with `media` before Paperclip gets it. Paperclip then generates a URI from that and stores the data (including our bogus filename) in the database as usual, and everything works fine.

**Comment by TazeTSchnitzel** [comment]
Not only does it not break BC (existing media works fine), but you can revert this change later and media uploaded while it was there still works. I was able to switch back to the master branch locally and have media with obfuscated filenames still work.

**Pull request merged**
