### PR TITLE
Misc gem bumps

### PR DESCRIPTION
**Pull request by mjankowski**
Update to [Haml 5](https://github.com/haml/haml/blob/master/CHANGELOG.md#500) in prep for Rails 5.1 (includes perf improvements), and bring some other things along as well.

### CODE REVIEW

**Comment by Gargron** [comment]
Wait, but we were using hamlit. I'm pretty sure

**Comment by mjankowski** [comment]
Oh ... I totally misunderstood what that was doing.  Let me review...

**Comment by mjankowski** [comment]
Here's a summary...

- We are in fact using `hamlit` (via `hamlit-rails`) ... I didn't know that prior to you saying as much
- The reason I had bumped `haml` version here is I noticed it was out of date, and it didn't occur to me that we were not rendering haml with the `haml` gem
- The reason `haml` gem was in the repo at all is that `haml_lint` was added here https://github.com/tootsuite/mastodon/commit/48594b18e6285d87ee2f58daa08d356b571c8aa6 - and it pulls in `haml` as a dependency

We probably don't want both `hamlit` AND `haml` gems pulled in...

I've updated this PR to remove both the explicit `haml` gem line that I had just added, and to also remove the `haml_lint` gem (not totally related ... but I'm generally skeptical of keeping tons of linting stuff in the repo itself ... we can rely on local installs for people who care, and CI or external service like codeclimate/hound/etc if we want to catch during PR process...)

**Review by Gargron — APPROVED** [review]

**Comment by yhirano55** [comment]
Oh...different versions between local and external services (CodeClimate) will occur each different violations. This PR includes risk that many developers may confuse, and may reduce their productivity...😢 

Certainly, it is not good to increase unnecessary dependencies. But `haml-lint` was `require: false` and be grouped on `development` on Gemfile. I think the possibility of causing problems is low (At least, after dealing with problems actually, I thought that deleting was not late).

If many developers seem confused like I said, please consider reverting.

**Pull request merged**
