### PR TITLE
Revert "Rails 7 update"

### PR DESCRIPTION
**Pull request by Gargron**
Reverts mastodon/mastodon#24241

Sorry @mjankowski, merged it too quick.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by mjankowski** [comment]
No problem. Issues/regressions? Or just not ready yet?

**Comment by Gargron** [comment]
There's going to be a release really soon so we probably shouldn't risk it at this stage without more time to give it a smoke test. Other than that it's fine, I was too hasty to merge it because I was looking forward to it. Can you please re-create the PR? Or I can revert the revert later.

**Comment by mjankowski** [comment]
> There's going to be a release really soon so we probably shouldn't risk it at this stage without more time to give it a smoke test.

Agreed, makes sense.

> Can you please re-create the PR? Or I can revert the revert later.

Yup, I'll rebase past the merge+revert and open another one.

**Comment by evelynmarie** [comment]
I 100% disagree with this revert - this PR has been in the works since March. There doesn't seem to be that many changes in that PR to begin with to warrant reverting due to some release coming out soon. - Yeah Rails 7 is a major release, but a Rails 7 upgrade would be a nice surprise in the aforementioned release.

So, I disagree with the reasoning behind reverting this.

**Pull request merged**
