### PR TITLE
Replace from scss-lint to sass-lint

### PR DESCRIPTION
**Pull request by ykzts**
Stop using scss-lint written in Ruby and replace it with sass-lint executed on Node.

> ### NOTICE: Consider other tools before adopting SCSS-Lint
> 
> The Sass core team is now building Sass in [Dart instead of Ruby](http://sass.logdown.com/posts/1022316-announcing-dart-sass), and will no longer be maintaining the Ruby implementation unless a maintainer steps up to help. Since the SCSS-Lint project relies on the Ruby Sass implementation, this means it will eventually not support the latest Sass features and bug fixes.

https://github.com/sds/scss-lint

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
> codeclimate — 5050 issues to fix 

:cold_sweat:

**Comment by ykzts** [comment]
awesome 😵

**Comment by Shleeble** [comment]
"codeclimate has no chill"

**Comment by Gargron** [comment]
Could you manually run the lint to find out what those 5050 issues could be? It is likely to be a misconfiguration of code style.

**Comment by ykzts** [comment]
image

uh...

**Comment by Gargron** [comment]
Okay, then it's CodeClimate's problem.

**Pull request merged**
