### PR TITLE
Support GNU Social share URLs

### LINKED ISSUE #4940: Support GNU Social share URLs
GNU Social supports a less automated share functionality than Mastodon (see #4511). One needs to enter an URL of an instance to be redirected to a post composing form (you can see how it works at https://publiccode.eu/), Although the URL is different than in Mastodon: `/notice/new?status_textarea=Lorem+ipsum`, it is trivial to redirect such queries.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by ilpianista**
Closes #4940

### CODE REVIEW

**Review by akihikodaki — CHANGES_REQUESTED** [review]
Please add a comment to indicate the intent type is used by GNU Social.

**Comment by ilpianista** [comment]
@akihikodaki isn't a `git blame` enough?

**Comment by akihikodaki** [comment]
@ilpianista No. `git blame` is for reviewing history; it will be harder to figure out the intention of the code when they are rewritten, renamed, or splitted into multiple files. That is because `git blame` is not a tool for such a use.
Old good comments are no longer used to record revision history, but they are still alive to clarify the intention of the code.

**Review by nightpool — COMMENTED** [review]
This was not included originally—in the absence of spec in this area we opted not to include the existing verbiage and I'd like to understand why before going back on that decision

**Comment by Gargron** [comment]
I don't think there's any precedent in our code for supporting gnu social-specific features. If there was a high demand for this I would understand, but I have never ever seen a "share to gnu social" link in the wild where you could input a Mastodon server, so I don't think this change is justified.

**Comment by ilpianista** [comment]
Please close #4940 as well.

**Comment by steelman** [comment]
@Gargron 
I've mentioned one public [site](http://publiccode.eu) in my report which enables sharing via GS link, so you can go and see it for yourself. Searching the web for "Share on GNU Social" returns some more [hits](https://duckduckgo.com/?q=%22Share+on+GNU+Social%22). Not many, I admit. In my humble opinion, however, such tiny details, which make software operate a little better in the existing environment, are important. They are for me.

Thank you for Mastodon anyway.

**Pull request closed without merging**
