### PR TITLE
Add follow unfollow contextmenu

### PR DESCRIPTION
**Pull request by Zmote**
Basic implementation for #20512, provides follow/unfollow in timeline via context menu. This is my first PR, please inform me about the things  I might have done wrong or have overseen. Still getting to know the project.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Hi! There appear to be two changes in this PR: adding the menu item itself, and making it so that both follower counts get updated correctly. While both of those changes are possibly desirable, it would probably be better if they were split into two PRs! Thanks!

**Comment by Zmote** [comment]
> 

Hi, yeah I'll make two PR's then.

**Comment by Zmote** [comment]
Added separate PR for accounts_counters #20941

**Comment by ClearlyClaire** [comment]
The PR looks sound, however, as someone who gets a *lot* of follow requests even though my profile tells people not to send one unless we have already interacted, I'd prefer if we didn't encourage people to follow someone without first checking their profile.

**Comment by mjankowski** [comment]
Closing due to merge conflicts and lack of consensus on initial feature idea -- if you feel strongly this should be considered again, can you rebase the branch and reopen the PR?

**Pull request closed without merging**
