### PR TITLE
Update robots.txt to exclude new AI data scraper crawlers/spiders bots.

### PR DESCRIPTION
**Pull request by UmbreonShapeshifter**
Following the recent surge in data scraping spider/crawler bots, I believe robots.txt had become quite outdated. While this definitely doesn't prevent the bots from accessing an instance's data (unfortunately).

It does explicitly deny them legal permission to continue grabbing people's data who might not be aware or desire that it's happening to them in the first place, and could also possibly reduce the load these scrapers might create assuming they do actually obey robots.txt as an extra bonus.

If there's any scrapers that I had forgotten or are created later, let me know. These companies have started merging much of their AI scrapers with their search engine bots (Like Googlebot), making it quite hard to keep instances searchable but also deny all scraping.

Also removing advertising company bots might be a worthwhile addition.

### CODE REVIEW

**Comment by nschonni** [comment]
Seems to have more than https://github.com/mastodon/mastodon/pull/31236

**Comment by shleeable** [comment]
Hell yeah brother.

**Comment by aaaaalbert** [comment]
FYI: this PR would also cover @lazaruscorporation's suggested AI scraper list in #28383, with small differences:

* `omgili` here is `OmgiliBot` there, and
* they have one `The Knowledge AI` in the list.
 
(I don't know whose is the more correct version).

**Comment by UmbreonShapeshifter** [comment]
> FYI: this PR would also cover @lazaruscorporation's suggested AI scraper list in #28383, with small differences:
> 
> * `omgili` here is `OmgiliBot` there, and
> * they have one `The Knowledge AI` in the list.
> 
> (I don't know whose is the more correct version).

So far I haven’t found any record of “The Knowledge AI”, beyond just a forum post that people are saying is tied to Google, however to be sure we can remove it.

**Comment by mjankowski** [comment]
Same opinion here as on similar one - https://github.com/mastodon/mastodon/pull/31236#issuecomment-2489324085

> I think I'm thumbs down on this ... feels like an eminently reasonable thing to do per-server if desired, but I'm not sure being a core project default makes sense:
> 
>  - Some servers may not want these rules
> - We'll be playing whack-a-mole with the list
>
> How about a documentation PR that makes it clear how you might go about customizing this setting, along with links to one/some of the various "here's a database of AI crawlers" projects?

**Comment by shleeable** [comment]
I've closed my PR.

**Comment by mjankowski** [comment]
> I've closed my PR.

Cool - going to close this one too.

@UmbreonShapeshifter - feel free to reopen if you feel strongly this should be a core project default ... otherwise, this seems like an utterly reasonable documentation PR to do re: how you'd add this and where you can find DBs of these values, etc.

**Pull request closed without merging**
