### PR TITLE
Update project to use Node.js v18.x

### PR DESCRIPTION
**Pull request by olof-nord**
Node.js v18 is the new LTS version [1]

This PR upgrades the project to the latest 18.x version as to ensure we stay up to date.

Digging into the CircleCI configuration, because `lts` is used by default (and specified in the config), this is the version used already.

```shell
$ docker run -it --rm cimg/node:lts node --version
v18.12.1
```

[1] https://nodejs.org/en/blog/announcements/v18-release-announce/

### CODE REVIEW

**Comment by ineffyble** [comment]
Looks like we're getting a container build fail. I found this which suggests there might be a Node dependency we need to upgrade:

> If you hit an ERR_OSSL_EVP_UNSUPPORTED error in your application with Node.js 17, it’s likely that your application or a module you’re using is attempting to use an algorithm or key size which is no longer allowed by default with OpenSSL 3.0.

**Comment by olof-nord** [comment]
Digging deeper, the required Webpack configuration was already adopted, but seemingly something is still missing:

https://github.com/mastodon/mastodon/pull/17930

**Comment by ineffyble** [comment]
Version of OpenSSL inside the container maybe?

**Comment by olof-nord** [comment]
I thought so too first, but seems ok:

```shell
$ docker run -it --rm cimg/node:lts openssl list -digest-algorithms | grep -i sha256
  RSA-SHA256 => SHA256
  SHA256
  sha256WithRSAEncryption => SHA256
  { 2.16.840.1.101.3.4.2.1, SHA-256, SHA2-256, SHA256 } @ default
$ docker run -it --rm cimg/ruby:3.0-node openssl list -digest-algorithms | grep -i sha256
RSA-SHA256 => SHA256
SHA256
sha256WithRSAEncryption => SHA256
$ docker run -it --rm ubuntu:20.04 bash -c "apt update -y && apt install -y openssl && openssl list -digest-algorithms | grep -i sha256"
[...]
RSA-SHA256 => SHA256
SHA256
sha256WithRSAEncryption => SHA256
```

My working hypothesis is that the webpack plugins and extra libraries somehow have hardcoded configurations: will push a webpack v5 upgrade soon

**Comment by olof-nord** [comment]
Reading the comment here explains why the project is not using webpack 5, and also rules out a simple way of upgrading it.

> EDIT: well, the blocker for a more recent version of webpack is webpacker, which only supports webpack 4.x.x and will not be updated to newer versions, we would need to investigate something like https://github.com/rails/jsbundling-rails/

https://github.com/mastodon/mastodon/issues/17924#issuecomment-1085552338

**Comment by ineffyble** [comment]
We've just changed the way Node.js is installed on the Docker image, sorry about that!

**Comment by olof-nord** [comment]
No problems! Ill update my fork.

Where I am at the moment is to look through all the webpack plugins and try to find out which ones are using 'md4' by default: possibly we could upgrade just the plugins and/or configure them to use a more modern hashing algorithm.

**Comment by olof-nord** [comment]
With this branch basically out of date and with two possible ways to progress on this, I will close this PR in favour of this issue:
https://github.com/mastodon/mastodon/issues/20968

**Pull request closed without merging**
