### PR TITLE
Local development setup using Docker and Makefile

### PR DESCRIPTION
**Pull request by exstral**
This adds a Docker setup to work locally for development. It now requires Docker version 18.09 or later that supports BuildKit and you also need the "make" tool for using the Makefile commands.

Changes summary:
- Adds stages to the Dockerfile for the development build while still keeping production the default
- Adds fancy Docker Buildkit cache mounts to the Dockerfile for speeding up apt installs
- Adds a docker-compose.local.yml file used for local dev environment
- Adds a Makefile for short and easy commands that initialize the database and start the local environment
- It should not interfere with the current docker-compose.yml used for production
- It should not interfere with the current vagrant setup used for local development

We are using this setup to work on Mastodon/Hometown in our small collective and see the following benefits:
- On Linux and Windows WSL hosts this is much much faster than the Vagrant VM based approach
- We are now using (almost) the same Docker image in both local, staging and production environments
- It is really fast to start and stop while checking out different commits to test and init a clean database when needed
- If this works well for everyone, then there is no need to maintain the separate Vagrant setup anymore

Any thoughts or feedback appreciated :relaxed: 

### Installation
1. Install make
  Mac: `brew install make`
  Ubuntu: `sudo apt install make`
  Windows: https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows
2. Install Docker
  Ubuntu: https://docs.docker.com/engine/install/ubuntu/
  Mac/Windows: https://www.docker.com/products/docker-desktop
3. Make sure that docker is correctly set up in your environment. This command should print an empty list of containers that are running:
  `$ docker ps`
  If that command gives you an error, resolve that using standard Docker guides _before continuing_. The command should not require sudo, if it does, your setup is not working correctly.

### Usage
1. Initialize the project and start the containers
  `$ make up`
   The first time this build can take up to 30 minutes depending on your machine.
   Wait until all services has started and webpack says it has compiled all resources.
2. Then you can access Hometown on http://localhost:3000
3. Press CTRL-C to stop the services.
4. To start it again next time, run the same command. 
   Dependencies are updated and containers rebuilt as needed.
   `$ make up`
5. Want to start over with a clean dev environment? 
   Run 'clean' to stop everything and delete all databases.
   `$ make clean`

## TODO
Currently these changes will likely break webpack in the Vagrant setup cause I had to change the host in `config/webpacker.yml`. That should be possible to solve with a dynamic variable by someone more experienced with Ruby than me :)

- [ ] Make webpacker dev server work with both vagrant host and docker host https://github.com/tootsuite/mastodon/pull/16211/files#diff-46b7721b943217c3670f6818a10c2661ec1f9f72dfea66469fd9f026dc74c36a
- [ ] Load webpacker public URL dynamically https://github.com/tootsuite/mastodon/pull/16211/files#diff-c1c619ffb7b249550067cb696b8e7d6c29d1efe2ed4cf5b7a8bb6bed47b409d1

### CODE REVIEW

**Comment by shleeable** [comment]
My environment is docker in prod. Does this require any change from my side?
right now upgrading is
```
# git checkout v3.4.0
# docker-compose pull
# docker-compose build
# docker-compose up -d
```

and I'm done.... what's changes?

**Review by decentral1se — COMMENTED** [review]
Fantastic stuff :) Much needed having something easy to work with locally. I noticed that these changes conflict with https://github.com/tootsuite/mastodon/pull/16244 so some coordination is required. Hoping this will be merged :rocket:

**Comment by exstral** [comment]
Hi @decentral1se and thanks for having a look at this pull request! :)

And thanks for pointing me to that other pull request. It made me realize the images built here actually got even bigger. After many hours of test-builds I have now put back the `build-dep` stage that I removed. This leads to a more complex multi-stage Dockerfile, but the resulting image is the same "small" size as the other pull request at 1.26 GB.

The apt installs on the other hand are more efficient here in my opinion. By using the new Docker BuildKit feature `--mount=type=cache` there is no need to consolidate the apt installs into one. This cache mount stores the apt cache between installs, so it is fast, and the cache is not included in the final image, so it is also small. In my opinion this is better because you can keep the organization of the dockerfile into different software groups while still having a speed and size benefit.

Here are some image size results:
1.65 GB - current main branch mastodon production image
1.26 GB - pull request #16244 production image
1.26 GB - this pull request production image, now after latest commit
(970 MB - this pull request development image used for local environment)

**Comment by exstral** [comment]
Rebased on latest mastodon main branch and squashed commits together more clearly

**Pull request closed without merging**
