### PR TITLE
improve status title

### PR DESCRIPTION
**Pull request by devkral**
The current generated status title is very uninformative and not helpful if used with atom/rss.
I redesigned it to contain the first 10 chars/first line depending what is shorter.
Sensitive Messages are excluded for not disclosing content.
What is your opinion?
What can I improve?

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by sternenseemann** [comment]
Any news on this?

**Comment by sternenseemann** [comment]
I believe this can be closed @ykzts?

**Comment by sternenseemann** [comment]
Okay, the commits got pushed into mastodon, but the changes somehow reverted again? I am confused.

**Comment by gytisrepecka** [comment]
Thanks, very useful 👍

**Pull request merged**
