### PR TITLE
Change bio limit from 160 to 500

### LINKED ISSUE #10628: Bio limits too restrictive
### Rationale
100-ish characters is a bit too low for conveying more than a short sentence or two. One can use profile fields to fit more information, but only for non-essential supplementary things, because profile fields aren't as widely supported in alternative implementations.

### Pitch
Slightly increase the default character limit on bios. Maybe make it the same as statuses (500?) But IMO at least 420.

### PR DESCRIPTION
**Pull request by trwnh**
Fix #10628 

Just following https://github.com/tootsuite/mastodon/issues/10628#issuecomment-493780569

### CODE REVIEW

**Comment by trwnh** [comment]
Looks like CI is failing because some of the tests expect longer than 160 to fail, but now they succeed -- not entirely sure how to fix that in CI.

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
You need to adjust tests in:

- `spec/controllers/api/v1/accounts/credentials_controller_spec.rb:68`
- `spec/models/account_spec.rb:607`

**Comment by trwnh** [comment]
looks like just the account_spec needed to be updated from 161 to 501. the api one just asserts that an unprocessable status returns an error instead of 200 ok. i'll wait for ci to recheck but hopefully that should do it

**Comment by Gargron** [comment]
No, sorry, it still needs an adjustment in the other file.

**Comment by trwnh** [comment]
I'm not sure how to fix the other file. Maybe it's a RUby syntax thing I'm not understanding, but it looks logically correct to me.

CI gives this:
```
1) Api::V1::Accounts::CredentialsController with an oauth token PATCH #update with invalid data returns http unprocessable entity
     Failure/Error: expect(response).to have_http_status(:unprocessable_entity)
       expected the response to have status code :unprocessable_entity (422) but it was :ok (200)
     # ./spec/controllers/api/v1/accounts/credentials_controller_spec.rb:68:in `block (5 levels) in <top (required)>'
```

Context around `./spec/controllers/api/v1/accounts/credentials_controller_spec.rb:68`:
```
      describe 'with invalid data' do
        before do
          patch :update, params: { note: 'This is too long. ' * 10 }
        end

        it 'returns http unprocessable entity' do
          expect(response).to have_http_status(:unprocessable_entity)
        end
      end
```

What should it be changed to? It seems to me like it's describing a test case that returns "unprocessable" and expecting it to have the "unprocessable" status code.

**Comment by Gargron** [comment]
The test case was expecting an error, but it is getting success instead, because of the raised limit. `'This is too long. ' * 10` repeats the string 10 times. Which is below 500 characters.

**Comment by trwnh** [comment]
Ahh, OK. I had no idea what exactly the *10 was doing, especially since the other test used a much less ambiguous `Fabricate.build(:account, note: Faker::Lorem.characters(501))`. Changed 10 to 30 so that the resulting string is 540 characters long.

**Comment by trwnh** [comment]
OK, looks like it passes all tests now!

**Pull request merged**
