### PR TITLE
Update components.scss

### PR DESCRIPTION
**Pull request by StefOfficiel**

### CODE REVIEW

**Review by yiskah — CHANGES_REQUESTED** [review]
Could you please document for us the purpose of this change and how it improves the code? "update" is not enough explanation for this to be merged

**Comment by StefOfficiel** [comment]
With : 


Without :

**Comment by mkody** [comment]
Yeah, so this is like #711 but without using flex.

**Comment by mjankowski** [comment]
Also dupes https://github.com/tootsuite/mastodon/pull/2021

**Comment by ashfurrow** [comment]
Thanks for the pull request @StefOfficiel. As his duplicates work already done in #711 and #2021, I'm going to close.

**Pull request closed without merging**
