### PR TITLE
Add public blocks to /about/blocks

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Add an option to display domain blocks on /about/blocks.

image

This setting has three options:
- Show to no one (disabled, the default)
- Show to logged-in users only
- To everyone

It comes with a similar setting to show the rationale.

## Without rationale

image

## With rationale

image

### CODE REVIEW

**Comment by ThibG** [comment]
Note that it lacks the rationale (as there is currently none included in the database), and it doesn't support censoring domain names.

**Comment by koyuawsmbrtn** [comment]
I need such a feature! It's a real pain in the ass to manually maintain a public blocklist.

**Comment by Kjwon15** [comment]
I am more interested on that "Sandbox" severity. (But it's more like soft-block)

**Comment by Gargron** [comment]
> I am more interested on that "Sandbox" severity. (But it's more like soft-block)

That's just a more commonly understandable phrasing. Sandbox means "silenced". The text and format of the page is taken from mastodon.social's published blocklist on GitHub. Since that was a standalone thing I felt comfortable using different terminology with explanations, but within Mastodon, it might be worthwhile to either a) use "silence" consistently or b) consistently rename all mod actions from "silence" to "sandbox".

**Comment by Kjwon15** [comment]
@Gargron is "silence" also prevent notification from stranger too? if that current hint message from admin UI below should be changed.
> <strong>Silence</strong> will make the account's posts invisible to anyone who isn't following them.

**Comment by ThibG** [comment]
Changed “Sandbox” to “Silence” and rebased on latest master.

**Comment by BenLubar** [comment]
Grouping domains by string-equal rationale would be good when adding rationale is supported.

**Comment by clarfon** [comment]
I feel like rationales should be discussed in another PR. What makes sense is to just have a set list of tags admins can control and allow filtering by tag.

**Comment by ThibG** [comment]
Edited to add support for optionally showing the public comment (rationale).

As for showing the blocklist at all, it can be set to show the rationale to anyone, logged in users, or nobody.

**Review by ykzts — APPROVED** [review]

**Comment by ThibG** [comment]
Rebased, and redesigned it so it better handles long domain names and rationales:
image

**Comment by ThibG** [comment]
Reworded the text a bit and added a disclaimer about suspended servers still being able to retrieve public content, whenever the instance is in `public_fetch_mode?`.

image

**Comment by ThibG** [comment]
@Gargron I think the text is fine, can this be merged?

**Pull request merged**
