### PR TITLE
Add a preferences API so apps can share basic behaviours

### PR DESCRIPTION
**Pull request by Gargron**
Resolve #9821

`GET /api/v1/preferences` example output:

```json
{
  "posting:default:visibility": "public",
  "posting:default:sensitive": false,
  "posting:default:language": null,
  "reading:expand:media": "default",
  "reading:expand:spoilers": false
}
```

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by ykzts** [comment]
oops. this PR was draft

**Comment by Gargron** [comment]
@Tak @connyduck Is this sufficient?

**Comment by Tak** [comment]
@Gargron Sorry, it's not clear to me from the diff - does this also allow apps to _write_ these preferences?

A minor comment on the output format - if the keys are meant to be hierarchical, why not represent them that way in the json?
```"posting": {
  "default": [
    "visibility",
    "sensitive",
    "language"
  ]
},
"reading": { //...```

**Comment by Tak** [comment]
Cool, good discussion.

**Pull request merged**
