### PR TITLE
Remove unused JS dependencies.

### PR DESCRIPTION
**Pull request by progval**
As far as I can tell, they are all unused. I did not actually check Mastodon runs without those, but tests pass.

`Number.isNaN` is never used. `isNaN` itself is used throughout the code, but I can't tell if it depends on that polyfill to work.

### CODE REVIEW

**Comment by Gargron** [comment]
How did you arrive at these conclusions?

**Comment by ProgVal** [comment]
I grepped for their names in `app/`, `config/`, and checked they were not executed by `package.json`.

**Comment by Gargron** [comment]
You missed `streaming/index.js`! I'm pretty sure most of these are used.

**Comment by ProgVal** [comment]
You're right :(

PR updated to keep those

**Comment by ThibG** [comment]
`autoprefixer` is apparently used by webpack, and i suspect `postcss-object-fit-images` is used to polyfill object-fit somehow

**Comment by ProgVal** [comment]
indeed, I missed postcss.config.js too

**Pull request closed without merging**
