### PR TITLE
Use Rails' counter caches through size, restore old spec

### PR DESCRIPTION
**Pull request by ClearlyClaire**
https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache

### CODE REVIEW

**Comment by ThibG** [comment]
This basically implements the change I requested for #8199. According to the documentation, when a counter cache is set up (which is our case), `size` uses that. Otherwise, if the records are loaded, it uses `length` and if that's not the case, it uses `count`.
It seems to re-read the cache counter as needed, producing the old results.

**Comment by Gargron** [comment]
I don't really get why this is important. For example followers relation will never be loaded *entirely* so `Array#size` fallback is useless (would be incorrect). So the only fallback it gives you is `Relation#count`. I like calling the attribute explicitly instead because there is no situation where I would want that count to actually be executed live. The only other thing is that it implicitly reloads the attributes if the followers collection changed on the loaded object, but that's a scenario only valid for the unit test.

**Comment by ThibG** [comment]
> I don't really get why this is important.

It's not extremely important, it just seems more natural to actually use cache counters the way they are intended.

> For example followers relation will never be loaded *entirely* so `Array#size fallback` is useless (would be incorrect).

Yup, we don't really care about this one.

> So the only fallback it gives you is `Relation#count`.

Not really a fallback but the whole point of this.

> I like calling the attribute explicitly instead because there is no situation where I would want that count to actually be executed live.

Fair enough, even though it will never do the query live, because you have a counter cache set up.

> The only other thing is that it implicitly reloads the attributes if the followers collection changed on the loaded object, but that's a scenario only valid for the unit test.

Is that really the case? That's the main reason for this change. You could also explicitly reload the attribute if the collection changed, instead of calling `#size` if you really want to avoid that.

**Comment by Gargron** [comment]
I'm sorry, I don't think this is a good change.

**Pull request closed without merging**
