### PR TITLE
Change “Toots with replies” to “Toots and replies”

### LINKED ISSUE #6870: Cosmetic: "Toots with replies" is not toots with replies
in english locales, the phrasing of the "Toots with replies" tab is misleading. on first encountering that phrase, i interpreted it as meaning "only those toots which have received replies" rather than "both this person's toots and this person's replies to other toots". suggested alternative would be "Toots and replies" (or maybe "Toots & replies").

toots with replies

at a cursory glance, this appears to be a potential issue in other languages as well ("Pouets avec réponses" vs. "Pouets et réponses"), though not universally ("投稿と返信" makes sense)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by mkljczk**
fixes #6870

### CODE REVIEW

**Review by akihikodaki — APPROVED** [review]

**Comment by trwnh** [comment]
Would it break anything to change the id name as well?

**Comment by trwnh** [comment]
@m4skin so why not do it? ;)

**Comment by nightpool** [comment]
@trwnh because it matches the path "/with_replies", which is *would* break things to change

**Comment by trwnh** [comment]
@nightpool That's fair, I'm just nitpicking for consistency

**Comment by shmibs** [comment]
cool ^_^

maybe could also be a good idea to have this as an excuse, native speakers checking over the other (probably just western) languages this may have percolated into via translation?

**Pull request merged**
