### PR TITLE
Enable AR Encryption

### PR DESCRIPTION
**Pull request by mjankowski**
By popular request, this is the AR-encryption-feature portion of https://github.com/mastodon/mastodon/pull/28325 (ie, all the devise-two-factor stuff not changed yet).

There is some discussion on that PR of how to configure these best for distribution, how to document, etc -- opening this one to get all that out of the way first in isolated issue, and then I can rebase the devise two factor changes after we're confident in the basic AR config.

### CODE REVIEW

**Comment by renchap** [comment]
Thanks for splitting this into another PR!

We need an associated documentation PR, updating the installation & configuration instructions. Do you want to take care of it?

My main worry here is that every admin updating to this code will need to update their configuration with the new values.

Those changes will need to be highlighted in the 4.3 changelog, but I am unsure of what to do for admins running the nightly code, where we do not have release notes.

We discussed several times about having something that checks if the essential configuration is there when starting a rails process, failing with an explicit message when it does not (similar to how we detect `RAILS_ENV`). It would solve the issue nicely here I think.

@ClearlyClaire any opinion or guidance?

**Comment by mjankowski** [comment]
> Thanks for splitting this into another PR!

Yes!

> We need an associated documentation PR, updating the installation & configuration instructions. Do you want to take care of it?

Started one here - https://github.com/mastodon/documentation/pull/1427 - will evolve them together as we work it out.

> My main worry here is that every admin updating to this code will need to update their configuration with the new values.

For existing instances - would a simple setup script that spits out 3 random strings (could use rails secret generator thing, I think) be useful?

For new instances - should this be in the setup rake task?

> We discussed several times about having something that checks if the essential configuration is there when starting a rails process, failing with an explicit message when it does not (similar to how we detect `RAILS_ENV`). It would solve the issue nicely here I think.

Right now, because we are using `fetch` without a default, it does blow up if the env vars are not set ... but it does so without any sort of informative message. This is better than launching without a needed value, but not as good as adding something more useful. Can likely improve this.

> 
> @ClearlyClaire any opinion or guidance?

**Comment by renchap** [comment]
> For existing instances - would a simple setup script that spits out 3 random strings (could use rails secret generator thing, I think) be useful?
Yes, having something to generate them accordingly to the Rails best practices is probably very helpful. But we need to be careful that this does not fail because the variables are not configured properly :D

> For new instances - should this be in the setup rake task?
Same as with the current `OTP_SECRET` I assume?




> Right now, because we are using `fetch` without a default, it does blow up if the env vars are not set ... but it does so without any sort of informative message. This is better than launching without a needed value, but not as good as adding something more useful. Can likely improve this.

I think it would be a good idea to have a kind of a quick config check method ran before the Puma or Sidekiq processes start, failing with user-friendly errors. Maybe also migrations? All tasks? But I can foresee that some tasks will need to be exempt of this check, for example when running the setup command.

**Comment by mjankowski** [comment]
Updated again, improving slightly the error output when env var is missing.

**Comment by ClearlyClaire** [comment]
> For existing instances - would a simple setup script that spits out 3 random strings (could use rails secret generator thing, I think) be useful?

Yes, I think we should have a tool similar to `bin/rails db:encryption:init` but tailored for our env variable setup.

> For new instances - should this be in the setup rake task?

Yes, I think these should be generated in the `mastodon:setup` task along with `SECRET_KEY_BASE` and `OTP_SECRET`.

**Comment by ClearlyClaire** [comment]
Regarding `SECRET_KEY_BASE`, what are the interactions, if any, between `SECRET_KEY_BASE`, `config/secrets.yml`, and AR Encryption ?

**Comment by mjankowski** [comment]
> Regarding `SECRET_KEY_BASE`, what are the interactions, if any, between `SECRET_KEY_BASE`, `config/secrets.yml`, and AR Encryption ?

I think they are relatively isolated, in the sense that the narrow AR encryption feature is using the values set in these new env vars (or otherwise passed into config) as the relevant values in the encrypt/decrypt process for column data. But (I'm ~90% sure on this) the previous use cases for the secret key base (cookies, message verifier, other signed things?) don't switch to using these values or the AR encryption approach, and vice versa.

They are potentially related just in the sense that you might store the secret key base and the encryption values in either the rails "secrets" or "credentials" style, as opposed to just plain env vars. I believe from previous discussion we want to stick with env vars for now.

**Comment by renchap** [comment]
> I believe from previous discussion we want to stick with env vars for now.

Correct, otherwise it will make it very painful to configure secrets for people deploying Mastodon using containers

**Comment by ClearlyClaire** [comment]
I think we should:
- have a tool to generate secrets for these three variables
- explain how to generate them when one env variable is missing, instead of just stating it is missing
- generate secrets in the `mastodon:setup` rake task

**Comment by mjankowski** [comment]
Rebased and pushed a few updates:

- Added a check to the initializer which will output a slightly more instructional error message if any required env var is missing
- That error message contains a reference to a built-in rails command to generate values for these env vars
- Added env var generation to the setup rake task, using the same generator method that the built in rails rake task is using

**Review by ClearlyClaire — APPROVED** [review]

**Review by renchap — APPROVED** [review]
Looks good to me. The documentation PR will need to be merged as well.

This will require configuration changes for anyone running a nightly version, but the message should help people to see that it is needed.

**Pull request merged**
