### PR TITLE
Optionally expose public toots over API without auth

### LINKED ISSUE #7087: Make user statuses available when not authenticated
Currently, it seems that /api/v1/accounts/:id/statuses return 401 if you are not authenticated.

My client supports browsing timelines and statuses before logging in, but this breaks showing user pages.

It seems a bit strange that this endpoint requires authentication, since it is publicly visible through the web interface. Could it be changed to work when not authenticated?

(I think the same applies to /api/v1/accounts/:id but I haven't looked into it properly.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by qguv**
Fixes #7087. Admins would have to opt-in.

### CODE REVIEW

**Comment by DagAgren** [comment]
If it is opt-in, then is the choice exposed to the client somewhere so it can adjust its UI accordingly?

**Comment by Gargron** [comment]
@DagAgren I am not sure about all of this, that's a bit premature

**Comment by qguv** [comment]
This feature was implemented with #9573. Closing as this PR is no longer necessary. Cheers!

**Comment by maxf** [comment]
Nice! Thanks :+1:

**Pull request closed without merging**
