### PR TITLE
Fix compatibility with Redis <6.2

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Note that this leaves the possibility of a race condition in which multiple second-factor authentication attempts are performed at the same time and all triggering a mail. This is relatively improbable, though, and would only result in (limited) spam, it would not allow an attacker to avoid sending the mail.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
cc @kmycode

**Comment by kmycode** [comment]
Thanks, it work for me.

```
$ redis-server --version
Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6

RAILS_ENV=test bundle exec rspec spec/features/oauth_spec.rb
```

**Review by ykzts — APPROVED** [review]

**Comment by renchap** [comment]
We will need to remember to revert this once we change our supported redis version

**Comment by ClearlyClaire** [comment]
It seems that we are again incompatible with Redis < 6.2 because of our Stoplight update.

**Pull request merged**
