### PR TITLE
Enable ESLint react/no-deprecated

### PR DESCRIPTION
**Pull request by nschonni**
Opening as a draft to flag the current issues with https://legacy.reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
These would be things needed to upgrade beyond React 16

### CODE REVIEW

**Comment by nschonni** [comment]
@takayamaki maybe you have an idea of how these should be correctly updated to non-deprecated calls

**Comment by takayamaki** [comment]
In fact, I am not used to writing class-based components.
Life-cycle functions of class-based components are very complex and difficult.

Other hand, hooks components are modern and simple.
Also, hooks component can cover most of usecases.
An example of behavior that hook-type components cannot perform is [error boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary).

I seem better to rewrite these components with hooks.

**Comment by ClearlyClaire** [comment]
afaik there are places where we do really rely on the old lifecycle methods and doing otherwise would require a very significant amount of work; that should only be a small portion of the code, though

**Comment by takayamaki** [comment]
Yes, these deprecated life-cycle functions are just the tip of that iceberg.
We can improve everywhere.

**Comment by nschonni** [comment]
@renchap I ran the same autoconversion of the events from your React 18 PR

**Review by renchap — APPROVED** [review]
Good with me 👍

**Pull request merged**
