### PR TITLE
Added Swiss German to languages dropdown

### PR DESCRIPTION
**Pull request by FlohEinstein**
See thread https://chaos.social/@FlohEinstein/111929063655542110 for interest

### CODE REVIEW

**Comment by FlohEinstein** [comment]
To your first comment: oh man, I'm stupid, my mistake! Happened because I tried several different versions of how to write Swiss German in Swiss German. Definitely agree with your point. Can you correct this or do I have to resubmit? 

To your second comment: I think this was addressed in the discussion here, https://github.com/mastodon/mastodon/pull/26634 , this does not need translation. Am I right?

**Comment by FlohEinstein** [comment]
> Based on the other entries in the file, I believe the first entry in the array should be the English language name, i.e. `Swiss German` in this case (But someone correct me if I'm wrong). 

To your first comment: oh man, I'm stupid, my mistake! Happened because I tried several different versions of how to write Swiss German in Swiss German. Definitely agree with your point. Can you correct this or do I have to resubmit? 

> Also I think adding this option might require Swiss German translations of the Mastodon interface on Crowdin first.

To your second comment: I think this was addressed in the discussion here, https://github.com/mastodon/mastodon/pull/26634 , this does not need translation. Am I right?

**Comment by lutoma** [comment]
> Can you correct this or do I have to resubmit?

I don't have merge permissions on the repository anyways, but it's probably easier for the maintainers if you change it.
 
> To your second comment: I think this was addressed in the discussion here, #26634 , this does not need translation. Am I right?

Looks like it, sorry for causing confusion there.

**Comment by FlohEinstein** [comment]
> I don't have merge permissions on the repository anyways, but it's probably easier for the maintainers if you change it. You can just force-push to your branch and the pull request will update itself.

Thanks for the tip, I just did that.

**Comment by renchap** [comment]
According to https://en.wikipedia.org/wiki/Alemannic_German, `gsw` is both the ISO-639-2 code for Alemanic german, and the ISO-639-3 code for Swiss German.

I am not sure what our policy here is, and which language we should use?

**Comment by FlohEinstein** [comment]
> According to https://en.wikipedia.org/wiki/Alemannic_German, `gsw` is both the ISO-639-2 code for Alemannic german, and the ISO-639-3 code for Swiss German.
> 
> I am not sure what our policy here is, and which language we should use?

According to https://www.iso.org/iso-639-language-code, the maintenance agencies for ISO 639-2 and ISO 639-3 are the Library of Congress and the SIL respetively, with the latter being the more complete (according to ISO).
The variable is called ISO_639_3. SIL has two lists, the code set https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab and the language names index https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Name_Index.tab .
Alemannic and Alsatian only appear in the Name Index list.

On the SILs page https://iso639-3.sil.org/code_tables/download_tables it specifically says for the code set
> NOTE: The "Ref_Name" column in this table contains a reference name by which this language is identified in the standard. The Reference Name is employed for ease of use of the code set, and does not imply it is to be preferred in any application to any other name that may be associated with the particular code element as given in the Language Names Index.

I would suggest that we follow the standard's way and use "Swiss German".

**Comment by gunchleoc** [comment]
I always use the CLDR as a reference, so the entry looks correct to me: https://www.unicode.org/cldr/charts/44/summary/gsw.html#225d5b8bb41c393

**Review by mjankowski — APPROVED** [review]

**Review by oneiros — APPROVED** [review]

**Pull request merged**
