### PR TITLE
Revocable sessions

### PR DESCRIPTION
**Pull request by sorin-davidoi**
As discussed in #3243, this introduces revocable sessions as explained [here](http://www.jonathanleighton.com/articles/2013/revocable-sessions-with-devise/).

Left to do:
 - [x] Expose the maximum number of sessions as a configuration option (in `config/environments`?)
 - [x] Make tests pass (see [this discussion](https://github.com/tootsuite/mastodon/pull/3243#discussion_r119736357))

### CODE REVIEW

**Comment by sorin-davidoi** [comment]
Where should the maximum number of session be set? Was thinking of `config/settings.yml`, but it seams that all those options are configurable from the Web UI.

**Comment by Gargron** [comment]
@sorin-davidoi Probably a config/initializers/ file. What maximum number of sessions do you mean though? Why should there be a maximum?

**Comment by sorin-davidoi** [comment]
With this modification, each login creates a new entry in the `session_activations` table. If the user frequently switches devices (or uses "private browsing" or just logs in frequently), I imagine this could lead to some space problems. So we place a limit on the number of active sessions (if `LIMIT` is 5 and your current login creates the sixth session, the first one gets deleted).

**Comment by Gargron** [comment]
@sorin-davidoi I wonder if it would be more appropriate to store sessions in Redis rather than Postgres.

**Comment by sorin-davidoi** [comment]
Not familiar at all with Redis, but I guess that would make #3243 harder? We need to link the subscription to the session that created it, to make sure that they get deleted together.

**Comment by sorin-davidoi** [comment]
Added the configuration option.

**Comment by sorin-davidoi** [comment]
Anything else I can do here to help with this?

**Comment by Gargron** [comment]
It'd be cool to have some input from @mjankowski or @krainboltgreene on this, looks okay to me but perhaps they had to implement something similar for different applications.

**Review by Gargron — APPROVED** [review]

**Comment by sorin-davidoi** [comment]
Rebase, moved the migration date to today.

**Pull request merged**
