### PR TITLE
Dockerfile: add support for arm64

### PR DESCRIPTION
**Pull request by PureTryOut**
I've used this to successfully build an image for an aarch64 device.

It would be nice if someone could publish an arm64 image to Dockerhub btw :smile:

### CODE REVIEW

**Comment by shleeable** [comment]
image
Nailed it.

**Comment by PureTryOut** [comment]
Wait, what? How did I miss that lol. For some reason the whole day I kept reading that as armv6...

Never mind this than, silly me :see_no_evil: 

Still, publishing the arm64 image to Docker Hub would be nice :wink:

**Comment by SuperSandro2000** [comment]
> Still, publishing the arm64 image to Docker Hub would be nice 😉

Which is not possible as long as Mastodon builds on Docker Hubs infrastructure or that build would take around about days.

**Comment by PureTryOut** [comment]
:cry:

**Pull request closed without merging**
