### PR TITLE
Run brakeman in GitHub Actions

### PR DESCRIPTION
**Pull request by nschonni**
Try using GitHub ~~and CodeQL~~ for brakeman results

### CODE REVIEW

**Comment by nschonni** [comment]
Noticed a warning on the current CodeQL workflow
```
[2023-02-19 00:52:50] [build-stdout] [2023-02-19 00:52:50] [build-stdout] ERROR /home/runner/work/mastodon/mastodon/lib/templates/rails/post_deployment_migration/migration.rb:3: parse error
```
Trying to use the custom setup to see if it gets around that after

**Comment by nschonni** [comment]
Sample annotations before suppression
image

**Comment by Gargron** [comment]
FYI I already removed CodeClimate from the repository so you can remove its configuration file.

**Comment by nschonni** [comment]
> FYI I already removed CodeClimate from the repository so you can remove its configuration file.

Thanks, I had dropped that one, but it created a bunch of issues, so I put it back in.
I've run into an issue with the sarif uploads to CodeQL not recogonizing the suppressions in `breakman.ignore`, so I may go back to the simpler approach

**Comment by nschonni** [comment]
@Gargron I deleted the config file again, but it looks like the application is still installed in the GitHub App Settings, since it's showing the failed hook results.

**Comment by nschonni** [comment]
Because of the unrelated CI failure on https://github.com/mastodon/mastodon/pull/24019, I figured it was a better idea to split out the `bundler-audit` to it's own job, that only runs when the Gemfile changes + on a regular schedule

**Comment by nschonni** [comment]
@Gargron is it easier if I restore the codeclimate file and just disable the last brakeman config?

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
oops, sorry I missed that, and I'm actually surprised we've stopped running brakeman… when did that happen?

Is there a way we can have brakeman's results more prominent and readable, instead of having them buried in the Ruby Linting action logs?

**Comment by nschonni** [comment]
> oops, sorry I missed that, and I'm actually surprised we've stopped running brakeman… when did that happen?

When codeclimate was removed

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
