### PR TITLE
Paperclip: add support for Azure blob storage

### PR DESCRIPTION
**Pull request by mistydemeo**
This adds support for Azure blob storage. Like with S3 and other backends, it uses Paperclip; since Paperclip doesn't have builtin Azure storage, this uses the `paperclip-azure` plugin gem. This is using the `md-paperclip-azure` fork because the original gem had some unreleased bugfixes, and to add host alias support. As with the other backends, the initializer code is only run if the appropriate environment variables are set. I've modified the media host code as well to support `AZURE_ALIAS_HOST`, similar to the S3 and Cloudfront paths, along with the appropriate initializer code.

This is in use at digipres.club to host images; I'm using `$AZURE_ALIAS_HOST` to serve images from behind Nginx, and can confirm that everything here works correctly.

### CODE REVIEW

**Comment by mistydemeo** [comment]
I've resolved the merge conflicts. Please let me know if there's anything else I need to do in order to make review easier.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by mistydemeo** [comment]
Thank you!

**Comment by renchap** [comment]
Commenting here to try to reach to this feature's audience: Microsoft dropped support for all their Azure gems, including the one we use. As this gem is now unmaintained, it may contained unpatched security issues. Additionally, it also depends on an old Faraday version, which is causing dependency issues for us.

Are you still using this feature? We are considering deprecating it in 4.3 and dropping it from 4.4, unless someone from the community works in an alternative Paperclip/Azure adapter that is supported, maybe using https://github.com/testdouble/azure-blob ?

**Comment by renchap** [comment]
I created a GH discussion on the topic, with a bit more details: https://github.com/mastodon/mastodon/discussions/31617

**Pull request merged**
