### PR TITLE
Bump Helm app version to 4.0.2

### PR DESCRIPTION
**Pull request by ineffyble**

### CODE REVIEW

**Comment by ineffyble** [comment]
@consideRatio @deepy I could do with a hand debugging this. Clearly something is failing to come healthy in the cluster but there's no useful output or clear way I can debug, and debugging outside of GH Actions would be frustrating for me to set up at present.

**Comment by consideRatio** [comment]
Hey @ineffyble! There is a lot of ourput from the kubernetes namespace report step that runs after the install step that failed. ImagePullBackoff is the failure observed.

It seems images are not available yet

**Comment by ineffyble** [comment]
Thanks! I suspected that the first time but I thought i re-ran after they were definitely available. Then again Docker Hub has been weird today. Re-running.

**Comment by consideRatio** [comment]
👍 

Btw you can make a PR draft, and let that indicate its a WIP.

**Comment by ineffyble** [comment]
This was created as a ready-to-merge PR until the tests failed, then I hastily corrected. You're right converting to draft would have been smart.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
