### PR TITLE
fix regex filter

### PR DESCRIPTION
**Pull request by abcang**
Fixed a bug that regex filter matches HTML tag generated by simple_format.

* completion of line breaks
* tag deletion
* unescape

### CODE REVIEW

**Comment by Gargron** [comment]
Have you noticed if doing the DOM parsing in a loop makes the columns noticeably laggier?

**Comment by abcang** [comment]
I confirmed that it will be delayed.
I would like to think of another way.
Thank you.

**Comment by Gargron** [comment]
@abcang Perhaps something like an extra reducer where you would store the indexable plaintext at time of entry, and then that would become part of the status object in the container and could be filtered-on.

Don't worry if this sounds too complicated, I might do it later...

**Comment by abcang** [comment]
Yes, I think so too.
Instead of deleting tags and escaping on the client side, I'd like to change the server side to send raw content.

**Comment by abcang** [comment]
I changed to send raw content on the server side.
But, in the case of remote toot, I noticed that escaped content was sent.
Therefore, I am planning to return to the process to escape on the client side.

**Comment by abcang** [comment]
I changed it to unescape in reducer.
Therefore, the lag problem was solved.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
