### PR TITLE
Fix incorrect context definition for the "featured" keyword

### LINKED ISSUE #8077: http://joinmastodon.org/ns#featured is improper type
currently, `http://joinmastodon.org/ns#featured` is defined in the context as `toot:featured`. However, this means that the featured thing isn't an `@id`, but an `http://www.w3.org/2001/XMLSchema#string`. The context should contain:
`"featured": {"@id": "toot:featured", "@type": "@id"}` instead.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by Gargron**
Fix #8077

### CODE REVIEW

**Review by nightpool — COMMENTED** [review]
do we also need to fix this for movedTo?

**Comment by Gargron** [comment]
@nightpool I don't know - maybe - we pretend that movedTo is in the ActivityStreams namespace because it comes from a thread on their issue tracker and it should become an official property at some point.

**Comment by nightpool** [comment]
yeah I'm working on getting sensitive and movedTo integrated but afaik
they're not currently in the context document?

**Comment by puckipedia** [comment]
this should indeed be fixed for anything that points to another AS2 object, since those are an ID, and not a string (I would probably consider anything that is always an IRI, like the ostatus predicates, candidate for changing to `@id`? though this might be more preference on my side, seeing as i'm the only one using actual json-ld for activitypub lol)

**Pull request merged**
