### PR TITLE
Change mutes to no longer hide statuses merely mentioning muted account

### PR DESCRIPTION
**Pull request by Gargron**
Mutes should hide statuses/notifications from an account, including when that account is reblogged, but not when a post mentions a muted account, as that is considered by some to be unnecessarily strong. Blocks will continue to hide statuses/notifications that mention a blocked account.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
I'd rather that we wait for the revamp of the filtering system before we make any such change. This can wait.

**Comment by digitalcircuit** [comment]
Context for :+1: with @ClearlyClaire:

I've personally used mutes both for…

* "I need a temporary break from listening to *posts made by* this person without unfollowing them"
   * E.g. they happen to post a lot in the past day and I'm trying to catch up on my home timeline
* "I need a break from being shown *conversations others have with* this person"
   * E.g. someone asked for silence from me so I don't want to be reminded of them meanwhile

It depends on the social situation.  And it sounds like revamping filters might address the second use case.  Another toggle (akin to `Hide notifications`) could cover this too, but I'd understand not wanting to add yet another option.

**Comment by trwnh** [comment]
can't you just mute the keyword `@username` or does that not cover the situation fully? in other words, what "revamp" is necessary before merging this pr?

**Comment by ClearlyClaire** [comment]
> can't you just mute the keyword `@username` or does that not cover the situation fully?

You can approach that with filters on `@username`, but `@username` appearing in the text of the message is an implementation detail of Mastodon, and other implementations may use the display name in the mention text, or leave it entirely. There's also the issue with the username being shared by multiple people on different servers.

> in other words, what "revamp" is necessary before merging this pr?

This referred to #18058, which is complete, and allows adding filter types without special handling from clients. Now, it would take implementing a new filter type on mentions, but that hasn't been done yet.

**Pull request closed without merging**
