### PR TITLE
Greater DM visibility

### PR DESCRIPTION
**Pull request by TheInventrix**
Highlights the envelope icon and lightens the status background to make
direct messages more visually distinct.

I've found it a little frustrating how easily direct messages can get mixed in or lost with the rest of your notifications and feed and feel that, since they're private messages specifically for me (as opposed to parts of a public conversation) and there's no discrete category for them, they should at least have some degree of elevated visual status.

### CODE REVIEW

**Comment by expenses** [comment]
Do you think you could fix the merge conflicts and take a screenshot of what this looks like?

**Comment by TheInventrix** [comment]
Sure thing! I'll get that up tomorrow; it looks like there were a bunch of class additions since the last tag that're causing the conflict but it should be a simple update.

**Comment by TheInventrix** [comment]
The conflicts should be resolved so it's only making the changes required for the added feature and not affecting anything else; I'm kind of new to github so I'm not sure why it still says there are conflicts.

Here's a screenshot!
dm demo

**Comment by expenses** [comment]
That looks good, maybe a little too bright though. Do you think you could use a colour between the darker grey and the lighter grey?

**Comment by TheInventrix** [comment]
Sure! Do you mean the DM background or the envelope icon? (I'm guessing the latter?)

**Comment by ashfurrow** [comment]
Thanks for the pull request @TheInventrix – looks cool! Sorry for all the merge conflicts 😅 Lots of CSS changes lately. Would you mind resolve the conflicts again and posting a screenshot of the updated design? I'd love to get this reviewed and merged before there are more conflicts 😄

**Comment by TheInventrix** [comment]
It took me an embarrassingly long time to figure out I was supposed to resolve the conflicts from the "Resolve Conflicts" page. As in, actually edit it. Ha ha. Ha. Ha...

Here's an updated screenshot!
dm demo 2

**Comment by ashfurrow** [comment]
Cool, looks nice! There are a few failing tests on Travis CI – let me know if you'd like some help with them.

**Comment by Gargron** [comment]
Relevant info from failing travis:

```
/home/travis/build/tootsuite/mastodon/app/assets/javascripts/components/components/icon_button.jsx
  38:20  error    'highlight' is missing in props validation  react/prop-types
  40:6   warning  Trailing spaces not allowed                 no-trailing-spaces
```

**Comment by beatrix-bitrot** [comment]
this seems like a good fix just in need of rebasing and a little tidy up @TheInventrix are you up to it? if not maybe we could get someone to help?

**Comment by TheInventrix** [comment]
@beatrix-bitrot I'll give it a shot! (I should learn how to do that, anyway.) And try to fix the travis build issue in the process.

**Pull request closed without merging**
