### PR TITLE
Change wording of “Content cache retention period” setting to highlight destructive implications

### PR DESCRIPTION
**Pull request by ClearlyClaire**
The effects of the setting introduced by #19232 are surprising to many admins and not documented clearly enough, as evidenced by the PR's comments and issues such as https://github.com/mastodon/mastodon/issues/23206.

I am not sure the feature itself is useful to many admins in its current form, but implementing a useful version of it that doesn't end up being too inefficient is a complex task.

In the meantime, I think it is worth rewording the description to make the destructive implications of the setting much clearer.

## Before

> Posts from other servers will be deleted after the specified number of days when set to a positive value. This may be irreversible.

image

## After

> All posts and boosts from other servers will be deleted after the specified number of days. Some posts may not be recoverable. All related bookmarks, favourites and boosts will also be lost and impossible to undo.

image

### CODE REVIEW

**Comment by trwnh** [comment]
> This may be irreversible, and favorites and bookmarks will be permanently lost.

i'd add a mention of private and direct statuses, which are arguably even more important

**Comment by ClearlyClaire** [comment]
That would make sense, however:
- I don't think there is any precedent in settings “hints” that are not a single paragraph (also technically the hint is in a `span` and I don't think lists are allowed there)
- private posts *can* currently come back if they are boosted by their author
- “direct posts” is not terminology we currently use

**Comment by trwnh** [comment]
those are all things that can be changed, not a dealbreaker imo

i guess the most concerning is the use of `<span>` for the hint which makes it not strictly semantic to put lists in there, but it's still *possible* i guess. just not best practice. but then again, best practice would be to use two `<p>` tags and a `<ul>`, maybe inside a div if you feel like it. alternatively, you could have the warning be its own `<div>` and display it below/after the span.

as far as wording changes: that last bullet point can be changed to two bullet points:

> - Posts sent to followers will be permanently lost unless boosted again by the original author
> - Posts sent to mentioned users only will be permanently lost

this reads somewhat worse though imo -- i think it's less bad to just say "direct posts" and leave out the bit about private boosts, even if it's less precise. although if precision is important, it's not a terrible option...

**Comment by ClearlyClaire** [comment]
This would involve more code changes than I'd like but:
image

**Comment by ClearlyClaire** [comment]
Pushed a second commit that changes it to the following:
image

I am not very happy with the CSS hack or the amount of HTML in the translation string, though.

**Review by ElanHasson — APPROVED** [review]

**Comment by selfawaresoup** [comment]
It's really unfortunate that this deletes bookmarks entirely with no chance of recovery. Seems like a pretty big oversight in how bookmarks are stored and it's bound to have unforeseen and unintended effects for users.

**Comment by ClearlyClaire** [comment]
Uncoupling bookmarks storage from post storage would be quite a large change and probably not worth it. I think it would make more sense for a feature that deletes only posts that are not faved, bookmarked, boosted and so on, but it's not what this particular feature has been designed to do.

**Comment by mejofi** [comment]
@ClearlyClaire That also works, and is probably the better option 🙂

**Comment by asonix** [comment]
A few admins recently have been talking about a problem where replies to a user's post were vanishing. I think that's also related to this setting.

If there is a way to purge old remote posts without also purging replies to local posts, that would be welcome to many of us. I (an admin) and other users have found this frustrating

**Comment by ClearlyClaire** [comment]
Simplified the wording and layout:
image

**Comment by ClearlyClaire** [comment]
Fixed the styling:
image

**Review by Gargron — APPROVED** [review]

**Pull request merged**
