### PR TITLE
Replace hide toot with hide post

### PR DESCRIPTION
**Pull request by seanthegeek**
Replace hide toot with hide post

### CODE REVIEW

**Comment by shleeable** [comment]
Disgusting.

**Comment by ykzts** [comment]
https://github.com/mastodon/mastodon/blob/2889c686108e89a87317505f93b841f5a8a6649b/app/javascript/mastodon/components/status_action_bar.js#L42

The Web UI locale will not be reflected unless the original file is changed.

**Comment by ykzts** [comment]
Do not change anything other than en.yml to avoid conflicts with changes in Crowdin.

**Comment by seanthegeek** [comment]
@ykzts In that case, I'll close this PR, and create a new clean branch with just my original changes?  should I also edit [status_action_bar.js](https://github.com/mastodon/mastodon/blob/2889c686108e89a87317505f93b841f5a8a6649b/app/javascript/mastodon/components/status_action_bar.js#L42) like you mentioned earlier?

**Comment by ykzts** [comment]
You do not have to close the Pull Request. Just rewind unnecessary changes.

**Comment by ClearlyClaire** [comment]
Translations are managed on Crowdin and the files should not be changed in PRs.

**Comment by seanthegeek** [comment]
There we go. Finally reverted properly. Sorry. I've never had to revert that far back before and had to do some googling.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
