### PR TITLE
fix: disable "post" button when no text was entered, and no other media is attached

### LINKED ISSUE #30512: [regression] "post" button does not get disabled for an empty post
### Steps to reproduce the problem

1. Open the Mastodon web ui, on any page with the new compose UI
2. The "post" button in the new compose UI will be enabled
3. Enter a single space into the compose box
4. The "post button" will change to its "disabled" state

### Expected behaviour

The post button should be disabled in both cases

### Actual behaviour

The disabled check doesn#t account for "post has no content"

### Detailed description

The check [here](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/features/compose/components/compose_form.jsx#L109) only accounts for:
- post is too long
- post has no media and is only whitespace

The check for "post has no media and is empty" is missing

### Mastodon instance

corteximplant.com

### Mastodon version

v4.3.0-alpha.4

### Browser name and version

FF 126.0.1

### Operating system

Win10

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by Sirs0ri**
fixes #30512

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This is not a regression and has been Mastodon's behavior for a very long time. This is intended because the alternative is having the main action button look disabled by default.

**Comment by Sirs0ri** [comment]
Oh, my bad about the regression part then, I was pretty certain it had been disabled by default before. 

Why is that behaviour intended? The button doesn't do anything until the user enters some text / attaches media, which can lead to some confusion whether the UI is responding to user actions (if I press "post" without having any content attached, I'd expect a) an empty post to be created or b) to get a warnign telling me the data I submitted wasn't complete). Generally a disabled "submit" button on a form that's not filled out enough to submit it is the way to give exactly that feedback.

**Comment by ClearlyClaire** [comment]
Yes, I understand that this is not ideal, but the button does get disabled if unable to post as soon as the form is not blank.

**Comment by mjankowski** [comment]
Doing PR triage - closing this one on assumption that the prior discussion concludes with "this is intended, wont change".

Please comment/reopen if I've misunderstood something and there's still something to extract here!

**Pull request closed without merging**
