### PR TITLE
Occitan 500 error page internalizacion

### PR DESCRIPTION
**Pull request by JeanGauthier**

### CODE REVIEW

**Comment by ykzts** [comment]
@JeanGauthier thank you for Pull Request. But,

> Please mind that there is no use in submitting translations for the `errors.500` string, as assets:precompile generates a single version.

see #5067

**Comment by JeanGauthier** [comment]
Oh okay

**Comment by nightpool** [comment]
@JeanGauthier Hey, just a heads up that we *did* fix i18n for the error page for instances that have a *default locale*: https://github.com/tootsuite/mastodon/pull/5099

**Comment by nightpool** [comment]
That is, if the admin has selected a locale for the server.

**Pull request closed without merging**
