### PR TITLE
Improve searching for private toots from URL

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Most of the time, when sharing toots, people use the toot URL rather than the toot URI, which makes sense since it is the user-facing URL.

In Mastodon's case, the URL and URI are different, and Mastodon does not have an index on URL, which means searching a private toot by URL is done with a slow query that will only succeed for very recent toots, and will otherwise timeout.

This change gets rid of the slow query, and attempts to guess the URI from URL instead, as Mastodon's are predictable.

### CODE REVIEW

**Comment by Gargron** [comment]
I understand why, but I am not entirely comfortable with this change. We're relying on a Mastodon-specific assumption to make something work better, which means suddenly other implementations have an incentive to adopt a Mastodon-specific design decision that's not in the spec...

**Comment by ThibG** [comment]
Well, webfinger and HTTP Signatures aren't in the spec either. Not having HTML in toots or having only 4 attached images max isn't in the spec either.

I don't know how other implementations do it, but Pleroma, for instance, does not have a different `url` and `id` for statuses, so it doesn't have this issue at all.

**Comment by ThibG** [comment]
> which means suddenly other implementations have an incentive to adopt a Mastodon-specific design decision that's not in the spec...

I'd like to say that today, other implementations already have an incentive to adopt a specific design decision to work better with Mastodon (and better than Mastodon actually works with itself): using the same value for `url` and `id`.

This PR would just give them another option, and improve Mastodon-to-Mastodon functionality.

**Comment by ariasuni** [comment]
Not being able to find a private toot by its URL is confusing and frustrating for users. I believe this would greatly improve usability of Mastodon in this area.

**Comment by Gargron** [comment]
Can we not just rely on authorized fetch (i.e. remove the URL query and fallback to network)? Will probably be faster and more reliable. I remember back when we had two different ID systems for URLs and URIs.

**Comment by ThibG** [comment]
Network is the default, and database query is the fallback. There are two issues with using authorized fetch for this:
- some implementations (e.g. pleroma) are decided to never render non-public objects on fetch
- privacy issues: we'd have to sign every URL search with the account requesting the search. I proposed that ages ago, it was deemed too much of a privacy issue, and adding an opt-in option was deemed too complicated UX

> Will probably be faster and more reliable.

How so? We have an index on uri…

**Review by Gargron — APPROVED** [review]
I do not like the hack at all code-quality wise but functionality-wise it does no harm. At least it removes the slow query. I think that in the future we should either revisit signing URL searches with the searching user and remove this hack or intentionally remove the ability to search for private posts by URL and remove this hack.

**Pull request merged**
