### PR TITLE
Add styles to suffix of display name

### PR DESCRIPTION
**Pull request by ykzts**
Additional to #9038

### CODE REVIEW

**Comment by Gargron** [comment]
I just have to wonder if this is the best fix, or if I should just revert #9038. A space is supposed to be more natural there...

**Comment by ykzts** [comment]
I think that space should be displayed even in rtl.

**Comment by mabkenar** [comment]
Yes, a space should be there, but not inside bdi element. Outside of it, so that when page is RTL and display name is in latin, the space follows the RTL flow, instead of being trapped inside the bdi box.

**Comment by Gargron** [comment]
But the space *wasn't* inside the bdi tag, it was after the tag (between bdi and span)

**Comment by mabkenar** [comment]
> But the space _wasn't_ inside the bdi tag, it was after the tag (between bdi and span)

Oh I see the root for my confusion: In the web app, space is outside the bdi tag (correct). In public pages, it is inside the bdi tag (incorrect). This is what I see right now on my instance at v2.5.2.

**Pull request closed without merging**
