### PR TITLE
Add explanation to mute dialog, refactor and clean up mute/block UI

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Move some stuff out of #11562

image

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by Gargron** [comment]
I believe there should be space between the "heading", which is the confirmation prompt, and the "explanation" element. Also, I am now noticing that it's odd to mix a left-aligned toggle element with a center-aligned text. Either both should be centered, or they all should be left-aligned.

**Comment by Gargron** [comment]
"This will hide posts from them and posts mentioning them, but it will still allow them to see your posts and follow you."

**Comment by ThibG** [comment]
Updated to this:
image

**Comment by ThibG** [comment]
Updated again, everything is left-aligned now

image

**Pull request merged**
