### PR TITLE
Changed retries and rescued in ActivityPub::ProcessingWorker

### PR DESCRIPTION
**Pull request by noellabo**
- Reduce the number of retries, as repeated retries are not effective.
- Give up RecordNotUnique immediately.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]
I think this is fine but would like opinion from @ThibG as well

**Comment by ThibG** [comment]
Hmm… where would `ActiveRecord::RecordNotUnique` be raised? It seems fine, but it may also hide bugs, I guess…
I think reducing the number of retries should be fine: while temporary errors are possible, they seem unlikely.

**Comment by noellabo** [comment]
The cause of ActiveRecord::RecordNotUnique has not been identified. May be due to configuration. I'll investigate more closely.

On the other hand, this error report is useful to the developer, but I'm not sure if it helps the server administrator, because the server administrator can't handle it.

P.S.
My server is accessing two replicated PostgreSQL servers through makara from puma and sidekiq located in different VPS operators. I am getting the above error from time to time.

**Comment by ThibG** [comment]
Well, having the error visible to administrators would enable them reporting it to us. I'd be more confident with this patch if we knew what caused that error, even though it's unlikely to be a big deal.

**Comment by Gargron** [comment]
Sidekiq may process jobs before data has replicated in postgresql, leading to some jobs being discarded (because we often catch and discard record not found errors). One of the reasons why my Sidekiq is connected directly to master... i wonder if you experience the same issue?

**Comment by noellabo** [comment]
I am monitoring for dead jobs where RecordNotUnique occurs.

1. Duplication of `index_statuses_on_uri` by Announce
2. Duplication of `index_favourites_on_account_id_and_status_id` by Like

My server has 3 relays connected and the same Object is often reached 4 times in Create or Announce.

- Create did Redis Lock, but Announce did not. https://github.com/tootsuite/mastodon/pull/14365
- Like Activity comes from Misskey's reaction. I look forward to the progress of #13275.
- Most of the other dead jobs in ActivityPub::ProcessingWorker were WebFinger timeouts. https://github.com/tootsuite/mastodon/issues/14091

The cause of RecordNotUnique has been resolved, so I will leave it so that I notice the abnormality when it occurs again.

**Comment by ThibG** [comment]
Hmm, not sure what to do about the Misskey reactions… maybe just… drop them, since they don't really mean the same thing as a `Like`?

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
