### PR TITLE
Better admin view of statuses

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Some fixes in the admin view:
- Clearly display whether a toot is a boost or not (previously, boosts were misrepresented as original content from the booster, without the media attachments)
- Display toot's privacy

screenshot-2018-3-30 etat du compte - mastodon instance perso de thibg

This also changes how toots are displayed on the public/simple page.

screenshot-2018-3-30 t h i b g thib sitedethib com

### CODE REVIEW

**Comment by nightpool** [comment]
Can you include a screenshot of the new boost indication?

**Comment by Sylvhem** [comment]
Have you tried to put the privacy icon to the right of the timestamp instead of the left? By doing so, all the icons will be aligned. I think it'll look even better like that.

**Comment by ThibG** [comment]
@Sylvhem yes, why not!
Pushed a change to do just that.

screenshot-2018-4-2 t h i b g thib sitedethib com

screenshot-2018-4-2 t h i b g thib sitedethib com 1

**Comment by Sylvhem** [comment]
@ThibG I was more thinking of the way toots are displayed on the admin panel (your first screenshoot).

**Comment by ThibG** [comment]
Oh ok, sorry about that. I'll try to do that.

**Comment by ThibG** [comment]
@Sylvhem updated the PR, this is the current result:

screenshot-2018-4-2 etat du compte - mastodon instance perso de thibg

**Comment by Gargron** [comment]
Notes before review:

- There is another PR that touches reports awaiting review currently, so careful about conflicts
- I feel like there might be value in stopping trying to display toots in admin UI like real toots and instead just use simplified table views?

**Comment by ThibG** [comment]
- As far as I know, there is no current PR conflicting this.
- Hm… maybe. Although I'm not too sure how that table should look like.

**Comment by ThibG** [comment]
@Gargron ping? Admittedly, there are two changes here: a really simple fix to admin views, and an additional marker for toot privacy in all static views. The second change has value in both admin and non-admin views. I could split it in two PRs if you want.

**Comment by Gargron** [comment]
I think this is obsolete now.

**Pull request closed without merging**
