### PR TITLE
Weblate translations (2018-08-27)

### PR DESCRIPTION
**Pull request by renatolond**

### CODE REVIEW

**Review by trebmuh — CHANGES_REQUESTED** [review]
Looks to be another occurrence of https://github.com/tootsuite/mastodon/issues/8451 (for the French translation)

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
@trebmuh I don't see any deletions in fr.yml or fr.json in the changeset?

**Comment by renatolond** [comment]
I manually fixed the removal, but there was indeed missing translations for a couple of languages, here:
https://github.com/tootsuite/mastodon/pull/8483/commits/4174a12f0ec569c3a738cf8545058f60b6d625c6
https://github.com/tootsuite/mastodon/pull/8483/commits/e8eee49a60da464d2010021805176fb24245d04e

**Comment by trebmuh** [comment]
Thanks @renatolond !

**Pull request merged**
