### PR TITLE
Add OTel Collector and OTel instrumentation to backend

### PR DESCRIPTION
**Pull request by julianocosta89**
Hello all 👋🏽 

This PR adds OpenTelemetry instrumentation to the Mastodon backend.
We are configuring the OTel SDK and initialising just the used instrumentation libraries in order to have more control over the dependencies.

For the OTel Collector, instead of using the OpenTelemetry Collector Contrib distro, we are using the OpenTelemetry Collector Builder (OCB) to build a binary containing just the dependencies used in our specific Collector. This gives us more control over the components that will be part of our Collector.
If any further component needs to be added in the future, we just need to add the `gomod` component to the manifests.

We've added 2 Collector config files, being one for Datadog and one named "default". The default one prints the Traces, Metrics and Logs to the console, but it already has the `otlp` and `otlp/http` exporters as part of it, to make it easy to configure with different backends.

Here is a screenshot of the 2 created services in Datadog:

image

### CODE REVIEW

**Comment by dmathieu** [comment]
See also https://github.com/mastodon/mastodon/pull/20338

**Comment by robbkidd** [comment]
Heeeey! I'm the author of #20338. I propose we team up!

The initializer in #20338 has some nuance in it I recommend:

* wrap the OTel requires and configure in a guard that checks for the presence of any OTEL_* environment variables
* instrument ActiveRecord via ActiveSupport::Notifications instead of monkeypatches; [the patches conflict with attr_encrypted's patches](https://github.com/mastodon/mastodon/pull/20338#issuecomment-1311226122)

I'm a fan of your idea to include an OTel Collector. I don't know how to provide a mechanism for admins to customize the Collector's config, though. When I first opened #20338, I had pictured the routing of telemetry being left to OTel Ruby SDK environment variables which are more straightforward to customize by Mastodon admins.

let our powers combine!

**Comment by julianocosta89** [comment]
Hello @robbkidd happy to collab and get #20339 done 🤩 
I'll address your suggestions by next week, but besides that do you see anything else we could make to get that going?

**Comment by julianocosta89** [comment]
hey @robbkidd, thanks for the suggestions again.

The `ActiveSupport` snippet I took from your PR. If you'd like to have the credit for it, let me know and I can remove it, so you push in this PR.

Besides that all other suggestions were applied.

**Comment by renchap** [comment]
Superseeded by #30130

**Pull request closed without merging**
