### PR TITLE
Preload common JSON-LD contexts

### LINKED ISSUE #9411: Common JSON-LD contexts should be bundled with Mastodon
In many cases, remote JSON-LD documents have to be loaded to parse/canonicalize JSON-LD documents.
This is the case for outbound statuses, which require at least `https://w3id.org/security/v1`, `https://www.w3.org/ns/activitystreams`, and `https://w3id.org/identity/v1`.

The last one is currently unavailable, so any instance not having it in cache is currently screwed.

Such documents used to be bundled with Mastodon, but that was reverted in d40ef1129e6df5098e150ff3f6ee4eda9b7efcf8. I don't think saving a few MB of RAM was worthwhile here.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #9411

### CODE REVIEW

**Comment by ThibG** [comment]
@nightpool It doesn't go through the `load_jsonld_context` codepath for those for the affected JSON-LD contexts, so it should be ok.

**Review by nightpool — CHANGES_REQUESTED** [review]
i want to make sure this gets tested on an affected instance (can just be locally after clearing redis) before merging.

**Comment by ThibG** [comment]
It doesn't try to get the cache anymore when I send a toot, so I'm pretty confident it fixes it.

**Comment by kit-ty-kate** [comment]
I'm testing it right now. Give my 30 minutes to rebuild the images and restart the services.

**Comment by Gargron** [comment]
This is counter to #7301

**Comment by nightpool** [comment]
@Gargron yes, because of urgent federation problems that some instances are experiencing.

**Comment by ThibG** [comment]
@Gargron I would argue that not depending on HTTP requests to a potentially unreachable remote JSON-LD document that isn't supposed to change is probably worth a slight increase in initial RAM usage

**Comment by Gargron** [comment]
OK, I've read the problem description. Thoughts:

Context is not neccessary for HTTP signatures, so why is federation broken when the context is unavailable, even though only linked data signatures should be broken? We should contain that error within that functionality, and make sure it doesn't break everything.

I have originally replaced the preloads with a cache mechanism because there is no guarantee that an incoming document will use any of the preloaded contexts, which would mean an arbitrary HTTP request. The preloads are a false sense of security in a way. Perhaps even more importantly, using cache instead of preloads allows even older instances to understand signatures from newer instances if the context has changed. However, I can't deny that currently things are bad because we don't have preloads as a fallback anymore.

**Comment by ThibG** [comment]
@Gargron yes, we could decouple those two things (signing the payload, and sending a potentially unsigned payload), but I don't think there is much sense in that if we can make sure signing the payload is always ok.

My commit doesn't remove the loading and caching of unknown remote contexts. I don't think such “core” contexts are supposed to change, are they? Also, I think preloading them has performances advantages over re-parsing and re-loading them from cache.

**Comment by nightpool** [comment]
@Gargron i agree, but we should get this fix out urgently and then work on making LDsigs fail-fast later.

@ThibG 

>I don't think such “core” contexts are supposed to change, are they?

contexts are assumed to be mutable by default, although i believe w3c does provide versioned activitystreams contexts now.

**Review by Gargron — APPROVED** [review]

**Review by nightpool — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
I confirm that the fixes works on my instance (sorry for the delay, the build failed halfway through)

**Pull request merged**
