### PR TITLE
Add ability to change notification sound

### PR DESCRIPTION
**Pull request by lfuelling**
This PR adds the ability to change the notification sound by adding a new dropdown to the notification settings:

Screenshot of settings page

The default setting (nothing in database) is the "Boop" sound so nothing would change for existing setups. 
This PR does not require any migrations.

New sounds can be added similar to how it works with themes:
1. Place sound files in `/public/sounds`
2. Add sounds to config: `/config/sounds.yml`
3. Add display names to `<lang>.yml#<lang>.sounds` (optional)

Since a single element dropdown looks kind of weird, I have included a second notification sound. 
Feel free to change or delete it, it's CC0 licensed (not made but edited by me):
https://freesound.org/people/kafokafo/sounds/128349/

### CODE REVIEW

**Comment by lfuelling** [comment]
The CodeClimate issues are out of scope and were present before, I have no idea why the check-i18n test fails; I have no changes in git after running `bundle exec i18n-tasks normalize` again (after d0f6ef6).

**Comment by ClearlyClaire** [comment]
The i18n issues seem to be caused by spurious changes in a bunch of local files. The way `i18n-tasks` handles files as `normalized` may depend on the particular version of yaml libraries installed, unfortunately. For the purposes of this PR, I'd just revert changes to all the locale files except for `en.yml` and `simple_form.en.yml`.

Otherwise this looks good to me.

**Comment by lfuelling** [comment]
You know what you damn bot, I'm going to do you the favor. 

Not like any Mastodon dev will react to this issue anyways...

**Comment by dowodenum** [comment]
Found this issue on duckduckgo after 10 articles of "how to change notification settings"

+1 to this feature - it's one of my only reasons for using a desktop client or thirdparty app.

**Comment by lfuelling** [comment]
Reopened on request by @ShadowJonathan

**Comment by lfuelling** [comment]
It was a misunderstanding, see last mentioned PR.

**Pull request closed without merging**
