### PR TITLE
CSS Variables for Sass $colors 💅

### PR DESCRIPTION
**Pull request by jpdevries**
One step closer to supporting “theming”. This would allow user agents and theme designers to customize the colors of the UI with very little CSS and no knowledge of the CSS selectors.
This is particularly useful for [supporting themes that respond to High Contrast Media queries](https://github.com/jpdevries/eureka#-accessible-themes).

CSS Variables aren’t completely safe to use. I’m not familiar with how the Sass is built, but thinking we’d need to:
- [ ] add a postcss plugin for CSS Variables fallbacks

CSS Tricks has a write up on [using CSS Custom Properties for Theming](https://css-tricks.com/css-custom-properties-theming/?utm_campaign=CSS%2BLayout%2BNews&utm_medium=email&utm_source=CSS_Layout_News_92)

<details open>
  <summary>Screenshots</summary >
  <div>
    
    
    
  </div>
</details>

### CODE REVIEW

**Comment by expenses** [comment]
Sounds good. The support for css variables isn't totally there yet though (http://caniuse.com/#feat=css-variables), so we need to be able to work around that.

**Comment by jpdevries** [comment]
@expenses yup. I believe postcss would turn 

```css
body {
  background: var(--color1, $color1);
}
```

to:
```css
body {
  background: $color1;
  background: var(--color1, $color1);
}
```

For backwards compatibility of the default colors

**Comment by jpdevries** [comment]
@expenses CSS varibales landed in a Edge today. Woot! 
https://twitter.com/malyw/status/851913674021371904

**Comment by wavebeem** [comment]
You can add a fallback but still have dynamic CSS variables in browser that support them? I didn't know that was possible.

**Comment by wavebeem** [comment]
Also I found a good example of updating CSS variables using JS!

https://codepen.io/wesbos/pen/adQjoY?editors=1010

**Comment by yookoala** [comment]
SASS / SCSS already has [variable support](http://sass-lang.com/guide#topic-2) that will naturally support all browser. So this sounds a bit strange to me. Do we really have a use case for this add-on?

**Comment by marrus-sh** [comment]
@yookoala The use-case for this is users who are styling Mastodon with Stylish themes (ie https://userstyles.org), since there isn't currently a way for users to adjust Mastodon's appearance otherwise. Users don't have access to the original SASS so using CSS variables would make this process much simpler.

If Mastodon supported setting its colours through Settings or elsewhere then having CSS variables would be less of an issue.

**Comment by yookoala** [comment]
But if Mastodon were to support theming through CSS variables, there will be no effect for older browsers. Plus theming through variables is, in my experience, usually inflexible. Would it be better off for Mastodon, as a platform, to better support theming through additional theme CSS files?

**Comment by jpdevries** [comment]
@yookoala see https://philipwalton.com/articles/why-im-excited-about-native-css-variables/

> But if Mastodon were to support theming through CSS variables, there will be no effect for older browsers.

Correct. This feature would be considered progressive enhancement, just like the flexbox layout that is currently used.

> Would it be better off for Mastodon, as a platform, to better support theming through additional theme CSS files?

Probably not. CSS Variables are way easier and don't require the theme designer to have any knowledge of the CSS selectors or structure. They just override the variables. CSS Variables are now safe to use in all modern browsers
http://caniuse.com/#search=css%20variables

**Comment by jpdevries** [comment]
I just tried out `postcss-custom-properties` for CSS Variable fallbacks in a project. It worked well, you just need to set the preserve option to true 

Turns
```css
.dangerous {
  color: var(--dangerous, red); }
```

into 
```css
.dangerous {
  color: red;
  color: var(--dangerous, red); } /* old browsers will ignore this */
```

**Comment by yookoala** [comment]
Can we have PostCSS setup to work with our current SCSS?

**Comment by wavebeem** [comment]
@yookoala `var(--blah)` syntax is already passed through Sass untouched, so you should be able to run PostCSS on top of the Sass results. If I recall correctly autoprefixer is actually a PostCSS plugin, and many people use that with Sass and LESS.

**Comment by jpdevries** [comment]
Note: With PostCSS you want to make sure to set preserve to true to no flatten the variables
https://twitter.com/nucliweb/status/856060132102463488

**Comment by mjankowski** [comment]
Closing after merge of https://github.com/tootsuite/mastodon/pull/2912

**Comment by jpdevries** [comment]
@mjankowski #2912 is great but doesn't add CSS Properties for non-Sass related theming support. Would you like me to rebase and submit another PR that does?

**Comment by mjankowski** [comment]
Sure!

**Comment by yookoala** [comment]
I have studied the scss code in detail. I feel it is hard job to change all the variables to CSS variables.

There are around 460 color variable calls in the current SCSS files. And more than 100 of them involves [lighten()] or [darken()] SASS method call. From what I read, these preprocessing script call cannot be translated to CSS Variables until [color-mod()] function is adopted by major browsers. There are also occurrence of SVG in SCSS that uses the theme color variables with method call.

Also, the lighten / darken percentages of these are not entirely consistent. It is not like we can rewrite them into just a few color.

Until we rewrite all those method call into pure SASS-variables, there is no way we can convert the whole theme to fully support CSS variables.

[lighten()]: http://sass-lang.com/documentation/Sass/Script/Functions.html#lighten-instance_method
[darken()]: http://sass-lang.com/documentation/Sass/Script/Functions.html#darken-instance_method
[color-mod()]: https://drafts.csswg.org/css-color/#funcdef-color-mod

**Comment by jpdevries** [comment]
@yookoala Yes you are correct that not all the current colors can be translated. In this PR, I just took a first step into translating all the simple color variables. Basically we would need to come up with names and variables for all the `lighten()` or `darken()` colors. I understand that would need to be part of a larger more organized effort. Would be willing to help out, as I think it would be a dream to be able to theme!

**Pull request closed without merging**
