### PR TITLE
Allow @ at the end of an URL

### LINKED ISSUE #30860: Unable to link to URLs ending with a @
### Steps to reproduce the problem

1. Look at this post: https://mastodon.gamedev.place/@CarePackage17/112688958098239356
2. Try clicking the link
3. Observe it leads to a 404 instead of https://gta.fandom.com/wiki/TW@

### Expected behaviour

The link should include the @ as part of its URL: https://gta.fandom.com/wiki/TW@

### Actual behaviour

the link gets broken

### Detailed description

_No response_

### Mastodon instance

mastodon.gamedev.place

### Mastodon version

4.2.9

### Browser name and version

Firefox Nightly 129

### Operating system

Android

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by adamniedzielski**
Fixes #30860

### CODE REVIEW

**Review by oneiros — DISMISSED** [review]
This is an unusual location for a spec file. But I guess this is an unusual location for a gem patch, so this kind of makes sense :slightly_smiling_face:

I researched this problem a little and this seems to be a known deficiency of the `twitter-text` gem and (at least at some point) with twitter itself. See https://github.com/twitter/twitter-text/issues/201

And the fact that their idea of how an URL should end falls too short was the original reason to patch this here. So I think the fix is correct.

Thanks a lot!

**Comment by mjankowski** [comment]
Agree that the fix looks good - but wonder if the spec should be at the link extraction level and not directly on the regex? Basically treat this regex as the equivalent of an impl detail or private method, and assert that the link can be pulled out correctly from text. Might make the spec location make more sense, and might make it easier for us to potentially replace the (unmaintained) twitter text gem at some point?

**Comment by oneiros** [comment]
> Agree that the fix looks good - but wonder if the spec should be at the link extraction level and not directly on the regex? Basically treat this regex as the equivalent of an impl detail or private method, and assert that the link can be pulled out correctly from text. Might make the spec location make more sense, and might make it easier for us to potentially replace the (unmaintained) twitter text gem at some point?

I agree. Work has already started on replacing `twitter-text` (though it is not a priority right now and might still take a long time). It would be fabulous if after this work is finished, there would still be a spec around that makes sure URLs with an `@` at the end still work.

Maybe it could be added to `spec/lib/text_formatter_spec.rb`.

**Comment by ClearlyClaire** [comment]
> I researched this problem a little and this seems to be a known deficiency of […] (at least at some point) with twitter itself

This is still Twitter's behavior to this day.

> And the fact that their idea of how an URL should end falls too short was the original reason to patch this here. So I think the fix is correct.

Yeah, there is precedent for widening set of characters allowed to be the last character of an URL, and I can't currently think of a reason to not allow `@`.

> Maybe it could be added to `spec/lib/text_formatter_spec.rb`.

Yes, this is where we have our other link-detection tests, so I think this test should be moved there for consistency.

**Comment by adamniedzielski** [comment]
@ClearlyClaire I moved the tests 💅

**Review by oneiros — APPROVED** [review]

**Pull request merged**
