### PR TITLE
Fix broken dependencies in helm chart and allow using existing secrets in the chart

### LINKED ISSUE #18139: Use an existing Secret in Helm Chart
### Pitch

The Helm Chart's values.yaml should accept an `existingSecret` value for any secret value., and based on that value, either template the `Secrets` as necessary or refer to the provided `existingSecret` for the value. For example, refer to many of Bitnami's charts but specifically https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha. 

### Motivation

This change would allow an entire Mastodon configuration to be stored in Git. An Instance's entire `custom-values.yaml` would be safe to share publicly as the sensitive info will be stored within the target cluster. This is in-line with modern DevOps practice and just feels good as a proponent of Infrastructure-as-Code. 

Further, anyone reading the `custom-values.yaml` or even the base `values.yaml` will know that `Secrets` must/can be configured in advance rather than at deployment (the alternative is having a `custom-values.yaml` and a separate `secrets.yaml` that is not stored in the repo, which is not very clear).

This is the one thing that is holding me back from deploying my own instance, and I'm willing to submit a PR adding this functionality if the maintainers are open to it!

### PR DESCRIPTION
**Pull request by deepy**
This PR builds on top of the work from @tedtramonte in https://github.com/mastodon/mastodon/pull/18179 and updates the chart dependencies to the lowest version still available.
The chart in mastodon/mastodon on main currently does not work as it depends on chart versions that no longer exist, this fixes that while also adding the ability to put the SMTP password into a secret.

Additionally this closes https://github.com/mastodon/mastodon/issues/18139

### CODE REVIEW

**Comment by deepy** [comment]
This has been tested with an external database

**Comment by deepy** [comment]
Updated to postgresql 11 and tested fine with inline secrets in values.yaml

**Comment by deepy** [comment]
and now SMTP password can also be put in a secret.

**Comment by deepy** [comment]
@dunn given your involvement in the issue, would you be able to have a look at this PR?

**Comment by dunn** [comment]
@deepy oh, thanks for this! looks great, and keeping chart versions relatively up-to-date is a good idea, but i think we should also switch to using the full chart repo https://github.com/mastodon/mastodon/pull/18946 so that things don't break unexpectedly if versions fall slightly out of date

**Review by dunn — APPROVED** [review]

**Comment by deepy** [comment]
@dunn thanks for having a look at this! :-)
I agree on the full-archive for charts, but your PR is missing the update to the lock-file so I added the change here as well

**Comment by dunn** [comment]
@deepy oh right! thanks for picking that up

**Review by Gargron — APPROVED** [review]

**Pull request merged**
