### PR TITLE
Fix minor jslint issue

### PR DESCRIPTION
**Pull request by yookoala**
* Undefined propType in react component `ColumnSettings`.
  Add proper PropTypes definition.

### CODE REVIEW

**Comment by yookoala** [comment]
I don't think this is a relevant duplication
[](https://codeclimate.com/github/tootsuite/mastodon/pull/1697)

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
I don't pay *too* much attention to CodeClimate. I know it has a lot of false positives.

**Review by Gargron — APPROVED** [review]

**Comment by rtucker** [comment]
this seems to cause breakage... grey screen on page load, error on dev console:

Uncaught TypeError: Cannot read property 'isRequired' of undefined
on: intl: _reactImmutableProptypes2.default.object.isRequired,

Removing the intl: line causes everything to work again.

**Comment by rtucker** [comment]
pr #1706 fixes the aforementioned error in my test environment

**Pull request merged**
