### PR TITLE
[Dependashlee] Update to Puma 6.1.0

### PR DESCRIPTION
**Pull request by shleeable**
Note: puma supports websockets now.

https://github.com/puma/puma/releases/tag/v6.0.0
https://github.com/puma/puma/releases/tag/v6.0.1
https://github.com/puma/puma/releases/tag/v6.0.2
https://github.com/puma/puma/releases/tag/v6.1.0

## 5.0 to 6.0 Migration notes

Check the following list to see if you're depending on any of these behaviors:

*    Configuration constants like DefaultRackup removed, see [#2928](https://github.com/puma/puma/pull/2928/files#diff-2dc4e3e83be7fd97cebc482ae07d6a8216944003de82458783fb00b5ae9524c8) for the full list.

*    We've removed the following public methods on Puma::Server: Puma::Server#min_threads, Puma::Server#max_threads. Instead, you can pass in configuration as an option to Puma::Server#new. This might make certain gems break (capybara for example).

*    We have changed the names of the following environment variables: DISABLE_SSL is now PUMA_DISABLE_SSL, MAKE_WARNINGS_INTO_ERRORS is now PUMA_MAKE_WARNINGS_INTO_ERRORS, and WAIT_FOR_LESS_BUSY_WORKERS is now PUMA_WAIT_FOR_LESS_BUSY_WORKERS.

*    Nakayoshi GC (nakayoshi_fork option in config) has been removed without replacement.

*    wait_for_less_busy_worker is now on by default. If you don't want to use this feature, you must add wait_for_less_busy_worker false in your config.

*    We've removed the following constants: Puma::StateFile::FIELDS, Puma::CLI::KEYS_NOT_TO_PERSIST_IN_STATE and Puma::Launcher::KEYS_NOT_TO_PERSIST_IN_STATE, and Puma::ControlCLI::COMMANDS.

*    We no longer support Ruby 2.2, 2.3, or JRuby on Java 1.7 or below.

*    The behavior of remote_addr has changed. When using the set_remote_address header: "header_name" functionality, if the header is not passed, REMOTE_ADDR is now set to the physical peeraddr instead of always being set to 127.0.0.1. When an error occurs preventing the physical peeraddr from being fetched, REMOTE_ADDR is now set to the unspecified source address ('0.0.0.0') instead of to '127.0.0.1'

*    Previously, Puma supported anything as an HTTP method and passed it to the app. We now only accept the 8 HTTP methods defined in RFC 9110.

### CODE REVIEW

**Comment by shleeable** [comment]
@Gargron @ClearlyClaire I'm going to continue to test this, but I don't think any of the breaking changes affect Mastodon.

**Comment by shleeable** [comment]
#Before 
```
=> Booting Puma
=> Rails 6.1.7.2 application starting in production
=> Run `bin/rails server --help` for more startup options
[7] Puma starting in cluster mode...
[7] * Puma version: 6.1.0 (ruby 3.0.5-p211) ("The Way Up")
[7] *  Min threads: 10
[7] *  Max threads: 10
[7] *  Environment: production
[7] *   Master PID: 7
[7] *      Workers: 6
[7] *     Restarts: (✔) hot (✖) phased
[7] * Preloading application
[7] * Listening on http://0.0.0.0:3000
[7] Use Ctrl-C to stop
[7] - Worker 0 (PID: 11) booted in 0.04s, phase: 0
[7] - Worker 1 (PID: 29) booted in 0.04s, phase: 0
[7] - Worker 2 (PID: 47) booted in 0.03s, phase: 0
[7] - Worker 3 (PID: 54) booted in 0.02s, phase: 0
[7] - Worker 4 (PID: 83) booted in 0.01s, phase: 0
[7] - Worker 5 (PID: 101) booted in 0.0s, phase: 0
X-Accel-Mapping header missing
X-Accel-Mapping header missing
```

# After
```

=> Booting Puma
=> Rails 6.1.7.2 application starting in production
=> Run `bin/rails server --help` for more startup options
[7] Puma starting in cluster mode...
[7] * Puma version: 5.6.5 (ruby 3.0.5-p211) ("Birdie's Version")
[7] *  Min threads: 10
[7] *  Max threads: 10
[7] *  Environment: production
[7] *   Master PID: 7
[7] *      Workers: 6
[7] *     Restarts: (✔) hot (✖) phased
[7] * Preloading application
[7] * Listening on http://0.0.0.0:3000
[7] Use Ctrl-C to stop
[7] - Worker 0 (PID: 11) booted in 0.05s, phase: 0
[7] - Worker 1 (PID: 24) booted in 0.04s, phase: 0
[7] - Worker 2 (PID: 47) booted in 0.03s, phase: 0
[7] - Worker 3 (PID: 60) booted in 0.02s, phase: 0
[7] - Worker 4 (PID: 83) booted in 0.01s, phase: 0
[7] - Worker 5 (PID: 96) booted in 0.0s, phase: 0
```

**Comment by xrobau** [comment]
FYI, This PR has been running fine on dev.mastodon.au for a few days with zero issues that I've noticed, and no unexpected errors in syslog.

**Comment by vmstan** [comment]
Testing on half of vmst.io now.

CleanShot 2023-02-24 at 08 12 13@2x

**Comment by shleeable** [comment]
I'll leave this to the devs.. but this looks good

**Comment by vmstan** [comment]
Rolled all of vmst.io up and no issues.

**Review by xrobau — APPROVED** [review]
Confirm approve

**Review by ClearlyClaire — APPROVED** [review]
I have verified the `MIN_THREADS` and `MAX_THREADS` settings work as expected. In addition, I have verified we don't use the `capybara` gem in a way that breaks.

LGTM

**Pull request merged**
