### PR TITLE
Add ability to disable login and mark accounts as memorial

### LINKED ISSUE #5597: Idea: Memorial Pages
I've been thinking (some of you will know why) recently about the idea of a toggle for mods that can switch an account into a sort of "memorial mode" to honor folks who have died. The simplest version would be one that just disallowed logging in as that person.

More complicated versions might put something like "in memoriam" on their profile, allow certain posts to be tagged for featuring (think, like, pinning a few different posts that exemplified the best of the person being memorialized), change the layout of the profile in some way, note their birth and/or death date, set up an `X-Clacks-Overhead` header with their name, or link to any sort of official announcement or donate-in-the-name-of sort of thing.

What do others think about this idea?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #5597

image
image
image

### CODE REVIEW

**Review by beatrix-bitrot — APPROVED** [review]
lgtm

**Comment by DarckCrystale** [comment]
Thank you a lot fot this great feature @Gargron :candle:

**Comment by itskiru** [comment]
Thanks you !

**Comment by Aldarone** [comment]
On a scale of 0 to F how risky is it to cherry pick?

**Pull request merged**
