### PR TITLE
Add af, gd and si locales

### PR DESCRIPTION
**Pull request by gunchleoc**
Add Afrikaans, Scottish Gaelic & Sinhala.

I did this by running `grep zh-HK * -r` to find the locations to edit. I hope I haven't missed anything.

I sourced the Sinhala native language name from the [CLDR](https://unicode-org.github.io/cldr-staging/charts/latest/summary/si.html#6b773b0f539e5dc6).

Please add the locales to Crowdin too (c.f. https://crowdin.com/project/mastodon/discussions/22)

Re https://github.com/tootsuite/mastodon/issues/15826
Re https://github.com/tootsuite/mastodon/issues/15799

### CODE REVIEW

**Comment by ariasuni** [comment]
I added Scottish Gaelic on Crowdin. I’m not sure if it’s necessary to add locales here or if it should only be done on Crowdin’s side?

**Comment by gunchleoc** [comment]
I expect we'll need them here in the code too, for the language selection menu in the settings.

The pipeline is failing though, because we'll need to pull the translated files from Crowdin first.

**Comment by Gargron** [comment]
Correct, files need to exist first, otherwise it will let people select the language and then have the UI crash because of missing files.

**Comment by Gargron** [comment]
Hi, please rebase on main

**Comment by Gargron** [comment]
Or never mind, I will rebase it myself

**Comment by gunchleoc** [comment]
Thanks!

**Pull request closed without merging**
