### PR TITLE
Add polyfill for Object.hasOwn

### LINKED ISSUE #27227: Notifications do not update in real time for old versions of Safari since update to ver 4.2.0
### Steps to reproduce the problem

1. Before ver 4.2.0 notifications and mentions automatically refreshed in Safari.
2. I would see the count of notifications I'd not checked.
3. When I clicked on Notifications tab/link I would see the new notifications.4. 
...
Now none of this happens unless I manually refresh the page.

Note: Posts/Home timeline continues to automatically refresh (only Notifications is affected.)

### Expected behaviour

Notifications automatically pushed to Safari

### Actual behaviour

I have to manually click the reload icon to see notifications.

### Detailed description

1. Before ver 4.2.0 notifications and mentions automatically refreshed in Safari.
2. I would see the count of notifications I'd not checked next to the Notifications link.
3. When I clicked on Notifications tab/link I would see the new notifications.
...
Now none of this happens unless I manually click the reload icon to refresh the page. 
Home and Live Feeds update automatically, just not Notifications.

### Mastodon instance

techhub.social

### Mastodon version

v 4.2.0

### Browser name and version

Safari Version 14.1.2 (14611.3.10.1.7)

### Operating system

macOS 10.14.6

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This would fix #27227 (at least for some of the users), but I am not sure this is worth adding, as the affected browsers aren't supported anymore.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by renchap** [comment]
I think this breaks due to our `.browserslistrc` file. It is configured to support those browsers: https://browserslist.dev/?q=ZGVmYXVsdHMsIG5vdCBJRSAxMSwgbm90IGRlYWQ%3D which does not include Safari 14.

In theory, there may be other things broken on Safari 14, if it does not support some modern JS features that the browsers in the list above support.

**Comment by ClearlyClaire** [comment]
We do explicitly use `hasOwn` in our source code, so I don't think this is an issue with our `.browserslistrc` file, unless I'm missing something. But that's also a good point.

In any case, I'm not sure what the best thing to do is, merging this would be a quick fix, but as you say, it doesn't guarantee another issue won't pop up, and those old browsers are unsupported by their vendors, too.

**Comment by renchap** [comment]
> We do explicitly use `hasOwn` in our source code, so I don't think this is an issue with our `.browserslistrc` file, unless I'm missing something. But that's also a good point.

Babel should replace `hasOwn` from our source code with the corejs polyfill automatically if it is not supported natively by the browsers we declare, this is what `babel-preset-env` does (or should do).

… after 15 minutes of testing …

Our current Babel config does not configure `useBuiltIns`, so standard library polyfills are not injected where they are used in the code.

After configuring it correctly, I confirm that in a file with `hasOwn`, Babel automatically adds `import "core-js/modules/es.object.has-own.js";` at the start of the file when transpiling it.

I will open a PR with this change.

I would prefer that we customise our supported browser list and have Babel automatically insert the needed polyfills, rather than manually importing them (which can result in unneeded polyfills, or some features not being polyfilled where they should be)

**Comment by renchap** [comment]
Babel changes are in https://github.com/mastodon/mastodon/pull/27333

**Comment by renchap** [comment]
This should be solved by #27333, Babel will now properly inject polyfills for `hasOwn` if there are browsers in our BrowserList config that do not support it.

**Pull request closed without merging**
