### PR TITLE
Added the law requirements for the EU/EEA

### PR DESCRIPTION
**Pull request by ghost**
See article 8 of the GDPR

### CODE REVIEW

**Comment by nightpool** [comment]
do not use this site -> please ensure you have parental permission before using this site.

**Comment by nightpool** [comment]
also the builds are failing

**Comment by jeroenpraat** [comment]
"Run `i18n-tasks normalize` to fix"

Sorry I don't have a development environment setup.

**Comment by ykzts** [comment]
I ran `i18n-tasks normalize`.

**Comment by nightpool** [comment]
@jeroenpraat the mastodon instances do not need to administer parental permission

**Review by Gargron — APPROVED** [review]

**Pull request merged**
