### PR TITLE
fix #4356 : sw.js not found on Docker.

### LINKED ISSUE #4356: The file sw.js is not found
I upgraded Mastodon to `v1.5.0rc1` (tagged release), but `sw.js` is not found.

https://mastodon.noraworld.jp/sw.js

I found `sw.js` on other instances, which version is `v1.5.0rc1`. I heard this is a specific problem with a deployment on Docker, which means it does not occur on non-Docker deployment. My instance is deployed with Docker.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by ikuradon**
Another solution from #4357 for #4356 .

### CODE REVIEW

**Comment by Gargron** [comment]
@sorin-davidoi Will this work?

**Comment by sorin-davidoi** [comment]
Not sure, will have to test when I get home.

**Comment by sorin-davidoi** [comment]
This serves `sw.js` from the `assets` directory. It needs to be served from root.

**Comment by ikuradon** [comment]
sw.js is need to serve from root path, but current Docker configuration Can't persist /public/ folder.
So, I wrote simple controller that only load /assets/sw.js and serve with /sw.js path.
How do you think?

**Comment by Gargron** [comment]
Closed in favour of  #4358

**Pull request closed without merging**
