### PR TITLE
Update rails to version 7.1.4

### PR DESCRIPTION
**Pull request by mjankowski**
Related...

- Deprecation output to be solved by - https://github.com/mastodon/mastodon/pull/31562
- UJS lib should be merged with this - https://github.com/mastodon/mastodon/pull/31556

### CODE REVIEW

**Comment by mjankowski** [comment]
I think the bundler audit issue here - https://github.com/rails/rails/security/advisories/GHSA-fwhr-88qx-h9g7 - is a false positive and will be fixed in the advisory db.

**Comment by mjankowski** [comment]
Advisory DB was updated, after rebase this is passing now. We should process the linked config/secrets PR first, before merge this.

**Comment by mjankowski** [comment]
With 7.1.4 rails-ujs merged, we should bring this one in as well (along with https://github.com/mastodon/mastodon/pull/31562 )

**Comment by mjankowski** [comment]
This one - https://github.com/mastodon/mastodon/pull/31562 - is now approved but not merged yet.

Will rebase this after merge, I think it's the only blocker.

**Comment by mjankowski** [comment]
Rebased after secrets removal merged, this passes fine w/out any deprecation warning now.

**Comment by mjankowski** [comment]
Added removal of configuration work-around we had in place that is resolved in 7.1.4

**Review by oneiros — APPROVED** [review]

**Pull request merged**
