### PR TITLE
Reword the direct message warning

### LINKED ISSUE #7030: Reword direct message warning to set proper privacy expectations
The DM warning is misleading, saying that “This toot will only be visible to all the mentioned users.”.

Currently, any moderator plus anyone with read access to the database can read those toots.

The warning should be updated to reflect that.

### PR DESCRIPTION
**Pull request by Sylvhem**
- Reword the direct message warning to set proper privacy expectations (fix #7030).
- Update the French translation accordingly.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by trwnh** [comment]
>Facebook and Twitter do not warn their users like this and it's an unfair advantage for them.

I'd rather we err on the side of transparency. FB and Twitter choose not to warn users because they don't care about privacy, and are willing to read private messages when wanted or requested.

**Comment by Sylvhem** [comment]
> We talked about this before when the previous warning text came up, but yeah "will only be sent to all" doesn't sound correct.

Maybe "This toot will only be sent to the mentioned users." would be better?

**Comment by Gargron** [comment]
Please use:

>This toot will only be sent to the mentioned users. However, the admin of yours and the receiving instance may ___ this message.

- see?
- view?
- inspect?

Not sure which is best. It needs to be indicated that it would take targeted action by the admin, rather than "all DMs wheezing by on the admin's screen"

**Comment by trwnh** [comment]
"...However, instance admins may view this message if it is reported."

AFAIK, admins can only see a direct message if it's 1) reported, or 2) if they look through the database manually, correct? And there's another open issue for 3) clicking a button to temporarily view direct messages while investigating a report, right? The above language should cover case 1 and maybe case 3, though IDK what language to use to cover case 2.

**Comment by Gargron** [comment]
What if instead of "may", it's just "able to"?

**Comment by Sylvhem** [comment]
> However, the admin of yours and the receiving instance may ___ this message.

I choose to use "operator" instead of "admin" because we seemed to agreed in [this discussion](https://github.com/tootsuite/mastodon/issues/7030), that it should be highlighted that not only the admins but also the moderators and the sysadmins could access to people DM. Since "operator" is the term used on [the new privacy policy](https://github.com/tootsuite/mastodon/pull/6666), I think we should reused it here.

> Not sure which is best. It needs to be indicated that it would take targeted action by the admin, rather than "all DMs wheezing by on the admin's screen"

Inspect is probably the best choice then.

New proposal: "This toot will only be sent to the mentioned users. However, the operators of yours and any of the receiving instances may inspect this message.".

> The above language should cover case 1 and maybe case 3, though IDK what language to use to cover case 2.

The wording I suggest actually covers all three cases.

**Comment by Gargron** [comment]
>New proposal: "This toot will only be sent to the mentioned users. However, the operators of yours and any of the receiving instances may inspect this message.".

:+1:

**Review by Gargron — APPROVED** [review]

**Review by ThisIsMissEm — COMMENTED** [review]
I honestly think this message creates undue amounts of FUD; perhaps: “this message is not encrypted & is stored in plaintext.”

Only server admins with database access can see DMs unless they’re reported.

Also, I know I’m late to comment, have been away with medical issues, still not back to 100%

**Comment by ThisIsMissEm** [comment]
You could use symmetric-encryption, a ruby gem to do exactly that. I also apply this gem to email addresses and oauth tokens, such that if the database is accessed by someone unauthorized, then it limits exposure.

This database level security doesn’t prevent anyone from using the rails console with production details in order to read it, so, it’s really protecting against accidental exposure.

Perhaps: “This toot is stored just the same as all other toots, however, it is only shown to mentioned recipients. Administrators may still access it – do you trust them?”

If you’re tooting a DM to a foreign server, similar to the “do you trust this foreign server?” Message.

**Comment by Gargron** [comment]
>I also apply this gem to email addresses and oauth tokens,

But then you can't query by those values quickly? And you kinda have to. Be careful re: performance

**Comment by ThisIsMissEm** [comment]
You can, you just encrypt the value, then search the database; it’s not using unique encryption keys per row, just per environment.

True, you couldn’t do partial matches anymore. Not sure how much of a problem this would be. I know we’ve occasionally used partial matches to find duplicate accounts, but usernames or display names tend to be more common.

**Pull request merged**
