### PR TITLE
Change fetch link card service to parse as HTML5

### PR DESCRIPTION
**Pull request by flavorjones**
__Context__

This PR is one in a series that aims to update Mastodon to parse all HTML content as HTML5. See https://github.com/mastodon/mastodon/pull/31812 for a longer explanation.

__Changes__

See related issues #30780 and #30929 which were working around Nokogiri's HTML4-specific behavior.

Passing a `nil` as the encoding to Nokogiri's HTML5 parser will attempt to find a matching encoding, and fall back to UTF-8, making the additional logic added in #30780 unnecessary.

In the case of encoding conversion failure, Nokogiri's HTML5 parser will replace the invalid bytes with the "�" (U+FFFD) codepoint and the resulting string is _always_ valid UTF-8 making the "bail out" behavior from #30929 unnecessary.

Also note that I've sped up encoding detection by operating directly on the strings (and not round-tripping through Nokogiri).

### CODE REVIEW

**Review by Gargron — DISMISSED** [review]

**Comment by flavorjones** [comment]
@oneiros Since you were involved in the two PRs I linked, I'd love your feedback on this change. ♥

**Comment by flavorjones** [comment]
I've force-pushed a change that removes the unnecessary rescue of `Encoding::UndefinedConversionError` in `LinkDetailsExtractoro#detect_encoding_and_parse_document`.

**Comment by oneiros** [comment]
Hey @flavorjones! Thank you so much for your contribution, it is much appreciated.

I am totally fine with these changes, but since you asked I will try to give a longer answer:

I believe you slightly misunderstood the purpose of the changes in #30780. When trying to parse arbitrary websites we are often faced with incorrect encoding (or better: incorrectly reported encoding).

So we usually cannot trust encoding that a website says it is in and we opted to use the `charlock_holmes` gem to try to detect what the actual encoding is. If `charlock_holmes` reports something with a fairly high confidence, we can rely on that being correct. But if its confidence is low, the result is not really usable.

In these cases we did not want to just give up, so we wanted to at least try to see if the reported encoding might work. There are two ways a website can report its encoding: It can have a `<meta>` tag saying what the encoding is and the webserver will usually give an encoding in the http headers.

We figured the one in the HTML is probably more trustworthy (because it is closer to the actual content) so we wanted to prioritize this. But we also encountered cases where the HTML was wrong, but the http headers were in fact right. So we went with: Try `charlock_holmes` first, then let nokogiri parse the page (which includes looking for the `<meta>` tag) and try the encoding from the http headers last.

If I understand you correctly, this would no longer work with `Nokogiri::HTML5`.

It might also be worth noting that we had decided to not display link previews with  "�" or any other replacement characters. There are other edge cases where we do not generate link previews, so there is no general expectation that they will always be displayed.

All that being said, I am all for your changes. I guess the security considerations trump the reasoning laid out above (and after all, you are the expert on this here :slightly_smiling_face:). It is simpler and might be faster. And last but not least, @Gargron already approved it :wink:

**Review by oneiros — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me overall. It *does* change the behavior by actually creating a preview card when encountering an encoding error, which might be unexpected… I'm not sure what the correct behavior *should* be though.

~~Also would like @oneiros to have a look on this.~~ EDIT: oops concurrent reviews

**Pull request merged**
