### PR TITLE
 Put the CW field between the toot we are replying to and the toot field

### PR DESCRIPTION
**Pull request by ariasuni**
As explained in #1326, users may be confused by or forget about the CW field automatically field with the CW of the toot they are replying to; notably, the CW field may be very far away or no longer be visible when the toot is long.

The solution I propose is to put the CW field just above the toot being composed itself, so it’s always clear that there’s a CW (or not). It’s also more logical to put the CW nearer the toot than the toot being replied to.

Screenshots before/after:

screenshot_2018-05-16 mastodon devscreenshot_2018-05-16 mastodon dev after

### CODE REVIEW

**Review by ClearlyClaire — COMMENTED** [review]
Why remove the Collapsable component/animation?

**Comment by Gargron** [comment]
Spacing looks wrong.

**Review by ClearlyClaire — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Gargron** [comment]
Yes, I do think the spacing needs change.

**Comment by Gargron** [comment]
I also haven't seen how the animation looks now. I'm not so sure: spring-based animation is generally more interesting to look at than CSS transitions. I do not agree with the arguments about style in the markup, we use Motion throughout the application so it's more consistent for us to have that than CSS transitions.

**Comment by ariasuni** [comment]
The problem I had with height of the element in the markup is that I couldn’t modify the size of the spacing under the CW easily with my custom CSS extension (I assume it’s the same for themes).

**Comment by ariasuni** [comment]
Here’s how it looks now:

screenshot_2018-05-31 mastodon dev

**Comment by ariasuni** [comment]
I also kept the CSS animation, since I didn’t notice any difference visible difference with the Spring one, and for the easier theming of margins.

**Pull request merged**
