### PR TITLE
Add boost visibility icon

### PR DESCRIPTION
**Pull request by noellabo**
Shows the boost visibility icon.

boost-visibility-icon

Note that the notification does not include boost visibility information, so the icon is not displayed at this time.

If someone "private boosts" your post, you may not be able to find the boost post even though you received the boosted notification if you are not following that user. It might be a hint if you can know the visibility of boost even in the notification.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Seems fine to me, although slightly worried this would make the interface feel a bit too noisy for a rather limited value.

**Comment by noellabo** [comment]
I think we can reduce the visual annoyance by hiding the public visibility globe, what do you think?

**Comment by noellabo** [comment]
Changed the class of boost visibility icon to `status__prepend-visibility-icon` and added `status__prepend-${visibility}` to `status__prepend`.

This makes it easy to customize, such as hiding only the added icons or certain of them.

Hide globe
```
.status__prepend-visibility-icon.fa-globe {
    display: none;
}
```

Hide boost visibility icons
```
.status__prepend-visibility-icon {
    display: none;
}
```

**Comment by mayaeh** [comment]
How about adding such a setting item so that the display can be switched?



I think it's a little noisy too.
However, I think that this visualization may be needed as the ActivityPub implementation extends.

**Comment by Gargron** [comment]
> Seems fine to me, although slightly worried this would make the interface feel a bit too noisy for a rather limited value.

I agree with this, I think this is too much information and not that important.

**Comment by noellabo** [comment]
Implemented the idea of a toggle switch.

'Boost visibility' is important for 'private' and 'limited'. If the boosts you see on your timeline are open to a limited audience, you should often consider posts related to them to match your boost visibility. In this case,'boost visibility icon' is very helpful. Therefore, displaying the'public'and'unlisted' icons does not make much sense. It's shown here for consistency, but you might want to omit it.

**Comment by Ahtie** [comment]
If it becomes possible to specify Boost visibility in the main of tootsuite/mastodon's Web UI in the future, I can partially agree with this icon(s).
However, "I" like the simple WebUI, so I hope I can opt-out. As mayaeh says.

**Comment by Delta-Time** [comment]
If it becomes possible to specify Boost visibility in the tootsuite/mastodon  Web UI in the future, I can partially agree with this proposal.
However, I prefer the simple WebUI, so I hope I can opt-out. As mayaeh says.

**Comment by noellabo** [comment]
If you want to turn off the server defaults, set `reblog_visibility: false` in advance.
https://github.com/tootsuite/mastodon/blob/e3644dba400dca4647d8d4230e1f0ae46983f1cd/app/javascript/mastodon/reducers/settings.js#L23

**Comment by Delta-Time** [comment]
It's nice that you can change it by changing the source code.

I think boost visibility is "better" as an option.
I want you to keep it simple in the WebUI without changing the source code.
 
I'm sorry I just commented because I don't have the technical ability to commit.

**Comment by ClearlyClaire** [comment]
My issue with the Home column toggle switch is that information shows up in a lot of other places than the Home timeline.

> If it becomes possible to specify Boost visibility in the tootsuite/mastodon Web UI in the future, I can partially agree with this proposal.

It's possible since #15704

**Comment by Delta-Time** [comment]
> It's possible since #15704

That's nice!
Thank you for reference.

**Comment by noellabo** [comment]
Moved display settings from home header to appearance.

I think this is a better position as it is not something that users change often. This also enables the settings for public pages.

We also made a change to hide the public globe icon.

Regarding the visibility of status, I adopted the opinion that the globe should also be displayed for consistency, but what about this? I think you can make it look cleaner without sacrificing functionality.

**Comment by weex** [comment]
I tried searching but couldn't find any issues related to this PR. Is there more description of the problem somewhere beyond the bottom of the initial comment?

**Comment by ClearlyClaire** [comment]
> I tried searching but couldn't find any issues related to this PR. Is there more description of the problem somewhere beyond the bottom of the initial comment?

Boosts can have different visibility: like toots they can be visible to followers only or to anyone. Currently, unlike toots, the visibility setting of boosts is not displayed anywhere. This PR aims to change that.

**Pull request closed without merging**
