### PR TITLE
Support animated PNGs in media attachments

### PR DESCRIPTION
**Pull request by c960657**
Handle animated PNGs like animated GIFs in media attachments.

`Fastimage.animated?` now supports PNG (as https://github.com/sdsykes/fastimage/pull/144).

The transparent pixels in GIFs are currently filled with white. To achieve the same for PNG transparency, the ffmpeg overlays the stream on a white background. For blurhash generation, the image needs to be flattened and compression should be disabled to prevent transparent pixels from being cropped (this would otherwise make blurhash generation crash – the crash is fixed in the not-yet-released PR https://github.com/Gargron/blurhash/pull/26).

`Fastimage.animated?` already works for GIF, so there is no need to use our own implementation. `Fastimage.animated?` is slightly slower due to an unnecessary call to `File.size?`, but the impact is minimal. Performance will be improved with upcoming PR https://github.com/sdsykes/fastimage/pull/143.

### CODE REVIEW

**Comment by vmstan** [comment]
So it appears like this would also fix the issue of a static GIF image always being processed according to the media limits as if it was an animated GIF?

**Comment by vmstan** [comment]
Closes #26351

**Comment by c960657** [comment]
> So it appears like this would also fix the issue of a static GIF image always being processed according to the media limits as if it was an animated GIF?

I am not sure which issue you are referring to? This PR is not supposed to change how static GIFs are handled.

**Comment by vmstan** [comment]
Currently any GIF file that gets uploaded gets treated the same regardless of it it's a static of animated. My read of your changes, as part of separating the processing of PNG files, seems like it's also separating the processing of GIF files into the same flow. (Instead of intercepting all image/gif file types, using FastImage to determine if it's animated?)

**Comment by vmstan** [comment]
Similarly, there is a GIF matrix limit of `GIF_MATRIX_LIMIT = 921_600` (1280x720) in `app/models/concerns/attachmentable.rb` to limit GIF size uploads. Would animated PNG uploads subject to the same limitations?

**Comment by c960657** [comment]
@ClearlyClaire I am not sure, what you are suggesting. Do you think we should convert them to a different animated image format (e.g. animated PNG) or to a static image?

As an end-user, I would expect animation to be preserved for PNGs as well as for GIFs, but I don't care about the output file format.

**Comment by ClearlyClaire** [comment]
I'm suggesting the animations are kept as animated PNGs. I thought they were for avatars, but that may only be true for GIF uploads?

**Comment by c960657** [comment]
> I'm suggesting the animations are kept as animated PNGs.

I don't know the history behind why we currently convert GIFs to mp4 instead of animated PNG, and I don't know whether PNG or mp4 is better for animated images.

If PNG is better, I think we should use that for animated GIFs also (for consistency, and to avoid having to support both `<video>` and ``). Do you agree?


> I thought they were for avatars, but that may only be true for GIF uploads?

Only GIF. kt-paperclip doesn't support animated PNGs: https://github.com/kreeti/kt-paperclip/pull/123

**Comment by ClearlyClaire** [comment]
A quick look at the PR looks ok, but I'll still need to do a more involved review, as media transcoding in Mastodon can be pretty messy :/

> Closes #26351

I don't think so, this issue is primarily about avatar headers, this PR is about media attachments.

> I don't know the history behind why we currently convert GIFs to mp4 instead of animated PNG, and I don't know whether PNG or mp4 is better for animated images.

I'd say the main benefits of APNG over MP4 are transparency and its lossless nature, which I guess GIF provides too but with a lot more limitations and larger file size. I suppose WebP could also be a worthwhile alternative, though I guess we may have trouble with the tooling… not sure how ffmpeg and ImageMagick handle those.

> If PNG is better, I think we should use that for animated GIFs also (for consistency, and to avoid having to support both `<video>` and ``). Do you agree?

We may still want to support audio-less videos the way we currently do, especially for longer-form media files where a lossless format is not reasonable.

> > I thought they were for avatars, but that may only be true for GIF uploads?
> 
> Only GIF. kt-paperclip doesn't support animated PNGs: [kreeti/kt-paperclip#123](https://github.com/kreeti/kt-paperclip/pull/123)

Ah, thanks for pointing that out!

**Comment by vmstan** [comment]
> > Closes #26351
> 
> I don't think so, this issue is primarily about avatar headers, this PR is about media attachments.

You're right.

**Comment by fabiscafe** [comment]
From a users POV: How is animated PNG(aPNG) in case of
1. file size
2. hardware acceleration/Power consumption
3. support
4. Licensing

compared to video formats and or other picture formats that can be animated and come with with alpha channel feature set?

Because at the end of the day aPNG is not a widely supported format, and so there might be toolkits that hardly can display them (ehem.. GTK) and I would prefer something that first of all is small in size, fast to download and doesn't hit my phones/laptops battery in any way..

**Comment by c960657** [comment]
> Because at the end of the day aPNG is not a widely supported format, and so there might be toolkits that hardly can display them (ehem.. GTK) and I would prefer something that first of all is small in size, fast to download and doesn't hit my phones/laptops battery in any way..

With this PR, aPNGs are converted to an MP4 video and a static thumbnail on the server, just like animated GIFs. The client does not receive the source aPNG file.

**Comment by ClearlyClaire** [comment]
I'm reminded of this PR in the context of #32096. We should treat WebP files as potentially animated as well.

**Comment by c960657** [comment]
I agree. Unfortunately ffmpeg does not support animated WebP, so implementing this requires more than just adding _image/webp_ to `IMAGE_ANIMATED_MIME_TYPES`.

https://trac.ffmpeg.org/ticket/4907

**Comment by mjankowski** [comment]
It's not 100% clear to me from re-reading the history here ... is this one blocked on product decision? Ready for code review? Still sorting out support/direction? Ready to go? Something else?

**Comment by vmstan** [comment]
I don't see why we shouldn't implement.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
