### PR TITLE
Retoot count increases without reason

### LINKED ISSUE #4916: Retoot count increases without reason
I recently made a toot with one account, and retooted it from another, and was surprised to find it indicated 2 retoots already.  I checked, but mine was the only retoot.  A few hours later, that same post has 3 retoots, but still only shows one when the details are checked.

Here's the post in question:
https://nfg.zone/web/statuses/203818

Running 1.6.0

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by cacheflow**
-The store_uri method for Statuses was being called on after_create and causing reblogs to be incremented twice.
-This calls it when the transaction is finished by using after_create_commit.
-Fixes #4916.

### CODE REVIEW

**Comment by brah** [comment]
wow thanks! @cacheflow great work bud!

**Comment by brah** [comment]
looking small!

**Comment by brah** [comment]
stay small @cacheflow !

**Review by krainboltgreene — APPROVED** [review]

**Comment by krainboltgreene** [comment]
Great catch.

**Comment by brah** [comment]
please reverse this. this exposes a very bad bug which my machine crash.

I'm using windows 95, v1.9.47 on a chrome browser to reproduce

**Pull request merged**
