### PR TITLE
Minimize re-displaying boosted posts that have already been seen

### PR DESCRIPTION
**Pull request by mfenniak**
The "Group boosts in timelines" functionality reviews the last 40 posts on a user's timeline and prevents them from re-displaying when a new post comes in.  This is a great feature, but there is still user feedback that the behavior still displays a lot of the same posts repeatedly.  For example...

> As a user, I see a lot of boosts for posts I have already seen because I follow the account directly. (#19665)

> Some users get too boost happy, and your timeline fills up with content they're boosting (#19951)

> Currently what is happening is that I will read posts earlier in the day, they get boosted, and then they show up higher in my feed when I check back later in the day. (#20411)

> For many users with many followers this can be reached in minutes so that they still see the same reboost every few minutes. Some users even never want to see reboosts, so they should have the option of increasing this value. (#18693)

The change proposed in this PR is *not* a comprehensive or complete solution... but it simply changes the "last 40 posts" into "the last 400 posts" (ie. the timeline length stored in redis).  This change is simple and it generally improves the user-experience, even though it's not perfect.

## Technological Risks

I don't believe there are significant technological to the change... there are two places that this value is used:

Location A:
https://github.com/mastodon/mastodon/blob/75bbe3b1b80207d9cab1a73a9fc38324ee6340d5/app/lib/feed_manager.rb#L312-L316
In this location zrevrange is being used with the `falloff_rank` parameter as both the start & end param.  zrevrange is documented as being "O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements returned." -- as this change hasn't adjusted "the number of elements in the sorted set" (400) or the "number of elements returned" (1), it should have no performance change from current.

Location B:
https://github.com/mastodon/mastodon/blob/75bbe3b1b80207d9cab1a73a9fc38324ee6340d5/app/lib/feed_manager.rb#L445-L451
In this location the `REBLOG_FALLOFF` is being used as a const value compared against the `zrevrank` return value.  Performing a comparison with a different const value should have no performance/scalability impact.

## User Experience Risks

I don't have the experience with the codebase or Mastodon in general to have a good sense of the user experience risks.  Obviously the expected outcome is that you see less of the same repeated boosts.  For my individual user experience, I would prefer to never see a repeated boost, so this is a step towards improvement.  However I understand that my user experience is not the only one -- I'm very interested to hear other perspectives on this.

## Summary

Thanks all for considering this patch.  I think a more comprehensive solution like that proposed in https://github.com/mastodon/mastodon/issues/19665#issuecomment-1301759432 is a better long-term solution (albeit with a large scope of change and performance/scalability risk), but, my argument is that this is a better experience with a minimal change.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
The logic is sound, although I'm not too sure about the assessments you make regarding the performance implications: indeed, while the `zrevrange` call itself would have the same performance, it would affect the number of items trimmed from the set associated with `reblog_key`. The performance implications of that should not be too bad, but it exists.

But taking a step back, the whole thing with `reblog_key` and the `REBLOG_FALLOFF` is to deal with reblogs that are in the timeline but have been pushed further than `REBLOG_FALLOFF` from the top. If we take `REBLOG_FALLOFF` to be equal to `MAX_ITEMS`, there is at most a single relevant reblog in the timeline at a time, and we probably can simplify the code to stop maintaining an ordered set.

As for the user experience impact, I personally do not mind the repeated boosts… I'd be slightly afraid of missing often-boosted posts more easily, but I am not sure how important that concern is.

**Comment by nikodemus** [comment]
Any chance of making this configurable in the admin section in the UI?

Additionally, I think from UX perspective it would be ideal if this was configurable by time instead of count of posts since last boost: "1 h, 1 day, 1 week, 1 month". (I haven't looked at all if this is a reasonable thing to ask for in the data model!)

**Comment by mfenniak** [comment]
>  while the zrevrange call itself would have the same performance, it would affect the number of items trimmed from the set associated with reblog_key. The performance implications of that should not be too bad, but it exists.

I haven't tested it at scale, but I'm only working off the documentation that would indicate that isn't a factor... but what you're suggesting makes sense.  I'm running this patch on a small instance and my personal UX is better, but I don't have the scale to see the performance impact.

> [...] we probably can simplify the code to stop maintaining an ordered set.

@ClearlyClaire I'd be willing to work on a patch along these lines if you think that's the best way forward.

> Any chance of making this configurable in the admin section in the UI?

I suppose I would argue that the existing "Group boosts in timelines" option is already the configuration for this option.  It indicates that it causes the timeline to "not show new boosts for posts that have been recently boosted".  It just doesn't define "recent".

image

> Additionally, I think from UX perspective it would be ideal if this was configurable by time instead of count of posts since last boost: "1 h, 1 day, 1 week, 1 month". (I haven't looked at all if this is a reasonable thing to ask for in the data model!)

An approach like this will significantly change the data model required... and the big risk is that it becomes an unbounded data set to search.  If you follow 10,000 people, the number of posts that might need to be checked for re-posts in "1h", "1d", "1w", and "1mo" is 100x higher than if you follow 10 people.  That's either a higher DB load or an unbounded redis memory utilization, depending on the approach.  Maybe there's some other clever design, but intuitively it seems like it's unbounded work.

I thought this might make sense, but, I'm not sure if that's what people want.  Personally, I don't want to see repeated content ever... I already saw that, why see it again?  But, I have found since I applied this patch to my own instance that it can be surprising to later find out who and how comprehensively a post was boosted.  I tend to think that the real feedback people would want is not re-seeing the same repost, but rather to see other people's interest in that post.

**Comment by ClearlyClaire** [comment]
> I'd be willing to work on a patch along these lines if you think that's the best way forward.

I'm honestly not sure about the whole behavior change, but I think doing as I described is the best way to implement the behavior change you're proposing, yes.



> > Additionally, I think from UX perspective it would be ideal if this was configurable by time instead of count of posts since last boost: "1 h, 1 day, 1 week, 1 month". (I haven't looked at all if this is a reasonable thing to ask for in the data model!)
> 
> An approach like this will significantly change the data model required... and the big risk is that it becomes an unbounded data set to search. If you follow 10,000 people, the number of posts that might need to be checked for re-posts in "1h", "1d", "1w", and "1mo" is 100x higher than if you follow 10 people. That's either a higher DB load or an unbounded redis memory utilization, depending on the approach. Maybe there's some other clever design, but intuitively it seems like it's unbounded work.

Since the snowflake IDs encode the time the post was made at, I don't think this would require a redesign of the data model. With the caveat that if a full timeline (400 posts) separate from the last occurrence, then the boost would be accepted even if the last 400 posts were made in the last hour or so.

**Comment by untitaker** [comment]
Hey, I've been thinking about this problem as well and my conclusion at the time is that the way reblog falloff works at the moment is not working well enough:

* a person with busy Home feed is _less likely_ to benefit from boost deduplication, because duplicate boosts may be further apart and therefore is _more likely_ to see duplicates, which contribute further to the business of their feed. therefore, the number of boosts to keep in the set should not purely be trimmed by number of boosts, but rather by time. ideally there is a gurantee that any boost does not reappear for e.g. 15 minutes, not just that it does not reappear earlier than every 40th row.
* not all posts are equally viral and annoying, and there are rarely 40 duplicate boosts i see at any given day. it is rather 3 or 4 viral posts that i am tired of seeing -> those posts should be kept in the set of dropped boosts for much longer.

Proposal:

* Keep LRU cache of already-seen boosts, per timeline. It is a sorted set where the score is "last duplicate seen".
*

**Comment by nikodemus** [comment]
> I suppose I would argue that the existing "Group boosts in timelines" option is already the configuration for this option. It indicates that it causes the timeline to "not show new boosts for posts that have been recently boosted". It just doesn't define "recent".

The reason I would like some configuration option for the range is for people using services like masto.host (like, uh, myself), who can't go the source and change the hardcoded value. :)

> An approach like this will significantly change the data model required... and the big risk is that it becomes an unbounded data set to search.

Something like an inverse bloom filter could work (first google hit: https://github.com/tylertreat/InverseBloomFilter - but I remember seeing similar data structures with another name as well) would do it, but finding a decently performing Ruby implementation might not be easy. 

I'm guessing that attaching "last seen by person x" per post isn't reasonable either?

I wonder if user having bookmarked, faved, boosted, or replied to the post could work as a proxy for those cases?

> I thought this might make sense, but, I'm not sure if that's what people want. Personally, I don't want to see repeated content ever... I already saw that, why see it again? But, I have found since I applied this patch to my own instance that it can be surprising to later find out who and how comprehensively a post was boosted. I tend to think that the real feedback people would want is not re-seeing the same repost, but rather to see other people's interest in that post.

Yeah, I've noticed this myself. Seeing repeated boosts of the same posts is interesting in a way, especially after a while.

**Comment by nikodemus** [comment]
Got a brainstorm, maybe.

- To give the "hey, people are interacting with this post" feeback, one option would be to turn repeated boosts into small placeholders like are used for filtered posts.

- To avoid creating lots of new work on the server side, it would be possible to implement time-based filtering client side.

**Comment by WearsHats** [comment]
Checking the last 40 is definitely not enough, so I'm glad to see this under discussion.

I get that expanding that number gives the server more work. It also brings up the potential problem of my missing stuff because I was offline for a while and didn't scroll back far enough. If you raise the number to 400, it could filter out stuff that was posted and boosted while I was asleep. So I didn't see it the first time, but it gets filtered out because it was boosted within the last 400 posts.

But I had an additional thought. I'm seeing stuff reboosted that the server is aware I've previously interacted with. If it already has a ⭐ that's a guarantee I've seen it. I don't need to see it again. Likewise if I've boosted it or replied to it. Just filter all those out.

I still support expanding the number from 40 (maybe even giving user control of that number, if possible). But I think checking to see if I've interacted with it would be really helpful. (Not sure what to do about posts that I didn't like the first time if it's coming from someone I don't want to block/mute entirely.)

**Comment by untitaker** [comment]
I have opened #22946 that heavily penalizes the top N most recently reblogged items from appearing in your timeline. PTAL

**Comment by mjankowski** [comment]
Doing some PR triage -- going to close this one due to sheer age and lack of consensus in previous discussion (and no updates in ~2 yrs).

Please comment/reopen if I'm missed something and you'd like to keep pushing forward.

**Pull request closed without merging**
