### PR TITLE
Guide readers to production wiki page after Docker setup

### LINKED ISSUE #319: Document serving static files in production
**EDIT:** My first question has been answered, but it should be documented.

~~~Hi again, I've gotten much further in setting up my Mastodon instance. The only issue now is that static files aren't being served. Is this handled by Rails or do I need to set up an Nginx reverse proxy to handle that? The documentation stops with using docker-compose so I assumed that was it. Wanting to know if that's the case before I proceed.~~~

Thanks!

### PR DESCRIPTION
**Pull request by alexgleason**
Fixes #319

### CODE REVIEW

**Comment by cllorca** [comment]
I followed the docker installation on a fresh centos7 image on linode. I have nginx configured to serve the mastodon/public/ directory as the webroot. I notice however that my browser is trying to load https://doma.in/stylesheets/application.css , https://doma.in/javascripts/application_public.js which returns a 404 because mastodon/public/javascripts and mastodon/public/stylesheets/ do not exist nor contain any files. I see application-1078a50ea7455a87a0fad81e1526a8b06a4041172d632b032bfa5d0dfd600b42.css and a similarly named application_public-hash.js and other static resources in mastodon/public/assets/

How do I tell the app to load the production assets from the right path and/or how do I point nginx to serve the static resources out of mastodon/app/assets/(fonts, images, javascripts, stylesheets)

What did I miss? I followed this for my nginx conf: https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Production-guide.md

**Comment by Gargron** [comment]
You need to restart the docker container after running the `assets:precompile` task. Then Rails will pick up the correct file hashes.

**Comment by cllorca** [comment]
This did not seem to resolve my issue. I tried docker-composer down; docker-composer up -d. I also tried docker container commands and stopped each container manually then started back up. Now my reverse proxy doesn't seem to work. Going to start from scratch I guess.

**Comment by Gargron** [comment]
Here is a good guide written by someone from the community: <https://urgero.org/index.php?page=howto/linux/mastodon.md> Perhaps you'll see some step you've missed?

**Comment by mitchellurgero** [comment]
When using nginx - anytime you restart the docker containers you MUST restart nginx (It for whatever reason unbinds the port? its weird)

**Comment by cllorca** [comment]
That's the guide I wish I had the first time around :) I will spool up another fresh server and try this guide and see if I can get it to work. Thanks for the link. @mitchellurgero yeah, I restart the webserver every time I restart docker, but something else must have happened. I'll report back success if this guide works out. Thanks!

**Comment by mitchellurgero** [comment]
Let me know if the guide works for you because I wrote it :) (See the domain and front page of the site.)

**Pull request merged**
