### PR TITLE
Updated 'toots' to 'yiffs' and testing git commit

### PR DESCRIPTION
**Pull request by dogshapedangel**

### CODE REVIEW

**Comment by manedfolf** [comment]
THIS WAS AN ACCIDENT LMAO

**Comment by m4sk1n** [comment]
It would be a great idea to change wording with every release 🤔

**Comment by trwnh** [comment]
likes are now florps

**Comment by manedfolf** [comment]
perhaps this would have a better chance if I spelled yiff properly, alas....

**Pull request closed without merging**
