### PR TITLE
Update Simplified Chinese translations

### PR DESCRIPTION
**Pull request by ghost**
This PR also includes a [fix](https://github.com/tootsuite/mastodon/commit/9df63c98767297e25616cb2f2d0632e4e086517e) for two "e-mail"s 😂

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Screenshots are from #6256 and #6263, only for reference; **they're NOT reflecting the latest code**

**Comment by SerCom-KC** [comment]
cc @Artoria2e5 @leopku

**Review by Gargron — APPROVED** [review]

**Pull request merged**
