### PR TITLE
Fix overflowing in web UI

### PR DESCRIPTION
**Pull request by lynlynlynx**
- It is needed to re-set text-overflow and overflow in `display: block;` .
With this commit, all overflowing problems are solved! 🎉 

Screenshot ( I use "THISISATESTFORVERYLONGUSERNAME", 30 letters.)
ba26

- ~~Fix: dropdown menu modal overflows outside the edge of the browser.~~

~~Before and after screenshots~~
ba27
~~Of course, modal sizing works properly.~~
ws000107

### CODE REVIEW

**Comment by lynlynlynx** [comment]
Unfortunately, `max-width: max-content;` property is not yet supported in Edge.
I reverted fixing overflowing dropdown menu modal.

**Comment by nightpool** [comment]
Can we use the max-content anyway? does is *break* on edge or is it just not supported? Can we use `@supports(max-width: max-content)` to gate this?

**Comment by nightpool** [comment]
```
display: block;
overflow: hidden;
text-overflow: ellipsis;
```

seems like it's getting repeated a lot of places. Maybe it makes sense to make a mixin rule?

**Review by Gargron — APPROVED** [review]

**Comment by lynlynlynx** [comment]
@nightpool thanks for your comments. 
max-width breaks styles on Edge, and it is not a fundamental way, so i look for another.
Repeating a lot, thats right, ill try to organize them with mixins before long

**Pull request merged**
