### PR TITLE
Remove kmr from language selection

### LINKED ISSUE #22200: Language Kurmancî shows up twice
### Steps to reproduce the problem

1. Open the language picker
2. Type "Kurdish"
3. See that Kurmancî (kmr/ku) is listed twice

Screenshot_2022-12-10-12-00-44-290-edit_com kiwibrowser browser

### Expected behaviour

Each language should be listed just once

### Actual behaviour

Kurmancî is being listed twice (kmr and ku)

### Detailed description

While trying to figure out which languages my Mastodon client should support (the API docs just say "ISO 639 language code", which should probably be specified – there's no way to query the supported languages, is there?) and after hearing that some [ISO 639-3 languages are missing](https://github.com/sk22/megalodon/issues/139) from Java's ISO 639-1 language list, I looked up the `LanguagesHelper` module, where I found two lines for the same (?) language:

```
ku: ['Kurmanji (Kurdish)', 'Kurmancî']
…
kmr: ['Kurmanji (Kurdish)', 'Kurmancî']
```

### Specifications

Mastodon v4.0.2

### LINKED ISSUE #22647: Kurmancî language item count
### Pitch

In Mastodon Web app Preferences->Other->filter languages, Kurmancî language item is doubled.

### Motivation

suitability for kurmacî language users

### PR DESCRIPTION
**Pull request by gunchleoc**
Closes https://github.com/mastodon/mastodon/issues/22647

Closes https://github.com/mastodon/mastodon/issues/22200

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Hi! I am not sure about this change, as my understanding is that we use the `ku` code for Kurmancî, and this change would cause the interface language picker to show “Kurdi” for `ku`.

**Comment by gunchleoc** [comment]
Kurmanji is `kmr`. See also Crowdin: 
crowdin_kmr

So, we need do a different name for `ku` to disambiguate.

I just tested in Mastodon and when I set the interface language to "Kurmancî" and then the posting language to match the UI language, the suggested posting language is `ku`, although the translation project in Crowdin is `kmr`. Something is wrong here and I'll need to do some more digging.

I don't speak those languages, but I did check my usual sources (CLDR, Wikipedia) and they agree. See my reasoning here: https://github.com/mastodon/mastodon/issues/22647#issuecomment-1637178975

For the sake of completenes, Sorani is `ckb` in Crowdin 
crowdin_sorani

**Comment by gunchleoc** [comment]
I have found the problem. This should now work, including database migration for the UI language setting.

I suspect that it has been a while since translations were pulled down from crowdin, since the locale codes did not match. So this PR should get some priority.

I have refrained from updating existing posts' langue settings, because both `ku` and `kmr` are available in the language selector.

**Comment by gunchleoc** [comment]
How do I fix these errors in the tests?

```
Run ./bin/rails db:create db:schema:load db:seed
Created database 'mastodon_test'
Run `bin/rails db:migrate` to update your database then try again.
You have 1 pending migration:
  20230813201512 FixKurdishLocale
Error: Process completed with exit code 1.
```

**Comment by ClearlyClaire** [comment]
> I suspect that it has been a while since translations were pulled down from crowdin, since the locale codes did not match. So this PR should get some priority.

I believe this is inaccurate and Crowdin is configured to export this locale as `ku`:
image

**Comment by ClearlyClaire** [comment]
I'm trying to wrap my head around the issue, and looking back at the conversations I had with a native speaker spanning from a few years ago. At some point we had Sorani (ckb) in the `ku` files, and I'm honestly not sure what was going on with the `kmr` files.

Back then, the `react-intl` version we were using (only recently updated) did not appear to support `kmr`, only `ku` and `ckb` (with the `ku` rules looking like they were for `kmr`), so we used `ku` for Kurmancî and `ckb` for Sorani.

Now, the version of the library we use should defer to the browser for locale support, and in case the browser does not support that API, fall back to a polyfill. But that polyfill seems to have support for `ku` and `ckb`, but not `kmr`.

Looking at browsers, `Intl.PluralRules.supportedLocalesOf(['en', 'ckb', 'ku', 'kmr'])` returns `['en', 'ckb', 'ku']` in all browsers I could try, so I think `kmr` should not be used.

Furthermore, https://cldr.unicode.org/index/cldr-spec/picking-the-right-language-code#h.lc35xrlj4da6 says:
> Similarly, suppose that you are looking for Kurdish written in Latin letters, as in Turkey. It is a mistake to think that because that is in the north, that you should use the subtag 'kmr' for Northern Kurdish. You should instead use [ku-Latn-TR](http://www.google.com/url?q=http%3A%2F%2Fku-latn%2F&sa=D&sntz=1&usg=AOvVaw3IXuhvSg0TdFcYJVc8LHol). See also: [ISO 636 Deprecation Requests](https://cldr.unicode.org/development/development-process/design-proposals/iso-636-deprecation-requests-draft).

**Comment by gunchleoc** [comment]
Shall we get rid of the `kmr` locale then as a duplicate of `ku` and keep `ku` with "Kurmancî" as its name? This sounds like a reasonable option to me to solve the problem.

**Comment by gunchleoc** [comment]
Done. Will we want a migration for posts' language too?

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
I merged this, but I'm now thinking about the issue of people possibly having selected `kmr` as their default posting language (not sure if there is any), in which case their default posting language will be mishandled. We possibly want a post-deployment migration here.

**Comment by gunchleoc** [comment]
I checked on an instance that's still on the latest stable and it has 2 Kurmancî-Entries in the dropdown for the posting language, so we should do that, and to be thorough for the posts as well.

**Comment by ClearlyClaire** [comment]
I addressed the settings in https://github.com/mastodon/mastodon/pull/26787

As for the posts, I am not sure this is worth another big migration.

**Pull request merged**
