### PR TITLE
Remove `sleep` in request pool spec

### PR DESCRIPTION
**Pull request by mjankowski**
The `RequestPool` uses a persistent http connection and passes a timeout value specifying when to close when idle for too long.

Previously the spec was using a `sleep` loop to simulate this timeout. This change instead stubs out the `seconds_idle` method on the `Connection`, which simulates an idle timeout having occured without the need for a long `sleep` duration in the spec.

Drops this one example from ~61 seconds to basically zero.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
One issue I have with this change is that it stops testing the proper behavior of reaper threads… I guess another way to save a few seconds would be to stub `RequestPool::MAX_IDLE_TIME` with a lower value, but this wouldn't be nearly as effective as your change.

**Comment by mjankowski** [comment]
> One issue I have with this change is that it stops testing the proper behavior of reaper threads… 

Yeah ... the `p.flush` line specifically within `Reaper` was previously called but is now not called with this change.

I had been looking for a place to stub the raising of a TimeoutError as a first choice here, but nothing obvious jumped out at a first pass, so I settled on stubbing the seconds_idle method as next best.

> I guess another way to save a few seconds would be to stub `RequestPool::MAX_IDLE_TIME` with a lower value, but this wouldn't be nearly as effective as your change.

Yeah ... we should do this at a minimum to drop this from ~60s to ~2s or whatever we want to stub to, but I think we can find a clean way to get all the way down to ~zero and not lose coverage.

I'll take another pass at this by first adding some `Reaper` and `Connection` class coverage to see if we can preserve that while still stubbing out the timeout scenario.

**Comment by mjankowski** [comment]
Pushed a change which adds some coverage for the `Reaper` class so we don't lose that when we stub the idle time.

**Comment by mjankowski** [comment]
Another idea here -- I'd be happy to open another PR which (for now) JUST stubs out the const to get a smaller sleep value in the spec, and we can keep noodling on better ideas to get rid of it entirely after that's in.

**Comment by ClearlyClaire** [comment]
Yes, that was what I was suggesting with:
> I guess another way to save a few seconds would be to stub RequestPool::MAX_IDLE_TIME with a lower value, but this wouldn't be nearly as effective as your change.

**Comment by mjankowski** [comment]
Opened https://github.com/mastodon/mastodon/pull/25470 which uses that approach.

**Pull request closed without merging**
