### PR TITLE
Add options to filter registrations on invite request text

### LINKED ISSUE #15273: How to make the invite request field mandatory
Hello,

On my instance, I activate the manual approval mode for accounts.
Now I'm dealing with high amount of accounts created without the invite field (Why do you want to join?) completed.
I want to make this field mandatory/required.

(after more than hour of search)
I try to edit the file /app/views/auth/registrations/new.html.haml to change to
= invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: true
(I also run the commands RAILS_ENV=production bundle exec rails assets:precompile and restart mastodon processes after that)

But the field is not required and I can create a test account without this field.

How to make this field mandatory ?
(version 3.2.1)

Thank you.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This partially addresses #13269 and #10742 by adding registration text filters: the rationale being that spambots frequently feel invited to paste their crap into the invite request field, so providing a way to filter those with keywords and regexps seem useful.

### Adding a filter

image

### Regexp validation

image

### Listing filters (mod and admin-facing)

image

### Audit log (mod and admin-facing)

image

## Registration form (user-facing)

image

### CODE REVIEW

**Comment by koyuawsmbrtn** [comment]
Another idea that came to my mind is to use regex to disallow reserved usernames like admin, root etc.

**Comment by shleeable** [comment]
Love to see it.

**Comment by Gargron** [comment]
> Another idea that came to my mind is to use regex to disallow reserved usernames like admin, root etc.

There's already a list of reserved usernames!

**Review by Gargron — COMMENTED** [review]
General thoughts:

- Making admins input regex directly will backfire. First, it's not very user-friendly and people will mess up the separators and escaped characters and what not (we've been through this with HTML already). Secondly, it's dangerous because people will accidentally create slow regexes. It would have to be something like our phrase filter form instead
- Too many settings on one page. We need to begin splitting up settings into separate pages, like a page dedicated to sign-ups or whatever. The form is too huge.

**Comment by ThibG** [comment]
Agreed wrt. regexps not being very user-friendly, although I do think being able to write regexps here is useful, maybe each filter could be either a word or a regexp. Wrt. slow regexps, only the instance admins can set them, and they are only applied to registrations, so I really don't think that's an issue.

I also agree with the fact the site settings would benefit being split into different pages, but I'm not too sure how they should be split.

**Comment by ThibG** [comment]
Maybe I could split this PR in 3:
- add the option to require invite request text (would still be an additional setting in the huge settings page, but we could break that down later)
- JS fixes
- add the option to filter on invite text (which would need to be reworked to not be a single regexp field)

**Comment by ThibG** [comment]
Split #15325 and #15326 out of it, I will rework the filtering thing later once they are merged.

**Comment by koyuawsmbrtn** [comment]
bump

**Review by ykzts — DISMISSED** [review]

**Comment by ClearlyClaire** [comment]
ping @Gargron

**Comment by ClearlyClaire** [comment]
ping @Gargron

**Comment by ClearlyClaire** [comment]
Rebased. Again.

cc @Gargron

**Comment by mstdn** [comment]
Wow, this is a great start!

**Comment by cking** [comment]
instead of allowing "plain" regex, you instead could use regular wildcards (that are already wildly used) like `*` and `?`

at least almost everyone understands what star means in normal wildcard environments. you could even go so far to make it understand (web)paths by differentiating `/*/` (single directory) and `/**/` (nexted directories) though that would be more complicated to understand

**Comment by mstdn** [comment]
Bump.. 

Is there a possibility this can get merged? We really, really, reallllllyyy need something against the bots..

**Comment by ClearlyClaire** [comment]
Rebased again.

**Comment by ThisIsMissEm** [comment]
I think the UI for listing the registration filters would probably better live under `/admin/settings/registrations`, since that's where you already configure registrations, so adding filters to that part of the UI feels like it'd make more sense, than adding it under the moderation section in the navigation.

It feels like we shouldn't give immediate feedback that the registration isn't accepted, but instead delay that until after their email is confirmed, and then do a email notification saying the registration was rejected automatically. This prevents an attacker from trying to "guess" the filters as to side-step them.

**Pull request closed without merging**
