### PR TITLE
Remove outline from focused toot

### PR DESCRIPTION
**Pull request by ykzts**
| before | after |
|-|-|
|  |  |

### CODE REVIEW

**Comment by unarist** [comment]
Probably it's useful while navigation by keyboard, even it's useless while using mouse.

Facebook and Twitter shows outline when I use keyboard, and it doesn't show when I use mouse. I think this behavior is better.

**Comment by sorin-davidoi** [comment]
Isn't this bad practice regarding accessibility?

**Comment by Gargron** [comment]
I suggest replacing the outline with a highlighted background (slightly less bright than the DM background, to avoid confusion - and slightly brighter for DMs)

**Comment by ykzts** [comment]
@sorin-davidoi @Gargron I changed styles.I feel like I have a better style....

### focus toot



### focus only toot content

**Review by Gargron — APPROVED** [review]

**Comment by beatrix-bitrot** [comment]
@ykzts @Gargron i request that this change be reverted before the release of 1.5.0

the reduction in contrast makes the text significantly more difficult to read

**Comment by yiskah** [comment]
Sorin is right, you need to have a way to mark that an object has focus. The outline is standard. If you must use something else you *must* do some bug-testing first to make sure you aren't making things less accessible. I agree with bea that it would be best to just revert to using the outline; that or test the contrast ratios this brings for every possible text, color, etc. that post-objects (including favs in notifs) can appear with

**Comment by nightpool** [comment]
additionally, this change makes it very easy to confuse private messages with ones that are focused.

**Comment by ykzts** [comment]
@beatrix-bitrot @yiskah @nightpool 

> additionally, this change makes it very easy to confuse private messages with ones that are focused.

I agree. I actually used it and had a sense of incompatibility.

Please check #4474

**Pull request merged**
