### PR TITLE
Remove previous landing page

### PR DESCRIPTION
**Pull request by Gargron**
The server card now displays in the web app, so the previous landing page no longer serves a purpose.

Redirect to frontpage.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
Please revert this, the old landing page was leagues better for instances that do not have or want trending content.

**Comment by Siphonay** [comment]
I have a huge issue with this new landing page: if you don’t want it to look completely empty, you have to inevitably have trends on your server. I do not wish to let trends be unmoderated on my server as it’s a huge vector for abuse and misinformation, but managing them is honestly unfeasible with only volunteer time, as they never stop showing up. Nearly all servers are non-commercial and do not have the funds to pay people full compensation for such moderation, I’m really not alone in this situation at all.

What this new landing page causes is that for servers like mine, unregistered users will be presented with an empty column front and center. I don’t need to explain that it’s a bad first impression when you want to be a welcoming, living space. It is also massively depriving admins of control over how their instance presents, which is incredibly frustrating.

There are many things, most out of control of the Mastodon development, that makes running a server more and more of a time-consuming burden for admins like me. Being forced to switch over to this landing page might be the tipping point that makes me give up on Mastodon entirely.

I politely request that you please re-evaluate those changes.

**Comment by foreverxml** [comment]
I don't think this is a good idea, it shuts access for users with no JS and makes Mastodon look like another twitter clone.

**Comment by justjosias** [comment]
On the instances I've run, we don't want local posts to be shared on the landing page. Previously that was as easy as changing settings in the administration menu. Is there a way to maintain this behavior without making the new landing page appear completely empty?

**Comment by Gargron** [comment]
> There are many things, most out of control of the Mastodon development, that makes running a server more and more of a time-consuming burden for admins like me. Being forced to switch over to this landing page might be the tipping point that makes me give up on Mastodon entirely.

I sympathize with the time requirements of running a Mastodon server. But that time is spent not for the benefit of the software, but for the benefit of the people using the software. Let me make clear that I do sit around and scheme for how I could ruin more admins' day. My efforts are in improving the software for the end-users. People *want* to see interesting content. The defining factor in whether someone will want to use Mastodon or not is whether there is something interesting they can read on the platform. Trends are just the most effective and safe way to prove that there is.

Let me however suggest a few ideas. First, it is possible to approve the most regular users, hashtags, and link domains, and then opt-out of any further notifications about trends up for review. It is more or less a one-time effort, it is not ideal and not flexible as time progresses, but it is better than nothing. Second, if your server is otherwise well-moderated, I consider it safe to run trends without requiring review. Any offending content that might slip through will be reported the usual ways, and it's still more safe than the local or federated timelines.

> I don't think this is a good idea, it shuts access for users with no JS

Mastodon has always required JS post-login. If I was just making this change for the sake of requiring JS, I would agree with you, but I think that having one consistent UI and layout is more valuable than maintaining compatibility with those few who run NoScript. Internal and external UIs looking and behaving differently has been source of user confusion, not to mention the burden of maintaining styles and components in two different places. The web app just looks better, too.

>  and makes Mastodon look like another twitter clone.

You (collectively) need to move away from the Twitter clone argument. You conveniently forget it every time you request Mastodon to copy a feature that you *like* from Twitter and you consider a "must-have". When you visit twitter.com, you don't get the explore page, you get login/sign-up form just like our previous landing page.

> On the instances I've run, we don't want local posts to be shared on the landing page. Previously that was as easy as changing settings in the administration menu. Is there a way to maintain this behavior without making the new landing page appear completely empty?

The setting for disabling unauthenticated access to the public timelines still exists. There never was a setting for excluding *local* content from being shown, so I figure that's what you meant. Disabling that *and* trends would result in all accessible pages in the web app being empty. We might come up with a different placeholder for that particular configuration (though I would prefer not to add more different layouts and keep it as consistent as possible).

___

I strongly believe that the new layout is the right way forward. However, I'm open to suggestions on how to make it work better for your configurations. For example, perhaps using an illustration for the empty placeholder would alleviate your concerns about it looking empty without trends, or duplicating the server card in the middle.

**Comment by wolfteeth** [comment]
Maybe a good alternative would be to redirect to the about/more page? Something reasonable for closed/invite-only servers that don't want to display the local TL to random web visitors.

**Comment by ClearlyClaire** [comment]
> I sympathize with the time requirements of running a Mastodon server. But that time is spent not for the benefit of the software, but for the benefit of the people using the software. Let me make clear that I do sit around and scheme for how I could ruin more admins' day. My efforts are in improving the software for the end-users. People _want_ to see interesting content. The defining factor in whether someone will want to use Mastodon or not is whether there is something interesting they can read on the platform. Trends are just the most effective and safe way to prove that there is.

It really just is _your idea_ of what people want. Evidently, instances who do not want to have trends are currently doing fine, and their users are not complaining. Many users and admins do not care or do not want trends, and the way you're repeatedly discarding their opinion is disheartening.

> > I don't think this is a good idea, it shuts access for users with no JS
> 
> Mastodon has always required JS post-login. If I was just making this change for the sake of requiring JS, I would agree with you, but I think that having one consistent UI and layout is more valuable than maintaining compatibility with those few who run NoScript. Internal and external UIs looking and behaving differently has been source of user confusion, not to mention the burden of maintaining styles and components in two different places. The web app just looks better, too.

That argument may make sense for the server-side-rendered pages for posts and accounts, but I fail to see how it applies to `/about`, which is its own thing.

> I strongly believe that the new layout is the right way forward. However, I'm open to suggestions on how to make it work better for your configurations. For example, perhaps using an illustration for the empty placeholder would alleviate your concerns about it looking empty without trends, or duplicating the server card in the middle.

What about: keeping `/about` as it was, and have it link to `/web/explore` when trends are enabled? You'd have the friendly, not-overwhelming, works-for-everyone landing page, with quick access to the WebUI and trending posts if that feature is enabled.

> Maybe a good alternative would be to redirect to the about/more page? Something reasonable for closed/invite-only servers that don't want to display the local TL to random web visitors.

That could work, but I think `/about/more` would require a rework to be more friendly than a wall of text with sign-in and sign-up buttons in a corner… but really, I think the previous `/about` was spot on for this.

**Comment by cadadr** [comment]
This is fucking awful. 

>> Let me make clear that I do sit around and scheme for how I could ruin more admins' day. My efforts are in improving the software for the end-users. People want to see interesting content.

Hello I'm an end user and I want none of this. I don't go to random instances to browse their local timelines or their federated timelines. I have absolutely no idea how this feature can be useful to any user at all. Oh but if you want your boring server to display interesting posts from people on other servers on the landing page, making it artificially more interesting, then yeah, this feature/design is probably useful. But that's more relevant to rogue admins than any users, isn't it? And frankly I wouldn't wanna be on a server what opens its local timeline to public. In fact that's why I prefer Hometown and Glitch-soc servers, because the local timeline is a meaningful place to encounter local users and not just where public posts from local users go.

As a user when I visit a server I want to see their `/about/more`, more than anything. I wanna see if they have good rules, and I wanna see their block list.

I'd say you're making up users whose made up desires, behold this marvellous gimmick of fate, exactly match your desires as to whatever kind of boring direction you want to take Mastodon towards. Whether it's this, or the awful, terrible, horrible, bullshit new reporting interface on 3.5.x, this is not what **we**, users of masto, want. I'm growing really tired of whatever the heck you're getting up to.

>> I strongly believe that the new layout is the right way forward. However, I'm open to suggestions on how to make it work better for your configurations.

    $ git revert ...

**Comment by Gargron** [comment]
> I have absolutely no idea how this feature can be useful to any user at all.

When designing Mastodon's interface, my primary focus is on non-technical people, not programmers, and not fediverse veterans, people who use social media to read and discover content, not browse through other servers' block lists as a pastime, though I don't see how this PR makes the latter any more difficult.

> I don't go to random instances to browse their local timelines or their federated timelines.

This is however an extremely common use case on the fediverse, because when people start brand new servers for themselves or their communities, there is no content on that server, so to find people to follow you go and browse other servers' feeds. It's always been this way, and when you don't have to do it, it's because other users on your server have done it for you before.

> I'd say you're making up users whose made up desires, behold this marvellous gimmick of fate, exactly match your desires as to whatever kind of boring direction you want to take Mastodon towards.

I do not appreciate your tone. Nobody forces you to use Mastodon, or update to a release containing these changes. Use whichever fork you prefer. I'm in a unique position where I get to listen to a lot more feedback about the software and platform than most people, you are free to believe it or not.

**Comment by cadadr** [comment]
I'm not on fedi to program, so whether I happen to program does not make my views that of a programmer. I'm a user of this software, and I use it to "read and discover content" indeed, we could say. I don't look at blocklists as a pastime, I look at that stuff to see if an instance is a safe, decent one, with active moderators (unlike e.g. mastodon.social and mastodon.online, wink wink). It's pretty malicious of you to try portray me as some weirdo who gets a kick out of lists of blocked domains, honestly.

> This is however an extremely common use case on the fediverse, because when people start brand new servers for themselves or their communities, there is no content on that server, so to find people to follow you go and browse other servers' feeds. It's always been this way, and when you don't have to do it, it's because other users on your server have done it for you before.

I've never once done this or heard anybody do this. I've found people to follow organically, and we recommend newcomers to post #/introduction posts and go to "Trunk" to find people to follow. Other servers' feeds is also available to you in the federated timeline, you don't need to go visit other servers' front pages.

Instead of tone policing me, stop lying. And quit the "nobody forces you" bs. You make a living out of this because users like me make fedi a worthwhile place. And sadly, very sadly, currently masto is the flagship fediverse server, so "don't use / fork off" is kinda like telling "get off fediverse".

I've seen many other fedizens be critical of these non-features and anti-features, this one included, people who are instance admins and users and not programmers. I'll take their word over what words you wanna put in their mouth. In fact I haven't heard one positive opinion about these recent features, besides edits, which receives mixed opinions. It clearly shows that it's untrue that you are "in a unique position where I get to listen to a lot more feedback about the software and platform than most people", at least when it comes to masto users.

I'll leave you be, and unsubscribe from this issue. I don't like interacting with people who when criticised, prefer to double down on their mistakes/misdeeds.

**Comment by Gargron** [comment]
> Other servers' feeds is also available to you in the federated timeline, you don't need to go visit other servers' front pages.

The only content in the federated timeline you get, is from users followed by at least one other person on your server. How did those people originally get followed from your server? Somebody went out and scavenged using external means such as aforementioned "Trunk" and other servers' public feeds and profiles. It is and always has been crucial for bootstrapping new servers and as discovery tools for those who self-host for just themselves. Organic discovery only becomes an option once you're past that hurdle.

Speaking of organic discovery, that does not just extend to new servers, but to new users as well. When I follow a lot of people, I get to discover other people and interesting content through reblogs (which is what you would call "organically"), so I do not feel the need to venture beyond the home feed. But when I am brand new, I do not follow anyone yet. The home feed is empty. Where to go? That is exactly where discovery comes in: Trends, follow recommendations, hashtags, local and federated timelines. Perhaps I'm not even signed up yet. I am wary of signing up to one more website and my interest has a limited time span. I need to see that there is something worth seeing on this unfamiliar platform so that I may decide to give it a spin.

> You make a living out of this because users like me make fedi a worthwhile place

I make 36.000 EUR per year pre-tax on a customer-facing, 24/7 job with 8-9 different areas of responsibilities and semi-regular harassment instead of doing literally anything else in the software industry that would pay more and be far less stressful because I am passionate about this project and believe that I am doing the right thing for the web, and because there are people who find the work that I'm doing, and the servers that I maintain to be valuable enough to fund the non-profit I founded with my savings. 

Side note: I checked your profile to see what "users like me" means after writing the above. I doubt that people who [insult others](https://archive.ph/22PYZ) make the fediverse a worthwhile place.

**Pull request merged**
