### PR TITLE
2.4.5-alpine3.8 (Test and consider 2.5.3-alpine3.8)

### PR DESCRIPTION
**Pull request by shleeable**

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Review by ykzts — APPROVED** [review]

**Comment by ashleyhull-versent** [comment]
ok. aus.social has been running this configuration since release... So far there are no issues. zero segfaults.

Waiting for others to give their recommendations.

**Comment by ashleyhull-versent** [comment]
ok. aus.social has been running this configuration since release... So far there are no issues. zero segfaults.

Waiting for others to give their recommendations.

**Comment by ashleyhull-versent** [comment]
ok. aus.social has been running this configuration since release... So far there are no issues. zero segfaults.

Waiting for others to give their recommendations.

**Comment by ashleyhull-versent** [comment]
ok. aus.social has been running this configuration since release... So far there are no issues. zero segfaults.

Waiting for others to give their recommendations.

**Pull request merged**
