### PR TITLE
Add some missing `dependent: :destroy` to models

### PR DESCRIPTION
**Pull request by mjankowski**
First-pass at some that were most obvious. There are still some missing `dependent` where I need to review again on how they should be declared. Each change is in one commit, so if any of these are incorrect for whatever reason, let me know which one and I can remove/rebase.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
All of those are deleted postgres-side through foreign key constraints and none of those have logic, so changing this would cause more models to be loaded and instanced. It's probably not a big change, though, and batch-deletion code paths should already handle those separately.

**Comment by mjankowski** [comment]
> All of those are deleted postgres-side through foreign key constraints and none of those have logic, so changing this would cause more models to be loaded and instanced. It's probably not a big change, though, and batch-deletion code paths should already handle those separately.

Ah, I see that now in the schema def, cool. Agreed that we don't want to add callback cycles where its more efficiently handled already in db.

Any objection to a separate PR which adds explicit `dependent: nil` to cases that are doing that db-level FK approach?

**Comment by ClearlyClaire** [comment]
> Any objection to a separate PR which adds explicit `dependent: nil` to cases that are doing that db-level FK approach?

Nope, fine by me!

**Comment by mjankowski** [comment]
Closing in favor of https://github.com/mastodon/mastodon/pull/28169

**Pull request closed without merging**
