### PR TITLE
Change default ruby version to 3.3.1

### PR DESCRIPTION
**Pull request by mjankowski**
Ruby 3.3.0 will likely be released around end of year, and 3.0 will be EOL in spring 2024.

We should not merge this until release, at least. Opening to see how CI behaves and hopefully work out any gem/lib issues leading up to release.

### CODE REVIEW

**Comment by mjankowski** [comment]
I see this failure intermittently locally - https://github.com/mastodon/mastodon/actions/runs/6936292271/job/18868266030#step:8:44 - and did see it in my first 3.3.0 spec run locally ... but can't regularly reproduce. I suspect not actually related to 3.3.

**Comment by renchap** [comment]
Good idea, I thought about it yesterday. 3.3 seems to bring many perf and memory improvements, so it will be very welcome.

I never saw this failure with an earlier version, so it must be somehow triggered by 3.3.0, or by one of our deps not supporting 3.3.0?

**Comment by shleeable** [comment]
> Good idea, I thought about it yesterday. 3.3 seems to bring many perf and memory improvements, so it will be very welcome.

https://railsatscale.com/2023-09-18-ruby-3-3-s-yjit-runs-shopify-s-production-code-15-faster/ ooooh nice.

**Comment by renchap** [comment]
Agreed, this test should probably be rewritten

**Comment by mjankowski** [comment]
Updated to use `3.3.0-rc1` ... which is apparently not yet available in `setup/ruby-build` - https://github.com/ruby/setup-ruby/pull/549

**Comment by renchap** [comment]
> I'm guessing this is a side effect of thread improvements (?) in 3.3 and we'll have to rewrite that in a way that gets at the same assertion a different way.

This seems to be the way to go. I cant wait to test with Ruby 3.3 in production and have a look at the performance and memory usage :)

**Comment by mjankowski** [comment]
Did a little more research here, added debugging, did some git bisect, and now have something more of a replication ability...

In ruby 3.3.0, when any spec which performs an http request with our `Request` class (there are many of these) runs before the request pool spec here, the spec fails.

A minimum replication is to add a line like `Request.new(:get, 'http://example.com').perform` right into the failing spec, before the array/thread loop. This will pass just fine in 3.2.2, and fail in 3.3.0.

Further debugging shows that in 3.2.2 the `RequestPool::Connection` object is initialized multiple times by different threads, whereas in 3.3.0 it's only initialized once (by the first thread created ... or presumably the first to execute).

I'll continue to try to follow this logic around, although I'll admit that the collection of custom request/pool/stack/etc classes are a bit hard to navigate through without full context. If anyone has insights just from the above info, that's appreciated.

**Comment by ClearlyClaire** [comment]
Those classes have been added in #10353 and basically left untouched since, and I am not familiar with them.

However, instrumenting `ConnectionPool::SharedConnectionPool#checkin` and `ConnectionPool::SharedConnectionPool#checkout`, I can see that Ruby 3.2.2 interleaves checkin and checkout irregularly as you would expect from such a number of threads, while on 3.3.0 it always checks in before checking out again, suggesting that the code is thread-safe but does not exhibit parallelism like we expect. This may be done to Ruby having a different strategy regarding when to yield execution to another thread, and the stubbed request not actually doing I/O, and thus not encouraging Ruby to yield to another thread.

Adding a small `sleep` statement in the `with` block in the test seems to fix the test failure:
```patch
diff --git a/spec/lib/request_pool_spec.rb b/spec/lib/request_pool_spec.rb
index f179e6ca94..b718c798a2 100644
--- a/spec/lib/request_pool_spec.rb
+++ b/spec/lib/request_pool_spec.rb
@@ -33,11 +33,14 @@ describe RequestPool do
 
       subject
 
+      Request.new(:get, 'http://example.com').perform
+
       threads = Array.new(20) do |_i|
         Thread.new do
           20.times do
             subject.with('http://example.com') do |http_client|
               http_client.get('/').flush
+              sleep 0.01
             end
           end
         end
```

**Comment by mjankowski** [comment]
Thanks for that insight. I have an approach based on that scheduler-nudging idea, which I'll open in another PR.

**Comment by mjankowski** [comment]
Opened another PR with an attempt to resolve the thread thing - https://github.com/mastodon/mastodon/pull/28596 - but also realized that one won't actually run 3.3 on CI run ... so I cherry-picked that commit onto this branch as well, and we'll see it run here.

**Comment by ClearlyClaire** [comment]
Your change does not seem to have fixed the issue. I personally do not experience any significant change in execution time with the `sleep` statement, but there's a couple things we can do to reduce the spec's execution time:
- change the sleep statement to `sleep 0`
- reduce the number of threads and iterations: 3 threads doing 2 iterations each seem to be enough for the test to pass pretty much 100% of the time on my setup

**Comment by mjankowski** [comment]
Yeah - just saw that ... I did some local testing and both the sleep and logging approaches seemed to work ... will play with more options here.

**Comment by mjankowski** [comment]
Added the `sleep(0)` and reduced the loop counts - that seems to have worked. Will update the other PR to include that change, and can review over there.

**Comment by mjankowski** [comment]
Rebased against main after the spec change merged, presumably we'll still be good there.

Are there any other concerns with this? Do we want to also update the Dockerfile and devcontainer defs in this PR? Anything else we can benchmark/verify?

**Comment by mjankowski** [comment]
I have separate "enable YJIT" and "turn on performance warnings" (finds object shapes issues) branches which I'll open as PRs as well with this branch as their base.

**Comment by renchap** [comment]
Yes the Docker image should be bumped, probably best to do it in this PR.

Deploying it to a production environment with Ruby 3.3.0 is probably a good idea to ensure we did not miss anything obvious, maybe @vmstan already does it?

**Comment by vmstan** [comment]
I had not done it yet, I was waiting to see if there was more required than just the bump.

**Comment by mjankowski** [comment]
Updated to bump Dockerfile as well. I think the devcontainers repo is not yet updated, but there's a PR for the bump there.

**Comment by vmstan** [comment]
I've been running containers based on the official Dockerfile, with Ruby 3.3, since January 4 and didn't see any errors or major problems, and initially didn't really see much difference in resource consumption until over the weekend I noticed that Sidekiq and Puma pods were using 1GB more in memory than what they normally run at.

My Sidekiq containers are usually around 850MB each once they've been running for an hour or two. Those are all queues (except scheduler and mailer) with 25 threads per pod. Scheduler/mailer runs in its own pod which is usually around 400-450MB. Puma pods are usually around 2.2GB each for me, that's set at 4 concurrency and 16 threads.

I did my last build and deployment on Friday, January 5, before the weekend around 4PM central US (as shown on graphs below) and did not reload any of them until Monday.

All Sidekiq and Puma pods were using around 700MB-1GB more memory than normal.

Screenshot 2024-01-08 at 8 02 34 AM
Screenshot 2024-01-08 at 8 03 01 AM

Charts show host level memory consumption from two hosts that were running the majority of the Ruby based pods. You can see pretty level consumption (with dips and gradual warming as pods are updated) through most of last week before Ruby 3.3 was adopted. 

To further validate this, I am in the process of building both Ruby 3.2 and Ruby 3.3 images of the latest `main` code, and deploying them in parallel for Sidekiq for direct comparison. I should have that up and running in the next few minutes.

**Comment by mjankowski** [comment]
RE: memory, I have no idea if this is the same issue you are seeing, but there is at least one discovered (and fixed, will be in 3.3.1) issue in the general area of memory growth - https://github.com/ruby/ruby/pull/9398 / https://bugs.ruby-lang.org/issues/20104

**Comment by mjankowski** [comment]
3.3 support in devcontainers now https://github.com/devcontainers/images/pull/905

**Comment by renchap** [comment]
Might be related to https://github.com/Shopify/ruby/issues/552#issuecomment-1902067761

@ClearlyClaire do we use Relation#extending?

**Comment by casperisfine** [comment]
> do we use `Relation#extending` or `Object#extend` somehow?

Grepping in your dependencies, I see `kaminari`:

```
/Users/byroot/.gem/ruby/3.3.0/gems/kaminari-activerecord-1.2.2/lib/kaminari/activerecord/active_record_model_extension.rb
17:          limit(per_page).offset(per_page * ((num = num.to_i - 1) < 0 ? 0 : num)).extending do
```

```ruby
      # Fetch the values at the specified page number
      #   Model.page(5)
      eval <<-RUBY, nil, __FILE__, __LINE__ + 1
        def self.#{Kaminari.config.page_method_name}(num = nil)
          per_page = max_per_page && (default_per_page > max_per_page) ? max_per_page : default_per_page
          limit(per_page).offset(per_page * ((num = num.to_i - 1) < 0 ? 0 : num)).extending do
            include Kaminari::ActiveRecordRelationMethods
            include Kaminari::PageScopeMethods
          end
        end
      RUBY
    end
```

But no other hits in the app or elsewhere. Also note that this may or may not be the cause. If it is, `3.3.1` will fix it.

**Comment by casperisfine** [comment]
And `.page(` returns quite a few hits in the app:

```
 rg -F '.page('
app/controllers/relationships_controller.rb
32:    @accounts = RelationshipFilter.new(current_account, filter_params).results.page(params[:page]).per(40)

app/controllers/follower_accounts_controller.rb
41:    @follows = scope.recent.page(params[:page]).per(FOLLOW_PER_PAGE).preload(:account)

app/controllers/following_accounts_controller.rb
44:    @follows = scope.recent.page(params[:page]).per(FOLLOW_PER_PAGE).preload(:target_account)

app/controllers/admin/roles_controller.rb
10:      @roles = UserRole.order(position: :desc).page(params[:page])

app/controllers/admin/relationships_controller.rb
12:      @accounts = RelationshipFilter.new(@account, filter_params).results.includes(:account_stat, user: [:ips, :invite_request]).page(params[:page]).per(PER_PAGE)

app/controllers/admin/accounts_controller.rb
12:      @accounts = filtered_accounts.page(params[:page])

app/controllers/admin/instances_controller.rb
56:      @instances = filtered_instances.page(params[:page])

app/controllers/admin/invites_controller.rb
8:      @invites = filtered_invites.includes(user: :account).page(params[:page])
21:        @invites = Invite.page(params[:page])

app/controllers/admin/custom_emojis_controller.rb
8:      @custom_emojis = filtered_custom_emojis.eager_load(:local_counterpart).page(params[:page])

app/controllers/admin/trends/statuses_controller.rb
8:    @statuses = filtered_statuses.page(params[:page])

app/controllers/admin/trends/links/preview_card_providers_controller.rb
7:    @preview_card_providers = filtered_preview_card_providers.page(params[:page])

app/controllers/admin/trends/links_controller.rb
8:    @preview_cards = filtered_preview_cards.page(params[:page])

app/controllers/admin/follow_recommendations_controller.rb
11:      @accounts = filtered_follow_recommendations.page(params[:page])

app/controllers/admin/trends/tags_controller.rb
7:    @tags = filtered_tags.page(params[:page])

app/controllers/admin/ip_blocks_controller.rb
8:      @ip_blocks = IpBlock.order(ip: :asc).page(params[:page])

app/controllers/admin/reports_controller.rb
9:      @reports = filtered_reports.page(params[:page])

app/controllers/admin/webhooks_controller.rb
10:      @webhooks = Webhook.page(params[:page])

app/controllers/admin/announcements_controller.rb
74:    @announcements = AnnouncementFilter.new(filter_params).results.reverse_chronological.page(params[:page])

app/controllers/admin/disputes/appeals_controller.rb
9:    @appeals = filtered_appeals.page(params[:page])

app/controllers/admin/statuses_controller.rb
62:      @statuses = Admin::StatusFilter.new(@account, filter_params).results.preload(:application, :preloadable_poll, :media_attachments, active_mentions: :account, reblog: [:account, :application, :preloadable_poll, :media_attachments, active_mentions: :account]).page(params[:page]).per(PER_PAGE)

app/controllers/admin/email_domain_blocks_controller.rb
8:      @email_domain_blocks = EmailDomainBlock.where(parent_id: nil).includes(:children).order(id: :desc).page(params[:page])

app/controllers/admin/action_logs_controller.rb
15:      @action_logs = Admin::ActionLogFilter.new(filter_params).results.page(params[:page])

app/controllers/filters/statuses_controller.rb
34:    @status_filters = @filter.statuses.preload(:status).page(params[:page]).per(PER_PAGE)

app/controllers/settings/login_activities_controller.rb
8:    @login_activities = LoginActivity.where(user: current_user).order(id: :desc).page(params[:page])

app/controllers/settings/applications_controller.rb
8:    @applications = current_user.applications.order(id: :desc).page(params[:page])
```

So it's indeed quite likely this could be the cause.

**Comment by renchap** [comment]
> If it is, `3.3.1` will fix it.

By any chance, do you know of an easy way to have a Ruby base Docker image with what will become 3.3.1?

Or are patch branches only created before release?

**Comment by casperisfine** [comment]
> By any chance, do you know of an easy way to have a Ruby base Docker image with what will become 3.3.1?

You have nightly builds in https://hub.docker.com/r/rubylang/ruby/tags

**Comment by renchap** [comment]
I dont think we should change the `.ruby-version`, as it would force people running `main` from git to install this version, which we know have issues. But we could add it explicitly to the CI?

**Comment by ClearlyClaire** [comment]
> I dont think we should change the `.ruby-version`, as it would force people running `main` from git to install this version, which we know have issues. But we could add it explicitly to the CI?

Now it has been added to the test matrix, this PR is about switching the default Ruby version to 3.3.0. Changing the PR's title accordingly.

Do we still have memory issues with Ruby 3.3.0?

**Comment by mjankowski** [comment]
> Do we still have memory issues with Ruby 3.3.0?

Yes, not production ready yet. Waiting on 3.3.1.

**Comment by larouxn** [comment]
> > Do we still have memory issues with Ruby 3.3.0?
> 
> Yes, not production ready yet. Waiting on 3.3.1.

Good news, Ruby 3.3.1 is out!

- https://github.com/ruby/ruby/releases/tag/v3_3_1
- https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/

**Comment by mjankowski** [comment]
Updated to use ruby 3.3.1, which was released today - https://github.com/ruby/ruby/releases/tag/v3_3_1

**Comment by larouxn** [comment]
Looks the like [CI failures on Ruby 3.2](https://github.com/mastodon/mastodon/actions/runs/8807961677/job/24176247327?pr=28013) are just network timeouts. Worth retrying the step/action.
Screenshot 2024-04-24 at 8 23 59

**Comment by mjankowski** [comment]
> Failures are not related to the PR and seem to be a github actions hosted runner global problem.

Seems widespread- https://github.com/actions/runner-images/issues/9733

I think we are ok code wise on 3.3.1, curious to see perf/memory results when people have tested in deploys.

**Comment by vmstan** [comment]
It's only been 12 hours but as I recall this was about enough time to see things go off the rails (pun intended) in memory usage with 3.3.0,  back when I was testing at the start of the year. So far things with 3.3.1 look pretty good (maybe even slightly better compared to 3.2.3) in terms of memory usage.

CleanShot 2024-04-24 at 08 16 51@2x

This is just cluster level memory usage across hosts running mostly Puma and Sidekiq workers, but blue chart line is average and it's building up to pretty expected levels.

Individual Sidekiq queues are holding steady. Currently configured with 24 threads, each process is showing 550-650MB consistently, which is what I was seeing with Ruby 3.2.3.

CleanShot 2024-04-24 at 08 24 23@2x

This is with the standard Dockerfile just built using the Ruby 3.3.1 image. YJIT is enabled, memory optimizations are the same.

**Comment by mjankowski** [comment]
Thanks, that definitely looks much more like what I'd expect than what you were seeing on 3.3.0. I'm guessing that whichever of the memory issues we were hitting was amongst the fixes in the 3.3.1 release.

**Comment by shleeable** [comment]
Love to see it.

**Comment by texpert** [comment]
Ryby 3.3.1 is broken with bootsnap - https://bugs.ruby-lang.org/issues/20450#change-108100

**Comment by mjankowski** [comment]
It's not clear to me from that ticket what the breakage is or how to verify that we have the issue... Is it any usage at all of 3.3.1<>bootsnap? Does it also require a specific gem? (if so, do we use that gem?) Is the breakage full breakage of the code, or just reduction/removal of bootsnap improvements?

**Comment by vmstan** [comment]
There is an execution of `bundle exec bootsnap precompile --gemfile app/ lib/` in the Dockerfile, which from what I can see runs without error under 3.3.1.

**Comment by vmstan** [comment]
As far as the memory usage issues from 3.3.0 are concerned, I think they've been cleared by 3.3.1. Overall usage continues to trend less than 3.2.3 over the same period of time, which is great. I did have to restart a couple of Puma pods for unrelated reasons (but not all the Sidekiq ones) and usage looks good.

CleanShot 2024-04-25 at 08 19 48@2x

**Review by renchap — APPROVED** [review]
Good for me if @vmstan says that the memory issues are solved.

I tried running this branch locally and have not been able to reproduce the bootsnap issues, so I am not sure where they come from? They do not seem to happen when the code is precompiled as we do it in the container image and they run fine…

**Comment by byroot** [comment]
The issue happens when requiring a "default gem" (shipped with ruby, essentially stdlib) that will be demoted to a bundled gem in 3.4 (still shipped with ruby but basically just a pre-installed gem).

The issue only happens if the gem in question isn't in the app gemfile, or required before the Bundler.require call.

Not sure about the context, but perhaps it's caused by some plugin or some modified install?

The backtrace should point to which gem is problematic.

**Comment by ClearlyClaire** [comment]
> Ryby 3.3.1 is broken with bootsnap - https://bugs.ruby-lang.org/issues/20450#change-108100

Is that something you encountered in Mastodon itself, or just a heads up that the issue exists elsewhere? If my understanding is correct, the CI would catch the issue for us, should we get ourselves in a situation where it can arise.

**Comment by mjankowski** [comment]
> The issue only happens if the gem in question isn't in the app gemfile, or required before the Bundler.require call.

Thanks for this clarification, that makes more sense and reminds me of previous issues we've solved by adding things to Gemfile to get rid of similar errors. Sounds like if our specs are passing we can safely conclude that we are not hit by this issue, and either aren't using the relevant gems and/or we have them in the Gemfile and they are required early enough that this bootsnap problem doesn't surface...?

**Comment by texpert** [comment]
> > Ryby 3.3.1 is broken with bootsnap - https://bugs.ruby-lang.org/issues/20450#change-108100
> 
> Is that something you encountered in Mastodon itself, or just a heads up that the issue exists elsewhere? If my understanding is correct, the CI would catch the issue for us, should we get ourselves in a situation where it can arise.

It was just a heads up.

**Comment by renchap** [comment]
Thanks for the additional context, not something we should care about then!

**Pull request merged**
