### PR TITLE
Fix NameError due to JsonldHelper

### PR DESCRIPTION
**Pull request by tribela**
Some system got this error, And this PR will fix that `NameError`
```
[2717270] ! Unable to load application: NameError: Couldn't find JsonldHelper, expected it to be defined in helpers/jsonld_helper.rb
bundler: failed to load command: puma (/home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/bin/puma)
NameError: Couldn't find JsonldHelper, expected it to be defined in helpers/jsonld_helper.rb
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/abstract_controller/helpers.rb:162:in `rescue in block in modules_for_helpers'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/abstract_controller/helpers.rb:155:in `block in modules_for_helpers'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/abstract_controller/helpers.rb:144:in `map!'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/helpers.rb:94:in `modules_for_helpers'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/abstract_controller/helpers.rb:108:in `helper'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_controller/railties/helpers.rb:19:in `inherited'
  /home/gurum/git/mastodon/app/controllers/application_controller.rb:3:in `<top (required)>'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:476:in `block in load_file'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:661:in `new_constants_in'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:475:in `load_file'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:373:in `block in require_or_load'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /home/gurum/git/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
```

### CODE REVIEW

**Comment by Kjwon15** [comment]
Even CI are failing because of this

**Comment by ThibG** [comment]
hm, weird, do you have any more info on the systems those issues are occurring on? Were they using a modified config or updated dependencies? I would have thought that having `JsonLd` defined as an acronym in `config/initializers/inflections.rb` prevented that error…

**Comment by ThibG** [comment]
I'd rather move the `config/initializers/inflections.rb` file to something like `config/initializers/0_inflections.rb`, but the issue is basically that application code gets loaded by the initializers, and I am not very comfortable with that.

**Comment by ThibG** [comment]
Closing this PR as we figured out why that was happening and I don't think this needs a change. Thank you.

**Pull request closed without merging**
