### PR TITLE
Add Sidekiq Prometheus Metrics Endpoint

### PR DESCRIPTION
**Pull request by mhamzahkhan**
There are probably better ways of doing this, and I was hoping if there is, people can advise how.

I am exposing metrics on /sidekiq_metrics, and using nginx to control who can access the page.

### CODE REVIEW

**Comment by Gargron** [comment]
I am afraid that exposing internal metrics at an endpoint that has to be explicitly hidden by modifying nginx configuration is not acceptable as a lot of admins will miss the memo. Also, since the desire for Prometheus metrics will likely not stop at Sidekiq defining a Sidekiq-only metrics endpoint is not future-proof.

**Comment by ykzts** [comment]
I'm using [statsd_exporter](https://github.com/prometheus/statsd_exporter). Does this not solve your request?

**Comment by mhamzahkhan** [comment]
Can statsd export sidekiq metrics?
Also, I'm not sure how it can be used when running mastodon in docker

**Comment by ykzts** [comment]
> Can statsd export sidekiq metrics?

Yes! It looks like this:

screenshot on Grafana

> Also, I'm not sure how it can be used when running mastodon in docker

If the UDP host and port provided by statsd_exporter are given to the Mastodon container in the form of the environment variable STATSD_ADDR, it works correctly.

**Comment by travnewmatic** [comment]
> If the UDP host and port provided by statsd_exporter are given to the Mastodon container in the form of the environment variable STATSD_ADDR, it works correctly.

statsd-exporter can listen listen on TCP and UDP.  Perhaps it would be nice to mention that mastodon is going to attempt to communicate via UDP?

spent a while troubleshooting until i determined that I had my statsd-exporter listening for the wrong protocol :)

**Pull request closed without merging**
