### PR TITLE
Add system specs for admin area `batch` actions

### PR DESCRIPTION
**Pull request by mjankowski**
First pass at adding coverage to the admin area controllers with `batch` actions. For almost of the controllers, this first pass is just exercising the "load the page and click a button" path, which then verifies the error that nothing was selected.

For the accounts controller, I also added some coverage of the different action options. Assuming this direction is fine and gets merged, I'll round out the missing actions for the other ones as well.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I'm not quite sure what's the difference between system tests and feature tests in this context, but we do have a few feature tests already and I think these new tests would fit there, without having to change RSpec's configuration. Otherwise this looks ok to me.

**Comment by mjankowski** [comment]
> I'd be happy to either a) update this PR and move them to features/, b) if this is merged in as-is, migrate the other feature specs to be system specs for consistency in future PRs -- let me know which direction is preferred.

@ClearlyClaire do you have an opinion or any guidance on this?

I'd love to get this one either accepted or rejected, and then evolve the system/features area in one of the directions discussed in the linked PR with the end-to-end specs.

**Comment by mjankowski** [comment]
Rebased against main and noticed a bunch of failures related to how the streaming server is enabled with the end-to-end stuff now.

Updated this PR to move all the additions into spec/features, which fixed those failures and (maybe?) makes this more mergeable now.

**Comment by renchap** [comment]
> Rebased against main and noticed a bunch of failures related to how the streaming server is enabled with the end-to-end stuff now.

Could you detail what was wrong here? It should not have impacted non-system tests 🤔

**Comment by mjankowski** [comment]
> Could you detail what was wrong here? It should not have impacted non-system tests 🤔 

In the original PR they were system specs. Latest commits move them back to features.

I didn't dig into the failures. Example: https://github.com/mastodon/mastodon/actions/runs/5931947135/job/16084923799

I still plan on doing some cleanup/consolidation after this is merged.

**Comment by ClearlyClaire** [comment]
Ah, sorry I missed those!

Yeah, we introduced system specs as end-to-end tests using selenium, so it makes sense to keep the distinction with feature tests.

I'm going to review this.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
