### PR TITLE
Add suggestion for secure cyphers to nginx.conf

### PR DESCRIPTION
**Pull request by gunchleoc**
Make it easier for admins to configure secure ciphers.

Since they are hard-coded, made it a suggestion only.

Follow-up to https://github.com/mastodon/mastodon/pull/26000

### CODE REVIEW

**Comment by renchap** [comment]
This is a good idea.

I think you could change the default to the Intermediate presets from the Mozilla generator: https://ssl-config.mozilla.org

And add a comment in the file linking to the generator, so people know where they come from.

**Comment by shleeable** [comment]
As a security idiot, I find myself in two minds.. but at the end of the day
1) People with older phones that don't support the latest ciphers deserve a base level of security, and nobody has ever been hacked for running TLS1.0 (unless they support the null cipher).
2) https is offering protection against people reading/injecting the fediverse traffic in motion, BUT, the actual toots from s2s and c2s should all be signed anyway on a message by message case... so that's offering you some authentication of the messages as well.

Chasing the highest TLS version and the best ciphers are great, but you need to remember that not everybody is rich and there might be a few people using older versions of windows or android that cannot use TLS 1.2 or 1.3

**Comment by renchap** [comment]
Can you cite any platform supporting TLS 1.0 but not TLS 1.2 that has more than 0.1% usage on a Mastodon instance?

This would be hitting the API because the frontend will not render on any device not supporting TLS 1.2.

Those TLS versions have been deprecated a long time ago, and for example the latest PCI-DSS standard (which every website where you enter a credit card needs to comply to) mandated TLS 1.0 to be disabled since 2020.

Any device not supporting TLS 1.0 and TLS 1.1 no longer have access to the vast majority of the internet, so there is no use in keeping those enabled. The Intermediate preset from the Mozilla configuration generator is in use my a huge number of websites, so it makes sense to stick to it.

Also, those are only a suggestion and any instance owner that wants to use outdated protocols can enable them if they want.

**Comment by shleeable** [comment]
Can you pull those stats from m.s? Maybe in <year of our lord here>, the actual numbers might show that the number of people on old hardware have upgraded beyond my argument (which was true in like 2015).

That said, Mastodon might have dropped support for older browsers anyway.. so my argument of supporting old stuff might be redundant regardless.

**Comment by shleeable** [comment]
The default nginx is TLS1.2/1.3 anyway... so we've dropped support for the actual protocol a long time ago

It's just the ciphers that are of interest to this PR.. so my comment is wrong.

**Comment by gunchleoc** [comment]
I have now added some more ciphers from the Mozilla tool. Thanks for the tip!

I have put the configuration live on my server, so you can see which browsers are supported here: https://www.ssllabs.com/ssltest/analyze.html?d=ailbhean.co-shaoghal.net&hideResults=on

Browsers that fail the handshake on that list are:

* IE <= 11
* Safari <= 8 (OSX <= 10.10, iOS <= 8.4)
* Android < 4.4.2

**Comment by renchap** [comment]
I think you should go further, and make the Mozilla intermediate configuration the default.

Those browsers are no longer supported by the Mastodon web app, and we should provide a secure default configuration.

**Comment by gunchleoc** [comment]
Done. I have deleted the old cipher set from the file.

**Review by renchap — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
