### PR TITLE
Fix “Back” button sometimes redirecting out of Mastodon

### LINKED ISSUE #25372: On first load, mastodon.social (advanced view) shows "back" link that goes nowhere
### Steps to reproduce the problem

I open https://mastodon.social .

### Expected behaviour

I expect to see three columns: Home feed, Notifications feed, "Getting Started" pane.

### Actual behaviour

The "Getting Started" column has a "BACK" link on it. But I just opened this window. There is nowhere to go back to.

### Detailed description

It looks like this

Screen Shot 2023-06-11 at 4 06 10 PM

If I click the "Back" link, it takes me (in the same column) to a search for nothing at all, and it says it "can not find anything for these search terms".

Screen Shot 2023-06-11 at 4 03 49 PM

Expected behavior: It should not do that.

### Specifications

I have seen this in Chrome on multiple computers. The server (m.s) is running v4.1.2+nightly-20230523 . I have been noticing this problem for the last day. I am *pretty sure* I never saw this problem before 2 days ago.

I use the "advanced" layout. I have not tried testing with the regular layout.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This handles both pushed and replaced states by overriding the `history.push` and `history.replace` in `app/javascript/mastodon/router.tsx` to manage a `fromMastodon` field in the state. When that field is set, we know going back is possible without leaving the interface.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
To actually fix this we need to properly handle `history.replace`. We may want to encode in the history state whether we are allowed to go back in the history, in such a way that `history.replace` would push it to the state and `history.push` would always allow it. Not sure how to best write it though.

**Comment by ClearlyClaire** [comment]
@renchap do you happen to know how we could cleanly hook into the right places to add a bit of logic and a bit of state in `router.history.replace` and `router.history.push` as described above?

**Comment by Signez** [comment]
> @renchap do you happen to know how we could cleanly hook into the right places to add a bit of logic and a bit of state in `router.history.replace` and `router.history.push` as described above?

If it can help, I had to add a few lines of logic on `push` calls in my recent pull request: [diff](https://github.com/mastodon/mastodon/pull/25893/files#diff-880f5e6d5e9498797cc0bee6b8444dd0893ace5a8f06a1cd01f25970c7b2d95cR247-R271). It basically consist on catching the legacy context at the `UI` component level, opening it there and patching the functions directly.

To be fair, this won't work any more as soon as `react-router` will be updated to `v5+` — those versions use modern contexts that we can't monkey-patch. For those versions, we can override the `history` object before providing it to the router: [this answer on StackOverflow](https://stackoverflow.com/a/73490873/2267902) illustrates that!

**Comment by ClearlyClaire** [comment]
@Signez thanks for the input! I think I addressed the issue for good this time by building upon your `router.tsx`.

This works for now, but if possible, it is probably better to define `History.LocationState` globally to be `MastodonLocalState | undefined`, which I have not managed to do (I am very new to Typescript)

**Review by renchap — APPROVED** [review]

**Comment by renchap** [comment]
> This works for now, but if possible, it is probably better to define `History.LocationState` globally to be `MastodonLocalState | undefined`, which I have not managed to do (I am very new to Typescript)

I think you can achieve it with something like this in `types/react_router.d.ts`:

```ts
import 'history';

interface MastodonLocationState {
  fromMastodon?: boolean;
  mastodonModalKey?: string;
}

declare module 'history' {
  namespace History {
    export type LocationState = MastodonLocationState;
  }

  export type LocationState = MastodonLocationState;
}
```

But it is not really useful at the moment, as the context can not be typed and React Router does not expose correct Prop Types.

This can be improved later, when we upgrade to React Router 5 and start using React Router in Typescript.

**Comment by ClearlyClaire** [comment]
> I think you can achieve it with something like this in `types/react_router.d.ts`:

That does not seem to work, `History.LocationState` is still considered to be of type `unknown`.

**Pull request merged**
