### PR TITLE
Fix request URL normalisation for bare domain and 8-bit characters

### PR DESCRIPTION
**Pull request by c960657**
As mentioned in https://github.com/mastodon/mastodon/pull/26219#issuecomment-1660761265 we need to normalise an empty path to `/`.

I realised that `expect(a_request(:get, 'http://...')).to have_been_made` is not a reliable way to check exactly what was sent over the wire. The URLs are both normalised before being compared, and that defeats the purpose for this test. So I have added tests for `response.request.headline` (.e.g `GET / HTTP/1.1`) instead.

This change to the tests revealed that the new normaliser does not encode 8-bit characters. 8-bit characters are not permitted in URLs according to RFC 3986, but they sometimes occur in user input. They are not permitted raw in the HTTP request line either, so they _must_ be dealt with.

\*sigh* I hope this issue will be fixed in http.rb or Addressable, so we don't have to reinvent this wheel.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]
That *looks* ok, or at least better than the current `main`, but I'm not super comfortable with all of this, there are lots of edge cases and I'm not sure I can spot all of them.

I'd be more comfortable with reverting to old behavior—save for the `query` normalization, for consistency with what `http.rb` does.

**Comment by c960657** [comment]
I understand your concern. It would be much cleaner to delegate this to a separate library.

I am not so concerned about edge cases, though. Passing on the URL as-is shouldn't be a big issue. This is what most HTTP clients do.

For the record, we need to bypass the default normalisation for both path and query.

Note that fixing invalid URLs and normalising URLs are two different issues. I don't think `Request` should do the former, so on second thought I kind of regret the introduction of `encode_non_ascii` in this PR. I think it would be cleaner to just pass invalid URLs as-is or even raise an exception. If a URL needs “fixing” in order to be valid, I think this should be done outside `Request`. Invalid URLs usually come from user input – a URL mentioned e.g. in an Open Graph tag should also be valid and should never need “fixing”.

**Comment by c960657** [comment]
I'll try to make a PR for http.rb.

**Comment by c960657** [comment]
PR for http.rb: https://github.com/httprb/http/pull/758

**Pull request merged**
