### PR TITLE
Allow streaming to connect to postgress with self-signed certs

### PR DESCRIPTION
**Pull request by ramuuns**
Currently, if you run your mastadon instance on e.g. DigitalOcean and use their managed postgres offering for the database, in order to be able to connect you need to manually patch streaming/index.js in order for it to be able to talk to the database.

Here is an example patch: https://github.com/rasca/mastodon/commit/f6d6bf19b59bb2d27ac7d3499466fc64c6503ef9

Now it turns out that the problem is that we're rolling our own postgres connection string parsing, instead of using the one provided by the library, which actually suppors everything we do and more and also happens to be signature-compatible with our own function, so it seems trivial to replace.

After this patch, it should be possible to simply properly set the configuration string to e.g.
```
DATABASE_URL=postgresql://user:password@host:port/mastodon_production?sslmode=no-verify&ssl=true
```
and drop the (fragile) workarounds.

That said, it should be noted, that DigitalOcean provides the conenction string with `sslmode=require`, so it should still be documented somewhere that the users of this need to change it to be `sslmode=no-verify` instead

### CODE REVIEW

**Comment by ineffyble** [comment]
@ramuuns There is an alternative to the patch you described, which is passing the Digital Ocean certificate and telling Node to trust it. 

What worked for another user recently is:

```
NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/do-db-certificate.crt
```

(obviously the path needs to be where the certificate file has been put).

Not to say that this change might not be a good one, although it's a little more secure to keep the SSL host verification.

**Comment by ramuuns** [comment]
@ineffyble, that option didn't come up in any of the google searches I did recently, however I did try it just now and at least that helped me to get rid of the ugly hack, so thanks :). 

That said, I am of the belief that postgres connection string parsing should not be a hand-rolled partial implementation of something that the "official" library already provides. I mean it feels odd for the streaming client to even concern itself with such things and keeping it might lead to further additional surprises (from the perspective of people who operate postgres) in the future.

**Review by ykzts — APPROVED** [review]

**Comment by bocan** [comment]
Not sure if this is related but my streaming server is failing with:

```
TypeError: Cannot read properties of undefined (reading 'charAt')
    at parse (/opt/mastodon/node_modules/pg-connection-string/index.js:13:11)
    at startWorker (/opt/mastodon/streaming/index.js:109:60)
    at throng (/opt/mastodon/node_modules/throng/lib/throng.js:25:12)
    at /opt/mastodon/streaming/index.js:1276:3
    at Server.<anonymous> (/opt/mastodon/streaming/index.js:1263:36)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1857:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
WARN Starting worker 2
/opt/mastodon/node_modules/pg-connection-string/index.js:13
  if (str.charAt(0) === '/') {
          ^
```

**Comment by Hanage999** [comment]
@bocan You can avoid the error by setting the DATABASE_URL environment variable in .env.production. Just translate the variables below into the form of a postgresql url.

https://github.com/mastodon/mastodon/blob/aa98c8fbeb02fecac2681464fd7c0445deb466b1/.env.production.sample#L24-L30

**Comment by Gargron** [comment]
Well, that’s not very backwards compatible

**Comment by Hanage999** [comment]
The code below needs changing so that it works without DATABASE_URL set, but it's beyond my skill...

https://github.com/mastodon/mastodon/blob/aa98c8fbeb02fecac2681464fd7c0445deb466b1/streaming/index.js#L109-L113

**Comment by bocan** [comment]
Thanks @Hanage999.  That'll get me back up and running.  I should have read the description above a bit more closely.  That said, surely it's going break a LOT of people's systems if they're running on the git-edge like I do.

**Comment by claus** [comment]
I am one of those users on DigitalOcean with managed postgres, and i used to have streaming/index.js patched.

I just updated to 4.2 and got rid of the patch, which mostly works, except for the streaming server.

I then changed my DATABASE_URL to have `?sslmode=no-verify&ssl=true` instead of `?sslmode=require&ssl=true` and when i restart services i get a 500 on `/` - nothing works anymore.

What am i doing wrong?

Can all this be added to the docs?

**Pull request merged**
