### PR TITLE
Do not add margin-right when opening modal on mobile

### PR DESCRIPTION
**Pull request by ykzts**
There is hasn't scrollbar on mobile, so there is no need to add a margin-right for the scrollbar.

### CODE REVIEW

**Comment by Gargron** [comment]
Wouldn't the scrollbar test return `0` on mobile? Width-based mobile detection includes small browser windows that do have non-zero scrollbars...

**Comment by ykzts** [comment]
If `-webkit-scrollbar` is specified, scrollbars will be added to elements with `overflow: scroll` even on mobile.

**Comment by Gargron** [comment]
But do webkit scrollbars take up width in the container? At least visually they are overlaid over the content rather than pushing it.

**Comment by ykzts** [comment]
https://github.com/tootsuite/mastodon/blob/c00ab575b7450f133946fb94d7367b5d810a2d89/app/javascript/styles/mastodon/components.scss#L2132

The container scrollbar is not displayed on mobile. This is controlled by CSS.

**Comment by Gargron** [comment]
What I am confused about is: Doesn't `getActualScrollbarWidth()` return 0 *anyway* when scrollbar is not displayed on mobile?

**Comment by ykzts** [comment]
I feel something is wrong (browser bug?)

| iPhone | Android |
|--------|---------|
| iphone | android |

https://codepen.io/ykzts/pen/BaBqMdp

**Review by Gargron — APPROVED** [review]

**Pull request merged**
