### PR TITLE
Add limited status icon and mention list

### PR DESCRIPTION
**Pull request by noellabo**
The limited visibility that has been considered private until now is displayed as an icon.

fifth_visibility_status

Limited visibility is a status visibility that includes audiences that are not explicitly mentioned, and is targeted to specific users just like Direct, but it is displayed on the home timeline and account timeline. However, because no special support for limited was defined, it was treated like private until now, and it was indistinguishable.

limited is a silent mention, you can show that it's limited, but you can't know who the post is for anyone other than yourself.

The ability to make limited posts on Mastodon is proposed in https://github.com/tootsuite/mastodon/pull/14354

### CODE REVIEW

**Comment by ThibG** [comment]
Introducing the `limited` visibility might break third-party clients

**Comment by Gargron** [comment]
I am not decided on whether allowing people to know that the post is targeted at a circle and not at all followers is a good thing.

**Comment by noellabo** [comment]
For compatibility, visibility remains unchanged from before and the limited flag has been added.

Do not merge this PR until you have decided to signal limited.

**Comment by ThibG** [comment]
I think at the very least the poster should know, and they should be able to know *which* circle they posted to. I think—but I'm not entirely sure—that it's fine for recipients to know they've received it because they were part of a circle, but they shouldn't know which one. But the whole thing's usability depends on how replies will be handled, tbh, and for now… i'm not too sure how they should be…

**Comment by Gargron** [comment]
On Google Plus you did not know that you saw a post because you were in a circle. That would be dangerous, I think. This feature must have plausible deniability because the reasons people might have for circles can be less than favourable to the people in those circles. Maybe the author should see the circle it was posted to, but the thing is, once it's posted, the circle doesn't matter anymore because even if you add/remove people from the circle it will not affect already published posts.

**Comment by ThibG** [comment]
Honestly, not being able to know whether I posted something to all my followers or only a given circle would be a pretty big issue. I personally would not be able to keep track of that, and many people have worse memory or attention than I do.

As for people not knowing they received it because they're part of a circle, yeah, that's a bit of an issue (although I'd say in most case the less than favourable reasons would be for *not* being in a circle, but I can see it going both ways).

**Comment by noellabo** [comment]
Currently, the status of direct visibility is not displayed on the home timeline. How about changing the background of limited visibility status in the same way as direct by using this in reverse? The difference from private is easier to understand.

limited_visibility_status

**Comment by noellabo** [comment]
The list of accounts mentioned by posters can be displayed from the circle icon.

```
GET /api/v1/statuses/:id/mentioned_by
```
Returns a list of accounts, similar to rebloged_by, favourited_by. If you are not the poster yourself, you will fail.

limited_status_icon_and_mentioned_accounts_list

**Pull request closed without merging**
