### PR TITLE
Additional AI bot coverage in robots.txt (round 1)

### PR DESCRIPTION
**Pull request by shleeable**
We need to reach consensus around what is a AI bot and what is a crawler.... because indexing is generally handled by the admin in the instance settings.

### CODE REVIEW

**Comment by shleeable** [comment]
Mastodev, I think this is ready for review.

**Comment by brookmiles** [comment]
I don't think you can just list all of the user agents and only apply a single Disallow at the end...

My expectation from the current format is that only the final user agent "Claude-Web" will be disallowed, as all of the other entries are essentially "empty".

```
User-agent: ...
User-agent: ...
User-agent: ...
User-agent: anthropic-ai
User-agent: ClaudeBot
User-agent: Claude-Web

Disallow: /
```

**Comment by brookmiles** [comment]
> as per https://datatracker.ietf.org/doc/html/rfc9309#section-2.1 Groups are allowed by the RFC.

Interesting, you're right. I don't think I've ever seen one structured that way before.

**Comment by shleeable** [comment]
Mastodev, I think this is ready for review.

354268442-429239ae-c7af-4f2e-b2fc-3822d92beffe

**Comment by mjankowski** [comment]
I think I'm thumbs down on this ... feels like an eminently reasonable thing to do per-server if desired, but I'm not sure being a core project default makes sense:

- Some servers may not want these rules
- We'll be playing whack-a-mole with the list

How about a documentation PR that makes it clear how you might go about customizing this setting, along with links to one/some of the various "here's a database of AI crawlers" projects?

**Pull request closed without merging**
