### PR TITLE
Reword and rearrange Content Retention page

### PR DESCRIPTION
**Pull request by vmstan**
Community feedback has been that the current Content Retention page under 'Administration > Server settings > Content retention' is confusing for administrators (even after some changes in Mastodon 4.2) and that the risks of using the current "Content cache retention period" are not fully explained or understood.

Screenshot 2023-11-04 at 4 59 18 PM

This has led to many incidents where administrators inadvertently are deleting conversations and interactions between their local users and users from remote systems.

https://mastodon.gamedev.place/@aras/111351365012735094
https://lapcatsoftware.com/articles/2023/10/1.html
Content cache retention period #27677

As explained by @Gargron in the project Discord, this feature was requested and intended for usage by EU governments to prevent all retention of non-local data, not for general use by Mastodon administrators to manage database size. Tools like `tootctl statuses remove` do this job by also accounting for user interaction with the remote content. However per @ClearlyClaire this has a high compute cost and it is not desirable to run this on a schedule or as initiated in the UI.

This PR attempts to addresses these issues by:

- Not referring to this feature as a cache, as that would imply the ability to restore the data when requested again as the media cache is able to do
- Making the warning for enabling this feature more clear about the impacts to user data
- Moving it to a separate section to indicate its importance. It's currently marked Danger Zone.
- Clean up the description for the remaining two media cache and user archive features to better explain their functions.

Screenshot 2023-11-06 at 10 56 57 AM

### CODE REVIEW

**Comment by rrgeorge** [comment]
Due to this setting still being misunderstood, I think the warning should be more explicit that replies and @-mentions will be removed, such as:
> All posts and boosts from other servers will be deleted after the specified number of days, without regard to any local user interaction with those posts, including bookmarks or favorites. Private and public messages between local users and users from different instances, including replies and @-mentions, will also be lost and impossible to restore.

**Comment by brookmiles** [comment]
- Suggest changing "Remote content retention period" to "Remote post storage period".  Both "content" and "retention", while accurate, are more jargon-y and imo less clear about what's happening.
- Make it red :)

Shortened it up a bit, and changed "instance" to "server" (I think that's the project's preferred term now?):

> ALL posts from other servers (including boosts and replies) will be deleted after the specified number of days. This includes posts marked as a bookmark or favourite by local users. Private mentions from users on different servers will also be lost and impossible to restore. This setting is intended for special purpose servers and most servers SHOULD NOT use this setting.

**Comment by vmstan** [comment]
> * Suggest changing "Remote content retention period" to "Remote post storage period".  Both "content" and "retention", while accurate, are more jargon-y and imo less clear about what's happening.
> * Make it red :)
> 
> Shortened it up a bit, and changed "instance" to "server" (I think that's the project's preferred term now?):
> 
> > ALL posts from other servers (including boosts and replies) will be deleted after the specified number of days. This includes posts marked as a bookmark or favourite by local users. Private mentions from users on different servers will also be lost and impossible to restore. This setting is intended for special purpose servers and most servers SHOULD NOT use this setting.

I would agree about "Remote post" but not so much on retentions, as that's the terminology used for the other settings and it's the "Content Retention" page.

As for the color, there is a red "Not recommended" label that I would like to set which is accessible on other pages but when I tried didn't work.

> All posts from other servers (including boosts and replies) will be deleted after the specified number of days, without regard to any local user interaction with those posts. This includes posts which have been bookmarked or favorited by your users. Private mentions between your users and those from different instances will also be lost and impossible to restore. Enabling this setting breaks many user expectations when implemented, and should be done only by servers with a need to limit all storage of remote user posts.

**Comment by shleeable** [comment]
On principle, this is a good chance considering it causes so many problems... but I'd really wonder why this is in the portal at all?

Shouldn't a rare feature that only 0.1% of instances need to use.. just be a ENV value?

**Review by ClearlyClaire — DISMISSED** [review]

**Comment by renchap** [comment]
The issue with `ENV` values is that they can not be set by an admin, and this is an issue when you use an hosting platform for your instance.

And if we remove it from here, we need to have handle the migration path to an `ENV variable, so people who want to keep it do not inadvertently disable it.

As this is definitely not a recommended setting, I wonder if we should think of a way to have admins confirm they really want it when they update to 4.3. Not sure how, maybe with the new (not-yet implemented) server-generated announcements?

**Comment by VladlenO** [comment]
How can it turn out like in this video?  This is an obvious bug.  There are recordings (!!!!!!) https://digic.cloud/s/y5Dz4gLrKsrnKgy

 Second point: the first point is that the cache will be loaded on demand.  This does not work(!!!).  Link preview doesn't work.  This is an obvious bug.

**Comment by vmstan** [comment]
On your second point, based on https://docs.joinmastodon.org/admin/tootctl/#preview_cards-remove my understanding is if your media cache retention is less than 14 days it would cause issues with preview cards cache being rehydrated. We should probably call that out in the interface.

**Comment by vmstan** [comment]
There is a separate issue for your request, please keep the discussion here relevant to the PR. @VladlenO

**Comment by VladlenO** [comment]
> There is a separate issue for your request, please keep the discussion here relevant to the PR. @VladlenO

Sorry, can you be more specific?  English is not my native language.  Thank you.

**Comment by FediVideos** [comment]
Should the warning also make clear that this feature isn't intended for normal servers? That it's just a niche setting intended for announcement servers? (Or something along those lines?)

**Comment by nemobis** [comment]
> All posts from other servers (including boosts and replies) will be deleted

This is an improvement but it still downplays the issue. It's not just the remote posts being deleted, but also the local interactions with them (likes and bookmarks). So I'd suggest something like:

> All local references to posts from other servers (such as bookmarks, favorites and replies) will be deleted,  irreversibly. Local copies of posts from other servers will also be deleted (until any future interaction), without regard to any past local user interaction with those posts. Local users will lose all their bookmarks or favorites, except for local posts. Private mentions between users from different instances will also be lost and impossible to restore. Use of this setting is intended for special purpose instances and breaks many user expectations when implemented for general purpose use.

**Review by ClearlyClaire — DISMISSED** [review]

**Comment by vmstan** [comment]
> > All posts from other servers (including boosts and replies) will be deleted
> 
> This is an improvement but it still downplays the issue. It's not just the remote posts being deleted, but also the local interactions with them (likes and bookmarks). So I'd suggest something like:
> 
> > All local references to posts from other servers (such as bookmarks, favorites and replies) will be deleted,  irreversibly. Local copies of posts from other servers will also be deleted (until any future interaction), without regard to any past local user interaction with those posts. Local users will lose all their bookmarks or favorites, except for local posts. Private mentions between users from different instances will also be lost and impossible to restore. Use of this setting is intended for special purpose instances and breaks many user expectations when implemented for general purpose use.

@nemobis the current state of the message is as such:

_All posts from other servers (including boosts and replies) will be deleted after the specified number of days, without regard to any local user interaction with those posts. This includes posts where a local user has marked it as bookmarks or favorites. Private mentions between users from different instances will also be lost and impossible to restore. Use of this setting is intended for special purpose instances and breaks many user expectations when implemented for general purpose use._

CleanShot 2024-03-12 at 09 36 00@2x

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
