### PR TITLE
Fix inconsistent wording in import/export settings

### PR DESCRIPTION
**Pull request by c960657**
I made some consistency changes to the wording in the _Import and export_ section in settings.

I think consistency in UI texts is important. If multiple terms are being used interchangably about the same concept, end-users may be confused, and it also makes translating the software more difficult. When you are new to Mastodon, there are plenty of new things to learn (instances, federation, multiple mobile apps, etc.), so there is no need to confuse matters more. In longer texts you can express yourself more freely, but UI labels should be brief and consistent.

The changes are:
- Rename “_Import and export_” to “_Export and import_” to reflect that you must first export your data, then import it (elsewhere). And reverse the order of menu items, so that _Export_ comes first. 
- ~When clicking on _Import and export_ menu item to expand it, open the first submenu item (_Import_). Currently the second item is open which is rather odd.~
- Keep _Import_ menu item highlighted (`highlights_on: :subpath`) on the confirmation page shown when trying to import a list of mismatching type, e.g. importing mutes as blocks.
- ~Rename “_Export data_” to just “_Export_” for consistency with _Import_. Menu item labels should be brief, and “data” is somewhat redundant in this context.~ (fixed in #32099)
- Reorder export items so they follow an order resembling that used in the account context menu in React app (below the top left search field).
- Consistently use the term “user” instead of ”account”. We are generally not consistent on this, but it seems “users” is the prevalent term, especially in end-user-facing UI.
- Likewise, consistently use the same terms as in the React app: “followers”, “following”, “muted users”, “blocked users”, “blocked domains” etc. [1]
- Avoid the word “list” for the individual options in the import dropdown, e.g. change “Blocking list” to “Blocked users”. This is redundant – everything here is lists.
- Change `followed_accounts.csv` to `following.csv` in the URLs and filenames of the exported CSV files so all types use the same terms as in the API, i.e. [followers](https://docs.joinmastodon.org/methods/accounts/#followers),[following](https://docs.joinmastodon.org/methods/accounts/#following), [mutes](https://docs.joinmastodon.org/methods/mutes/), [blocks](https://docs.joinmastodon.org/methods/blocks/), [domain_blocks](https://docs.joinmastodon.org/methods/domain_blocks/) (a different approach would be following the UI labels, i.e. `muted_users.csv`etc.).

I did not touch the header names in the CSV files. This has some BC issues, so I think this should be dealt with separately.

[1] Re “following”:
This word is a bit unusual, because it is used somewhat like a plural word meaning “followed users”. But this is what we use elsewhere. In particular, the word “follows” (plural noun) is generally not used in UI texts. Distinguishing following and followers is generally confusing, so in pages like these where space is not limited, we could use more elaborate terms, e.g “users you follow” and “users who follows you”. I like that idea.

image

image

### CODE REVIEW

**Comment by gunchleoc** [comment]
I have tested this and I like it. There's one change I'd make though: The export process will be used more frequently than the import process, so rather than selecting Import by default, I'd switch the 2 menu items and call the menu category "Export and import"

- **Export and import**
  -  **Export**
  - Import

**Comment by c960657** [comment]
Good point. Also, from a chronological viewpoint, export comes before import. You must first export your data, before you can import it.

**Comment by mjankowski** [comment]
This needs a rebase. I think at least portions of this make sense -- I wonder if chopping it up would make review more likely?

**Comment by c960657** [comment]
> I wonder if chopping it up would make review more likely?

You are probably right.

First PR: #33032

**Comment by c960657** [comment]
Second PR: #33032

**Pull request closed without merging**
