### PR TITLE
Install python3 when building with Docker

### LINKED ISSUE #17794: Docket AMD64 build error - not fatal
```
#22 242.9 warning Error running install script for optional dependency: "/opt/mastodon/node_modules/bufferutil: Command failed.
#22 242.9 Exit code: 1
#22 242.9 Command: node-gyp-build
#22 242.9 Arguments: 
#22 242.9 Directory: /opt/mastodon/node_modules/bufferutil
#22 242.9 Output:
#22 242.9 gyp info it worked if it ends with ok
#22 242.9 gyp info using node-gyp@9.0.0
#22 242.9 gyp info using node@16.13.2 | linux | arm64
#22 242.9 gyp ERR! find Python 
#22 242.9 gyp ERR! find Python Python is not set from command line or npm configuration
#22 242.9 gyp ERR! find Python Python is not set from environment variable PYTHON
#22 242.9 gyp ERR! find Python checking if \"python3\" can be used
#22 242.9 gyp ERR! find Python - \"python3\" is not in PATH or produced an error
#22 242.9 gyp ERR! find Python checking if \"python\" can be used
#22 242.9 gyp ERR! find Python - \"python\" is not in PATH or produced an error
#22 242.9 gyp ERR! find Python 
#22 242.9 gyp ERR! find Python **********************************************************
#22 242.9 gyp ERR! find Python You need to install the latest version of Python.
#22 242.9 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#22 242.9 gyp ERR! find Python you can try one of the following options:
#22 242.9 gyp ERR! find Python - Use the switch --python=\"/path/to/pythonexecutable\"
#22 242.9 gyp ERR! find Python   (accepted by both node-gyp and npm)
#22 242.9 gyp ERR! find Python - Set the environment variable PYTHON
#22 242.9 gyp ERR! find Python - Set the npm configuration variable python:
#22 242.9 gyp ERR! find Python   npm config set python \"/path/to/pythonexecutable\"
#22 242.9 gyp ERR! find Python For more information consult the documentation at:
#22 242.9 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#22 242.9 gyp ERR! find Python **********************************************************
#22 242.9 gyp ERR! find Python 
#22 242.9 gyp ERR! configure error 
#22 242.9 gyp ERR! stack Error: Could not find any Python installation to use
#22 242.9 gyp ERR! stack     at PythonFinder.fail (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#22 242.9 gyp ERR! stack     at PythonFinder.runChecks (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#22 242.9 gyp ERR! stack     at PythonFinder.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#22 242.9 gyp ERR! stack     at PythonFinder.execFileCallback (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#22 242.9 gyp ERR! stack     at exithandler (node:child_process:404:5)
#22 242.9 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:416:5)
#22 242.9 gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
#22 242.9 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
#22 242.9 gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
#22 242.9 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#22 242.9 gyp ERR! System Linux 5.11.0-1028-azure
#22 242.9 gyp ERR! command \"/opt/node/bin/node\" \"/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
#22 242.9 gyp ERR! cwd /opt/mastodon/node_modules/bufferutil
#22 242.9 gyp ERR! node -v v16.13.2
#22 242.9 gyp ERR! node-gyp -v v9.0.0
#22 242.9 gyp ERR! not ok"
#22 242.9 info This module is OPTIONAL, you can safely ignore this error
#22 243.0 warning Error running install script for optional dependency: "/opt/mastodon/node_modules/utf-8-validate: Command failed.
```

### PR DESCRIPTION
**Pull request by ykzts**
Resolve #17794

### CODE REVIEW

**Comment by shleeable** [comment]
Thanks.

**Comment by shleeable** [comment]
Still good to merge.

**Comment by shleeable** [comment]
also this issue is fixed in #16244 - So this PR can be closed once that's merged in.

**Comment by ykzts** [comment]
@Gargron I would like to have this change merge as it affects Docker build speed.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
