### PR TITLE
Change hashtags at the end of the post to render out-of-band

### PR DESCRIPTION
**Pull request by Gargron**
People will often put all of the hashtags relevant to the post at the end of the post, but it looks spammy. Others avoid using hashtags this way because it looks spammy, and therefore lose out on discoverability. Since hashtags on Mastodon are out-of-band on the protocol and API level anyway, we can continue to allow them to be input the usual way but render them out-of-band in a more clean manner.

Screen Shot 2023-08-06 at 21 38 23

___

Fixes MAS-141

### CODE REVIEW

**Comment by Cassolotl** [comment]
This is going to cause a lot of confusion before *Show mention of the followed hashtag #19528* is resolved!

**Comment by woozalia** [comment]
This does seem problematic if done automatically and without any choice.

As a better and more useful solution, how about *markup to hide stuff* -- either like Discord spoilertext or as an icon/emoji you can click to reveal? That would allow the same essential functionality while enabling greater user agency.

Actually, there are at least three useful modes for content-hiding:
* **spoilertext** - like Discord's ||hide this|| markup: preserves size/layout of text
* **hide-icon** - replace marked text with an icon/emoji which can be clicked to reveal it
* **dropdown** - like `<lj-cut>`, allowing multiple CWs per post; currently supported in HTML by, the `<detail>` and `<summary>` tags: shows an author-provided summary with an icon which you click to see the full content

Also, if we're fixing hashtags:
* There should be markup for "link to hashtag stream but don't include this post" (so people can maintain hashtag lists without spamming the hashtags they're listing)
* Hashtags in user profiles should result in those profiles being listed on the page for that hashtag.

**Comment by nononymousse** [comment]
+1 on letting the user have the choice. always left choices for peoples. specially on something this important and that will lean to a lot of confusions

**Comment by averixus** [comment]
Is there _any_ precedent in any other social media context where user-written tags are completely, 100% hidden to readers? Am I actually misunderstanding the summary of this change? Because it seems like a completely un-requested and incomprehensible feature, I can't think of any reason it would be a good idea.

**Comment by rkingett** [comment]
Having an option to show these hashtags, rather than having users hide hashtags, controlled by user, would be better, as I actually do want to see all hashtags sometimes and follow more hashtags than groups/people and this will be one way to give users more agency, also, [this comment pointed out something that probably should be tackled first or in addition](https://github.com/mastodon/mastodon/pull/26260#issuecomment-1657201225)

**Comment by fabioromeo** [comment]
I get that hashtags could be annoying, but they're also an useful tool for discoverability. Instead of just invisible, it could be hid by default under a "tags" button, coupled with a setting toggling its visibility, allowing each user to decide if they want that or not. 

Just cutting them off is plain wrong.

**Comment by vidarlo** [comment]
This is bad for discoverability. Showing hash tags means it's easy to drill down into interesting topics that you stumble upon, and shows what hashtags the community at large is using. Hiding is effectively harming usability of the software, and makes getting to know the fediverse harder, and makes introduction into new communities more difficult.

This doesn't sound like a good solution to me.

**Comment by MadokVaur** [comment]
> Is there _any_ precedent in any other social media context where user-written tags are completely, 100% hidden to readers? Am I actually misunderstanding the summary of this change? Because it seems like a completely un-requested and incomprehensible feature, I honestly can't think of any reason it would be a good idea.

Going to drop in very briefly to mention that someone (won't doxx him) spun up a Mastodon fork on a single-user instance and began posting into my (and others I'm sure) Home feed with no visible connection to any of the participants. Took me a while to figure out what was going on. He was posting in response to Followed hashtags with his own hashtags set as non-printing/visible. I challenged him as to what he was doing and he dropped out and went dark. It could, however, make a confusing mass-reach vector for all sorts of mischief. /EOF

**Comment by rrgeorge** [comment]
This seems like a terrible idea, it will just be abused to spam hashtags. It’s already confusing enough for people that follow hashtags not knowing why a post is in their timeline. Also, there is no mention of MAS-141 on the public roadmap, so it’s unclear what problem this is fixing.

**Comment by eslerm** [comment]
@Gargron what is MAS-141?

Is that tracking system public? The above reviews should be in that bug report instead of a PR.

**Comment by belaset** [comment]
If there were an option to show/hide hashtags, I would choose to SHOW them because that's how I discover new tags, new fun things, new groups, new topics, new people. Why would I NOT want to see tags?

**Comment by jonpincus** [comment]
As others have pointed out, this seems like it will have a lot of problematic consequences.  

What problem is this trying to address, and is there a different way to address it?

**Comment by danShumway** [comment]
I'll go to bat for the idea behind this feature, but not this specific implementation.

----

Visible-by-default hashtags are likely a large contributor to the number of people who don't use tags on Mastodon and it limits their usefulness both as a categorizing tool and as a blocking/filtering tool.

A couple of use cases:

- It would be good to be able to tag jokes or sarcasm with `#joke` or `#sarcasm` so that they're easier to search and so that they can reduce confusion for users who don't initially understand what's going on. But the inclusion of those tags will spoil the joke for most readers. Hiding them by default solves that problem.

- Subjectively, I suspect that many users find hashtags to be ugly or equate them subconsciously with Twitter spam, which makes them less likely to tag their posts. Hiding tags by default might be a way for them to get over that "shame". I suspect there are posters who want their posts to be searchable and still don't tag them just because they think the tags look ugly.

- For artists, it would be good to include descriptive numbers of tags on their photos/videos/media. That means more than one or two, it means tags that actually categorize what is going on in the artwork; and doing that is going to be a huge visual mess. Of course artists that don't want their artwork to show up in lists or be searchable might not use tags, but many artists are not going to fall into that bucket -- it is good for them to be able to attach *dozens* of tags to the same picture because that's just how most artists tag artwork. You're thorough, the tags are meant to be comprehensive. Mastodon's current tag visibility discourages this practice.

- To expand on that idea, people often only include (subjectively) too few tags even in pure-text posts. So this may be a controversial idea and I may be in a minority saying this, but the idea of tag "spam" is a holdover from Twitter, it stems from how broken Twitter's tagging system was (is? I have no idea what the heck Musk is doing there now). In most systems, you want lots of tags in posts. You don't want *inaccurate* tags (that's a separate conversation), but you want enough tags to describe what the post is talking about. And this is especially the case in Mastodon where search is entirely tied to tags. Tags are how discoverability works in Mastodon. I know there are people who would disagree with me saying this, but as long as the tags are accurate it is desirable for people to "spam" tags.

----

Content filtering also *heavily* suffers because of visible-by-default tags:

Tags are also a useful way to allow users to easily filter topics that don't really deserve content warnings in most cases but may be triggering to some readers (`#politics`, `#sickness`, `#bugs`, etc). From what I've seen on Mastodon (maybe I'm just looking at the wrong circles) tags are rarely used that way; instead posters rely solely on content warnings and have debates about what topics need warnings. These debates rarely go well and they contribute to the (admittedly often undeserved) reputation among non-Mastodon users that the network feels hostile or unwelcoming when it comes to policing posting behavior.

A large number of debates about content warnings in front of value-neutral topics like `#bugs` stem entirely from the (subjective) value statement that putting a post behind a content warning implies. I've seen etymologists refuse to put content warnings in front of posts with bugs because (in their words) their entire life's work is in some ways about pushing back against social stigma against bugs, and they refuse to reinforce that stigma. I've also seen people say the same thing about content warnings in front of discussions of mental health, and I have a hard time disagreeing with their argument that it's harmful to imply that their visible existence is something that needs a warning in front of it.

Tags neatly sidestep this entire issue (tagging a post does not reinforce a social stigma) and encouraging more tag use instead of relying so heavily on content warnings would probably get rid of a huge number of arguments around content warnings. But tags are rarely used in these situations specifically because they make posts look ugly and hard to read. Hiding tags by default solves that problem. It is because tags are visible by default that it is so hard to suggest their use for content moderation.

----

**BUT** all that being said, there absolutely should not be a way to hide tags without there also being a way to show them again, and this pull request doesn't seem to provide any mechanism for that. "Hiding tags by default" and "hiding them invisibly to the user with no indication that they're there" are two very different features. The first is desirable, I consider the second to be a harmful change.

This pull request is a quick fix for a problem that unfortunately needs a well-thought-out fix. Stripping tags can't be how this feature is implemented, users need to be able to (at a minimum):

- change an account setting or client setting to make tags default to visible again.
- easily view the tags attached to a post in their timeline even if their settings are to hide tags by default.
- see an indicator on each post that has hidden tags so that they know there are tags they can view.

Ideally this shouldn't be a serverside setting at all (other than that it would be helpful for the server to separate trailing tags so that the client can more easily decide what to do with them). Basically, default invisible tags are a great feature that's sorely missing from Mastodon, but this is not the way to fix that problem.

I don't necessarily agree with previous comments that #19528 would need to be implemented before this feature, but it would be a useful addition. My bigger point is just that tags definitely still have to be viewable.

**Comment by rezzish** [comment]
Gargron, you are a programmer, not a software engineer. If i was a hiring manager and i looked over this repo, i would be appalled at how you treat your code base, your pull requests, the other people who have tried to contribute to this repository. There's no info on the issue you're trying to solve, there's no precedent for the change, nobody's been asking for it. You obviously don't know what you're doing if you're getting strings of negative comments like this. You've built a piece of community software but you're still treating it like a personal project.

**Comment by ToadKing** [comment]
Yeah, this change seems premature until there's another way to view all the hashtags on a post.

**Comment by unlink2** [comment]
Personally, if it is seen as an issue to have hashtags at the end I would like to see a different UI to still have the option to display them. I like being able to tell why a post appears in my timeline (was it because I explicitly followed a user, a hashtag or was it a boost?). For me personally I also commonly follow hashtags in posts no matter where they appear.

**Comment by trwnh** [comment]
similar concept: can we expect media URLs at the end of a status to be converted to attachments? yes? no? what about links to other statuses? should those be converted to quote posts once those are added? or would that be considered a change in the author's intent?

other examples:

- a post body that is just a hashtag, followed by a media attachment. after this pr, it would be rendered with the attachment first, and the hashtag second (and much smaller and more de-emphasized). this ruins the intended framing of seeing the hashtag first before seeing the media -- the hashtag is part of the content, and it would be unexpected to have it render out-of-band.
- a post body that ends in hashtags on a new line, but the lines are again part of the content. consider:

```
"""
song lyrics
"""
#nowPlaying #Artist #SongTitle
```
the behavior in this pr would necessitate hacks in order to bypass it, similar to the .@ syntax of old twitter, one would need to add non-hashtag characters or text to any line that would otherwise be terminal and entirely composed of hashtags.

i think it is a good idea to have a "hidden hashtag" display on posts, and an option to enter "hidden hashtags" separately from the post body within the compose UI, but auto-converting behavior is just going to be an annoyance and break user expectations. essentially, this comment, but disregarding the first of the three proposal images: https://github.com/mastodon/mastodon/issues/25873#issuecomment-1633690976

**Comment by ocdtrekkie** [comment]
@trwnh There are edge cases, sure, but if you scroll through the federated feeds, of the small number of posts this would even apply to, it would handle 99.9% of them correctly. Those who explicitly need to hack around it... can?

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

**Comment by VAggrippino** [comment]
My 2¢ : I'd rather see all the hashtags.

Some version of this has apparently already been implemented.

Unfortunately, people use hashtags inappropriately to promote their political / social views or unrelated business ventures. Now, thanks to "out-of-band" hashtags, I can't even tell which hashtag they're abusing.

People abused hashtags frequently on Twitter and Mastodon seems to be the most likely heir. These "out-of-band" hashtags just make it easier to be spammy.

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire Doesn't this only change how they display when viewed on a compatible front-end? Wouldn't there be no change to older servers and clients?

No, it strips the last line from the contents in all contexts (federation and API as well), as long as it's a local post and the last line is hashtags only. This also applies to previously-made local posts.

> At least for the Mastodon server in question, could this behavior be shown or indicated during authoring, maybe by inserting a separator visualization of some sort if a match for this behavior is detected? I think having a separate box or more complicated entry tools would be a lot more confusing.

Possibly. I'm afraid I'm not sure what the best approach would be here.

**Comment by chrismessina** [comment]
> > @ClearlyClaire Doesn't this only change how they display when viewed on a compatible front-end? Wouldn't there be no change to older servers and clients?
> 
> No, it strips the last line from the contents in all contexts (federation and API as well), as long as it's a local post and the last line is hashtags only. This also applies to previously-made local posts.
> 
> > At least for the Mastodon server in question, could this behavior be shown or indicated during authoring, maybe by inserting a separator visualization of some sort if a match for this behavior is detected? I think having a separate box or more complicated entry tools would be a lot more confusing.
> 
> Possibly. I'm afraid I'm not sure what the best approach would be here.

I wrote up some [detailed thoughts here](https://medium.com/chris-messina/the-problem-with-the-problems-with-hashtags-35d4ba29b04d?sk=89627c83abff03705edb64fe59570415). I very much prefer that this FE treatment be an opt-in choice for instances and creators.

**Comment by ClearlyClaire** [comment]
Yeah, I would much prefer if it was done explicitly by the user at authoring time, but doing that would require a lot more UX work than we can afford to right now

**Comment by Leatherface75** [comment]
Here is an exemple how it looks like in Friendica.

image

**Comment by chrismessina** [comment]
> Here is an exemple how it looks like in Friendica.
> 
> image

Doesn't this demonstrate how hard it is to get this right? Four hashtags appear at the bottom of the post, two from the post's body and two from the end of the post.

The change as proposed in this PR wouldn't include any of those hashtags in the hashtag bar.

**Comment by Leatherface75** [comment]
> > Here is an exemple how it looks like in Friendica.
> > image
> 
> Doesn't this demonstrate how hard it is to get this right? Four hashtags appear at the bottom of the post, two from the post's body and two from the end of the post.
> 
> The change as proposed in this PR wouldn't include any of those hashtags in the hashtag bar.

Yeah i don't see the problem with this.
You easy see all tags in the bottom from the post as it should be.
Ofcourse you could try to hide it from the post but many people use tags everythere in the post so that makes it hard.

**Comment by chrismessina** [comment]
> Yeah i don't see the problem with this.

I'm only pointing out the different in implementation. 

If all hashtags (from the body, from trailing, and from ActivityPub) are to be aggregated in the hashtag bar, that seems consistent with Friendica's model. 

However, the implementation (as I understand it) only exposes trailing hashtags from the end of the post combined with out-of-band tags. Tags from the body of a post are not repeated in the hashtag bar.

**Comment by ocdtrekkie** [comment]
The information is displayed either way, but different software can decide to display it in different ways.

**Comment by Leatherface75** [comment]
> > Yeah i don't see the problem with this.
> 
> I'm only pointing out the different in implementation.
> 
> If all hashtags (from the body, from trailing, and from ActivityPub) are to be aggregated in the hashtag bar, that seems consistent with Friendica's model.
> 
> However, the implementation (as I understand it) only exposes trailing hashtags from the end of the post combined with out-of-band tags. Tags from the body of a post are not repeated in the hashtag bar.

Yeah it seems i don't see the logic with only showing some of the hashtags there.

**Comment by renchap** [comment]
#26499 has been merged, and implemented something similar, but on the web frontend only, so it keeps compatibility with clients not supporting out-of-band tags, and does not change the original message.

This might change in the future and maybe we will want to change the message, but this will be a breaking change (as it will break compat with old clients / instance versions) and will only happen once most of the ecosystem got support for it.

**Comment by renchap** [comment]
Closing as this was done another way in #26499

**Pull request closed without merging**
