### PR TITLE
Implement hotkeys for web UI

### LINKED ISSUE #376: shortcuts: namely, N to start a new post
it's in the title

### LINKED ISSUE #471: Scroll down to main status when ancestors are loaded
When clicking on toots in a long thread, the context column scrollbar goes to the top of the thread rather than zooming to the clicked toot.

### LINKED ISSUE #2102: Keyboard mappings
It would be nice to map the `esc` key on keyboards to fire the "Back" navigation element in the right column in the UI.

When scrolling through a timeline view and viewing a status or a person, sometimes a quick glance is all that's needed, and going back with a quick keypress is better than seeking with mouse.

### PR DESCRIPTION
**Pull request by Gargron**
- Fix #2102
- Fix #471
- Fix #376

Demo: <https://mastodon.social/@Gargron/20188468>

Hotkeys:

- `r` to reply
- `m` to mention author
- `f` to favourite
- `b` to boost
- `enter` to open status
- `p` to open author's profile
- `up` or `k` to move up in the list
- `down` or `j` to move down in the list
- `1`-`9` to focus a status in one of the columns
- `n` to focus the compose textarea
- `alt`+`n` to start a brand new toot
- `backspace` to navigate back
- `s` to focus search
- `esc` to un-focus compose textarea/search
- various "goto" combinations

### CODE REVIEW

**Review by nolanlawson — DISMISSED** [review]
I tested this out in Firefox/Chrome/Safari on Mac and Edge on Windows. Every command is working great in all four browsers except that there is a small bug for the `r` and `m` commands where it actually puts the literal letter `r` or `m` in the compose box. This bug occurs in Chrome, Safari, and Edge, but not in Firefox.

**Comment by Kjwon15** [comment]
Great feature!
How about `h`/`←`, `l`/`→` to move between columns like Tweetdeck does?

**Comment by Gargron** [comment]
@nolanlawson I fixed that, I also made the hotkeys work in notifications column and detailed status view! :sparkles:

**Review by ykzts — APPROVED** [review]

**Comment by channprj** [comment]
@Gargron Nice feature! Thank you for your work 👍 🎉 
But there's no keyboard shortcut modal, so end user do not know about it.
How about <kbd>shift + /</kbd> to show up keyboard shortcut modal like below?

**Pull request merged**
