### PR TITLE
Do not default SMTP verify mode to "peer", default to "none"

### PR DESCRIPTION
**Pull request by Gargron**
Resolves #6823

### CODE REVIEW

**Comment by ProgVal** [comment]
When `peer` is selected, a client certificate is required.

**Comment by Gargron** [comment]
The setup utility is not omnipotent. If extra config is needed, just edit the .env file.

**Review by nightpool — APPROVED** [review]
gonna approve for now and we can tweak if it continues to be an issue

**Comment by ProgVal** [comment]
LGTM

**Pull request merged**
