### PR TITLE
Fix trying to deliver to relays/forward replies when signing is disabled

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Comment by nightpool** [comment]
why make this change here instead of fixing the ingress logic to do resolve the status when it gets a forwarded status it can't authenticate?

**Comment by Gargron** [comment]
I'm not sure I understand? This is a fix for redundant egress

**Comment by nightpool** [comment]
It just seems weird to me to cut the egress back now when we know we want to fix reply forwading and relays in the future, even under secure mode. Why not just look up the status like we do for unknown Announces?

**Comment by Gargron** [comment]
Well, these forwards aren't announces so I feel like it's a bit harder to know that something even needs to be done in that regard. Like without an LD-Signature they just look like misattributed posts (and I believe they should get rejected because of that)

**Comment by ThibG** [comment]
I'm not too sure about the reply forwarding part, but the relay part is definitely working with relays made for Pleroma. Pleroma never had any LDSigning, so their relays work by `Announce`ing activities they receive. They are widely in use and work with both Mastodon and Pleroma.

On the other hand, if it is to check signatures at every request and not cache status, I'm unsure Mastodon would ever manage to cope with near-simultaneous requests from all subscribers to a relay.

**Pull request closed without merging**
