### PR TITLE
Added .tool-versions to manage dependencies with asdf

### PR DESCRIPTION
**Pull request by nileshtrivedi**
[asdf](https://asdf-vm.com/) is a developer tool to manage multiple versions of multiple programming languages, databases and other dependencies. This PR adds a `.tool-versions` file that specifies all necessary dependencies for local development of Mastodon. Once merged, correct versions of Ruby, NodeJS, Postgres and Redis can be installed with `asdf install` in the root directory.

I have taken Ruby and NodeJS versions as they're specified in the existing `Dockerfile` and Postgres and Redis versions as they are specified in the existing `docker-compose.yml`. If different versions are supported, the `.tool-versions` file will need to be changed appropriately.

An additional convenience can be achieved by changing `Procfile.dev` to look like this:

```
pgsql: postgres
redis: redis-server
web: env PORT=3000 RAILS_ENV=development bundle exec puma -C config/puma.rb
sidekiq: env PORT=3000 RAILS_ENV=development bundle exec sidekiq
stream: env PORT=4000 yarn run start
webpack: ./bin/webpack-dev-server --listen-host 0.0.0.0
```

This will enable `foreman start` to enable not just Mastodon but also Postgresql and Redis in non-daemon mode and collect logs in the same terminal. Because this may not be the desirable workflow for all, the PR does not include this change.

### CODE REVIEW

**Comment by ineffyble** [comment]
Another source of truth for versions of these, oh no 😁

**Comment by nileshtrivedi** [comment]
I was told that there's another set of files where dependencies versions are kept and that is in [.devcontainer](https://github.com/mastodon/mastodon/tree/main/.devcontainer)

**Comment by dogelover911** [comment]
There is no downside to including `.tool-versions`. It should either be included or gitignored. As it stands, users of asdf will need to add the file and then try not to add it to git. If the file is there and the versions are correct, everything is fine. If the versions are outdated, the developer will need to edit the file and try not to add it to git, which is no worse than the current scenario.

**Comment by ThisIsMissEm** [comment]
> There is no downside to including `.tool-versions`. It should either be included or gitignored.

I would say the downside is repetition of these values, which could all get out of sync would be a major downside (as it is, the node version in the `.nvmrc` didn't match the node.js version used in the Dockerfile). I'd be inclined to suggest this file should be ignored.

**Comment by mjankowski** [comment]
Closing this in favor of keeping the versions declared in fewer places.

Also FYI -- I am an asdf user and use it on this project. You can do something like:

```shell
echo ".tool-versions" >> .git/info/exclude
```

if you want to continue to use `asdf` on projects that don't use it, but don't want it in git (this is a local-only config for you, so the project gitignore doesnt need it)

**Pull request closed without merging**
