### PR TITLE
revert Gemfile.lock over change

### LINKED ISSUE #12993: bundle install fails (actionpack-5.2.4.1 revealed dependencies)
### Expected behaviour

After checking out v3.1.0rc1 `bundle install` should install the latest dependencies

### Actual behaviour

>Fetching actionpack 5.2.4.1
> Downloading actionpack-5.2.4.1 revealed dependencies not in the API or the lockfile (rack (~> 2.0, >= 2.0.8)).
> Either installing with `--full-index` or running `bundle update actionpack` should fix the problem.

### Steps to reproduce the problem

Check out `v3.1.0rc1` tag and run `bundle install`

### Specifications

Mastodon v3.1.0rc1
```
mastodon@vServer:~/live$ bundle --version
Bundler version 2.1.4
mastodon@vServer:~/live$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```
----

Disclaimer: I know nearly nothing about ruby package management.

I found some hints on the internet that one could edit the lockfile and indeed this fixed the issue for me:

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index d78465c8f..5f7f72770 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -44,7 +44,7 @@ GEM
     actionpack (5.2.4.1)
       actionview (= 5.2.4.1)
       activesupport (= 5.2.4.1)
-      rack (~> 2.0, >= 2.1.2)
+      rack (~> 2.0, >= 2.0.8)
       rack-test (>= 0.6.3)
       rails-dom-testing (~> 2.0)
       rails-html-sanitizer (~> 1.0, >= 1.0.2)
```

Probably just updating the lockfile would also fix this.

### PR DESCRIPTION
**Pull request by hinaloe**
fix #12993

#12991 was changed manually

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by ThibG** [comment]
No need to bump capybara for that, also there was another spurious change in activerecord dependencies

**Comment by hinaloe** [comment]
>No need to bump capybara for that
yes, I overlooked that it had been changed

**Comment by hinaloe** [comment]
This included in #12995, so This PR can close.

**Comment by ThibG** [comment]
I'll close this in favor of #12995. Thank you for your contribution, though!

**Pull request closed without merging**
