### PR TITLE
Rename "Federated timeline" feeds to "Live feeds"

### LINKED ISSUE #26068: Globe icon tooltip in advanced view says 'Federated timeline' and not 'Live feeds'
### Steps to reproduce the problem

1. Open Advanced Interface
2. Over over globe icon in lefthand column
3. Tooltip shows 'Federated timeline'

### Expected behaviour

Should read 'Live feeds' to match description on standard view

### Actual behaviour

Shows 'Federated timeline'

### Detailed description

CleanShot 2023-07-18 at 14 19 13@2x

### Specifications

Mastodon `main`

### PR DESCRIPTION
**Pull request by renchap**
Fixes #26068

There are 2 other strings with "Federated timeline", but I am not sure if they need to be changed:

https://github.com/renchap/mastodon/blob/62c996b52d4dc50e5713b8e7657fc5eaa52f39c8/app/javascript/mastodon/features/keyboard_shortcuts/index.jsx#L129

https://github.com/renchap/mastodon/blob/5785bfcafab6aef65fae3f1a51fbfe1368bc3b5b/app/javascript/mastodon/features/public_timeline/index.jsx#L23

### CODE REVIEW

**Comment by vmstan** [comment]
That was quick 😆

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
Not sure I agree with this, see https://github.com/mastodon/mastodon/issues/26068#issuecomment-1641641939

**Comment by gunchleoc** [comment]
Wrong fix, these don't have the same semantics as 'Live feeds'.  They correspond to the "Other servers" tab there, c.f. my comment https://github.com/mastodon/mastodon/issues/26068#issuecomment-1676421749

**Comment by renchap** [comment]
Closing this as it is not the correct fix

**Pull request closed without merging**
