### PR TITLE
Change unlisted icon to `low-vision` for better user clarity

### PR DESCRIPTION
**Pull request by rrgeorge**
The `unlock` icon causes confusion with users to understand what Unlisted privacy does. I propose changing the icon to `low-vision` to give a more clear indication of what Unlisted does.
Screenshot 2023-08-25 at 17 31 32

### CODE REVIEW

**Comment by Gargron** [comment]
To be less misleading the option would need the `globe` icon, same as public.

**Comment by rrgeorge** [comment]
> To be less misleading the option would need the `globe` icon, same as public.

The `globe` icon is used for both Public and the “Live Feeds” timelines (which unlisted posts do not appear on). 
Unlisted opts out of public timelines, trending, hashtag indexes, and it’s not included in the new public status indexes. I don’t see how it makes any sense to use the same icon as Public with all those factors in mind. A lot of users prefer to post unlisted, especially for replies, due to these factors. The `unlock` icon doesn’t quite encapsulate that feature set, and I believe that `low-vision` does.

**Comment by trwnh** [comment]
how about
- `globe` for unlisted 
- for public
  - `bullhorn` could mean being loud
  - `podcast` could mean broadcasting widely
  - `hashtag` could mean inclusion in hashtag timelines (and other such timelines)
  - `search` with a checkmark in it (custom icon) could mean opting into being found (or `search-plus` if not wanting to make a custom icon)

**Comment by rrgeorge** [comment]
> how about
> 
> * `globe` for unlisted
> * for public

The `globe` icon is industry standard for every platform for public, changing the icon for public, or reusing it for unlisted would be an unnecessary change that would only create confusion.

> i don't think `low-vision` covers the meaning
I don’t think `unlock` does at all. 

I don’t understand why my suggestion to change the Unlisted icon into something that the average user can understand better is being met with this disingenuous straw-man arguments. If you don’t like `low-vision` and prefer to keep `unlock' for Unlisted, then fine just say that. Both of these comments are both unconstructive and hostile to new ideas.

**Comment by Gargron** [comment]
The `low-vision` icon implies that the unlisted post is somehow hidden, which is not true. The unlisted option is unfortunately misleading by nature. It's equivalent to public in every *access control* way. FYI I don't think we should be getting any more attached to Font Awesome than we already are. The more unique/niche icons you use the harder it will be to switch to a better icon system.

**Comment by rrgeorge** [comment]
> The `low-vision` icon implies that the unlisted post is somehow hidden, which is not true. 

For all intents and purposes, unlisted is essentially hidden from the wider public because it’s only shown on on the timelines of followers or followers of people that have boosted it (which is the equivalent of sharing the direct link). I agree that it’s a less than ideal option, but I still think it’s more clear than `unlock`, but since Mastodon is currently using Font Awesome 4, the options for something that matches the style of the existing icons are rather limited. 

> The unlisted option is unfortunately misleading by nature. It's equivalent to public in every _access control_ way. 

Yes, but not in scope of broadcast, General public visibility and discoverability. The access control aspect of Unlisted, as Mastodon implements it, is no different than other platforms with an Unlisted privacy. 

> FYI I don't think we should be getting any more attached to Font Awesome than we already are. The more unique/niche icons you use the harder it will be to switch to a better icon system.

That’s a valid concern.

**Comment by trwnh** [comment]
Sorry, there wasn't any hostile intent in my comment, but rather the intent is that any clarification should clarify that unlisted is basically public. You might consider "unlisted" as opting out of discovery, but you might also consider "public" as opting into discovery. This is why I tried to suggest icons that imply broadcast, or otherwise directly using hashtag or search as stand-ins for what "public" does that "unlisted" doesn't. `fa-unlock` is not a good icon to convey this[^1], but IMO the correct icon to convey this is actually a globe, and the current "public" option should IMO be renamed to "discoverable".

[^1]: You could make a devil's advocate argument that "unlock" indicates that it is "unlocked" so that anyone can see it and fetch it, in which case it is actually a decent icon but for a different concept.

**Comment by mjankowski** [comment]
Closing due to merge conflicts and lack of consensus here, but also because the ongoing switch to not-font-awesome will make this decision need to be repeated. That said, there's clearly room for improvement here ... please either open an issue (or add comment to existing), and/or rebase/reopen this once we remove the font-awesome set more fully.

**Pull request closed without merging**
