### PR TITLE
Upgrade react-rails to v2.x

### PR DESCRIPTION
**Pull request by ykzts**
Sorry! There are many file changes. But, I just added `import React from 'react';`.

Also, never use jQuery in React Components. I deleted `//= require jquery`.

### with jQuery

```shell
$ du -sk public/assets/application-*.js*
2892	public/assets/application-acd2b42d93ab83e0fae21a51767e530d17ed4e0c2d9d0c3bd839cae162d48a67.js
496	public/assets/application-acd2b42d93ab83e0fae21a51767e530d17ed4e0c2d9d0c3bd839cae162d48a67.js.gz
```

### without jQuery

```shell
$ du -sk public/assets/application-*.js*
2776	public/assets/application-3a7e5f14a72c345ca3c138fefd79c813612c94afb5140d753428d0bb32225968.js
456	public/assets/application-3a7e5f14a72c345ca3c138fefd79c813612c94afb5140d753428d0bb32225968.js.gz
```

### CODE REVIEW

**Comment by ykzts** [comment]
oops... Why is RSpec pass in my local environment?

**Comment by ykzts** [comment]
OK, CI passed.

**Comment by tcitworld** [comment]
Pretty sure jquery had a use.

**Comment by ykzts** [comment]
jQuery is breaks DOM node created by React.

**Comment by Wonderfall** [comment]
Without jQuery I get these messages : `$ is not defined`.

**Comment by ykzts** [comment]
@Wonderfall Oh, I'm sorry. I overlooked it. I think that it is corrected by a373e0f.

**Comment by ykzts** [comment]
Because it conflicts with #2617 it closes.

**Pull request closed without merging**
