### PR TITLE
Add ability to see poll results without voting

### PR DESCRIPTION
**Pull request by gabrielcosta42**
Adds a link to show the results of a poll without voting and before it's expired. 
Discussed on #24746.

### CODE REVIEW

**Comment by Gargron** [comment]
Please include a screenshot to speed up the review process.

**Comment by ClearlyClaire** [comment]
Thank you for your contribution!

As Gargron pointed out, PRs changing the user interface should include screenshots.

In this case, this looks like something like this:

image
image

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
The translatable strings have not properly been added to `app/javascript/mastodon/locales/en.json` and `app/javascript/mastodon/locales/defaultMessages.json`.

You should run `yarn build:development && yarn manage:translations en`. In this case you can also directly apply the changes detected by the Github check: https://github.com/mastodon/mastodon/actions/runs/4983929609/jobs/9054807533?pr=24991#step:7:1179

Also of note, the model supports polls that do not disclose results until they have expired, so that might be something to consider. This is not currently exposed to the API nor is it possible to create such polls, though, so I think this PR not addressing that is fine.

**Comment by Gargron** [comment]
I would drop the paranthesis and just separate out "See results" with a bullet point like the time. I would also keep it short as "See results".

**Comment by Gargron** [comment]
Done in another PR now.

**Pull request closed without merging**
