### PR TITLE
Add alt text badge to images and gifs with alt text, and display alt text when badge is clicked

### PR DESCRIPTION
**Pull request by hs4man21**
Twitter had success in promoting alt text use and awareness by adding the `ALT` badge to tweeted images and gifs that contain alt text (aka an image description).
https://help.twitter.com/en/using-twitter/how-to-use-alt-gif

This PR adds the feature to Mastodon, with some modifications that make it more seamlessly weaved into the existing UI (e.g. the alt text of individual images/gifs from the same post can be exposed one-by-one and shown inside the image frame with a back button to view the image, instead of the alt text taking up your whole screen as is the case on the Twitter app).

This simple feature will:
- encourage more folks to make their posts more accessible
- allow folks to view alt text without assistive technology or dev skills (a number of accounts write really good alt text that folks who are not blind or low-vision also enjoy being able to read)

### Demo part 1
https://user-images.githubusercontent.com/38192823/208328029-79d9a61e-7768-414f-9b32-756dba2ccdd3.mov

### Demo part 2
https://user-images.githubusercontent.com/38192823/208328258-68bbcfe3-522c-46eb-a4a1-38dc78763caa.mov

### Demo part 3
https://user-images.githubusercontent.com/38192823/208328528-f1e3d305-861e-430f-9c65-c72703012c09.mov

### Demo part 4
https://user-images.githubusercontent.com/38192823/208328659-afa7ac2b-2c8a-4ef5-9d16-9475cbe33c08.mov

### CODE REVIEW

**Comment by rinsuki** [comment]
off-topic: desktop-*.mov and full-demo-p-2.mov using H.265 for encoding video, but it is not playable on some environments...

**Comment by hs4man21** [comment]
> off-topic: desktop-*.mov and full-demo-p-2.mov using H.265 for encoding video, but H.265 is not playable on some environments...

Thanks for flagging. I'm also looking into some linting issues and will push up an update soon.

**Comment by rinsuki** [comment]
also I think it would be good to use modal dialog (like Twitter does), since alt-text for movie/gif will be longer (than image) and may not suitable to show in small space.

**Comment by hs4man21** [comment]
> also I think it would be good to use modal dialog (like Twitter does), since alt-text for movie/gif will be longer (than image) and may not suitable to show in small space.

Yeah, I had that thought as well. I think there are pros and cons. The modal approach is not great when a post has multiple images/gifs and you want to view the alt text of each. But I was thinking a follow-up PR might implement full-screen alt text view for an image that is expanded. Definitely open to all thoughts/suggestions on this!

**Comment by nschonni** [comment]
> > off-topic: desktop-*.mov and full-demo-p-2.mov using H.265 for encoding video, but H.265 is not playable on some environments...
> 
> Thanks for flagging. I'm also looking into some linting issues and will push up an update soon.

If you run `yarn test:lint:sass --fix` it should be able to autofix the SCSS issues. Likewise `yarn test:lint:js --fix` for the JavaScript issues

**Comment by Freeplayg** [comment]
> also I think it would be good to use modal dialog (like Twitter does), since alt-text for movie/gif will be longer (than image) and may not suitable to show in small space.

Definitely preferable as it also doesn't cover up the image ~~(and imo would look better)~~

**Comment by mjankowski** [comment]
Closing due to lack of activity/rebase.

**Pull request closed without merging**
