### PR TITLE
Add ability to choose media thumbnail in web UI

### PR DESCRIPTION
**Pull request by Gargron**
image

I wanted to do something fancier but can't reach any satisfying results for now. At the end of the day, the most important part is having the function at all, and I suppose it looks nice enough.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is basically an invitation for trolls to put completely unrelated thumbnails on videos. I am not a fan of this.

**Comment by ThibG** [comment]
I don't know, people could already engineer videos with a frame they would want to see as thumbnail.

**Comment by SuperSandro2000** [comment]
I did no research but with this change it got a lot easier.

**Comment by Sasha-Sorokin** [comment]
I agree with @ThibG, before this moment Mastodon extracted the first frame as thumbnail for the video. And I, in fact, used this [here](https://mastodon.social/web/statuses/104388666952367874) (the only thing is that I suck at ffmpeg and did not concat correctly, so it uses much more frames, which is visually noticeable). This PR just makes it easier for you to have such thumbnail without modifying the video.

**Pull request merged**
