### PR TITLE
Add documentation of SMTP_DOMAIN

### PR DESCRIPTION
**Pull request by ian-kelling**
Without setting it, exim will reject the mail with a message like:

    rejected EHLO from [10.20.0.1]: syntactically invalid argument(s): {}

### CODE REVIEW

**Comment by ian-kelling** [comment]
This helps people avoid issues like  #1130. Someone should take a look at what it defaults too, as it seems to me that setting it to LOCAL_DOMAIN is better. Right now, I see it's set to config.x.local_domain, but I don't know what that resolves to, and I'm not bothering to find out.

**Comment by ineffyble** [comment]
Hey,

It should actually already set to LOCAL_DOMAIN.

`config.x.local_domain` is set to the LOCAL_DOMAIN by default, falling back to `localhost:PORT`. I'm just going to confirm this is working as intended, will comment again.

**Comment by ineffyble** [comment]
Except that's not the case, because `config.x.local_domain` isn't set at the point where it's referenced... I suspect this may have changed/broken at some point in the past.

This actually explains a few other reported issues. I'm making a patch now.

**Comment by ian-kelling** [comment]
I updated my pull request, simplifying the documentation, as this is rarely going to need to be set.

**Review by ineffyble — APPROVED** [review]
Looks good to me, approving for merge.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
