### PR TITLE
Bringing Hungarian translation up-to-date

### PR DESCRIPTION
**Pull request by gerazo**
- All translations added
- Hunglish phrases removed
- Several naming and phrasing inconsistencies were removed
- Boost term got a translation instead of just using Reblog

### CODE REVIEW

**Comment by Gargron** [comment]
I am really sorry but you need to submit translations via [Crowdin](https://crowdin.com/project/mastodon) now for a better workflow with proofreading, glossaries, QA checks etc.

**Comment by gerazo** [comment]
Ok. I've put up this whole translation on Crowdin. It was a lot of work, but it helped polishing the whole thing further. What is the next step? How and when can such a translation make its way into a release?

**Comment by Gargron** [comment]
Crowdin translations are periodically merged into master. Can't say when the next release is going to be, though!

**Comment by gerazo** [comment]
Thanks.

**Pull request closed without merging**
