### PR TITLE
In detail status view, display attachment uncropped if there's only one

### PR DESCRIPTION
**Pull request by Gargron**
A bit of a bummer: no way to make the media spoiler element the same height as the image/video it hides (since image/video is not in DOM when media spoiler is displayed)

### CODE REVIEW

**Comment by Gargron** [comment]
@akihikodaki Let me know if you have ideas about the media spoiler height. I imagine this PR would be very desired by Pawoo since it's great for artworks.

**Comment by akihikodaki** [comment]
Actually the media spoiler doesn't have to represent the height of the content. I think even one line is enough.

**Comment by akihikodaki** [comment]
I'm testing this on the local environment, and it looks really nice with drawings. Thank you for the improvement.

**Comment by nightpool** [comment]
We could cache the size of the image in the media attachment record. I
think paperclip might have an option for that?

**Comment by abcang** [comment]
I think that it is possible to calculate the height by using the aspect in meta of media_attachments.

**Comment by Gargron** [comment]
@abcang The react component is not aware of its own width, though... So even if I hack that in by checking the DOM, it won't be very react-like. There are ways to make it happen using higher-order components like autosize (new dependency), but...

If the height of the media spoiler does not matter, then this is done.

**Comment by abcang** [comment]
Hmm, it seems difficult to calculate the height of the media spoiler. I think that fixing the height of the media spoiler is not a problem.

**Comment by akihikodaki** [comment]
Maybe we could make up that with stretching animation or kind of?

**Comment by Gargron** [comment]
@akihikodaki @abcang I used react-sizeme to make the media spoiler the right height. I also made it so the "standalone" mode is only enabled *if* there is enough information (meta->small->aspect)

I also enabled this mode on public detailed status pages.

**Comment by abcang** [comment]
I think it's good!

**Pull request merged**
