### PR TITLE
Make handle more easily selectable on profile page

### PR DESCRIPTION
**Pull request by cadars**

### CODE REVIEW

**Review by cadars — COMMENTED** [review]
Makes it easier to copy handles from other instances (especially on touch screens).

**Comment by ClearlyClaire** [comment]
There is a small issue when the account is locked, in which there will be an additional space and an icon at the end. Could you perhaps add another `span` wrapping the handle and have the `user-select: all` on it?

Otherwise this is a very good improvement!

**Comment by cadars** [comment]
Cool, I've wrapped the handle in a span and corrected the CSS as well. Let me know if that works for you!

**Review by ClearlyClaire — APPROVED** [review]

**Review by connorshea — APPROVED** [review]

**Comment by evanphilip** [comment]
This possibly resolves https://github.com/mastodon/mastodon/issues/21074 and https://github.com/mastodon/mastodon/issues/19850

**Comment by evanphilip** [comment]
@cadars Thank you so much for this extremely useful pull request! 

I think merge is blocked by the whitespace in this blank line, right? I hope this gets merged soon (though I have already patched my instance).
https://github.com/mastodon/mastodon/blob/3e2ea498dba7c1985dae31eb7a609ca445bf44f5/app/javascript/styles/mastodon/components.scss#L7085

**Comment by cadars** [comment]
@evanphilip Oops. Should be fixed now!

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
