### PR TITLE
Adds bootsnap. Faster boot time

### PR DESCRIPTION
**Pull request by Gargron**
<https://shopifyengineering.myshopify.com/blogs/engineering/235340559-bootsnap-optimizing-ruby-app-boot-time>

Boot does feel a lot faster. I don't see any downsides to this.

### CODE REVIEW

**Review by mjankowski — APPROVED** [review]

**Comment by pooza** [comment]
On FreeBSD, bootsnap can not be built.

===
ERROR:  Error installing bootsnap:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3/gems/bootsnap-0.2.14/ext/bootsnap
/usr/local/bin/ruby23 -r ./siteconf20170521-16252-1l1etrq.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.3/gems/bootsnap-0.2.14/ext/bootsnap
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.3/gems/bootsnap-0.2.14/ext/bootsnap
make "DESTDIR="
compiling bootsnap.c
bootsnap.c:3:10: fatal error: 'sys/xattr.h' file not found
#include <sys/xattr.h>
         ^
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/local/lib/ruby/gems/2.3/gems/bootsnap-0.2.14/ext/bootsnap

make failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3/gems/bootsnap-0.2.14 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3/extensions/amd64-freebsd-11/2.3/bootsnap-0.2.14/gem_make.out

**Comment by saper** [comment]
Just run into this as well.

**Comment by Jehops** [comment]
An fyi for anyone that comes across this. The FreeBSD package, for now, patches to remove this dependency.

**Comment by Gargron** [comment]
@saper Told me that bootsnap 0.3 solves this issue so master has upgraded to that now. Hopefully this won't be an issue anymore!

**Comment by saper** [comment]
thanks @Gargron this is fixed now

**Comment by Jehops** [comment]
Thanks @Gargron.  Yes, bootsnap compiles now, but both Mastodon worker daemons fail to start when it is included.  I've included logs below.  So, for now, I will continue to leave bootsnap out of the FreeBSD package.

Puma errors with bootsnap: http://ftfl.ca/paste/puma_errors_with_bootsnap.html
Sidekiq errors with bootsnap: http://ftfl.ca/paste/sidekiq_errors_with_bootsnap.html

**Comment by pooza** [comment]
Thanks @Gargron .
It works!

**Comment by Jehops** [comment]
@saper, @pooza Could you elaborate?  You don't get the errors starting puma or sidekiq with bootsnap?  If that is the case, then maybe there is an issue with the global installation of bootsnap.

**Comment by saper** [comment]
In my case it has solved the compile error, but I was stuck into other dependency problems and it didn't start yet. So not really "working" yet.

**Comment by pooza** [comment]
@saper There is no problem, on my instance.

```
# service mastodon restart
=> Booting Puma
=> Rails 5.0.3 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
[1435] Puma starting in cluster mode...
[1435] * Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
[1435] * Min threads: 5, max threads: 5
[1435] * Environment: production
[1435] * Process workers: 2
[1435] * Preloading application
[1435] * Listening on tcp://0.0.0.0:3000
[1435] * Daemonizing...
# service sidekiq restart
# cat /var/log/sidekiq.log
{snip}
2017-05-29T08:30:17.877354+09:00 mstdn sidekiq[1513]: Booting Sidekiq 5.0.0 with redis options {:url=>"redis://localhost:6379/0"}
```

**Comment by Jehops** [comment]
@pooza, I see you are doing `service mastodon restart`.  Is this a local port you created?

**Comment by pooza** [comment]
@Jehops No, I implemented rc file only. :-)

/usr/local/etc/rc.d/mastodon
https://gist.github.com/pooza/c249f3bc56744b15758bcfd805093381

**Pull request merged**
