### PR TITLE
Fix old migration failing with new status default scope

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by aisk** [comment]
Got the same error, and cherry-picked this PR, looks like it dose not work.

**Comment by aisk** [comment]
Sorry, forgot run docker build first, trying.

**Comment by aisk** [comment]
@Gargron Hi can we add some special notice for people who is upgrading from older version to v3.0.1 to prevented this issue?

**Comment by ThibG** [comment]
What error do you get after applying this patch?

**Comment by aisk** [comment]
@ThibG Sorry can not access that machine now, but the erorr log should be the same with #12689 . I'll verify it later this day.

**Comment by aisk** [comment]
Sorry not familiar with rails, but maybe rails thinks the changes you made in this PR is already migrated and trying to run the next migration with error? @ThibG

**Comment by aisk** [comment]
@ThibG Sorry I think I should run the `db:rollback` and cherry-pick this PR and migate again. Solved, sorry for trouble you, thanks.

**Pull request merged**
