### PR TITLE
Fix unusual number formatting in some locales

### LINKED ISSUE #17904: Russian UI not rounding stats in about/more
### Steps to reproduce the problem

1. Open about/more page in Russian locale
2. Open about/more page in English locale
3. Compare

### Expected behaviour

English shows "123 K posts", while Russian shows "123 тыс. постов"

### Actual behaviour

English shows "123 K posts", while Russian shows "123 321 тыс. постов" which translates into "123 321 K posts".

### Specifications

Снимок экрана от 2022-03-30 00-10-00
Снимок экрана от 2022-03-30 00-09-53

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #17904

### CODE REVIEW

**Comment by Izorkin** [comment]
If there are few users on the instance, then following result is obtained:
```
Здесь расположились
               10,0
      пользователей
```
Needed:
```
Здесь расположились
                 10
      пользователей
```

**Comment by ClearlyClaire** [comment]
oops, good catch, sorry about that!

**Comment by Izorkin** [comment]
Working!
It remains to correct the message from `поста` to `постов`.

**Comment by ClearlyClaire** [comment]
I don't know Russian, would this normally be “1,601 поста” or “1,601 постов” if the number weren't abbreviated?

**Comment by Izorkin** [comment]
An example with an accurate display of the number of users and posts:
```
Здесь расположились 1501 пользователь   one
Здесь расположились 1502 пользователя   few
Здесь расположились 1503 пользователя   few
Здесь расположились 1504 пользователя   few
Здесь расположились 1505 пользователей  more
...
Здесь расположились 1511 пользователей  more
Здесь расположились 1512 пользователей  more
Здесь расположились 1513 пользователей  more
Здесь расположились 1514 пользователей  more
Здесь расположились 1515 пользователей  more
...
Здесь расположились 1520 пользователей  more
Здесь расположились 1521 пользователь   one
Здесь расположились 1522 пользователя   few
Здесь расположились 1523 пользователя   few
Здесь расположились 1524 пользователя   few
Здесь расположились 1525 пользователей  more
...
Здесь расположились 1570 пользователей  more
Здесь расположились 1571 пользователь   one
Здесь расположились 1572 пользователя   few
Здесь расположились 1573 пользователя   few
Здесь расположились 1574 пользователя   few
Здесь расположились 1575 пользователей  more

И опубликовано 1501 пост    one
И опубликовано 1502 поста   few
И опубликовано 1503 поста   few
И опубликовано 1504 поста   few
И опубликовано 1505 постов  more
...
И опубликовано 1511 постов  more
И опубликовано 1512 постов  more
И опубликовано 1513 постов  more
И опубликовано 1514 постов  more
И опубликовано 1515 постов  more
...
И опубликовано 1520 постов  more
И опубликовано 1521 пост    one
И опубликовано 1522 поста   few
И опубликовано 1523 поста   few
И опубликовано 1524 поста   few
И опубликовано 1525 постов  more
...
И опубликовано 1570 постов  more
И опубликовано 1571 пост    one
И опубликовано 1572 поста   few
И опубликовано 1573 поста   few
И опубликовано 1574 поста   few
И опубликовано 1575 постов  more
```

Example with rounding the number of users and posts:
```
Здесь расположились 1,01 тыс пользователей   more
Здесь расположились 1,21 тыс пользователей   more
Здесь расположились 1,32 тыс пользователей   more

Здесь расположились 1,01 млн пользователей   more
Здесь расположились 1,21 млн пользователей   more
Здесь расположились 1,32 млн пользователей   more

И опубликовано 1,01 тыс постов  more
И опубликовано 1,21 тыс постов  more
И опубликовано 1,32 тыс постов  more

И опубликовано 1,01 млн постов  more
И опубликовано 1,21 млн постов  more
И опубликовано 1,32 млн постов  more
```

In the second example, always used `more`.

**Comment by Brawaru** [comment]
Selecting correct plural for compact notation is difficult, see #16683. Something tells me that Rails too doesn't have any helpers for that. So we can fix compact notation formatting, but not the plural of words below, unfortunately. :(

**Comment by Izorkin** [comment]
Leave variant with rounding stats?

**Review by Gargron — APPROVED** [review]

**Comment by Izorkin** [comment]
@ClearlyClaire is it possible to add a pop-up window with real number of posts and users?

vivaldi_2022-04-02_11-41-43_

**Comment by Izorkin** [comment]
@ClearlyClaire this commit does not round off number of users:

vivaldi_2022-04-02_12-51-50_

**Pull request merged**
