### PR TITLE
Fix hidden label causing accessibility issue for search inputs

### LINKED ISSUE #6850: Search Function in Web UI has Poor Accessibility and Returns No Results
According to [a blind user using NVDA screenreader software](https://octodon.social/web/statuses/99718973629937162), the web UI's Search function has poor accessibility and returns no results.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by alexstine**
Fixes #6850

There is a label wrapped around the search input that contains `style="display:none;"`. This is useless and should be removed since this will not be read by screen readers or shown visually at any point. Adds `aria-label` as relying on `placeholder` attribute is not meeting the accessibility spec.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This change really messes with the visual design of the search box, so I think we will have to go another way. Maybe using `aria-label` would be better in this case?

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
This change really messes with the visual design of the search box, so I think we will have to go another way. Maybe using `aria-label` would be better in this case?

**Comment by alexstine** [comment]
@ClearlyClaire Looks better now? I hope this also does not break the visual layout but to have an empty label is really not great. Added the `aria-label` as suggested.

**Review by ClearlyClaire — APPROVED** [review]
Yup, this looks good to me!

**Pull request merged**
