### PR TITLE
Add `vite_rails` gem and `vite` binstub

### PR DESCRIPTION
**Pull request by mjankowski**
In advance of https://github.com/mastodon/mastodon/pull/24981

While some of the other last few PRs are also useful even w/out vite, this one ONLY makes sense if we are comitted to the vite direction and also want to really minimize the size of the linked PR by pulling things out in advance. This change is sort of pointless (Adding gem and binstub but not using them in any way), but also harmless in advance of the actual usage, I think.

### CODE REVIEW

**Comment by shleeable** [comment]
``` Configuration /home/runner/work/mastodon/mastodon/config/vite.json file for vite-plugin-ruby not found.
Make sure `bundle exec vite install` has run successfully before running dependent tasks.```

**Comment by mjankowski** [comment]
Hmm, looks like the default integration wants more than I have here. Will look for ways to disable the hooks during assets compile...

**Comment by mjankowski** [comment]
Expanded this slightly beyond the original scope to handle those issues. Looks like there's some default hooks into the asset process, but they can be disabled with an env var. So, in addition to the original gem and binstub, I added:

- Generated config file, because script complains if it's missing
- Env vars for production (CI only) and test (dotenv) to disable the integration

Even though this is currently passing CI, it is actually sort of risky for merge ... because the env var for production is only in the CI config now, and if you try to compile assets w/out setting that env var, you get an error. I'll look for some other way to disable that's more resilient.

**Comment by renchap** [comment]
I do not see any value in adding those before Vite is added. It may minimise the diff for the Vite PR slightly, but it does not really bring any benefits.

**Comment by renchap** [comment]
Closing this PR as it does not provide significant benefits.

**Pull request closed without merging**
