### PR TITLE
Part two of `devise-two-factor` migration

### PR DESCRIPTION
**Pull request by mjankowski**
Follow up on https://github.com/mastodon/mastodon/pull/28325

Should not be merged until after next version release at earliest.

### CODE REVIEW

**Comment by mjankowski** [comment]
Converted to ready for review since 4.3 is in RC mode. This should wait until after release, but in theory could be reviewed for merge into main/4.4.

This includes the followup tasks from the migration guide -- dropping the now unused columns and a few related methods.

One thing I'm not sure about ... I'd love to be able to just delete the legacy/migration module, but we reference it in that old migration. For now I've moved it out of concerns and into inline inclusion in the migration (which already has an inlined user class). It occurs to me though - if we have an expectation that people should have fully upgraded/migrated on the previous minor number version prior to upgrading to another one - then everyone who upgrades to 4.4 some day will have already upgraded to 4.3 and run that migration, so in theory we could update the migration in some way that dropped reference to the now-deleted module, but did something reasonable for dev/CI "full migration" purposes. Thoughts on that welcome.

**Comment by mjankowski** [comment]
With 4.3 out, this may be safe to go now - would like any thoughts on previous question about the legacy behavior module.

**Comment by mjankowski** [comment]
Would love thoughts on whether getting this next step in is appropriate for 4.4?

**Comment by mjankowski** [comment]
Also curious on this one -- is it ready for rebase/reopen now into main, or should wait until post-4.4-release?

**Comment by mjankowski** [comment]
> Also curious on this one -- is it ready for rebase/reopen now into main, or should wait until post-4.4-release?

I realize no one is tagged on this and I'm talking to myself.

CC @renchap @ClearlyClaire

**Comment by ClearlyClaire** [comment]
Sorry we forgot about this!

Basically, if I understand correctly:
- 4.3.0 introduced the new encryption, added a post-deployment migration to make sure every code has been re-encrypted after the migration, and added code to gracefully fall back to the old encryption scheme to provide zero-downtime migration from 4.2.0
- migrating from 4.3.0 to this PR can happen with a zero-downtime migration, since every code has been migrated and we don't need the fallback
- a zero-downtime migration from pre-4.3.0 to this PR is not completely safe, as people won't be able to log in (or TOTP will be skipped? need to check) if a person tries to log-in while the new code is running but the post-deployment migration isn't done yet

**Comment by mjankowski** [comment]
Yes, I think that's a good summary ... the devise-two-factor upgrade instructions purposefully break it into two pieces, and this PR is just capturing their clean up steps.

I think that's also correct that the only real risk here would be someone blowing through the upgrade instructions and winding up running this version of the code that removes the legacy fallback code, without having fully migrated first.

Shall I rebase/reopen for review for 4.4?

**Comment by ClearlyClaire** [comment]
Yes please!

**Pull request closed without merging**
