### PR TITLE
Update notification labels for mentions

### PR DESCRIPTION
**Pull request by renchap**
The current iteration duplicates the username, which is wasteful and disturbing, especially when they contain emojis.

image

They also do not really differentiate mentions from replies.

With this change, there is no more duplication and the difference is explicit

image

Fixes MAS-296

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Do we want the “@ Mention”? Currently, the only places “@” appears are related to private mentions specifically.

**Comment by renchap** [comment]
> Do we want the “@ Mention”? Currently, the only places “@” appears are related to private mentions specifically.

I thought it would make sense to differentiate mentions and replies. We could have a different icon for mentions, or private mentions if you think it makes sense.

**Review by Gargron — APPROVED** [review]

**Comment by leo60228** [comment]
At least in Firefox, this seems to also affect desktop notifications, which no longer list the responsible user at all:

Mention: @leo test

Was this intentional?

**Comment by renchap** [comment]
This has nothing to do with native (system) notifications. If you are experiencing this, please open a new issue on this repo with some details.

**Comment by ClearlyClaire** [comment]
This is actually related, as the string `notification.mention` is also used in the service worker (`app/javascript/mastodon/service_worker/web_push_locales.js`).

I noticed this issue too but failed to make the connection with this PR.

**Comment by ClearlyClaire** [comment]
> Good point, I missed this. Can you open a PR with a fix to use different locales there?

That may actually be a bit tricky, as so far we've got away by re-using in the service worker translation strings used elsewhere in the WebUI, and exporting a subset of the translations using `preval` (see `app/javascript/mastodon/service_worker/web_push_locales.js`).

We would need to use something to `createMessage` if possible for the translation toolchain to pick up those strings.

**Pull request merged**
