### PR TITLE
[i18n] Update Occitan

### PR DESCRIPTION
**Pull request by Quenty31**
For the directory + some harmonisations

### CODE REVIEW

**Comment by Quenty31** [comment]
Oh :( I don’t what failed here :S

**Comment by nightpool** [comment]
````
The following data requires normalization:
config/locales/oc.yml
config/locales/simple_form.oc.yml
Run `i18n-tasks normalize` to fix
````

**Comment by Quenty31** [comment]
yes thanks, but I don't know what lines exactly I should change =/

**Comment by Quenty31** [comment]
Hello @Gargron may you help me there?
I am not good a using the validation tests =/

**Comment by ykzts** [comment]
oops

**Comment by ykzts** [comment]
@Quenty31 #9491 new Pull Request.

**Pull request closed without merging**
