### PR TITLE
Add button to clear all recent searches

### LINKED ISSUE #27279: Button to clear recent searches
### Pitch

When focusing on the search bar, it shows a list of recent searches. It is possible to clear these searches individually by clicking on the X icon for each of them. But we could also have an button above to clear all searches.

image

The button could live above the row of Xs, on the right of the “Recent searches” label. It could be an icon such as a small broom, or the words “Clear all”.

### Motivation

If a user wants to clear al search history, they currently have to clear each search one by one. Many other platforms provide a way to clear all searches.

For instance: [Linkedin](https://github.com/mastodon/mastodon/assets/923008/40363e39-b9b9-4a69-ad16-2f58d1065ab2)

### PR DESCRIPTION
**Pull request by hughrawlinson**
Fix #27279

Screen Shot 2023-10-07 at 15 12 56

### CODE REVIEW

**Comment by vmstan** [comment]
The X appears misaligned to me.

**Comment by hughrawlinson** [comment]
@vmstan Ah yeah, it doesn't seem fully aligned with the heading. I'll update.

**Comment by ashleyhull-versent** [comment]
also, I'd really like to see the clear all search icon to be different than the delete single search icon

**Comment by hughrawlinson** [comment]
I guess the bot will remove the label now that I've rebased?

**Comment by vmstan** [comment]
Yeah it takes a little bit to run through it.

**Comment by Gargron** [comment]
The icon system has changed. I recommend going with a "Clear" text instead of icon.

**Comment by hughrawlinson** [comment]
image

Updated to use the word "Clear" instead of an icon.

**Review by mjankowski — APPROVED** [review]

**Comment by mjankowski** [comment]
Doing some old PR triage ... looks like this one was vaguely agreed to but not approved? (also looks like CI might need approval)

**Comment by hughrawlinson** [comment]
@mjankowski yep, that's the status.

Fwiw I kind of gave up on contributing to mastodon/fedi after this. It's a tiny PR linked with a clear issue that was accepted as an issue, I addressed comments on I thin the same day they were given, and then just radio silence. No blame, I understand it's a tricky thing to run a high profile open source project. I just don't know what I could've done differently to make contributing an OK experience, or to make merging easier.

**Comment by mjankowski** [comment]
> @mjankowski yep, that's the status.

Thanks for confirming. I'll leave open a bit longer to see if there's available UX feedback.

> Fwiw I kind of gave up on contributing to mastodon/fedi after this. It's a tiny PR linked with a clear issue that was accepted as an issue, I addressed comments on I thin the same day they were given, and then just radio silence. No blame, I understand it's a tricky thing to run a high profile open source project. I just don't know what I could've done differently to make contributing an OK experience, or to make merging easier.

Understood completely. Apologies for not seeing this earlier and attempting to corral the necessary resources in the direction of these changes.

**Comment by hughrawlinson** [comment]
image

There are now non-trivial merge conflicts with this PR, and having had next to no movement on this PR for a year, I deleted my dev environment because it seems to me that my contributions were unwelcome. Since I no longer remember how to test this, nor care to invest the time to set up my project again faced with the prospect of another year of silence on a PR that would be trivial to review, I'm going to close this PR and wish you all good luck.

I absolutely do not want to seem hostile here - while it's no fun to have this kind of experience in open source, I am putting my feelings aside so that I can give you the feedback that may be useful to you: this kind of contribution experience *sucks*. I'm not saying that as a disgruntled attempted contributor who had a bad patch, I'm telling you as someone with about a decade experience in developer experience, that this is not how a first-time-contributor experience should work. It may be that you're focused on the experience of long time contributors, and that is a legitimate thing to optimize for (or to have any number of other priorities)! But in that case, you really ought to be clear about that in the readme and contribution guidelines. Even a "we don't have the capacity to review all PRs, here are the areas and practices you can focus on to make it easier for us" would do. I was going to learn Ruby for this, I cared so much! :stuck_out_tongue:

**Pull request closed without merging**
