### PR TITLE
Use `github` reporter on `haml-lint` runs on CI

### PR DESCRIPTION
**Pull request by mjankowski**
Including a violation in this PR to see annotation/logs output. Will remove before merge.

Related https://github.com/mastodon/mastodon/pull/29181#issuecomment-1959253912

### CODE REVIEW

**Comment by mjankowski** [comment]
Ok, this has run and failed as expected. If you look at the files tab in github there is an annotation on the line with the problem.

One trade-off here is that with this reporter enabled, the default reporter is disabled, so the specific line information will ONLY be in the annotations, and not in the CLI output on the failing run itself. For example, on this run - https://github.com/mastodon/mastodon/actions/runs/8019637801/job/21907836377?pr=29375 - you see the error output about which linter failed, but not the file/line information. This may be fine, just wanted to highlight.

**Comment by renchap** [comment]
Is it possible to configure 2 reporters at the same time?

**Comment by mjankowski** [comment]
I don't think so. That was my hope because the rspec reporter works that way, but I think in haml-lint its just one reporter allowed.

**Comment by renchap** [comment]
It is probably worth opening a feature request on their side.

I think that for now it is better to have annotations than the errors in the log, but having both would be better, or somehow have the Github reporter also output the error location in the logs somehow

**Comment by mjankowski** [comment]
Opened issue in haml-lint repo, linked here.

**Review by ClearlyClaire — DISMISSED** [review]

**Comment by mjankowski** [comment]
Updated to remove the failing haml changes I had here for test purposes. Now includes just the config change.

We can watch that linked issue and see if there's a way to have both the annotations and actions log at same time.

**Review by ClearlyClaire — APPROVED** [review]

**Review by renchap — APPROVED** [review]

**Pull request merged**
