### PR TITLE
Refactor appeal partial to avoid brakeman XSS warning

### PR DESCRIPTION
**Pull request by mjankowski**

### CODE REVIEW

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
The `html_safe` was needed because of the nested `content_tag`s, the PR causes the following issue:
image

**Review by ClearlyClaire — COMMENTED** [review]
Looks good, but as far as the brakeman warning is concerned, I think all the PR does is shuffle things around enough for brakeman to lose track of it, and I'm a bit uncomfortable with that.

**Comment by mjankowski** [comment]
> Looks good, but as far as the brakeman warning is concerned, I think all the PR does is shuffle things around enough for brakeman to lose track of it, and I'm a bit uncomfortable with that.

This is a few months old and unfortunately I didn't preserve this order of changes in the commit history -- but my memory here is that I was able to get rid of the warning in the view directly first by using the hash slice changes, and then the moving it over to a helper method was just a refactor and not purely an obfuscation.

That said, just pushed a change which drops the hash slice approach in favor of just adding an extra `#h` call around the i18n key which satisfies brakeman since thats where they hypothetical user-supplied db value could come from.

**Comment by ClearlyClaire** [comment]
> That said, just pushed a change which drops the hash slice approach in favor of just adding an extra `#h` call around the i18n key which satisfies brakeman since thats where they hypothetical user-supplied db value could come from.

Sorry, I'd actually prefer the `slice` version since this is a translation string key, not a value to be directly included, so escaping this way does not seem to make sense, but the slice does (even though it's a bit verbose).

**Comment by mjankowski** [comment]
Restored the slice

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
