### PR TITLE
Add RSpec GitHub annotations gem

### PR DESCRIPTION
**Pull request by nschonni**
Didn't get to this in the original PR to setup the GitHub Actions. One of the nice things with the platform is that it can comment inline with annotations when things fail.

This adds annotations for the RSpec tests, while keeping the current formatters as well.

You can see an example over on https://github.com/nschonni/mastodon/pull/123/files#diff-27c972f410ab415cb244d66c06cdc91b40c072a70d991fe9d96f64c797e9450e that has failures on files that weren't touched in the PR directly, but if they were changed files, the would also appear in a similar format. Note that because of the batching, one line might have some duplicate annotations if it fails across multiple environments

This also rolls them up to the Summary of the jobs https://github.com/mastodon/mastodon/actions/runs/4372159157 but there are limits to how many annotations will bubble up/annotate.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
> Note that because of the batching, one line might have some duplicate annotations if it fails across multiple environments

Is there something we can do about that? It's really noisy.

**Comment by nschonni** [comment]
Noisy from the message for each ruby version, or from the Pending test warnings? The pending ones mostly will go away as there are a few PRs that currently are filling them in.

**Comment by nschonni** [comment]
@ClearlyClaire I think https://github.com/mastodon/mastodon/pull/23969 would get rid of the bulk of the noise from the pending specs

**Comment by ClearlyClaire** [comment]
> Noisy from the message for each ruby version, or from the Pending test warnings?

Both.

**Comment by ClearlyClaire** [comment]
Is there something we can do to deduplicate the reports?

**Comment by nschonni** [comment]
Not really, unless reporting was only conditionally run on particular Ruby runtimes. Probably the better fix is either to fix https://github.com/mastodon/mastodon/pull/24040#issuecomment-1492836696 or suppress all the Pending noise

**Comment by ClearlyClaire** [comment]
Warnings for untouched pending specs is not the only noise I'm concerned about, I think having duplicate annotations for most errors is going to be annoying/distracting more than helpful. Unfortunately, I could not find a way to solve this. There are issues open for Github Actions, but unfortunately, there doesn't seem to be any progress: https://github.com/actions/runner/issues/264 https://github.com/actions/toolkit/issues/395

**Comment by mjankowski** [comment]
I believe at this point all the pending/xit/etc stuff has been cleaned up, so that wont be present anymore.

Could we run this on JUST the `.ruby-version` run in the matrix, so that we reduce dupes? This would hypothetically miss annotating failures if they were present in an older version, but we'd still get the failure - and it might be a way to nudge this in if the annotations are useful.

**Comment by ClearlyClaire** [comment]
> I believe at this point all the pending/xit/etc stuff has been cleaned up, so that wont be present anymore.
> 
> Could we run this on JUST the `.ruby-version` run in the matrix, so that we reduce dupes? This would hypothetically miss annotating failures if they were present in an older version, but we'd still get the failure - and it might be a way to nudge this in if the annotations are useful.

That makes sense to me!

**Comment by nschonni** [comment]
Looks like all the warnings are gone! I didn't try to see if it could be filtered to just one of the jobs. Currently it only runs based on it seeing it's on GitHub Actions, but i'm not sure if there is a simple way the build matrix gets exposed as environment variables. I'll leave that for someone else to figure our if they're interested

**Review by ClearlyClaire — APPROVED** [review]
Alright, going to merge it as-is and then experiment with how failures are reported and tackle any duplicate report in an upcoming PR.

**Pull request merged**
