### PR TITLE
Change reblogs to be excluded from "Posts and replies" tab in web UI

### LINKED ISSUE #11120: User timeline UI: add tab to show only user's original toots
### Pitch

As a user viewing another user's account, deciding whether to follow them or not, I want to see only their own toots, not boosts.

I proposed an `exclude_reblogs` extension to `/api/v1/accounts/:id/statuses` in #9606, which @Gargron implemented in #9640 and I documented in [mastodon/docs#17](https://source.joinmastodon.org/mastodon/docs/merge_requests/17).

This feature is thus already supported by the backend, but it needs UI.

### Motivation

It can be very hard to see a user's own toots if they boost a lot of other users' toots. When I'm deciding whether to follow someone or allow them to follow me, I really only want to see what they've written, not what other people have written.

## Proposed implementation

This could be surfaced in the Mastodon frontend as a fourth tab alongside "Toots", "Toots and Replies", and "Media": "Toots and Boosts". I've prototyped this in #11119: "Toots" now shows only the user's original toots, and "Toots and Boosts" shows the user's toots and boosts.

image

image

### Alternate implementation (simple)

Alternatively, to retain the original behavior of the "Toots" tab, we could instead introduce a fourth "Toots without Boosts" tab. This would probably be very similar to #11119, code-wise.

### Alternate implementation (complex)

Since that timeline API has several filters which are orthogonal, we could replace the timeline tabs with filter checkboxes for:
- [x] show replies
- [x] show boosts
- [ ] show only media

However, this would be a significant departure from the shape of the existing UI, and I don't know enough React to do it myself (yet). Thoughts welcome.

### Notes on other implementations

The only third-party client that I know of that supports `exclude_reblogs` is Mast as of ShihabM/Mast#35, which made `exclude_reblogs` a global preference. I don't think we want to go that route UI-wise.

I added `exclude_reblogs` to Pleroma's backend in [pleroma/pleroma#598](https://git.pleroma.social/pleroma/pleroma/merge_requests/598).

### PR DESCRIPTION
**Pull request by Gargron**
Fix #11120

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
I love it. The way I usually use these tabs is:

- Posts: What will be added to my feed if I follow.
- Posts with replies: What this user is saying. Boosts feels like clutter in this context.

**Comment by trwnh** [comment]
this change makes it so that there is no way to get a complete view of a profile.

**Comment by Gargron** [comment]
I'm okay with that.

**Comment by VyrCossont** [comment]
Thank you!

**Comment by rinsuki** [comment]
I think this is _not_ okay, since some peoples posts are implicitly depends to previous boost. at least we should have all posts option.

**Comment by Gargron** [comment]
That's what the "Posts" tab is for.

**Comment by vmstan** [comment]
For anyone confused here:

Posts tab now shows all of the users Posts + Boosts
Posts & Replies tab only shows users Posts & Replies

It seems like an appropriate compromise.

**Comment by rinsuki** [comment]
I think then you should rename tab to something other things, like just "Replies" and show only replies.

If tab "A" and "A & B" are exists, expected behavior is everything in tab "A" is also included in "A & B" tab.

**Pull request merged**
