### PR TITLE
Rewrite `load_gap.jsx` to ts and FC

### PR DESCRIPTION
**Pull request by nxxkap**
This PR rewrites `load_gap.jsx` to ts and FC.

### CODE REVIEW

**Comment by taichi221228** [comment]
I've encountered a conflict with this case for the first time.
Could anyone guide me on what should be the appropriate steps to resolve this issue? Any help would be greatly appreciated.

**Comment by nschonni** [comment]
`git pull --rebase upstream main`, then you'll need to force push with `git push -f`

**Comment by taichi221228** [comment]
WTF, the history has become quite complicated.
Given that the changes are minimal, would it be better to create a new branch instead?
I would appreciate your suggestions.

**Comment by shleeable** [comment]
Feels like it.

**Pull request closed without merging**
