### PR TITLE
Add nds locale to posting languages

### PR DESCRIPTION
**Pull request by gunchleoc**
Requested on Mastodon:  https://todon.nl/@anarchiv/111245093625347887

### CODE REVIEW

**Review by ykzts — DISMISSED** [review]

**Review by renchap — DISMISSED** [review]

**Comment by renchap** [comment]
Can you rebase? I will then merge it

**Comment by gunchleoc** [comment]
> Can you rebase? I will then merge it

Done

**Review by renchap — DISMISSED** [review]

**Comment by renchap** [comment]
Sorry, it needs another rebase due to a dependency bump to fix a security issue.

**Comment by gunchleoc** [comment]
> Sorry, it needs another rebase due to a dependency bump to fix a security issue.

Actually, it's because the locale codes for the languages I'm adding happen to be next to each other in the alphabet. So, I expected this :)

**Review by renchap — APPROVED** [review]

**Pull request merged**
