### PR TITLE
Change dependency from annotate to annotaterb

### PR DESCRIPTION
**Pull request by drwl**
This PR changes the project to use AnnotateRb instead of Annotate. 

I tested it locally and there are no changes to the annotation configuration nor annotations themselves. What does change is the CLI, so if running annotations manually previously you would use `bundle exec annotate`, now one would use `bundle exec annotaterb models`.

I was a maintainer of the [old gem (annotate)](https://github.com/ctran/annotate_models) but decided last year to make a fork and tidy up the code a lot. The new gem (annotaterb) is actively maintained and _should_ perform faster for newer Rails (6+) apps because it leverages Zeitwerk instead of eager loading everything.

This PR is self-serving in that it does grow usage of my project, so feel free to reject this. I am also happy to answer any questions.

### CODE REVIEW

**Comment by mjankowski** [comment]
Is the old gem unmaintained now? I see it has ~10 commits in last ~2 years, so obviously it's not VERY active ... just curious if it's a situation where what you are doing here is more of a hard fork of the project, or more of an issue of whoever has ownership permissions on original no longer being available or something?

**Comment by drwl** [comment]
> Is the old gem unmaintained now? I see it has ~10 commits in last ~2 years, so obviously it's not VERY active ... just curious if it's a situation where what you are doing here is more of a hard fork of the project, or more of an issue of whoever has ownership permissions on original no longer being available or something?

I think it's safe the say the old gem is unmaintained, the repo owner hasn't had time to maintain + hasn't written in Ruby in some time.

I decided to hard fork it last year to have full permissions over the project (I was limited as a maintainer of the old gem) + take the gem in a certain technical direction which was easier when I could make breaking changes.

**Comment by mjankowski** [comment]
Glad to hear you're moving it forward! ... what's the nature of the direction you're moving?

Are you in contact at all with gem/repo owner? Are they interested in handing it off totally? Giving you more perms, etc? If they've truly bailed, seems a shame to lose the stars/issues/gem and other history.

**Comment by drwl** [comment]
Answering inline

> Glad to hear you're moving it forward! ... what's the nature of the direction you're moving?

Thanks! The repos have since diverged but it may be possible to do a diff since AnnotateRb still has the git history. But in short, I changed a lot of the internals through refactors and how data flows. The old gem, in my opinion, is/was essentially a shell script that accrued a bunch of technical debt.

> Are you in contact at all with gem/repo owner? Are they interested in handing it off totally? Giving you more perms, etc? If they've truly bailed, seems a shame to lose the stars/issues/gem and other history.

This is a good question and commonly asked — I sent him an email a while back and didn't hear anything back. So I don't think he's bailed but just doesn't have the time or resources to maintain it (I don't blame him, open source for small/not funded projects is hard work).

**Review by Gargron — DISMISSED** [review]

**Comment by drwl** [comment]
Hi @Gargron and @renchap, I've rebased and updated the PR. It seems like workflows need to be approved to run, so I'll wait to get feedback from CI once they get approved.

**Comment by drwl** [comment]
I believe it should be good to go now

**Review by mjankowski — APPROVED** [review]
Looks good - thanks.

Is the config here sufficiently close to the previous that running the annotation process does not produce any changes to models? (ie, did this PR also re-run annotation, or just change the gems?)

**Comment by mjankowski** [comment]
I pulled this PR branch down locally and ran the task -- no changes! Think we're all good here.

**Review by renchap — APPROVED** [review]

**Pull request merged**
