### PR TITLE
Add Samogitian locale

### PR DESCRIPTION
**Pull request by gunchleoc**
Still needs to be activated on Crowdin too, see https://crowdin.com/project/mastodon/discussions/48

### CODE REVIEW

**Comment by zordsdavini** [comment]
Is it possible to review this somehow?

**Review by zordsdavini — APPROVED** [review]
name is correct

**Comment by luzpaz** [comment]
bump

**Comment by zordsdavini** [comment]
WIP with CLDR. Not so fast process.

**Comment by gunchleoc** [comment]
We could also add a custom locale to Crowdin with the plural rules you provided over there, but I'm not an admin, so I can't do it. @Gargron ?

**Comment by zordsdavini** [comment]
in Crowdin recomended to go through CLDR

**Comment by gunchleoc** [comment]
@zordsdavini That will probably be some time next autumn then. Tag me here or on Crowdin when you're ready and I'll try again to help.

**Pull request closed without merging**
