### PR TITLE
add clustering for node.js streaming.

### PR DESCRIPTION
**Pull request by matyapiro31**
* add npm package cluster.
* add cluster on pacakge.json, and yarn.lock.

### CODE REVIEW

**Comment by Gargron** [comment]
But we already have clustering..?

**Comment by matyapiro31** [comment]
clustering for service mastodon-streaming.I think it's not supported now, is it?

**Comment by Gargron** [comment]
https://github.com/matyapiro31/mastodon/blob/74d31c21317011335fff4e2f0f8fb21b134c358e/streaming/index.js#L492

**Comment by akihikodaki** [comment]
I think this pull request should be closed, isn't it?

**Pull request closed without merging**
