### PR TITLE
Fix rare race condition when rebloged status is deleted

### PR DESCRIPTION
**Pull request by ClearlyClaire**
In some cases, it's possible for a reblog to be created and not marked as discarded while the underlying status is discarded, causing `status.reblog?` to be `true` yet `status.reblog` and `status.proper` to be `nil`.

Note that this does not retroactively fix such records nor does it fix the call sites that use `status.reblog` or `status.proper`.

### CODE REVIEW

**Comment by Gargron** [comment]
Might it make sense to add a database constraint for this instead of a post-transaction check? Or would that not work because the status is *not* discarded in our transaction? Maybe a pessimistic lock on the original status would help?

**Comment by ClearlyClaire** [comment]
I don't think we can write a database constraint that depends on another row than the one being created/updated.

As for a pessimistic lock, that's a good question. I think it would require using the lock in all call sites that create reblogs (2 currently, I think) and in most case would require an extra query anyway. I'm also not completely sure about the performance implications.

This solution is akin to an optimistic lock, although it does an extra query. I've checked how Rails does optimistic locking internally, and it does something smarter by using adding to the `WHERE` clause in the `UPDATE` it issues. That's of course only valid for updates, which is not our case here. Taking inspiration from this, the optimal solution might be something like using a subquery in the `INSERT INTO` but I don't think ActiveRecord would allow to do that without overriding some internal methods.

**Comment by ClearlyClaire** [comment]
I have pushed a commit changing the approach entirely, by overriding the internal Rails method responsible for building the final SQL query on a `create!` or `create` call in order to use a `INSERT INTO "statuses" … SELECT (…) FROM "statuses" WHERE …` query instead of a `INSERT INTO "statuses" … VALUES …` query. The inserted values are the same and are passed into the query pretty much in the same way, but the `WHERE` clause ensures the reblogged status is *not* discarded.

I believe this approach has minimal overhead since it's a very simple query, SQL-wise and does not result in any additional query.

As for overriding the internal `_insert_record` class method, I have found no other way to change the SQL query resulting from a `create!` call, and defining another method to replace `call!` would essentially require the same work in addition to managing hooks and validations properly, so I think this is the simplest and most maintainable way to do that specific SQL trick, although I do understand it's maintainability is not ideal.

**Review by Gargron — APPROVED** [review]

**Comment by mjankowski** [comment]
@ClearlyClaire low priority, but would love to get your input on the question above if possible so I can prepare this for Rails 7 upgrade in either of the proposed directions, or something else.

**Comment by ClearlyClaire** [comment]
> The underlying rails code did change in 7, so we'll need to update the monkey patch. Before I dig into it, is the background here (and need for this patch) that you could have a timing issue and race condition where sometime after a new status is started to be created (and where it's reblogging another status) but before its written to DB, the original status being reblogged is discarded, in which case the newly saved status will be saved as though it's reblogged a status but that original status is now nil?

What happens is that there can be race conditions in which posts can be marked as discarded (that is, soft-deleted, the record is still here but with a non-nil `deleted_at` column) between the time it has been selected for being reblogged and the reblog actually gets written to the database, resulting in a “non-discarded” (`deleted_at` is nil) reblog of a “discarded” status (`deleted_at` is not nil).

For most of the codebase, a discarded status is handled like a deleted one, but while we have database constraints that forbid a reblog of a deleted status, we can't have such a database constraint for soft-deletions.

> The naive thing here would be to add a rails model level validation so that during save the new status notices that the other one has been discarded and adds an error (and then stops the reblog service) so that doesn't happen.

This would at best narrow the race condition window but it would still be open.

> The next thing I can think of would be to not only add the validation, but also add an after_commit callback which reloads the referenced reblogged status, and then either destroys or also discards the just-created record running the callback. I think this would happen in advance of the reblog service proceeding as well, so you'd avoid having distributed the new status.

I think this would work, and be easier to understand and significantly more maintainable. But that's also an extra query in a hot path, so I'd prefer keeping the current approach if it is not too difficult to port.

**Comment by ClearlyClaire** [comment]
> In that latter case ... it'd be great to know which specs are relevant here. I'm guessing this linked one? https://github.com/mastodon/mastodon/pull/17732/files

Yes, this is the relevant test case, although it might be a bit too loose if we end up changing the logic, as something like your earlier proposal of adding a Rails validation would pass the test but still have a race condition window open.

**Comment by mjankowski** [comment]
> I think this would work, and be easier to understand and significantly more maintainable. But that's also an extra query in a hot path, so I'd prefer keeping the current approach if it is not too difficult to port.

Sounds good, I'll take that approach in the Rails 7 PR branch.

I also see that you did a quick refactor and spec improvement there, which I'll update PR against as well.

**Pull request merged**
