### PR TITLE
Expose the expand_spoilers user setting via the credentials API

### PR DESCRIPTION
**Pull request by Tak**

### CODE REVIEW

**Comment by connyduck** [comment]
This is an important feature for client apps, please merge it!

**Comment by Gargron** [comment]
We need a preferences API, sticking more and more properties into the source attribute feels increasingly unsustainable.

**Comment by Tak** [comment]
Ok, has there been any planning for that, or do you have guidance about an implementation you would approve?

**Comment by Gargron** [comment]
I have a vague idea of what it would look like. Something like /api/v1/preferences returning a hash of key/values. I imagine the keys would be namespaced similarly to OAuth scopes, via colons, and the names of the properties would not necessarily correspond to their in-database name, rather, we should aim for more understandable names and try to avoid underscores if possible.

**Pull request closed without merging**
