### PR TITLE
Avoid hitting database in some model specs when not needed

### PR DESCRIPTION
**Pull request by mjankowski**

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Makes sense overall, but in most cases, in the actual code, such records *are* persisted in the database. And like you pointed out in another PR, the underlying behavior may occasionally change between persisted and non-persisted records, so I think it might be wiser to stick with persisted records in more places as it's closer to what the production code actually does.

**Comment by mjankowski** [comment]
Fair enough -- I was looking for places we could get marginal speedup improvement in the spec run and this struck me as a path to pursue.

I agree that there's some risk here if you had diverging behavior, but in specifically places where the method is like, interpolating a string or otherwise just doing some basic ruby action on a basic attr where the DB didn't matter, it seems low risk.

Happy to close this if you'd prefer to not pursue this path, or to give it a once over around relative safety/risk of each change.

**Comment by ClearlyClaire** [comment]
> Fair enough -- I was looking for places we could get marginal speedup improvement in the spec run and this struck me as a path to pursue.

Have you measured the speedup? I would expect it to be extremely marginal, in which case I do not think it is worth the change.

**Comment by mjankowski** [comment]
Noted. Closing this for now.

May circle back on refactoring some of the truly non-DB-interacting methods out into POROs or helpers after I wrap up my coverage project, and see if that can have a nice side effect of reducing DB hits.

**Pull request closed without merging**
