### PR TITLE
Updated docker components

### PR DESCRIPTION
**Pull request by GoliathLabs**
Good day,
I've just updated the docker components of the docker-compose.yml.

Feel free to give some feedback regarding this. 

Cheers,
thegoliath

### CODE REVIEW

**Comment by shleeable** [comment]
1) While I deeply, want to approve a PR like this... Sadly Postgres doesn't "migrate" that way

image

You'll need to prepare a migration plan to backup and restore the DB to this new version. I've been meaning to help with this but it hasn't seemed to get a lot of traction from the high powers.

2) Redis doesn't need a hardcoded minor. Better to just say `redis:6` or whatever. the data in redis should be refreshed on upgrade anyway

3) I believe the ES can be upgraded that way without issue, but I needed to do some testing to confirm which version can upgrade to which version etc.

**Comment by GoliathLabs** [comment]
Thanks for the feedback so far. We may want to use something like https://gitlab.com/cyber5k/mistborn/-/blob/master/compose/production/postgres/Dockerfile is using.

**Comment by weex** [comment]
Bump on conflicts, maybe should be closed if this particular PR is a dead-end. Also, is there any specific motivation for the upgrades?

**Comment by GoliathLabs** [comment]
@weex We need to upgrade PostgreSQL sooner or later, as version 10 will see its final release already next year. So upgrading to a newer/current version might be advisable before version 10 reaches its EOL.

**Comment by weex** [comment]
@GoliathLabs Makes sense to me.

@shleeable When you mentioned migration plan are talking about something automated or simply a doc? I did one for a similar 4 major version upgrade that was essentially a dump and restore.

Does docker-compose have any features that help with such migrations?

**Comment by GoliathLabs** [comment]
This is not an issue directly related to docker-compose, but to how PostgreSQL handles major version upgrades. You need to manually upgrade the database via pg_upgrade.

In my opinion, I would upgrade the PostgreSQL image to the latest version. If you decide to upgrade your docker-compose file or do a git pull, you should check the changelog beforehand or manually upgrade the database to the latest available version when starting the containers. But I'm always open to other solutions and ideas.

**Comment by shleeable** [comment]
@GoliathLabs this change has been completed. Feel free to close

**Pull request closed without merging**
