### PR TITLE
chart: add a toggle to opt-out of the `rollme` pod annotation

### PR DESCRIPTION
**Pull request by nadiamoe**
The `mastodon.rollingPodAnnotations` template unconditionally adds a `rollme` annotation whose value is the current helm release number. The change to this annotaiton causes all pods to be recreated every `helm upgrade`.

This PR adds a simple boolean toggle, `revisionPodAnnotation`, which is set to true by default and allows to opt out of the `rollme` annotation. This keeps the change non-breaking, while allowing users to select a behavior that is more kubernetes-like: Pods will only be restarted if either their configuration or their spec changes.

### CODE REVIEW

**Comment by ineffyble** [comment]
For context here, the current situation is a result of https://github.com/mastodon/mastodon/pull/20184.

That PR was put in place because the existing mechanism that ensured that pods were rolled when there was a migration had a side-effect of breaking GitOps-style deployments.

Part of the reason for that previous mechanism is documented here: https://github.com/mastodon/mastodon/pull/19702

If this toggle is set for a Helm release, then upgrading may result in an error state where pods aren't rolled when they should be and things stop working. So it should be considered advanced usage and admins should understand the consequences.

**Comment by ineffyble** [comment]
@deepy can I get your thoughts on this?

**Comment by roobre** [comment]
@ineffyble I was aware of #20184, and I like the approach that was followed there: Random numbers are a definitely a no-go for gitops, and the checksum annotations are the common and idiomatic way of solving this.

I do not particularly agree with #19702. It is true that pods will not be recreated if their spec is the same, but in the event of an upgrade, the image tag will change (e.g. from `tootsuite/mastodon:v4.0.0` to `tootsuite/mastodon:v4.0.1`. This alone will cause pods to be recreated.

It is true that there are some changes where the image tag may not change, e.g. if the user overrides the default image tag and sets it to `latest`. For this reason I think it is alright for the option to add the `rollme` annotation to exist. But the way I see it, it is useful only in corner cases, so I think it is reasonable to at least provide a way to opt-out from it.

**Comment by deepy** [comment]
From having tested it I think this works as expected :+1:
I just haven't yet looked into if there's other corner cases than the tag being set to `latest` but I also don't see any reason why this couldn't be the new default in the future

#19702 was about fixing the (then) current state of the application, it was a bug that `rollme` only appeared if you set `podAnnotations` and at the time of that PR there was no checksum annotations.
In hindsight, I should've just replaced it with checksum annotations back then

As for `latest` as image tag, there's no way we should support this, with this you could get a partial system upgrade (imagine web running 3.5.5 and sidekiq upgrading to 4 because the pod was recreated)
The only time latest is supported is if you add the digest as well, but at this point the problem goes away as when you upgrade the spec will change.

**Comment by roobre** [comment]
>  In hindsight, I should've just replaced it with checksum annotations back then

Agreed. Do you think it is best to make the `rollme` annotation opt-out as it is now, or do you prefer to change it to opt-in in this PR?

I'm fine with either, but I think that if we change it to opt-in it might be a good idea to add some comments and perhaps a warning in `NOTES.txt` if the tag is manually overridden but `revisionPodAnnotation` is false.

**Review by ineffyble — APPROVED** [review]

**Review by deepy — APPROVED** [review]

**Comment by roobre** [comment]
Rebased `main`.

**Comment by deepy** [comment]
@roobre I think your rebase accidentally caught the wrong change

**Comment by Gargron** [comment]
Moving the Helm chart out to mastodon/chart

**Pull request closed without merging**
