### PR TITLE
Added new line to .gitignore file to ignore tmp dir in bin dir.

### PR DESCRIPTION
**Pull request by M-D-M**

### CODE REVIEW

**Comment by Gargron** [comment]
Why would there be a tmp directory in the bin directory?

**Comment by M-D-M** [comment]
> Why would there be a tmp directory in the bin directory?
I do not know.  It seems to be in my bin directory for some reason -- it formed after I started running cron tasks successfully with tootctl.  Is it just me and this hasn't happened for anyone else?

> mastodon@vm-mastodon-01:~/live/bin$ cd tmp
mastodon@vm-mastodon-01:~/live/bin/tmp$ ls -ltra
total 12
drwxrwxr-x 3 mastodon mastodon 4096 Nov 15 20:27 .
drwxrwxr-x 2 mastodon mastodon 4096 Nov 15 20:27 cache
drwxrwxr-x 3 mastodon mastodon 4096 Dec 10 14:26 ..
mastodon@vm-mastodon-01:~/live/bin/tmp$ cd cache
mastodon@vm-mastodon-01:~/live/bin/tmp/cache$ ls -ltra
total 2016
drwxrwxr-x 3 mastodon mastodon    4096 Nov 15 20:27 ..
-rw-rw-r-- 1 mastodon mastodon 2049324 Nov 15 20:27 bootsnap-load-path-cache
drwxrwxr-x 2 mastodon mastodon    4096 Nov 15 20:27 .
mastodon@vm-mastodon-01:~/live/bin/tmp/cache$

**Comment by M-D-M** [comment]
Just tested again -- removed the "tmp" directory that's in bin, and ran my cronjob again.  Created the same directory.  Very odd.

**Comment by Gargron** [comment]
Does your cronjob `cd` into the bin directory, maybe?

**Comment by Gargron** [comment]
I found the issue, the cache path is defined very loosely here: https://github.com/tootsuite/mastodon/blob/master/config/boot.rb#L7

**Pull request closed without merging**
