### PR TITLE
Change "bot" label to "automated"

### PR DESCRIPTION
**Pull request by Gargron**
Less negative connotation.
___

Fixes MAS-156

### CODE REVIEW

**Comment by digitalf0x** [comment]
This might also clarify the intent of the badge (unmonitored accounts where there's no point in responding) for some folks who view `Bot` as a *positive* label (e.g. mechanical and robot-adjacent creatures).

Though it is unfortunate to diminish the fun use of the badge for them, hopefully this makes it easier to actually filter automated accounts using this signal (e.g. having a timeline of hourly photo bots).  Custom emoji in display names might help make up for the loss and allow a wider range of identification options.

**Review by ykzts — APPROVED** [review]

**Comment by Gargron** [comment]
The hint for "This is a bot account" on the profile edit page says "Signal to others that the account mainly performs automated actions and might not be monitored".

**Comment by moshpirit** [comment]
Not English native speaker. Why does "bot" have a negative connotation?

**Comment by ocdtrekkie** [comment]
> Not English native speaker. Why does "bot" have a negative connotation? 

We often use the word "bot" in tandem with spam or junk, because a lot of scripted bots are used to post spam and junk. Whereas a perfectly well-managed account might automatically post content.

**Pull request merged**
