### PR TITLE
Fix crash when a status has not been correctly loaded

### LINKED ISSUE #7899: Entire webpage crashes when "unhiding all" for a thread you can't view all of
When trying to reproduce #8117, it also triggers a nasty rendering bug:
- open one toot of user1 except the first
- click on «Show more for all»
- rendering issue causing all the `div#mastodon` to be empty.

The rendering errors seem to arise from the fact that it tries to «show more» on statuses with IDs that aren’t showed in the interface.

<details>
  <summary>Javascript stacktrace</summary>

```
The above error occurred in the <Status> component:
    in Status (created by Connect(Status))
    in Connect(Status) (created by InjectIntl(Connect(Status)))
    in InjectIntl(Connect(Status)) (at index.js:334)
    in div (at index.js:385)
    in div (at index.js:413)
    in ScrollContainer (at index.js:412)
    in div (at column.js:59)
    in Column (at index.js:404)
    in Status (created by Connect(Status))
    in Connect(Status) (created by InjectIntl(Connect(Status)))
    in InjectIntl(Connect(Status)) (at react_router_helpers.js:50)
    in Bundle (created by Connect(Bundle))
    in Connect(Bundle) (at react_router_helpers.js:49)
    in Route (at react_router_helpers.js:66)
    in WrappedRoute (at index.js:159)
    in Switch (at react_router_helpers.js:16)
    in WrappedSwitch (at index.js:139)
    in div (at columns_area.js:175)
    in ColumnsArea (created by InjectIntl(ColumnsArea))
    in InjectIntl(ColumnsArea) (created by Connect(InjectIntl(ColumnsArea)))
    in Connect(InjectIntl(ColumnsArea)) (at index.js:138)
    in SwitchingColumnsArea (at index.js:452)
    in div (at index.js:449)
    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    in HotKeys (at index.js:448)
    in UI (created by Route)
    in Route (created by withRouter(UI))
    in withRouter(UI) (created by InjectIntl(withRouter(UI)))
    in InjectIntl(withRouter(UI)) (created by Connect(InjectIntl(withRouter(UI))))
    in Connect(InjectIntl(withRouter(UI))) (created by Route)
    in Route (at mastodon.js:66)
    in ScrollContext (created by Route)
    in Route (created by withRouter(ScrollContext))
    in withRouter(ScrollContext) (at mastodon.js:65)
    in Router (created by BrowserRouter)
    in BrowserRouter (at mastodon.js:64)
    in Provider (at mastodon.js:63)
    in IntlProvider (at mastodon.js:62)
    in Mastodon (at main.js:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:9643
The above error occurred in the <Connect(InjectIntl(ColumnsArea))> component:
    in Connect(InjectIntl(ColumnsArea)) (at index.js:138)
    in SwitchingColumnsArea (at index.js:452)
    in div (at index.js:449)
    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    in HotKeys (at index.js:448)
    in UI (created by Route)
    in Route (created by withRouter(UI))
    in withRouter(UI) (created by InjectIntl(withRouter(UI)))
    in InjectIntl(withRouter(UI)) (created by Connect(InjectIntl(withRouter(UI))))
    in Connect(InjectIntl(withRouter(UI))) (created by Route)
    in Route (at mastodon.js:66)
    in ScrollContext (created by Route)
    in Route (created by withRouter(ScrollContext))
    in withRouter(ScrollContext) (at mastodon.js:65)
    in Router (created by BrowserRouter)
    in BrowserRouter (at mastodon.js:64)
    in Provider (at mastodon.js:63)
    in IntlProvider (at mastodon.js:62)
    in Mastodon (at main.js:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:9643

TypeError: status.get(...) is undefined. common.js line 2007 > eval:274:9
render
status.js:181
finishClassComponent
react-dom.development.js:8389
updateClassComponent
react-dom.development.js:8357
beginWork
react-dom.development.js:8982
performUnitOfWork
react-dom.development.js:11814
workLoop
react-dom.development.js:11843
callCallback
react-dom.development.js:100
invokeGuardedCallbackDev
react-dom.development.js:138
invokeGuardedCallback
react-dom.development.js:187
replayUnitOfWork
react-dom.development.js:11318
renderRoot
react-dom.development.js:11885
performWorkOnRoot
react-dom.development.js:12449
performWork
react-dom.development.js:12370
performSyncWork
react-dom.development.js:12347
interactiveUpdates
react-dom.development.js:12597
interactiveUpdates
react-dom.development.js:1958
dispatchInteractiveEvent
react-dom.development.js:4259
dispatchInteractiveEvent self-hosted:1031:17

TypeError: c is null. application.js line 182 > eval:139:7
SwitchingColumnsArea/_this.setRef
index.js:129
callCallback
react-dom.development.js:100
invokeGuardedCallbackDev
react-dom.development.js:138
invokeGuardedCallback
react-dom.development.js:187
safelyDetachRef
react-dom.development.js:9723
commitUnmount
react-dom.development.js:9953
commitNestedUnmounts
react-dom.development.js:9992
unmountHostComponents
react-dom.development.js:10279
commitDeletion
react-dom.development.js:10329
commitAllHostEffects
react-dom.development.js:11413
callCallback
react-dom.development.js:100
invokeGuardedCallbackDev
react-dom.development.js:138
invokeGuardedCallback
react-dom.development.js:187
commitRoot
react-dom.development.js:11559
completeRoot
react-dom.development.js:12502
performWorkOnRoot
react-dom.development.js:12452
performWork
react-dom.development.js:12370
performSyncWork
react-dom.development.js:12347
interactiveUpdates
react-dom.development.js:12597
interactiveUpdates
react-dom.development.js:1958
dispatchInteractiveEvent
react-dom.development.js:4259
dispatchInteractiveEvent self-hosted:1031:17

TypeError: status.get(...) is undefined. common.js line 2007 > eval:274:9
render
status.js:181
finishClassComponent
react-dom.development.js:8389
updateClassComponent
react-dom.development.js:8357
beginWork
react-dom.development.js:8982
performUnitOfWork
react-dom.development.js:11814
workLoop
react-dom.development.js:11843
renderRoot
react-dom.development.js:11874
performWorkOnRoot
react-dom.development.js:12449
performWork
react-dom.development.js:12370
performSyncWork
react-dom.development.js:12347
interactiveUpdates
react-dom.development.js:12597
interactiveUpdates
react-dom.development.js:1958
dispatchInteractiveEvent
react-dom.development.js:4259
dispatchInteractiveEvent self-hosted:1031:17
```
</p></details>

### PR DESCRIPTION
**Pull request by ariasuni**
fix #7899

### CODE REVIEW

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Ok, while your fix should work, I think the core of the issue lies in the reducer, specifically in the following lines:
https://github.com/tootsuite/mastodon/blob/9a1a55ce526c956ac6b35897d483c316b7ad4394/app/javascript/mastodon/reducers/statuses.js#L46-L57

Indeed, in those cases, if the status `id` does not exist in the state, it will create a “shallow” object only containing the `muted` or `hidden` property. I am not sure that case can occur with `muted`, but it can apparently happen with `hidden`, because of how contexts are loaded.

In this case, I would suggest not performing the `setIn` for statuses not already known, as it may cause issues in more than just the rendering code.

**Comment by ariasuni** [comment]
I understand your comment but I’m not sure what you’re suggesting. If you think it’s better to change the part of the code you highlighted, then I don’t know how to know if a status is already known from the `id`.

**Comment by ThibG** [comment]
I have limited connectivity right now so I can't look it up, but I think something like “state.get(id)” should return undefined if the status isn't known and an object otherwise.

Le 6 août 2018 15:11:53 GMT+02:00, "Mélanie Chauvel (ariasuni)" <notifications@github.com> a écrit :
>I understand your comment but I’m not sure what you’re suggesting. If
>you think it’s better to change the part of the code you highlighted,
>then I don’t know how to know if a status is already known from the
>`id`.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tootsuite/mastodon/pull/8118#issuecomment-410702778

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ariasuni** [comment]
I don’t know what’s wrong with `test-ruby2.4`, but it doesn’t seem to be caused by my change.

**Comment by ThibG** [comment]
I don't know what's going on with it either, but that's definitely not because of your change. It's a bug I have seen for a while in CI builds and haven't managed to understand yet.

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me!

**Pull request merged**
