### PR TITLE
Add tootctl command to mark remote media for redownload 

### LINKED ISSUE #16456: tootctl command to trigger re-download of remote media
### Pitch

It seems the `public/system/cache` directory could be excluded from backups to save on backup space, this would need to be able to mark remote media as needing a redownload.

See the [discussion on the Mastodon Discourse](https://discourse.joinmastodon.org/t/can-the-cache-directory-be-removed-from-backups/3683?u=thegcat).

### Motivation

This would benefit administrators to reduce storage needs for backups.

### PR DESCRIPTION
**Pull request by weex**
_Recreating this PR (#16457) that had discussion and an approval but mistakenly closed when the topic branch was deleted. Trying to cleanup the topic branches in that repo so this is the better PR to have open._

Makes excluding public/system/cache from backups more convenient, thereby allowing for smaller backups. After restore, running the command mark-media-missing will mark all remote media to be downloaded again from the source server.

Implemented @ClearlyClaire's suggestion from https://discourse.joinmastodon.org/t/can-the-cache-directory-be-removed-from-backups/3683/4 to fix #16456.

No errors occurred testing RAILS_ENV=development bin/tootctl media mark-media-missing on a relatively blank development instance.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by RainofTerra** [comment]
This code was extremely useful for migration, I see it was approved  but then closed instead of merged, @weex was there a reason for that or was it just a branch closure error or something? Thanks for the code either way!

**Comment by weex** [comment]
I merged that branch elsewhere and had no need to keep recreating the branch. It's here for the record in any case. Glad you got it.

**Comment by keskival** [comment]
This code was extremely useful and approved. Could we get it merged to Mastodon proper as well?

**Comment by weex** [comment]
Looks like this needs to be rebased but I don't think I'm going to get to it. Feel free to take the code and create a new PR.

**Comment by keskival** [comment]
Actually I think `tootctl media remove` does the same thing after I dug a bit deeper into this.

**Pull request closed without merging**
