### PR TITLE
nodeinfo: expose admin contact

### PR DESCRIPTION
**Pull request by 6543**
with this one dont need to handle mastodon as edgecase

ref: https://codeberg.org/thefederationinfo/nodeinfo-go/src/commit/4bb03bed8c8d88bfae21511267c051e0a5102d6b/extension/mastodon.go#L45

### CODE REVIEW

**Comment by 6543** [comment]
this is a followup to #28079  and was not initial included as is till learn the codebase ;)

**Comment by 6543** [comment]
@ClearlyClaire do you have time to look at it? or is it feature freeze right now?

**Comment by 6543** [comment]
the tldr is, to not have such code: https://codeberg.org/thefederationinfo/nodeinfo-go/src/branch/main/extension/mastodon.go

:)

**Comment by 6543** [comment]
@Gargron any updates?

**Comment by 6543** [comment]
@ ClearlyClaire sorry of the ping - just have no idea what is missing or whats going on :/

**Comment by 6543** [comment]
@ClearlyClaire sorry of the ping - just have no idea what is missing or whats going on :/

**Comment by 6543** [comment]
If the contribution is now welcome just tell me - gosting is bad :/

or tell if you dont have time to review/merge it jet ...

**Comment by ClearlyClaire** [comment]
Hi. Please keep in mind that the Mastodon development team is very small and spread thin across many tasks.

Your previous PR (#28079) brought Mastodon in line with various other implementations, but it seems that is not the case of the current PR and what you're pushing for here is a novel attribute. I don't fundamentally oppose that, but this needs more consideration

**Comment by 6543** [comment]
@ClearlyClaire thanks for the answer !!!

❤️ 

Well that's fine.

In this case, I'll close the pull.

More dessisions to standardize are currently taken at https://github.com/jhass/nodeinfo/issues/76

And for this exact case, we currently discusst at https://github.com/jhass/nodeinfo/pull/84

Feel free to take part in it.

I would create a pull for that spec once it's finished.

**Pull request closed without merging**
