### PR TITLE
[wip] Implementation of private messaging

### PR DESCRIPTION
**Pull request by hach-que**
I started working on an implementation of private messaging.  At the moment, I haven't implemented the federation protocol for it - this is just sort of the UI basics + data storage.

However, I'm a little bit puzzled as to why the when the API executes it's view, `current_user.id` doesn't seem to match the actual current user ID, which causes the visibility of private messages to be incorrect.  For some reason, when user `3` hits the public timeline endpoint, the resulting JSON has `current_user_id: 2` in it.  I'm not sure if there's some built-in caching layer on the API that persists across application restarts, but I couldn't find anything in the database that would suggest caching there, and the issues continues to occur even across application restarts and users logging in/out.  So I'm quite puzzled as to how `current_user.id` can have a value of `2` when the view executes for user `3`.

Otherwise, here's some screenshots (at the moment private messages appear in timelines other than "Home", but the intention is the client will hide them, and the API will not expose them in these circumstances):

image

image

Until I can figure out the API `current_user` bug and implement the rest of this, I don't expect this to be merged.

### CODE REVIEW

**Comment by hach-que** [comment]
Rebasing to resolve conflicts now...

**Comment by hach-que** [comment]
Okay, I think that rebase should be good.

**Comment by hach-que** [comment]
For reference, this is a snippet of the JSON I see coming back from the `public` API endpoint in the second screenshot (where the current user should be user ID `3`):

```json
[
  {
    "id": 7,
    "created_at": "2016-11-26T13:46:26.562Z",
    "in_reply_to_id": null,
    "is_private": true,
    "account": {
      "id": 1,
      "username": "hqtest",
      "acct": "hqtest",
      "display_name": "",
      "note": "",
      "url": "http:\/\/localhost\/users\/hqtest",
      "avatar": "http:\/\/localhost:3000\/avatars\/large\/missing.png",
      "header": "http:\/\/localhost:3000\/headers\/medium\/missing.png",
      "followers_count": 0,
      "following_count": 0,
      "statuses_count": 4
    },
    "media_attachments": [
      
    ],
    "mentions": [
      
    ],
    "tags": [
      
    ],
    "uri": "tag:localhost,2016-11-26:objectId=7:objectType=Status",
    "content": "<p>This is a private message<\/p>",
    "url": "http:\/\/localhost\/users\/hqtest\/updates\/7",
    "reblogs_count": 0,
    "favourites_count": 0,
    "current_user_id": 2,
    "account_id": 1,
    "private_recipient_id": 2,
    "private_content": "<p>hello2<\/p>",
    "private_recipient": {
      "id": 2,
      "username": "hq",
      "acct": "hq@mastodon.social",
      "display_name": "June",
      "note": "game developer - she\/her - @hachque (Twitter) - https:\/\/www.redpointgames.com.au\/ ",
      "url": "https:\/\/mastodon.social\/users\/hq",
      "avatar": "http:\/\/localhost:3000\/system\/accounts\/avatars\/000\/000\/002\/large\/Avatar.jpg",
      "header": "http:\/\/localhost:3000\/headers\/medium\/missing.png",
      "followers_count": 0,
      "following_count": 0,
      "statuses_count": 0
    },
    "reblog": null,
    "favourited": false,
    "reblogged": false
  },
  "more entries here...."
]
```

**Comment by Gargron** [comment]
I'm sorry, but this won't work. There's no reason to include current user in API response (the UI is already aware which user is logged in). And you should not stick so much new unrelated stuff into the status model... private messages would warrant their own model and API. I appreciate that you are motivated to contribute to the project but I am not ready to accept such big changes to the system without agreeing to them beforehand.

**Comment by hach-que** [comment]
For rererence, I did outline the proposal here: https://github.com/Gargron/mastodon/issues/223

The current user isn't supposed to be in the response - that's just debugging information to try and figure out why the API does not appear to have to correct user information when responding.

As I said above, this is WIP / not intended to be merged as-is, but it's impossible to even have a private messages endpoint if that endpoint doesn't know what the current user is, or if the result of endpoints is being implicitly cached somewhere.

The purpose of this PR is to ask you if you know of any reasons why the current user would not be correct when the API is processing a response.

**Pull request closed without merging**
