### PR TITLE
Refactor raw SQL queries to use Arel

### PR DESCRIPTION
**Pull request by Gargron**
Close #15828

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Honestly I find that a lot messier and less readable than #15828 :/

**Comment by ClearlyClaire** [comment]
Honestly, I'm pretty split with this one. It abstracts things away in such a way some of it might be easier to grasp, but there is just so much happening here, I am not sure it's a net positive overall.

Stuff like generating the `tsvector` from a `FIELDS` is a rather elegant abstraction (it might be my favorite part of the PR), but its usefulness is limited by the fact the vector needs to exactly match the one used for the database index.

And of course, I'm still wary of the reliance on `ARel` in the lower-level methods, as `ARel` is very verbose, difficult to read, undocumented, and considered a private API with no stability guarantee across even minor versions of Rails, as well as relying on another low-level dependency (`activerecord-cte`) which has relatively few users.

**Comment by Gargron** [comment]
A month onwards, I took another look at both PRs, and I still prefer this one. It eliminates repetition between 3 large, different-but-similar query executions. I think while individual query parts written using Arel are perhaps harder to read at a glance, their composition is more understandable.

Also, the quotation of the query term is more understandable in this format, and in the other PR it changes the results for some terms due to being written differently.

**Comment by ClearlyClaire** [comment]
> A month onwards, I took another look at both PRs, and I still prefer this one. It eliminates repetition between 3 large, different-but-similar query executions. I think while individual query parts written using Arel are perhaps harder to read at a glance, their composition is more understandable.

I still think “individual query parts written using Arel are perhaps harder to read at a glance” is a pretty big understatement.
I do agree that the composition is more understandable to some extent.

> Also, the quotation of the query term is more understandable in this format, and in the other PR it changes the results for some terms due to being written differently.

I don't think it's more understandable than in the other PR. Which results are different?

**Pull request closed without merging**
