### PR TITLE
Change error page on host validation failure

### PR DESCRIPTION
**Pull request by ClearlyClaire**
The rationale is that the error message misleads admins into thinking they should add something to `config.hosts` while this error is indicative of a reverse-proxy misconfiguration, or an error in any of the `LOCAL_DOMAIN`, `WEB_DOMAIN` or `ALTERNATE_DOMAINS` variables.

Indeed, since the introduction of #16087, I have seen multiple support requests asking where to edit `config.hosts` while ignoring the underlying problem. I believe a proper error message would help everyone here.

## Before

image

### Reverse-proxy misconfiguration not detected

image

### Reverse-proxy misconfiguration detected

When `window.location.hostname` does not match the `Host` header received by Puma, the following is displayed (`mastodev.lan` is from the `window.location.hostname`, not leaked from the configuration):

image

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Rather than redirecting, which might cause issues such as leaking the instance name if an attacker tries to access random addresses, I'm thinking a custom error page may be preferable.

## Before

image

## After

image

**Comment by ClearlyClaire** [comment]
Updated the design, wording, and added a javascript bit to further highlight if there seem to be a reverse-proxy misconfiguration.

## Reverse-proxy misconfiguration not detected

image

## Reverse-proxy misconfiguration detected

image

**Comment by ClearlyClaire** [comment]
Some notes:
- the CSS and Javascript are simplified and inlined to avoid any risk of leaking domain information (e.g. by using the assets pipeline and `CDN_HOST`)
- the Javascript is using old APIs and basic syntax, maximizing compatibility without needing transpiling or anything
- localization could make sense, but this would be more involved, and I expect most admins would understand at least a bit of English. The previous error page wasn't translatable either

**Review by ykzts — APPROVED** [review]

**Comment by Gargron** [comment]
I’m not entirely comfortable with a public page revealing configuration information. I think that ideally it would use the template with the elephant and just say that the server is not accessible from that domain, then print more stuff into the rails log.

**Comment by ClearlyClaire** [comment]
The only thing this reveals is the `Host` header Mastodon sees. It's already in the current error message.

**Comment by Gargron** [comment]
But it’s openly technical. It assumes the viewer is a sysadmin or programmer. My assumption is that this would be off-putting/scary to a random visitor.

**Comment by ClearlyClaire** [comment]
Yes, it's indeed openly technical. In most cases, this would happen right after update or initial install, so one of the first people to see this would probably be the admin. Furthermore, the JS bits is useful to point the admin to the precise issue.

**Comment by mjankowski** [comment]
Is it possible for this to be a static error page in `public/`, or does it need the custom app render?

**Comment by renchap** [comment]
I think this could be useful. What about using the elephant error page template, but with a `<details>` part titled "If you are the server administrator" or something, which shows the full technical error?

**Comment by ClearlyClaire** [comment]
> Is it possible for this to be a static error page in `public/`, or does it need the custom app render?

It needs to go through the controller to get the `Host` value Rails sees

**Comment by mjankowski** [comment]
The default framework page for this has SLIGHTLY more info now:

Screenshot 2024-10-23 at 14 54 38

Still not what I'd call naive-admin-friendly, but a small improvement.

**Comment by ClearlyClaire** [comment]
Yeah, but admins should not have to mess with `config.hosts` so this change may end up being more misleading/confusing than anything else :/

**Comment by ClearlyClaire** [comment]
I'm ok with closing it if we can't reach consensus, but I still think this could be useful.

I do still hear about people running into these kind of issues from time to time, but it has gotten quite rare compared to when I wrote this PR. Not sure what may have changed for us to see les of this.

**Comment by mjankowski** [comment]
Cool, going to close from lack of consensus ... I wonder if doc improvements and/or various issues with solutions have led to increase in people being able to self-solve the issue if/when it still happens.

We can revisit if this becomes a regular issue again.

**Pull request closed without merging**
