### PR TITLE
Replace Travis to CircleCI

### PR DESCRIPTION
**Pull request by ykzts**
Travis CI is very slow 😢 In this Pull Request, delete the configuration file of Travis CI and add the configuration file of CircleCI.

[Workflows](https://circleci.com/docs/2.0/workflows/) can be used in CircleCI. By using Workflows, duplicate processing can be omitted, contributing to speedup.

To merge this Pull Request, you need to enable CircleCI.

### Before (Travis CI)

Screenshot on Travis CI

### After (CircleCI)

Screenshot on CircleCI

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
I've signed up on CircleCI and merged this.

I think the build badge in README needs to be updated. Also, I cannot find a GitHub integration for CircleCI, will the PR build status be displayed in PRs?

**Comment by Gargron** [comment]
Also I wonder if testing Ruby 2.4 is still necessary. There are hardly any breaking changes between 2.4 and 2.5, I believe, if it works on one, it should work on the other...

**Comment by ykzts** [comment]
Thank you for merge this Pull Request!

The build status will be displayed when a new Pull Request is created.

**Comment by ykzts** [comment]
I think it is necessary to tests also in Ruby v2.4.

Mastodon dependence on multiple extension library for Ruby. These things are version incompatible and sometimes break.

**Pull request merged**
