### PR TITLE
Sign follow/unfollow request of federation relay

### PR DESCRIPTION
**Pull request by u1-liquid**
ActivityPub::DeliveryWorker.perform_async doesn't signing request payloads.
It should be signed by caller, obviously.

I just confirmed this works without relay server changes.
image

### CODE REVIEW

**Comment by u1-liquid** [comment]
related #8485

**Comment by Gargron** [comment]
That doesn't seem necessary as the message doesn't need to be forwarded anywhere. So this change doesn't really do anything..?

**Comment by u1-liquid** [comment]
As reported in #8485 , Some of instances having trouble following relay server.  
Solution suggested by @mdbraber was actually works for my instance ( tsuki.network )
I thought that "https://w3id.org/security/v1" context prevents request being processed.

.... Maybe I'm wrong and it might be timing or mystery bug of relay server.

**Comment by u1-liquid** [comment]
I suspect as per https://source.joinmastodon.org/mastodon/pub-relay/blob/master/src/inbox_handler.cr#L20 will requires json signing for all of received requests.
actually I'm curious why it gives 202 for unsigned request...

**Comment by Gargron** [comment]
It's resolved: https://github.com/tootsuite/mastodon/issues/8485#issuecomment-417520855

**Comment by u1-liquid** [comment]
It's strange, I could not enable without this when I tried it just a while ago ...
Anyway, I just confirmed that the relay status can be turned 'Enabled' with latest master repository.
Sorry for interrupting you!

**Pull request closed without merging**
