### PR TITLE
Switch to compose view when tapping 'mention' in dropdown on mobile

### PR DESCRIPTION
**Pull request by blackle**
puts the layout check in an `isMobile` function so we can use the idiom `isMobile(window.innerWidth)` elsewhere in the code to do mobile-only logic

### CODE REVIEW

**Comment by blackle** [comment]
it looks like the travis check is hanging on this?

**Comment by Gargron** [comment]
Can you move the `isMobile` check out of `/components` since it's not a component? Maybe a `utils.js`

**Comment by blackle** [comment]
sure, which folder should that be in?

**Comment by Gargron** [comment]
Top level where `emoji.jsx` lies

**Pull request merged**
