### PR TITLE
Add ability to middle-mouse click posts in web UI

### LINKED ISSUE #29835: right-click in browser to open post in new tab
### Pitch

Enable right-click in browser to open post in new tab.

### Motivation

It is useful to be able to scroll down the web page and select several posts to read further, including their replies.

This is made much easier if we can right-click and "open in new tab". This was possible with the Twitter web interface.

The current mastodon web interface doesn't allow this, and it means clicking to a post, and then returning - which means the view of posts often changes due to the updated timeline.

This request should not cause any regressions. I believe it is an oversight and not intentionally disallowed. I think right-clicking a profile name/icon on a post does allow open in new tab.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #29835

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by disabledautomatic** [comment]
Very happy to see this being implemented. <3 I did however immediately notice that in the current nightly version running on mastodon.social (v4.4.0-nightly.2024-11-23) the middle click redirects you to the post source instance and not to the copy on your home instance. 

This means that every time you want to open a post in a new tab you will leave your home instance and will be forced to accept the "You are leaving mastodon.social." dialogue.

Being able to go to the post source can be useful, but it imo should only happen when you clearly intend to do so by clicking on the little world icon/timestamp. I think the post header should just open the post on your home instance.

**Comment by ClearlyClaire** [comment]
What you are describing is middle-clicking when logged out, I believe. I am unable to reproduce this when logged-in.

**Comment by disabledautomatic** [comment]
Ah nice catch. I indeed am not logged in usually so that makes sense. Do you think there might be a reason for it to be different from the logged in experience or is this just a bug?

**Comment by ClearlyClaire** [comment]
There is a reason: we do not want people to link to one server for content it is not authoritative for (and the reason for the “You are leaving mastodon.social” thing is that we don't want people to be confused if they land on a different interface, and to avoid open redirects)

**Comment by disabledautomatic** [comment]
> for content it is not authoritative for

That seems like a decent reason and its honestly not a huge problem, but i dont fully understand it yet.

The post content still exists on the server that you are viewing the post from no matter where it was authored.
So it wont prevent any legal issues i would think. 

Maybe to prevent other servers from getting spammed with requests for a post linked to from elsewhere? But that could be counterproductive too if a small server gets all the load for a post linked to by a popular site/user.

**Pull request merged**
