### PR TITLE
Added Thai diacritics and tone marks in HASHTAG_INVALID_CHARS_RE

### LINKED ISSUE #25705: Thai tone marks and diacritics not shown in hashtags under hashtag search/explore/trending
### Steps to reproduce the problem

1. Search for hashtags with tone marks or diacritics in Thai.
2. Or see hashtags in Thai language as it's trending.
3. The hashtags would not have tone marks or diacritics, such as เบอร์, ล่ม, สิ่งแวดล้อม being shown as เบอร, ลม, สิงแวดลอม. The problem is also present in Mastodon for iOS after tapping on the hashtag in posts and while composing a new post.

Sometimes, the same hashtag both with tone marks/diacritics and without it are shown in the same result page. Additionally, searching for either versions of the same hashtag shows both.

### Expected behaviour

Thai tone marks and diacritics above characters should be included in hashtags shown in Trending and search results, and should be treated the same as regular characters.

### Actual behaviour

Thai tone marks and diacritics above characters are excempt from showing in hashtags.

### Detailed description

Searching for #ทวิต brings up these results:
image

Another same search on mastodon.social:
image

On Mastodon for iOS (under mastodon.in.th), tapping on a hashtag (in this case #ไกด์ช้างม่วง) shows the one without tone marks and diacritics upon finished loading:
IMG_8528

Also on Mastodon for iOS under the same instance, but in the New Post field while selecting hashtags:
IMG_8534

### Specifications

As a regular user, I've found this problem with Mastodon 4.1.2 on https://mastodon.in.th & Mastodon 4.1.2+nightly-20230627 on https://mastodon.social.

### PR DESCRIPTION
**Pull request by ppnplus**
I added the range U+0E47 - U+0E4E to HASHTAG_INVALID_CHARS_RE, which could help resolve #25705.

### CODE REVIEW

**Review by slamp — APPROVED** [review]
Seems OK for me

**Comment by ClearlyClaire** [comment]
Sorry, due to my lack of knowledge of Thai, I may not understand the issue correctly.

For other languages, diacritics are usually part of the spelling, and we can't automatically pick the “right” spelling, so we leave that up to admins to fix the canonical “display name”.

If I understand correctly, you expect `#เบอร์` and `#เบอร` to be the same hashtag, and be listed without diacritics in its “normal” form?

**Comment by mishari** [comment]
@ClearlyClaire when I'm in the server mastodon.in.th and I search for hashtags, there's #ทวิตล่ม which is correct, but when I click on it, on the next page the tone mark on ล่ม has been stripped

https://mastodon.in.th/tags/%E0%B8%97%E0%B8%A7%E0%B8%B4%E0%B8%95%E0%B8%A5%E0%B9%88%E0%B8%A1

image

You can see the correct hashtag on top, with an incorrect "ทวิตลม" at the bottom.

**Comment by ClearlyClaire** [comment]
Then you expect the diacritics to be kept? But this pull request is meant to remove them. I'm a bit confused.

**Comment by ClearlyClaire** [comment]
Wait, I misunderstood. The PR is indeed about keeping diacritics, as you'd expect. I misread the original issue, and I understand now.

A caveat to be aware of, though: `#เบอร์` and `#เบอร` are considered to be the same hashtag, and the first version used is picked up, so if the latter is used, it's the version that will be kept.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ppnplus** [comment]
@ClearlyClaire
> A caveat to be aware of, though: `#เบอร์` and `#เบอร` are considered to be the same hashtag, and the first version used is picked up, so if the latter is used, it's the version that will be kept.

Well, I expect both of these to be considered different hashtags. Currently, hashtags returned by the server doesn't have tone marks or diacritics as I expect. In Thai language, having tone marks and diacritics removed changes the word's meaning, making it unable to read the word. It affects usability for the Thai community.

https://user-images.githubusercontent.com/503018/274454114-a1a4be4d-79a6-44f3-a9ef-4bb456ee9057.png

I appreciate your guidance.

**Comment by ClearlyClaire** [comment]
Sorry, I'm still confused. We “normalize” tags by internally normalizing encoding, folding case, and removing diacritics. This is so posts using a hashtag can be found despite changes in case or minor mispellings.

Because Mastodon can't know what's the correct or most legible spelling is, the version that will be displayed is the first that is encountered, but that can be overridden by server admins.

Are there many Thai words that only differ in diacritics?

**Comment by veer66** [comment]
> Sorry, I'm still confused. We “normalize” tags by internally normalizing encoding, folding case, and removing diacritics. This is so posts using a hashtag can be found despite changes in case or minor mispellings.

I guess I understand I usually confuse between tu and tú, when I learn Spanish on Duolingo.

> Because Mastodon can't know what's the correct or most legible spelling is, the version that will be displayed is the first that is encountered, but that can be overridden by server admins.

We can make an acception for Thai tone marks, as proposed in this patch.

> Are there many Thai words that only differ in diacritics?

Yes, there are many. About 40% of Thai words have tone mark. For example, ปูตาย means a crab died, ปู่ตาย means grand farher died. Both make sense, so I cannot guess.

**Comment by ClearlyClaire** [comment]
> Yes, there are many. About 40% of Thai words have tone mark. For example, ปูตาย means a crab died, ปู่ตาย means grand farher died. Both make sense, so I cannot guess.

I see, thanks for explaining! I guess the change makes sense then! I'm not sure how it'd interact with the client-side matching we do in `app/javascript/mastodon/components/hashtag_bar.tsx` though (but we want to do everything server-side at some point).

**Comment by ppnplus** [comment]
You’re welcome! I no longer see this problem in the hashtag bar below posts (which I’ve mentioned & included a screenshot in #25705 few months ago), but I’ll look into the client-side code that you’ve suggested.On 14 Nov 2023, at 22:04, Claire ***@***.***> wrote:﻿

Yes, there are many. About 40% of Thai words have tone mark. For example, ปูตาย means a crab died, ปู่ตาย means grand farher died. Both make sense, so I cannot guess.

I see, thanks for explaining! I guess the change makes sense then! I'm not sure how it'd interact with the client-side matching we do in app/javascript/mastodon/components/hashtag_bar.tsx though (but we want to do everything server-side at some point).

**Pull request merged**
