### PR TITLE
i18n: Add Hebrew interface translation

### PR DESCRIPTION
**Pull request by seefood**
* follow the instructions for registering the language as stated on the Tootsuite's docs.

* Added translation strings from latest master

Adding &rlm; characters to many strings that are misdirected in the interface.

A tiny grammar fix

Updates of Hebrew strings to v1.3.1

Hebrew translation of the mailer templates.

Fix strings and a missing comma.

Just discovered two string keys were updated. this should lay Travis' mind to rest at last.

Remove mentions before counting characters to decide RTL ratio

Fixes for PR #2573

updated strings for latest master

Undo RTL counting, moved out to another branch for future consideration...

Updates and changes, still with unicode issues

Fixed and added to list of RTL languages. works nicely in development env :)

### CODE REVIEW

**Comment by Gargron** [comment]
This PR is aimed to the 1.3-stable branch instead of master?

**Comment by seefood** [comment]
I saw the branches diverged and 1.3.3 is not on master and does not include my previous PR, so...

Also updated the translations on master, adding a new PR now (file locations changed, strings updated or removed, a few grammar fixes etc)

**Comment by Gargron** [comment]
There will likely not be any more 1.3.x updates - 1.3.3 was a backport.

**Comment by seefood** [comment]
Okie dokie then, I'll just continue at #2880

**Pull request closed without merging**
