### PR TITLE
Filter Superlinter to Ruby files only

### PR DESCRIPTION
**Pull request by nschonni**
Superlinter uses it's own versions of tools rather than the ones in the project lock files.
This increases the number of jobs, but those jobs now only run if a related file is touched by filtering with the `path` globs.
There are new failures from the Rubocop run that is probably coming from a difference between the project and Superlinter version

### CODE REVIEW

**Comment by ineffyble** [comment]
If we're merging this can we also merge https://github.com/mastodon/mastodon/pull/20993?

**Comment by nschonni** [comment]
@ineffyble just checking that you're asking that the other PR gets landed, not merged into this PR. I think the separate approach over there makes sense, and is a similar approach to the splitting here

**Comment by darronschall** [comment]
This is possibly an unrelated bug, but might be worth exploring while you're switching up rubocop linting.

When I run `bundle exec rubocop` locally, my results differ than the lint-ruby job. (I've freshly cloned the repository, and have done nothing other than setup and run specs).

```bash
 bundle exec rubocop --version
1.39.0
```

```bash
bundle exec rubocop

# output omitted...

1899 files inspected, 7447 offenses detected, 4208 offenses autocorrectable
```

The lint job inspects 960 files, but locally my run inspects 1899.

For example, I'm seeing a lot of `to_not` used in specs, when RuboCop should be flagging these as warnings to be replaced with `not_to` instead, per https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/NotToNot. If you search in the project, you'll see these inconsistencies slipped through, e.g. [spec/config/initializers/rack_attack_spec.rb#L15](https://github.com/mastodon/mastodon/blob/main/spec/config/initializers/rack_attack_spec.rb#L15)

**Comment by nschonni** [comment]
Could be related to the version getting unpinned in https://github.com/mastodon/mastodon/pull/20574

**Comment by nschonni** [comment]
I left Superlinter for the Ruby files, since there are still a bunch of Rubocop issues, so it's easier to use it's filtering of only touched files till it's more cleaned up

**Review by Gargron — APPROVED** [review]

**Pull request merged**
