### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by ghost**
Updating some missing french translations.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by trebmuh** [comment]
There are some missing spaces before the "?".

**Comment by BoFFire** [comment]
Hum ?

**Comment by BoFFire** [comment]
Some repetition in here :
Êtes-vous sûr de vouloir de vouloir supprimer le présent statut ?
I'll correct.

**Comment by trebmuh** [comment]
As an example, it should be :
-  "confirmations.delete.message": "Are you sure you want to delete this status ?",
and not :
-  "confirmations.delete.message": "Are you sure you want to delete this status?",

**Comment by trebmuh** [comment]
As an example, it should be :
"confirmations.block.message": "Êtes-vous sûr de vouloir bloquer {name} ?",
and not :
"confirmations.block.message": "Êtes-vous sûr de vouloir bloquer {name}?",

**Comment by BoFFire** [comment]
OK @trebmuh, you're right :) I didn't want to touch that ;). Okay I'll correct it.

**Comment by trebmuh** [comment]
Awesome, thanks @BoFFire

**Pull request merged**
