### PR TITLE
Remove dependency on posix-spawn

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Made this PR a draft because I do not think there is any rush to get rid of `posix-spawn` and I have observed it brings a (marginal) performance benefit, but opening a PR nonetheless to keep track of my investigations.

`posix-spawn` seems unmaintained, and according to https://github.com/rtomayko/posix-spawn/issues/90#issuecomment-1122815520 there should be no reason to use it anymore, someone even states that it is slower than Ruby's `Process.spawn`: https://github.com/rtomayko/posix-spawn/issues/90#issuecomment-1140315750

## Benchmarks

However, my findings are different, at least in the context it is used within Mastodon, as I find `posix-spawn`'s implementation to be marginally faster.

Growing the parent's memory use before fork seem to have no bearing to those performances, which is consistent with Ruby having switched to `vfork` for `Process#spawn` since Ruby 2.2, thus addressing the main reason for `posix-spawn` to exist.

### Powerful amd64 machine

Running the following in a Rails console displays better performances using `posix-spawn` (powerful amd64 machine, Ruby 3.0.3p157):
```ruby
puts Benchmark.measure { 100000.times { line = Terrapin::CommandLine.new('/usr/bin/true'); line.run } }
```

This yields the following when using `posix-spawn` 0.3.15:
`  6.083073   6.323450  28.110833 ( 25.366304)`

And the following without:
`  8.098447   5.089173  29.062399 ( 26.534835)`

### Slower arm64 machine

On a slower arm64 machine with a different version of Ruby (3.0.4p208), the difference is similar.

With `posix-spawn` 0.3.15:
` 61.136000  34.660000  95.796000 (206.971681)`

Without `posix-spawn`:
` 82.876000  35.380000 118.260000 (229.970904)`

### CODE REVIEW

**Comment by tnm** [comment]
@ClearlyClaire If mastodon is interested in keeping posix-spawn, I can clean it up upstream and I think a couple folks might be interested in maintaining it, just lemme know!

**Comment by ClearlyClaire** [comment]
Honestly I don't know! The benefits of using `posix-spawn` are very marginal now, so I'm not sure maintaining it is worth it.

There is one thing we could benefit from if `posix-spawn` were maintained (fixing https://github.com/rtomayko/posix-spawn/issues/90) but we already have a workaround in place and everything is working well, so seems fine either way to me.

**Comment by nschonni** [comment]
Should this be dropped with Ruby 2.7?

**Comment by mjankowski** [comment]
I think this could be rebased and merged (removing gem), given negligible perf benefits in all supported rubies which are not EOL'd now.

**Review by renchap — DISMISSED** [review]

**Review by renchap — APPROVED** [review]

**Pull request merged**
