### PR TITLE
Add email validation

### LINKED ISSUE #1286: Broken email validation in instances.
A user tried to create an account with "username@domain" missing the ".tld" part and surprisingly their account was created on my instance.

They of course now cannot create a valid account as their desired handle has been taken, suggesting that the basic email validation is broken.

On that note, any guidance on helping me edit the db at backend would be a sure help.

Thanks a lot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by R0ckweb**
Fix #1286

### CODE REVIEW

**Comment by ericblade** [comment]
I can't comment on wether this is desireable or not, not knowing where this particular function is used, but the comment directly above it specifically states that that regex is not for checking that it's a valid email, only that it has an @ in it somewhere.

SO, if this change doesn't break anything, at the very minimum, it would need to have that comment altered.

**Comment by R0ckweb** [comment]
@ericblade You're absolutely right !

**Comment by expenses** [comment]
Seeing as we're validating emails anyway through confirmation, I think it's best to leave email checking to the client-side.

**Comment by R0ckweb** [comment]
I think back-end validation is always a good idea.
Let client insert wrong values in DB make me nervous ^^

But, feel free to ignore and close this PR :)

**Comment by Gargron** [comment]
Here is what an actual valid e-mail regex looks like: http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html

The sanest thing to do is check if there's a @, and send a confirmation e-mail. Sorry. Thank you for your effort on this, anyways.

**Pull request closed without merging**
