### PR TITLE
Bundler version update and misc gem version bumps

### PR DESCRIPTION
**Pull request by mjankowski**
In what is apparently a mid-March tradition - https://github.com/mastodon/mastodon/pull/24131 - this does a version bump of bundler itself (to 2.5.7) and a bunch of gems which are generally speaking:

- Just patch version bumps
- Mostly secondary or tertiary deps of other things
- Not getting renovate bumped.

I've kept things pretty well isolated to one gem per commit here, so if there's anything in this list we want to actively not update or are not sure about I can pull them out.

### CODE REVIEW

**Review by renchap — APPROVED** [review]
Looks good, but it would be great to have Renovate update those non-direct dependencies regularly. I wonder if there is a way to do it 🤔

**Comment by shleeable** [comment]
rangeStrategy update-lockfile?

**Comment by mjankowski** [comment]
> rangeStrategy update-lockfile?

I'm  not super familiar with Renovate ... would that lead to periodic PRs updating multiple deps in the gemfile (like I did manually here)? -- or to more regular one-dep-at-a-time PRs just including the indirect deps?

I think the latter would be preferrable ... I'd probably want the updater to be as aggressive as possible around what could be or should be updated (we can choose to ignore some); but as minimal/narrow/conservative as possible within each PR (ie, update as few indirect deps of whatever is the main update ... see issues recently re: i18n gem, for example, blocking unrelated updates).

**Comment by nschonni** [comment]
https://docs.renovatebot.com/configuration-options/#lockfilemaintenance seems to be the way if you want it to wipeout and recreate the lock file on some sort of schedule

**Comment by shleeable** [comment]
> https://docs.renovatebot.com/configuration-options/#lockfilemaintenance seems to be the way if you want it to wipeout and recreate the lock file on some sort of schedule

That looks perfect.

**Comment by mjankowski** [comment]
I think that's less ideal than getting a one-PR-per-dep setting, but if thats not possible its probably worth enabling this for a few weeks to see how it looks.

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me, but I'd be wary of the aws-sdk-s3 changes, those regularly have surprise breakage with any S3-compatible provider that isn't AWS.

**Review by renchap — APPROVED** [review]
Looks good, I checked `aws-sdk-s3` changelog and did not see anything possibly risky.

**Comment by renchap** [comment]
> https://docs.renovatebot.com/configuration-options/#lockfilemaintenance seems to be the way if you want it to wipeout and recreate the lock file on some sort of schedule

I think this will not work, as it will also update any direct dependency gem having a minor/major version bump where we do not specify a version constraint in the Gemfile?

**Comment by ClearlyClaire** [comment]
One of the aws-sdk-s3 changes is:
https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/CHANGELOG.md#11440-2024-03-13
> Feature - This release makes the default option for S3 on Outposts request signing to use the SigV4A algorithm when using AWS Common Runtime (CRT).

Not sure what this means exactly, but I'd keep an eye for weird S3 behavior.

**Pull request merged**
