### PR TITLE
Redesign Content Warning and filters

### LINKED ISSUE #32352: Revert: #31365
### Pitch

Revert the styling introduced by #31365. Alternatively, remove the chevron bars in the compose, timeline, and post views.

### Motivation

The content warning styling introduced in #31365 / v4.3.0 is off putting and anxiety inducing. Content warnings are used in a myriad of ways, not just as warnings but also as wrappers/email headlines/you name it. The visually blaring warning style that was added doesn’t fit these other purposes.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This removes the stripes, adjust the borders accordingly, widen the click area and slightly rework the styling and wording

## Before

image
image

## After

image
image

### CODE REVIEW

**Review by renchap — APPROVED** [review]

**Review by antimundo — APPROVED** [review]
This is great, and has been highly requested in #32352

Thanks! :))

**Comment by Izorkin** [comment]
Is it possible to make CW framing customizable in user settings?

**Comment by omentic** [comment]
Hello! Thanks for this change, it is much appreciated. My instance started running it and I have some minor feedback. The full content warning modal is rather large, two lines at the least, while content titles themselves are typically rather short. This makes for a lot of unused space. I think it would be nicer if the show/hide modal was on the same line as the title, especially since a lot of the posts on my timeline have content titles (people use it for shop talk, politics, etc).

This is what the current design looks like:


Here is a mockup of what this could like instead, with the content icon removed (for space) and the "show/hide post" dialog on the same line as the title:


If this is desired, I can open a PR. I am going to be writing the CSS for this anyway as a change to my home instance.

**Comment by antimundo** [comment]
I like your proposal @omentic and I agree that the current modal feels too large

**Comment by pwarren** [comment]
> Hello! Thanks for this change, it is much appreciated. My instance started running it and I have some minor feedback. The full content warning modal is rather large, two lines at the least, while content titles themselves are typically rather short. This makes for a lot of unused space. I think it would be nicer if the show/hide modal was on the same line as the title, especially since a lot of the posts on my timeline have content titles (people use it for shop talk, politics, etc).
 
> If this is desired, I can open a PR. I am going to be writing the CSS for this anyway as a change to my home instance.
I would at least like the custom CSS for my instance please, I've fiddled around with a flexbox on .content-warning, but can't make it look right yet (has been a decade since I did HTML/CSS)

**Pull request merged**
