### PR TITLE
✨ Add an LDAP Mail attribute config

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Add an LDAP Mail attribute config

This is just a small improvement that allows to set the LDAP mail attribute.
Also, I suggest a default search filter that allows LDAP users to login from their UID or their email address (just like internal users).

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Sorry for the delay. Please rebase.

**Comment by madmath03** [comment]
Hi @Gargron,

No problem.
This should be okay now.

**Comment by Gargron** [comment]
The changeset is now very large, I'm worried something else might get reverted by accident if I merge. Could you please do `git reset --hard HEAD~1` to remove the latest commit ("Merge branch..."), `git fetch` to make sure the info is up to date, then `git rebase origin/master`?

**Comment by madmath03** [comment]
My bad.
I did not notice that when I pushed. It should be all good now.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
