### PR TITLE
Add resend confirmation for admin

### PR DESCRIPTION
**Pull request by shuheiktgw**
Addressed this issue: https://github.com/tootsuite/mastodon/issues/7333

I added resending confirmation feature for admin user.
Thanks! 👍

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Tip: Write "fix #xxxx" anywhere in commit message or PR text to automatically close linked issue when merged

**Comment by shuheiktgw** [comment]
@Gargron Thank you! I'll do that.
BTW, I found it tiresome to add translations to all the yaml files  once I added new translatable texts to the application. Would you think it would be nice if I create some ways (probably a gem or a task ) to automatically add translations to all the other yaml files? I'm thinking I could create a gem to take diffs and adding missing translations to yaml files using Google Translation API.

**Comment by nightpool** [comment]
@shuheiktgw did you google translate the strings you put in there? that sounds bad, we generally require our translations to be done by someone who speaks the language for accuracy.

**Comment by shuheiktgw** [comment]
@nightpool Oh..., yes I used Google Translate. Should I remove the translations and wait another contributor to fix them?

**Comment by Gargron** [comment]
No, it's already done. If something is wrong with them, eventually someone will fix them.

**Pull request merged**
