### PR TITLE
Install foreman to use it on development

### PR DESCRIPTION
**Pull request by takahashim**
I'd like to execute `bundle install && bundle exec foreman` on development environment.

### CODE REVIEW

**Comment by AA4ch1** [comment]
Have you checked #2742?
I think this is duplicated with that.

**Comment by takahashim** [comment]
Thanks for your comment.
I saw #2742 and [Vagrant-guide.md]( https://github.com/tootsuite/documentation/blob/be7b16d4f8a3d2c0a6bdfd79c1d07c8b8d25bcfd/Running-Mastodon/Vagrant-guide.md). But I don't use Vagrant, and force to execute `gem install foreman` globally is not a good idea, I guess.

**Comment by AA4ch1** [comment]
Oh, I'm sorry, I jumped into the wrong conclusion.
I agree with your suggestion.

**Comment by mjankowski** [comment]
I'd prefer we not bundle things which are optional (I'm a foreman user), and let people opt in or out to whatever local dev setup makes sense.

Its fine to expect developers to understand how to install foreman or forego or the heroku cli, or to not want to use foreman/procfile at all.

**Review by mjankowski — CHANGES_REQUESTED** [review]
To clarify here - I think adding docs or something to explain how you might use (and install) foreman locally would be useful. I think adding the gem version of foreman (which is only one of several foreman tools, and which itself is only one of many ways to run the app) isn't required.

**Comment by Gargron** [comment]
The thing is - foreman is a global tool. Which is why I don't think bundling it is necessary.

**Pull request closed without merging**
