### PR TITLE
Animate avatar GIFs on-hover on public profiles

### PR DESCRIPTION
**Pull request by hyenagirl64**
Fix for issue #10388

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]
Looks fine to me, except for the fact that the full URL for avatars wasn't used. I took the liberty to edit it myself, I hope you don't mind.

Also, in the future, you can push new commits to your pull request instead of closing it and making a new one! If you're not satisfied with the history and want to clean it up, it is always possible, although a bit more involved (you may want to learn about `git rebase` and `git push --force` for this)

**Comment by hyenagirl64** [comment]
I don't mind at all.  Thank you for all the help :)

**Comment by hyenagirl64** [comment]
Are there any other steps I need to take on this for it to be merged?

**Comment by ThibG** [comment]
No, not right now at least. Someone who's authorized to merge has to review your PR, and Gargron is taking a break right now.
Thank you for your contribution!

**Pull request merged**
