### PR TITLE
Eslintrc fix

### PR DESCRIPTION
**Pull request by yookoala**
[eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y/) has just published 5.0.0 and Code Climate has upgraded to the version. In the new version, some of the plugins are renamed or re-written. Therefore eslint will produce errors in Code Climate.

This PR bumped the `eslint-plugin-jsx-a11y` version and made changes to eslintrc accordingly.

### CODE REVIEW

**Comment by yookoala** [comment]
Strange. Code Climate doesn't seem to read the `.eslintrc.json` in this repository.

**Comment by nightpool** [comment]
@yookoala no, it's telling you those errors were fixed! look at the little "fixed" tag to the right

**Comment by nightpool** [comment]
image

**Comment by yookoala** [comment]
Thanks @nightpool. That's more comforting.

**Comment by yookoala** [comment]
`role="region"` is a [WCAG recommendataion](https://www.w3.org/WAI/GL/wiki/Using_the_region_role_to_identify_a_region_of_the_page). Should be kept.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
