### PR TITLE
Bring back mascot on single column

### PR DESCRIPTION
**Pull request by tribela**
Make mascot appear again!

It moves link footer to right panel and bring back mascot on left bottom corner

image

### CODE REVIEW

**Comment by joycem137** [comment]
The mascot image isn't scaled in this version of the fix, so if you use a different size mascot than default, it'll appear at its native resolution and be huge or tiny.

**Comment by Kjwon15** [comment]
oh. I'll find way to fix that

**Comment by joycem137** [comment]
This will still break some mascots that are tall, since you're not constraining on the height.  Also, make sure to try really tall compose boxes to see how they interact with it.

Here's what I'm seeing on my dev instance with your PR:

**Comment by Kjwon15** [comment]
@joycem137 Since it's floating from main UI, It's not possible to resize like advanced UI without js support.
What do you think about changing z-index to hide behind compose box?

**Comment by Kjwon15** [comment]
I tried to use flex and `position: relative` to slide left, chrome doesn't support 'flex-basis: content` and `overflow-y: hidden` is malfunctioning..

**Pull request closed without merging**
