### PR TITLE
Nicer sparkline scaling for comparing hashtags

### PR DESCRIPTION
**Pull request by naught101**
This will plot empty hashtags as a line at the bottom of the graph, instead of in the middle.

It will also scale small hashtags, so that e.g. something with 1 tag will only use ~10% of the available graph height, where something with 10 tags will use ~50% of the height, and something with 100 tags will use ~90% of the height, etc.

I haven't had time to set up a dev environment, so this is untested, but I'm 99% sure it should work as advertised, following the [react-sparkline docs](https://www.npmjs.com/package/react-sparklines).

### CODE REVIEW

**Comment by Gargron** [comment]
I would like some screenshots to confirm that it looks good and looks better than before.

**Comment by naught101** [comment]
Fair enough, I will try to get a dev server set up. Any tips on creating sufficient content to get some data to show would be useful.

**Comment by naught101** [comment]
@Gargron it does work as I hoped. I don't know how to generate lots of old tag data, but here are some examples - there are 19 toots with `#hashtag`, 4 with `#hashtagMedium`, and one with `#hashtagSmall` 

image

**Comment by naught101** [comment]
With this, a 20 tag peak uses 2/3 of the available height.

I think that this is a good scaling for hashtag searches, where most hashtags only have a couple of hits. Perhaps not so good for the popular hashtags feed though, where most of the hashtags have hundreds of hits, and so the scaling will always be nearly 100%. It still gives you a bit of difference though, and the relative change is still there, so I think this is still a good change as-is.

Potentially you could figure out a way to store the maximum hash tag hits among all displayed, and do something like add 10% to the max, so if you had one 1000 hit tag, that would be at about 90%, and a 100 hit tag in the same feed would show 50%, and a 10 hit tag would show ~9%. But maybe not worth it.

**Comment by mjankowski** [comment]
Closing from lack of activity/rebase ... and because this area has changed slightly and I'm not sure still relevant.

If you want to nudge forward, can you rebase the PR, upload some before/after images of changes (with present-day UI)?

**Pull request closed without merging**
