### PR TITLE
Add bot icon to bot avatars and migrate to newer version of Font Awesome

### PR DESCRIPTION
**Pull request by MaciekBaron**
This is a prerequisite for implementing #8347.

This change updated the repo used to https://www.npmjs.com/package/@fortawesome/fontawesome-free which is more up to date.

### CODE REVIEW

**Comment by MaciekBaron** [comment]
I've tested it and all the icons look exactly the same, but I'm happy to wait after 2.5.0. I will add my bot icon work to this PR though so it's not in limbo.

**Comment by Gargron** [comment]
@MaciekBaron I'm ready for this

**Comment by MaciekBaron** [comment]
Great, I'll resolve all conflicts and issues later today

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Well, turns out I don't really like how it looks, so what do we do?

image

**Comment by MaciekBaron** [comment]
I've based this on the design from #8347, we can tweak it.

**Pull request merged**
