### PR TITLE
A few updates to the Spanish translation and some typos fixing

### PR DESCRIPTION
**Pull request by thermosflasche**

### CODE REVIEW

**Comment by ykzts** [comment]
I resolve conflicts.

**Comment by ykzts** [comment]
cc @007lva @carlosjs23 @kant @victorhck

**Comment by carlosjs23** [comment]
lgtm

**Comment by Gargron** [comment]
The build is failing and I don't understand why 🤔

**Comment by bruwalfas** [comment]
I guess it's something with @ykzts 's commit. Mine only translated the locales

**Comment by ykzts** [comment]
@bruwalfas 

> I guess it's something with @ykzts 's commit. Mine only translated the locales

No, you seem to be doing unnecessary translations.

**Comment by ykzts** [comment]
All green :smile:

**Review by ykzts — APPROVED** [review]

**Comment by bruwalfas** [comment]
My bad! 😖 I'll debug it with i18n-tasks next time 😅

**Pull request merged**
