### PR TITLE
Fix account search showing results from domains hidden by user

### LINKED ISSUE #8586: Hiding a domain should remove its users from the search results
When I enter a search, I shouldn't see users from domains I have hidden: 
a mastodon search, which shows results from Switter even though i have the instance blocked
(To clarify, switter.at *is* a hidden domain, not shown in this screenshot)

While this is a trivial example, I've come across instances that exist purely to impersonate users, and because there's no way to hide the instances from the search results, they will block out the search results I actually want to find.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #8586

### CODE REVIEW

**Review by ClearlyClaire — COMMENTED** [review]
It's ok, but shouldn't we make the filtering directly in the ES/SQL query?

**Comment by Gargron** [comment]
Since I combined username + domain into `acct` in the accounts index it's a little more difficult to filter out by domain, not to mention the SQL fallback queries are very clunky to work with. This is not a proper solution but it does fix the bug.

**Comment by ThibG** [comment]
The SQL fallback to change is `Account#advanced_search_for`. I guess it's ok like that, but my worry is that all relevant accounts get filtered out a posteriori, leaving 0 results.

**Comment by ThibG** [comment]
Hmmm also being able to search for someone on a domain that you have personally blocked might be useful. In part to be able to unblock that domain. And we don't remove individually blocked users from the search results either.

**Comment by ThibG** [comment]
Forget about the “in part to be able to unblock that domain”, as we do have some UI listing blocked domains and allowing to unblock them.

Exact match and URL search isn't affected by this change, which sounds good to me.

So after checking this PR again, my only reservation is that we probably should do the domain filtering earlier, in the Postgres/ElasticSearch query if possible.

**Pull request closed without merging**
