### PR TITLE
Remove preference to aggregate reblogs in home/list feeds

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by trwnh** [comment]
Please consider reverting this. The default is already to aggregate reblogs, so this change only hurts power users who would rather see all times a post is boosted.

**Comment by Gargron** [comment]
There was a performance cost to the check and it’s in a hot path. I think the default is adequate.

**Comment by noellabo** [comment]
Out of about 4000 users on fedibird.com, 200 users have explicitly set the setting to off. This is not a small number.

I think this is mainly because there is a use case called "boost reference" which is commented after boost.
This means that if you don't show all boosts, it's hard to trace the context, so it's an essential feature for those who have it set to off.

Alternatively, you can employ the quote feature :-)

**Comment by ClearlyClaire** [comment]
> There was a performance cost to the check and it’s in a hot path. I think the default is adequate.

Is the performance impact noticeable? iirc you wrote this when we were investigating deadlocks when m.s was under huge loads, as some of the locks occurred in this check, but it turned out to be a broader issue with `redis` that got solved by moving to a connection pool

**Pull request merged**
