### PR TITLE
Guard against nil URLs in Request class

### LINKED ISSUE #7265: ActivityPub::SynchronizeFeaturedCollectionWorker exception: NoMethodError: undefined method `normalize' for nil:NilClass
Observed after switching to v2.3.3, but I wasn't observing logs prior to that so it's possible it's present in older versions too.

Let me know if you need any more information. 

```
2018-04-25T22:39:43.513Z 7 TID-gnfiljq0c WARN: {"context":"Job raised exception","job":{"class":"ActivityPub::SynchronizeFeaturedCollectionWorker","args":[13934],"retry":true,"queue":"pull","jid":"259a3852f3872a6e2251e470","created_at":1524693097.9847162,"enqueued_at":1524695983.4240708,"error_message":"undefined method `normalize' for nil:NilClass","error_class":"NoMethodError","failed_at":1524693098.0427012,"retry_count":6,"retried_at":1524694479.1596196},"jobstr":"{\"class\":\"ActivityPub::SynchronizeFeaturedCollectionWorker\",\"args\":[13934],\"retry\":true,\"queue\":\"pull\",\"jid\":\"259a3852f3872a6e2251e470\",\"created_at\":1524693097.9847162,\"enqueued_at\":1524695983.4240708,\"error_message\":\"undefined method `normalize' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1524693098.0427012,\"retry_count\":6,\"retried_at\":1524694479.1596196}"}
2018-04-25T22:39:43.514Z 7 TID-gnfiljq0c WARN: NoMethodError: undefined method `normalize' for nil:NilClass
2018-04-25T22:39:43.515Z 7 TID-gnfiljq0c WARN: /mastodon/app/lib/request.rb:13:in `initialize'
/mastodon/app/helpers/jsonld_helper.rb:85:in `new'
/mastodon/app/helpers/jsonld_helper.rb:85:in `build_request'
/mastodon/app/helpers/jsonld_helper.rb:63:in `fetch_resource_without_id_validation'
/mastodon/app/helpers/jsonld_helper.rb:58:in `fetch_resource'
/mastodon/app/services/activitypub/fetch_featured_collection_service.rb:8:in `call'
/mastodon/app/workers/activitypub/synchronize_featured_collection_worker.rb:9:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:188:in `execute_job'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:169:in `block in process'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:97:in `local'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:42:in `block in call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:41:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:204:in `stats'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/job_logger.rb:7:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:72:in `global'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:129:in `block in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:44:in `with_context'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:128:in `dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:168:in `process'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:85:in `process_one'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:73:in `run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:16:in `watchdog'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).v2.3.3

### PR DESCRIPTION
**Pull request by Gargron**
Dunno why but :man_shrugging: 

Fix #7265

### CODE REVIEW

**Comment by nightpool** [comment]
Is silently passing on nil URLs the correct behavior here? Shouldn't we just fix the synchronize featured collection worker?

**Comment by Gargron** [comment]
@nightpool That worker isn't even queued unless featured_collection_url is present. The actual service itself does not guard against that case, but it would still take some weird circumstances for that to be the problem. :thinking:

**Comment by renatolond** [comment]
Is it the whole url that's nil? I had that trouble but ended up never finishing the patch in masto.donte and the issues I was seeing were urls without the scheme (links like `//www.test.com` for matching schemes)

**Comment by mal0ki** [comment]
We need these questions cleared up before I want to allow this to be merged.

**Comment by Gargron** [comment]
I have done what @nightpool suggested. As for @renatolond, you may have dealt with a different issue but the issue linked from OP is clearly a nil error that only occurs if nil is passed into parse.

**Review by nightpool — APPROVED** [review]

**Comment by ProgVal** [comment]
I have a lot of tracebacks like this (`WARN: NoMethodError: undefined method `featured_collection_url' for nil:NilClass`) on my instance about this user: https://mastodon.rocks/@UBports

Maybe that can help you debug?

**Comment by ProgVal** [comment]
nvm, that was not the same issue

**Pull request merged**
