### PR TITLE
Allow creation of backdated statuses via API

### PR DESCRIPTION
**Pull request by lucahammer**
This was requested by #10639 and would allow third party tools to offer CSV imports as discussed in #981. Could be an alternative to fully supported content migration within the Fediverse as well #12423 .

# Why?
Many people want to take their content from other platforms with them for different reasons. Sometimes because the platforms shut down (eg. Google+, Vine, certain fediverse instances), sometimes because they want to delete their account on the other platform (eg. Twitter). 

There are already tools that create the content from archives as new posts (eg. https://github.com/FGRibreau/import-tweets-to-mastodon), but those come with two major issues: 
- They spam followers, local and federated instances
- Statuses have incorrect dates

I wanted an option to import content without these issues.

# How does it work?
This PR adds an optional "created_at" parameter to the [v1/statuses](https://docs.joinmastodon.org/methods/statuses/#create) endpoint. If that parameter is set, the status isn't distributed (neither on the same instance nor to others).

This allows developers to create tools for data exports from any other platform to be imported to an Mastodon instance.

# Possible problems and mitigations
## Server load
Importing thousands of posts could add serious load to servers. Because it is done through the API, the rate limits prevent users from importing everything at once and instead spread out the import over a longer time frame.

## Posts in the future
The current PR dates posts with a created_at in the future to the current time. Another option would be to convert them to scheduled ones or reject them completely. 

## Abuse/Forgery
Admins always are able to manipulate posts and timestamps in the database. No code will prevent that. But this allows users to create statuses with any date they want. Needing an app for that makes it slightly easier for admins to identify abuse of the feature and and remove statuses that was created through that app, but that only helps after it happened and probably the account would get banned anyways.

### CODE REVIEW

**Comment by rbairwell** [comment]
Personally, I'd prefer this is be behind an admin flag/setting as some admins might not want to offer it for a variety of reasons (such as trust)

**Comment by ClearlyClaire** [comment]
One worry I have about such things is how much easier it would make someone posting awful stuff to discredit their moderator's work. e.g. a bad actor posts questionable “takes” that are sure to bring scrutiny from local and remote moderators alike, but not bad enough that the local moderators would ban them… and a few days later they post something truly awful, but backdated, so that it would appear to people that the local moderators could not possibly have missed it when the account was first reported.

**Comment by tobyink** [comment]
> a bad actor posts questionable “takes” that are sure to bring scrutiny from local and remote moderators alike, but not bad enough that the local moderators would ban them… and a few days later they post something truly awful, but backdated, so that it would appear to people that the local moderators could not possibly have missed it when the account was first reported.

That could be fixed by including an "imported on" datetime in small text at the bottom of backdated posts showing the date it was really imported.

**Comment by leo60228** [comment]
For reference, Tumblr allows arbitrarily backdating posts and this functionality isn't really known for abuse. That doesn't have the concerns with regard to moderation, though.

**Comment by moritzdietz** [comment]
FWIW: Matrix is also building out something similar to what is being asked here: [MSC2716: Incrementally importing history into existing rooms](https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/msc2716/proposals/2716-batch-send-historical-messages.md)
That's how they pulled off importing all of Gitter.im into Matrix.

I would like to think that users would appreciate it if there was a way to import history of their previous posts from other websites - whatever this may be. It could be a Twitter, Instagram, Tumblr archive or whatever. With the goal in mind that their   content does not get lost when the platform goes down.
If there is a proper API and spec around doing that, there could be a market for tools that handle importing those and other export formats.

**Comment by mjankowski** [comment]
Closing due to lack of activity, merge conflicts, and lack of consensus on how to handle this idea (re: ability to fake data) ... however!, there's definitely a use case here for some variation of this.

If you want to push forward, can you rebase this, reopen, add some spec coverage for the basic import case, and add some commentary around the various concerns?

**Pull request closed without merging**
