### PR TITLE
Update model annotations to use BIGINT for IDs

### PR DESCRIPTION
**Pull request by danhunsaker**
All the migrations have been updated to use BIGINTs for ID fields in the DB, but ActiveRecord needs to be told to treat those values as BIGINT as well. This PR does that.

### CODE REVIEW

**Comment by danhunsaker** [comment]
Just a quick bump to get some feedback, at least.

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Unfortunately, since this is auto-generated, this will all get overwritten the next time we run db:migrate

**Comment by danhunsaker** [comment]
That shouldn't be an issue, since the autogenerated annotations should then correctly be `bigint` instead of `integer`?

**Comment by Gargron** [comment]
@danhunsaker Well, for whatever reason, the annotate gem picks them up as integer and not bigint. Otherwise this PR wouldn't have had anything to correct either.

**Comment by danhunsaker** [comment]
I was a little confused about why the annotations hadn't been updated already in that case.

So we're looking at a bug in the annotations gem, then?

**Comment by ykzts** [comment]
It is fixed by https://github.com/ctran/annotate_models/pull/515 . But it has not been released yet.

**Pull request merged**
