### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by rkarabut**
Translated the newly-added and changed strings. Also added the email templates (for confirmation, password change and password reset).

### CODE REVIEW

**Comment by rkarabut** [comment]
What's with all these new Travis errors?..
  
```
NoMethodError:
       undefined method `deep_symbolize_keys' for "Òc":String
```

**Comment by yookoala** [comment]
@rkarabut Suggest to do reset hard on origin master before your next work. Simpler history to follow:

```
git fetch origin master
git reset --hard origin/master
git push -f
```

**Comment by rkarabut** [comment]
@yookoala Thanks for the suggestion, I'm a bit of a noob when it comes to git. Should also probably make a separate branch for this :)

**Comment by yookoala** [comment]
@rkarabut It took me long enough to have a sense with git. Some [nice article](https://www.atlassian.com/git/tutorials/comparing-workflows) can help :-)

**Pull request closed without merging**
