### PR TITLE
Exit 1 after an error in `tootctl media remove-orphans`

### LINKED ISSUE #20417: `tootctl media remove-orphans` crashes with exit code 0
### Steps to reproduce the problem

1. Make `tootctl media remove-orphans` crash for any reason while it's running

### Expected behaviour

`tootctl media remove-orphans` should return a non-zero exit code

### Actual behaviour

`tootctl media remove-orphans` returns a non-zero exit code

### Detailed description

These are the last lines:

```
Error fetching list of files: end of file reached
Progress: |
If you want to continue from this point, add --start-after=accounts/avatars/000/117/935/original/635b01d14c52b041.png to your command
```

Because it returns a non-zero exit code, `tootctl media remove-orphans` has been failing for years on my machine, and I was not notified by my monitoring, causing about 0.5TB of orphans to accumulate.

### Specifications

Mastodon 3.5.3
Ruby 2.7.4p191

### PR DESCRIPTION
**Pull request by erbridge**
Fixes #20417

### CODE REVIEW

**Review by Gargron — COMMENTED** [review]
It is not obvious to me that the exit code should be affected by 1 out of x items failing. What is the use case here? I don't think this command should be part of any pipes, in fact, it is a very niche troubleshooting command that should usually not be needed.

**Comment by erbridge** [comment]
I do think any error in the process is an error in the execution of the programme, and therefore should have an error exit code. But I'm fine to remove that for now given it's probably an "acceptable" error for many use cases.

**Comment by progval** [comment]
> What is the use case here?

See #20417:

> Because it returns a non-zero exit code, `tootctl media remove-orphans` has been failing for years on my machine, and I was not notified by my monitoring, causing about 0.5TB of orphans to accumulate.

**Review by mjankowski — COMMENTED** [review]
The pulling out of private methods for each case is a good change in my opinion, but makes the diff about what's actually changing hard to look at on it's own.

I think that the narrow case of "S3 is misconfigured and actually can't work" should definitely exit with non-zero code here. Not sure about the subtleties of SOME (but not all) records having issues in the loop.

Could you rebase this, and either a) first do a refactoring-only PR that separates out the methods here, or b) change this to just add some up-front error checking for the S3 config, but not (yet) do anything with the looping/counting error status?

**Comment by mjankowski** [comment]
Closing from lack of activity/rebase -- if you feel strongly this should change, see my comment from Dec '23 and nudge forward along those lines.

**Pull request closed without merging**
