### PR TITLE
Fix “slow mode” issues

### PR DESCRIPTION
**Pull request by ClearlyClaire**
- Do not scroll weirdly when clicking the “load pending items” button
- Treat pending items as unread items

### CODE REVIEW

**Comment by ThibG** [comment]
The “X new items” click was interfering with the mouse movement scroll prevention behavior, which resulted in very weird scroll behavior. I fixed that.
By doing so, I decided to *not* scroll to top, which I guess is debatable.

**Comment by Gargron** [comment]
Is the mouse movement thing still necessary if scrolling down will add new stuff to pending items instead of pushing the feed down?

**Comment by ThibG** [comment]
yes, if you're still on top

**Review by Gargron — APPROVED** [review]

**Comment by ThibG** [comment]
Pushed another commit preventing a scroll discrepancy I hadn't seen: when scrolled down and the “x new items” button appears, it pushed everything down and that wasn't corrected

**Pull request merged**
