### PR TITLE
Drawer tab according to column

### PR DESCRIPTION
**Pull request by ykzts**
Add a link to the notifications to the drawer when there is no notification in columns.

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
I like it!

**Comment by Gargron** [comment]
I think it would be a bit inconsistent if the public/local icons are always on but only notifications is conditional.

**Comment by ykzts** [comment]
@Gargron Certainly. I changed it.

### add all colums



### remove all columns

**Comment by beatrix-bitrot** [comment]
the home column can also be un-pinned. will it show there if it is?

**Comment by ykzts** [comment]
@beatrix-bitrot I add :house:

**Review by Gargron — APPROVED** [review]

**Comment by beatrix-bitrot** [comment]
thanks @ykzts !!

**Pull request merged**
