### PR TITLE
Add ID3v{1,2} and Vorbis metadata to boop

### PR DESCRIPTION
**Pull request by hannahwhy**
Inspired by https://awoo.space/@noiob/98889877558300456.

ogginfo results on `boop.ogg` after this PR:

```
$ ogginfo boop.ogg 
Processing file "boop.ogg"...

New logical stream (#1, serial: d23ff368): type vorbis
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Lavf57.72.100
Channels: 1
Rate: 44100

Nominal bitrate: 80.000000 kb/s
Upper bitrate not set
Lower bitrate not set
User comments section follows...
        ENCODER=Lavc57.92.100 libvorbis
        TITLE=boop
        ARTIST=jk@mastodon.social
        DATE=2017
Vorbis stream 1:
        Total data length: 1812 bytes
        Playback length: 0m:00.235s
        Average bitrate: 61.658333 kb/s
Logical stream 1 ended
```

id3v2 -l results on `boop.mp3`:

```
$ id3v2 -l boop.mp3 
id3v1 tag info for boop.mp3:
Title  : boop                            Artist: jk@mastodon.social            
Album  :                                 Year: 2017, Genre: Unknown (255)
Comment:                                 Track: 0
id3v2 tag info for boop.mp3:
TSSE (Software/Hardware and settings used for encoding): 
TLEN (Length): 450
APIC (Attached picture): ()[, 0]: image/png, 8714 bytes
TIT2 (Title/songname/content description): boop
TPE1 (Lead performer(s)/Soloist(s)): jk@mastodon.social
TYER (Year): 2017
```

Size difference with `master`:

- boop.mp3: 12070 -> 12280 bytes (+210 bytes)
- boop.ogg: 5164 -> 5220 bytes (+56 bytes)

Embedded cover art (only in the MP3, I couldn't find a way to embed it as Vorbis metadata without unacceptably huge filesize increases):

media2

### CODE REVIEW

**Comment by noiob** [comment]
Thank you.

**Comment by noiob** [comment]
Thank you.

**Comment by yiskah** [comment]
I heard in the thread you were trying to make a rotatey gif the album art and I would caution against that. If there's album art it should be static

**Comment by yipdw** [comment]
It is static; throwing in the entire animation would have added something like a megabyte to the filesize.

**Comment by yipdw** [comment]
There may exist a licensing issue with the cover art: it's a derivative work of @jk@mastodon.social's avatar, and for this to go through it would have to be covered under AGPLv3 (or appropriate notations need to be made in the Mastodon license data, etc.)  Probably should ask @jk@mastodon.social about this.

**Review by nolanlawson — APPROVED** [review]

**Comment by yipdw** [comment]
@jk@mastodon.social approved the derivative work:

- https://mastodon.social/@jk/98890577339113049
- https://web.archive.org/save/https://mastodon.social/@jk/98890577339113049

I have also updated the comment field in the ID3 and Vorbis metadata as per his request.  New metadata:

```
$ id3v2 -l boop.mp3 
id3v1 tag info for boop.mp3:
Title  : boop                            Artist: jk@mastodon.social            
Album  :                                 Year: 2017, Genre: Unknown (255)
Comment: josefkenny.com                  Track: 0
id3v2 tag info for boop.mp3:
TSSE (Software/Hardware and settings used for encoding): 
TLEN (Length): 450
APIC (Attached picture): ()[, 0]: image/png, 8714 bytes
TIT2 (Title/songname/content description): boop
TPE1 (Lead performer(s)/Soloist(s)): jk@mastodon.social
COMM (Comments): ()[eng]: josefkenny.com
TYER (Year): 2017
$ ogginfo boop.ogg 
Processing file "boop.ogg"...

New logical stream (#1, serial: d23ff368): type vorbis
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Lavf57.72.100
Channels: 1
Rate: 44100

Nominal bitrate: 80.000000 kb/s
Upper bitrate not set
Lower bitrate not set
User comments section follows...
        ENCODER=Lavc57.92.100 libvorbis
        TITLE=boop
        ARTIST=jk@mastodon.social
        DATE=2017
        COMMENT=josefkenny.com
Vorbis stream 1:
        Total data length: 1812 bytes
        Playback length: 0m:00.235s
        Average bitrate: 61.658333 kb/s
Logical stream 1 ended
```

**Pull request merged**
