### PR TITLE
Add server-side waveform generation for audio attachments

### PR DESCRIPTION
**Pull request by Gargron**
System requirement:

```
sudo add-apt-repository ppa:chris-needham/ppa
sudo apt-get update
sudo apt-get install audiowaveform
```

### CODE REVIEW

**Comment by mstdn** [comment]
Nice

**Review by ykzts — APPROVED** [review]

**Comment by shleeable** [comment]
Please throw `audiowaveform` into the Dockerfile. Around line 100.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Dockerfile and doc updates are missing

**Comment by ThibG** [comment]
I'm uncomfortable with adding yet another system dependency (especially something not widely packaged) for such a minor feature. For the time being, I'd prefer if it were an optional dependency (also, the front-end should check the presence of peaks either way, since it may be used with older toots)

**Comment by Gargron** [comment]
I would hold off on merging this because I might possibly change how audio attachments are rendered in the UI and this might mean that server-generated waveforms would no longer be required.

**Comment by Gargron** [comment]
No longer needed thanks to the audio player change

**Pull request closed without merging**
