### PR TITLE
Add API to get multiple accounts and statuses

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Add an API to get accounts and statuses by ID.

Documentation PR: https://github.com/mastodon/documentation/pull/1433

Rebase and update #24199 by @noellabo

```
GET /api/v1/accounts?ids[]=1&ids[]=2
GET /api/v1/statuses?ids[]=1&ids[]=2
```

- The `ids` parameter can request up to DEFAULT_ACCOUNTS_LIMIT (=40) for accounts and DEFAULT_STATUSES_LIMIT (=20) for statuses, and a 422 Mastodon::ValidationError will occur if exceeded.

I have multiple needs.

- We want to update the accounts and statuses we hold to the latest information, including additional information (favorites, boosts, edit history, etc.)
- To save resources, if we only keep the ID and purge other payloads, we want to retrieve it again when needed
- We want to get only what we need from an API response that only returns an ID

___

Fixes MAS-52

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
@Gargron returned a hash indexed by `id` but honestly I am not sure this is worth it. Afaik we have never done it in the API so far, and it makes the code significantly more awkward.

**Comment by ClearlyClaire** [comment]
I reverted to not index by id, as it makes the code more awkward and is inconsistent with every other API endpoint for little benefit.

**Comment by renchap** [comment]
This will need a corresponding documentation update

**Review by renchap — APPROVED** [review]
Looks good to me, but I would like to have a +1 from @Gargron as well

**Comment by shleeable** [comment]
Can this get tagged as milestone 4.3?

**Review by Gargron — APPROVED** [review]

**Pull request merged**
