### PR TITLE
[A11y] Icon Button update

### PR DESCRIPTION
**Pull request by xirclebox**
# Purpose
While `tabindex="0"` is used to add an element to the accessible tabbing order, buttons receive focus natively. Therefore the `tabindex` attribute is not necessary. If a button is to be removed from the tabbing order, it should be disabled instead.

### CODE REVIEW

**Comment by Gargron** [comment]
Have you checked if the prop `tabIndex` on the `IconButton` component is never used for anything but `0`?

**Comment by xirclebox** [comment]
> Have you checked if the prop `tabIndex` on the `IconButton` component is never used for anything but `0`?

Hey @Gargron ... I looked around but didn't see anything. I saw a bunch of `div`s used as buttons that have a However, if you know of a spot, let me know and I'll update it there as well.

**Comment by ClearlyClaire** [comment]
Going through the code, I've found one use of `IconButton` with non-0 `tabIndex`. This occurs in `app/javascript/mastodon/features/ui/components/actions_modal.js`, which if I remember correctly, is used in place of dropdown menus on mobile.

This was added as part of #4408 in order to make that modal more accessible, as the button is in a larger link that represents the same item.

I don't know why it's a button in the first place, though. It seems to me it should simply be a presentational icon as the container itself is a link/button.

**Comment by xirclebox** [comment]
> 

I agree. It looks as if this was just a shortcut to get the icon graphic to render instead of just using the graphic alone. I'll look at updating this as well.

**Comment by xirclebox** [comment]
hey @ClearlyClaire ... do you know where in the UI the `actions_modal` is? I'm looking for it because I want to do a visual test but I can't find it.

**Comment by ClearlyClaire** [comment]
> hey @ClearlyClaire ... do you know where in the UI the `actions_modal` is? I'm looking for it because I want to do a visual test but I can't find it.

It's used on mobile in place of most dropdown menus

**Comment by mjankowski** [comment]
Closing due to no activity in ~1 year and merge conflicts -- if this is still relevant, can you fix the lint errors, rebase, and comment/reopen?

**Pull request closed without merging**
