### PR TITLE
Change media upload limits and remove client-side resizing

### PR DESCRIPTION
**Pull request by Gargron**
For media attachments, the limits become:

- Images:
  - Upload size: 10 MB to 16 MB
  - Target dimensions: Full HD to 4K
  - Processing limit: 4K to 8K
- Videos:
  - Upload size: 40 MB to 99 MB
  - FPS limit: 60 FPS to 120 FPS
  - Processing limit: Full HD to 4K

For link preview cards, the limits become:

- Upload size: 1 MB to 2 MB

Client-side resizing is removed to avoid low-quality output. The max. RAM usage of ImageMagick becomes 847 MB.

___

Fixes MAS-47

### CODE REVIEW

**Comment by renchap** [comment]
If this goes through, you can also remove the `resize_image.js` files and the `exif-js` JS dependency.

**Review by ykzts — APPROVED** [review]

**Comment by tabletcorry** [comment]
Can the media resizing process forks be niced to keep them from swamping the system as heavily?

Larger media sounds great, but I already see occasional media cause massive CPU spikes on my personal instance. Communicating the low priority of conversion to the cpu scheduler would help a lot.

**Comment by ClearlyClaire** [comment]
> If this goes through, you can also remove the `resize_image.js` files and the `exif-js` JS dependency.

True, although we could use `exif-js` to provide alt-text-from-image-metadata functionality (could also be done server-side I guess but it makes more sense to me as a client-side feature)

**Comment by shleeable** [comment]
Storage is cheap, so I'm fine with the increased image/movie size, but Client-side resizing is a stretch.

I'd rather you set a standard and transcode on the iOS app for example to a known universal standard... My CPUs are going to cry... but making 8 accounts and uploading a large 4K video will most than likely result in a DOS.

**Comment by anampses** [comment]
This is a welcome change for art instances such as mine. However, I noticed that this upcoming change increased the max video resolution to 4K, but image resolution is increasing to only 2K for some reason. Is there a reason for this? Why would video media get to have more pixels when previously both video and images had the same FHD limit image format?

Ideally the image size should be bumped up to at least 4K, just like video. Having more pixels is important for artists since it is more common for images to be entirely graphical (eg illustrations, comics) than it is with videos which is usually captured. 

Also, since there is no more client-side resizing, a higher pixel limit will keep the server's CPU/RAM usage down since the server won't have to do resizing of images as often.

**Comment by ClearlyClaire** [comment]
Bumping the image pixel count limit is very RAM-costly due to the tools we use. Until we ditch ImageMagick, I don't think it's wise to increase the allowed input image pixel count at all. #23322 touches on this and actually allows larger output images than the current PR (that means a potential storage cost increase, but not a RAM or CPU one unlike the current PR)

**Comment by rrgeorge** [comment]
I think that the max size should only be 100MB, as that’s the upload limit on some CDNs.

**Comment by Gargron** [comment]
Changed video size limit to 99 MB, target dimensions for images to 4K (same as videos).

The changed image matrix limit means the max. ImageMagick memory usage will be about 847 MB.

**Review by WhiskeyOmega — CHANGES_REQUESTED** [review]
Can I suggest we include slightly higher vertical resolution to include DSLR images Aspect Ratios

app/models/concerns/attachmentable.rb
MAX_MATRIX_LIMIT = 33_177_600 # 7680x4913px or approx. 847MB in RAM

app/models/media_attachment.rb
    original: {
      pixels: 9_434_880, # 3840x2457px
      file_geometry_parser: FastGeometryParser,
    }.freeze,

**Comment by floogulinc** [comment]
Any idea when we'll see this in a stable release?

**Comment by madrobby** [comment]
For whom it may concern, the standard size for many phone and DSLR photos is currently moving to (and often already is) 48MP (roughly 8,500 by 5,650 pixels, this is slightly more than 8K UHD).

It's likely fine to stay at the ~4K target as most phones convert 48MP to 12MP internally anyway, but it's definitely coming somewhere down the line.

**Comment by rrgeorge** [comment]
> Does anyone know if the audio upload limit has been increased too? Doesn't seem to be mentioned anywhere...?

It appears that audio uses the same size limit as video (https://github.com/mastodon/mastodon/blob/27e84c069112a3d2abfad947642457cc997a261a/app/models/media_attachment.rb#L233), so it's now 99mb.

**Pull request merged**
