### PR TITLE
Localize locale names (with twitter-cldr)

### PR DESCRIPTION
**Pull request by c960657**
Locale names currently only exist in English and the locale language itself.

With this PR, locale names are stored in regular i18n yml files and handled like any other string.

For locales supported by CLDR, the files have been prepopulated with all languages included in CLDR for the locale in question. When new supported locales are added, run `rake repo:languages` to update all `language.*.yml` files with new locale based on CLDR (where applicable).

Of the ~198~ 95 locales supported by Mastodon (`I18n.available_locales`), the [twitter-cldr](https://github.com/twitter/twitter-cldr-rb) gem used in this PR gem supports ~68~ [56](https://github.com/twitter/twitter-cldr-rb/blob/master/resources/supported_locales.yml). For most of these, CLDR has translations for all locales in SUPPORTED_LOCALES except these: `bh` (Bihari), `cnr` (Montenegrin), `kmr` (Kurmanji (Kurdish)), `ldn` (Láadan), `tai` (Tai), `tok` (Toki Pona), `zba` (Balaibalan).

With locale names available in the chosen UI language, I think it is more appropriate for `/settings/preferences/other` to show these rather than the native names. I wonder if we should follow this logic and flip the native vs. localized string in the language dropdown in the compose form, so the localized name is written in black and the native name in light grey?

I changed the native name for some locales in `LanguagesHelper` to reflect the name in CLDR. This includes some changes to lowercase (language names written in uppercase in e.g. English but not in e.g. Spanish) and remove “language” suffix (e.g. from _“беларуская мова”_ to _“беларуская”_ – the suffix _“мова”_ means language – as also suggested [here](https://crowdin.com/project/mastodon/discussions/285))“.

### CODE REVIEW

**Comment by Gargron** [comment]
It may not be wise to add new dependencies that are maintained by Twitter. Twemoji recently lost all staff.

**Comment by c960657** [comment]
> It may not be wise to add new dependencies that are maintained by Twitter.

I agree that it seems likely that Twitter will stop maintaining this gem. However, it is very popular (9,9 million downloads according to [RubyGems](https://rubygems.org/gems/twitter_cldr)) and open source (Apache License 2.0), so it will probably be forked by somebody else. The actual translations are maintained by Unicode, not Twitter, and the gem has tooling for importing updates from CLDR.

I looked for other CLDR libraries, and the only one I found which is still maintained was [ruby-cldr](https://rubygems.org/gems/ruby-cldr). This library only handles converting from CLDR XML files to YAML files, so support for e.g. [inheritance from parent locales](https://unicode.org/reports/tr35/#Locale_Inheritance) ourselves would have to be implemented in Mastodon (or contributed to that library). This is definitely feasible, and I would be happy to look into that, if you prefer that approach. But for now I think **twitter_cldr** is a good choice.

(btw, I am a big fan of CLDR. I have contributed to [Punic](https://punic.github.io/), a PHP CLDR library, and added localised [timezones](https://github.com/matomo-org/matomo/pull/12901) and [currencies](https://github.com/matomo-org/matomo/pull/13068) to Matomo based on Punic)

**Comment by c960657** [comment]
I have created PR #24245 which implements the same but with the [ruby-cldr](https://github.com/ruby-i18n/ruby-cldr) gem. I realised that this gem does already support parent locale inheritance (contrary to what I wrote in my previous comment).

While working on this I created a [bug report for twitter-cldr](https://github.com/twitter/twitter-cldr-rb/issues/263) and a [PR for ruby-cldr](https://github.com/ruby-i18n/ruby-cldr/pull/234), and both were handled within a few days.

I think twitter-cldr is more mature, but ruby-cldr gets the job done. But an important point is that ruby-cldr supports all locales in CLDR, while twitter-cldr only supports [a subset](https://github.com/twitter/twitter-cldr-rb/blob/master/resources/supported_locales.yml). For that reason I think ruby-cldr is the better choice for this task.

**Comment by gunchleoc** [comment]
Since there's no telling where Twitter will jump next with Musk at the help, the ruby-cldr option is probably more sustainable in the long run?

**Comment by ThisIsMissEm** [comment]
> For that reason I think ruby-cldr is the better choice for this task.

Should this PR be closed then in favour of #24245 ?

**Comment by c960657** [comment]
Agreed. Closing.

**Pull request closed without merging**
