### PR TITLE
Remove Keybase integration

### LINKED ISSUE #13670: Remove all Keybase features from Mastodon
### Pitch and Motivation

Because Keybase is acquired by Zoom, a large privacy disrespecting US company, Mastodon's (and all privacy loving Mastodon servers) reputation is at stake.

https://blog.zoom.us/wordpress/2020/05/07/zoom-acquires-keybase-and-announces-goal-of-developing-the-most-broadly-used-enterprise-end-to-end-encryption-offering/

So this is actually not a feature request, but an anti-feature request.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #13670 

Keybase has been acquired by Zoom and has, to my knowledge, stopped development of its platform. Also, the manual approval for Mastodon servers that they insisted on doing on their side never scaled and created frustration on our side. Also, Keybase never solved the verification problem in the way that people expected it to be solved, i.e. I still won't know if I'm looking at the real, famous John Smith, or just someone who claimed the john.smith handle on Keybase. For all other purposes it doesn't do anything that our own link verification mechanism doesn't do already.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by Gaelan** [comment]
FYI, I (and presumably anyone else who used Keybase with Mastodon) just got this email:

> Subject: your mastodon.social (gaelan) proof just broke
> 
> Uh-oh, gaelan, your previously-proven mastodon.social identity gaelan just broke. We've been checking it repeatedly, and it's not working from our perspective.
> 
> If you deleted a public proof, remember that proofs must stay public so anyone can trust you without trusting the Keybase.io server.
> 
> Here are your options: you can (a) revoke the proof, (b) replace it, or (c) ask us to keep trying. All this can be done from the Keybase app or website.
> 
> Thanks! -Keybase

(Not that I'm disagreeing with the decision here: keybase seems very much on its deathbed)

**Comment by levigroker** [comment]
Hi all, I too just got this keybase email, and while I realize there was a lengthy discussion in the related issue, I'm still unclear as to why this seemingly generic identity verification mechanism was removed. Unfortunate.

**Comment by Gargron** [comment]
The version with this PR has not been released yet. Also, the generic method of verification is link verification. Sorry about the noise.

**Comment by KaKi87** [comment]
> Keybase has been acquired by Zoom and has, to my knowledge, stopped development of its platform

Those seem to be good reasons to remove the Keybase integration from Mastodon, but please provide sources to support your statements.

Thanks

**Comment by Gargron** [comment]
grafik

https://github.com/keybase/client/graphs/contributors
https://techcrunch.com/2020/05/07/zoom-acquires-keybase-to-get-end-to-end-encryption-expertise/

**Comment by TheButterZone** [comment]
> stopped development of its platform

Just updated Keybase to Version 6.0.1-20220609162338+0fc9feea3d (6.0.1-20220609162338+0fc9feea3d)

June 9, 2022, 16:23:38 if I'm reading that correctly.

**Comment by spitfire** [comment]
> > stopped development of its platform
> 
> Just updated Keybase to Version 6.0.1-20220609162338+0fc9feea3d (6.0.1-20220609162338+0fc9feea3d)
> 
> June 9, 2022, 16:23:38 if I'm reading that correctly.

The client is still being updated. The fact that the development slowed down, does not mean it has stopped.
Also: why remove a feature that is working? As a political statement?

**Comment by hexandcube** [comment]
>The client is still being updated. The fact that the development slowed down, does not mean it has stopped.

The client is still being maintained, but the development has completely stopped in 2020

**Comment by mathieujobin** [comment]
One core dev as resumed working on keybase, which is well alive. and Zoom isn't as evil as others. Anyway, that's very subjective.

image

I wish those features could be merged back.

Thanks

**Comment by kg4zow** [comment]
I can understand if *some people* might not want to allow Keybase proofs, however I think **this is a decision which should be left up to each server operator**, rather than being forced on every server by fiat like this.

Keybase IS still being actively maintained - certainly not at the same rate it was originally, but it hasn't been abandoned by any means. If it were being abandoned, they would have just shut it down entirely, rather than continuing to pay the S3 storage bill for everybody's encrypted data blocks (for which users are *still* not being charged). And it's not "just maintenance" ... there have been new features added, including [Keybase Sites](https://book.keybase.io/sites), which I am currently using to host a few personal web sites.

Remember that the whole reason Zoom acquired Keybase was to get access to their security expertise, after several security issues were found in the Zoom client. I'm sure that after the acquisition, Zoom wanted the Keybase developers to work on the Zoom client code, so it makes sense to me that the "pace of commits" on the Keybase client repo dropped at the time.

PLEASE consider restoring this functionality, and making it configurable by each server operator. Even if you want it make it "off by default" for new installs, and leave it off for `mastodon.social`, at least give the server operators a way to turn it back on if they want to.

Otherwise, as others have mentioned, this feels more like a political statement than anything else.

**Comment by Nezteb** [comment]
@kg4zow does bring up good points.

The repos are still getting updates: https://github.com/keybase

I'm curious what @pzduniak, @joshblum, @michalz-zoom, @chrisnojima, and @mmaxim think. Sorry for the pings, but your opinions would be super valuable. 😅

**Comment by billyjbryant** [comment]
Is there any update on whether or not Keybase will be re-integrated for Mastodon verification?

**Comment by spitfire** [comment]
Probably not, as this seems to be some political statement from mastodon team:/

**Comment by tesaguri** [comment]
The maintenance status of Keybase is only one of the problems stated in the OP, and the other problems need to be solved as well, I suppose?

Especially, the <q>manual approval</q> problem significantly limits the applicability of the feature and I'd empathize with the dev team if they don't want to maintain a feature that is only available to a set of servers chosen by a thirdparty in a centralized way.

**Pull request merged**
