### PR TITLE
Change design of federation pages in admin UI

### PR DESCRIPTION
**Pull request by Gargron**
Redesign the domain page to use new metrics API and design, add graphs for development of numbers over time (even though the displayed numbers are totals for all time, as opposed to on the dashboard or tag pages), add most used languages and most followed accounts for that domain to give a quick representation of what the domain is about.

image

### Changes

- Remove extra page/form submission needed to unblock a domain
- Change metrics API to support returning totals outside of time range by omitting `previous_total`
- Change metrics API to support returning non-numeric totals with `unit`/`human_value`
- Change filters for domains with delivery failures
- Change public/private comment inputs to be single-line (helps with autocomplete of past values)
- Fix being able to queue multiple domain purge workers at the same time

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
“their followers here” VS “our followers there”??

**Comment by ClearlyClaire** [comment]
Missing (or unclear) from the PR descriptions are:
- the red “Delivery unavailable” text in the instance list being replaced with a label-less warning icon:
image
- the shortcuts from #15771 being removed altogether

**Comment by ClearlyClaire** [comment]
No, they don't seem to be. I think that would be useful indeed, although it could have mild privacy implications.

**Comment by ClearlyClaire** [comment]
Not that this is not really a new issue (in the sense that it also affects the admin dashboard), but the graphs are not necessarily accurate as undoing a follow, deleting a status etc. will affect the value for the time it was created.

**Pull request merged**
