### PR TITLE
Update fr.yml

### PR DESCRIPTION
**Pull request by trebmuh**
punctuation

### CODE REVIEW

**Comment by Komic** [comment]
[also gotta fix the •](https://github.com/tootsuite/mastodon/pull/4533), sorry about that!

**Comment by ykzts** [comment]
@trebmuh #4533 looks better to me. What do you think?

**Comment by trebmuh** [comment]
@ykzts yep, all good, you can squeeze this very PR and merge #4533 which includes the same fix + another one. Thanks @Komic .

**Comment by ykzts** [comment]
@trebmuh Thank you for checking another Pull Request!

**Pull request closed without merging**
