### PR TITLE
Leave unknown language as nil if account is remote

### PR DESCRIPTION
**Pull request by tribela**
It is not reasonable to use Local instance's language setting for foreign user's toot.

### CODE REVIEW

**Comment by Kjwon15** [comment]
When language field is `nil`, Is it never shown to user who filtered some languages?

**Comment by Gargron** [comment]
The language detector is super inaccurate for short messages. Also, you can't ignore when people set a posting language preference (which is hopefully more correct than the detector, although vandalism is also possible)

**Comment by Kjwon15** [comment]
So.. It's better to set `nil` on foreign toot which not having language field?

**Comment by ThibG** [comment]
@Kjwon15 When a status' language is set to `nil`, it is always shown.

@Gargron afaict this change doesn't ignore the posting language setting, it just drops the fallback to default user / instance setting on receiving remote toots for which a language wasn't defined and for which the detection has been deemed unreliable.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by Kjwon15** [comment]
Yes, It actually fixes a bug

**Pull request merged**
