### PR TITLE
Fix SSL configuration regression in streaming API

### LINKED ISSUE #10223: Timeline streaming stopped after #10210
### Actual behaviour
Streaming stopped because connection from node to postgresql become SSL even if DB_SSLMODE is not set. (regression from #10210)

### Steps to reproduce the problem

Start streaming service with postgresql which works non ssl connections. I got error log, and streaming stopped.

```
ERR! Error: The server does not support SSL connections
```

There is not DB_SSLMODE in my .env.production. As far as I investigate, "ssl" option of pg.Pool() of node not has "sslmode" option. Probabry, just only add "ssl" key, and even if it is empty, connection to postgresql become SSL.

### Specifications
- mastodon: master (3f4a6d4)
- My server is all-in-one that is contains web, streaming, sidekiq, redis and postgresql in single.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #10223

### CODE REVIEW

**Comment by kedamaDQ** [comment]
Thanks! Thanks a lot!!

**Comment by kedamaDQ** [comment]
Please wait. Just with the "ssl" key, node forcedly seemed to connect with ssl.

**Comment by Gargron** [comment]
Even if `false`? :confused:

**Comment by kedamaDQ** [comment]
I will check it.

**Comment by kedamaDQ** [comment]
As far as I confirmed, the situation did not change. Just with the key "ssl", streaming stops, it seems that an error is output to the log.

I done in development environment:

```
# git fetch upstream pull/10225/head:check
# git checkout check
# foreman start
```

But situation did not change... :thinking:

**Comment by Gargron** [comment]
@kedamaDQ I'm going to try passing `ssl: undefined`. Let me know if it works.

**Comment by kedamaDQ** [comment]
Just a moment please. I am midnight in my country ... I'm sorry.

**Review by ykzts — APPROVED** [review]

**Comment by kedamaDQ** [comment]
I'm sorry, I forgot to delete "DB_SSLMODE=prefer" from my .env ...
I deleted "DB_SSLMODE" and confirmed to solved the problem with either "false" or "undefined".

Thank you for your response!

**Comment by kedamaDQ** [comment]
Oops...sorry I have probrems yet...
スクリーンショット 2019-03-10 15 23 33

**Pull request merged**
