### PR TITLE
Made images from posts draggable

### PR DESCRIPTION
**Pull request by ghost**
In posts, I have found annoying to not being able to drag-and-drop images to my desktop.

I propose to change this—or at least to debate about it! 😉

### CODE REVIEW

**Comment by vmstan** [comment]
Does this change the "zoom" behavior?

**Comment by vmstan** [comment]
Yeah I applied it and I could only make the image in the timeline view drag, which is a nice improvement, but ideally they both would.

**Comment by vmstan** [comment]
I have the change running on https://vmst.io and the expanded image doesn't drag.

**Comment by Gargron** [comment]
I'm not sure if there's a point in dragging the possibly-low-res thumbnail?

**Comment by vmstan** [comment]
> I'm not sure if there's a point in dragging the possibly-low-res thumbnail?

Maybe not a photograph or something super detailed but a meme or something to send to a friend or repost, I just used it to grab something a few minutes ago 😆

**Pull request closed without merging**
