### PR TITLE
Improve language filter

### PR DESCRIPTION
**Pull request by renatolond**
After investigating #5035 I've made some tests at masto.donte.com.br to find out what could improve the language filter and this are the results of my investigation.

I'm removing html tags as the first stage of simplify text, so that the final text sent to CLD3 only the original text or as close to that as possible.

Also, when receiving a text in ActivityPub, if the language doesn't come, I'm trying to detect it from the text that was received.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by ykzts** [comment]
Why Travis does not run?

**Comment by renatolond** [comment]
Sorry, added one more commit to remove the custom_emoji before the detection.

**Comment by renatolond** [comment]
Don't know about travis, I checked over there and it seems the PR is not appearing on the list 🤔 
I can close this one and open another to see if it solves it.

**Comment by ykzts** [comment]
1. Close PR
2. Delete branch
3. Restore branch
4. Reopen PR

Can you try out?

**Pull request closed without merging**
