### PR TITLE
WIP: Fix sass deprecation warnings

### LINKED ISSUE #32608: Fix Sass Deprecation warnings
### Steps to reproduce the problem

Currently when compiling assets via webpack, we have a number of Sass Deprecation warnings. It'd be good to fix these, and they look mostly find the source of the warning and replace it with the newer syntax:

The current warnings on main @ [`1fc165de02`](https://github.com/mastodon/mastodon/tree/1fc165de02d79294c8a218f5fa82bcd477484ca1) are as follows:

```
Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 66.6666666667%)
color.adjust($color, $lightness: 20%)

More info: https://sass-lang.com/d/color-functions

   ╷
14 │ $darker-text-color: lighten($ui-primary-color, 20%) !default;
   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/contrast/variables.scss 14:21  @import
    app/javascript/styles/contrast.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 40%)
color.adjust($color, $lightness: 12%)

More info: https://sass-lang.com/d/color-functions

   ╷
15 │ $dark-text-color: lighten($ui-primary-color, 12%) !default;
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/contrast/variables.scss 15:19  @import
    app/javascript/styles/contrast.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 50%)
color.adjust($color, $lightness: 6%)

More info: https://sass-lang.com/d/color-functions

   ╷
16 │ $secondary-text-color: lighten($ui-secondary-color, 6%) !default;
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/contrast/variables.scss 16:24  @import
    app/javascript/styles/contrast.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 32.2580645161%)
color.adjust($color, $lightness: 10%)

More info: https://sass-lang.com/d/color-functions

   ╷
17 │ $highlight-text-color: lighten($ui-highlight-color, 10%) !default;
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/contrast/variables.scss 17:24  @import
    app/javascript/styles/contrast.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 61.7283950617%)
color.adjust($color, $lightness: 50%)

More info: https://sass-lang.com/d/color-functions

   ╷
18 │ $action-button-color: lighten($ui-base-color, 50%);
   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/contrast/variables.scss 18:23  @import
    app/javascript/styles/contrast.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 12.3076923077%)
color.adjust($color, $lightness: 8%)

More info: https://sass-lang.com/d/color-functions

   ╷
19 │ $success-green: lighten(hsl(138deg, 32%, 35%), 8%);
   │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon-light/variables.scss 19:17  @import
    app/javascript/styles/mastodon-light.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 32.0987654321%)
color.adjust($color, $lightness: 26%)

More info: https://sass-lang.com/d/color-functions

   ╷
36 │   $ui-base-lighter-color: lighten(
   │ ┌─────────────────────────^
37 │ │   $ui-base-color,
38 │ │   26%
39 │ │ ) !default; // Lighter darkest
   │ └─^
   ╵
    app/javascript/styles/mastodon/variables.scss 36:25  @import
    app/javascript/styles/application.scss 2:9           root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 26.1538461538%)
color.adjust($color, $lightness: 8%)

More info: https://sass-lang.com/d/color-functions

   ╷
70 │ $highlight-text-color: lighten($ui-highlight-color, 8%) !default;
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon/variables.scss 70:24  @import
    app/javascript/styles/application.scss 2:9           root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 7.2727272727%)
color.adjust($color, $lightness: 4%)

More info: https://sass-lang.com/d/color-functions

   ╷
72 │ $action-button-focus-color: lighten($ui-base-lighter-color, 4%) !default;
   │                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon/variables.scss 72:29  @import
    app/javascript/styles/application.scss 2:9           root stylesheet

Deprecation Warning: transparentize() is deprecated. Suggestions:

color.scale($color, $alpha: -65%)
color.adjust($color, $alpha: -0.65)

More info: https://sass-lang.com/d/color-functions

   ╷
78 │   --on-surface-color: #{transparentize($ui-base-color, 0.65)};
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon-light/variables.scss 78:25  @import
    app/javascript/styles/mastodon-light.scss 1:9              root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 4.9382716049%)
color.adjust($color, $lightness: 4%)

More info: https://sass-lang.com/d/color-functions

   ╷
98 │   --dropdown-border-color: #{lighten($ui-base-color, 4%)};
   │                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon/variables.scss 98:30  @import
    app/javascript/styles/application.scss 2:9           root stylesheet

Deprecation Warning: darken() is deprecated. Suggestions:

color.scale($color, $lightness: -42.1052631579%)
color.adjust($color, $lightness: -8%)

More info: https://sass-lang.com/d/color-functions

   ╷
99 │   --dropdown-background-color: #{rgba(darken($ui-base-color, 8%), 0.9)};
   │                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon/variables.scss 99:39  @import
    app/javascript/styles/application.scss 2:9           root stylesheet

Deprecation Warning: hue() is deprecated. Suggestion:

color.channel($color, "hue", $space: hsl)

More info: https://sass-lang.com/d/color-functions

   ╷
61 │     hue($color),
   │     ^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon-light/variables.scss 61:5  lighten()
    app/javascript/styles/mastodon/variables.scss 72:29       @import
    app/javascript/styles/application.scss 2:9                @import
    app/javascript/styles/mastodon-light.scss 2:9             root stylesheet

Deprecation Warning: hue() is deprecated. Suggestion:

color.channel($color, "hue", $space: hsl)

More info: https://sass-lang.com/d/color-functions

   ╷
53 │     hue($color),
   │     ^^^^^^^^^^^
   ╵
    app/javascript/styles/mastodon-light/variables.scss 53:5  darken()
    app/javascript/styles/mastodon/variables.scss 99:39       @import
    app/javascript/styles/application.scss 2:9                @import
    app/javascript/styles/mastodon-light.scss 2:9             root stylesheet

Deprecation Warning: transparentize() is deprecated. Suggestions:

color.scale($color, $alpha: -50%)
color.adjust($color, $alpha: -0.5)

More info: https://sass-lang.com/d/color-functions

    ╷
112 │   --on-surface-color: #{transparentize($ui-base-color, 0.5)};
    │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    app/javascript/styles/mastodon/variables.scss 112:25  @import
    app/javascript/styles/application.scss 2:9            @import
    app/javascript/styles/mastodon-light.scss 2:9         root stylesheet

Warning: 158 repetitive deprecation warnings omitted.

Warning: 164 repetitive deprecation warnings omitted.
```

### Expected behaviour

No deprecation warnings should be output, besides the legacy-js-api ones

### Actual behaviour

Deprecation warnings are output

### Detailed description

_No response_

### Mastodon instance

n/a

### Mastodon version

v4.3.0 / main

### Browser name and version

n/a

### Operating system

n/a

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
This should start to resolve #32608, however, the mastodon-light theme is currently really messed up, and I'm not sure why exactly. I'm guessing the difference comes from the [overridden lighten/darken](https://github.com/mastodon/mastodon/pull/32611/files#diff-51dfccf3c923b37fdc92ea2a126c1bb644d3fd67bd632c04431a18399e393027L50-L66) functions in the mastodon-light theme?

### v4.3.0 on hachyderm:

Screenshot 2024-10-21 at 18 43 45

### After this change

Screenshot 2024-10-21 at 18 44 18

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
I think what we may need to do is to actually define a variable for the input backgrounds, rather than using lighten/darken everywhere.

**Comment by ThisIsMissEm** [comment]
Also, in the light theme, the links in the settings navigation basically have no hover styling.

**Comment by renchap** [comment]
Couldn't we rather define our own `darken` and `lighten` SASS function (in the base theme), rather than changing all the call sides, and overriding it in the light mode file?

**Comment by ThisIsMissEm** [comment]
I'm going to close this and hand it back to someone else to try to tackle.

**Pull request closed without merging**
