### PR TITLE
Fix SidekiqProcessCheck checking for a queue name that isn't used in Mastodon

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by inga-lovinde** [comment]
As I understand, this is what removes the following warning from the admin dashboard:

>  No Sidekiq process running for the ingress queue(s). Please review your Sidekiq configuration 

The warning itself does not mean something is wrong with Mastodon; it is there by mistake, and this PR removes it.

Leaving this comment there so that other admins who see such a warning in their admin dashboard can find this PR. (Right now, the warning text produces zero results in Qwant, DuckDuckGo or Google.)

**Comment by ClearlyClaire** [comment]
I'm not sure why you would get that warning, it was only in `main` for a short time and didn't reach any Mastodon release. Warnings for queues other than `ingress` should be accurate.

**Comment by inga-lovinde** [comment]
I'm getting it on the latest glitch docker image from pluralcafe.
(I believe it's that one: https://github.com/pluralcafe/mastodon/tree/glitch)

**Comment by ClearlyClaire** [comment]
Oh yeah, that seems outdated, and unfortunately picking a version from the short amount of time where this bug existed…

**Pull request merged**
