### PR TITLE
Adding arabic string localization (rebased)

### PR DESCRIPTION
**Pull request by yookoala**
Rebased and squashed commits by @BoFFire. Fixed errors in Travis.

resolves #1798
resolves #1950

### CODE REVIEW

**Comment by BoFFire** [comment]
Thank you :)

**Review by mjankowski — DISMISSED** [review]
There are two keys which are not used (see travis build) but which are in your translation -- can you remove those?

(They were very recently removed, which is why you had them to start with)

**Comment by yookoala** [comment]
@mjankowski Obsoleted translations removed.

**Comment by yookoala** [comment]
@mjankowski Hi, Can you please check this PR again? See if it still miss anything. Thanks.

**Comment by yookoala** [comment]
@mjankowski Hello. Please read this again if you have time. We've passed the tests now.

**Review by wxcafe — APPROVED** [review]
lgtm

**Comment by BoFFire** [comment]
Thanks for the fixes @yookoala :)

**Review by Gargron — APPROVED** [review]

**Pull request merged**
