### PR TITLE
Dutch language added

### PR DESCRIPTION
**Pull request by meneer**

### CODE REVIEW

**Comment by xvilo** [comment]
Thanks Mate! Was just looking into translating it.

**Comment by blackle** [comment]
why are these changes spread out over multiple branches?

**Comment by meneer** [comment]
> Pick your reaction
I have no clue about the inner workings of github. Will try to find sme more info to prevent my multiple branches

**Comment by yookoala** [comment]
You're creating / editing files directly in Github's editor?

**Comment by yookoala** [comment]
Two issues to your patches.
1. Unnecessarily breaking commits into different branch.
2. Your editor is using Windows EOL. That blocks normal workflow in code diff-ing.

**Pull request closed without merging**
