### PR TITLE
Preserve Photo Sphere metadata

### PR DESCRIPTION
**Pull request by akihikodaki**
Changes required by server-side for #5867. See also #6138.

### CODE REVIEW

**Comment by akihikodaki** [comment]
See https://github.com/kagucho/documentation/commit/dc7e75c560c136a939f8a44701823b259900b54e for the corresponding change for the documentation.

**Review by Gargron — COMMENTED** [review]
New system dependency... What's the CC file?

**Comment by akihikodaki** [comment]
It is an image with Photo Sphere metadata and is used for the spec. I added the source link.

**Comment by neuhaus** [comment]
Could we please get this merged? Almost everything is ready

**Pull request closed without merging**
