### PR TITLE
Run Prettier on JS & JSX files

### PR DESCRIPTION
**Pull request by renchap**
This PR removed `.js` and `.jsx` from the files ignored by Prettier (first commit), then runs `yarn fix` (second commit).

It formats every JS & JSX files using Prettier, hence the very large diff.

This is the recommended way of handling JS formatting in the JS ecosystem, and is recommended by ESLint (rather than having ESLint check for formatting issues).

If this gets merged, then another PR needs to add the merged commit to `.git-blame-ignore-revs` so this refactor is i[gnored in Github's blame view](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).

If/when this is merged, then forks should make the same change in their `.prettierignore`, and run `yarn fix` on their whole codebase when rebasing this commit.

Open PRs will also need to be rebased, and run `yarn fix` to make their code compliant with the new format.

### CODE REVIEW

**Comment by mjankowski** [comment]
I'm assuming the vast majority of this is automated corrections -- which both makes it likely to be fine, but also the sheer size here is hard to review. Thoughts on breaking into smaller PRs? (or at minimum, breaking out the eslint config changes into separate ahead of the actual application of rules, etc...)

**Comment by renchap** [comment]
The first and last commits are manual, and are only there to enable Prettier and add a few ESlint comments that were badly formatted.

The second commit is fully automated and the result of `yarn fix`.

This can not be split further, as this PR only does one thing: enabling prettier for JS files.

What is missing here is approval from @Gargron and @ClearlyClaire, understanding that this will require work from our forks, and require all PRs to be rebased / apply prettier to them.

**Comment by nschonni** [comment]
It only shifts the fork issue, but I'd do this in separate batches for JS and one for JSX

**Comment by mjankowski** [comment]
This is still in draft, ~1 year old, needs rebase (also changes many many files) ... is this still worth contemplating/rebasing, or should we close?

**Comment by renchap** [comment]
Let's close it for now. The team fears that changing so many files (even if 100% automated) will make things very hard for forks and open PRs.

**Pull request closed without merging**
