### PR TITLE
harden docker-compose

### PR DESCRIPTION
**Pull request by Eriner**
Drop linux capabilities for redis, web, streaming, and sidekiq services.

Use a read-only root filesystem and create tmpfs volumes as necessary.

### CODE REVIEW

**Comment by shleeable** [comment]
This needs to be tested, but thanks for investigating this change.

**Comment by Eriner** [comment]
These changes should also be carried over into the helm charts I suppose.

Additional hardening options could be set here (`no-new-privileges` comes to mind) but I've tried avoided those which might cause breakage downstream.

**Comment by Eriner** [comment]
It's also possible that an `cap_add: [mkdir]` might be necessary if directories don't exist (first time installation). I haven't tested that.

**Comment by ineffyble** [comment]
Good change but needs comprehensive testing, easy to miss a specific scenario/component needing a specific capability.

**Comment by Eriner** [comment]
Of course. FWIW noagendasocial.com has been running with these settings for more than a year without any issues to my knowledge, but I haven't done any testing of first-time instance setup with these settings, hence the potential need for `mkdir` cap.

**Comment by mig5** [comment]
I tried these changes out but it broke my redis container (and thus everything else), the logs were showing this:

```
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
su-exec: setgroups: Operation not permitted
```

After I reverted that cap change from the redis container definition (but kept the other changes), everything else seems OK at first glance.

This is the docker image I'm using for redis:

```
redis                                               7-alpine        96a149ad0157   8 days ago      28.4MB
```

**Comment by Eriner** [comment]
@mig5 does applying [959af01](https://github.com/mastodon/mastodon/pull/21165/commits/959af0105ff6cc4a7c8740bd8b01f0e827e5c3f4) fix it?

**Comment by mig5** [comment]
@Eriner yes, so far so good! I'll let you know in the next couple days if I encounter problems, but otherwise assume all good. 

The other changes have also remained fine for me for 9 days without any obvious issue.

**Comment by Eriner** [comment]
Adding `setuid` isn't ideal. It's probably better to explicitly set the `user` and fix the incongruence, but that will be a more involved "fix" and probably break more deployments than just accepting the risk of `setuid` for redis. Permission (in)congruence for host-mounted volumes is always a pain because of host environment variety. Perhaps a comment inline with the `cap_add` to suggest uncommenting a (new) commented-out `user` directive?

**Comment by nberlee** [comment]
@Eriner great work, i wish saw this PR before I mostly did the same thing.... I will refrain from creating another PR from this commit: https://github.com/nberlee/mastodon/commit/d6731f7ee7dc4970e598ea6162a194aaf6cd0ef6

But please note the differences:
* container `db` is able to run with `read_only` and cap_drop ALL
* mount options `nosuid`,`nodev` and `noexec` prevents creating and accessing executables, SUID masked files (which are really bad) and preventing character devices in those directories.
* I like my non-root approach better (having the `user:` directive means the container never becomes root) Having that said, CAP_DROP still mitigates a lot

**Comment by mig5** [comment]
The tmp/pids thing affected me too, eventually, after I restarted docker on my machine. 

I ended up going with @nberlee 's changes and they've been working well for me. 

Here's my current [docker-compose.yml](https://gist.github.com/mig5/3b352d2d09d61faddfb2b722e60478ee).

**Comment by Eriner** [comment]
Sorry it's taken me so long to get back to this. @nberlee I've integrated your changes into the latest commit, as I too was impacted by moby/moby#20437.

**Comment by Eriner** [comment]
I also added an explicit `user` directive to each service, leaving fixing any host incongruence to the operator. This is necessary to name uids when setting ownership of the tmpfs dirs.

**Comment by mjankowski** [comment]
Closing from lack of activity/rebase ... and because I personally don't know if this is all still relevant after other changes to the config. If you want to nudge forward, can you rebase/reopen?

**Pull request closed without merging**
