### PR TITLE
Feat: allow filter original statuses on user profile

### LINKED ISSUE #18413: Add "Show boosts" option on the account profile page
### Pitch

Add a "Show boosts" switch button on the account profile page, so people can choose only to see original posts or posts including reblogging.

Here is a demo:

(maybe the button should be smaller)

Adding a `collapseButton` may make things too complex, so I simply add a `Toggle` in `Header`.

I will try to open a PR if this is acceptable.

### Motivation

I have seen so many people in my community say that they want to see one's original posts, especially when dealing with follow requests. Therefore, this option will be very useful.

### PR DESCRIPTION
**Pull request by OmmyZhang**
The backend parameter is already added 5 years ago #9640 .

I continue to see users complaining that when they process follow requests, they sometimes have to spend a long time finding a original status. Therefore, I believe this feature is very useful.

I agree that one more column may not be suitable for small-screen phones and multi-column UI, especially after there's the sidebar since 4.0. So I add a switch. In the future, perhaps we can also change withReplies to a switch and keep only 2 columns.

 How it looks:

image

image

This change also incidentally brings some minor optimizations to the display of loading. Returning a full screen`<LoadingIndicator>` is only necessary when account info is not ready, otherwise the `isLoading` of `<StatusList>` just works fine.

Close #18413 .

Some other related issues: #10011 #20575 #21418 .

### CODE REVIEW

**Comment by trwnh** [comment]
> So I add a switch. In the future, perhaps we can also change withReplies to a switch and keep only 2 columns.

imo it would be better if there were no tabs at all, just posts, and *everything* was a switch -- include replies, include boosts, include media

**Comment by jiangshanghan** [comment]
整挺好

**Comment by OmmyZhang** [comment]
@jiangshanghan Could you please remove your comment? It's somehow inappropriate.

可以删掉你的评论吗，不太合适。

**Comment by jiangshanghan** [comment]
> 

please do not scream like that. my comments had no offense.

**Comment by aaaaalbert** [comment]
AFAICS, since v4.2 the Profile page tabs work like [this](https://github.com/mastodon/mastodon/pull/26302#issuecomment-1666001844) (quoting the linked PR), implementing your suggestion:

> "Posts" tab now shows all of the users Posts + Boosts
> "Posts & Replies" tab only shows users Posts & Replies

Caveats:
* v4.1 still shows boosts in "Posts" and "Posts & Replies"
* The tabs are predefined filters, no finer-grained configuration is available

**Comment by OmmyZhang** [comment]
solved by #26302

**Pull request closed without merging**
