### PR TITLE
Add ./bin to PATH and specify WORKDIR in dev container

### PR DESCRIPTION
**Pull request by c960657**
When you start a Bash shell in the dev container using `docker compose exec bash`, the default folder is `/`, so you have to manully run `cd /workspace/mastodon`. Also, you have to type `bin/rails` and not just `rails`, because `/workspace/mastodon/bin` is not in `PATH`.

The current `.devcontainer/docker-compose.yml` does not only expose the repository root to the container, but also its parent folder, i.e. all other projects you have checked out into the same folder as Mastodon. This makes the path to Mastodon inside the container depend on the name of the folder containing Mastodon (this defaults to `mastodon` when cloning the repo, but it may have renamed for whatever reason). I don't know why that is, but it seems a bit scary. I have asked for the rationale [here](https://github.com/mastodon/mastodon/pull/23872#discussion_r1315061565), but so far I have not received a response.

In any case, it seems simpler if the repo is always mounted at the same path inside the container, `/mastodon`. This makes it easy to include `/mastodon/bin` in `PATH`, and to specify `WORKDIR` so the default directory is `/mastodon` when starting a shell in the container.

### CODE REVIEW

**Comment by taku0** [comment]
Still got `fatal: detected dubious ownership in repository at '/mastodon'`.  `USER vscode` in `Dockerfile` would be better than adding `/mastodon` to `safe.directory`.

Even after that, I got `webpack config /mastodon/config/webpack/tests.js not found, please run 'bundle exec rails webpacker:install' to install Webpacker with default configs or add the missing config file for your custom environment.` Changing `NODE_ENV=tests` to `NODE_ENV=test` in `post-create.sh` doesn't help.  `config/webpack` directory doesn't have `tests.js` nor `test.js`.

**Comment by renchap** [comment]
I am not sure we should add `./bin` to `$PATH`, this is not a common setup and you should invoke it with a relative path.

The workdir change makes sense.



> Even after that, I got `webpack config /mastodon/config/webpack/tests.js not found, please run 'bundle exec rails webpacker:install' to install Webpacker with default configs or add the missing config file for your custom environment.` Changing `NODE_ENV=tests` to `NODE_ENV=test` in `post-create.sh` doesn't help. `config/webpack` directory doesn't have `tests.js` nor `test.js`.

Does this happen with a brand new container? We made some changes and assets are now compiled with `NODE_ENV=production` in tests, so nothing should refer to `config/webpack/tests.js` anymore.

**Comment by c960657** [comment]
> I am not sure we should add `./bin` to `$PATH`, this is not a common setup and you should invoke it with a relative path.

The need for adjusting `$PATH` comes from the use of `bundle config path 'vendor/bundle'` in `.devcontainer/post-create.sh`. If we didn't change that config setting, Bundler would just install `rails`, `rspec` etc. in `/usr/local/rvm/gems/default/bin` which is already in `$PATH`. So I don't think it is that uncommon to assume that these commands can be invoked without a relative path.

I am not sure why we run `bundle config path 'vendor/bundle'` in the first place. I guess it is nice to have the source files of the installed gems nearby, so you can easily inspect them in your text editor.

**Comment by taku0** [comment]
tests.js is removed by #27333. So should we change `NODE_ENV=tests` to `NODE_ENV=production` in post-create.sh?

**Comment by c960657** [comment]
The NODE_ENV issue has been fixed in # 28099.

> Still got `fatal: detected dubious ownership in repository at '/mastodon'`.

Is this still an issue? I cannot reproduce this. In fact, even when I completely remove the `safe.directory` line, I still cannot reproduce it. The line was added in #24303, and I remember experiencing getting the warning myself prior to that change, but I have forgotten under which circumstances the warning occurred.

> `USER vscode` in `Dockerfile` would be better than adding `/mastodon` to `safe.directory`.

That would prevent doing stuff inside the container that requires root privileges, e.g. `apt-get install`, and I think that would be annoying. Do you agree?

**Comment by taku0** [comment]
>> Still got fatal: detected dubious ownership in repository at '/mastodon'.
>
> Is this still an issue? I cannot reproduce this. In fact, even when I completely remove the safe.directory line, I still cannot reproduce it. The line was added in #24303, and I remember getting the warning myself prior to that change, but I have forgotten under which circumstances the warning occurred.

It is still reproduced on my Linux machine where `mastodon` directory is owned by user id 1000.

Steps to reproduce:

```bash
# Clone and checkout this PR.
git clone --depth 1 --single-branch https://github.com/mastodon/mastodon.git
cd mastodon
git fetch --depth 1 origin pull/26921/head:devcontainer-workdir
git switch devcontainer-workdir

# Remove existing container image if any.
docker image rm devcontainer-app

# Start containers.
docker compose -f .devcontainer/docker-compose.yml up -d

# Run post-create.sh
docker compose -f .devcontainer/docker-compose.yml exec app .devcontainer/post-create.sh
```

It shows the following messages:

```
# Make Gemfile.lock pristine again
git checkout -- Gemfile.lock
fatal: detected dubious ownership in repository at '/mastodon'
To add an exception for this directory, call:

        git config --global --add safe.directory /mastodon
```

Now we can tear down the containers:

```bash
# Tear down containers.
docker compose -f .devcontainer/docker-compose.yml down --volumes
```


>> USER vscode in Dockerfile would be better than adding /mastodon to safe.directory.
>
> That would prevent doing stuff inside the container that requires root privileges, e.g. apt-get install, and I think that would be annoying. Do you agree?

Executing `post-create.sh` with root user creates files owned by root under `vendor` directory on the **host** machine, which is not desirable.

`USER vscode` can be placed at the end of the Dockerfile and it doesn't affect lines `RUN apt-get ...`:

```patch
diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
index 820e25e..f021d90 100644
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -17,4 +17,4 @@ WORKDIR /mastodon
 
 ENV PATH=/mastodon/bin:${PATH}
 
-RUN su vscode -c "git config --global --add safe.directory /mastodon"
+USER vscode
```

After that, if we need a root privilege in a running container, we can use `sudo`.


> The NODE_ENV issue has been fixed in # 28099.

It is not fixed yet.  I got `TypeError: Cannot read properties of undefined (reading 'compress')` with `USER vscode`  patch above.

**Comment by c960657** [comment]
@taku0 When reproducing this, are you also deleting the container? Your steps to reproduce only mentions deletes the image (`docker image  rm`), not the container (`docker rm`).

When using these exact steps, I cannot reproduce the problem:
```
docker pull mcr.microsoft.com/devcontainers/ruby:1-3.2-bullseye
docker compose -f .devcontainer/docker-compose.yml rm --stop --force app
docker compose -f .devcontainer/docker-compose.yml build app
docker compose -f .devcontainer/docker-compose.yml up -d
docker compose -f .devcontainer/docker-compose.yml exec app bash .devcontainer/post-create.sh
```

In any case, I think the “dubiuos ownership”/`USER vscode` issue is outside the scope of this PR. This PR just moves the existing `git config -add safe.directory` from `devcontainer.json` to `Dockerfile`.

**Comment by daudix** [comment]
Moving the `git config --global --add safe.directory /mastodon` from Dockerfile to post-create.sh seems to fix the issue

**Comment by mjankowski** [comment]
There were a whole bunch of devcontainers/dockerfile/compose changes last week, some of which (removing peer dirs from volumes/workspace, remove post-create script completely, some user/perms stuff, etc) may have handled portions of what this PR was after.

Want to rebase this and see what else if anything is still necessary here?

**Comment by c960657** [comment]
> Want to rebase this and see what else if anything is still necessary here?

`.devcontainer/compose.yaml` now specifies `working_dir`, and `rails` can now be invoked directly via the bin wrappers `/usr/local/rvm/gems/default/bin`, so there is nothing left in this PR. Closing.

**Pull request closed without merging**
