### PR TITLE
Use active variants for boost icons and increase icon size

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Follow-up to #27817

## Before

image

## After

image

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Doing this without increasing the pixel size is possible, but we would need to redesign a 20×20px variant of our custom icons.

**Comment by renchap** [comment]
We discussed switching the icon SVGs to the 24px version. Will this change something to this PR?

**Comment by ClearlyClaire** [comment]
> We discussed switching the icon SVGs to the 24px version. Will this change something to this PR?

We basically have two choices:
- switching to 24px versions and merging this PR, at the cost of having icons that may look too big
- switching to 20px versions, redoing our custom icons, and adapting this PR to use them and remove the CSS changes

**Comment by ClearlyClaire** [comment]
Rebased on #28064 and switched to 24×24px icons:

image

**Review by renchap — DISMISSED** [review]
Looks good to me, but I would prefer to have @Gargron approve it as well

**Review by renchap — APPROVED** [review]

**Pull request merged**
