### PR TITLE
Add cross-domain fediverse remote authentication client support

### PR DESCRIPTION
**Pull request by abanink**
[OpenWebAuth](https://zotlabs.org/page/zot/specs+openwebauth) provides a light-weight form of cross-domain authentication between websites on the open web.
This PR shows how Mastodon users could log in as visitors on OpenWebAuth enabled services like Hubzilla and the project nicknamed "Streams" or any Fediverse server which implements the server-side of OpenWebAuth. Mastodon users do not need an account on the other server.
In practice, it depends on the services and the permissions that the Mastodon user has on the other server's services; e.g. a user on Hubzilla or Streams could allow a Mastodon user to post on his wall, upload a picture to his cloud etc.
Note: this is only the 'client' side of the protocol i.e. Hubzilla/Streams users could not log in to Mastodon.

How this can be tested:

Prerequisites:

    Hubzilla or Streams server ("OWA-S")
    user on Mastodon

Procedure:

    Log in on Mastodon
    In the same browser in a new tab: open the login screen of the OWA-S, perform a 'remote authentication' and enter the Mastodon handle as identifier

Expected outcome:

    The Mastodon user should now be logged in to the OWA-S as a visitor.

Note: this is just a test scenario for the protocol.

In a more real-life scenario, resources on Hubzilla/Streams would be available as
`https://OWA-S/<resource>?zid=<mastodon handle> ` 
in order for the user having this Mastodon handle to access the resource on the OWA-S.

The protocol code was borrowed from the Hubzilla code and adapted by me to work with the Mastodon code. I did not make an effort to re-use existing code in Mastodon.

Checks done:
Rspec:
```
$ rspec spec/requests/magic_spec.rb 

Randomized with seed 41651
 4/4 |======================================================================================= 100 =======================================================================================>|
4 examples, 0 failures
```

Rubocop:
```
$ rubocop app/controllers/magic_controller.rb spec/requests/magic_spec.rb config/routes.rb 
Inspecting 3 files
...

3 files inspected, no offenses detected
```

### CODE REVIEW

**Comment by anderspitman** [comment]
@abanink is there a link to an actual specification for OpenWebAuth anywhere? I found the high level explanation pretty unclear.

**Comment by abanink** [comment]
@anderspitman I don't have any knowledge of other specifications besides the reference implementation that you can find in the public (streams) and hubzilla repos on codeberg. For the OpenWebAuth client in (streams), it's [Code/Module/Magic.php](https://codeberg.org/streams/streams/src/branch/release/Code/Module/Magic.php).
Yet, and even though I'm not the author of the spec, I was able to write working software in a different software stack and in a different language as the reference implementation.
The code is out there and here to be inspected, tested and challenged.

Which are the questions for the existing spec you would need to see answered?

**Comment by erlend-sh** [comment]
> is there a link to an actual specification for OpenWebAuth anywhere?

This was recently created.

Spec:
https://codeberg.org/fediverse/fep/src/branch/main/fep/61cf/fep-61cf.md

Discussion:
https://socialhub.activitypub.rocks/t/fep-61cf-the-openwebauth-protocol/3907

**Review by mjankowski — COMMENTED** [review]
Is this actually ready for review? ... there's a lot of debugging/logging type code left in here, the style isn't really idiomatic ruby/rails code (or consistent with other controller actions in the app), etc...

**Comment by mjankowski** [comment]
Closing due to sheer age and lack of response to feedback here.

Please comment/reopen and address feedback if you'd like to nudge forward.

**Pull request closed without merging**
