### PR TITLE
In basic UI, bring 2-column view to the center

### PR DESCRIPTION
**Pull request by Hanage999**
Fix the layout of the new basic UI where columns are justified to the right when 2 columns are shown.

### CODE REVIEW

**Comment by Gargron** [comment]
Any side effects here? Does it affect how the multi-column UI looks?

**Comment by Gargron** [comment]
Two side effects:

1. When the page loads, the width of the center element jumps
2. In multi-column layout, everything becomes centered

**Comment by Hanage999** [comment]
> Two side effects:
> 
>     1. When the page loads, the width of the center element jumps
> 
>     2. In multi-column layout, everything becomes centered

2 looks like a good effect, and I would not mind 1, but it may well depend on how you use Web UI daily.

**Comment by Hanage999** [comment]
Another side effect:

3. In multi-column layout, you cannot scroll to the leftmost column when a window is not wide enough to cover all UI elements.

At least I'm going to fix this.

**Comment by trwnh** [comment]
It may be useful to add a class to the base body tag when "simple mode" is set or when "advanced mode" is set. This would allow CSS fixes to target only one of the two layouts.

**Comment by Hanage999** [comment]
https://github.com/tootsuite/mastodon/pull/10915 should serve the same purpose without side effects, so I close this PR.

**Pull request closed without merging**
