### PR TITLE
Update `actions/cache` to v4 (updates node 16->20)

### PR DESCRIPTION
**Pull request by mjankowski**
Should silence a bunch of deprecation/upgrade warnings in CI runs.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I think `renovabot` had a PR for that, but I'm unable to find it? IIRC there was an issue with download failures?

**Comment by mjankowski** [comment]
> I think `renovabot` had a PR for that, but I'm unable to find it?

Probably this? https://github.com/mastodon/mastodon/pull/28415

 > IIRC there was an issue with download failures?

I think the issues some people had were with the upload and download artifacts actions. I think this one is ok.

**Comment by renchap** [comment]
How did renovate miss this one? 🤔

**Review by renchap — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
> > I think `renovabot` had a PR for that, but I'm unable to find it?
> 
> Probably this? #28415
> 
> > IIRC there was an issue with download failures?
> 
> I think the issues some people had were with the upload and download artifacts actions. I think this one is ok.

You're right, thanks!

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
