### PR TITLE
Remove broken “share” option on account profile dropdown

### LINKED ISSUE #20931: Remove "Share {user}'s profile"
### Pitch

When you open your profile in Mastodon's web UI, there is a ["Share {user}'s profile"](https://github.com/mastodon/mastodon/blob/7fdeed5fbca1b6b761029870f02a3f812288f0aa/app/javascript/mastodon/features/account/components/header.js#L219) item in the menu. Has anyone ever used this?

image

Probably no one has used it.

From what I've researched, this was added in the #10337. And it hasn't worked since then. This is because the action `this.handleShare` does not exist.

I've investigated further and looked for any issues that mention this, but haven't found any. This means that in the 3+ years since this feature was added, no one has had a problem with it not working.
(I think one of the reasons is that it doesn't display in Firefox, which is the preferred browser for open source people.)

It's easy to fix this not working, but what you really want is to remove this functionality.

### Motivation

No need to maintain features that no one uses. Removing features reduces the code developers (and translators) need to read.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #20931

As pointed out of #20931, it's been broken ever since it was first introduced, over 3 years ago, so it should be either fixed (#21490) or dropped. Considering that I have seen nobody complain about it before now, it is unlikely many people even tried to use it, so removing it seems sensible.

### CODE REVIEW

**Comment by evelynmarie** [comment]
I oppose straight up removing this. I think it should be fixed instead of dropped.

**Review by evieluvsrainbows — COMMENTED** [review]
I oppose straight up removing this. I think it should try and be fixed instead of just removing it entirely.  Nobody has used it, because of the fact it hasn't worked. Perhaps if it was fixed, people would actually use it.

**Comment by rinsuki** [comment]
@evelynmarie this menu only appears on profile page, so user should be able to use browser's share functionality.

**Comment by ClearlyClaire** [comment]
> Nobody has used it, because of the fact it hasn't worked. Perhaps if it was fixed, people would actually use it.

Yeah, but I haven't read a single complaint about it not working either, so I suppose very few people have actually tried using it.

In any case, I'm not feeling strongly one way or another, both options (removing it, and fixing it) are fine by me.

**Comment by eai04191** [comment]
The `account.share` locale key is not used anywhere else, so if we remove this feature, we can remove the key at the same time.

**Comment by ClearlyClaire** [comment]
> I oppose straight up removing this. I think it should try and be fixed instead of just removing it entirely. Nobody has used it, because of the fact it hasn't worked. Perhaps if it was fixed, people would actually use it.

Made an alternative PR for that: https://github.com/mastodon/mastodon/pull/21319

> The `account.share` locale key is not used anywhere else, so if we remove this feature, we can remove the key at the same time.

Thanks for pointing that out! Added a commit to remove those.

**Comment by ClearlyClaire** [comment]
Superseded by #21490

**Pull request closed without merging**
