### PR TITLE
Fix not being able to invoke phrase search using unicode quotation marks

### LINKED ISSUE #26677: "Search for phrase" should support quote marks beyond " (U+0022)
### Pitch

To search for an entire phrase, the user currently needs to quote the phrase using QUOTATION MARK (Unicode U+0022). Many people use software that automatically replaces this character by typographic quotation marks (for US English, LEFT DOUBLE QUOTATION MARK U+201C and RIGHT DOUBLE QUOTATION MARK U+201D). This software often makes it difficult to type U+0022 unless you use a workaround. It would be great to accept the typographic marks as well as the ASCII version.

In addition, other languages use different styles of quotation marks, and it would be good to support as many of them as possible. E.g., single marks for UK English, guillemets for French, etc). Here is a reasonably complete set of such characters: “”‘’„«»「」『』'"《》

Reference: https://en.wikipedia.org/wiki/Quotation_mark

### Motivation

This would make phrase search considerably easier for people who use typographic (curly) quotes, as well as users of other languages.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #26677

### CODE REVIEW

**Comment by Gargron** [comment]
I would figure most people don't even notice there's a difference between them. The case of searching specifically for curly quotes seems very unlikely to me.

**Comment by ClearlyClaire** [comment]
I mean, I don't know of any search service that treats “fancy” quotes as double quotes, and breaking exact match on a “fancy” quote seems more surprising. But those are edge cases either way.

Also extending the PEG is a bit more cumbersome than I originally thought.

On a tangentially related note, I just noticed that having an uneven number of quotes in your search string results in full-text search being silently skipped, only giving you results from accounts and tags.

**Comment by Gargron** [comment]
Also, punctuation like `“` is *not* kept in the search index, so it would have no effect on the query, even within phrase match.

**Comment by ClearlyClaire** [comment]
I know, but `"foo « bar » baz"` should match `foo bar baz` and `foo « bar » baz` right? with the suggested changes it would be changed to `"foo " bar " baz"` which may match things… differently.

I suppose this is an ok approach, if not completely satisfactory. Those are edge cases anyway.

One thing I would suggest, though, is having these characters in the parser rules instead of a new ad-hoc substitution, so the logic is easier to follow, not being split in more places.

**Comment by Gargron** [comment]
It's much more bothersome to handle all quotation marks in the parser instead of normalizing them before processing, because not only do you need to define the `quote` rule to match them all, you also need to negatively match them all in the `term` rule.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
