### PR TITLE
Fixed low-hanging rubocop errors

### PR DESCRIPTION
**Pull request by expenses**
Managed to get the total amount of offenses down from 130 to 45.

### CODE REVIEW

**Comment by ineffyble** [comment]
Heh, I was literally thinking I should do this tonight.

**Comment by ineffyble** [comment]
Looks like Rubocop is now upset about string literals - are you able to make changes to stop the new errors showing up on Code Climate, @expenses ?

**Comment by expenses** [comment]
I didn't mean to include my 'boost tooltip' commit, but I'm not the best at git and I don't know how to get it out of the PR >_<

**Comment by expenses** [comment]
@ineffyble They're not showing up on my end, but I can fix them manually, yeah.

**Comment by expenses** [comment]
@ineffyble OK, so rubocop (0.48.1 on OSX) on my end says that string literals should use square brackets, while the rubocop that codeclimate uses says that they use should use round brackets.. I'm not quite sure which one to go with.

**Comment by ineffyble** [comment]
Hmm, it looks like that's a very recent change to Rubocop defaults https://github.com/Drenmi/rubocop/commit/a4db12efc4b02e45f3a21d70a3a89331c2a16222

**Comment by expenses** [comment]
@ineffyble Do we not worry about codeclimate then, seeing as they'll update their rubocop version sometime?

**Comment by ineffyble** [comment]
I think the commit I linked wasn't relevant for *string* literals. I'm assigning to @Gargron to sort this out.

**Comment by expenses** [comment]
@ineffyble No, I think you linked to the right thing. The [ruby style guide](https://github.com/bbatsov/ruby-style-guide#percent-literals) says that array literals (`%w`) should use square brackets.

**Comment by ineffyble** [comment]
Hmm, okay, yes. Code Climate docs show they're on Rubocop `0.46.0` but the Mastodon `Gemfile.lock` specifies `0.48.1` - sounds like this is a change between the two versions.

**Comment by expenses** [comment]
@ineffyble Just emailed support about updating their version.

**Comment by bdelmas** [comment]
@expenses I saw your comment: https://github.com/tootsuite/mastodon/pull/1757#issue-221789452 and I am coming to help.

If you want to do it yourself, the easiest can be to use cherry-pick. It let you pick the commit you want and add them to your branch.

Set a branch for you and just in case:
`git checkout rubocop` 
`git checkout -b old-rubocop`
`git checkout rubocop`

Comes back to where was master, the root of your branch and merge:
`git reset 067eb220 --hard` 

Add the 2 commits to the branch:
`git cherry-pick 6e72049` 
`git cherry-pick 428954a`

At that point you don't have the first commit, then rebase or merge if you prefer and resolve the merge/rebase conflict like you did. And push your PR with ` -f` this time to force push to erase the former rubocop branch and replace it by the new one.

You may take a look at `git rebase -i` in the future. It helps you to keep your commit clean by selecting what you want, what you want to rename, what you want to fusion with other commit, etc... 👍

**Comment by Gargron** [comment]
Hey, basically I just need more time to review this because of the number of changed files. I'll get to it in time! This PR is definitely good and wanted

**Comment by expenses** [comment]
@bdelmas Thanks!

**Comment by expenses** [comment]
I'm going to close this PR because it's out of date. If anyone wants to make a new one just:

* `git checkout -b rubocop`
* `rubocop -a`
* `git commit -a -m ""`...

**Pull request closed without merging**
