### PR TITLE
Support a "format" parameter to request raw source from API methods that return Status

### LINKED ISSUE #22502: Addition of plaintext request parameters for API
### Pitch

Add some form of plaintext parameter to requests such as statuses, account fields, et al.

For example, under [`GET /api/v1/statuses/:id`](https://docs.joinmastodon.org/methods/statuses/#get) the `content` and `account/fields` field returns exclusively HTML preformatted text, with no option to request unformatted plaintext responses 

However in the Serializer models for `Status`, `Account`, et al, the fields that return this HTML preformatted data all get passed through HTML formatting functions, and could easily bypassed under the presence of an `instance_option`, for example as is used [`source_requested?`](https://github.com/mastodon/mastodon/blob/main/app/serializers/rest/status_serializer.rb#L140) in the `REST::StatusSerializer`.

By applying similar functions to fields like `Status.text` under `REST::StatusSerialiser`, et al, we can quite simply provide the `Status.text` field as a replacement or in addition to `Status.content`. 

I also realise that there is an existing way to get this data, through the [`GET /api/v1/statuses/:id/source`](https://docs.joinmastodon.org/methods/statuses/#source) endpoint but if a client were to rely on this for plaintext content, it creates additional requests for the Mastodon server to handle which creates overhead for the server, as well as results in a slower experience for the client, which would be amplified in clients running on slower machines. This also doesn't resolve the formatting under `Account.fields`.

In addition to this, implementing this as a new parameter ensures that no existing client has any incompatibility with the API changes, but could easily take advantage of if the parameter were available.

I don't know if this should be implemented as a global parameter much like the limit parameter is in [API::BaseController](https://github.com/mastodon/mastodon/blob/main/app/controllers/api/base_controller.rb#L101) or if this should be on a per controller basis, but I think either would be effective. 

I can happily write a pull request that implement the feature for either method, if deemed desirable!

### Motivation

I've been helping a friend navigate the API, for her Mastodon TUI client in Free Pascal as you well know, API requests like status, account details, et al all return formatted HTML responses in JSON.

For those of us wanting to write clients that don't want or have access to HTML parsers and renderers, this is non-ideal having to manually strip and reformat the fields. 

A perfect example of clients that would benefit from this are those coming out of the Retrocomputing Community, such as [Macstodon](https://github.com/smallsco/macstodon
) (for classic Mac OS) and [Amidon](https://mastodon.social/@midwan/109531630748868249) (for Amiga), or CLI clients such as [Toot](https://toot.readthedocs.io/en/latest/). For example, MiDWaN writing Amidon was [having trouble with a HTMLView class](https://mastodon.social/@midwan/109534364332701006) for displaying content from the API. All of these examples would have a far simpler time with just formatting the plaintext response whether that be from an unformatted Status.content or Status.text, for example.

### PR DESCRIPTION
**Pull request by danielpunkass**
This pull request is offered as one possible solution to a challenge that seems common across many Mastodon API clients: needing or wanting to present Status content in plain-text format. Typically, client apps seem to do their best to strip HTML formatting from the `content` property, but it would be more consistent and easier if the API could just return raw source upon request. If accepted, I believe this PR would close #22502.

The proposed solution adds support for a 'format' parameter to all v1 API methods that return Status objects. This parameter, if set to 'source', instructs the API to return the status content as raw source instead of rendered HTML. Consistent with the /source endpoint on statuses, the raw source is returned in a 'text' property to clearly differentiate it from the HTML content that is return by default in the 'content' property. 

Controlling this behavior with the use of a 'format' parameter seems pragmatic, as opposed to for example exposing 'request_source' directly, because it leaves the door open to support other formats such as Markdown in the future, and also supports the possibility that the API might return multiple formats at once in a single response. Future interpretations of the 'format' parameter could, for example, read the value as a comma or space-separated list of desired formats to include in the response.

If the proposed solution is not considered acceptable for any reason, I would love to keep a conversation going and help to drive a solution to this so that myself and others who are using the Mastodon API can present a more consistent experience to users, with less work and less bug-proneness.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Note that the “source” is only known for local posts, anything remote is only known as HTML.

**Comment by danielpunkass** [comment]
@ClearlyClaire Thank you that's an interesting caveat. I wonder if the parameter name should convey the uncertainty. Maybe "preferred_format" or something? Or maybe just something to clarify in documentation if the PR is accepted.

I guess there are multiple use cases for wanting the "raw source" of a post. My interest is primarily in order to have large cache of an author's actual own writing, for ease of editing. Other developers who have a priority for displaying the status content in a non-HTML content will have to "strip formatting", at least for the federated statuses, as you say. I imagine for a long time to come all clients will also need/want to have a backup "strip formatting" case. My main interest in this PR is to offer a way for editor apps to efficiently obtain the history of posts in raw source format. But once I saw that `request_source` was a parameter on the `StatusSerializer` I thought it might as well be exposed to all API endpoints that culminate there.

**Comment by danielpunkass** [comment]
I wonder if I was too ambitious trying to tackle the whole API surface when supporting a "format" parameter. @ClearlyClaire do you think this might have a better chance of being reviewed and accepted if I revise the PR to very precisely add support for such a flag on the most important (for editor apps) endpoint, the one that lists a specific user's statuses?

I think that it might be easier to reason the merits of accepting such a PR so I'll start working on that this week unless there is any objection. Especially if plans to support Markdown proceed, it will become increasingly important to provide some means for clients to download a user's statuses in source format, because the Markdown will presumably be harder to reverse engineer, especially without knowing whether the user originally wrote the status using Markdown or not.

**Comment by danielpunkass** [comment]
Hi @mjankowski  - I did end up opening a separate pull request that tries to approach this problem more simply: #24987. It was opened in May so it seems possible it has merge problems, too. If you think there's any hope for it I'll clean it up if needed.

**Comment by mjankowski** [comment]
Cool, thanks -- will leave this one closed and get to that (eventually) in my triage process.

**Pull request closed without merging**
