### PR TITLE
Redesign landing page

### PR DESCRIPTION
**Pull request by Gargron**
grafik
___

### Design notes

- Less busy layout
- Reduce layout differences caused by various admin settings
- Public timeline on a separate page in masonry layout, like the public hashtag page
- Bite-sized tagline to communicate Mastodon's purpose
- Prominent hint that you can talk to people from other servers
- Prominent hint that mobile apps exist
- More useful server stats: Only total registered and monthly active (MAU)
- Server info and all custom content in one compact widget
- Layout form always displayed to simplify returning users login
- Prominent link to help with login issues

___

### Progress

- [x] New design
- [x] Ensure it's responsive on smaller screens
- [x] Public timeline page similar to public hashtag page
- [x] Support local/federated admin setting
- [x] Support hiding timeline preview admin setting
- [x] Support hiding profile directory admin setting
- [x] Support closed registrations admin setting

___

### Responsive design screenshots

Screen Shot 2019-03-12 at 01 14 58
Screen Shot 2019-03-12 at 01 15 05

___

### Other notes

- `site_description` is no longer displayed on the frontpage, specifically only `site_short_description`. This is because based on real-world examples, it would not fit into the hero widget, and would also contain a lot of information that is not urgent. Some parts of the code, especially the instance REST API, continue to use `site_description`
- The registration form is now always displayed, but disabled when registrations are disabled. This is also a little bit of preparation for approval-based registrations mode which I promised

### CODE REVIEW

**Comment by marek-lach** [comment]
Liking it so far, 2 points about grammar corrections:

> Browse a profile directory and filter by **it**, not _ir_

> Try a mobile, **or desktop** app

**Review by krainboltgreene — APPROVED** [review]

**Comment by Aditoo17** [comment]
> > Browse a profile directory and filter by **it**, not _ir_
It's actually "filter by interests", but that didn't fit on the mobile screen. See the desktop screenshot above to see it.

**Comment by SnDer** [comment]
Is the logo on the landing page new or is there just some text added in code? "Follow friends and discover new ones"

**Comment by Gargron** [comment]
Text added in code.

**Comment by Kjwon15** [comment]
`closed_registrations_message` also gone.

**Pull request merged**
