### PR TITLE
Add JS console errors check

### PR DESCRIPTION
**Pull request by mjankowski**
Pulls out just the JS errors catching portions of https://github.com/mastodon/mastodon/pull/27732

For this initial version I've had it only care about `SEVERE` level JS errors. This would have caught some of the recent JS issues we've had ... in the future if we want to tighten this up even further we could have it raise on `WARNING` as well ... but I know there actually are a bunch of those now, so we'd have to clean up as well.

Like the last PR adjusting capybara config, I've updated this to just apply to ALL system specs for now, since they all use the JS driver.

The constants are needed to align the capybara driver hostname expectations with the running rails server. A good future refactor here would be to further align this so that we don't need a setting just for the system specs, and can use the same value in the whole suite.

### CODE REVIEW

**Comment by mjankowski** [comment]
I'm not sure if this is amusing or useful, but this appears to have caught a JS error - https://github.com/mastodon/mastodon/actions/runs/7477517579/job/20350502536?pr=28682

I've seen this as intermittent failure a few times while rebasing these JS/capybara PRs.

Any guesses as to why the `api/v1/markers` might sometimes have issues loading? It seems to be intermittent on CI, and I can't replicate locally (yet).

**Comment by mjankowski** [comment]
It's returning a 422, which I think comes from any of:

- Invalid record or validation error being raised
- RecordNotUnique or DateError
- Request not being from an auth'd user

I'd bet that something is intermittently causing that final scenario, but am not sure what.

**Comment by ClearlyClaire** [comment]
Is it possible to get the backtrace of such errors?

**Comment by mjankowski** [comment]
> Is it possible to get the backtrace of such errors?

On the JS client side, it's using the webdriver/selenium manager API to loop through any logged errors. I'm not 100% on this, but I think at the time that access is happening, they are just logged messages and you can't bind to the stack or pull more info out ... but I'll look into that a bit and see if either we can get more backtrace info, or we could configure the selenium client to be more verbose in it's logging during the run so that when an error log comes out there's more detail there.

For this specific one, I still can't replicate locally. I just rebased and I'll see if CI fails again. If it does, I'll use a GH action running on my fork and try to add more verbose debugging on the ruby side to see where the 422 is coming from.

**Comment by mjankowski** [comment]
Hmm, it passed on that run ... but I don't know if I trust that. I think the changes here are ready to go, but I worry that the intermittent issue will occur often enough to be a problem. I'll look into re-recreating, and into more error detail first.

**Comment by mjankowski** [comment]
I ran this many times and cannot get that error to occur. I'd guess at this point that it's a real but intermittent failure that either reflects some load order edge case or something, or maybe is unique to how the streaming server manager and system specs in general are setup to run. Not sure.

I'd say probably safe to merge with understanding we may see those again.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
This got triggered again in https://github.com/mastodon/mastodon/actions/runs/7501669991/job/20422819352?pr=27924

**Comment by mjankowski** [comment]
Excellent.

I have run this like ~hundreds of times locally and never get the failure. I enabled GH actions on my fork and have a branch which is running JUST this system spec with some added debug info, have been pushing to it a bunch, no failures yet. I do continue to see intermittent failures on other branches on my fork.

Will keep observing I guess. Might also double check chrome versions and stuff like that to compare my local vs CI envs.

**Comment by mjankowski** [comment]
The log object we get back is an https://www.rubydoc.info/gems/selenium-webdriver/Selenium/WebDriver/LogEntry

Unfortunately it has minimal backtrace information.

I've added even more debugging info and will continue to try to get it to trigger.

**Comment by mjankowski** [comment]
Finally got an error with debugging enabled.

Based on these 4000 lines of logs - https://github.com/mjankowski/mastodon/actions/runs/7504396667/job/20431413295 - it looks like the error is coming from api/base_controller:27 (you can search for "caught an" in that log to see the approx error details ... although I screwed up here and tried to log a var that didn't exist ... but the trace is accurate).

My guess based on that is that there's something in api/markers#create which tries to run the create query twice somehow (?), or that there's something in the JS generating multiple calls to this API with the same `last_read_id` param and it's trying them both and getting error on the second. In the logs here there are two sql `CREATE` near each other with same exact params except for an updated_at that's like 1000ths of a second different.

**Comment by mjankowski** [comment]
Running this local, this system spec does result in two calls to markers#create. The relevant code there is wrapped in a transaction, and does a find_or_initialize_by to establish a marker ivar, then updates it with the last_read_id from params.

I'm guessing there's a multi-threading interaction happening here where two diff requests are handled close enough in time that one is persisted and the other fails at the db level. Notably there is NOT any AR/Rails level validation in place here, but there is a db-level unique index. This would explain the `ActiveRecord::RecordNotUnique` being caught at api base controller.

I suspect this actually is a bug and the solution is to modify how the records are created ... but I also want to be able to recreate this locally as well which I haven't been able to get the timing just right for yet. Will keep trying.

**Pull request merged**
