### PR TITLE
Email template update (rebased and delinted from existing)

### PR DESCRIPTION
**Pull request by mjankowski**
This PR starts with all the commits from @hteumeuleu in https://github.com/mastodon/mastodon/pull/28416 and then:

- Rebases against main to fix false positive haml lint
- Removes two unused local vars to pass final haml lint
- Runs prettier on css to pass sass lint
- Normalizes locale file (trailing whitespace) to pass that lint
- Moves the two new mailer partials out of `layouts/` dir
- Reduces the diff on the  mailers themselves by moving the layout conditional to top

I have a few other change ideas (the way the partials/templates interact could maybe be better ... but I want to see more emails first and then refactor after the fact instead of guessing up front) ... but did not want to stray too far from original.

I believe this will pass all the CI lints, would like to confirm. This might be merge ready (I've left authorship from the original PR on the commits - so should be easy to see original vs what I added), but pre-release we will need to:

- Get rid of the "new" naming
- Convert the rest of the emails (I suspect this will be speedy after initial are good)
- Add the couple new emails?

### CODE REVIEW

**Comment by mjankowski** [comment]
@hteumeuleu - feel free to look at the last ~5 commits from me here. Would love your take to make sure the html is still solid. Also feel free to steal any of this as you update the other PR. I don't care strongly which one gets merged -- just looking to help nudge this along (I think it looks great).

**Comment by hteumeuleu** [comment]
Thank you for this! I've integrated the changes from your branch in mine.

**Comment by mjankowski** [comment]
> Thank you for this! I've integrated the changes from your branch in mine.

Glad it was helpful! I'll keep an eye on your PR, feel free to ping me with any other rails-ish issues.

**Comment by mjankowski** [comment]
@hteumeuleu I updated this to your latest changes, and once again added a few commits on the end to correct the linting stuff if you want to grab/copy those again.

**Comment by mjankowski** [comment]
Closing since https://github.com/mastodon/mastodon/pull/28416 was merged -- will open any improvements as separate PRs.

**Pull request closed without merging**
