### PR TITLE
Fix ActivityPub handling of replies with WEB_DOMAIN (#4895)

### PR DESCRIPTION
**Pull request by ClearlyClaire**
For all intents and purposes, `local_url?` is used to check if an URL refers
to the Web UI or the various API endpoints of the local instances. Those things
reside on `WEB_DOMAIN` and not `LOCAL_DOMAIN`.

### CODE REVIEW

**Comment by ThibG** [comment]
Tests fail because the spec is about `LOCAL_DOMAIN` and not `WEB_DOMAIN`. Not sure if the spec should be changed, the function changed to test against *both* `LOCAL_DOMAIN` and `WEB_DOMAIN`, or yet something else.

As said earlier, in practice, `local_url` is exclusively used for things that should be checked against `WEB_DOMAIN`.

**Comment by ThibG** [comment]
Because all current usages of this function only make sense with WEB_DOMAIN. But I'm fine with both solutions, as I can't see any adverse effect of accepting LOCAL_DOMAIN here.

**Comment by ThibG** [comment]
Actually, I can think of a (crazy) situation where that would matter! Let's have two domains, A and B, associated with two instances, one of which has WEB_DOMAIN=A and LOCAL_DOMAIN=B while the other has WEB_DOMAIN=B and LOCAL_DOMAIN=A.

I'm not sure there are people crazy enough to do this, but I think there are some instance admins that could prove me wrong :]

**Comment by ThibG** [comment]
Decided that the correct behavior for `local_url?` would be to use web_domain exclusively, as all URLs handled by Mastodon are by definition on `WEB_DOMAIN`.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
