### PR TITLE
Add optional hCaptcha support

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Add optional hCaptcha support based on https://github.com/glitch-soc/mastodon/pull/1665 and https://github.com/glitch-soc/mastodon/pull/1667, largely rewriting prior work at https://github.com/glitch-soc/mastodon/pull/1323

Whenever the environment variables `HCAPTCHA_SECRET_KEY` and `HCAPTCHA_SITE_KEY` are set, the admin can enable hCaptcha:
image

When enabled, users are shown a captcha when confirming their email:
image

The fact that is done during confirmation and not upfront is for:
- not requiring changes to the app sign up flow
- restricting use of external hCaptcha javascript to a single page (the confirmation interstitial page)

### CODE REVIEW

**Review by renchap — APPROVED** [review]

**Comment by renchap** [comment]
To give some context to people seeing this: this is an emergency feature backport from Glitch SOC to help mitigating an ongoing spam wave, this feature may not make it in a next release, or with significative changes.

**Comment by ShadowJonathan** [comment]
Oh, so only because mastodon.social has spam wave attacks now, it is an "emergency"?

It's not like we've been asking for this for multiple years: https://github.com/mastodon/mastodon/issues/7601, and https://github.com/mastodon/mastodon/issues/877

**Comment by benaryorg** [comment]
I would also like to inquire about this "emergency".
To my knowledge there is an ongoing spam wave localized a less than a handful of instances which could at any point turn on registration approvals and moderate the registrations, a measure that many, if not most, other instances have taken.

Of course implementing captchas is a useful feature, considering that it has been asked for several times and even been implemented in glitch-soc, however by merging this change upstream with the prospect of possibly removing it again it like a slap in the face to people who maintain downstream forks since the patch has been introduced, which may cause merge conflicts, but more importantly a removal would also mean that the downstream projects would have to revert the removal if they want to keep the original code.

You are increasing the maintenance burden of people many of whom do the maintenance of said forks in their free time, with the sole reason of reducing moderation overhead on a single instance, an instance which would not even be problematic if registrations were closed since the federation allows other instances to take in the new users, many of which already have an approval process (or in the case of glitch-soc captchas even).

Furthermore as was already mentioned in #25023 the use of hCaptcha proves a *significant* invasion into privacy as it leaks PII to a third party, to my knowledge without consent of the user. The third party (which does not even list an easily accessible imprint on their website, how convenient) being resident in the United States being subject to the CLOUD act which is and always has been fundamentally incompatible with GDPR also means that this violates GDPR for all users resident in the EU facing this registration form. The lack of consent makes this especially critical. However I'll leave the details to the mentioned issue.

Considering that this is, again, a measure taken to reduce moderation overhead of a single instance I would like to inquire about the exact circumstances that constitute an emergency, and how such an emergency can be declared by other instances using the same software and receive similar treatment (fast tracked implementation of measures), if any such process is planned to be implemented at all?

**Comment by benaryorg** [comment]
This is a very solid response addressing a lot of relevant technicalities, with others being addressed in open issues, thank you very much.

The matter of consent is currently one of the most important ones I am aware of in this context, I have opened #25025 to track a potential measure while the hCaptcha mechanism is in place.

Within my bubble at least there are still open questions regarding other topics some of which unrelated to the technology aspect of Mastodon or at least this repository.
I assume that there is *some* level of awareness for these issues, several of which are hopefully apparent from my initial reply.
Any further discussion of those topics here is off-topic and probably counter-productive, so I hope that these will be addressed in other form.

**Comment by Synkstar** [comment]
Shouldn't this technically be done before the confirmation email is sent because someone could use proxies to send out a crap ton of emails?

**Comment by ClearlyClaire** [comment]
> Shouldn't this technically be done before the confirmation email is sent because someone could use proxies to send out a crap ton of emails?

This was the only way we could do it without breaking the sign-up-from-app flow. I guess this could be revisited now that we have `registrations.url` in `/api/v2/instance`

**Pull request merged**
