### PR TITLE
Add featured tags selector for WebUI

### PR DESCRIPTION
**Pull request by noellabo**
image

### CODE REVIEW

**Comment by trwnh** [comment]
this might look better in the bio?

**Comment by noellabo** [comment]
This link behaves differently from a normal hashtag link, so it's easier to understand if it's separated from the bio.

Also, this is a Fedibird to upstream port, but Fedibird has a mode to focus on posting with options to hide bio and hide fixed posts, which is clearly a timeline switching feature.

image
This screenshot is from Fedibird and is for reference only. This pull request contains only the featured tags selector.

**Comment by Gargron** [comment]
I had the idea that visually it might work better if we use a portal to render this into the navigation panel. But I'm OK with doing that on my own after merging.

**Comment by noellabo** [comment]
I'm interested in that idea. Can you merge so far and continue?

**Review by Gargron — APPROVED** [review]

**Pull request merged**
