### PR TITLE
Switch from yarn to pnpm

### PR DESCRIPTION
**Pull request by renchap**
This is al alternative to #27073

Yarn 1 is no longer maintained and suffers from many bugs (including https://github.com/eslint/eslint/discussions/17215#discussioncomment-6609097 which prevents multiple package upgrades)

pnpm is a more modern package manager, which should be much faster and generate a more correct `node_modules/`

The two main changes are:
- `pnpm` maintains a global package repository on your machine. Then it links those packages into `node_modules/`, which makes installation much more efficient and reduces the disk usage if you have many JS projects on your computer
- only direct dependencies are linked into `node_modules/`. For example, `tesseract.js-core` was not defined as a dependency but was imported from a JS file, causing an error, so I added it as an explicit dependency.

As Webpacker relies on `yarn`, I monkey-patched the parts that called `yarn` directly to replace it with `pnpm`.

Our setup should now properly support corepack, so installing the package manager is as simple as `corepack prepare --activate` (and maybe `corepack enable` before, if it has never been ran on this machine and is not down when installing node). It will automatically install the correct pnpm version.

This PR is based on #27295 as we can no longer use `capitrano-yarn`, and Capistrano is not tested so I removed it.

### CODE REVIEW

**Comment by nschonni** [comment]
Probably a good choice, but you'll have to look at the Dockerfile stuff, since the official images only ship with NPM and Yarn1. I know there are a few Docker related PRs active right now, that might move off the official NodeJS image

**Comment by renchap** [comment]
> Probably a good choice, but you'll have to look at the Dockerfile stuff, since the official images only ship with NPM and Yarn1. I know there are a few Docker related PRs active right now, that might move off the official NodeJS image

I switched the docker images to using `corepack`, which will handle installing the correct JS package manager automatically, using the `packageManager` field from `package.json`.

**Review by Gargron — DISMISSED** [review]

**Comment by vmstan** [comment]
> Probably a good choice, but you'll have to look at the Dockerfile stuff, since the official images only ship with NPM and Yarn1. I know there are a few Docker related PRs active right now, that might move off the official NodeJS image

I've been working on one of them, and have it setup to test this and worked with Renchap to get a successful build on it today.

**Comment by ClearlyClaire** [comment]
Switching from our current `yarn` version to anything else will require significant changes for admins (unless using docker), and the documentation will need to be updated.

I ran into multiple issues setting up corepack on my setups, but to be fair, I had other issues with yarn 1.

For some reason, on my ArchLinux-based development environment, the `husky` hook now somehow picks up the wrong bundle environment. I don't understand what is causing this nor how to fix it:
```
✖ bundle exec rubocop --force-exclusion -a:
bundler: command not found: rubocop
Install missing gem executables with `bundle install`
```

Manually running `bundle exec rubocop --force-exclusion -a` works without issues.

**Comment by renchap** [comment]
> For some reason, on my ArchLinux-based development environment, the `husky` hook now somehow picks up the wrong bundle environment. I don't understand what is causing this nor how to fix it:

What node version manager are you using? This is very weird, I am not sure what is happening here 🤔

**Comment by renchap** [comment]
> Also, should we change something to the Renovate config?~~

Nothing specific, we use `matchManagers: ['npm'],` which will work with every JS package manager.

The currently open PRs will probably need to be rebased, but Renovate should do it.




> the documentation will need to be updated.

I did it for documentation in this repo, but as the main documentation is not versioned, I will probably need to add specific instructions for Mastodon >= 4.3 everywhere `yarn` is mentioned :(

Do you want me to open the PR for this now, or should we do it closer to the 4.3 release?

**Comment by renchap** [comment]
Rebased with latest `main`, if you want to merge it :)

**Comment by vmstan** [comment]
> Rebased with latest `main`, if you want to merge it :)

Compiled and running it in prod, no errors.

**Comment by renchap** [comment]
Closing as https://github.com/mastodon/mastodon/pull/27073 has been merged.

**Pull request closed without merging**
