### PR TITLE
Fix haml-lint Rubocop `Rails/*` cops

### PR DESCRIPTION
**Pull request by mjankowski**
Lumps a few separate rule fixes all under the `Rails/` namespace into one PR.

### CODE REVIEW

**Comment by nschonni** [comment]
FYI, I think before the last version update, I had used `bundle exec haml-lint --auto-gen-config --auto-gen-exclude-limit 100` to have the actual file names in the ignore. Unforntuntly haml-lint doesn't include the options in the TODO file like Rubocop. I think the built in limit might be 20 or something

**Comment by mjankowski** [comment]
Yeah - it defaults to 15 violations as a limit, and for anything higher than that excludes that from being individually listed.

Based on earlier versions of the file, I do think it must have been generated with 100 at some point.

Not a huge deal - easy enough to comment out the disable line to see what the violations are.

**Comment by nschonni** [comment]
Yeah, just a note that the 50, isn't 50 files, it's just any issue count. This is what the config looks like with the artificial 100 limit
```yaml
# This configuration was generated by
# `haml-lint --auto-gen-config`
# on 2023-07-17 16:28:33 -0400 using Haml-Lint version 0.48.0.
# The point is for the user to remove these configuration records
# one by one as the lints are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of Haml-Lint, may require this file to be generated again.

linters:

  # Offense count: 959
  LineLength:
    enabled: false

  # Offense count: 22
  UnnecessaryStringOutput:
    exclude:
      - 'app/views/accounts/show.html.haml'
      - 'app/views/admin/custom_emojis/_custom_emoji.html.haml'
      - 'app/views/admin/relays/_relay.html.haml'
      - 'app/views/admin/rules/_rule.html.haml'
      - 'app/views/admin/statuses/index.html.haml'
      - 'app/views/auth/registrations/_sessions.html.haml'
      - 'app/views/disputes/strikes/show.html.haml'
      - 'app/views/notification_mailer/_status.html.haml'
      - 'app/views/settings/two_factor_authentication_methods/index.html.haml'
      - 'app/views/statuses/_detailed_status.html.haml'
      - 'app/views/statuses/_poll.html.haml'
      - 'app/views/statuses/_simple_status.html.haml'
      - 'app/views/user_mailer/suspicious_sign_in.html.haml'
      - 'app/views/user_mailer/webauthn_credential_added.html.haml'
      - 'app/views/user_mailer/webauthn_credential_deleted.html.haml'
      - 'app/views/user_mailer/welcome.html.haml'

  # Offense count: 67
  RuboCop:
    exclude:
      - 'app/views/admin/accounts/_account.html.haml'
      - 'app/views/admin/accounts/index.html.haml'
      - 'app/views/admin/accounts/show.html.haml'
      - 'app/views/admin/announcements/edit.html.haml'
      - 'app/views/admin/announcements/new.html.haml'
      - 'app/views/admin/custom_emojis/index.html.haml'
      - 'app/views/admin/dashboard/index.html.haml'
      - 'app/views/admin/domain_blocks/confirm_suspension.html.haml'
      - 'app/views/admin/follow_recommendations/show.html.haml'
      - 'app/views/admin/invites/_invite.html.haml'
      - 'app/views/admin/invites/index.html.haml'
      - 'app/views/admin/ip_blocks/index.html.haml'
      - 'app/views/admin/reports/_status.html.haml'
      - 'app/views/admin/reports/actions/preview.html.haml'
      - 'app/views/admin/reports/index.html.haml'
      - 'app/views/admin/reports/show.html.haml'
      - 'app/views/admin/roles/_form.html.haml'
      - 'app/views/admin/status_edits/_status_edit.html.haml'
      - 'app/views/admin/statuses/index.html.haml'
      - 'app/views/admin/statuses/show.html.haml'
      - 'app/views/admin/tags/show.html.haml'
      - 'app/views/auth/registrations/_sessions.html.haml'
      - 'app/views/auth/registrations/new.html.haml'
      - 'app/views/auth/sessions/two_factor.html.haml'
      - 'app/views/auth/shared/_progress.html.haml'
      - 'app/views/disputes/strikes/show.html.haml'
      - 'app/views/filters/statuses/index.html.haml'
      - 'app/views/invites/_invite.html.haml'
      - 'app/views/layouts/application.html.haml'
      - 'app/views/layouts/error.html.haml'
      - 'app/views/notification_mailer/_status.html.haml'
      - 'app/views/settings/applications/_fields.html.haml'
      - 'app/views/settings/preferences/appearance/show.html.haml'
      - 'app/views/statuses/_detailed_status.html.haml'
      - 'app/views/statuses/_og_image.html.haml'
      - 'app/views/statuses/_poll.html.haml'
      - 'app/views/statuses/_simple_status.html.haml'
      - 'app/views/statuses/_status.html.haml'
      - 'app/views/statuses_cleanup/show.html.haml'
      - 'app/views/user_mailer/warning.html.haml'

  # Offense count: 3
  ViewLength:
    exclude:
      - 'app/views/admin/accounts/show.html.haml'
      - 'app/views/admin/reports/show.html.haml'
      - 'app/views/disputes/strikes/show.html.haml'

  # Offense count: 41
  InstanceVariables:
    exclude:
      - 'app/views/admin/reports/_actions.html.haml'
      - 'app/views/admin/roles/_form.html.haml'
      - 'app/views/admin/webhooks/_form.html.haml'
      - 'app/views/auth/registrations/_sessions.html.haml'
      - 'app/views/auth/registrations/_status.html.haml'
      - 'app/views/auth/sessions/two_factor/_otp_authentication_form.html.haml'
      - 'app/views/authorize_interactions/_post_follow_actions.html.haml'
      - 'app/views/invites/_form.html.haml'
      - 'app/views/relationships/_account.html.haml'
      - 'app/views/shared/_og.html.haml'
      - 'app/views/statuses/_status.html.haml'

  # Offense count: 6
  ConsecutiveSilentScripts:
    exclude:
      - 'app/views/admin/settings/shared/_links.html.haml'
      - 'app/views/settings/login_activities/_login_activity.html.haml'
      - 'app/views/statuses/_poll.html.haml'

  # Offense count: 3
  IdNames:
    exclude:
      - 'app/views/authorize_interactions/error.html.haml'
      - 'app/views/oauth/authorizations/error.html.haml'
      - 'app/views/shared/_error_messages.html.haml'
```
I do change the double quotes back to single quotes after generating, but that would also happen through the commit hook anyway

**Comment by nschonni** [comment]
Since the other Rubocop haml PRs landed, it might be a good time to run the `bundle exec haml-lint --auto-gen-config --auto-gen-exclude-limit 100`

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
