### PR TITLE
New audio player

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
Follow up for #11358

### CODE REVIEW

**Comment by koyuawsmbrtn** [comment]
https://webhost.koyu.space/uploads/f.php?h=1lhMUSrH

@ThibG here's the patch file for the last codeclimate issues left

**Comment by ThibG** [comment]
@koyuawsmbrtn yup, should be ok to push to this PR

**Comment by koyuawsmbrtn** [comment]
> @koyuawsmbrtn yup, should be ok to push to this PR

What do you mean? I don't have any permission to change anything on your branch which is why this PR can't get updated by mself.

**Comment by koyuawsmbrtn** [comment]
Can be closed, see https://mastodon.social/@Gargron/102664024082128039

**Pull request closed without merging**
