### PR TITLE
Revert to using Paperclip's filesystem storage, and fix dangling records in remove_remote

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by ThibG** [comment]
Actually, that may be too much of performance hit, ̀#exists?` checks for the actual existence of the file afaict.

**Comment by ThibG** [comment]
Ok, for some reason, there are some media for which `#exists?` is false while `#present?` is true.
This shouldn't happen, I don't know why it did, but I updated the worker to destroy the attachment (and thus the record claiming the file exists) regardless of whether the actual file exists.

**Review by ykzts — APPROVED** [review]

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
How is CircleCI still not finished...

**Comment by ThibG** [comment]
@Gargron I re-pushed because it just refused to run last time I pushed.
It's maybe due to the fact that you are out-running your plan by about 500% :x

**Review by Gargron — APPROVED** [review]

**Comment by gllmhyt** [comment]
Can you please release with this fix as soon as possible? My server media storage is getting out of hand and will soon have its drive fully loaded and be unusable: unable to run, unable to boot, requiring manual deletion of files where it should have been automatically deleted.

**Pull request merged**
