### PR TITLE
Use Rails built-in `health` controller

### PR DESCRIPTION
**Pull request by mjankowski**
Rails 7.1 adds a framework-supplied health controller which is doing basically what the custom one was. Route stays the same so anything relying on this for uptime/status checks will not need to change.

### CODE REVIEW

**Review by ykzts — DISMISSED** [review]

**Comment by ClearlyClaire** [comment]
The returned value is different (simple HTML with some inline CSS that gets stopped by our CSP, instead of a simple “OK”), I expect this could break some tools expecting “OK” instead of checking the HTTP status code. Can we change that?

**Comment by mjankowski** [comment]
> The returned value is different (simple HTML with some inline CSS that gets stopped by our CSP, instead of a simple “OK”), I expect this could break some tools expecting “OK” instead of checking the HTTP status code.

Fair point. The route (`/health`) and response codes (200 or 500) stay the same as prior, but to try to be exhaustive about the things which do change:

- The success response is now text/html instead of text/plain
- The success html response is just a body element with a green background, and no text content
- The failure response if an error occurs is also text/html (and also has styled body element), instead of whatever the app default error view is
- The previous "OK" text from the text/plain response is gone

> Can we change that?

There's not much in the way of configuration, the feature is really meant for the most basic cases. We could either monkey patch the framework class, or subclass the controller and override the `up` state method ... but those both seem sort of awkward. The main benefit here is the code deletion if the check is the same as the built-in.

I'd say that if it's very critical to keep the "OK" response because it may be relied on, we should probably not bother with this. I'm not sure what the official expected API is here. The docs describe the streaming server health check (and in that case the docs do mention the OK response), but don't mention this general app health check at all.

**Comment by ClearlyClaire** [comment]
> I'd say that if it's very critical to keep the "OK" response because it may be relied on, we should probably not bother with this. I'm not sure what the official expected API is here. The docs describe the streaming server health check (and in that case the docs do mention the OK response), but don't mention this general app health check at all.

Yeah, it should at least not affect the bundled `docker-compose` health check, but I do not know how this endpoint is used in the wild.

**Comment by mjankowski** [comment]
> Yeah, it should at least not affect the bundled `docker-compose` health check, but I do not know how this endpoint is used in the wild.

Yeah, I could see either of...

- We have created an implicit promise to include "OK" in the response even though it's not documented anywhere and should retroactively consider this to be the public API and not break it; or
- There never was a public API so we're not breaking anything. The response code is almost definitely the thing you *should* be relying on, so we're fine to change the response body as long as we maintain the response codes. We can also document this in the API docs and *establish this* as the public API going forward. There will likely be little breakage, and if there is it should be a straightforward update for anyone relying on the response body to switch to status instead.

...as sort of valid. Let me know.

**Comment by Gargron** [comment]
I do not see a major benefit to outsourcing this endpoint to Rails when we already have it custom built.

**Comment by mjankowski** [comment]
My take would be that having to maintain a custom version of a thing (trivial in this case of course) is a negative when the framework provides it for free; and getting to delete some code (liability) while preserving the feature (asset) is a small net win.

That said, this a small tweak that I don't feel strongly about. Happy to close if we need to preserve that "OK" and/or have more customization on a roadmap.

**Pull request closed without merging**
