### PR TITLE
Remove deprecated `Import` model

### PR DESCRIPTION
**Pull request by mjankowski**
Attempting to remove the deprecated code from https://github.com/mastodon/mastodon/pull/21054

### CODE REVIEW

**Comment by renchap** [comment]
This needs to be merged before we release our next major update, as it will prevent to update from a pre-4.2 version to the version containing this.

**Comment by ClearlyClaire** [comment]
> This needs to be merged before we release our next major update, as it will prevent to update from a pre-4.2 version to the version containing this.

You meant “**after** we release our next major update”?

**Comment by renchap** [comment]
No, before we release it? So people can upgrade to the latest 4.x release (and we know they will have done the migration) then upgrade to 5.0 (which will require you to be up-to-date on the latest 4.x before upgrading to the next major)

**Comment by ClearlyClaire** [comment]
Ok, I think we do agree, I just was confused by your initial post as it seemed to imply the earlier it was merged, the better.

The cost of merging it early is breaking in-progress imports for instances updating from pre-4.2.0 to a release containing this change.

The cost of merging it late is carrying “dead” code for longer.

I agree that 5.0 sounds like a good breakpoint to get rid of this.

**Comment by mjankowski** [comment]
I guess ... I'd probably just wait however long we need to wait to be confident all migrations/queues are handled and then remove it.

Separately, maybe I'll pull out the few changes here which are not just about the deprecation removal, but are more like handling other usage of the class, into separate PRs which I think could harmlessly merge sooner.

**Comment by mjankowski** [comment]
Rebased after the view change to use form::import, so this is just the deprecated stuff removal now.

I want to review the paperclip options thing a bit more before removing that fully.

**Comment by mjankowski** [comment]
There was some initial back and forth on version target here, but curious if (post extraction of other stuff) we're still looking at 4.4 (ie, current main) as appropriate for removal here?

**Comment by ClearlyClaire** [comment]
We were targeting 5.x. But we don't have a firm policy on version numbers, so we can't really say when that would be.

**Comment by mjankowski** [comment]
> We were targeting 5.x. But we don't have a firm policy on version numbers, so we can't really say when that would be.

Is there a milestone or appropriate tag to track that ... or just leave this as draft until post-4.4?

**Comment by ClearlyClaire** [comment]
Any reason this has been closed?

Thinking a little more about it, I'm not confident in merging it now. One reason for that is that we still support 4.1, and while we don't exactly support zero-downtime migration from pre-4.2 to 4.3, this is worse than that (for the same reasons as https://github.com/mastodon/mastodon/pull/33353#issuecomment-2553023579).

That being said, 4.1 is approaching EOL. So i think the next major or minor after 4.4 makes sense, though we do not have any timeline for this.

**Comment by mjankowski** [comment]
Will re-create after 4.4 or when 4.1 is EOL, whichever happens first.

**Comment by ClearlyClaire** [comment]
I think it would be ok to merge not long after 4.1 goes EOL.

**Pull request closed without merging**
