### PR TITLE
Change web UI to not use /web prefix anymore

### PR DESCRIPTION
**Pull request by Gargron**
:warning: **Work in progress**

The Mastodon UI has been split into a React-based web UI under the `/web` prefix and a static UI for permalinks until now. The static UI and the web UI had different designs and different interaction patterns (e.g., status bodies not clickable with the static UI) which confused people. It was also the source of code duplication (having to render the same data using haml templates and React components). With this PR, the React-based UI should be displayed for all resources (except the settings and admin UIs, which are still separate), for logged-in as well as logged-out users.

With the following considerations:

- The web UI must set document title and meta tags for each route appropriately
- The web UI must not attempt any API requests that require authentication when the user is not logged in
- The web UI must display onboarding elements that used to be on the static pages - such as login links and server description
- Authorization requirements for some API actions must be reconsidered - should search be allowed for logged-out users?

It would also be great if the initial state could be extracted into an API endpoint (`/api/web`) instead of rendering it into the HTML of the page as it may simplify caching logic.
___
Funded through the BMBF (BMBF Förderkennzeichen: 01IS21S29)

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
With regards to API authentication, one current effect of `AUTHORIZED_FETCH` mode is to require authentication for all API calls.
This means that switching to the Web UI for everything would either require log-in to access public toots on those instances, or that restriction will have to be reconsidered.

**Comment by mashirozx** [comment]
Will we consider the SEO issue in the new React UI, for example, do some server side rendering (SSR) jobs?

**Comment by shleeable** [comment]
Is it possible to support multiple web FEs? If you ever wanted to have a beta branch of the UX to test features in an A/B kind of way? I'd love to allow mastodon users to opt into a secondary UX branch

**Comment by digitalcircuit** [comment]
> Will we consider the SEO issue in the new React UI, for example, do some server side rendering (SSR) jobs?

I'd like to expand upon this:

While the UI doesn't need to look perfect without JavaScript, I do greatly appreciate how Mastodon currently makes it possible to read public toots from various instances comfortably with NoScript, or on slow/flaky connections and/or older mobile devices where more client-side JS heavy sites take a long time to initialize.  I'd imagine there's a good chance anyone not yet on the fediverse who is linked to a toot won't have any resources cached.

Merely an optional request; I'd understand if this is out of scope!  And I do appreciate the usefulness of unifying the code base.

**Pull request closed without merging**
