### PR TITLE
[i18n] Occitan update

### PR DESCRIPTION
**Pull request by ykzts**
retry #7293

cc @Quenty31

### CODE REVIEW

**Comment by ykzts** [comment]
```console
#!/bin/bash -eo pipefail
bundle exec i18n-tasks unused
Unused keys (12) | i18n-tasks v0.9.21
+--------+--------------------------------------------+-----------------------------------+
| Locale | Key                                        | Value                             |
+--------+--------------------------------------------+-----------------------------------+
|   oc   | admin.reports.account.created_reports      | Rapòrts creats per aqueste compte |
|   oc   | admin.reports.account.moderation.silenced  | Mes en silenci                    |
|   oc   | admin.reports.account.moderation.suspended | Suspendut                         |
|   oc   | admin.reports.account.moderation.title     | Moderacion                        |
|   oc   | admin.reports.account.moderation_notes     | Nòtas de moderacion               |
|   oc   | admin.reports.account.targeted_reports     | Rapòrts ligats a aqueste compte   |
|   oc   | admin.reports.avatar                       | Avatar                            |
|   oc   | admin.reports.history                      | Istoric de moderacion             |
|   oc   | admin.reports.notes.label                  | Nòtas del moderator               |
|   oc   | admin.reports.notes.new_label              | Ajustar una nòta del moderator    |
|   oc   | terms.contrast                             | Fòrt contrast                     |
|   oc   | terms.default                              | Mastodon                          |
+--------+--------------------------------------------+-----------------------------------+
Exited with code 1
```

🤔

**Comment by Quenty31** [comment]
It means I translated things that are no longer used o_Ô ?

**Comment by ykzts** [comment]
@Quenty31 https://github.com/tootsuite/mastodon/pull/7188/files#diff-37c9b835927e3c363588f172de9bb6fa 😌

**Comment by Quenty31** [comment]
Oh :( been doing useless things...What should we do now? Remove it all?

**Review by Gargron — APPROVED** [review]

**Pull request merged**
