### PR TITLE
Cleanup CSS

### PR DESCRIPTION
**Pull request by ghost**
Fixes some issues with spacing between columns and column height on large screens.

### CODE REVIEW

**Comment by j0k3r** [comment]
Screenshots before / after? :slightly_smiling_face:

**Comment by Gargron** [comment]
I'm not really sure what this is fixing, but it's removing a special style for large screens that was submitted by another user and I'm not sure that's good.

**Comment by ashfurrow** [comment]
Thanks for the PR @rainyday – it doesn't look like something that fit within the vision @Gargron has for Mastodon, and there are quite a few merge conflicts. I'm going to recommend we close this, but it's totally up for discussion.

**Comment by ashfurrow** [comment]
Hi again – looks like there hasn't been any updates on this, so I'm going to close. Please let us know if you have any questions, and thanks again for the pull request!

**Pull request closed without merging**
