### PR TITLE
Allow user handles to wrap in the popover when they are very long

### PR DESCRIPTION
**Pull request by nclm**

### CODE REVIEW

**Comment by nclm** [comment]
Tested after seeing this: https://mastodon.social/@gabboman@app.wafrn.net/113430646739253619

**Review by ClearlyClaire — APPROVED** [review]
I wonder whether we want that to wrap, or be ellipsized.
I think in this case, wrapping works, but in more extreme cases, it could be an issue.

I guess we could do something like:
```css
overflow-wrap: anywhere;
text-overflow: ellipsis;
overflow: hidden;
display: -webkit-box;
line-clamp: 3;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
```

**Comment by ClearlyClaire** [comment]
Also, I think there is another place where an overflow is occurring: if the contents of `.account__header__tabs__name h1 small span` are especially long, it will cause the whole username to overflow and the domain pill to not be shown.

I suppose a fix for that would be adding the following to the existing rules for `.account__header__tabs__name h1 small span`:
```css
text-overflow: ellipsis;
overflow: hidden;
```

**Comment by Gargron** [comment]
Claire is right, in my view this should be `text-overflow: ellipsis` with no wrapping.

**Comment by vmstan** [comment]
@nclm can you fix?

**Comment by mjankowski** [comment]
> @nclm can you fix?

In addition to incorporating (or disagreeing with) the previous feedback - could you add a before/after screenshot to PR description so we're all on same page re: changes here?

**Comment by mjankowski** [comment]
Superceded by https://github.com/mastodon/mastodon/pull/33286

**Pull request closed without merging**
