### PR TITLE
Update fr.jsx

### PR DESCRIPTION
**Pull request by StefOfficiel**
"Pouet" isn't serious. It would be best to keep the generic term "Toot".
"Emoji" is a proper nouns. Proper nouns start with a capital letter.

### CODE REVIEW

**Comment by yannicka** [comment]
Why we should be serious? "Pouet" is a funny name.

**Comment by StefOfficiel** [comment]
Yes, it's funny, but it's way too childish. Mastodon has a clean and professional appearance, so do not go too much in the funny style and so stay "professional".

**Comment by StefOfficiel** [comment]
In addition, Anglicisms are fun in France! ;-)
Imagine, tomorrow, on TV, "Leonardo Dicaprio made a "Pouet" on Mastodon!" compare to "Leonardo Dicaprio made a "Toot" on Mastodon!" xD

**Comment by StefOfficiel** [comment]
Or, we must invent another term specific to France, for example "Twoot". It's a simple idea!

Fortunately that Twitter has to keep the term "Tweet" and not "Piailler"! Huhu!

**Comment by yannicka** [comment]
Why should Mastodon be professional? It's a social network, it's made for people to speak and share, not for companies to make advertisements. And what is the problem if a celebrity post a "pouet"? Everything does not have to be politically correct.

**Comment by trebmuh** [comment]
> In addition, Anglicisms are fun in France!

bullshit argument

**Comment by StefOfficiel** [comment]
> not for companies to make advertisements

I did not say that !

> bullshit argument

Okay!

**Comment by mkody** [comment]
There's a discussion about that in #1099.

**Comment by StefOfficiel** [comment]
It is especially when one says "Toot" and "Tooter" works without problems, but "Pouet" and "Poueter" = "Péter" (fart) = not great, not funny!

**Comment by tcitworld** [comment]
Please don't merge this until #1099 is resolved.

**Comment by Gargron** [comment]
I am strongly against removing "pouet"

**Comment by SansPseudoFix** [comment]
And, actually, if you hover reactions below your post, you can see "emoji" not "Emoji".

**Comment by Gargron** [comment]
Is this PR dead/redundant?

**Comment by yookoala** [comment]
@Gargron Just checked the latest [fr.jsx](https://github.com/tootsuite/mastodon/blob/fdcb55a0a645e8b89d6b094c38a1571291174500/app/assets/javascripts/components/locales/fr.jsx):

* `compose_form.publish` (current English string: "Toot") has translated [here](https://github.com/tootsuite/mastodon/blob/fdcb55a0a645e8b89d6b094c38a1571291174500/app/assets/javascripts/components/locales/fr.jsx#L36) the same way as this PR.
* `emoji_button.label` (current English string: "Insert emoji") [remains unchanged](https://github.com/tootsuite/mastodon/blob/fdcb55a0a645e8b89d6b094c38a1571291174500/app/assets/javascripts/components/locales/fr.jsx#L41).

So the question would be "should we capitalize '`Emoji`'" in fr.jsx. If not, this PR is not needed anymore.

**Comment by tcitworld** [comment]
Please close.

**Comment by wxcafe** [comment]
I'm closing this, if people from #1099 want to make a PR given the result of the vote they should make a new, clean one.

**Pull request closed without merging**
