### PR TITLE
Helm document the major refactor

### PR DESCRIPTION
**Pull request by deepy**
Should be merged after #20733

- Adds the ingress queue to the default sidekiq deployment
- Adds queue weights to default sidekiq deployment matching `config/sidekiq.yml`
- Updates the chart version to 4.0.0
- Updates the README to document the changes in #20733
- Fixes S3 existing secret in CronJob (related to #21726)
- Fixes S3 existing secret error in deployment

### CODE REVIEW

**Comment by SISheogorath** [comment]
Uhm, we might just merge this one instead of #20733 since this contains all the chanches and is basically rebased to upstream.

**Comment by deepy** [comment]
We could, but this one lacks the discussions from #20733 it's always nice to have those

**Review by Gargron — APPROVED** [review]

**Comment by deepy** [comment]
rebased it on main, thanks ❤️

**Comment by SISheogorath** [comment]
Regarding: 759566a9c916fbd6607f99ec25fb3b1624815780

I'm not sure it's a good idea, to put this magic in there. People will set replicas higher and wonder why the helm chart simply ignored it. I would rather like to see a [fail](https://helm.sh/docs/chart_template_guide/function_list/#fail), which explains the reasoning, rather than magic overwrites of replicas.

**Comment by Gargron** [comment]
Moving the Helm chart out to mastodon/chart

**Pull request closed without merging**
