### PR TITLE
Test blank account field verifiability

### PR DESCRIPTION
**Pull request by emilyst**
This change tests the need for #20428, which ensures that we guard against a situation in which `at_xpath` returns `nil`.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by emilyst** [comment]
I put up this draft pull request because it felt easier than setting up to run tests locally.

I thought that the blank string would be the cause of the error I saw on my instance running 4.0.0rc3 (see #20428), but it appears to work fine. I might add one or two more commits with additional tests before finalizing.

This blank string test should probably go in regardless, so I'll keep it here.

For reference, the error I encountered in production manifested for a job posted to the ingress queue and processed by `ActivityPub::ProcessingWorker`. Screenshot from Sidekiq's dead jobs:

Capture 2022-11-11 at 15 27 49

More detailed error information:

#### Error Class

`NoMethodError`

#### Error Message

`undefined method `children' for nil:NilClass`

#### Error Backtrace

```
/opt/mastodon/app/models/account/field.rb:79:in `extract_url_from_html'
/opt/mastodon/app/models/account/field.rb:32:in `value_for_verification'
/opt/mastodon/app/models/account/field.rb:38:in `verifiable?' 
```

I've omitted the job parameters here in case there's a privacy issue around that, but I'm trying to isolate the specific issue.

**Comment by emilyst** [comment]
Meh, I'll test more tomorrow.

**Comment by nyura123** [comment]
Looks like this is the same issue as #20450

**Comment by ClearlyClaire** [comment]
Blank profiles are indeed one of the things that can cause this issue, but for remote profiles rather than local ones!

**Comment by emilyst** [comment]
> Blank profiles are indeed one of the things that can cause this issue fixed by #20428.

I was silly and careless, and I forgot that the rest the test I put in passes is because I rebased my `main` on top of yours after merging #20428.

**Comment by ClearlyClaire** [comment]
Anyway, what I meant is that the test you added is good and useful, but what was actually causing an issue was in the `'for remote accounts'` context, not the `'for local accounts'` one! So I'd duplicate your test in the remote accounts context too.

**Comment by emilyst** [comment]
> Anyway, what I meant is that the test you added is good and useful, but what was actually causing an issue was in the `'for remote accounts'` context, not the `'for local accounts'` one! So I'd duplicate your test in the remote accounts context too.

Ah yeah. I can do that tomorrow. Sorry, it's rather late where I am.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by emilyst** [comment]
Thanks for the approval! Hope this helps!

**Pull request merged**
