### PR TITLE
Use NodeJS v20 by default

### PR DESCRIPTION
**Pull request by renchap**
The latest Webpack 4 version properly supports Node 18+.

Node 16 is out of support next week, so let's upgrade to Node 20, which will be the LTS version starting in October.

The `compression-webpack-plugin` version 6 (the last major version compatible with Webpack 4) still uses the `crypto` module to compute MD4 hashes, so I forked it to use the new MD4 hash function from Webpack instead. My fork can be replaced if a new v6 version is published upstream (related issue: https://github.com/webpack-contrib/compression-webpack-plugin/issues/364).

### CODE REVIEW

**Comment by renchap** [comment]
This fails because of https://github.com/webpack-contrib/compression-webpack-plugin/issues/364

**Comment by vmstan** [comment]
Built successfully for me, deployed to vmst.io now.

**Review by ClearlyClaire — APPROVED** [review]
LGTM! Would be good if the fix was in upstream `compression-webpack-plugin`, but using a specific version of a fork looks fine to me in the meantime.

**Comment by renchap** [comment]
I updated the PR to use Node 20 as discussed.

Also updated https://github.com/webpack-contrib/compression-webpack-plugin/issues/364 with my patch, and pushed it on Github ([diff from v6.1.1](https://github.com/webpack-contrib/compression-webpack-plugin/compare/v6.1.1...renchap:compression-webpack-plugin:v6-stable?expand=1)

**Comment by renchap** [comment]
Upstream [said that they will release a new v6 version](https://github.com/webpack-contrib/compression-webpack-plugin/issues/364#issuecomment-1710960788) with those changes. No ETA yet, so maybe we want to merge this now and then switch back to their version, if we want to test it before releasing the RC.

**Comment by ClearlyClaire** [comment]
> Upstream [said that they will release a new v6 version](https://github.com/webpack-contrib/compression-webpack-plugin/issues/364#issuecomment-1710960788) with those changes. No ETA yet, so maybe we want to merge this now and then switch back to their version, if we want to test it before releasing the RC.

Sounds like a sensible plan to me!

**Comment by janbrasna** [comment]
Now with compression-webpack-plugin releasing v6.1.2 to fix this (https://github.com/webpack-contrib/compression-webpack-plugin/issues/364#issuecomment-1869678263) this could be linked back…

**Pull request merged**
