### PR TITLE
Add mastobot.club

### PR DESCRIPTION
**Pull request by yiskah**
Added mastobot.club to instance list

### CODE REVIEW

**Comment by mitchellurgero** [comment]
That is not an instance?

**Comment by Gargron** [comment]
Indeed, this is not an instance. Feel free to put it under apps, however (maybe separate section for app-websites)

**Comment by yiskah** [comment]
Hmmm, interesting conundrum.

It is a server domain, right? Bots run off of it? And it's an application. But it's not an interface really... it's very gray. regardless it seems like it doesn't go here.

**Comment by Gargron** [comment]
I believe that bots sign in into other accounts from this one using OAuth

**Pull request closed without merging**
