### PR TITLE
Add class to mentions to differentiate from other toots

### LINKED ISSUE #8424: Add a class to mentions to differentiate them from all other toots
tl;dr: Add a class to mentions, like DMs have (`status-direct`) for targeting with custom CSS.

****

One of the customisations I'm doing in Mastodon when running in [Fluid](https://fluidapp.com/) is changing the colour of DMs and mentions. DMs have `status-direct`, boosts have `notification-favourite` and so on. Without a specific class on mentions (they have a generic `status-public`), it's impossible to highlight mentions in the feed and the notifications column (I can target the notifications column, but only using `nth-child` which doesn't work if the columns are rearranged).

This also becomes more valuable with #8399 as instance admins will be able to add custom CSS.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Colin-Marvin**
Fix #8424 
Appreciate any constructive criticism, this is for a university project, and is also my first time attempting to contribute to open source as a whole.

### CODE REVIEW

**Comment by shleeable** [comment]
Thank you for your PR.

**Comment by renchap** [comment]
Your change does not only add a class for mentions, but it also changes how they are styled. Is this expected?

**Comment by Colin-Marvin** [comment]
No, it's merely a placeholder with the goal to get feedback on how to actually connect it to custom CSS. I was attempting to do something along the lines of #8399, but it seems the admin side of this is different than user.

**Comment by ClearlyClaire** [comment]
Hi! Thank you for your contribution.

Unfortunately, I don't understand the use case of the linked issue: I don't understand if they want the mention themselves to have a specific class, or the post container itself. I also don't understand if they want this for every mention or for mentions to the author. I *think*, with the context that they have given, that what they want is not mention links to have a specific class, but post containers for mention *notifications* to have such a class.

We could ask for clarification, but given how old the issue is, I'm not sure we will have a reply.

> No, it's merely a placeholder with the goal to get feedback on how to actually connect it to custom CSS. I was attempting to do something along the lines of #8399, but it seems the admin side of this is different than user.

Mastodon has currently no facility for user-set CSS (beyond admins being able to set custom CSS for the whole site), and I'm not sure trying to do this is a good idea, I think that use case is best served by browser extensions dedicated to this. Furthermore, I think the original issue is not about that, but just about having some CSS class to select on. Therefore I would leave out any actual CSS change from this PR!

**Comment by mjankowski** [comment]
Closing since the original linked issue has been closed (they no longer need this feature) and the feedback here was to not bother with the css styling.

All that said - thanks for the contribution, please find more!

**Pull request closed without merging**
