### PR TITLE
Add option to block follows from domain

### PR DESCRIPTION
**Pull request by andrew-d**
This feature, if enabled, will block all follows from the given domain unless the recipient of the follow already follows the sender back.

🗒️ This is my first contribution to Mastodon; thanks for a really neat project! Feedback on style/code layout/etc. is appreciated 😃

### CODE REVIEW

**Comment by trwnh** [comment]
~~This seems very similar to the existing "domain block" feature. Perhaps it could be a modification to that instead?~~

~~Currently, the "block an entire domain" removes all followers from that domain, no exceptions.~~ EDIT: nvm, I thought this was about user-level domain blocks

Given that this appears to be targeting the admin side of domain blocks, I have two comments:

1) This should probably also extend to the REST API -- I only see the regular `admin` controllers being edited and not the `api/v1/admin` controllers.
2) There is some overlap between "rejecting follows" and the existing `severity=suspend` option. With this addition, I suspect this might grow to be a source of complications unless the old `severity` option is progressively deprecated.

Otherwise, it seems okay conceptually, but I'm not qualified to judge the technical quality of the code as written.

**Comment by andrew-d** [comment]
> Given that this appears to be targeting the admin side of domain blocks, I have two comments:
> 
> 1. This should probably also extend to the REST API -- I only see the regular `admin` controllers being edited and not the `api/v1/admin` controllers.

Good catch–I had missed that. Added and confirmed that the tests for that controller pass–thanks!

> 2. There is some overlap between "rejecting follows" and the existing `severity=suspend` option. With this addition, I suspect this might grow to be a source of complications unless the old `severity` option is progressively deprecated.

Yeah, even though there's a difference ("suspend" blocks all follows, this feature blocks a follow unless the recipient already follows the sender back), I can totally see some people being confused. As this is my first contribution, I'm hesitant to propose any particular solution here, but I'm happy to adjust if others have feedback.

**Comment by andrew-d** [comment]
> From a UX perspective, this is basically identical to the "silence" feature that already exists. I don't think the minor differences (allowing replies, but blocking follows entirely instead of turning them into follow requests) is worth the complexity of adding yet another too-similar option

My motivation for adding this is to add the option to do something less strict than the fairly heavyweight "Suspend" option.

Currently Limiting (silencing) a domain restricts all interaction to only followers, but accounts on that server can still follow users on the local server. If a server admin wants to protect from a problematic server, restricting follows still allows local users to see posts from the limited server if they follow a user there, which (in my opinion) can be more user-friendly in some cases than just Suspending the server and preventing any interaction whatsoever.

**Review by ineffyble — CHANGES_REQUESTED** [review]
Can you fix the failing i18n checks?

**Comment by ineffyble** [comment]
@andrew-d You may have hit the fun niche issue I hit a week ago.

can you check the version of libyaml you have installed?

```
$ irb
> require "yaml"
> Psych.libyaml_version
```

**Comment by andrew-d** [comment]
> Psych.libyaml_version

```
$ irb
Resolving dependencies...
3.0.4 :001 > require 'yaml'
 => true
3.0.4 :002 > Psych.libyaml_version
 => [0, 1, 7]
3.0.4 :003 >
```

**Comment by Gargron** [comment]
> Currently Limiting (silencing) a domain restricts all interaction to only followers, but accounts on that server can still follow users on the local server.

Not quite, follows from the limited server go into follow requests.

**Pull request closed without merging**
