### PR TITLE
Remove clipping text overflow for a11y improvement

### LINKED ISSUE #20870: Add hover text for trending tags
### Pitch

The "X people in the past days" should have a title, so that when you hover over it, it displays the full text.

### Motivation

Right now, the text may be cut off if you're using a language that is more... "exhaustive" or smth. In such cases (like with german) will this cause the issue that you can't read the full text as it will be displayed with three dots at the end, cutting of the remaining parts.

Since the text doesn't have any hover is this causing issues as you can't tell what the full text may be.
Sure, it's always the same text, but in the end is it still not good to cut it off without having a way to see the full that that isn't "Right click -> 'inspect element'".

Image showing the issue:
grafik

### PR DESCRIPTION
**Pull request by palewire**
Fixes #20870

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Wouldn't it be better to just add a `title` rather than risk display issues?

**Comment by palewire** [comment]
Of course it's debatable. My argument is that clipping the text doesn't make sense as the default user interface. Commonly clipping the text in more verbose languages, such as a German, seems like an anti-pattern. In my view, the container should be designed to work for all languages out of the box.

**Comment by Andre601** [comment]
I assume the text would simply cut to a new line if it is too long for the box?
In such a case is the title a lot better for readability than having 2 or more lines of one tag...

**Comment by ClearlyClaire** [comment]
> I assume the text would simply cut to a new line if it is too long for the box? In such a case is the title a lot better for readability than having 2 or more lines of one tag...

Good point. That's probably fine indeed.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by Gargron** [comment]
The trends section has to deal with limited vertical and horizontal space. We can't account for all languages and situations. I'm against breaking the layout for long hashtags. The user can find out the hashtag by navigating to it or to the trends page, and screen readers read out the full thing regardless so I don't follow how it's an accessibility matter.

**Comment by Andre601** [comment]
Having to click the hashtag to see what it means isn't good either. It's extra work for no benefit añd could in worst case expose the user to content they don't want.

I myself don't want the full text zo be displayed. Clipping is fine. But a title to see the full text on hover would be good as it allows to know what the hashtag is without having to actually open a new page.

**Comment by palewire** [comment]
Does the lower line of text actually tell you what a trend is about? In the sample site I'm using as a reference, it only has a time frame. That doesn't give you any insight beyond the hashtag. 
Screenshot from 2022-12-15 08-46-11

**Pull request closed without merging**
