### PR TITLE
more free pgconfig by .env

### PR DESCRIPTION
**Pull request by amazedkoumei**
It fixes websocket error on dev-env caused by wrong DB_USER.

### CODE REVIEW

**Review by Gargron — CHANGES_REQUESTED** [review]
👍 on the env variables, I know I said no to this in the past but honestly, I see no harm in this. But the default values are wrong. For example, my default postgres on Ubuntu 16.04 uses a socket instead of localhost/port, and uses my logged-in user instead of "mastodon". I think the pg driver knows this, so it's important to not overwrite those default values with our own ones.

**Comment by amazedkoumei** [comment]
Thank you for your review.
I have fixed wrong default values, and understand your thoughts.
> it's important to not overwrite those default values with our own ones.

**Comment by amazedkoumei** [comment]
I edit database.yml to behave as sama as streaming server. 
I confirmed that pg gem behaves as in accordance with https://www.postgresql.org/docs/9.2/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS .

and remove "for streaming-server" from this pull request's title.

**Review by Gargron — APPROVED** [review]

**Comment by unarist** [comment]
Hmm, should we have `TEST_DB_*` variables separate from `DB_*` variables?

We had used same values for both environments previously, so using same variable is reasonable I think. or fallback to `DB_*` variables would be useful.

**Comment by Gargron** [comment]
@unarist Yes, I think you are right.

**Pull request merged**
