### PR TITLE
fix(web_push_notifications): Send message with welcome notifications

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Since the format message was not sent with the first notification, grouping would fail. This includes the message in the payload for the welcome notification, but also reads it from the last notification (to avoid reading the misconfigured one).

### CODE REVIEW

**Comment by sorin-davidoi** [comment]
@beatrix-bitrot This was why grouping would fail on Android :disappointed:

**Review by Gargron — APPROVED** [review]

**Comment by Komic** [comment]
@sorin-davidoi Would this require resubscribing, or should it fix already existing subscriptions too?

**Comment by sorin-davidoi** [comment]
It should fix them as soon as the next one comes.

**Comment by Komic** [comment]
Great, thanks. :)

**Comment by sorin-davidoi** [comment]
I think when the first one comes it will be grouped together with the previous notifications - even if those were dismissed. This is a bug in the Android implementation, but this should work around that.

**Pull request merged**
