### PR TITLE
Make S3's retry limit a ENV variable

### PR DESCRIPTION
**Pull request by smiba**
In #12085 we've configured the S3 retry_limit to be 0, however on some slightly less stable S3 services this results in some posts from other instances to have missing images/videos.

This has been observed in the issues https://github.com/mastodon/mastodon/issues/13739 & https://github.com/mastodon/mastodon/issues/16520

I have been running my instance with the retry_limit set to 2 for a while now, and I think making this an environment variable would give administrators the option to deal with S3 services sometimes having issues. (In my case a request may rarely randomly fail, causing a S3 action to fail. A retry straight away resolves this)

### CODE REVIEW

**Comment by nightpool** [comment]
@smiba in your case, you mentioned that Sidekiq had several dead jobs with Seahorse::Client:: Networking error. How many retries did those jobs have? Since all of our S3 operations happen in the context of the job queuing system, I think it's inappropriate to have the S3 adapter retry the job synchronously without first yielding the job to Sidekiq to allow it to coordinate how often and how frequently the request should be retried 

That said, a retry count of 1 or 2 doesn't seem excessive, and it's much lower then the original default of 10. However, the fact that these retries happen inside of a Postgres transaction is pretty concerning to me. Do you know I'd that's still the case, or has that code been changed since 2019.

**Comment by smiba** [comment]
> @smiba in your case, you mentioned that Sidekiq had several dead jobs with Seahorse::Client:: Networking error. How many retries did those jobs have?

They went into the failed jobs, however I've found out that a lot of these failed media retrievals don't have any error in sidekiq. Makes me wonder if the ones I found in sidekiq were an exception for other reasons (media host being down / bad etc.)

> A retry count of 1 or 2 doesn't seem excessive, and it's much lower then the original default of 10. However, the fact that these retries happen inside of a Postgres transaction is pretty concerning to me. Do you know if that's still the case, or has that code been changed since 2019?

I've not looked into it, but I assume this is still the same. If it happens entirely async nowadays I would advocate for also increasing the default retry_limit from 0. 

I think having a transaction hang for a bit is preferable over just failing entirely, as long as we stay sensible and don't lock the transaction for minutes chugging through the 10 default retries. Failing right away will harm the user experience more, something is responsible for the S3 call that would otherwise fail. If this is a user upload, taking a little longer is strongly preferred over throwing an upload failed error. If it's timeline content this is retrieved in the background anyway so a lockup of a few seconds doesn't matter.

**Comment by vmstan** [comment]
Bumping this as I ran into an issue with the MediaAttachmentsVacuum job failing without being able to change this setting.

**Comment by vmstan** [comment]
Fixes https://github.com/mastodon/mastodon/issues/27752

**Review by xrh0905 — APPROVED** [review]

**Review by xrh0905 — APPROVED** [review]
Looks good

**Review by mjankowski — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
