### PR TITLE
Change interaction modal input to disable browser spell-checking, capitalization and autocomplete

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This should improve the experience, especially on mobile

### CODE REVIEW

**Comment by vmstan** [comment]
This fixes my complaint, shared in the Discord, for mobile users.

**Comment by adamlui** [comment]
Why would autocomplete be unwanted I don't understand

**Comment by vmstan** [comment]
This is specifically for the domain search. See attached example.

https://github.com/mastodon/mastodon/assets/3002053/6ec25dc9-563a-4213-9043-35cf9e93634a

**Comment by vmstan** [comment]
And then with the default to disable automatic capitalization in the domain field.
https://github.com/mastodon/mastodon/assets/3002053/af7d54be-3b16-46b7-9ea4-c995a155a723

**Comment by ClearlyClaire** [comment]
Spell-checking and capitalization are definitely counter-productive in there, as for autocomplete… I guess that depends on browser implementation, but since we store the resolved input in local-storage, I believe this would not be very useful even if the browser managed to autocomplete with the right thing.

**Review by ThisIsMissEm — APPROVED** [review]

**Review by ykzts — APPROVED** [review]

**Pull request merged**
