### PR TITLE
Implement HTML ruby tags for east-asian languages

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
I'm working on implementing #26592, so far I've just focused on the "getting the tags kept", I haven't yet tested how these display in the web UI.

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Screenshot 2024-07-02 at 19 00 01

Rendering looks okay, but there's duplicate whitespace between words, but that could be my markup: `<p>Lorem <ruby>明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp></ruby> ipsum</p>`. Maybe it should've been: `<p>Lorem <ruby>明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp> </ruby>ipsum</p>`

**Comment by dahlia** [comment]
> Rendering looks okay, but there's duplicate whitespace between words, but that could be my markup: `<p>Lorem <ruby>明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp></ruby> ipsum</p>`. Maybe it should've been: `<p>Lorem <ruby>明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp> </ruby>ipsum</p>`

Yeah, actually Chinese and Japanese do not space between words, so I believe it's okay.

**Comment by ThisIsMissEm** [comment]
> > Rendering looks okay, but there's duplicate whitespace between words, but that could be my markup: `<p>Lorem <ruby>明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp></ruby> ipsum</p>`. Maybe it should've been: `<p>Lorem <ruby>明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp> </ruby>ipsum</p>`
> 
> Yeah, actually Chinese and Japanese do not space between words, so I believe it's okay.

TIL! I probably should've paid more attention in Japanese class in high school 😂

**Review by dahlia — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]
This looks good to me. Composing would be a lot more work, but I think this is a separate issue.

**Pull request merged**
