### PR TITLE
Update intersection-observer to version 0.4.0

### PR DESCRIPTION
**Pull request by ykzts**
ref https://github.com/WICG/IntersectionObserver/pull/224

### CODE REVIEW

**Comment by nolanlawson** [comment]
FWIW we don't really need https://github.com/WICG/IntersectionObserver/pull/224 because we already work around the Edge issue, but upgrading won't hurt. :)

**Review by Gargron — APPROVED** [review]

**Comment by nightpool** [comment]
We should probably just revert this given that we want to get 1.5 out tomorrow

**Comment by ykzts** [comment]
@nightpool Chromium 57 on Mageia 5.1 will not download [`extra_polyfills.js`](https://github.com/tootsuite/mastodon/blob/v1.5.0rc3/app/javascript/mastodon/extra_polyfills.js).

virtualbox_mageia_01_08_2017_00_12_01

Probably other cause (The problem itself is reproduced).

**Comment by Gargron** [comment]
Could it be the isIntersecting vs entry.isIntersecting change? Can you reproduce before/after with PR?

**Comment by ykzts** [comment]
@Gargron Oh, nice! The problem seems to be there. Please wait a moment. I will submit a fix Pull Request.

**Comment by ykzts** [comment]
@Gargron OK. I created PR (#4469).

**Pull request merged**
