### PR TITLE
Use Class and Property Decorators

### PR DESCRIPTION
**Pull request by ykzts**
ref https://tc39.github.io/proposal-decorators/

### before

```javascript
class C extends React.Component {
  /* ... */
}

export default connect(makeMapStateToProps)(injectIntl(C));
```

### after

```javascript
@connect(makeMapStateToProps)
@injectIntl
export C extends React.Component {
  /* ... */
}
```

### CODE REVIEW

**Comment by geta6** [comment]
Looks good to me.
`transform-decorators-legacy` is reliable transform plugin.

**Comment by sorin-davidoi** [comment]
Just as a sidenote, decorators are not currently in the JavaScript standard. It is likely that they will be, but right now they are not. I would personally incline to keep the codebase as close as possible to the standard (on the other hand, dynamic imports are also not in the standard and yet we use them).

**Comment by ykzts** [comment]
resolved conflicts.

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
@sorin-davidoi We use various transpilations *anyway*, this cleans up boilerplate code massively, so I am for it!

**Pull request merged**
