### PR TITLE
add bundle flag to suppress root warning

### LINKED ISSUE #16555: Unnecessary bundle root warning in docker install
### Expected behaviour

There should be no warning

### Actual behaviour

Bundle warns that it shouldn't be run as root, even though it's typical operation in docker containers

### Steps to reproduce the problem

1. Run `docker-compose build`
2. Notice this message:
```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
```

### Specifications

[current main](https://github.com/mastodon/mastodon/commit/7b9299f667673c30bb4807ec2c924390caa8b0f0)

### PR DESCRIPTION
**Pull request by weex**
Fixes #16555

### CODE REVIEW

**Comment by shleeable** [comment]
Works for me. the warning was purely informational...might as well remove the noise

**Comment by ClearlyClaire** [comment]
Why is that even executed as root to begin with…

**Comment by weex** [comment]
Root is default inside docker containers, you'd only add non-root if a binary intentionally fails for root.

**Comment by ClearlyClaire** [comment]
I'd be slightly happier with `bundle` and `yarn` running as the `mastodon` user, although if I understand correctly this is made slightly more awkward by that install step being performed in an intermediate image. Though since the user and group IDs are specifically set, we'd just need the user to be created in both images, right?

**Comment by shleeable** [comment]
Short view is: this PR simply removes a warning during the first stage of the docker build.
The compile stage of the dockerfile is run as root, then select files are copied to the runtime container. etc etc.

The runtime is if I remember correctly running with non-root privledges.

**Comment by ClearlyClaire** [comment]
I know this PR simply removes a warning, and I understand that the daemons then run with non-root privileges. The thing is, `bundle` really does not have to run as root to install dependencies, and I'm not sure what it would cost us to have it stop doing that instead of ignoring the warning.

**Comment by weex** [comment]
This is just to solve the referenced issue, which is admittedly a small one. If there's another bigger issue, I don't mind creating another issue for that to be discussed. This is just the one I felt compelled to solve after having done a little research on bundle flags.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
