### PR TITLE
Change local and federated timeline to be tabs of a single “Live feeds” column

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This:
- split `/public/remote` out of `/public`
- adds a new column to handle all routes under `/public`, with a tab selector to switch between Local/Remote/All
- merges the “Local” and “Federated” links in the single-column navigation panel into a single “Live feeds” item
- keeps the existing columns for the advanced interface: pinning the new “Firehose” column will in fact pin one of the existing column types (this was the easiest way for me to keep compatibility with existing pinned columns)

image

---

Fixes MAS-161

### CODE REVIEW

**Comment by trwnh** [comment]
wait... why "firehose"? what's wrong with "public"?

**Comment by ClearlyClaire** [comment]
There's not really anything wrong with the “public” name, but having `/public` be the public timeline and `/public/local` was awkward and prevented having everything under a clear namespace and benefiting from `react-router`'s path matching.

**Comment by renchap** [comment]
Could we have `/public/local`, `/public/remote` and `/public/all`?

Or replace `/public` with everything, and `/public/local` + `/public/remote` as they are kind of filtered view of the `/public` endpoint?

**Comment by ClearlyClaire** [comment]
The issue is that it would change the meaning of `/public` or prevent the “Live feeds” navigation panel link from going to anything else than the “All” tab

**Comment by ClearlyClaire** [comment]
We can actually do that with our version of `react-router-dom` using `isActive`, so I went ahead and kept the existing routes

**Review by Gargron — APPROVED** [review]

**Comment by Benzi-Junior** [comment]
Can we please make this an optional feature of the interface because quite frankly I hate everything about this.
It seems to be forcing federated content into everyone's feed and make accessing the local feed a multi step process.

**Comment by ClearlyClaire** [comment]
> Can we please make this an optional feature of the interface because quite frankly I hate everything about this. It seems to be forcing federated content into everyone's feed and make accessing the local feed a multi step process.

I'm not sure what you mean, the “Live feeds” tab defaults to Local, so it's the same number of steps as before. If anything, it makes accessing “Federated” (now called “All”) a multiple-step ordeal.

**Comment by hibiyasleep** [comment]
Did this change ever considered mobile layouts?
there's absolutely no reason to block mobile users wandering between Notifications and Federated timeline at once.

image

and "tabbed header" is total waste of real estate in small screens.  
sidebar, header, column header, uh, those three were enough.

**Comment by Benzi-Junior** [comment]
> > Can we please make this an optional feature of the interface because quite frankly I hate everything about this. It seems to be forcing federated content into everyone's feed and make accessing the local feed a multi step process.
> 
> I'm not sure what you mean, the “Live feeds” tab defaults to Local, so it's the same number of steps as before. If anything, it makes accessing “Federated” (now called “All”) a multiple-step ordeal.

I retract my previous statement.
I still think it is a bit odd to merge these views in this way. It seems to be designed to work in the dashboard view, and should do that very well.
Also, why is the "Explore" feed kept separate ?

**Comment by hibiyasleep** [comment]
I can understand why Explore tab have tabs, since it's working as 'search filter' that only limits (not expands) results.

Please understand a case of small private instances, there's a lot, we have literally _zero interest_ at Local timeline.  
what we get fron Local timeline is exact equivalent of my Profile, or very limited subset of Home timeline.

**Comment by joenepraat** [comment]
Actually I like this change. It also creates space for the future Groups button. The only I really dislike is the name 'Live feeds'. It isn't really descriptive IMO and I think a novice user will think about live feeds of events (live streaming). It's also not very translatable. A better name is I think (maybe there are better ones): **Public timelines**

**Comment by solarbirdy** [comment]
I'm late to this party but I have to say as a small-instance admin we both actively use and _desperately need_ separate local and federated feeds for both administrative and discovery purposes. (Admins need local, non-admin users need Federated.)

I don't object to a combined version - sure, go ahead, why not - but losing separates of this would make our lives meaningfully harder.

**Comment by Tangeek42** [comment]
I'm also quite puzzled by this change. I'm sincerely hoping there's something I don't understand, but another issue I would have with this is that I often browse the *local* feed of other instances than my own, because they are thematic. If, by upgrading on their side, their local TL is merged with their global one, I would then see every post they know of. That would defeat the entire purpose of having themed instances.

As others have said, have fun merging stuff, but at least give us an option to still have them separated.

**Comment by joenepraat** [comment]
> Why is the local-only feed going away

The local only feed is not going away. It's still there and still one click.

**Comment by joenepraat** [comment]
> Why is the local-only feed going away

The local only feed is not going away. It's still there and still one click.

> @ClearlyClaire Actually I like this change. It also creates space for the future Groups button. The only thing I really dislike is the name 'Live feeds'. It isn't really descriptive IMO and I think a novice user will think about live feeds of events (live streaming). It's also not very translatable. A better name is I think (maybe there are better ones): **Public timelines**

@ClearlyClaire @Gargron Please consider to change 'Live feeds' to 'Public timelines'. It much better describes where it's about and existing users will not complain about missing functionality.

**Comment by ClearlyClaire** [comment]
> I'm late to this party but I have to say as a small-instance admin we both actively use and _desperately need_ separate local and federated feeds for both administrative and discovery purposes. (Admins need local, non-admin users need Federated.)
> 
> I don't object to a combined version - sure, go ahead, why not - but losing separates of this would make our lives meaningfully harder.

They are still both there and still at the same routes! They are just presented slightly differently, with only one sidebar item, and tabs instead.

**Comment by hibiyasleep** [comment]
so that means forcibly adding a navigation step every time, for all who wants other than default tab. (even previous selection doesn't remembered, right?)

and again, by this change we have 3 header bars in mobile, eating 150.5px total. 
wasting almost 20% of screen height for zero-information navbars should not be normal IMO.

**Pull request merged**
