### PR TITLE
Change the nouns "toot" and "status" to "post"

### PR DESCRIPTION
**Pull request by Gargron**
As far as I can tell, "posts" were first changed to "toots" in #4608, and I think that was a mistake. It was originally spurred by a never-ending stream of questions of "what do we call posts here?", but I don't think every platform needs a cutesy branded name for whatever is on it. Videos on YouTube aren't yeets, they are just videos. Posts on facebook are just posts. Twitter is an exception. I was also not originally aware that "toot" was slang for "fart" in some regions. It makes Mastodon harder to take seriously.

In this PR, the publish button still says "Toot!" but it's worth thinking about as well.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by gunchleoc** [comment]
I just finished my translation and I did notice that there's a hodgepodge of "toot", "post" and "status" in the codebase. Whatever you want to end up with, it needs to be consistent, so I'd be in favor of changing the button label as well, because new users will not understand it.

**Comment by rysiekpl** [comment]
> I was also not originally aware that "toot" was slang for "fart" in some regions.

So, just because a small fraction of the world's population has an immature reaction to anything that reminds them of bodily functions we now must stop using an andearing term deeply ingrained in our community?..

> It makes Mastodon harder to take seriously.

It really doesn't. What makes Mastodon harder to take seriously is that we're not taking it seriously enough.

Just yesterday there was a meeting with the European Commission where Mastodon was prominently featured. There's another one next week. Mastodon is a serious project and can afford itself a bit of light humor, even if some people just cannot get over their childish **ass**ociations.

Not only we *don't have to* go all dry-corporate-language on this magnificently colorful community, we simply *shouldn't*.

**Comment by shleeable** [comment]
image

**Comment by GibsonGibson** [comment]
This is a stupendously bad idea. “Toot!” Sets this platform apart from predecessors.

**Comment by ZoeBijl** [comment]
I don’t much care what they’re called in the backend (can we still it that?) The word “toot” is a part of mastodon, it fits, people know what you mean. If you take that away you take away a part of mastodon’s soul. Also, I think this is a bit too late. We have toots, boosts, tootuals, an app called Toot!, lots of puns and whatever. Why change that now?

Irregardless, I’m trying to not this too seriously, neither should you. Fuck the haters, keep on tootin’.

**Comment by M-i-k-o-t-o** [comment]
I believe that this is a nice chance as it will make the terminology similar to these used by other fedi platforms such as misskey and pleroma. The more we can do to unite the community the better.

**Comment by joyeusenoelle** [comment]
I firmly disagree with this proposal for the same reason M-i-k-o-t-o is in favor of it. "Toot" is part of the character of Mastodon; changing it to make Mastodon more like Misskey and Pleroma (and Twitter and Facebook) gives people one fewer reason to choose Mastodon over those alternatives. In addition, this PR is going to make _existing_ users feel like Mastodon is on a trajectory toward being a "more mainstream" platform - and they'll wonder what changes are next, like algorithmic timelines or suggested follows. This is a grave mistake, and I hope you reconsider.

**Comment by ChlorideCull** [comment]
Calling them toots is part of Mastodon now, really. I think it would be a shame to replace that with something as generic as "post".

If someone says that "they made a toot" I instantly know that it's on Mastodon. It's a surprisingly important part of the Mastodon "brand", just like Tweet and Twitter.

**Comment by goatrocks** [comment]
Unifying how things are named in the variables makes sense. I don't understand the push to rebrand to make things more palatable. Renaming toots to posts will lose some of the character of the software for little gain when, imo, one could make a better case for mastodon by adding better moderation or trust and safety features. Seems like putting a bandaid on things in hopes of getting a couple more users.

**Comment by nihilazo** [comment]
"toot" is part of mastodon's character and culture. The fediverse is so varied and creative and I think that having a more playful word for "post" is part of that vibe. Making the backend more consistent is cool, but please keep "toot".

**Comment by theotheroracle** [comment]
even as someone in a region where it is slang, i immediately knew that a toot was meant to be like an elephant noise . i thought it was so cute, and it's honestly one of the reasons i've loved fedi so much . everyone i've shown it to thought it was cute and fun too, no one's really questioned it . taking it out just seems so sterile, like a step backwards for no good reason .

**Comment by Roboron3042** [comment]
There's a fundamental issue I always think about when seeing the "toot" word: it is just a rebrand of Twitter "tweet" word, a joke. 

1. On the good side, this introduces some sort of identity among the existing Mastodon community, a brand if you like. 
2. On the bad side, some users could misleadingly think that that's all what Mastodon is: just a Twitter joke, nothing to be taken seriously (and I'm pretty sure Eugen still remember the "colonizers" from some years ago who didn't take Mastodon seriously).
3. On the accessibility side, the toot word means nothing if you don't understand the joke. This is a strong argument in favour of using a word which actually means something. Not everyone comes from an IT environment and is able to catch IT jokes, so it is better to use words with a meaning.

I think it is better to have a generic word used by default, but instances can always choose to display a different word anyway, and some already do (like cyber.space with "PING!") because they want to differentiate. That's where having a differentiating "brand" makes more sense: on instances, not on the whole network.


Now, talking about my experience as a Mastodon/Fediverse translator, this change is also a good idea. Someone already pointed out that other Fediverse apps/networks use post/boost, but on the Spanish translation of Mastodon those are translated as toot/retoot (boost == retoot == retweet; going further with the joke). That introduced a big problem for us when previously Mastodon-only applications (such Fedilab and Tusky) started supporting other Fediverse networks. The "right" only solution was to re-translate toot/retoot with the actually right translations of post/boost (publicar/impulsar), but that introduced confusion for Mastodon users that were used to the previous words. This change is the only way we can end such confusion, hopefully.

**Comment by dariusk** [comment]
I'm in favor of this. I made these changes myself when I made the Hometown fork, it is literally one of our main features (a non embarrassing verb!) so if for whatever reason people somehow veto this idea in favor of keeping "Toot"... There's always Hometown.

**Comment by dariusk** [comment]
I'm in favor of this. It's one of the things I changed when I made the Hometown fork and it's literally one of the main points I make when I advertise the fork: no silly verb name, which lets you recruit a wider range of people to your server since their eyes don't reflexively roll out of their head when you show them the main thing you are supposed to do on the site.

**Comment by Playzinho** [comment]
Please keep Toot in Brazil is toot is a verb

**Comment by Gargron** [comment]
> “Toot!” Sets this platform apart from predecessors.

> [...] changing it [...] gives people one fewer reason to choose Mastodon over those alternatives

I think it is incredibly disingenious to the work that went into Mastodon's privacy, safety, decentralization, scalability and usability to say that the only reason someone would pick Mastodon over alternative platforms is that the posts are called "toots".

And, I don't know if it was in this thread, or somewhere on Mastodon, but someone said I'm trying to make Mastodon more like corporate platforms by doing this... When in fact, aping Twitter's "tweet" is the only reason "toot" ever came to be.

> In addition, this PR is going to make existing users feel like Mastodon is on a trajectory toward being a "more mainstream" platform

It always has been on a trajectory to being a mainstream platform. That has been my stated goal since the first posts on Patreon in 2016, this has been my stated intention in every interview and podcast I've been invited to, I've been open about it on my Mastodon account and it's been in my pinned post for years. I do not know how this can come as a surprise to anybody.

**Comment by M-i-k-o-t-o** [comment]
> I firmly disagree with this proposal for the same reason M-i-k-o-t-o is in favor of it. "Toot" is part of the character of Mastodon; changing it to make Mastodon more like Misskey and Pleroma (and Twitter and Facebook) gives people one fewer reason to choose Mastodon over those alternatives. In addition, this PR is going to make _existing_ users feel like Mastodon is on a trajectory toward being a "more mainstream" platform - and they'll wonder what changes are next, like algorithmic timelines or suggested follows. This is a grave mistake, and I hope you reconsider.

Misskey and Pleroma are less mainstream compared to mastodon. Instead it simply makes Mastodon seem like a better citizen of the fediverse. Neither of these have "algorithmic timelines or suggested follows" btw.

A Mastodon user calling a post by a Misskey user as a "toot" is no different to a Xerox user calling your HP printer a "Xerox", and sadly this kind of thing seems common in the mastodon world which makes people have a low opinion of it.

**Comment by kyefox** [comment]
My one meta contrition: toot's origin story as someone goofing at Eugen and Eugen changing it in the space of like 5 minutes is a reflection of the best part of Mastodon and changing it represents a fundamental shift away from that culture of spontaneous, innocent human interaction to one overly concerned with mainstream presentation.

**Comment by ClearlyClaire** [comment]
Concerning the issue at hand, I have no strong opinion either way. I don't think the use of “toot” has an exceedingly negative effect on the perceived “seriousness” of Mastodon nor that Mastodon has any need to pursue being perceived as such.

On the minus side, it'd feel a bit sad to lose this funny verb, on the plus side, this would make the thing slightly more consistent with the remaining of the fediverse (though they'd also be called Notes, Statuses, etc.) and maybe slightly more immediately understandable to people (though I don't think the current “toot” is much of an issue in this regard)

> In addition, this PR is going to make _existing_ users feel like Mastodon is on a trajectory toward being a "more mainstream" platform - and they'll wonder what changes are next, like […] suggested follows.

Suggested follows have already been a thing for a while (so far it only suggested you people you had already interacted with, based on the amount of time you faved, boosted or replied to them). Since a recent PR, it also suggests “popular” people, as a fallback to the previous mechanism (e.g. for new people who haven't interacted with many people yet). Those are only displayed:
- on first log-in (since a very recent PR)
- when looking at the search page on mobile

**Comment by Gargron** [comment]
> My one meta contrition: toot's origin story as someone goofing at Eugen and Eugen changing it in the space of like 5 minutes is a reflection of the best part of Mastodon and changing it represents a fundamental shift away from that culture of spontaneous, innocent human interaction to one overly concerned with mainstream presentation.

It represents a lot of things, not the least of which is that I am now 5 years older. [Here's the fated exchange](https://mastodon.social/@Hbomberguy/146524). You must understand this happened even before Mastodon's first jump in popularity in April 2017. When Mastodon was like three servers and a few thousand users. When the GitHub repository was just me committing right to master.

There were no stakes. A YouTuber that I'd previously only watched videos of, one of the first "celebrities" on a website I built, was daring me to do something silly. It was a completely different environment.

**Comment by kyefox** [comment]
> > My one meta contrition: toot's origin story as someone goofing at Eugen and Eugen changing it in the space of like 5 minutes is a reflection of the best part of Mastodon and changing it represents a fundamental shift away from that culture of spontaneous, innocent human interaction to one overly concerned with mainstream presentation.
> 
> It represents a lot of things, not the least of which is that I am now 5 years older. [Here's the fated exchange](https://mastodon.social/@Hbomberguy/146524). You must understand this happened even before Mastodon's first jump in popularity in April 2017. When Mastodon was like three servers and a few thousand users. When the GitHub repository was just me committing right to master.
> 
> There were no stakes. A YouTuber that I'd previously only watched videos of, one of the first "celebrities" on a website I built, was daring me to do something silly. It was a completely different environment.

I was there, so I know. I think it's the conflict over how to resolve two values that are often at odds: growth of culture and growth of population. You can have both, but favoring one too much tends to squish the other if you're not careful. One way, you get Nazis. The other, you get sprawling, unmanageable megatropoli like Atlanta. Or Twitter.

Twitter is only bad because of choices Twitter makes in service of capital, so I don't think aiming for Twitter scale is bad. A Mastodon on track to reach Twitter scale will always be better than Twitter because you seem to care about not being like Twitter. You're not Jack and co. I just want to make sure we're conscious of how a favoring of growth in population impacts culture. I use Twitter and Mastodon for different things. If Mastodon comes to hold what I use Twitter for (everyone is on it!) without the abusive algorithms, I'm fine with that.

I also like Mastodon's culture and would hate to see it disappear. The respect for boundaries I liked has already faded to almost nothing.

**Comment by GibsonGibson** [comment]
Easy way to fix this is make the displayed button configurable in the interface.---- On Tue, 20 Apr 2021 12:29:35 -0400  ***@***.******@***.***> wrote ---- 
 
 
My one meta contrition: toot's origin story as someone goofing at Eugen and Eugen changing it in the space of like 5 minutes is a reflection of the best part of Mastodon and changing it represents a fundamental shift away from that culture of spontaneous, innocent human interaction to one overly concerned with mainstream presentation. 
 
It represents a lot of things, not the least of which is that I am now 5 years older. Here's the fated exchange. You must understand this happened even before Mastodon's first jump in popularity in April 2017. When Mastodon was like three servers and a few thousand users. When the GitHub repository was just me committing right to master. 
There were no stakes. A YouTuber that I'd previously only watched videos of, one of the first "celebrities" on a website I built, was daring me to do something silly. It was a completely different environment. 
 
I was there, so I know. I think it's the conflict over how to resolve two values that are often at odds: growth of culture and growth of population. You can have both, but favoring one too much tends to squish the other if you're not careful. One way, you get Nazis. The other, you get sprawling, unmanageable megatropoli like Atlanta. Or Twitter. 
Twitter is only bad because of choices Twitter makes in service of capital, so I don't think aiming for Twitter scale is bad. A Mastodon on track to reach Twitter scale will always be better than Twitter because you seem to care about not being like Twitter. You're not Jack and co. I just want to make sure we're conscious of how a favoring of growth in population impacts culture. I use Twitter and Mastodon for different things. If Mastodon comes to hold what I use Twitter for (everyone is on it!) without the abusive algorithms, I'm fine with that. 
I also like Mastodon's culture and would hate to see it disappear. The respect for boundaries I liked has already faded to almost nothing.

**Comment by andybroomfield** [comment]
Where would the fun be in that? 

The Toot! button gives Mastodon character.

**Comment by GibsonGibson** [comment]
It’s your project Eugen, and we can just as easily make the button say whatever it needs to.

**Comment by cathalgarvey** [comment]
Would just like to second @GibsonGibson 's suggestion: there's no reason this stuff can't be made configurable per-server without requiring operators to hack directly on code and complicate updates.

I'd also be sad to see a part of the whimsical feel of Mastodon get removed just to look "legit" but if it coincided with those UI elements getting more configurable and personalisable, then it might add to, rather than subtract from, the communal feel of the Mastodon-fedi.

**Comment by dheadshot** [comment]
How about "Post Toot" or "Send Toot"?

**Comment by kevinmarks** [comment]
I think hbomberguy was referring back to Merlin Mann from ages ago: https://twitter.com/pigpogm/status/771658034?s=20

**Comment by duckwork** [comment]
As someone who's made multiple toots playing off the fact that they're called "toots," I want to say that the verb "toot" is approximately 94% of the reason I joined a Mastodon server a few years ago.  I think that calling them "toots" is more than just a silly (and slightly naughty) branding move; calling posts "toots" is an indication of the anti-corporate nature of Mastodon, and the Fediverse, as a whole.  It's something I really like about this space, that feeling that we're all basically friends and like, there's no money-grubbing or profit motive.  I think "toots" is a sign post to a new user that we don't take ourselves too seriously.

Of course, changing it to "posts" doesn't immediately make Mastodon a sell-out or anything.  I just think it'd remove a cute thing that I personally really like about the community.  I do agree with the earlier comments saying the verb should be called the same throughout the codebase, whatever it's decided to be.  I just hope it stays "Toot!"

**Comment by sambhavsaggi** [comment]
If this is gonna be merged, you might wanna fix some CI issues:

In `spec/mailers/notification_mailer_spec.rb:62`, set it to `post` instead of `status`

Same file line 67: status to post again

Again on lines 79, 84

**Comment by shleeable** [comment]
image

Personally I'm pro-toot.

**Comment by kaias1jp** [comment]
Are you thinking about the impact on the app name using "toot"?

**Comment by kaias1jp** [comment]
Better yet, why not use Esperanto's "Afiŝu"?

**Comment by torresjrjr** [comment]
If we're going to change the terms, heres a good opportunity to disambiguate verbs from nouns with "publish".

> to toot a toot

becomes

> to publish a post

**Comment by rik-shaw** [comment]
I understand people saying "toot" is part of the mastodon legacy, but in my interactions there have been many possible users that simply will not consider moving to mastodon with the word "toot" as it is. Thanks for considering onboarding of new users.

**Comment by KNTRO** [comment]
Hello,

I think this change should have been notified in Crowdin as well. It's a shame that a term related issue is not notified into the translation platform. 😒

Just my two cents here.

**Comment by saladhax** [comment]
I personally don't see a problem with Toot. It's fun and gives the platform some personality. Everyone uses post, so why not set ourselves apart a bit by just keeping it as Toot?

**Comment by cybergrunge** [comment]
Yeah, I think we should also put a suit and tie to the mascot, that would be more corporate.
🙄

**Comment by ndri** [comment]
>Videos on YouTube aren't yeets

Petition to rename YouTube videos to yeets

**Comment by revk** [comment]
Oooh, I missed this one - it makes my personal server, toot.me.uk, a bit daft now :-)

**Comment by Eriner** [comment]
For anyone who wants to revert this change without forking/rebuilding, some CSS hackery can get you there:

https://gist.github.com/Eriner/16749bd3f2f65a24c5f2ac02ae679a74

If you add the CSS there to your instance's `/admin/settings/appearance` page and it'll "replace" the text.

**Pull request merged**
