### PR TITLE
Remove some unused css styles

### PR DESCRIPTION
**Pull request by mjankowski**
I've got a branch locally where I'm using purgecss to automate finding some unused styles. For the first pass here I'm doing it somewhat manually and then also doing some manual checking of when/where things were removed.

If this proves reliable, I'll either automate the changes, and/or try to add the tooling itself to the repo (we should be able to use the compiled css, captured html from specs, repo js/ts/etc)

For this first pass - I just picked a few changes, each one has a ref to removal of last usage in the commit message.

Any feedback on how to best submit/automate this welcome.

### CODE REVIEW

**Comment by renchap** [comment]
From my experience, it is very easy to removed used styles with `purgecss`. You need to have a very extensive coverage for it to work (or CSS files scoped to specific URLs). This is expecialy true with our JS frontend, as there is no way to know if a class if really unused.

**Comment by oneiros** [comment]
> This is expecialy true with our JS frontend, as there is no way to know if a class if really unused.

So, what do we do?

I think the removals from `admin.scss` would be safe to merge. But what about the others?

**Comment by mjankowski** [comment]
> From my experience, it is very easy to removed used styles with `purgecss`. You need to have a very extensive coverage for it to work (or CSS files scoped to specific URLs). This is expecialy true with our JS frontend, as there is no way to know if a class if really unused.

Yeah - the biggest concern is from "dynamically" created class strings either on the ruby or JS side, because the tool is just doing a dumb string token search and wont count this.

The setup I did here was to configure rspec to do a full response body dump into a tmp/ dir (purgecss can't read haml), and then point it at the full app JS dirs and this html output dir on the usage side, and the compiled asset css on the css side.

In this PR, I just sort of randomly plucked a few out of the unused pile and tried to do some manual search checks to see if/where they were removed.

**Comment by mjankowski** [comment]
How can we safely accomplish this or something like it?

**Comment by mjankowski** [comment]
Is this mergeable if I adjust to just the admin.css changes?

If not, what path forward do we have for an exercise like this?

**Pull request closed without merging**
