### PR TITLE
Add a featured link

### PR DESCRIPTION
**Pull request by cutls**
## What's this request?

Add a featured link on the frontpage.  
It can be used for a link to a funding, a status page, a community wiki or something.  

## Screenshots
clink2  
clink1

### CODE REVIEW

**Comment by cutls** [comment]
Now, I'M checking i18n...

**Comment by Gargron** [comment]
I like the idea! I like where it's positioned! But I wonder if it's taking the `Setting` model a bit too far, maybe a separate model is appropriate? After all, it's multiple values grouped together like a row in a table. Deferring to other contributors

**Comment by nightpool** [comment]
could we just put a hash of {link, title, desc, icon} into the settings
table directly?

**Comment by Gargron** [comment]
Technically, yeah, the settings gem encodes stuff as YAML. Not sure how elegant that is though.

**Comment by cutls** [comment]
I think it is not best code, but I have no idea to improve it. I wish I had ability to write an elegant code...

**Pull request closed without merging**
