### PR TITLE
Encode . as - in username URLs (potential fix)

### LINKED ISSUE #6860: Usernames with dots in them break routes
See https://github.com/tootsuite/mastodon/pull/6844#issuecomment-374993289

This is because the dot is used as separator for format in Rails. Before you could easily pull up the ActivityPub JSON of a resource by adding `.json` to the URL, if we change the constraints of the routes, this will become impossible.

### PR DESCRIPTION
**Pull request by Gargron**
Just one possible solution... It does not look super pretty, though.

Fix #6860

### CODE REVIEW

**Comment by tigre-bleu** [comment]
We might have a problem if @john.doe and @john-doe are both existing accounts.

**Comment by Gargron** [comment]
@tigre-bleu We don't allow dashes in usernames :P

**Comment by tigre-bleu** [comment]
😄 Ok, well I think the issue requiring dots in usernames is also valid for dashes (As a reminder the goal is to support already existing LDAP user names).

IMHO any character valid as a the user part of an email adress shall be allowed as a mastodon username.

**Comment by nickswift** [comment]
Have you considered encoding periods and hyphens and other such characters with ASCII codes, ie. `%2E` and `%2D` respectively? It doesn't make for the most attractive URLs, but if the goal is to observe LDAP usernames and the like, this seems like the most straightforward way to go about it.

**Comment by tigre-bleu** [comment]
Another maybe easier to implement solution could be to authenticate using the email adress from the LDAP and to let the user choose a username with the legacy constraints.

**Pull request closed without merging**
