### PR TITLE
NodeJS 14 support - circleci/docker/.nvmrc

### PR DESCRIPTION
**Pull request by shleeable**
NodeJS v14 is now the LTS release.

### CODE REVIEW

**Comment by shleeable** [comment]
TO BE TESTED BEFORE MERGING!

**Review by Gargron — APPROVED** [review]

**Comment by shleeable** [comment]
@Gargron Hey, I've been running v3.4.0 on NodeJS 14.17.

No problems so far

**Comment by danieljakots** [comment]
Any reason why this wasn't merged yet?

**Comment by shleeable** [comment]
Tested for the last week. No issues I'm aware of.

**Comment by shleeable** [comment]
Still no problems with v14.

**Comment by shleeable** [comment]
Updated for https://nodejs.org/en/blog/vulnerability/july-2021-security-releases-2/

**Comment by weex** [comment]
I noticed the README lists Node.js 12+ in requirements which this should also update.

**Pull request merged**
