### PR TITLE
Fix /api/v1/admin/trends/tags using wrong serializer

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fix regression from #18641

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
@Gargron do you mind reviewing this?

**Review by Gargron — COMMENTED** [review]
I don't know what I was thinking when designing this controller, but it's using the normal serializer because when the user doesn't have admin scope/permission, it acts like the non-admin controller. Using the admin serializer here would expose extra details to non-admin users.

**Comment by ClearlyClaire** [comment]
This is an ugly workaround, but I changed it so:
- which serializer is used depends on whether the usage can manage trending tags
- the javascript component doesn't link to anywhere if the `id` is not serialized

**Comment by trwnh** [comment]
> the javascript component doesn't link to anywhere if the id is not serialized

how does that interact with #21701? if done this way, i feel like you would also need an admin API endpoint to lookup tag id by name... or perhaps checking for one of the other properties?

**Comment by ClearlyClaire** [comment]
> > the javascript component doesn't link to anywhere if the id is not serialized
> 
> how does that interact with #21701? if done this way, i feel like you would also need an admin API endpoint to lookup tag id by name... or perhaps checking for one of the other properties?

I don't think this whole endpoint is very useful when the user doesn't have the permissions to manage hashtags. AFAICT the only reason there's the fallback to begin with is the admin dashboard that is displayed even if one does not have tag management permissions.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
