### PR TITLE
Add ability to pin thread columns

### LINKED ISSUE #11467: CW / Pin visible in all headers, even where inapplicable
mastodon.social master -- can suddenly see CW reveal icon in header, even for threads that have no CW. Can also see menu icon with "pin" option, although clicking this just makes the column disappear.

image

### PR DESCRIPTION
**Pull request by Gargron**
Fix #11467

### CODE REVIEW

**Comment by ThibG** [comment]
I am not sure how useful that is without subscribing to updates from the thread

**Comment by Gargron** [comment]
You get auto-updates if they arrive via notifications / home feed. Yes, it's not super useful, but then again how many people even know about the "pin" button? It feels like this would satisfy a few people without any side effects.

**Comment by ThibG** [comment]
Hm, it seem to me that the use case would be to have quick access to some toots, more than having them displayed at all times. Such an use case could be addressed by bookmarks.

Otherwise OK, but every other pinned column does get update, this would introduce a confusing discrepancy

**Comment by Gargron** [comment]
Quick access to some toots is also solved by favourites, I think the idea is having them always displayed.

**Pull request closed without merging**
