### PR TITLE
Convenient colour palettes

### PR DESCRIPTION
**Pull request by marrus-sh**
This doesn't change *anything* about the site, but it does add some handy colour palettes (Tango, Solarized, etc) in `variables/palettes.scss` to make customizing your instance as easy as substituting one variable name for another.

### CODE REVIEW

**Comment by ineffyble** [comment]
Ooh, I like it.

**Comment by expenses** [comment]
Looks good. I suppose there could be concerns about bloat with this sort of thing, but we definitely want to put colours into a separate file to avoid 'magic numbers'.

**Review by mjankowski — CHANGES_REQUESTED** [review]
Thanks for collecting all of these -- can you explain a little more about how these would be intended to be used?

I have some concern that we should improve the variable usage throughout the project first before adding "themes" or color-sets.

Separately, this PR needs a rebase.

**Comment by ashfurrow** [comment]
Cool idea! Thanks for the PR @marrus-sh. I think now that we have the ability to add custom CSS maybe some documentation could be added too. Could you rebase with the latest changes from master?

**Comment by ashfurrow** [comment]
Any update on this @marrus-sh ?

**Comment by ashfurrow** [comment]
Hi there, thanks for the pull request! It's been a few weeks with no updates, and https://github.com/tootsuite/mastodon/pull/2912 has been merged which addresses the same problem. I'm going to close this pull request, but if you'd like to discuss it further please don't hesitate to open a new one, or an issue. Thanks again!

**Pull request closed without merging**
