### PR TITLE
Fix db:seed - only run some validations when the field was changed

### PR DESCRIPTION
**Pull request by Gargron**
I'm not 100% sure how to test this. But I believe something like this is good practice, I have seen this pattern in the GitLab codebase. However, correct me if I'm wrong on something.

### CODE REVIEW

**Comment by mjankowski** [comment]
The benefit here is some smallish time savings by avoiding validations which aren't going to be relevant for certain fields? I guess that's fine to do.

If you wanted to add specs for those validation skips - you could make records with invalid values for these skipped fields, and then have the spec expect them to be valid, and/or expect there to be no errors on a field which we know to actually be invalid - but which did not change as part of the valid/save step.

**Review by mjankowski — COMMENTED** [review]
The benefit here is some smallish time savings by avoiding validations which aren't going to be relevant for certain fields? I guess that's fine to do.

If you wanted to add specs for those validation skips - you could make records with invalid values for these skipped fields, and then have the spec expect them to be valid, and/or expect there to be no errors on a field which we know to actually be invalid - but which did not change as part of the valid/save step.

**Comment by Gargron** [comment]
I added tests. Please review/approve!

**Review by joyeusenoelle — APPROVED** [review]
This all looks valid to me!

**Review by ykzts — APPROVED** [review]

**Review by mjankowski — APPROVED** [review]

**Comment by clworld** [comment]
I'm getting 'Note is too long' error in RemoteProfileUpdateWorker.
It seems "with_options if: :local?" is ignored.
This comment says nested conditions are overrided: https://github.com/tootsuite/mastodon/pull/3612#issuecomment-307101972
With reverting my instance to yesterdays version, this exception does not happen.

long_note

**Comment by Gargron** [comment]
@clworld Thank you for reporting this so soon. I will try to submit a fix immediately.

**Comment by Gargron** [comment]
@clworld #3644

**Pull request merged**
