### PR TITLE
Fix Web UI trying to save user settings when logged out

### LINKED ISSUE #30066: Error: `422 can't verify CSRF token authenticity` on explore page
### Steps to reproduce the problem

1. Visit typo.social/explore
2. Scroll down
3. See error:

Screenshot_20240425-110837

On desktop (Windows, Firefox) no error is produced, but scrolling stops at the same point, suggesting to me that the error occurs but is not communicated.

### Expected behaviour

No error

### Actual behaviour

Error (and then no additional posts will load)

### Detailed description

Also reported here:
- https://www.reddit.com/r/Mastodon/comments/18fmda5/422_cant_verify_csrf_token_authenticity/?rdt=43597
- https://mementomori.social/@rolle/110802929745486086
- Possible duplicate of https://github.com/mastodon/mastodon/issues/1236 (I can't tell)

### Mastodon instance

typo.social

### Mastodon version

v4.2.8

### Browser name and version

Firefox on Android, 124.2.0 (Build #2016012559), 7a0e399c7b+ GV: 124.0.2-20240401114208 AS: 124.0 2024-04-01T17:18:00.821594648

### Operating system

Android 13

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #30066

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This could be worth backporting, but this would require rebuilding assets, which is not required by the current backports for the next patch releases yet.

**Review by renchap — APPROVED** [review]
Looks good to me.

I am not against a backport, having to recompute the assets should not be a big issue for server admins?

**Comment by projectuser60** [comment]
Thank you for squashing this bug. I duplicated changes made in 'app/javascript/mastodon/actions/settings.js' and restarted Mastodon processes but issue persists. Are any further actions required to apply this to a running Mastodon 4.2.9 instance?

**Comment by renchap** [comment]
You need to run the `assets:precompile` task to recompile the JS assets after changing the source file.

**Pull request merged**
