### PR TITLE
Add notifications when a reblogged status has been updated

### PR DESCRIPTION
**Pull request by Gargron**
Follow-up to #16697

___

Funded through the BMBF (BMBF Förderkennzeichen: 01IS21S29)

### CODE REVIEW

**Review by ClearlyClaire — COMMENTED** [review]
I don't know if this notification type warrants all the notification pathways that other notification types use, but I can't see anything in this PR about:
- web push notifications `app/javascript/mastodon/service_worker/web_push_locales.js`, `app/javascript/mastodon/service_worker/web_push_notifications.js`, `app/controllers/api/web/push_subscriptions_controller.rb`
- configuring how and where to show notifications (`app/javascript/mastodon/reducers/settings.js`, `app/javascript/mastodon/features/notifications/components/column_settings.js`)
- mail notifications

**Comment by Gargron** [comment]
We don't have e-mail notifications for polls or new statuses, and I think it doesn't make sense for this either. I've added the other things. The notification settings are definitely too long now, and have too many things that I wouldn't care about adjusting, but it will do for now.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
In `LocalNotificationWorker`, notifications are skipped if `Notification.where(account: receiver, activity: activity).any?`.

This means that `update` notifications will be missed if you have a `status` (subscription) notification already. Maybe that condition needs changing to include the notification type as well.

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me.

There is another scenario I'm a bit worried about but I don't have an easy fix to it: suppose you're boosting someone who is silenced (e.g. someone you follow boosted them), and they then edit their post. Because they're silenced and you don't follow them, you don't get the notification.

But on the other hand, someone could be silenced precisely because they do stuff like spam in edits?

**Pull request merged**
