### PR TITLE
Add command to remove avatar and header images of inactive remote accounts from the local database

### LINKED ISSUE #9567: tootctl media remove does not include profile avatars and headers
### Expected behaviour

1. `tootctl media remove` should clean up media thats older than `x` days to clean up file space, including headers and profile pictures that haven't been accessed as these also go under media.

### Actual behaviour

1. `tootctl media remove` only cleaned out file uploads, not headers and profile pictures.

### Steps to reproduce the problem

Clean up disk space by removing old media.

### Specifications

Commit hash: 2e1b5edfea1b03f64c69266f979caee228fa90b7 . Running through docker.

### PR DESCRIPTION
**Pull request by evanphilip**
This implements a new sub-commands for `tootctl media` called `remove-profile-media` to remove avatar and header images of remote accounts that appear inactive from the local database.

Fixes https://github.com/mastodon/mastodon/issues/9567 : absence of method to remove avatar and header images, leading to excessive disk usage. 

This PR is just a slight modification of https://github.com/mastodon/mastodon/pull/21066 by @dunkelstern, which was withdrawn by the author since `last_webfingered_at` was not a satisfactory way to determine old accounts. While imperfect, the existing `tootctl accounts cull` uses `updated_at` and `last_webfingered_at`. Maybe it is the best one can do? 

I have also added an option which lets one keep avatars.

All credit to @dunkelstern , I am just desperate to clear my storage and it looks like there are others like me who could use this too!

### CODE REVIEW

**Comment by evanphilip** [comment]
If anyone wants to test this command, I'd be happy to walk them through it. But please backup your instance first.

**Comment by zseri** [comment]
wouldn't it make more sense to print account URLs as they are deleted? that would provide a nice progress indication, I suppose, if we're printing them anyways...

**Comment by evanphilip** [comment]
> wouldn't it make more sense to print account URLs as they are deleted? that would provide a nice progress indication, I suppose, if we're printing them anyways...

This is using Mastodon’s own concurrent worker which doesn’t have an option for thread-safe printing. This is the first time I am using Ruby, but in general simple printing during a concurrent process can lead to corruption of the output.

Thank you for looking at this!

**Comment by evanphilip** [comment]
* This is using the same check that is used by `tootctl accounts cull` to check for confirmed account activity within a span of time. `updated_at` and `last_webfingered_at` is not perfect, but since a command in the stable release uses it, maybe it is the best one can do?
* There is a discussion about table column hotness here that may help make a better test: https://github.com/mastodon/mastodon/issues/7908

**Comment by evanphilip** [comment]
I am bad at naming 🙄 
I am open to suggestions.

**Pull request closed without merging**
