### PR TITLE
Add account notes to hover cards

### PR DESCRIPTION
**Pull request by renchap**
To avoid the card taking too much space, we only display the first 3 lines of the note.

Fixes MAS-294

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This is how it looks:
image

The code is clean, but I have a concern that it's not clear at all that this is the user-provided note for the account.

**Comment by renchap** [comment]
Maybe I can add a "User note" (or simply "Note"?) header above the note text, similar to the field labels?

**Comment by renchap** [comment]
Updated to match the account header:
image

I also changed the label (in both places) from "Note" to "Personal note", to make it cleared that this is only something you can see.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by shleeable** [comment]
Wonderful! I think I had an issue for this... *looks*

**Pull request merged**
