### PR TITLE
Fix `tootctl accounts approve --number N` not approving the N most recent registrations

### LINKED ISSUE #24596: `tootctl accounts approve --number` does not approve  the N most recent registrations
### Steps to reproduce the problem

1. Require approval for sign-up in your Mastodon instance.
2. Create some users. The example below manipulates the `created_at` attribute for exemplification:
```rb
Fabricate(:user, created_at: 10.days.ago)
Fabricate(:user, created_at: 5.days.ago) # most recent registration
```
3. Approve the most recent account with the CLI `--number` option as shown below:
```
RAILS_ENV=development bin/tootctl accounts approve --number 1
```

### Expected behaviour

Approves account whose `created_at` is 5 days ago

### Actual behaviour

Approves account whose `created_at` is 10 days ago

### Detailed description

According to the [documentation](https://docs.joinmastodon.org/admin/tootctl/#accounts-approve), `tootctl accounts approve --number N` should approve the N most recent registrations.

However, the actual behavior is approving the N-first found accounts.

### Specifications

Mastodon 4.1.2
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

### PR DESCRIPTION
**Pull request by danielmbrasil**
Fixes #24596.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Sounds to me it would make more sense for the documentation to be changed, accepting a fixed number of pending accounts seems only useful for a waiting-list type use case, in which FIFO makes more sense.

**Comment by trwnh** [comment]
https://github.com/mastodon/documentation/pull/1201

**Comment by danielmbrasil** [comment]
Hey @ClearlyClaire, could you help me with this problem?

So, I'm still working on (#24541)  and ended up opening this PR because my tests for this method turned out to be flaky. Now, trying to test it with the N earliest registrations I'm having basically the same issue.

I'm trying to test it by creating a bunch of users with a before hook, then invoking `#approve` for a few of them and checking if the earliest created ones were approved. Apparently, this is not always correct.

It seems that sometimes the earliest registrations aren't returned first by the `#limit` method in:

https://github.com/mastodon/mastodon/blob/faf657d709667867daad4ba229f2b9d30ada71c7/lib/mastodon/accounts_cli.rb#L547

Shouldn't that line order pending accounts first before approving them to make sure always the earliest pending registrations are approved? Or could this problem be related to my test?

The flaky test in question:
```rb
context 'with --number option' do
  context 'when the number is positive' do
    let(:options) { { number: 3 } }
    let(:total_users) { 10 }

    before do
      Form::AdminSettings.new(registrations_mode: 'approved').save
      Fabricate.times(total_users, :user)
    end

    it 'approves the N earliest pending registrations' do
      described_class.new.invoke(:approve, nil, options)

      n_earliest_pending_registrations = User.order(created_at: :asc).first(options[:number])

      expect(n_earliest_pending_registrations.all?(&:approved?)).to be(true)
    end
end
```

**Comment by ClearlyClaire** [comment]
> Shouldn't that line order pending accounts first before approving them to make sure always the earliest pending registrations are approved?

I think the current order is unspecified, but it would make sense for it to be oldest first, so adding an `order` close on `id` or `created_at` would make sense.

**Pull request closed without merging**
