### PR TITLE
Extract `ActivityPub::Identifier` model concern

### PR DESCRIPTION
**Pull request by mjankowski**
Pulls out same behavior from these 3 models into shared concern.

Side note, the method def they are calling is:

```
  def generate_uri_for(_target)
    URI.join(root_url, 'payloads', SecureRandom.uuid)
  end
```

- The method just ignores the argument it's sent ... we could potentially change the signature and/or naming here to remove the ignored arg. Something like `generate_payload_uri` or whatever may be more accurate (my assumption before I looked at the def was that the passed in object had something to do with the generation, but it doesnt, its just a random string).
- Is there a reason that `payloads` string is there? I don't think it ever contributes to the generated string...

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
> Is there a reason that `payloads` string is there? I don't think it ever contributes to the generated string...

I think it is intended to contribute but has not ever been verified to. This should probably be changed to `URI.join(root_url, '/payloads/', SecureRandom.uuid)`.

**Comment by ClearlyClaire** [comment]
I find the concern name confusing. This method is used to set a unique URI that does not directly correspond to database IDs, and the concern is only about that, and not to generate any kind of ActivityPub payload.

On a side note, I'm not sure how useful that whole approach is given activities cannot be looked up by such URLs in an efficient way. It might make more sense to have per-activity-type namespace and an easy-to-look-up internal ID. However, this cannot really be retroactively applied to existing activities…

**Comment by mjankowski** [comment]
RE: the concern module name ... I think I named that prior to fully investigating what the method they were calling was doing. Open to better ideas there. Might make sense to rename/update that value-generating method first, then contemplate a module name.

Is it accurate that for all these use case the whole goal is just to get some unique uri value as a global identifier that never needs to be accessed/routed/etc, but does need to be unique across the universe of published AP objects by the instance?

**Comment by ClearlyClaire** [comment]
> Is it accurate that for all these use case the whole goal is just to get some unique uri value as a global identifier that never needs to be accessed/routed/etc, but does need to be unique across the universe of published AP objects by the instance?

Mostly accurate. There are edge cases where they need to be identified by URI, and those edge cases are slow due to the lack of indexes.

**Comment by mjankowski** [comment]
Excellent. Thoughts on ...

- Rename existing method to `ActivityPub::TagManager#generate_activity_uri` (and remove the unused arg) - can do this in separate PR
- Rename the added concern here to `ActivityPubActivityURI` or similar?

**Comment by mjankowski** [comment]
Rebased and made a few changes:

- Renamed model concern to `ActivityPub::Identifier`, models include this now
- Renamed the TagManager method to `generate_activity_uri`
- Removed the unused arg from that method and places its called

**Comment by mjankowski** [comment]
Curious if this is acceptable/desirable post-rename, or if we need more, etc.

**Pull request closed without merging**
