### PR TITLE
Add Storj DCS to cloud object storage options

### PR DESCRIPTION
**Pull request by jtolio**
More explanation here: https://forum.storj.io/t/object-storage-provider-for-mastodon-instance/11464/37

### CODE REVIEW

**Comment by jtolio** [comment]
@ClearlyClaire any tips on if this can be merged?

**Review by Gargron — APPROVED** [review]

**Comment by emilweth** [comment]
FYI they used this merge request to back up a spam then sent to a scrapped list of mastodon admins
image

**Comment by jtolio** [comment]
Oof - that email was sent out on cc by mistake from our growth team trying out a new tool. Apologies, we mean nothing but goodwill to the Mastodon community! Storj is also federated and open-source. We'd love any feedback around the core technology, and how it could improve as a project. 

As a brief note - you do not have to buy any token anything. We integrate with Stripe and accept credit cards. Bandwidth is priced in dollars though we do use an Ethereum incentive layer for node participation. We are broadly interested in how we can create a better global persistence/distribution layer for open-source apps and hope that our federated-style approach to cloud object storage can be helpful here.

**Comment by TheKinrar** [comment]
Besides how unlikely it is that your "growth team" inadvertently sent a marketing email to many Mastodon admins, with wording that suggests that this PR being merged means the Mastodon project endorses Storj in any way, it is also not a really acceptable (nor legal) practice to scrape emails online to fill a mailing list.

**Pull request merged**
