### PR TITLE
initial update of nan-TW l10n

### PR DESCRIPTION
**Pull request by Yoxem**
For crowdin or other way of l10n of Taiwanese (nan-TW).

Initial lang data files pushed.

### CODE REVIEW

**Comment by nschonni** [comment]
https://github.com/mastodon/mastodon/blob/main/CONTRIBUTING.md#translations

**Comment by renchap** [comment]
As @nschonni said above, our translations are managed using [Crowdin](https://crowdin.com/project/mastodon).

Please upload your translations there, and they will be imported into the codebase automatically.

**Comment by gunchleoc** [comment]
@Yoxem We'll also need the English and native name to add to the language menus.

**Comment by Yoxem** [comment]
> @Yoxem We'll also need the English and native name to add to the language menus.

English: Taiwanese (Hokkien)
Native: 臺語（Hô-ló話）

**Comment by gunchleoc** [comment]
I have created a PR with the changes to the application: https://github.com/mastodon/mastodon/pull/29184

**Review by Pham1993 — COMMENTED** [review]
Anh

**Comment by gunchleoc** [comment]
Looks like Crowdin doesn't have this locale out of the box, and it isn't listed on the CLDR, so, we need the plural rules. For examples of plural rules, see https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html

https://support.crowdin.com/changing-target-languages/#adding-custom-languages

**Comment by Yoxem** [comment]
> Looks like Crowdin doesn't have this locale out of the box, and it isn't listed on the CLDR, so, we need the plural rules. For examples of plural rules, see https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html
> 
> https://support.crowdin.com/changing-target-languages/#adding-custom-languages

Taiwanese (Min Nan) have neither plural nor dual form of noun and adjectives, like Cantonese  and Mandarin Chinese.

**Comment by Pham1993** [comment]
Hi

**Pull request closed without merging**
