### PR TITLE
Remove inline CSS in SVG logo

### PR DESCRIPTION
**Pull request by luxiaba**
Move inline css `style="color:#fff"` in svg logo to `mastodon/basics.scss` to comply with Content Security Policy, otherwise there are some "Refused to apply" errors in production env like below:

image

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
These can probably be dropped altogether rather than moved, as they currently work fine with the CSP blocking them.

**Comment by luxiaba** [comment]
Yes it is, you reminded me thank you🤩

**Review by ClearlyClaire — APPROVED** [review]

**Comment by Gargron** [comment]
The inline style is there for when/if somebody uses the logo file standalone.

**Comment by luxiaba** [comment]
How about filling the color `#FFF` directly into the `path`?

**Comment by MaciekBaron** [comment]
No, the path currently uses `currentColor` so that it can be overridden by a `color` definition. The `use` approach allows defining a default colour (white / `#FFF`). Probably best to just include the hash in the CSP for this purpose.

**Pull request merged**
