### PR TITLE
Change video uploads to enforce certain limits

### PR DESCRIPTION
**Pull request by Gargron**
- Dimensions smaller than 1920x1200
- Frame rate at most 60

This numbers are adopted from Twitter, as I think they're quite reasonable for avoiding invalid video uploads as well as uploads that would not play well within a browser or mobile environment.

### CODE REVIEW

**Comment by ThibG** [comment]
Hm, I'm not sure about that.
My single-user instance knows about a bunch of video files that would have been rejected by this change.

**Comment by Gargron** [comment]
@ThibG Yes, I am also aware of a few video uploads that would have been rejected by this change. They lag my browser whenever they appear. That's my point. Mastodon is ill-fitted for high-definition video because we don't generate different size variants and load them based on container size / bandwidth capacity.

**Comment by ThibG** [comment]
I'm not only talking about videos with too high a resolution, there are some which have an aspect ratio outside the specified range. Some are just slightly out of it, other are well outside, but still are displayable kinda fine?

**Comment by Gargron** [comment]
Do you suggest a different aspect ratio limit or removing the aspect ratio limit?

**Comment by Gargron** [comment]
Worth mentioning, these checks will be performed on GIFV uploads (such as soundless WebM, MP4 files), but not on GIF uploads that will then be converted to GIFV, because of the order of conversions. I'm not sure how fine or not fine that is. This could be alleviated, if necessary, by moving these checks into a validation, however, that would mean ffmpeg would run on to-be-rejected videos before they are rejected.

**Comment by ThibG** [comment]
What's the reason for an aspect ratio limit? Avoiding very high or large videos? If so, maybe limiting height and width directly would make a little more sense.

I seem to have only encountered aspect ratios of up to 1:3.02 in the wild, but if we do opt for an aspect ratio limit, I guess we could allow even things like 1:4 or 1:5. It may be useful for some art or showcasing parts of an UI, for instance.

**Comment by Gargron** [comment]
Removed aspect ratio check.

Here is my concern. GIF smaller than 32x32px is converted to GIFV on server A. This then federates as a video file. Server B then rejects it. That wouldn't be good :confused:

**Comment by Gargron** [comment]
Removed the lower bound of 32x32. Since there is a GIF matrix limit that is even smaller than the video matrix limit, the upper bound should not present any issue.

**Review by ykzts — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Why is such stuff not configurable? Why is there no optional option to downscale the video?

**Pull request merged**
