### PR TITLE
Keep avatars transparent

### PR DESCRIPTION
**Pull request by zunda**
Fixes https://github.com/mastodon/mastodon/pull/31966#issuecomment-2382664429

### CODE REVIEW

**Comment by zunda** [comment]
Before (black square around green icon with transparent background):
before

After (poster's icon shows around the green icon):
after

**Comment by ClearlyClaire** [comment]
Note that this was added in #31966 to have graceful fallback for avatars that fail to load.

**Comment by renchap** [comment]
Yes, this is not a proper fix.

We probably need to have an `onload` callback on the image, and remove the background if the image loaded successfully.

**Comment by zunda** [comment]
[Googling](https://stackoverflow.com/a/52968407/5716182), I found that a pseudo selector like `img::before` might work here.

A big problem with me is that I cannot really reproduce the situation where the avatar fails to load. Is it OK to just delete the image file in the development environment? Might there be a procedure you followed when working on 31966?

**Comment by Gargron** [comment]
> Is it OK to just delete the image file in the development environment?

Yes, this would work.

**Comment by zunda** [comment]
Current status:

Screenshot_2024-10-03_15-58-09

`acct?.get('acct')` is visible in boosted post. Is this expected?

Screenshot_2024-10-03_15-58-46

with added `img::before`:

```patch
--- a/app/javascript/styles/mastodon/components.scss
+++ b/app/javascript/styles/mastodon/components.scss
@@ -2077,14 +2077,21 @@ body > [data-popper-placement] {
   display: block;
   position: relative;
   border-radius: var(--avatar-border-radius);
-  background-color: var(--surface-background-color);
 
   img {
     width: 100%;
     height: 100%;
     object-fit: cover;
     border-radius: var(--avatar-border-radius);
+    display: block;
+  }
+
+  img::before {
+    width: 100%;
+    height: 100%;
+    border-radius: var(--avatar-border-radius);
     display: inline-block; // to not show broken images
+    background-color: var(--surface-background-color);
   }
 
   &-inline {
```

but with `alt=' '` needed:

```patch
--- a/app/javascript/mastodon/components/avatar.tsx
+++ b/app/javascript/mastodon/components/avatar.tsx
@@ -46,7 +46,7 @@ export const Avatar: React.FC<Props> = ({
       onMouseLeave={handleMouseLeave}
       style={style}
     >
-      {src && <img src={src} alt='' />}
+      {src && <img src={src} alt=' ' />}
       {counter && (
         <div
           className='account__avatar__counter'
```

Might there be a way to force browsers to render the empty image content even when it fails to load?

**Comment by zunda** [comment]
Another try with `` fails with errors like

```
✖ eslint --fix:

.../app/javascript/mastodon/components/avatar.tsx
  53:11  error  JSX props should not use arrow functions                   react/jsx-no-bind
  54:28  error  Unsafe member access .display on an `error` typed value    @typescript-eslint/no-unsafe-member-access
  55:36  error  Unsafe member access .className on an `error` typed value  @typescript-eslint/no-unsafe-member-access
```

with:

```patch
--- a/app/javascript/mastodon/components/avatar.tsx
+++ b/app/javascript/mastodon/components/avatar.tsx
@@ -46,7 +46,14 @@ export const Avatar: React.FC<Props> = ({
       onMouseLeave={handleMouseLeave}
       style={style}
     >
-      {src && <img src={src} alt='' />}
+      {src && <img
+        src={src}
+        alt=''
+        onError={(e) => {
+          e.target.style.display = 'none';
+          e.target.parentElement.className = 'account__avatar__noicon';
+        }}
+      />}
       {counter && (
         <div
           className='account__avatar__counter'
```

```patch
--- a/app/javascript/mastodon/components/avatar_overlay.tsx
+++ b/app/javascript/mastodon/components/avatar_overlay.tsx
@@ -39,7 +39,13 @@ export const AvatarOverlay: React.FC<Props> = ({
           className='account__avatar'
           style={{ width: `${baseSize}px`, height: `${baseSize}px` }}
         >
-          {accountSrc && <img src={accountSrc} alt={account?.get('acct')} />}
+          {accountSrc && <img
+            src={accountSrc}
+            alt={account?.get('acct')}
+            onError={(e) => {
+              e.target.parentElement.className = 'account__avatar__noicon';
+            }}
+          />}
         </div>
       </div>
       <div className='account__avatar-overlay-overlay'>
@@ -47,7 +53,13 @@ export const AvatarOverlay: React.FC<Props> = ({
           className='account__avatar'
           style={{ width: `${overlaySize}px`, height: `${overlaySize}px` }}
         >
-          {friendSrc && <img src={friendSrc} alt={friend?.get('acct')} />}
+          {friendSrc && <img
+            src={friendSrc}
+            alt={friend?.get('acct')}
+            onError={(e) => {
+              e.target.parentElement.className = 'account__avatar__noicon';
+            }}
+          />}
         </div>
       </div>
     </div>
```

and

```patch
--- a/app/javascript/styles/mastodon/components.scss
+++ b/app/javascript/styles/mastodon/components.scss
@@ -2073,11 +2073,14 @@ body > [data-popper-placement] {
   align-items: center;
 }

-.account__avatar {
+%account-avatar {
   display: block;
   position: relative;
   border-radius: var(--avatar-border-radius);
-  background-color: var(--surface-background-color);
+}
+
+.account__avatar {
+  @extend %account-avatar;

   img {
     width: 100%;
@@ -2146,6 +2149,13 @@ body > [data-popper-placement] {
   }
 }

+.account__avatar__noicon {
+  @extend %account-avatar;
+  background-color: var(--surface-background-color);
+  color: var(--surface-background-color);
+  overflow: hidden;
+}
+
 a .account__avatar {
   cursor: pointer;
 }
```

Any help from experts are appliciated!

**Pull request closed without merging**
