### PR TITLE
Fix typo

### LINKED ISSUE #376: shortcuts: namely, N to start a new post
it's in the title

### PR DESCRIPTION
**Pull request by Pangoraw**
_It adds a shortcut (n) to focus the compose textarea_, **and also fixes autoFucus -> autoFocus in defaultProps**.

**EDIT**: Removed the shortcut, only fixes the typo.

### CODE REVIEW

**Comment by ykzts** [comment]
please see https://github.com/tootsuite/mastodon/issues/376#issuecomment-282911571

**Comment by Pangoraw** [comment]
Since this is still in discussion. I will change my pr to only fix the typo.

**Comment by ykzts** [comment]
Can I change the title of this Pull Request?

**Comment by Pangoraw** [comment]
I just did ! :+1:

**Review by ykzts — APPROVED** [review]

**Review by Gargron — APPROVED** [review]

**Pull request merged**
