### PR TITLE
Add UI for enabling/disabling poll notifications

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by Aditoo17** [comment]
Could you also add poll notifications to the quick filter bar?

**Comment by Gargron** [comment]
I'm wondering if the strings are understandable enough for the end-user. Polls - why polls? Maybe call it "Poll results" or something like that? What does the notification text say when you get a notification like that?

**Comment by ThibG** [comment]
Fair point, “poll results” is probably a better name.

Here is what it looks like:
Screenshot_2019-03-13 Dev instance(1)

And looking at it, I realize it hasn't been updated since the point such notifications were only for your own polls…

**Comment by Gargron** [comment]
Okay! So "Poll results", and also "A poll you voted in has ended"

**Comment by ThibG** [comment]
Screenshot_2019-03-13 Dev instance(2)

**Review by Gargron — APPROVED** [review]

**Pull request merged**
