### PR TITLE
Remove `config/secrets.yml` file

### PR DESCRIPTION
**Pull request by mjankowski**
In Rails 7.1 this feature is deprecated, and in 7.2 it's removed.

We have a work-around in our devise config to avoid a deprecation warning which comes from how we were setting the value, but in Rails 7.1.4 (just released, I have WIP update branch) the deprecation is back and comes from just using the secrets feature at all.

I initially thought we'd have to either go down the "credentials" feature path (not ideal for multi-operator packaged app), but I think that's not the case. In both 7.1/7.2 the [behavior](https://github.com/rails/rails/blob/v7.2.1/railties/lib/rails/application.rb#L453-L471) here is like:

- In production environment, read first from `SECRET_KEY_BASE` env var, and then from credentials file, raise error if not configured (auto-generation is never attempted in production, I think)
- In test/dev, generate a random value which gets persisted in `tmp/local_secret.txt` and use that one

...I think that makes this safe to just delete? All local dev/test envs will keep operating w/out needing new values in `.env.*` files; and all production servers will keep reading from the env var (and error if they are removed or failed to set up on new installs) ... all of which I think is our desired behavior?

Separately - I think this feature throwing up a deprecation notice is the only issue on a 7.1.4 upgrade ... will do separate PR if that's true.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
> ...I think that makes this safe to just delete? All local dev/test envs will keep operating w/out needing new values in `.env.*` files; and all production servers will keep reading from the env var (and error if they are removed or failed to set up on new installs) ... all of which I think is our desired behavior?

I think dropping this file will break cookies and so on for dev environments.

**Comment by mjankowski** [comment]
Uh ... yes, probably.

I think once deleted the next time you restart your dev server it would no longer load from this yaml, so any previous sessions would be clobbered, but on that very restart the server would generate a `tmp/local_secret.txt`, which all subsequent restarts would read from and preserve session.

Seems like a negligible one-time price to pay to get rid of a deprecated feature?

**Comment by oneiros** [comment]
> I think dropping this file will break cookies and so on for dev environments.

Currently everyone in a development environment would use the hardcoded secret from `secrets.yml`. If we want to avoid any breakage we could just move it to `.env.development`, I guess?

> so any previous sessions would be clobbered

I believe it is a bit more than this, since the key is re-used for devise. So things like password reset would be affected as well. This can be annoying, especially since we have no way to know who is currently working on this code.

That being said:

> Seems like a negligible one-time price to pay to get rid of a deprecated feature?

I agree. This has the potential to be *really* annoying to some devs, but I suspect this annoyance would be very short term. Since the new handling in rails with the tempfile is a new default, going forward it will soon be surprising to new devs if we deviate from that for no apparent reason.

**Comment by mjankowski** [comment]
> If we want to avoid any breakage we could just move it to .env.development, I guess?

That's not a bad idea -- let me know if you want me to move the currently hard-coded dev/test (or just dev maybe?) values from the secrets yml into the env specific `.env` files to minimize breakage of things which use the secret key base value in this PR, or if we're fine w/ the one time issue.

**Comment by ClearlyClaire** [comment]
> > If we want to avoid any breakage we could just move it to .env.development, I guess?
> 
> That's not a bad idea -- let me know if you want me to move the currently hard-coded dev/test (or just dev maybe?) values from the secrets yml into the env specific `.env` files to minimize breakage of things which use the secret key base value in this PR, or if we're fine w/ the one time issue.

Looks like a good idea to me

**Comment by oneiros** [comment]
> I looked into this more - and I think the env approach won't actually work.

It seems it will in fact not. Sorry, looking at the docs / code  and current behavior I was under the impression it should, but a lot was changed there in recent versions and the docs seem to not be correct for all 7.1 versions :frowning_face: 

> I guess you could manually put the previously configured value into the tmp file ahead of a restart after pulling these changes if you really wanted to keep your local value.

I think this should work as well. If only we had a way to notify developers of this. Then I guess it would be fine.

In any case I think we should not try to fight rails and accept the new default behavior.

**Comment by mjankowski** [comment]
> In any case I think we should not try to fight rails and accept the new default behavior.

My take as well. I had some fears that we were going to need to either figure out how to use credentials in a way that works for multiple separate hosted apps or do some hack to insert something from the env there, but this seems pretty clean and in line with how we want it to work.

**Review by ClearlyClaire — APPROVED** [review]
I still worry about the impact on development environments but it should not cause any issue on production ones at least.

**Pull request merged**
