### PR TITLE
Open the media content in a modal window

### PR DESCRIPTION
**Pull request by pfm-eyesightjp**
Open the media content(image/movie) in a modal window instead of in a new window.

modal

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
Hmmm, I thought it already opens in a modal (on click)

When does media open in a new window?

**Comment by pfm-eyesightjp** [comment]
Hello.

Timeline in /web/getting-started is modal window.

Timeline in /@account is not modal window.
-> Change to modal window.

**Comment by beatrix-bitrot** [comment]
Ah thank you! That makes sense.

**Comment by Gargron** [comment]
This has become pretty outdated. Basically, I prefer not to duplicate JS logic between React and non-React. Recently I moved the images rendering logic from being in both Haml and React to just being in React, mounted from a static element. The correct way to make modals work on static pages would be to find a way to mount the ModalContainer as well, and for them to use the same store so the eventing works. But this is complicated and not critical.

**Pull request closed without merging**
