### PR TITLE
Remove the terms blacklist and whitelist from UX

### PR DESCRIPTION
**Pull request by Gargron**
Localization strings:

- "Whitelist mode" -> "Limited federation mode"
- "Blacklist e-mail domain" -> "Block e-mail domain"
- "Whitelist domain" -> "Allow domain for federation"

...And so on

Environment variables (backwards-compatible):

- `WHITELIST_MODE` -> `LIMITED_FEDERATION_MODE`
- `EMAIL_DOMAIN_BLACKLIST` -> `EMAIL_DOMAIN_DENYLIST`
- `EMAIL_DOMAIN_WHITELIST` -> `EMAIL_DOMAIN_ALLOWLIST`

tootctl:

- `tootctl domains purge --whitelist-mode` -> `tootctl domains purge --limited-federation-mode`

Removed badly maintained and no longer relevant .env.production.sample file

____

While I don't think that the terms blacklist and whitelist are racially charged in their etymologic origin, they're falling out of vogue in the industry and thinking about how they could be replaced led to what I believe are far more intuitive strings for end-users.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]
~~This will result in the loss of backward compatibility. The release should be done carefully.~~

Wrong. Forget about it.

**Comment by nightpool** [comment]
I thought the pull description specifically says that the env vars are
backwards compatible?

**Comment by koyuawsmbrtn** [comment]
No. No. No. Fuck off. I use Pleroma now.

**Comment by koyuawsmbrtn** [comment]
And such changes are making it harder for translators like me to get it right and sometimes having to making words longer. Thank you Gargron for introducing another useless change and giving me more work than I should do. I think I'll move back from Mastodon.

**Comment by Sasha-Sorokin** [comment]
What's your problem, @koyuawsmbrtn? For me it seems easier to translate “Block e-mail domain” than previous “Blacklist e-mail domain”. This is a very good change IMO.

**Comment by koyuawsmbrtn** [comment]
> What's your problem, @koyuawsmbrtn? For me it seems easier to translate “Block e-mail domain” than previous “Blacklist e-mail domain”. This is a very good change IMO.

Domain whitelisten > Erlaube Domäne für Föderation

**Comment by koyuawsmbrtn** [comment]
It's a UX change on the cost of the UI. It's useless and utter garbage. Sorry, but this is my stance and it will only change if somebody comes up with a better idea.

**Comment by Gargron** [comment]
You have artistic license for translations to other languages that make the most sense for the language. Nobody's asking for machine translations.

**Comment by SuperSandro2000** [comment]
@koyuawsmbrtn 

Domain für Föderation erlauben/verbieten bzw. white/black listen

**Comment by SuperSandro2000** [comment]
> Removed badly maintained and no longer relevant .env.production.sample file

The [doc is website](https://docs.joinmastodon.org/admin/config/) is equally not great. Do I need to grep trough the code to find relevant settings or how do you imagine this?

**Comment by Gargron** [comment]
> Domain whitelisten

That's a bad example by the way because "whitelisten" is not a German word at all, I don't think it would pass as a correct translation in Germany.

**Comment by Gargron** [comment]
> 
> 
> > Removed badly maintained and no longer relevant .env.production.sample file
> 
> The [doc is website](https://docs.joinmastodon.org/admin/config/) is equally not great. Do I need to grep trough the code to find relevant settings or how do you imagine this?

For a start we gotta copy over the info that was in the sample file there.

**Comment by SuperSandro2000** [comment]
> That's a bad example by the way because "whitelisten" is not a German word at all.

But it is very commonly used in German IT.

**Pull request merged**
