### PR TITLE
Add role badges on public

### LINKED ISSUE #19922: Staff badges missing on new instance
### Steps to reproduce the problem

1. Create a new instance at v4.0.0rc1 or higher
2. Create an admin user
3. View the admin profile and the badge will not be present

### Expected behaviour

"Admin" (or other custom text) badge should appear

### Actual behaviour

No staff badges appear

### Detailed description

We recently setup a new instance on v4.0.0rc1 a few days ago and we're not seeing any of the role badges being displayed on user profiles. We've double checked that the "Display role as badge on user profiles" option is checked on the role.

If need be, I can try upgrading the instance we have that predates v4.0.0 and see if that is affected or if the badges display there.

Affected instance / profile: https://pawb.fun/@crashdoom

### Specifications

- Mastodon v4.0.0rc2
- Ruby 3.0.4
- Safari Version 16.1 (18614.2.9.1.12)

### PR DESCRIPTION
**Pull request by cdp1337**
Fixes #19922

New account component for account badges and implemented on a few places on the public UI. Supports the public toggle and color definition from admin.

### CODE REVIEW

**Comment by cdp1337** [comment]
Yeah, I noticed the newline issue, but hadn't had a chance to commit the fix yet.

Screenshot from 2023-04-29 23-59-20
Screenshot from 2023-04-29 23-59-44
Screenshot from 2023-04-30 00-00-26

Also screenshots!  I posted them in #20031 but forgot to do so here, (I tend to forget that merge requests and issues are duplicates of each other for some weird reason...)

I didn't change the UI of the existing badges, just expanded support for `roles` on them, (other than adding the tags for admin-defined colours).

**Comment by ClearlyClaire** [comment]
> I didn't change the UI of the existing badges, just expanded support for `roles` on them, (other than adding the tags for admin-defined colours).

I meant the addition of badges in posts (your changes to `app/javascript/mastodon/features/status/components/detailed_status.jsx`, the second screenshot above) is the part that looks especially off and is probably better left off.

Otherwise, it looks good to me, but we'll wait for feedback from our designer.

**Comment by VityaSchel** [comment]
you are cool

**Comment by ClearlyClaire** [comment]
Hi! Thank you for your contribution, but following input from our designer, it has been implemented as #25649 and #26281

**Pull request closed without merging**
