### PR TITLE
Make it clearer what "no end-to-end encryption means.

### PR DESCRIPTION
**Pull request by Peetz0r**
I think many non-technical users don't understand the consequences of this text without further clarification. So I think it's a good idea to make it more explicit.

### CODE REVIEW

**Comment by shleeable** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAA. While this is true, it's not true... there is no interface, CLI or API to pull out the DMs.
You need to login to the DB and do additional work.... Maybe we can make use of the rails 7 encrypted tables in the future.

but as this is written is FUD.

https://guides.rubyonrails.org/active_record_encryption.html

**Comment by rinsuki** [comment]
fyi: it is not only server owner, (malicious) app developer that have a token with read:statuses permission of victim also can read their DM.

**Comment by Crashdoom** [comment]
To me, saying “can” read messages is a misnomer because of how difficult it is to do, otherwise the impression is that it’s as easy as any other moderation action.

Is it possible? Yes. Is it practical? Not really.

If this is a necessary change, “may be able to” fits better than “can”.

**Comment by Gargron** [comment]
I think the current message is descriptive enough and links to a "Learn more"

**Pull request closed without merging**
