### PR TITLE
feat(redux): Persist store

### PR DESCRIPTION
**Pull request by sorin-davidoi**
This does not really make sense on its own, but after #3052 is ready, this will enable the usage of the website offline: #3052 will cache the assets and this will cache the timelines.

Roadmap:
- [x] Lazy-load
- [ ] Fix hydration (do not overwrite the previous state)
- [x] Choose a better storage strategy - `localForage`?
- [ ] Set an upper bound on the size of the cache
- [x] Set a flag for statuses loaded from cache and show an indication that the information is outdated
- [x] Only enable for browsers with Service Worker support
- [ ] Handle errors - wipe the caches

### CODE REVIEW

**Comment by ykzts** [comment]
I think it is better to use `localForage`.

**Comment by sorin-davidoi** [comment]
I agree. Have to look into but, but it would be nice to only load the IndexedDB driver - not need for the others since this is only for browsers with Service Worker support.

**Comment by nolanlawson** [comment]
At this point I think it may make sense to directly use IndexedDB – localForage was written for a time when WebSQL still reasonably needed to be supported due to Safari/Android. Another alternative is [Dexie](http://dexie.org/).

Performance-wise I'd be a bit concerned about stuffing the entire redux store into IndexedDB as a single document – can we break it up, or can we confirm whether or not the object is prohibitively large to insert as one single object?

**Comment by sorin-davidoi** [comment]
> At this point I think it may make sense to directly use IndexedDB

👍 

> Performance-wise I'd be a bit concerned about stuffing the entire redux store into IndexedDB as a single document

I don't think that is the case. Have to check, but I think that it creates a document for each of the four store states.

**Comment by Gargron** [comment]
If you manage to implement this with the upper bound on cache size, you will also close #787

**Comment by sorin-davidoi** [comment]
The cache size I'm referring to is the size of the serialized store in IndexDB. This won't trim the in-memory store while the page is open - another approach is needed for that.

**Pull request closed without merging**
