### PR TITLE
Replace "reblogging" with "boosting" in privacy policy

### PR DESCRIPTION
**Pull request by erbridge**
"Boost" is the terminology generally used across the service, so it makes sense to match it in the privacy policy.

Relates to #19829

### CODE REVIEW

**Comment by Gargron** [comment]
I'm not entirely comfortable with flavour language being used in the legal document. "Boost" is flavour language.

**Comment by erbridge** [comment]
"Boost" is the language everyone uses to describe the action. "Reblog" is also flavour language (Tumblr's). Clarity of language is important, and it doesn't make a lot of sense to mix the terminology to me. But if you think this is the wrong change, feel free to close the PR - it's not a major issue.

**Review by ghost — APPROVED** [review]

**Comment by ThisIsMissEm** [comment]
Given the UI and API refer to this activity as "boosting", yet the documentation does use mixed language: https://docs.joinmastodon.org/methods/statuses/#boost

> Reshare a status on your own profile.

Should probably read:

> Boosts a status to share it to your followers and on your own profile.

 Perhaps the `/api/v1/statuses/:id/reblog` is named so out of legacy, and an alias could be introduced of `/api/v1/statuses/:id/boost`?

**Comment by trwnh** [comment]
> Given the UI and API refer to this activity as "boosting"

the API actually refers to it as `reblog`, not `boost`. the codebase also uses `reblog` throughout. the technical term as far as mastodon is concerned is `reblog`. it's only `boost` in the UI

**Comment by gunchleoc** [comment]
The way legal documents tend to handle clarification of terminology is to use parentheses and quotes, so we could have something like

> The action of reblogging  (“boosting”, “resharing”) or

**Comment by mjankowski** [comment]
Closing due to a) lack of consensus on change, b) text customization is now in site setting instead of i18n, and would need rebase.

**Pull request closed without merging**
