### PR TITLE
Refactor resizeImage method

### PR DESCRIPTION
**Pull request by ykzts**
- Use `URL.createObjectURL` (replace from `FileReader`)
- Use `HTMLCanvasElement.prototype.toBlob` (replace from `HTMLCanvasElement.prototype.toDataURL`)
- Use `Promise` (replace callback interface)

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by jebuskrust** [comment]
Not sure why, but if you're trying to figure out why images aren't uploading [i'm on mobile at this time]. Reverting this commit fixes everything. 

Have an awesome day

**Comment by Gargron** [comment]
:weary: :weary: :weary:

**Comment by ykzts** [comment]
@jebuskrust Please tell me more detailed information.

I am confirming that there is no problem with iOS's Safari.

**Comment by jebuskrust** [comment]
image

Sorry to come back to this guy..  Been a busy week... This is the error that I get..

Thought it was something that I had done. The uploading DOES work but only allows me to upload gifs and mp4's.. Every other file type seems to get rejected.. However, When I revert this commit, everything's magically works.

Sorry again! But there's some information for you.

**Comment by jebuskrust** [comment]
Hmm looks like I may have a strict CSP policy. rofl

Thanks again.

Refused to load the image 'blob:https://lab.testsite.testdomain/93e6554f-7235-4750-8b72-0e74d98ff50e' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Pull request merged**
