### PR TITLE
Fix account note translations following #14208

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by Sasha-Sorokin** [comment]
Kind of duplicate of #14250?

**Comment by ThibG** [comment]
I fail to see how they are related, this PR is about copying two changed source strings to their untranslated counterparts in various translation files.

**Comment by Sasha-Sorokin** [comment]
I see, that's why @mayaeh [asks](https://github.com/tootsuite/mastodon/pull/14250#issuecomment-655453138) whether they should or not include string updates to other languages than English. If they do so, it will supersede this PR as well as update other strings and finally push new strings to Crowdin. That's why *kind of*.

**Comment by mayaeh** [comment]
I think this PR is a lot better than what I was thinking of adding.
What I was thinking of adding in my PR was just doing `yarn manage: translations`.
Therefore, the update of "account.account_note_header" cannot be fixed in my PR.

**Comment by ThibG** [comment]
@Sasha-Sorokin  Oh. No, I don't think it would, because their PR is about adding new strings, but this one is about an existing string which old version is already present in the translation files, so I think that PR would just leave them untouched.

**Comment by Sasha-Sorokin** [comment]
@mayaeh @ThibG got it! Waiting for both to be merged then :+1:

**Pull request closed without merging**
