### PR TITLE
fix: `s3_force_single_request` not parsed

### PR DESCRIPTION
**Pull request by HolgerHuo**
Fix issue https://github.com/mastodon/mastodon/issues/16822.
The [original patch](https://github.com/mastodon/mastodon/pull/16866) did not work as the environment file could not be parsed there.

### CODE REVIEW

**Review by Gargron — COMMENTED** [review]
I'm not sure why the original code doesn't just check the variables dynamically instead of conditionally monkey-patching. That seems far less predictable...

**Comment by HolgerHuo** [comment]
I guess it might because that this is not a common issue as most storage providers are fully s3-compatible and we were waiting for kt-paperclip to support single request natively?
https://github.com/mastodon/mastodon/pull/16866

**Comment by Gargron** [comment]
I realize, I mean that the monkey-patched code could check the env variables and then either perform `super` or the custom code.

**Comment by HolgerHuo** [comment]
I see that. I think we should wait for Claire's interpretation on this.

**Comment by ClearlyClaire** [comment]
Why would the original patch not work? The monkey-patching is conditional in part because iirc loading the S3 lib itself is conditional on the environment variables.

**Comment by HolgerHuo** [comment]
> 

That's it. As this is only a temporary patch for a temporary issue it's ok to load it only from environment variables

**Comment by ClearlyClaire** [comment]
I mean, the fact it ignores the `.env.production` is confusing and a bug, having the code live in the same place `aws-sdk-s3` is loaded makes sense. Your change is fine, but I'd also be fine with the monkey-patching being done in the `if ENV['S3_ENABLED'] == 'true'` block and checking `ENV['S3_FORCE_SINGLE_REQUEST']` in `copy_to_local_file` itself.

**Comment by HolgerHuo** [comment]
Sorry, but could you please elaborate that? I'm not quite sure about how to do that as I don't usually code in Ruby so I might need your help here. I think `copy_to_local_file` belongs to `kt-paperclip` so how can we check for `S3_FORCE_SINGLE_REQUEST` in that function alone?

**Comment by ClearlyClaire** [comment]
I mean, you were discussing why conditionally monkey-patch `kt-paperclip`.

You need to monkey-patch `Paperclip::Storage::S3` conditionally on `ENV['S3_ENABLED']` because this only gets conditionally loaded.

But instead of patching it conditionally on `ENV['S3_FORCE_SINGLE_REQUEST']`, you could move that check into the monkey-patched `copy_to_local_file` by doing something like `return super unless ENV['S3_FORCE_SINGLE_REQUEST'] == 'true'`.

Both options (your current PR, and moving the env variable check inside the method) make sense to me, I have no preference.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by HolgerHuo** [comment]
I understand it. Thanks for your explanation! 
I'm still getting familiar with Mastodon's code structure and may not have a full comprehension of the complete application so you may change the commit to whatever is best for future implementation.

**Pull request merged**
