### PR TITLE
Add pry-rails and pry-byebug gems for debugging in dev and test

### PR DESCRIPTION
**Pull request by KevinBongart**
Extracted from https://github.com/mastodon/mastodon/pull/27982#pullrequestreview-1738724813, I thought other contributors of this repo could benefit from these helpful debugging tools:

- https://github.com/pry/pry-rails as a powerful Ruby REPL
- https://github.com/deivid-rodriguez/pry-byebug for easily navigating between frames

In case this helps anyone, I put the following in a `~/.pryrc` file to navigate the Ruby code:

```ruby
Pry.commands.alias_command 'c', 'continue'
Pry.commands.alias_command 'f', 'finish'
Pry.commands.alias_command 'n', 'next'
Pry.commands.alias_command 's', 'step'
Pry.commands.alias_command 'q', 'quit'
Pry.commands.alias_command 'w', 'whereami'
Pry.history.load
```

### CODE REVIEW

**Review by mjankowski — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
I have no strong opinion either way, but this was removed earlier this year in #23884.

**Comment by KevinBongart** [comment]
Thanks for linking to @nschonni's PR, this is useful context.

If no one has a strong objection, I recommend merging this PR as, IMO, `pry` provides more value to Mastodon maintainers than it would take. It's the first tool I reached for when familiarizing myself with the codebase yesterday and debugging API behavior.

The argument that `pry-rails` is no longer maintained is certainly fair, but I'm not aware of it being a source of issues. It remains an excellent way to debug Ruby code and I'm not sure there's another good debugging REPL we could use instead. It would be easy to remove if any issue arises from it and, by being in the Gemfile, it creates some exposure to potential future maintainers of `pry-rails`.

If that helps, I could add a comment in the Gemfile along those lines: "As of 2021, `pry-rails` is no longer maintained. Remove/replace it if it starts causing any issues."

(Another option: I can just add those gems to my Gemfile locally, run `bundle` and make sure I don't commit those changes. That's not very dev-friendly but it would work.)

**Comment by ThisIsMissEm** [comment]
Heh, I did the debug gem in https://github.com/mastodon/mastodon/pull/27960

I've no strong feelings any particular way, just as long as it's possible to interactively debug tests & code in development

**Comment by ClearlyClaire** [comment]
@KevinBongart any reason to prefer `pry-rails` and `pry-byebug` over the `debug` gem as suggested in #27960? (I have personally used neither of those)

**Comment by renchap** [comment]
`pry-rails` is deprecated, and  `byebug` is no longer maintained. The new `debug` gem is the official replacement.

`irb` is also being improved a lot lately (work led by Shopify's developer experience team), and they recommend using `irb` in the `Gemfile` for projects to get the latest version.

I would strongly prefer sticking with the lastest `irb` + `debug` gems (as Rails is doing) than re-adding `pry` and associated gems.

**Comment by renchap** [comment]
Closing this in favour of the recent `irb` + `debug` gem from #27960

**Comment by KevinBongart** [comment]
Oh, I missed the recent development in IRB and `debug`! Yes, let's definitely use these instead of `pry`. (I'll also switch my own apps)

**Pull request closed without merging**
