### PR TITLE
Fix incorrect french spelling

### PR DESCRIPTION
**Pull request by mleduque**

### CODE REVIEW

**Comment by nightpool** [comment]
cc @Sylvhem

**Review by renatolond — CHANGES_REQUESTED** [review]
I don't think there's any incorrect french spelling. The french is spelling is intentionally gender neutral.

**Comment by ThibG** [comment]
As @renatolond, this is correct and an intentional gender-neutral form. Closing.

**Comment by mleduque** [comment]
Sorry, no, I don't think you'll find anyy reference grammar book that
consider this correct.

**Comment by Fl0ux** [comment]
Please fix french translations, they are incorrect and unreadable.

**Comment by wxcafe** [comment]
Please fuck off (also, people who still have moderator access on this repo: please close this discussion thread)

**Comment by baudc** [comment]
Fix it. French language must comply with grammatical and syntactic rules. It's awful and unreadable.

**Pull request closed without merging**
