### PR TITLE
Surround mid-text display names with bdi tags

### LINKED ISSUE #1095: Need defensive measures against Unicode direction overrides
If you put U+202E RIGHT-TO-LEFT OVERRIDE in your display name, the effects spill out of the display name field and affect other parts of the UI, as shown here:

screen shot of the bug described above

There are probably a bunch of other closely-related bugs.

(Inspired by a similar bug in Twitter found by [@0xabad1dea](https://twitter.com/0xabad1dea).)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #1095

See https://github.com/tootsuite/mastodon/issues/1095#issuecomment-357559460

### CODE REVIEW

**Comment by wxcafe** [comment]
:/

**Comment by Sylvhem** [comment]
*pat, pat* @wxcafe

**Comment by joyeusenoelle** [comment]
Suggestion: Could this be a per-user toggle, so people bothered by the UI interference can turn it off for their displays without affecting anyone else?

**Comment by lanodan** [comment]
> per-user toggle
Appart for keeping the “wxcafe glitch” what is the use case? I think this would add ~useless code.

**Comment by nightpool** [comment]
I'm not against this in principle, but you'll have to find someone else to approve it :P

**Comment by nightpool** [comment]
Push notifications are also affected iirc

**Pull request merged**
