### PR TITLE
Add API endpoint to list followed users whose reblogs are hidden

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by ThibG** [comment]
This may be useful to know which users you're hiding boosts from, as there is currently no way to know that except by manually checking every follower.

**Comment by Gargron** [comment]
Eh, that seems kind of too specific? A whole API just for a single option?

**Comment by ThibG** [comment]
Well, seeing your favourites is also one API endpoint for a single option… the server must communicate those informations somehow… the alternative, I guess, would be an option to `/api/v1/following_accounts` but that is very awkward because the option would only apply to when the requested account is the account of the person logged in

**Comment by Gargron** [comment]
The difference is that "favourites" is a primary function while "hide reblogs" is an option on the primary "follows" function. Perhaps it would make sense within the larger goal of making the "relationship manager" become possible through the API.

**Pull request closed without merging**
