### PR TITLE
WIP #1337 Support JRuby

### PR DESCRIPTION
**Pull request by fapdash**
Started working on this. Since my experience with JRuby is limited, any help is highly appreciated.

### CODE REVIEW

**Comment by fap-** [comment]
Currently the database schema can't be set up properly, I'm not sure if this is a problem with [activerecord-jdbc-adapter](https://github.com/jruby/activerecord-jdbc-adapter) (ActiveRecord 5.0 support is still WIP) or if we can do something about it.

```
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "statuses" are not allowed
  Position: 53: CREATE TABLE "statuses" ("id" bigserial PRIMARY KEY PRIMARY KEY  PRIMARY KEY, "uri" character varying, "account_id" integer NOT NULL, "text" text DEFAULT '' NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "in_reply_to_id" bigint, "reblog_of_id" bigint, "url" character varying, "sensitive" boolean DEFAULT 'f', "visibility" integer DEFAULT 0 NOT NULL, "in_reply_to_account_id" integer, "application_id" integer, "spoiler_text" text DEFAULT '' NOT NULL, "reply" boolean DEFAULT 'f', "favourites_count" integer DEFAULT 0 NOT NULL, "reblogs_count" integer DEFAULT 0 NOT NULL)
arjdbc/jdbc/RubyJdbcConnection.java:555:in `execute'
/home/mastodon/mastodon/db/schema.rb:229:in `block in (root)'
/home/mastodon/mastodon/db/schema.rb:13:in `<main>'
bin/rails:4:in `<main>'
ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "statuses" are not allowed
  Position: 53
arjdbc/jdbc/RubyJdbcConnection.java:555:in `execute'
/home/mastodon/mastodon/db/schema.rb:229:in `block in (root)'
/home/mastodon/mastodon/db/schema.rb:13:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by Gargron** [comment]
This may be a helpful resource: <https://devcenter.heroku.com/articles/moving-an-existing-rails-app-to-run-on-jruby>

**Comment by fap-** [comment]
@Gargron Thank you, I had already read that.
We probably have to wait until [activerecord-jdbc-adapter](https://github.com/jruby/activerecord-jdbc-adapter) supports AR5 with postgres.
SQLite integration might already work but Mastodons schema seems to be quite postgres specific so I think it's just not worth the trouble, just to get it working with JRuby NOW.
If not someone else comes up with a smart idea we'll just have to wait.

**Comment by Gargron** [comment]
Is it possible to use a different pg gem, maybe?

**Comment by fap-** [comment]
This seems to be the only alternative and is neither compatible with Rails 5 nor maintained: https://github.com/headius/jruby-pg/issues/25

There is a working adapter but only for Oracle DB: https://github.com/rsim/oracle-enhanced#rails-50
=\

**Comment by Gargron** [comment]
Alright, I suggest putting this on hold until JRuby catches up with Rails 5, then. Are you okay with that?

**Comment by fap-** [comment]
Sure. :+1:

**Comment by gouessej** [comment]
I haven't found any updated roadmap for JRuby, do you know when it's planned to support Rails 5? Have you ever tried to use Warbler to make a war for Mastodon and deploy it on Jetty?

**Pull request closed without merging**
