### PR TITLE
Fix restored words from "toot" to "status"

### PR DESCRIPTION
**Pull request by mayaeh**
This PR returns words returned in #13749  again.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ThibG** [comment]
How did those strings get reverted…

**Comment by Gargron** [comment]
> 
> 
> How did those strings get reverted…

Resolving merge conflicts :pensive:

**Comment by ThibG** [comment]
But, that means Crowdin introduced changes in the source strings? :thinking:

**Comment by Gargron** [comment]
No... I don't think Crowdin writes to the `en` files, I just did a `git checkout HEAD -- app/javascript/mastodon/locales` to solve the multitude of conflicts during `git merge`, and since `HEAD` had the outdated `en.json` file, this is what happened.

**Pull request merged**
