### PR TITLE
Remove unmaintained `nsa` gem

### PR DESCRIPTION
**Pull request by mjankowski**
Background on Rails 7 PR: https://github.com/mastodon/mastodon/pull/24241#issuecomment-1575672474

Question here before merge: should I go ahead and just remove the entirety of this statsd config file for now? Seems somewhat pointless w/out the NSA init...

### CODE REVIEW

**Review by Gargron — APPROVED** [review]
Yes, probably remove the file

**Comment by mjankowski** [comment]
Pushed again to remove statsd config file entirely.

**Comment by renchap** [comment]
This will require a specific changelog entry, and a documentation update.

**Comment by ShadowJonathan** [comment]
This removed statsd support, please add this to a changelog entry.

**Pull request merged**
