### PR TITLE
Upgrade docker-compose to postgres v16

### PR DESCRIPTION
**Pull request by melroy89**
Using Postgres v16 tag.

Edit: updated from 15 to 16.

### CODE REVIEW

**Comment by ashleyhull-versent** [comment]
Please no.

**Comment by shleeable** [comment]
Please no.

**Comment by danger89** [comment]
Ow why? I'm running mastodon fine on v15

**Comment by mohe2015** [comment]
I think you would need to migrate data. Otherwise this wouldnt work

**Comment by danger89** [comment]
But that would be the same for v13 to v14 migration. But if people use v15 by default now, new people won't need to upgrade at all when setting up a new instance themselves.

**Comment by mohe2015** [comment]
I can't comment on the line because GitHub is stupid but https://github.com/mastodon/mastodon/pull/21059/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L12 needs changing too I think. Also I think release notes would be nice but I don't know how this was done in the past.

**Comment by danger89** [comment]
> I can't comment on the line because GitHub is stupid but https://github.com/mastodon/mastodon/pull/21059/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L12 needs changing too I think. Also I think release notes would be nice but I don't know how this was done in the past.

Your link is not pointing to something you think it points to I guess.. I'm confused now.

**Comment by quardbreak** [comment]
@danger89 looks like line of code ref don't work well with diff-files from pull requests. I believe @mohe2015 pointed to the line 12 from the same file you edited.

**Comment by danger89** [comment]
> @danger89 looks like line of code ref don't work well with diff-files from pull requests. I believe @mohe2015 pointed to the line 12 from the same file you edited.

AH indeed. We could rename this to `./postgres15` as well indeed. That being said. For existing instances running on PostgreSQL 14 we can document a migration step.

I assume this is not the first time Mastodon is upgrading major releases of database dependencies? Could it be documented here: https://docs.joinmastodon.org/

**Comment by shleeable** [comment]
This deserves a better response. There was a guide included in the previous upgrade from postgres 9 to 14, and we can follow that guide for any future upgrades. https://github.com/mastodon/mastodon/pull/16947

I have no problem upgrading to v14 to v16 for example.. but stability is worth it.. the EOL for 14 is 30 Sep 2026.

**Comment by shleeable** [comment]
If we want to chase the dragon and always use the latest postgres,.. we just need to make it manageable.

**Comment by melroy89** [comment]
Good idea. V16 is out. 😎

**Pull request closed without merging**
