### PR TITLE
Increase poll option length limit to 100 chars, number of options to 5

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by Gargron** [comment]
You've pointed out that even at 25 characters the options are sometimes longer than the bar. Previously that led to one-letter ellipsis, but now it leads to line breaks and thicker bars. Increasing that to 100 characters will ensure that the problem will become widespread and the uglier multiline inconsistent-height bars will be a common occurence. As I've mentioned that looks untidy and unprofessional and we should avoid showing it when possible.

**Comment by ThibG** [comment]
Would something like the following make you reconsider?
Peek 16-09-2019 12-29

Alternative design
image

**Comment by Gargron** [comment]
@ThibG Could clicking on the poll open the poll in a modal?

**Comment by ThibG** [comment]
@Gargron honestly that would just be worse…? The modal would display it in a way similar to the proposed solutions and it would not be more intuitive or natural in any way?

**Pull request closed without merging**
