### PR TITLE
helm: bump default image tag to v3.2.0

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Review by Gargron — COMMENTED** [review]
Can this value by fed from the somewhere else, say, our version.rb?

**Comment by SuperSandro2000** [comment]
Probably not.

**Comment by ykzts** [comment]
> Can this value by fed from the somewhere else, say, our version.rb?

There is no way to embed the version except to generate Yaml in a script. Maybe.

**Comment by dunn** [comment]
The alternative would be to default to the `latest` Docker tag, and add a comment to the effect of 'consider setting this explicitly to the version you want to deploy.'

**Pull request merged**
