### PR TITLE
Enable `Rails/Output` in `spec/` dir

### PR DESCRIPTION
**Pull request by mjankowski**
Would have caught https://github.com/mastodon/mastodon/pull/31886 I believe.

### CODE REVIEW

**Comment by nschonni** [comment]
Would it be better to just remove https://github.com/mastodon/mastodon/blob/main/spec/controllers/.rubocop.yml

**Comment by mjankowski** [comment]
> Would it be better to just remove https://github.com/mastodon/mastodon/blob/main/spec/controllers/.rubocop.yml

I'm not sure how that's relevant...?

The default values here - https://github.com/rubocop/rubocop-rails/blob/v2.26.1/config/default.yml#L730-L734 - don't include `spec...` so I'm adding it in.

**Comment by nschonni** [comment]
Got it, it was more around the Inheritance part. I was reading it as part of the reason why it wasn't caught, but you're saying it was just because the rule doesn't apply to those files rather than being an inheritance issue with the override

**Comment by mjankowski** [comment]
Yup, exactly -- there are some separate situations where we do have a weird interaction with some of those nested `.rubocop.yml` override files and I think we may have accidentally disabled some rules (I recall this in a prior PR maybe related to db/migrations stuff?) but forget which off top of my head.

In this case though it's just a normal config change to add to base set.

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
