### PR TITLE
Reduce vulnerabilities

### PR DESCRIPTION
**Pull request by EdgarPsda**
### Important Note on the react-router-dom Upgrade
Hi team,

I wanted to inform you that this PR includes an upgrade to react-router-dom to version 6. It’s important to note that there are significant changes in the API and behavior of this library compared to version 5.

Key changes to consider:

Using <Routes> instead of <Switch>: Routes must now be defined within the <Routes> component, and it’s no longer necessary to specify the exact prop since all routes are exact by default.

Change in the prop for rendering components: The component prop has been replaced by element, which means we should pass components as JSX.

Redirections: The way to redirect between routes has changed from <Redirect> to <Navigate>.

Nested Routes: Nested routes are more intuitive and are defined directly within the parent route.

New Hooks: New hooks have been introduced that can be useful, such as useRoutes.

It’s advisable to review the migration documentation to familiarize yourself with these changes and ensure our code continues to function correctly.

If you have any questions or need help adapting the code, feel free to reach out.

Thank you!

### CODE REVIEW

**Comment by shleeable** [comment]
Highly recommend splitting that Regex into it's own PR...

The marjor package version upgrades are kind of all known about with plans for upgrading.. like webpack is due to be replaced instead of upgraded.

**Comment by Gargron** [comment]
Is this PR AI-generated?

**Comment by EdgarPsda** [comment]
@shleeable okay, I wil do that.

**Comment by EdgarPsda** [comment]
> Is this PR AI-generated?

It's generated using Snyk.

**Comment by EdgarPsda** [comment]
I will close this PR to create a new one with issolated changes.

**Pull request closed without merging**
