### PR TITLE
Fix RedownloadMediaWorker

### PR DESCRIPTION
**Pull request by noellabo**

### CODE REVIEW

**Comment by ThibG** [comment]
Oh! Very good catch!
From what I understand, `Remotable#reset_#{attr}!` would only work reliably if the including class has a database-backed `#{attr}_remote_url` attribute, which is the case of every `Remotable` attribute except `MediaAttachment`, which has a `remote_url` instead of `file_remote_url`.

I guess the cleanest solution to this would be to rename `remote_url` to `file_remote_url`, but that would require a painful database migration.

Your solution is fine, but `lib/mastodon/media_cli.rb` needs to be fixed too.

An alternative might be to change `Remotable`'s `alt_method_name` to `url = has_attribute?(attribute_name) ? self[attribute_name] : self['remote_url']`

**Comment by noellabo** [comment]
Thank you! I will change to the method of suggestion.

**Comment by Gargron** [comment]
> I guess the cleanest solution to this would be to rename `remote_url` to `file_remote_url`, but that would require a painful database migration.

Or just define an alias on the MediaAttachment model

**Comment by ThibG** [comment]
> Or just define an alias on the MediaAttachment model

Would it work correctly with the `self[attribute]` and `attribute=` method?

**Comment by Gargron** [comment]
Oh.. No, it wouldn't. But then maybe Remotable should be using methods and not attributes directly anyway to allow more flexibility. Another option is overriding the `reset_file!` method on MediaAttachment to make it do the right thing.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
