### PR TITLE
Use Ruby 2.7.2

### PR DESCRIPTION
**Pull request by zunda**
`thwait` and `e2mmap` are no longer needed in Gemfile. Gems properly require those.

### CODE REVIEW

**Comment by ThibG** [comment]
I am not against that, and I actually use Ruby 2.7.2 as provided by my distribution, but some of our dependencies are still using deprecated language constructs, resulting in pretty polluted logs.

**Comment by nightpool** [comment]
Ruby 2.7 has incompatibilities in keyword arguments also, right? So there could be a bug introduced because of the change in how keyword arguments is handled between versions

**Comment by zunda** [comment]
Thanks for comments!

[Deprecation warnings are turned off by default on 2.7.2](https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/) so logs should be cleaner than 2.7.0 and 2.7.1. Running `rspec`, the code generated warnings at only two lines:

```
$ bundle exec rspec 2>/tmp/warnings.txt
  :
3026 examples, 0 failures, 23 pending

Randomized with seed 40915
Coverage report generated for RSpec to .../mastodon/coverage. 13789 / 20177 LOC (68.34%) covered.
$ sort -u /tmp/warnings.txt
.../vendor/bundle/ruby/2.7.0/gems/cld3-3.3.0/lib/cld3.rb:91: warning: rb_safe_level will be removed in Ruby 3.0
.../vendor/bundle/ruby/2.7.0/gems/rotp-2.1.2/lib/rotp/totp.rb:56: warning: URI.escape is obsolete
```

I`d say the Mastodon code is pretty compatible with ruby-2.7.2. `rspec` completes successfully. My server has been on ruby-2.7.2 since October 2nd. I haven't seen any problem due to the ruby version, but yeah there are features I have never used on my single user server.

**Comment by shleeable** [comment]
rotp 2.1.2 is from april 2016.. there is a version 6.2.0 https://rubygems.org/gems/rotp/versions

**Comment by shleeable** [comment]
image
Working without issue with this PR + the nodejs v14 PR for the last few hours.... we'll come back tomorrow

**Comment by shleeable** [comment]
LGTM. Tested without issue so far.

**Comment by shleeable** [comment]
LGTM. Tested without issue so far. Merge away.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
