### PR TITLE
Add a config file for easily find or change some settings like status max chars

### LINKED ISSUE #25546: Singular Config for configuration
### Pitch

Hello Everyone, 

I am wondering if we could have a global config that would be used for all the possible variables on building the project when updating. 

### Motivation

this would be a single config file which includes all the limits and options e.g. image size, video sizes, toot length, sign up status. keys and api's, block lists etc so settings can be saved from a single file or setup via that one location. 

**Priority:** Low 
**Scope:** non-impacting

### PR DESCRIPTION
**Pull request by sinoru**
Add a config file `config/mastodon.yml`

At this time, This will contains:
- `accounts.max_featured_tags`
- `statuses.max_characters`
- `statuses.url_placeholder_chars`
- `media_attachments.file_size_limit.image`
- `media_attachments.file_size_limit.video`
- `media_attachments.max_description_length`
- `media_attachments.mime_types`
- `polls.max_options`
- `polls.max_option_characters`

And will be more on later PRs.

This will fixes #25546, #12265 partially.
I found #5697 PR.
but this PR will only introduces a config file, not env. So It can not be easily switching value, not encouraging to change it.
But there are already many servers which fork and change these values. For those, this will make them comfortable.

So this is trying to make middle ground:
1. Not easily configurable, should fork to change it.
2. But, Can find and replace it easily.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Mastodon configuration mostly works either through environment variables (loaded from `.env.production`) or from the admin interface. I am not sure there is any benefit in introducing a third way.

**Comment by sinoru** [comment]
> Mastodon configuration mostly works either through environment variables (loaded from `.env.production`) or from the admin interface. I am not sure there is any benefit in introducing a third way.

@ClearlyClaire I agree with that, but Gargron doesn't seem to agree on changing things like the status character limit easily (https://github.com/mastodon/mastodon/pull/5697#issuecomment-345078582), so I used third way, and I think it would be better to manage constants in one file than multiple codes.

**Comment by ClearlyClaire** [comment]
I don't know whether Gargron's position has changed on this, but I do not think introducing a third location for settings.

**Comment by sinoru** [comment]
> I don't know whether Gargron's position has changed on this, but I do not think introducing a third location for settings would change his mind.

@ClearlyClaire
In my opinion, it is inefficient to refer to or modify const values that are hard coded in various files or codes in development. But everything in .env would be really vast to put all the constant values.
So I think it's better to leave the parts that can be easily set in .env and manage the rest of the constants through `mastodon.yml` config. What I think about in the future is to include every constants like file size limit and image resolution size, etc.

**Comment by sinoru** [comment]
I added some values for demonstration, examples.
This is not definitely easily configurable values. But, this will make minor server admin happy for who do already did fork for customize this values, can make them easily change, easily merge upstream.

**Comment by ClearlyClaire** [comment]
Again, I don't think there is a reason to not use env variables for those settings. The fact those limits cannot be changed without changing the source code is on purpose (even though that is something I personally disagree with), so introducing a new config file will not make the changes more likely to be merged.

**Comment by mjankowski** [comment]
Closing due to sheer age, lack of rebase, and my suspicion based on previous feedback that this will not be merged.

Separately - we are nudging some config values into yml files via rails `config_for` mechanism. This might accomplish parts of this as an unintentional side effect.

**Pull request closed without merging**
