### PR TITLE
Use buildx functions for faster build

### PR DESCRIPTION
**Pull request by inductor**
Ref. https://docs.docker.com/engine/reference/builder/#copy---link
cc: @unasuke

### CODE REVIEW

**Comment by inductor** [comment]
I'm sure the web ui test is irrelevant for this PR. Wondering why it fails though.

**Comment by ykzts** [comment]
> I'm sure the web ui test is irrelevant for this PR. Wondering why it fails though.

Fixed in #20677.

**Comment by unasuke** [comment]
This changes looks good to me, and my local build passed. Why actions build failed...

**Comment by inductor** [comment]
test passed.

@ykzts kindly give me an advice for the next step

**Review by ykzts — APPROVED** [review]

**Comment by inductor** [comment]
Node.js and Ruby installation could be separated in this Dockerfile so that the build will become even faster 🤔

**Comment by inductor** [comment]
https://github.com/moby/buildkit/issues/2987
:|

**Comment by ineffyble** [comment]
Will need to have conflicts resolved with #20678 - depending on which is merged first, conflicts will either occur here or there.

**Comment by inductor** [comment]
@ineffyble happy to help them if this gets merged first.

**Pull request merged**
