### PR TITLE
Fix crash in alias settings page

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by joenepraat** [comment]
Great it's a bug and fixed. How to cherry-pick this @ClearlyClaire @Gargron, so my new users can migrate normally?

**Comment by joenepraat** [comment]
Oh I see it's only adding a few lines to a file. Nevermind the previous comment.

**Comment by ElectricDryad** [comment]
Forgive me if this is covered somewhere, but once the fix is implemented, is there a way to strip the alias info from the users who tried to enter one before the fix? Should this be necessary?

**Comment by ClearlyClaire** [comment]
> Forgive me if this is covered somewhere, but once the fix is implemented, is there a way to strip the alias info from the users who tried to enter one before the fix?

Yes

> Should this be necessary?

No, the bug is about displaying aliases, there is nothing wrong with the alias itself. If an alias is incorrect, it can be removed as intended, just like before this bug started occurring.

**Pull request merged**
