### PR TITLE
Fix typo in handler function call name

### PR DESCRIPTION
**Pull request by nschonni**
Did a pass with cSpell to see if there was much. Mostly some minor things in comments/tests, but this was a functional issue, so I kept it separate from the other changes

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by nschonni** [comment]
@ClearlyClaire I noticed a few of mine got stuck on the `build-and-test` CI job. Is there anything I need to do, or is that something that needs to manually kicked off by a maintainer?

**Comment by nschonni** [comment]
Not a problem, I'll try to rebase later and see if the CI likes that 😄

**Comment by connorshea** [comment]
@nschonni @ClearlyClaire FYI since I had this exact same problem: what's probably causing this is that you created your own CircleCI project for mastodon (e.g. `nschonni/mastodon`), and for whatever reason that confuses CircleCI and prevents it from running the CI job in the main `mastodon/mastodon` project, which is what the status checks actually want to see. So try going into Circle, deleting the mastodon project under your namespace, and then merge `main` into your branch to trigger a new run of CI.

**Comment by nschonni** [comment]
Thanks for the suggestion. I went and checked to see if that was the case, but I ended up remembering that I had deleted my CircleCI account some time ago because I was getting spam notifications that they wouldn't block properly.

**Comment by nschonni** [comment]
I definitely seems like there is some sort of account confusion though

> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

**Comment by connorshea** [comment]
ah, yeah in that case you need a CircleCI account connected

**Comment by nschonni** [comment]
Looks like configuring it and rebasing got it running

**Pull request merged**
