### PR TITLE
Update en.jsx - "What's on your mind" string

### PR DESCRIPTION
**Pull request by pappasadrian**
as suggested by @rowletbot@octodon.social
https://octodon.social/web/statuses/106228

### CODE REVIEW

**Comment by Gargron** [comment]
I feel like that's way too informal... Very very unsure about this. For the record, you didn't link to the permalink (e.g. the link that the relative time points to) so we can't open it without an octodon.social account.

**Review by yiskah — CHANGES_REQUESTED** [review]
buddy? How does this help? I can see "What's" versus "what is" but "buddy" is very unncecessary

**Comment by expenses** [comment]
I think the default is fine as it is. You can change the string on your own instance if you want to though.

**Comment by yiskah** [comment]
Expenses makes a good point. I'm going to close this as-is.

**Pull request closed without merging**
