### PR TITLE
Fix spelling of "log in" and "log out" verbs

### PR DESCRIPTION
**Pull request by valtlai**
*Log in* and *log out* should be written as two words when they are used as verbs. *Login* and *logout* are nouns.

### CODE REVIEW

**Comment by BoFFire** [comment]
Hello @valtlai 

If those strings are translatable, it is better to review them on Crowdin translation platform.

**Comment by valtlai** [comment]
Ok, the `en-GB` strings can be translated there, but what about the source language `en`?

**Comment by BoFFire** [comment]
@valtlai Same for source language `en`, you can open issue related to `source language string` on Crowdin :) It will be marked as `issue` and will remain until someone resolves it on Crowdin then will be marked as resolved and will be synched to Git :)

**Comment by valtlai** [comment]
@BoFFire Thanks for the help. I’ve now opened the issues on Crowdin, so closing.

**Pull request closed without merging**
