### PR TITLE
Ensure well_known controllers use WEB_DOMAIN by including RoutingHelper

### LINKED ISSUE #2375: Using WEB_DOMAIN wrong URL is returned in Webfinger for atom, salmon
I set up an instance whose public domain is eridi.us and whose WEB_DOMAIN is social.eridi.us. Using webfinger.net to look up kevin@eridi.us, I get the following:

```json
{
  "subject": "acct:kevin@eridi.us",
  "aliases": [
    "https://social.eridi.us/@kevin",
    "https://social.eridi.us/users/kevin"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://social.eridi.us/@kevin"
    },
    {
      "rel": "http://schemas.google.com/g/2010#updates-from",
      "type": "application/atom+xml",
      "href": "https://eridi.us/users/kevin.atom"
    },
    {
      "rel": "salmon",
      "href": "https://eridi.us/api/salmon/1"
    },
    {
      "rel": "magic-public-key",
      "href": "data:application/magic-public-key,RSA.wek_FwrfGUhUxrmdbksDqGW-nMZM21h3kVCw5dYhE5_ln5nGTIOxySEneAJWDTMhRwsOm_TBSKfUJfW0kdt3vgwcGhPpzYjo4gYKZG54zMZ91mjc5uOmQXSmRsss17SOBQu_SlM01Bq3oar06ln94pVGd3t-NfS6DbFUgrJIkH7tL1jupGNUVEP_UvLBoegFCHusUmi6VDEjd_IpNR3OPnHCiHAjUe-Fz7j4m_POQc16Om_pHJ_5LfvNKszgQLOPGuLXqJaZfj6yZ8VhnSp_ERmiyUg1EAlAK3I16KrXT9gyMjidV8nI-R8VyHoElv0IFs4lZIPFoth7RMbeSjapmw==.AQAB"
    },
    {
      "rel": "http://ostatus.org/schema/1.0/subscribe"
    }
  ]
}
```

Note how both the Atom URL and the Salmon URL are using eridi.us instead of social.eridi.us.

* * * *

This bug happens on current `master` (ef5937da1ff2d6caca244439dd9b9b9ed85fb278).

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This fixes #2375.

### CODE REVIEW

**Comment by ThibG** [comment]
I obviously incorrectly include'd RoutingHelper, and I will fix that in the next version of the patch. However, I'm wondering whether it shouldn't simply be include'd in ApplicationController, so that *any* URL generated from route URL helpers will reference WEB_DOMAIN.

**Comment by Gargron** [comment]
RoutingHelper should already be part of ApplicationController this controller inherits from...

**Comment by ThibG** [comment]
RoutingHelper is not currently included in ApplicationController. Including it does indeed fix it, but breaks a few tests (I think the tests themselves should be changed).

**Comment by ThibG** [comment]
This is a pretty minor issue, but one easy to fix. Is anything blocking this PR? Do you want me to move it into ApplicationController instead?

**Review by Gargron — APPROVED** [review]

**Pull request merged**
