### PR TITLE
Localize locale names (with ruby-cldr)

### PR DESCRIPTION
**Pull request by c960657**
(this PR has the same goal as #23587 but is based on the [ruby-cldr](https://github.com/ruby-i18n/ruby-cldr) gem rather than the [twitter-cldr](https://github.com/twitter/twitter-cldr-rb) gem).

Locale names currently only exist in English and the locale language itself. This leads to mixed-language strings such as _“Translated from 日本語 using DeepL.com”_ instead of _“Translated from Japanese using DeepL.com”_.

With this PR, locale names are stored in regular i18n yml files and handled like any other string.

For locales supported by CLDR, the files have been prepopulated with all languages included in CLDR for the locale in question. When new supported locales are added, run `rake cldr:download cldr:build` to update all `language.*.yml` files with new locale based on CLDR (where applicable). Once in a while we can bump the CLDR version number to get updated translations.

Of the 95 locales supported by Mastodon (`I18n.available_locales`), CLDR supportes 87. For most of these, CLDR has translations for all locales in SUPPORTED_LOCALES except these: `bh` (Bihari), `cnr` (Montenegrin), `kmr` (Kurmanji (Kurdish)), `ldn` (Láadan), `tai` (Tai), `zba` (Balaibalan).

With locale names available in the chosen UI language, I think it is more appropriate for `/settings/preferences/other` to show these rather than the native names. I wonder if we should follow this logic and flip the native vs. localized string in the language dropdown in the compose form, so the localized name is written in black and the native name in light grey?

I changed the native name for some locales in `LanguagesHelper` to reflect the name in CLDR. This includes some changes to lowercase (language names written in uppercase in e.g. English but not in e.g. Spanish) and remove “language” suffix (e.g. from _“беларуская мова”_ to _“беларуская”_ – the suffix _“мова”_ means language – as also suggested [here](https://crowdin.com/project/mastodon/discussions/285))“.

image

image

### CODE REVIEW

**Comment by gunchleoc** [comment]
I like this for the language selector, to replace English bits. It makes things easier to type when searching for the language you want.

For the language filter settings, I'd still like to see the native names there.

We also need a way to provide language names via Crowdin for the ones missing from the CLDR, because it's now showing the locale codes instead.

**Comment by Yoxem** [comment]
`tai` is not a valid ISO 639 code, the most suitable code for the language is `nan-TW` recently. see [the issue](https://github.com/mastodon/mastodon/pull/23880)

**Comment by renchap** [comment]
Quick note here: the latest feedback from the team was that this gem did not seem maintained (no recent release), and also that it adds a *lot* of files to the repository, which might make it much heavier.

I am not sure there is a better way, and I need to discuss this again to ensure I remember things correctly

**Comment by mjankowski** [comment]
Excellent. Closing on assumption that we won't merge an unmaintained gem and lots of files are scary.

Good followup here might be:

- Try to get the gem to release (and changelog since last release)
- Does all this yaml have to be generated and live in the app, or can it live in gem (and if yes/no, explain)?

Please reopen if/when gem seems more supported (I think this IDEA is great and makes sense).

**Pull request closed without merging**
