### PR TITLE
Dropdowns accessibility

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This is an attempt to fix accessibility issues with the different dropdown menus, including #7039.
It is not quite complete yet as keyboard navigation is not implemented.
Also, I'm far from being a web accessibility expert, so I could really use some review/feedback here.

### CODE REVIEW

**Comment by ThibG** [comment]
I think I'm done implementing this, but I would appreciate some reviewing/feedback here.

**Review by Gargron — APPROVED** [review]
Seems fine...

**Comment by mal0ki** [comment]
@ThibG did this fix all the issues in #7039, if so I'll close that issue.

**Comment by ThibG** [comment]
Hm maybe not, the generic dropdown menu items are still buttons, and not menuitems, maybe that should be changed.

**Pull request merged**
