### PR TITLE
Change "Allow trends without prior review" setting to include statuses

### LINKED ISSUE #17934: Make it possible for admins to auto-approve posts and links on the Explore page
### Pitch

Please make it possible to automatically approve trending posts and links on the Explore page. This is also possible for trending hashtags. Most of the well moderators servers have already non-problematic content trending, because of the organic network effect of their users. If there are problematic posts and links they can be removed later or reported by the users. I think it's up to  the admin to decide this. 

### Motivation

Most moderators don't have the time to approve posts and links as few per day or even daily. Therefore I predict that the Posts and News tab on the Explore pages will not be updated on many servers very often. This defies the use case of the Explore page.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #17934 

image

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I strongly disagree with this, especially with tying that with the existing setting.

**Comment by shleeable** [comment]
> I strongly disagree with this

These kind of changes nice to have as opt-in tho. Defaulting to off hopefully makes you feel less conflicted?

**Comment by ClearlyClaire** [comment]
> > I strongly disagree with this
> 
> These kind of changes nice to have as opt-in tho.

Eh, debatable.

> Defaulting to off hopefully makes you feel less conflicted?

Somewhat. But every trending feature has been creeping in, in an all-or-nothing way, if you want trending hashtags, you also have to deal with trending links and posts.

> I will be enabling this because I want trends to actually trend... and not be updated once or twice a week when I get around to it.

It is off by default, though it's tied to the existing setting which used not to do that. Now, if you want to go without *a priori* review of hashtags, you forfeit *a priori* review of links and statuses.

Also the whole “explore” things is displayed regardless of whether trends are enabled or not (in which case it will simply be empty).

**Comment by shleeable** [comment]
The first principles of this feature to me is pulling posts from the federated timeline. I don't approve posts in the federated timeline (my favorite timeline) -- so trending shouldn't be any different

People can report toots or accounts or even whole instances for me to audit and moderate after the fact.

I figure trending is no different than the firehose to me.

**Comment by tribela** [comment]
> I strongly disagree with this, especially with tying that with the existing setting.

I agree that "tying with the existing setting" part.

>  I will be enabling this because I want trends to actually trend... and not be updated once or twice a week when I get around to it.
> People can report toots or accounts or even whole instances for me to audit and moderate after the fact.

Me too. because i don't want to review all of trends same as i don't review all of posts on local/fed timelines
I don't want to pre-censor trending

BTW, I want to auto-allow **local** posts to be trend at least

**Comment by cbayerlein** [comment]
I strongly support this PR and would absolutely be happy to see this feature.

**Comment by TheKinrar** [comment]
Any plans on this? I understand how some people might not want to enable this feature, but I can't really see the issue with it if it's opt-in, and split from the current hashtags setting.
I mean, I'm disabling trends on my instance because I don't have the time to moderate dozens of statuses each day (and I'm getting too much emails), and even a slight delay in moderation probably kills the idea of a "trending" post. On the other hand, clearly, if someone has the time (and/or less users I guess) to do the moderation, that seems fine too, so I would also be in favour of this being opt-in, and not tied to the existing setting.

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
Why is this still tied to the hashtag setting?

**Pull request merged**
