### PR TITLE
Updating Chinese (Simplified) translations

### PR DESCRIPTION
**Pull request by ghost**
- Minor changes on translations for Devise and Doorkeeper. See also tigrish/devise-i18n#214 and doorkeeper-gem/doorkeeper-i18n#37 - cc @Artoria2e5 
- Suggestion: Change `静音` (`mute` and `silence`) to `隐藏`
- Add translations for #5087 & #5669

### CODE REVIEW

**Comment by Artoria2e5** [comment]
not a literal translation, a bit radical, but not a bad idea i guess

**Comment by SerCom-KC** [comment]
@Artoria2e5 That's actually what Twitter uses, plus `静音` always sounds weird to me if not talking about audio.
LGTY?

**Comment by Artoria2e5** [comment]
Hmmm… I guess 隐藏 is good. (Don't use that Lu Xun roof/window quote on me, please.) The 黑名单 (blacklist) business feels like going a bit too far.

**Comment by SerCom-KC** [comment]
Sure.
If nothing else please approve :P

**Review by Gargron — APPROVED** [review]

**Review by Artoria2e5 — COMMENTED** [review]
👍

**Pull request merged**
