### PR TITLE
Add boost confirm modal

### PR DESCRIPTION
**Pull request by blackle**
Fix for #621 

It looks like this: 
screenshot of modal

the modal is defined to be 480px but no wider than 90% of the screen size, and also the toot preview cannot be taller than 60% of the screen size (when this happens it becomes scrollable)

also pointer events for the toot preview are disabled thru css so the user doesn't click on, say, the username and get taken to their profile _behind_ the modal

### CODE REVIEW

**Comment by yiskah** [comment]
Does this have the ability to use alt-click to bypass the modal?

**Comment by blackle** [comment]
woops, forgot to implement that part
I can either modify this commit to add that or do it in a later one

**Comment by yiskah** [comment]
If it's easy enough to add to this pull i think it would be ideal since it would be tedious for a lot of people to have to confirm every time

**Comment by rainyday** [comment]
Can there be a way to turn this off? This just makes it more work to do anything and as someone who suffers from RSI I really don't like the idea of having to hold an extra key just to boost.

**Review by ghost — CHANGES_REQUESTED** [review]
svg should be in its own file not crammed into the stylesheet

**Comment by blackle** [comment]
the svg has to be in the stylesheet so admins can edit the colour scheme through variables.scss

**Comment by blackle** [comment]
Ok, I added the alt+click to bypass the dialog, and also a setting in user preferences to disable it altogether

**Comment by rainyday** [comment]
Is there a reason you can't just use css instead of a svg? This kind of thing is bad for performance and long term maintainability.

**Comment by blackle** [comment]
I don't see how this is relevant to the current PR, I didn't add that in this commit, just changed the rules so it didn't apply to the boost button

**Comment by blackle** [comment]
fuck, accidentally closed

**Review by Gargron — APPROVED** [review]

**Pull request merged**
