### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by rkarabut**
Testers found loads of strings with default values not mentioned in the English language templates (should probably add them there as well), fixed everything I could locate. Also, some updates for new features like toggling sound notifications.

### CODE REVIEW

**Comment by yookoala** [comment]
There are merge conflicts with this PR. Can you help rebase the new changes onto the current master HEAD?

**Comment by rkarabut** [comment]
Sure! Sorry, I'm new to this and haven't realized what was needed to be done.

**Comment by rkarabut** [comment]
So what should be done about travis checks? These failures obviously don't have anything to do with the actual commit.

**Review by Gargron — APPROVED** [review]

**Comment by yookoala** [comment]
Suggest to clean up this branch before carry on works:
1. `git reset hard f39174c`.
2. [git rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) to the current master (resolve the conflicts manually.

Reduce unnecessary merge commits.

**Pull request merged**
