### PR TITLE
Correctly read Russian language

### PR DESCRIPTION
**Pull request by MastodonRussia**
Hi. 
I finished my localization in Russian
See in work - https://mastodonrussia.ru/

### CODE REVIEW

**Comment by mkody** [comment]
You should remove the changes you've made to

- `app/assets/javascripts/components/features/getting_started/index.jsx`
- `config/application.rb`
- `config/initializers/paperclip.rb`
- `config/locales/en.yml`

**Comment by rkarabut** [comment]
There's already a full translation pending merge at https://github.com/tootsuite/mastodon/pull/1023

**Comment by Gargron** [comment]
Given that we merged #1023, is there anything in here that isn't there?

**Comment by rkarabut** [comment]
I skimmed through it yesterday, nothing I haven't translated. Some mistakes, too, especially in the Doorkeeper section (OAuth stuff is pretty technical).

**Comment by Gargron** [comment]
Alright, sorry, closing this one! Feel free open other PRs on top of the up-to-date translations, thank you for your time!

**Pull request closed without merging**
