### PR TITLE
Paginate descendant statuses in public page

### PR DESCRIPTION
**Pull request by akihikodaki**
See also #7102.

### CODE REVIEW

**Comment by Gargron** [comment]
I'd like a review from someone else regarding the UX that this introduces. They're cool changes but I wanna make sure threads don't become less convenient because of them.

**Comment by Sylvhem** [comment]
Can we have some screenshoots of the result posted here?

**Comment by Gargron** [comment]
I wonder if maybe some special exception needs to be made for self-replies. It seems like a self-reply chain should not be paginated, what do you think?

**Comment by akihikodaki** [comment]
We can relax the threshold for self-replies, but the pagination is still desired for performance and security. I wonder what the threshold should exactly be. It should be sufficient for most use cases, including self-replies.

**Review by Gargron — APPROVED** [review]

**Comment by nightpool** [comment]
4 is an extremely small limit. Most every reply chain has more then 4 statuses in them.

**Pull request merged**
