### PR TITLE
Fix some fonts were not loaded due to CSP

### PR DESCRIPTION
**Pull request by gomasy**
screenshot from 2018-10-25 21-45-56

### CODE REVIEW

**Comment by Gargron** [comment]
What kind of font is that though?.. Is it loaded by rellax.js?

**Comment by Gomasy** [comment]
No, pure Mastodon UI seems to have this error.

**Comment by Gargron** [comment]
It does not happen on mastodon.social which is vanilla 2.6.0rc1

Do you have a browser extension that inserts those fonts into the page, maybe?

**Comment by Gomasy** [comment]
I am sorry.
It was a problem with the extended function, sorry for taking your time.

**Pull request closed without merging**
