### PR TITLE
Restrict permitted posting languages

### PR DESCRIPTION
**Pull request by c960657**
Many instances specify a list of permitted posting languages in their server rules. However, such rules are not enforced/encouraged by the software.

Showing only permitted languages in the language dropdown makes users more aware of the server rules, and it makes it easier for users to find the relevant language in the list. For regional instances, it contributes to the perception of a closed community.

With this PR, an instance owner can specify a list of permitted posting language using an environment variable, e.g. `POSTING_LANGUAGES=en,nl,fr`.

Obviously, you cannot prevent users from selecting a random language and then post in whatever language they like, so this feature should be considered a guide rather than an enforcement.

### CODE REVIEW

**Review by ClearlyClaire — COMMENTED** [review]
The implementation looks ok but honestly I'm not sure how good of an idea that is.

**Comment by vmstan** [comment]
> Obviously, you cannot prevent users from selecting a random language and then post in whatever language they like, so this feature should be considered a guide rather than an enforcement.

I think this highlights why it's not a good idea to implement this. Translation being prompted is totally dependent on the language selection being correct and different from the user's selected language. There is enough of an issue with folks not doing this and posting German with English selected, etc. Making it harder on the user to do the right thing would just lead to them posting with the incorrect setting.

**Comment by vmstan** [comment]
Also, if I'm on a server that only support English, and I'm following someone who posts something in a language that I understand and I want to reply in that native language, now I'm forced to do so incorrectly or not reply at all.

**Comment by c960657** [comment]
> There is enough of an issue with folks not doing this and posting German with English selected, etc. Making it harder on the user to do the right thing would just lead to them posting with the incorrect setting.

Limiting the available language options should make it _easier_ for the user to do the right thing. If a user on a regional instance opens the language selector, they will only see a handful of languages, rather than a very long list where you need to search for the language they need. We could even write “only these languages are allowed on this server” at the top of the language selector, so users know why there are no more options.

If the user doesn't even bother to open the language dropdown, this change will not make any difference.


> Also, if I'm on a server that only support English, and I'm following someone on another server who posts something in a language that I understand and I want to reply in that native language, now I'm forced to do so incorrectly or not reply at all.

If the server rules of your instance requires that all posts are in English, you cannot do that anyway without violating said rules.

Some instance administrators might be more liberal about which languages are used in e.g. unlisted statuses. To support that kind of policy, we could update this PR to make the available languages dependent on the selected visibility.

**Comment by Gargron** [comment]
I'm against the idea. This won't stop anyone from writing in another language, but will force them to tag it wrong.

**Pull request closed without merging**
