### PR TITLE
Switch docker-compose to version 3.

### PR DESCRIPTION
**Pull request by valentin2105**
It allow possibility to Deploy Mastodon in a Swarm cluster directly from the compose file.

I will write a small doc to explain How to do this.

### CODE REVIEW

**Comment by Gargron** [comment]
> `extends`: This option has been removed for version: "3.x" Compose files.

https://docs.docker.com/compose/compose-file/compose-versioning/#version-2x-to-3x

**Comment by valentin2105** [comment]
@Gargron I missed this, I deleted every extends occurences.

**Review by Gargron — APPROVED** [review]

**Comment by Wonderfall** [comment]
Why not the latest version 3.2?

**Comment by Gargron** [comment]
@Wonderfall This is about the version of the config file, not of the docker-compose binary - unless the config file has minor versions?

**Comment by Wonderfall** [comment]
The config file has minor versions since version 2. It's also possible `version: 3` refers to the latest 3.x, but I'm not sure.

**Comment by valentin2105** [comment]
Updated in 3.2, (tested). But requiere a docker-compose --upgrade via Pip.

**Pull request merged**
