### PR TITLE
Re-add StatsD support through the `nsa` gem

### PR DESCRIPTION
**Pull request by ClearlyClaire**
As we still don't have a replacement for StatsD/`nsa`, re-introduce the gem, although this is now using a fork of `nsa` for Rails 7 support.

This also disables sidekiq collection unless `STATSD_SIDEKIQ` is set to `true`, as the way the `nsa` gem does this is known to add a lot of overhead.

This also reverts #11232 for the global variable aspect, as it appears to me that was unused.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by vmstan** [comment]
I had a STATSD endpoint in my configuration from prior to the removal of the gem earlier in development, and after trying the build that includes this PR, I could not get services to start until I removed the STATSD_ADDR setting from the config (I did not have the second option specific to Sidekiq even mentioned as nothing changed.)

**Comment by renchap** [comment]
Can you share the error you got?

**Comment by vmstan** [comment]
```
2023-08-03T21:52:23.529Z pid=7 tid=5cr INFO: Booting Sidekiq 6.5.9 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"rediss://default:REDACTED@REDACTED", :namespace=>nil}
2023-08-03T21:52:23.581Z pid=7 tid=5cr WARN: SocketError: getaddrinfo: Name or service not known
2023-08-03T21:52:23.581Z pid=7 tid=5cr WARN: /usr/local/bundle/gems/statsd-ruby-1.5.0/lib/statsd.rb:462:in `ip'
/usr/local/bundle/gems/statsd-ruby-1.5.0/lib/statsd.rb:462:in `block in connect'
/usr/local/bundle/gems/statsd-ruby-1.5.0/lib/statsd.rb:451:in `synchronize'
/usr/local/bundle/gems/statsd-ruby-1.5.0/lib/statsd.rb:451:in `connect'
/usr/local/bundle/gems/statsd-ruby-1.5.0/lib/statsd.rb:306:in `initialize'
/opt/mastodon/config/initializers/statsd.rb:6:in `new'
/opt/mastodon/config/initializers/statsd.rb:6:in `<main>'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:667:in `load'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:667:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/notifications.rb:208:in `instrument'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:666:in `load_config_initializer'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:372:in `initialize!'
/opt/mastodon/config/environment.rb:7:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/sidekiq-6.5.9/lib/sidekiq/cli.rb:286:in `boot_application'
/usr/local/bundle/gems/sidekiq-6.5.9/lib/sidekiq/cli.rb:53:in `run'
/usr/local/bundle/gems/sidekiq-6.5.9/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/cli.rb:492:in `exec'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by vmstan** [comment]
For anyone who comes along later and finds this, the issue is that it's trying to initialize the gem by verifying that the statsd server is online via DNS query. Either fire up statsd or remove the setting from your configuration if it's not available.

**Pull request merged**
