### PR TITLE
Document AUTHORIZED_FETCH mode and WHITELIST_MODE

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by Gargron** [comment]
Should this maybe be part of documentation instead? Since .env.production is auto-generated from mastodon:setup, a lot of people probably don't look into the sample file like they used to. It feels weird to document functionality in bash comments in an env file.

**Comment by ThibG** [comment]
Well, summarily describing flags in the config file sample is helpful and common practice.
But I guess a shorter description of what they do *and* a proper entry in the documentation would be best.

**Comment by Gargron** [comment]
A link to the anchor in documentation would be perfect, actually

**Comment by ThibG** [comment]
Updated by shortening significantly the description and linking to the docs

**Review by Gargron — APPROVED** [review]

**Pull request merged**
