### PR TITLE
Skip ActivityPub Announces of non-public objects

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Review by nightpool — APPROVED** [review]
LGTM

**Comment by ThibG** [comment]
Hm… ActivityPub does not restrict the `Announce` activity to objects with a public audience.
This change basically makes #6157 useless for Mastodon.

**Comment by akihikodaki** [comment]
> This change basically makes #6157 useless for Mastodon.

We should have a change to accept boosts by the author as soon as possible though such frequent releases may be bothering server administrators.

**Comment by ThibG** [comment]
@akihikodaki I think the only restriction that really makes sense is to not widen the audience of the original toot. E.g., it could be boosted by a follower of the original poster, and that boost would then be seen only by the intersection of the booster's audience and the original poster's audience.

I'm not sure how Mastodon handled that before the change discussed here, though.

**Comment by akihikodaki** [comment]
@ThibG See #6236.

**Pull request merged**
