### PR TITLE
Remove all main scrollbar styling

### LINKED ISSUE #31917: [Accessibility] The main scrollbar is too thin and is difficult to grab.
### Steps to reproduce the problem

1. Go on Mastodon web interface on your desktop and look at the scrollbars sizes, mainly the main scrollbar totally on the right.
2. Some people, including me, can't grab it with the mouse because it's too thin.

### Expected behaviour

I can grab the scrollbar with the mouse to scroll because it's normal size.

### Actual behaviour

I can't grab the scrollbar with the mouse to scroll because it's too thin.

### Detailed description

The main scrollbar (on the `html` element) is too thin and it's very difficult to grab it to scroll with the mouse. On the screenshot below, this is the scrollbar on the right. The other for the navigation is normal size.

Screenshot of Mastodon interface with the thin main scrollbar and a normal size one for the navigation

I've found this code in the CSS which is the problem:

```css
@supports not selector(::-webkit-scrollbar) {
  html {
    scrollbar-color: #606085 var(--background-border-color);
    scrollbar-width: thin;
  }
}
```

There is an ["Accessibility" section on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#accessibility) to explain why the CSS property `scrollbar-width` is a problem when you fix the `thin` value.

Is it possible to remove this property from the CSS? Or to add an option so that users can choose if they want the normal size for scrollbar or a thin size?

Thanks

### Mastodon instance

eldritch.cafe

### Mastodon version

v4.3.0

### Browser name and version

Firefox 130

### Operating system

Windows 11

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by vmstan**
Fixes https://github.com/mastodon/mastodon/issues/31917 as alternative to #32091 explained in https://github.com/mastodon/mastodon/pull/32091#issuecomment-2374586692 😄

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Unfortunately, this is how it looks without styling when I try it in chromium (128.0.6613.113 on linux):
image

**Comment by vmstan** [comment]
Yeah, do you have always show scrollbars set?

**Comment by ClearlyClaire** [comment]
If there is such a setting in Chromium, I don't know where it is.

**Comment by vmstan** [comment]
Closed in favor of #32117

**Pull request closed without merging**
