### PR TITLE
Add retention policy for cached content and media

### PR DESCRIPTION
**Pull request by Gargron**
Allow setting a retention policy for cached content or media. Content (statuses) or media (media attachments and preview cards) that are older than the retention period will be automatically removed. Removes the need for manually running `tootctl media remove` and so on. This is not an exact copy of `tootctl statuses remove` -- that command has to create temporary database indices to perform very expensive checks to only delete statuses that have never been interacted with by local users. The retention policy only takes time into account.

Fix #18763

image

___

This project was funded through the [NGI0 Discovery](https://nlnet.nl/discovery) Fund, a fund established by [NLnet](https://nlnet.nl/) with financial support from the European Commission's [Next Generation Internet](https://ngi.eu/) programme, under the aegis of DG Communications Networks, Content and Technology under grant agreement No 825322.

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by hugogameiro** [comment]
Does `StatusesVacuum` delete all posts locally after the set number of days, no matter if they were favourited, boosted or replied to by a local user?

**Comment by Gargron** [comment]
It only removes remote posts, posts by local users are not touched. Yes, it removes all of them outside of the retention period.

**Comment by ClearlyClaire** [comment]
I can see some issues with that, including losing bookmarks, the ability to signal other instances that you deleted your reblog of something (since you'd lose any record of that), or the access to any DMs. I don't think the description does a good enough job of explaining that, and I think the feature should ideally avoid those cases in the first place.

Otherwise, it's a very welcome feature!

**Comment by hugogameiro** [comment]
Yes, I agree, this is a very welcome feature. Just worry that if I bookmark or favourite a remote post and when I go looking for it, it's no longer there. Same, for a remote post I boost and that disappears from my profile after a while without me noticing it.

**Comment by jwildeboer** [comment]
@hugogameiro If the remote content isn't locally found, it could trigger a re-sync of that specific content. Would add a bit of latency and traffic, but I would think that is acceptable to avoid excessive storage use of cached content that is (I guess) hardly ever touched after a few days. The re-sync would then start a new retention period, rinse, repeat.

**Comment by hugogameiro** [comment]
@jwildeboer If I am thinking about this correctly, I don't know how that could be achieved. The problem is that `StatusesVacuum` does not differentiate between interacted posts and non-interacted ones. So, remote posts older than X days will be deleted, no matter what. 

To do what you suggest, all records needed to stay in the database, and only the actual content (meaning the post's text) would be deleted. I believe that the metadata associated with a post (id, uri, create date, account id, etc.) will use more disk space than the actual text of the post. But Mastodon would need that metadata to re-fetch the content, at least partially. In that case, the reduction in storage would not be significant and would increase the CPU/RAM needed to re-fetch the post.

I started a discussion #19260 with an idea to work around this.

**Comment by quicoto** [comment]
Does this feature include cleaning the Avatar and Headers for remote accounts? Which should fix #9567 ?

Thank you

**Comment by retiolus** [comment]
I also think that it should be possible to delete locally the headers and avatars of users from other servers.

**Comment by jsailo** [comment]
> Does this feature include cleaning the Avatar and Headers for remote accounts? Which should fix #9567 ?
> 
> Thank you

I'm curious about this too.

**Comment by ClearlyClaire** [comment]
No, it does not.

**Comment by cham2019** [comment]
Will this be considered and implemented with this retention policy of content and media on the admin side too ? I mean, for local posts too, based on aging, and handled by the admin as an internal instance policy (not by the local user interface who already has the "automated post deletion" option)

[https://github.com/mastodon/mastodon/issues/1554#issuecomment-294262801](url)
> Alternatively - delete all, including local, content that is older than x. That's something that could be debated.

**Comment by ClearlyClaire** [comment]
They disappear completely from the local database. When re-fetched, your server won't know they were favourited/boosted/bookmarked

**Comment by cham2019** [comment]
Thanks for the reply.  So that means favourited/boosted/bookmarked posts deleted by this feature will be gone forever, at least locally I mean.  Because, as far as I understand mastodon (and how ActivityPub works)  once those old remote posts are removed from my local instance by this timing-based instruction (favorited posts or not), there is no way to re-fetch historical posts from remote accounts by local request. Or is there a way?  Unless of course, someone from remote (with still access to those old posts, and followed by at least one account from my local instance) boosts it.  Did I understand this correctly?

**Comment by ClearlyClaire** [comment]
The posts can be re-fetched if someone remote boosts or replies to them, or if a local user paste their URL into the server's search bar. But the associated boosts/favs/bookmarks won't be recovered.

**Comment by zeeZ** [comment]
This should all be documented somewhere, preferably close to that setting. "This may be irreversible" only raises more questions than it answers, and having to dig through comments on a pull request to get those answers is not the way, IMHO.

**Comment by nemobis** [comment]
Any admin thinking of enabling this on their instance would do well to warn the instance's users in advance, so that they have a chance to download an archive of their favorites and bookmarks (even better would be to send them such an archive right away by email: https://github.com/mastodon/mastodon/issues/19400 ).

Discussions will most likely become impossible to understand as messages are forgotten and relationships severed. Users can be advised to use [mastodon-archive](https://alexschroeder.ch/cgit/mastodon-archive/about/) or similar to download their data before it vanishes.

**Pull request merged**
