### PR TITLE
Fix tootsuite/mastodon#15950

### LINKED ISSUE #15950: All `mimemagic` versions prior to `0.3.6` have been yanked
All `mimemagic` versions prior to `0.3.6` have been yanked. (More at https://github.com/rails/rails/issues/41750)

### Expected behaviour

`bundle install` should run as normal.

### Actual behaviour

```bash
mastodon@robert-U56E:~/live$ bundle install -j$(getconf _NPROCESSORS_ONLN)
Fetching gem metadata from https://rubygems.org/............
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed
sources, that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that
hasn't been removed in order to install.
```

### Steps to reproduce the problem

Just run `bundle install`.

### Specifications

Found in https://github.com/tootsuite/mastodon/commit/f8e50eaea351d743bf80e65c2178c4ed46d65881.

### PR DESCRIPTION
**Pull request by lunaisnotaboy**
Bump a few gems, particularly `mimemagic`.

Fixes tootsuite/mastodon#15950

### CODE REVIEW

**Comment by lunaisnotaboy** [comment]
You should probably bump the release `3.3.1`, too.

**Comment by nightpool** [comment]
Unfortunately, 0.3.6 has also been yanked. I think we need to wait on Rails upstream to release a version of `marcel` that removes mimemagic, a new system dependency is a no-go for us—our installation instructions are already complicated enough as it is.

**Comment by lunaisnotaboy** [comment]
@nightpool I saw. I only just got around to pushing the commit, so I have the newer version that is MIT-licensed. For the time being, this at least allows for `bundle install` to complete.

**Comment by dakotahp** [comment]
Rails has released 6.1.3.1 which fixes the missing dependency by using a different library. https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/

Bumping Rails instead of these changes would completely fix the issue cleanly. (I am having trouble bundling locally due to libidn or I'd open a PR myself).

**Pull request closed without merging**
