### PR TITLE
Set up Docker compose for development with minimal changes

### LINKED ISSUE #16747: Development Works out of the Box
### Pitch

Hey Team, 

The current docker/docker-compose.yml explicitly targets production and the current steps for setting up a dev environment are a work in progress on the "getting started".

You can search in the issues and see quite a few issues with development, this would reduce the "help footprint" by providing an env for people to dev in, there are dozens, just picked a few
 - https://github.com/mastodon/mastodon/issues/15863
 - https://github.com/mastodon/mastodon/issues/15751
 - https://github.com/mastodon/mastodon/issues/14941
 - https://github.com/mastodon/mastodon/issues/10926

https://github.com/mastodon/mastodon/issues?q=is%3Aissue+development

I can setup a docker-compose.dev.yml and Docker.dev to support the env right now.  

I think even better would be to invert this.  It would break anything that currently depends on the docker being production
- Make `Dockerfile` and `docker-compose.yml` target the development build 
- Create a new Dockerfile.prod and docker-compose.prod.yml

Alternatively
- make `docker-compose.yml` target development, create a Dockerfile.dev
- keep Dockerfile the same to reduce change of things breaking

### Motivation

To support all the features, this is a relatively complex software system.  Someone who hasn't worked on elastic,redis, rails and postgres for years is going to have a pretty rough time. whereas if we have a docker-compose.yml they can at least 

```docker-compose -f docker-compose.dev.yml up``` and be off to the races

### PR DESCRIPTION
**Pull request by nileshtrivedi**
This should fix #16747

Currently, docker-compose.yml is set up for production. And .env.production is NOT meant for Docker at all.

To get Docker-based development going without affecting either of the above settings, this PR adds a `docker-compose.dev.yml` file and a `Dockerfile.dev`. The corresponding config will have to go in `.env.development` which remains gitignored.

Here are the summary of changes:

- docker-compose.dev.yml
  - Postgres container is configured with explicit username, password and database name
  - Postgres healthcheck command is corrected
  - For `web`, `streaming`, and `sidekiq` services, build now refers to `Dockerfile.dev` and env_file refers to `.env.development`. References to pre-built images on Docker Hub are removed.
  - The web service is started with `-b 0.0.0.0`
- Dockerflie.dev
  - This is mostly similar to `Dockerfile` except that `RAILS_ENV` and `NODE_ENV` are set to "development"
  - "development" group of gems is installed instead of "production"

With this PR, you will need the following changes in your .env.development:

- LOCAL_DOMAIN=masto.local
- REDIS_HOST=redis
- DB_HOST=db
- DB_USER=mastodon
- DB_NAME=mastodon_development
- DB_PASS=mysecretpassword
- DB_PORT=5432
- ES_ENABLED=false
- S3_ENABLED=false

The steps to set up the development environment would be:

- Build the image with: `docker build -f Dockerfile.dev .`
- Clean the DB data with: `rm -rf ./postgres14/*`
- Start DB and Redis so that we can run Rails migrations: `docker compose -f docker-compose.dev.yml up -d db redis`
- Run Rails DB migrations: `docker compose -f docker-compose.dev.yml run --rm web bundle exec rake db:migrate`
- Now, all the services can be started with: `docker compose -f docker-compose.dev.yml up`
- Create an admin account and generate a random password with: `docker compose -f docker-compose.dev.yml run --rm web bundle exec bin/tootctl accounts create eshnil --email youremail@example.com --confirmed --role admin`
- Modify your `/etc/hosts` file so that `masto.local` points to 127.0.0.1
- Open http://masto.local:3000 and login with the above email/password

### CODE REVIEW

**Comment by claudioc** [comment]
Great work, and... finally! Let's hope this will be merged

LGTM!

**Comment by ineffyble** [comment]
Just to confirm, the existing [dev container](https://containers.dev/) setup in [.devcontainer](https://github.com/mastodon/mastodon/tree/main/.devcontainer) is not fit for purpose?

**Comment by nileshtrivedi** [comment]
@ineffyble I had not heard of either devcontainers or Mastodon's support for it. 

- Installed the CLI with `npm install -f @devcontainers/cli`
- Ran `devcontainer up --workspace-folder .`
- Followed by `devcontainer exec --workspace-folder . foreman start`

Although the logs said the app was running on port 3000, it was not available on localhost, probably because neither the Dockerfile nor the docker-compose.yml file export any container ports to localhost. 

Also, strangely, there is no `devcontainer down` command to shut down all the containers.

I also noticed that Redis and NodeJS versions in these files are somewhat behind the main. 

If the devcontainer setup is documented, maintained, then yes, I think my PR is redundant and can be closed. Coud you point me to any docs on how to use this devcontainer for local development correctly?

**Comment by nileshtrivedi** [comment]
Ah, I get it now:

- Need the Dev Containers extension in VS Code
- Follow the instructions here: https://code.visualstudio.com/docs/devcontainers/tutorial

Also, discovered that the ports to be exposed are defined in devcontainer.json file and not Dockerfile/docker-compose.yml.

Although it doesn't quite work for me yet, this does seem like a complete Docker-based workflow for local development. Closing my PR for now. Will look separately for improving documentation of this as well as correcting dependency versions.

**Comment by ineffyble** [comment]
Yeah, Dev Containers are only supported in VS Code and GitHub Codespaces so far. I am hoping it gets wider adoption.

**Comment by ineffyble** [comment]
As someone who was fairly involved in Mastodon local dev enablement in the very early days, it's also worth noting that there hasn't been a huge amount of attention paid to Docker-based local dev workflows because it was felt that they had slower feedback cycles. Vagrant support was added quite early on as a way to do an isolated/virtualised dev environment.

That said, I am generally a big believer in containerised dev workflows where possible, so the more we can do in that regard the better.

**Comment by nileshtrivedi** [comment]
@ineffyble Vagrant doesn't work currently on Apple M1 machines at all, because VirtualBox doesn't and Mastodon's Vagrantfile requires ubuntu/bionic64 box which requires libvirt provider. I filed [an issue](https://github.com/mastodon/documentation/issues/1097) for this just a few days ago. 

Personally, I would prefer Docker for development because it matches the production setup more closely. In fact, it would be ideal if even the container images were identical for development and production. As Heroku's [12 factor app recommendation says](https://12factor.net/config), config (things that differ across deploys) should only be stored in environment variables.

**Comment by jaykz52** [comment]
Apologies for hi-jacking this thread, but @nileshtrivedi I wanted to surface https://github.com/mastodon/mastodon/discussions/21596 to you. I was able to get Mastodon running locally using VS Code / Dev Container but it did require some manual steps - hopefully this is helpful to you as well!

**Comment by astridx** [comment]
@jaykz52  Is it possible for you to exchange messages with other computers that are also installed locally (follow, nodes)?

I ask because I am stuck with a local installation at this point. I think it is because localhost:3000 is not encrypted (no https).

https://github.com/mastodon/mastodon/discussions/22309

https://discourse.joinmastodon.org/t/local-deployment/1018

**Comment by Austio** [comment]
@ineffyble Would this be acceptable to reanimate and merge for people that do not use vscode?

**Pull request closed without merging**
