### PR TITLE
Export and import `hide_notifications` alongside user mutes

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Comment by Gargron** [comment]
I am concerned that this is a pandora's box because we also have follows with/without reblogs and whatnot. So far the CSV files were just lists of strings, very simple and understandable, now we are putting unexplained booleans in them. Maybe this should require the introduction of a header row.

**Comment by ThibG** [comment]
Ah, yes, we could add a header, that would also help with potential future changes.
We need to be careful to chose header names that might not be interpreted as usernames by older versions though

**Comment by ThibG** [comment]
Well, I'm afraid I have no idea why the test fails on 2.4 and 2.5 but not 2.6.

**Comment by ThibG** [comment]
It appears it's a bug in the CSV module in older versions of Ruby when involving both headers and empty lines :weary:
I modified the test suite to not have such empty lines…

**Comment by ThibG** [comment]
Updated to use more natural-looking headers such as “Account address” instead of “#account”

**Review by Gargron — APPROVED** [review]

**Pull request merged**
