### PR TITLE
Remove Puma pidfile before boot if container receives SIGTERM

### PR DESCRIPTION
**Pull request by ladyisatis**
Fixes an issue mentioned in https://github.com/docker/compose/issues/1393

### CODE REVIEW

**Comment by Gargron** [comment]
Question: Is the PID file even needed inside Docker? Can it be disabled via some config? Would be much preferable to command like this

**Comment by Reverite** [comment]
I tried looking, but nope, Puma doesn't have an ability to disable it, and several other projects have had to do something this "hacky" unfortunately.

**Comment by Reverite** [comment]
On second thought, Docker supports mounting directory as a tmpfs, so something like this in the docker compose yml for the web container might work?

```
    tmpfs:
      - /mastodon/tmp/pids:uid=991,gid=991,mode=0644
```

**Comment by moritzheiber** [comment]
I wouldn't want to hardcode the UID/GID though

**Comment by Reverite** [comment]
After discussion on Discord, I tried this:

```
  tmpfs:
    - /mastodon/tmp/pids
```

Instance went down and wouldn't boot because of these errors:

```
/mastodon/vendor/bundle/ruby/2.4.4/gems/rack-2.0.3/lib/rack/server.rb:362:in 'initialize': Permission denied @ rb_sysopen - /mastodon/tmp/pids/server.pid (Errno::EACCES)
```

**Review by Gargron — APPROVED** [review]

**Comment by iGEL** [comment]
@Gargron In our Rails app (not mastodon), I just set the Pid file to `/dev/null`, which seems to work fine.
`rails server -b 0.0.0.0 -P /dev/null`

**Pull request merged**
