### PR TITLE
Build ffmpeg from source in Dockerfile

### PR DESCRIPTION
**Pull request by vmstan**
This PR enhances the production Dockerfile by converting from installing the version `ffmpeg` that is available in the Debian repos, to using a custom built versions. This has the following advantages:

- **Image size reduction:** the current Dockerfile was optimized in #26850 through a number of methods including separating the Core Image and Streaming image, removing Node from the resulting image. The 4.2 image is approximately 1.5GB in size while the current 4.3 image is just under 1GB. When `ffmpeg` is installed from the Debian repo, it includes a number of dependencies to support file formats that are not used or explicitly not desired in Mastodon, including the unused X11 server. #30571 took the first step in compiling libvips from source to eliminate this dependency. _The size of the resulting Docker image built by this PR under 700MB!_
- **Controlled version adoption:** ffmpeg version control should be considered as essential as Ruby, Node, Postgres, or any other Mastodon dependency given the importance of media processing. The Debian repos are notoriously slow in adoption of upgrades, for example `ffmpeg` is currently at 5.1.4 when 7.0.1 is available.
- **Optimized library selection:** Compiling these packages from source allows us to use only the libraries that are necessary for Mastodon. Ultimately I would like to become more restrictive about what formats are compiled as supported in ffmpeg as most are not needed by Mastodon. 

### ffmpeg compile/library settings
- Versions can be controlled in a similar method as Ruby/Node through Docker build arguments, to enable easier local testing and customized version deployments. `[--build-arg FFMPEG_VERSION="7.0.1"]`
- Source code is downloaded directly from ffmpeg.org.
- Building documentation and direct network support are disabled. (Full list of compile options available at https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)
- `libx264` is used for H.264 video encoding
- `libx265` is used for HEVC video encoding
- `libvpx` is used for VP8/VP9 video encoding/decoding
- `libopus` is used for Opus audio encoding/decoding
- `libdav1d` is used for AV1 decoding
- `libmp3lame` is used for MP3 encoding
- `libvorbis` is used for Vorbis audio encoding/decoding
- `libwebp` is used for WebP encoding
- `libsnappy` is used for compression

```
$ ffmpeg -version
ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/local/ffmpeg --toolchain=hardened --disable-doc --disable-network --disable-static --disable-debug --disable-ffplay --disable-devices --enable-gpl --enable-version3 --enable-shared --enable-ffmpeg --enable-ffprobe --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libwebp
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```

### CODE REVIEW

**Comment by renchap** [comment]
Please split the vips part from the ffmpeg part.

Also, how to we ensure that we update those versions regularly?

**Comment by shleeable** [comment]
I've given this PR a test as well... and this looks good on my machine.

**Comment by shleeable** [comment]
image

This PR is running A.S now with no known regression.

**Comment by vmstan** [comment]
> Please split the vips part from the ffmpeg part.
> 
> Also, how to we ensure that we update those versions regularly?

When paired with #30602 both libvips and ffmpeg versions will be tracked by Renovate

**Comment by vmstan** [comment]
This has been renamed and rebased to only include `ffmpeg` changes, since the Vips changes were merged separately in #30571

**Comment by renchap** [comment]
I love this, but I wonder how we should handle the supported ffmpeg versions. Major versions might have incompatible options, and I dont think we even care about this right now, or we provide a minimum supported ffmpeg version?

**Comment by vmstan** [comment]
Closes #20838

**Comment by vmstan** [comment]
> I love this, but I wonder how we should handle the supported ffmpeg versions. Major versions might have incompatible options, and I dont think we even care about this right now, or we provide a minimum supported ffmpeg version?

This shouldn't really impact overall supported versions, although ffmpeg would probably be the hardest one to come up with a minimum supported version as they're still providing updates for their 2.8.x

**Review by renchap — DISMISSED** [review]
Looks good to me. We will probably need to run it in production and check that we do not have weird video formats/codecs that are no longer processed correctly due to a missing library.

**Comment by vmstan** [comment]
> Looks good to me. We will probably need to run it in production and check that we do not have weird video formats/codecs that are no longer processed correctly due to a missing library.

I cleaned up some of the options that upon further review seemed unnecessary, and also added support for `libsnappy` as a compression method (it's the same one used by the Debian repo builds). 

I'm hopeful we'll be covered on most formats/codecs as it seems like a lot of the more advanced libraries are around _encoding_ files which Mastodon has limited format support on that side (H.264 with AAC video, or MP3 audio)

**Comment by shleeable** [comment]
Thanks for this PR @vmstan - I've been testing this PR without (known) regressions.

**Review by ClearlyClaire — APPROVED** [review]

**Review by renchap — APPROVED** [review]

**Pull request merged**
