### PR TITLE
Update sidekiq to version 7+

### PR DESCRIPTION
**Pull request by mjankowski**
As of now I just have the commits necessary to resolve the dep update, and get rid of errors/warnings after the update. Have done basically zero QA here.

Opening as draft to work through what's needed. Will leave comments as I research.

### CODE REVIEW

**Comment by renchap** [comment]
I started researching this yesterday and the big blocker is `redis-namespace` support being dropped.

We need a clear migration path to avoid phantom jobs and will be hard to properly implement and/or document.

Some details here: https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/

**Comment by renchap** [comment]
Another potential issue here is the removal of `hiredis` for Sidekiq, we will need to test this in a high-load environment to test how it performs, but if this means upgrading to Sidekiq 7 and we are seing issues, then it will hard to rollback?

**Comment by mjankowski** [comment]
> I started researching this yesterday and the big blocker is `redis-namespace` support being dropped.
> 
> We need a clear migration path to avoid phantom jobs and will be hard to properly implement and/or document.
> 
> Some details here: https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/

Agreed - I think this will actually be very straightforward code-wise (very few changes), slightly more complicated dependency-wise (more research needed to ensure we have upgraded/dropped appropriately) ... but the most complexity/planning will be in the upgrade/migration/documentation area.

**Comment by mjankowski** [comment]
> Another potential issue here is the removal of `hiredis` for Sidekiq, we will need to test this in a high-load environment to test how it performs, but if this means upgrading to Sidekiq 7 and we are seing issues, then it will hard to rollback?

Sidekiq switched from the `redis` gem to the `redis-client` gem. I think there are a few questions here:

- I found a `hiredis-client` (used in the PR here) which I think does for `redis-client` what the `hiredis` gem (Removed in this PR) was doing for the `redis` gem in terms of using hiredis lib. Need to confirm.
- Need to research to what extent our other non-sidekiq usage of redis relies specifically on the `redis` gem -vs- what could also be updated to use `redis-client` so we could drop `redis` entirely. Also might be fine to keep both.

**Comment by renchap** [comment]
The redis question is a bit more complex. Currently we do not support complex Redis setups, for example with TLS (mandatory for some hosted Redis offerings) or distributed Redis setups (Redis Sentinel or Redis Cluster), as they are not supported by `hiredis`.

There is more context here:
https://github.com/mastodon/mastodon/issues/19824
https://github.com/mastodon/mastodon/pull/23516

If we are starting to touch Redis's handling, we most probably want to ensure we move to libraries supporting those features, as they are needed for many setups (and we will probably need clustering quite soon for mastodon.social)

**Comment by renchap** [comment]
The main task here seems to be the migration path for servers with a namespaced Redis configuration.

This seems doable, but will require an extensive documentation about the steps.

What could work is:
- if you use a namespace for Redis, then you need to switch to using a different Redis DB for each instance
- we do not care about cache, it will be reset on upgrade
- what do we do for "app" data? Should it be migrated? Could it be dropped without too much impact?
- for sidekiq:
  - prepare a new configuration using a Redis DB instead of the namespace
  - stop Sidekiq scheduled jobs
  - run pre-upgrade migrations
  - start Sidekiq & web servers with the new code (and new config)
  - new jobs are now enqueued onto the new Redis, only older jobs are remaining on the old Sidekiq redis
  - let your old Sidekiq processes run until the queues are empty. We should probably provide a command that will output the status of those queue. And what about retries, can we simply ignore those and loose those jobs? Should we have a command to transfer them to the new redis?
  - stop your old sidekiq processes
  - run the post migrations

**Comment by renchap** [comment]
An issue with using Redis databases: redis pub/sub (used for streaming) does not support databases: https://redis.io/docs/interact/pubsub/#database--scoping

The documentation advises to add a scope in the front of the keys, similar to the namespacing we support at the moment

**Comment by mjankowski** [comment]
Side note here: I think with the propshaft change merged, sidekiq 6.x is our only dep still locked to rack 2.x.

**Comment by mjankowski** [comment]
After the last rebase here, we have some failures in the newly added `spec/system/new_statuses` -- which is nice, because it gives a more direct target to correct here. I believe the failure is indeed from the changing namespace/db behavior.

Apologies if I'm missing it in these comments, but putting aside the migration for a moment, what do you think is the preferred configuration in terms of the current redis/sidekiq usages and how they map onto new db numbers and/or prefixes? If we can pin that down I can take a crack at updating code to match that, then we can do a round on migration paths once we're confident in the new alignment of that stuff.

**Comment by vmstan** [comment]
Looking at this for testing in deployment, because currently I remove `hiredis` driver/gem in my builds since I'm using TLS with Redis. I don't use any namespaces. Looking through the documentation at  I'm not entirely clear on if this `hiredis-client` supports TLS?

**Comment by mjankowski** [comment]
> Looking at this for testing in deployment, because currently I remove `hiredis` driver/gem in my builds since I'm using TLS with Redis.

As a tangent here, I think it's possible to use SSL with hiredis, but its not there by default and may need to be built against installed openssl, which would be extra steps in gem install / build process. Not 100% on this.

> I don't use any namespaces.

I think in our config loading scenario the redis usage of the cache winds up having a namespace whether you set one or not. The sidekiq one stays nil if you don't set one.

> Looking through the documentation at I'm not entirely clear on if this `hiredis-client` supports TLS?

I think it does? Or at least a) the main `redis-client` gem its part of described ssl connection in the readme and does not note that its not relevant to hiredis-client, b) the hiredis-client code area has some SSL context related code in it.

Separate tangent unrelated to your comment but something I thought of - I believe it's still possible to keep the `redis` gem in a codebase even after the sidekiq update (where sidekiq itself pulls in `redis-client and/or `hiredis-client`).

Also separately - reading about this is a maddening exercise in similarly-named things.

I'd love for someone more familiar with typical setups to confirm/reject these assumptions that I currently hold here about typical setups in current apps:

- For people who DO NOT explicitly set a namespace here, they will wind up with something like `cache:7.1` as their rails cache namespace for redis backed cache. They will not have a sidekiq namespace.
- For people who do set a namespace, the rails cache will be `<namespace>_cache:7.1` and redis will have a namespace of whatever they set.
- In both scenarios (set namespace or not), both the rails cache and sidekiq redis connections will be operating aginst redis `db: 0`

**Comment by mjankowski** [comment]
I did a little exploration here around the current spec failures -- it seems like in this branch the `Sidekiq::Testing.inline!` setting that we use to make jobs run immediately is not taking effect, and so the specs which look for the status text (which need to be published to the timeline by a background job) never show up and fail.

My guess about what's actually happening is that something changed about how sidekiq/redis get configured, and its being accidentally reloaded somewhere in our classes, and resetting itself back to the test env default (to run the fake version).

I started to work on that but am definitely in over my head on awareness of which portions of our sidekiq/redis config are specific to the prior version and may no longer be relevant, or which are relevant to our non-sidekiq usage and need to stay the same, etc.

**Comment by mjankowski** [comment]
Maybe also of note - the other things that have dependencies on `redis` gem here are:

- The `redlock` gem (req'd by stoplight), which has a newer version that uses `redis-client`, but the version reqs of stoplight (even v4) still require the older redlock that needs `redis`
- The `brpoplpush-redis_script` requirement of `sidekiq-unique-jobs`, though it appears that has some WIP to support `redis-client` as well

So, while I believe they can live side by side, we may want to monitor those to see if we hit a point of support across everything we need.

**Comment by mjankowski** [comment]
Figured out the inline/fake mode thing ... there's a configuration style we were using that some people reported breaking the behaviour during their upgrades. I changed the style to just always set it as desired instead of using the block form, and that seems to have fixed at least that portion of the spec failure here.

Still need to learn more about changing connection/pool/etc changes in the gems.

**Comment by pboling** [comment]
I just published a [security advisory](https://github.com/mhenrixon/sidekiq-unique-jobs/security/advisories/GHSA-cmh9-rx85-xj38), which is critical CSVV3.1 10/10 in severity for `sidekiq-unique-jobs`, which affects all prior versions.  Please upgrade!

**Comment by mjankowski** [comment]
There's a `sidekiq-unique-jobs` CVE out. We've already merged the 7.x fix into main - https://github.com/mastodon/mastodon/pull/29175 - I just updated this PR branch to use the 8.x branch that has the fix as well.

Separately, sometime in the last few point releases `sidekiq-unique-jobs` removed its dependency on `brpoplpush-redis_script` gem, which in turn had a `redis` dependency; so that reduces our previously listed dependencies on `redis`.

**Comment by pboling** [comment]
The brpoplpush changes were inlined into sideline-unique-jobs so the side gem is no longer needed!

**Comment by mjankowski** [comment]
I've kept this updated/rebased, but I'm not really sure how to advance this further. Feels somewhat blocked on decisions/direction on how to handle namespace migration

**Comment by renchap** [comment]
Ok, let's try to move forward on this topic.

What is really blocking here is Sidekiq 7 not supporting namespaces. We need to help people using namespaces move away from it and use databases.
But we still need to somehow support namespaces for the `app` Redis, because this is used by streaming (pub/sub does not  support databases).

What about splitting the work in two:
- first remove support for Redis namespaces in Sidekiq. This involves updating the code, documentation, and provide a procedure for people to migrate their production environment without loosing jobs (see https://github.com/mastodon/mastodon/pull/25988#issuecomment-1764876284)
- once done, a second PR to update to Sidekiq 7

If we manage to get this done in the next 3 weeks, there is a high chance we can get this released in 4.3

What do you think? I feel that the hard part is documenting and testing the migration procedure.

Related thread with a poll on namespace usage: https://oisaur.com/@renchap/111697493933269165

**Comment by mjankowski** [comment]
Rebased, updated sidekiq to 7.3.0

**Comment by renchap** [comment]
As discussed above, the big issue here is migration for people using namespaces. We definitely want to upgrade to Sidekiq 7, but we need to have a migration path for those servers.

The approach I [discussed above](https://github.com/mastodon/mastodon/pull/25988#issuecomment-1764876284) does not really work because you would loose your retries.
I think we should go with a migration script (a bit similar to "the big migration" from [this article](https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/), copying the keys from the original redis server + namespace to a new server (or redis database), stripping the namespace prefix.

This would require downtime but I dont see how we can avoid this.

As this is independent from this PR (but a pre-requisite), this should probably be implemented in a new PR, which would then unlock this one.

**Comment by mjankowski** [comment]
This has become sort of burdensome to keep rebased, will re-create something like this after namespace thing dealt with.

**Comment by mjankowski** [comment]
Sidekiq 8 released - https://www.mikeperham.com/2025/03/05/introducing-sidekiq-8.0/

We are still blocked from upgrade to 7 on namespace stuff.

**Comment by vmstan** [comment]
"Sidekiq also officially supports Valkey and DragonflyDB"

Excellent

**Comment by mjankowski** [comment]
oh-that's-excellent-gill

**Pull request closed without merging**
