### PR TITLE
Raise Mastodon::RaceConditionError if Redis lock failed

### PR DESCRIPTION
**Pull request by akihikodaki**
An explicit error allows user agents to know the error and Sidekiq to
retry.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by benpro** [comment]
Sorry for the noise on this PR.
I noticed a lot of `Mastodon::RaceConditionError` on my logs/sidekiq.
May I ask what kind of scenario make the redis lock failing?

**Comment by meZee** [comment]
@benpro same, queue is growing to 400,000+

**Comment by Gargron** [comment]
Which queue?

**Comment by meZee** [comment]
image

**Comment by meZee** [comment]
Error log being outputted by mastodon-sidekiq in journalctl
```Jan 08 21:47:34 nyc bundle[1710760]: 2021-01-09T05:47:34.894Z pid=1710760 tid=ost090nuw class=ActivityPub::ProcessingWorker jid=5822d522630807dac01a3579 elapsed=10.024 INFO: fail
Jan 08 21:47:34 nyc bundle[1710760]: 2021-01-09T05:47:34.895Z pid=1710760 tid=ost090nuw WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"default","backtrace":true,"class":"ActivityPub::ProcessingWorker","args":[245,"{\"@context\": \"https://www.w3.org/ns/activitystreams\", \"type\": \"Announce\", \"to\": [\"https://relay.libranet.de/followers\"], \"actor\": \"https://relay.libranet.de/actor\", \"object\": \"https://mstdn.foxfam.club/users/EthanVanSciver/statuses/105522963683767033\", \"id\": \"https://relay.libranet.de/activities/7907ea1e-d999-41a7-a38d-80bd73c4cc3b\"}",null],"jid":"5822d522630807dac01a3579","created_at":1610159500.08584,"enqueued_at":1610159500.0859277},"jobstr":"{\"retry\":8,\"queue\":\"default\",\"backtrace\":true,\"class\":\"ActivityPub::ProcessingWorker\",\"args\":[245,\"{\\\"@context\\\": \\\"https://www.w3.org/ns/activitystreams\\\", \\\"type\\\": \\\"Announce\\\", \\\"to\\\": [\\\"https://relay.libranet.de/followers\\\"], \\\"actor\\\": \\\"https://relay.libranet.de/actor\\\", \\\"object\\\": \\\"https://mstdn.foxfam.club/users/EthanVanSciver/statuses/105522963683767033\\\", \\\"id\\\": \\\"https://relay.libranet.de/activities/7907ea1e-d999-41a7-a38d-80bd73c4cc3b\\\"}\",null],\"jid\":\"5822d522630807dac01a3579\",\"created_at\":1610159500.08584,\"enqueued_at\":1610159500.0859277}"}
Jan 08 21:47:34 nyc bundle[1710760]: 2021-01-09T05:47:34.895Z pid=1710760 tid=ost090nuw WARN: Mastodon::RaceConditionError: Mastodon::RaceConditionError
Jan 08 21:47:34 nyc bundle[1710760]: 2021-01-09T05:47:34.895Z pid=1710760 tid=ost090nuw WARN: /home/mastodon/live/app/lib/activitypub/activity/announce.rb:28:in `block in perform'
Jan 08 21:47:34 nyc bundle[1710760]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:49:in `acquire'
Jan 08 21:47:34 nyc bundle[1710760]: /home/mastodon/live/app/lib/activitypub/activity/announce.rb:7:in `perform'```

**Comment by Gargron** [comment]
I don't know what's up with that. Maybe flushing redis would help (warning: you will lose all queued sidekiq jobs and will have to regenerate home feeds with `tootctl feeds build --all` if you do this).

**Pull request merged**
