### PR TITLE
Don't remove originals of boosted toots from timeline

### LINKED ISSUE #5097: Boosted toots jump to top of timeline
When I boost a toot far from the top of my home timeline, it immediately disappears and moves to the top of the timeline, making it hard to interact further with the toot (eg favouriting, replying).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by duxovni**
I believe this fixes #5097 . I'd like to hear from @Gargron what the original rationale was for including this line, though.

### CODE REVIEW

**Comment by Gargron** [comment]
Do people want to see duplicate original+reblog in their home?

**Comment by nullkal** [comment]
Some people toots after boost when they want to talk something related to the boosted toot. 

So, I want to see the same toot whenever some followee boosted.

**Comment by nolanlawson** [comment]
I find it annoying when the toot disappears after I boost it, yeah. I always have to remember to favorite it _before_ boosting, and as @nullkal says you can't reply after boosting without finding the toot all over again. I think maybe in this one case duplicates can be tolerated.

**Comment by nolanlawson** [comment]
OTOH this PR appears to duplicate _all_ reblogs, not just the one reblogged by the user themselves?

**Comment by sdukhovni** [comment]
I think that this PR is a good idea even if we're not dealing with toots the user boosted themselves. If I'm about to click the "favorite" button on a toot, and someone I'm following boosts that toot a second before I click, the toot will disappear from under my mouse and I'll click on some other random toot. If we don't want duplicates, then rather than removing the original we should just not show the boost.

**Comment by sdukhovni** [comment]
But yup, as @nullkal points out, not showing the boost would make "LB" posts more confusing, so I think it's fine to just have duplicates.

**Comment by sdukhovni** [comment]
Also, I believe that we still won't have duplicates in close proximity, because if a toot is already near the top of your timeline then boosts don't seem to get added to the timeline at all.

**Comment by sdukhovni** [comment]
Just checking in, are there any objections to this PR that haven't been addressed?

**Comment by charlag** [comment]
I agree, current behavior is counter-intuitive and I would rather see duplicates or see the original post.

**Review by akihikodaki — APPROVED** [review]
I'm for this change. Disappearing toots are too annoying.

**Comment by akihikodaki** [comment]
> Do people want to see duplicate original+reblog in their home?

Reblogs made in the same session do not have to be inserted anyway.

**Pull request merged**
