### PR TITLE
Document dev environment set up for Windows

### PR DESCRIPTION
**Pull request by hach-que**
This adds a work-in-progress development environment set up guide.  I'm working on Windows so I've started documenting that, though now I'm stuck at `rails db:migrate` not picking up the database configuration properly.  I'll continue figuring out the issue with that tomorrow night.

### CODE REVIEW

**Comment by Gargron** [comment]
Oh boy. Does it even work on Windows? I dread to think

**Comment by hach-que** [comment]
This is still a WIP and I'm not at a point where I have it running (still attempting to get the DB migration to work), but all the dependencies seem to be satisfied and the external deps eithee run natively on Windows or are run inside Docker (neo4j). 

That said I'm wondering now if the right way to dev is just `docker-compose up`. I'm worried about long build/restart dev cycles with that approach though.

**Comment by Gargron** [comment]
Yeah docker is more for deploying, it'd be really difficult to develop with it since you'd need to rebuild the image and restart the container on every change. Also as I said neo4j is optional and actually recently I'm contemplating just dropping it and removing follow suggestions because neo4j is a big fat mess in deployment

**Comment by hach-que** [comment]
I think follow suggestions are very useful though (I found them useful), and with Docker I'd expect deployment to be relatively trivial.

**Comment by hach-que** [comment]
(Do you not deploy with Docker to production?)

**Comment by hach-que** [comment]
Also I definitely should have gone to sleep hours ago, so I will follow up to any responses tomorrow

**Comment by Gargron** [comment]
I used Docker at first but when I started to need load balancing and faster re-deploys I've opted to just install the dependencies properly and use systemd.

**Comment by hach-que** [comment]
I'm going to close this for now since I don't think I'll get a chance to set up a proper development environment until the weekend or later.

**Comment by Gargron** [comment]
Okay, don't worry about it.

**Pull request closed without merging**
