### PR TITLE
Fix profile avatar being slightly offset into left border (fixes #20822)

### LINKED ISSUE #20822: Profile picture glitch in Mastodon 4
### Steps to reproduce the problem

1. Go to any Mastodon profile
2. Look at the profile picture

### Expected behaviour

There should be an even border around the profile picture

### Actual behaviour

There is a border to the top and right but not to the bottom and left of the profile picture

### Detailed description

The issue becomes especially pronounced when using the "Mastodon (Light)" theme.

profilebug1
profilebug2
profilebug3

### Specifications

Mastodon v4.0.2 (bug is present on both https://mastodon.social and https://zirk.us)
GNOME Web v43.0 (WebKitGTK 2.38.2)

### LINKED ISSUE #22179: Avatar border bug
### Steps to reproduce the problem

1. Visit a profile on v4.0.2 (either advanced or simple), for example this one: https://front-end.social/@moiety

messed up border around avatar

messed up border in advanced

### Expected behaviour

border looks normal, loops around

### Actual behaviour

border is broken up

### Detailed description

Seems to be caused by a `margin-left: -2px` on `.account__header__bar .avatar` in [components.scss.js](https://github.com/mastodon/mastodon/blame/e8481e67a760d901742f2af2b306557dcd9183a3/app/javascript/styles/mastodon/components.scss#L7024)

[relevant thread](https://front-end.social/@moiety/109484037335689148)

### Specifications

Mastodon 4.0.2
Checked in Chrome and Firefox

### PR DESCRIPTION
**Pull request by RiedleroD**
I don't know why it was shifted in the first place or why the width is specified twice, but this fixes the problem, so it looks fine to me.

edit: I now do know why it was shifted, but I ignored the width thing because it's not part of the PR and I don't have to touch the codebase again hopefully

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I think this was here to align the avatar with the text. Maybe moving `margin-left: -2px` to the container element would make sense.

**Review by patrick91 — APPROVED** [review]
I've done something like this in my instance to add transparent bg, it worked well :)

**Comment by hampuskraft** [comment]
@RiedleroD Would it be possible to do as @ClearlyClaire suggested and move it to the `account__header__tabs` class instead of removing the negative margin? That way, the avatar is perfectly aligned with the elements below it.

**Comment by RiedleroD** [comment]
@hampuskraft certainly, but negative margin is usually bad practice. I'll see if there's a better way to do it later today and commit the best way I can find.

**Comment by hampuskraft** [comment]
In this case, I think a negative margin is the best (if not the only) solution. But if an alternative exists, that could be interesting.

**Comment by RiedleroD** [comment]
Well if I knew more about the codebase, I'd simply remove the `overflow:hidden` that cuts off the border, and change the border into an outline, so it doesn't affect layouting. I don't know why the overflow was hidden though, because it's apparrently impossible to comment your CSS code (glaring at whoever wrote that, not looking up who it was via git blame though)

anyway, to resolve this as quickly as possible, this workaround is good enough for now. Someone should really rewrite that mess though, before too much technical debt accumulates and mastodon ends up looking like youtube or something.

**Comment by RiedleroD** [comment]
btw, someone with a working mastodon testing setup should check if my changes actually work as intended. I double- and triple-checked with the changes I make via inspector in my browser, but mastodon is important enough for that to be insufficient. I won't be setting up a whole testing environment for a two-line change though, especially as reviews are required anyway.

**Review by hampuskraft — CHANGES_REQUESTED** [review]
[Deleted for privacy reasons]

**Review by hampuskraft — APPROVED** [review]

**Comment by RiedleroD** [comment]
"Hmm I wonder why it takes this long to get looked at by the crew"

> _Pull requests that do not pass automated checks may not be reviewed_

I thought the mastodon team was lackin but it was I who was the fool all along :I

well, I'm just glad I finally looked at the contributing guidelines instead of blaming it on "gargron bad hurr durr"

**Review by ClearlyClaire — APPROVED** [review]

**Pull request merged**
