### PR TITLE
Change rate limits to 1,500/5m per user, 300/5m per app

### PR DESCRIPTION
**Pull request by Gargron**

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
I'm afraid this would let bad actors easily bypass limits by just multiplying app registrations

**Comment by trwnh** [comment]
> bypass limits by just multiplying app registrations

isn't that the point of the per-user limit? the math works out so that it assumes each user may use 5 clients

**Comment by lapineige** [comment]
Does this affect removals too ?

**Comment by ClearlyClaire** [comment]
> > 
> 
> isn't that the point of the per-user limit? the math works out so that it assumes each user may use 5 clients

Yes, you're right, I somehow missed that block :woman_facepalming: 

> Does this affect removals too ?

Yes and now, deletes fall into these limits but they also have their own separate limit which is unchanged.

**Pull request merged**
