### PR TITLE
Add a link for alternatives in sign in page and follow authorization page

### PR DESCRIPTION
**Pull request by akihikodaki**
See also #6143.
screen shot 2018-01-01 at 19 08 45

### CODE REVIEW

**Comment by akihikodaki** [comment]
https://codeclimate.com/github/tootsuite/mastodon/app/controllers/auth/sessions_controller.rb?from_sha=65f30f65&to_sha=b3a2a5d5
nonsense.

**Comment by akihikodaki** [comment]
1796fadb980848e1d049ff01d8b64119c3ffaf98:
screenshot-2018-1-20 follow tenshi - mastodon dev

**Comment by akihikodaki** [comment]
8f0460d76ac3e68ed6ab0f7bf6eabaa9d460c731 is a change corresponding to https://github.com/tootsuite/mastodon/pull/6143#issuecomment-366507462.

**Comment by Gargron** [comment]
(Sorry for year later update. Cleaning up old PRs now. We have abandoned `web+mastodon` protocol handlers so this isn't needed anymore, I believe)

**Pull request closed without merging**
