### PR TITLE
Federate custom emojis with accounts

### LINKED ISSUE #5666: Please render custom/local emojis in biographies.
Please render custom/local emojis in biographies.

I don't know if this is a bug or a feature request, but there are users who try to add those custom emojis to their bio and they are not rendered (resulting in unsatisfied users).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by davefp**
Fixes #5666 

This PR Adds an option to the `simplified_format` helper to render custom emoji.

It also adds this option to calls made from the REST account serializer and the account show partial.

Finally, there are unit tests for the new option.

I'm not familiar with the ins and outs of the various views and serializers, so if this PR puts code in the wrong place please let me know. Thanks!

### CODE REVIEW

**Review by akihikodaki — DISMISSED** [review]
The idea sounds great, but this implementation does not federate, does it?

**Comment by davefp** [comment]
I don't know. I'm not familiar enough with the codebase to recognize which bits deal with federation vs. which don't. Can you expand on which bits are problematic?

**Comment by akihikodaki** [comment]
To federate:
* the sender should attach emojis
* the receiver should receive attached emojis

For instance, the sender implementation for statuses attaches emojis
* to note as tags for ActivityPub (see `ActivityPub::NoteSerializer`)
* to post object as links for OStatus (see `OStatus::AtomSerializer`)

The receiver implementation for statuses resolves emojis
* in Create object for ActivityPub (see `ActivityPub::Activity::Create`)
* in post object for OStatus (see `OStatus::Activity::Creation`)

Similar changes is required by:
* `ActivityPub::ActorSerializer`
* `OStatus::AtomSerializer`
* `ActivityPub::ProcessAccountService`
* `UpdateRemoteProfileService`

**Comment by davefp** [comment]
Thanks! I'll take a look at this in more detail over the weekend.

**Comment by davefp** [comment]
I also want to add tests and do a little refactoring, please do not merge yet :)

**Comment by Gargron** [comment]
This looks alright, I think, is it still WIP?

**Comment by davefp** [comment]
I was hoping to add some tests, but the functionality is all there.

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
For reference, I think this is still missing the parts for rendering custom emojis within the web UI.

**Pull request merged**
