### PR TITLE
Enabel YJIT by default

### PR DESCRIPTION
**Pull request by inductor**
Reopen for https://github.com/mastodon/mastodon/pull/24091 since Ruby 3.2.2 is in the upstream

### CODE REVIEW

**Comment by shleeable** [comment]
I don't know if there are benchmarks in Mastodon specifically.. @ClearlyClaire might have something in her bag of tricks.

If there are any large instances running APMs? That can monitor the metrics from before/after for a few days?

**Review by ykzts — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
afaik YJIT may use more memory, which can be an issue when Mastodon is already memory-constrained on some setups

**Comment by renchap** [comment]
We can try this out on mastodon.online and mastodon.social, by simply setting the env variable and looking at CPU/memory usage on our various pods, as well as HTTP error rates.

I would prefer we test this on high-trafic instances before enabling YJIT everywhere, as we were hit by various YJIT-related bugs in Ruby 3.2.0 and 3.2.1.

**Comment by inductor** [comment]
@ClearlyClaire I believe that should have been solved in 3.2 (it was a thing in 3.1), though YJIT sure consumes slightly more memory than not using it.

**Pull request closed without merging**
