### PR TITLE
Use corepack yarn in `bin/setup`

### PR DESCRIPTION
**Pull request by mjankowski**
Two changes:

- For rubygems, run an update before running bundler install
- Align the yarn command with what we are using elsewhere

### CODE REVIEW

**Comment by renchap** [comment]
Do we really need to update rubygems here? This has have system-wide for the developer and I am not sure this is a good idea to do it here (where all other changes are local to the project).

All supported ruby versions should have a modern-enough gem command to install our bundler version?

**Comment by mjankowski** [comment]
Hmm, fair point re: global. 

In my experiments yesterday with devcontainers this seemed useful/desirable - but this change was also in part some preparation work for removing the post create script, which is now done by the other pr.

I'll pull down the new setup and run it all again and see if both parts here still seem needed, and follow up.

**Comment by nschonni** [comment]
DevContainers have their own script hooks, so I'm not sure this is the right spot to make these changes. I'm also not sold that DevContainers are being used as much as all the churn that is happening in them warrants

**Comment by vmstan** [comment]
> DevContainers have their own script hooks, so I'm not sure this is the right spot to make these changes. I'm also not sold that DevContainers are being used as much as all the churn that is happening in them warrants

They haven't been used because they've been broken.

**Comment by mjankowski** [comment]
Here's what I found, running on current main...

### Running devcontainer/compose directly on CLI

First step runs fine, no errors.

Second step outputs this as part of setup:

```
❯ docker compose -f .devcontainer/docker-compose.yml exec app bin/setup
== Installing dependencies ==

A new release of RubyGems is available: 3.5.9 → 3.5.11!
Run `gem update --system 3.5.11` to update your installation.
```

It then also prompts (in a way that pauses setup for input) for corepack to install yarn, which we can avoid by having this explicit enable in place.

In the aftermath of the install, ruby -v shows `3.3.1` which I think is coming from the base image, which has not been updated to 3.3.2 yet.

Running `bin/dev` from CLI compose also works fine, launches process with 3.3.1.


### Running from vscode devcontainer integration...

First step is fine, although as an aside, the integration works by running both the project compose file AND a compose file from the vscode-remote extension together. I think this doesn't matter, just noting it as difference.

Same rubygems version warning

Same corepack prompt

Install finishes and I get a vscode error from the Ruby LSP extension like:

```
Automatic Ruby environment activation with rbenv failed: Command failed: rbenv exec ruby -W0 -rjson -e 'STDERR.print({env: ENV.to_h,yjit:!!defined?(RubyVM::YJIT),version:RUBY_VERSION}.to_json)' rbenv: version `3.3.2' is not installed (set by /workspaces/mastodon/.ruby-version)
```

I think what’s happening there is that the image has 3.3.1 installed and is just happily running the app with that, and since nothing in our install/run process actually relies on rbenv or .ruby-version that’s all fine — but then the editor/LSP integration DOES try to use rbenv with the .ruby-version and that error pops up.

### Next steps

Given all that, I think we should:

- At least do the corepack enable portion of this PR
- Maybe do ruby gems update
- Maybe add an `rbenv install $(cat .ruby-version)` step somewhere? … probably either in the postCreateCommand, or maybe earlier in the Dockerfile directly?

**Comment by mjankowski** [comment]
> DevContainers have their own script hooks, so I'm not sure this is the right spot to make these changes.

I would love feedback from any Docker/devcontainers experts on where to best put these commands.

**Comment by mjankowski** [comment]
Pushed update to this PR to remove the rubygems update part -- this is just the addition of `corepack enable` (and some style/cleanup) changes now.

**Review by renchap — APPROVED** [review]

**Comment by renchap** [comment]
Looks good to me.

For the `gem update` + correct Ruby installation, I think those are specific to dev containers (or containers), not the generic `bin/setup` script, and that those should only be executed in the containers, so those commands would belong to either the dockerfile (with the benefit that it gets cached) or a post install script.

Ideally with the devcontainer base image, the specific Ruby version we use will only be installed if the base container does not have it installed already (if they already use `rbenv` to install Ruby, then running `rbenv install` again should do nothing?)

**Review by renchap — APPROVED** [review]

**Pull request merged**
