### PR TITLE
fix: set s3_acl_enabled to false when s3_permission empty

### PR DESCRIPTION
**Pull request by everpcpc**
for: https://github.com/mastodon/mastodon/issues/17978

A `kt-paperclip` upgrade is also needed, e.g.  https://github.com/kreeti/kt-paperclip/pull/80

### CODE REVIEW

**Comment by shleeable** [comment]
If this sets any kind of default. Please add it to the .env.production file

**Comment by Gargron** [comment]
What is the replacement for ACL? Setting media to private on suspension is a pretty important function.

**Comment by everpcpc** [comment]
> What is the replacement for ACL? Setting media to private on suspension is a pretty important function.

there is a `Bucket owner enforced` mode to use policy for bucket
https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html

**Comment by everpcpc** [comment]
> What is the replacement for ACL? Setting media to private on suspension is a pretty important function.

Since we usually want our s3 bucket to be private entirely and serve files via CloudFront, maybe we could change this way suspension media. For example by moving them to specific path with special bucket or CloudFront policy?

**Comment by lgE-1** [comment]
This option is also necessary for other s3 services which donot support ACLs such as Clouflare R2.

**Comment by everpcpc** [comment]
https://github.com/kreeti/kt-paperclip/pull/92
has been merge, and we need to wait for this commit release

**Comment by everpcpc** [comment]
Seems like we can just set this option with `S3_PERMISSION`, update.

**Review by mjankowski — APPROVED** [review]

**Comment by ThisIsMissEm** [comment]
This currently has a "won't fix" label, though it looks like it was automatically added — is this still something that's necessary or desired?

**Comment by mjankowski** [comment]
Based on rebase needed and sheer age - closing this. Please rebase/reopen if still relevant.

**Comment by everpcpc** [comment]
I've rebased this, but I did not see any `reopen` button

**Pull request closed without merging**
