### PR TITLE
fix #4356 : missing sw.js in Docker environment

### LINKED ISSUE #4356: The file sw.js is not found
I upgraded Mastodon to `v1.5.0rc1` (tagged release), but `sw.js` is not found.

https://mastodon.noraworld.jp/sw.js

I found `sw.js` on other instances, which version is `v1.5.0rc1`. I heard this is a specific problem with a deployment on Docker, which means it does not occur on non-Docker deployment. My instance is deployed with Docker.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by skoji**
This patch should fix #4356 .

### CODE REVIEW

**Comment by skoji** [comment]
Yes, mounting directories that does not change to a docker container is not normal.

To avoid this, I've considered other fixes (e.g. generate sw.js in `public/assets` directory and add `public/sw.js` symbolic link that points to `public/assets/sw.js`), but this kind of fix (or workaround) “exposes”  a fix of docker-specific problem to non-docker environment.  I think it is not desirable.

**Comment by skoji** [comment]
I've implemented symbolic-link version.
https://github.com/skoji/mastodon/commit/58c748c8c62cb48734022a8c677831257512e5ab
If this is preferable,  I'll replace this PR with this commit.

**Comment by Gargron** [comment]
This might be fine..? I think if people kept the host-side volume mappings of the default (e.g. public/assets, public/system pointing to their in-docker counterparts) this change shouldn't break anything. Otherwise they'd have to move system and assets folders into a common folder. Want some input on this @Wonderfall

**Comment by Wonderfall** [comment]
Mounting the entire public folder will break a few things from Mastodon if the person is using the image from Docker Hub directly or is not using a volume not corresponding to the repository of Mastodon.

I prefer the other version.

**Comment by Gargron** [comment]
I like this. But I can't test if it works as expected since I don't use Docker in production. @Wonderfall: this okay? @ikuradon: would this likewise solve the problem in your opinion?

I might prefer it over #4357 for simplicity (less changes)

**Comment by Wonderfall** [comment]
It's okay for me, it's simple and should do the trick.

**Comment by nightpool** [comment]
I'm a fan of this one, although it might cause problems for non-docker users who already have an sw.js, if they don't clear their assets before cloning the repository?

**Comment by ikuradon** [comment]
Looks good to me, but i don't know that symlinks work with every environments.

**Comment by skoji** [comment]
@nightpool 

>  it might cause problems for non-docker users who already have an sw.js

Yes. But it is not a problem for released version users.
v1.5 Release candidate or `master` users may already have an `sw.js` and released version (<= v1.4.7) users do not have one.

**Comment by skoji** [comment]
I'm running this version on [my single user instance](https://sandbox.skoji.jp) and it is working fine.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
