### PR TITLE
Change preview cards to not be fetched/displayed on sensitive statuses

### LINKED ISSUE #13435: CW or sensitive media mention from PeerTube
Hello,

When a video is marking as sensitive on PeerTube, Mastodon show the media and its thumbnail on the timeline. To keep the Fediverse a safe place, I think it couldn't.

As mentionned on this issue on the PeerTube package :

> PeerTube correctly send the sensitive AP attribute, and Mastodon inserts it in its database. But you can't really see it on Mastodon because AFAIK sensitive attribute acts only on medias 
> https://github.com/Chocobozzz/PeerTube/issues/2597#issuecomment-610250273

Can you envisage to do something for that ?

Thank you :)

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #13435

### CODE REVIEW

**Comment by endokai** [comment]
为什么不能使用“始终显示标记为敏感介质”设置，而直接禁用所有存储卡预览？ 带CW的预览卡不能直接预览。 现在所有的敏感链接都不会被预览。 为什么不能像Mastodon一样使用“敏感标记”设置？

**Comment by kuoncp** [comment]
Why just disable all  card preview directly? The preview card with CW does not preview directly. and now all the sensitive links will not be previewed. Why we can't use the "sensitive mark" setting like inside Mastodon?

**Comment by ThibG** [comment]
@kuoncp I am not sure what you mean, this change only makes it so that statuses marked as sensitive don't fetch/display preview cards. In Mastodon, `sensitive` statuses are those for which media are marked sensitive.

For the most part, this will not change anything, since preview cards are not fetched/displayed when there are media attachments.

What it does change is that videos coming from Peertube that are marked sensitive won't have a preview card created/displayed in Mastodon (#13435)

**Comment by kuoncp** [comment]
I know there are too many ways to hide the preview card, attach media, add CW, or make it not in the first position, it will be hidden. But it is not configurable,  because it is the same configuration for everyone. (show or hide).
After the CW is added, even if the we has set "Always expand toots marked with content warnings", Preview card will not be displayed. Even if the only reason is because of add CW.
If all the preview cards with sensitive marks will not be generated, then all NSFW links will not be displayed no matter what.

**Comment by ThibG** [comment]
Yeah, this means that it will be the sender's choice to disable preview cards, by setting the `sensitive` flag. Note that the Web app only ever sets that flag when sending media, which presence already prevents preview cards. So I can't really see the downside of this.

**Comment by kuoncp** [comment]
You haven't considered the issue of NSFW content creators, they need to add CW to Toot and media with sensitive tags to prevent everyone from easily seeing them. But flowers can still see content and media by clicking, or by setting "Always show sensitive content."
Back to the preview card, there are some reasons why external links are not used instead of Mastodon. The first is that the picture only allows 1280x1280, and the second is the video only allows 40M size. or just want to share a  external link. I know the media size limit can be modifying the source code, but that will broken federation, so external links are required. If you don't set the "sensitive" label at the link, everyone will see it. But if the link is set to "sensitive", everyone can not see it. Can't use personal settings to perform different actions like media sensitive tags

**Comment by kuoncp** [comment]
And, for PeerTube, it can be federated with Mastodon (ActivityPub). But its display in Mastodon depends on the preview card. If you block all videos with "sensitive" tags, then all PeerTube sensitive videos will not be previewed in Mastodon, it will just be displayed as a link without a player.
So your modification will cause PeerTube NSFW video will not be displayed in Mastodon.
PeerTube's setting for these NSFW videos is that the site level can set whether to display NSFW videos (displayed, blurred, not listed). But personal level can also set whether to display these NSFW content.

**Comment by kuoncp** [comment]
> 
> 
> And, for PeerTube, it can be federated with Mastodon (ActivityPub). But its display in Mastodon depends on the preview card. If you block all videos with "sensitive" tags, then all PeerTube sensitive videos will not be previewed in Mastodon, it will just be displayed as a link without a player.
> So your modification will cause PeerTube NSFW video will not be displayed in Mastodon.
> PeerTube's setting for these NSFW videos is that the site level can set whether to display NSFW videos (displayed, blurred, not listed). But personal level can also set whether to display these NSFW content.

PeerTube in Mastodon: https://mastodon.social/web/accounts/275808

**Comment by kuoncp** [comment]
If you block a preview of all sensitive links, then PeerTube ’s NSFW will only be displayed as a title and a link, no image and player. Everyone needs to open the link to PeerTube, The sense experience drops significantly

**Comment by kuoncp** [comment]
We hope to treat the content inside and outside fairly. Both inside and outside are configurable. Rather than simply block all the outside sensitive content

**Comment by kuoncp** [comment]
Your idea is just "Everyone shouldn't be able to see the sensitive link preview content", without considering "Many people don't want to see this content, but some people want to see this content".
This answer is like why Mastodon does not ban NSFW and has a sensitive media mark.

**Comment by ThibG** [comment]
Yeah the only thing that would change is not having a preview, just the link, that would still be here.

We *could* still fetch the preview card, but only display it when the “media display” setting is set to “always show media”, but it wouldn't be entirely consistent with what we already have, and, I guess, possibly confusing.

**Comment by kuoncp** [comment]
I think the behavior of the preview card should be the same as the "sensitive media mark", It will always be generated when without additional media, and should not be influenced by CW. When the link sends a sensitive label, blur the preview card, and use the setting of "Always show sensitive media".

**Comment by ThibG** [comment]
#13985 implements client-side special handling of preview cards. In the case of a Peertube video, this would not hide the title/short description but at least it would blur the preview.

**Pull request closed without merging**
