### PR TITLE
Change favourites to likes

### LINKED ISSUE #13268: Rename "Favorite" to "Like"?
### Pitch

Rename "Favorite" to "Like"

### Motivation

Now that bookmarks are a thing, there might be some value in renaming the "Favorite" feature to "Like". I think it'd be more familiar to newcomers and "like" doesn't sound as serious as "favorite", so it might make the feature more used causing more internet love to be distributed 🥰

### PR DESCRIPTION
**Pull request by Gargron**
Fix #13268

### CODE REVIEW

**Review by ykzts — DISMISSED** [review]

**Comment by ClearlyClaire** [comment]
Some tests hardcode the “favorite” language and should be updated.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by IGLOU-EU** [comment]
Why keeping "favourite" into code function and var names ? This could interfere with code readability.
Same for "favorite-fill.svg", this is no longer a "favorite, keeping it for file name is a little bit disturbing.

**Comment by ClearlyClaire** [comment]
`favorite-fill` is the name of the icon in Material Symbols, not our choice

**Comment by Gargron** [comment]
Sorry, closing for now.

**Pull request closed without merging**
