### PR TITLE
Adds instructions for adding admin users for Heroku installs

### PR DESCRIPTION
**Pull request by ashfurrow**

### CODE REVIEW

**Comment by Gargron** [comment]
You don't have to use the heroku CLI, you can use the rails task `USERNAME=yourUsername rails mastodon:make_admin` through the heroku runner

**Comment by ashfurrow** [comment]
I didn't know that, would you like an amended pull request?

**Comment by Gargron** [comment]
Yes! I would like that

**Comment by ashfurrow** [comment]
Done 👍

**Pull request merged**
