### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by ErikXXon**
I added the Swedish translation file for Matodon

### CODE REVIEW

**Review by ykzts — DISMISSED** [review]
https://github.com/tootsuite/mastodon/blob/3e2f79394891bae1a0afbf8899855a0b10ef9e15/config/application.rb#L31-L63

https://github.com/tootsuite/mastodon/blob/3e2f79394891bae1a0afbf8899855a0b10ef9e15/app/helpers/settings_helper.rb#L4-L37

Add languages settings.

**Comment by ykzts** [comment]
This Pull Request is Work In Progress?

**Comment by ErikXXon** [comment]
Yes still work i progress with a couple of the files - pull rest of them in a few days

**Comment by ErikXXon** [comment]
All of the Swedish language file adden now

**Review by ykzts — APPROVED** [review]

**Pull request merged**
