### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by tribela**
Mastodon 2.1.0 has moderation and invitation functions.
I translated related it and some javascript file.

But there's a few problem. 

1. I cannot find these messages(_Max uses_, _Expires in_) on locale file.
image

2. I cannot translate 이/가, 은/는(It mean "is" but different character depending on character in front).
It's like "you _are_" and "I _am_"

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
Purely from a file structure point of view, this looks good. I ran both the `yml` and `json` through validators. Both are valid. 👍 

EDIT: My validation checks are now invalid as files have since changed.

**Comment by SerCom-KC** [comment]
> I cannot find these messages(Max uses, Expires in) on locale file.

You'll have to edit `config/locales/simple_form.ko.yml`. Obviously you'll have to either run `bundle exec i18n-tasks add-missing ko` (see the [documentation](https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md#key-usages) for details) or add them manually.
In English locale file they're at [line 38](https://github.com/tootsuite/mastodon/blob/a29432f0cdb8e20d89789091235d56c522c53542/config/locales/simple_form.en.yml#L38) and [line 33](https://github.com/tootsuite/mastodon/blob/a29432f0cdb8e20d89789091235d56c522c53542/config/locales/simple_form.en.yml#L33).

**Comment by Kjwon15** [comment]
Thanks @SerCom-KC. I'll work on that file.
I ran `i18n-tasks add-missing ko`  but `config/locales/simple_form.ko.yml` doesn't changed. Did I something wrong?

**Comment by Kjwon15** [comment]
Oh, it's ignored on `config/i18n-tasks.yml#L40-42`. but why..

**Comment by SerCom-KC** [comment]
> Oh, it's ignored on `config/i18n-tasks.yml#L40-42`. but why..

I didn't notice that...
@Gargron Is this expected one?

**Review by ykzts — APPROVED** [review]

**Pull request merged**
