### PR TITLE
Add japanese translations for custom emoji.

### PR DESCRIPTION
**Pull request by mayaeh**
Add japanese translations for Custom emoji.

"alphanumeric" is translated "英数字" in Japanese.
But I adopted "半角英数字" meaning "Half size alphanumeric characters".

Because there are 2 bytes of alphanumeric characters in Japanese characters.
e.g. ＡＢＣ，１２３

### CODE REVIEW

**Comment by lynlynlynx** [comment]
Please modify these two below,
- `image_hint` should not contain spaces around 50KB and PNG same as icon and header sections.
- `shortcode_hint` should be "2文字", no space, same as username and bio sections.

----

Personally I think about `destroyed_msg`

I think using popular joke "Emojo" as it is is more humorous.
"Emojoは消滅しました！" :thinking:
Hmm, difficult, needs more opinions...

**Comment by mayaeh** [comment]
Thank you.
Emojo ... 🤔

**Comment by mayaeh** [comment]
I read https://github.com/tootsuite/mastodon/pull/5002#discussion_r139579169
( thanks for lynlynlynx )

I adopted it because it felt interesting about Emojo.
But I think many Japanese people Won't know it's Joke.

I'm worrying about restoring destroyed_msg.

**Comment by mayaeh** [comment]
Restore destroyed_msg.

**Comment by lynlynlynx** [comment]
I discussed with Japanese on Mastodon, and finally I agree with translating usually.

**Review by Gargron — APPROVED** [review]

**Pull request merged**
