### PR TITLE
Remove hiredis driver for Redis

### LINKED ISSUE #19824: hiredis does not support SSL (NotImplemented)
### Steps to reproduce the problem

1. use an SSL redis server
2. try booting up Mastodon
3. profit

### Expected behaviour

Mastodon boots and works normally

### Actual behaviour

Fails to even start - you get "hiredis does not support SSL"

### Detailed description

I'm using Heroku with modifications in https://github.com/haydenwalker980/mastodon, premium 0 plan for Redis

Full traceback:
```
2022-11-06T01:27:18.771601+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e]   
2022-11-06T01:27:18.771616+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e] NotImplementedError (SSL not supported by hiredis driver):
2022-11-06T01:27:18.771617+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e]   
2022-11-06T01:27:18.771618+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e] app/models/ip_block.rb:38:in `blocked?'
2022-11-06T01:27:18.771619+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e] config/initializers/rack_attack.rb:46:in `block in <class:Attack>'
```

### Specifications

Ruby 3.0.4
Mastodon [58fc889](https://github.com/mastodon/mastodon/commit/58fc889c6fe697da4f880cb43e75d97d3a604d79)

### PR DESCRIPTION
**Pull request by Gargron**
Fix #19824

### CODE REVIEW

**Comment by renchap** [comment]
@mperham Hi Mike!

This change has a potentially large impact on Sidekiq's performance for Mastodon. We spawn a lot of jobs (around 100M per day on mastodon.social), with huge spikes on some actions.

Other people worried that moving away from `hiredis` will cause perf problems, what would you advise?

**Comment by mperham** [comment]
Sidekiq 7 has moved away from redis-rb to the newer redis-client gem so depending on hiredis will make a future migration to Sidekiq 7 harder.

https://github.com/redis-rb/redis-client

There is a corresponding hiredis-client gem which I believe does support TLS.

https://github.com/redis-rb/redis-client/tree/master/hiredis-client

Regarding performance, it's always hard to guess. hiredis has always had a noticeable 10-20% improvement in Redis performance but that doesn't mean you'll notice a big slowdown. Most of your job performance will still be dominated by the remote side. I generally advise people to avoid hiredis unless they absolutely need the performance, it is a native gem which can crash the VM.

@byroot is the best person to talk to about large scale Redis usage in Rails apps.

**Comment by byroot** [comment]
You don't have to remove `hiredis` just now, you can just make pass `driver: :ruby` if the redis connection parameters show it needs SSL.

Also yes, once you upgrade to redis-rb 5.x, you can use the hiredis bundings with SSL (via the `hiredis-client` gem).

**Comment by mperham** [comment]
Sounds like the optimal solution is to migrate to redis-rb 5.x and then you can opt into hiredis and/or TLS if you want.

**Comment by nametoolong** [comment]
There are still several "false" pipelining calls in the codebase. They work on hiredis thanks to the async support but will no longer pipeline on redis-rb which is a **real** performance hit.

https://github.com/mastodon/mastodon/blob/6a5e447753095606e42cc3899887ba7fae77a0e8/app/lib/feed_manager.rb#L276-L296

**Comment by byroot** [comment]
@nametoolong no idea what you are talking about, pipelining absolutely work with the `:ruby` driver even on redis-rb 4.x.

**Comment by nametoolong** [comment]
@byroot https://github.com/redis/redis-rb#pipelining

> Commands must be called on the yielded objects. If you call methods on the original client objects from inside a pipeline, they will be sent immediately:

The code snippet calls redis directly. Nasty but works with hiredis.

**Comment by byroot** [comment]
> Nasty but works with hiredis.

That has nothing to do with `hiredis`, it's about `redis-rb 4.x` vs `redis-rb 5.x.`

Also these are absolutely trivial to fix.

**Comment by nametoolong** [comment]
> That has nothing to do with `hiredis`, it's about `redis-rb 4.x` vs `redis-rb 5.x.`

You are right. Just want to put a reminder here (some of the calls are somewhat deep). Apologies for the noise.

**Pull request closed without merging**
