### PR TITLE
Fix OpenGraph meta tag's translation error

### PR DESCRIPTION
**Pull request by mayaeh**
After #6818 , "translation missing" is displayed in og: description of OGP meta tag on toot direct link  in untranslated language.
This PR will fix it.

before:

after:

### CODE REVIEW

**Comment by mayaeh** [comment]
Please wait for the merge yet.
I am looking at problems pointed out at Mastodon.

**Comment by Gargron** [comment]
Odd. It should definitely just fallback to the `en` locale in production?

**Comment by tateisu** [comment]
if fall back to non-en language, it may reproduct missing translation. I think fallback to en is mandatory.

**Comment by mayaeh** [comment]
Sorry, I chose this approach because I could not find any other way.
I thought en would be better than choosing a language that might not have a translation.

**Comment by Gargron** [comment]
This code:

https://github.com/tootsuite/mastodon/blob/master/config/application.rb#L78-L83

Should've made sure than when the default locale is not English, missing translations still fallback to English. Why is it not working then?

**Comment by unarist** [comment]
https://github.com/tootsuite/mastodon/blob/a5c6c748e096f61d00bbd778a263e22117e1ae9f/config/application.rb#L79-L81

https://github.com/tootsuite/mastodon/blob/a5c6c748e096f61d00bbd778a263e22117e1ae9f/config/environments/production.rb#L57-L59

Well...it is overwritten.

**Comment by MitarashiDango** [comment]
In my environment this phenomenon was reproduced.
Also, it was confirmed that `DEFAULT_LOCALE` of `.env.production` is affecting.
Is this the intended behavior?

**Comment by Gargron** [comment]
>Well...it is overwritten.

@akihikodaki aaaaaaaaaaaaaaa

**Comment by akihikodaki** [comment]
I'm really sorry. Recently I had two bugs, including this, which cannot be reproduced on my development environment, but I think I could find out them before it gets merged if I was careful enough.

I'm preparing a fix and submit shortly.

**Comment by ineffyble** [comment]
@mayaeh This issue was addressed by #6843 - are you happy to close?

**Comment by mayaeh** [comment]
Thank you for being taught.
I am also checking merging # 6843 in my environment.
Please let me close this after that running.

**Pull request closed without merging**
