### PR TITLE
Make the header a blurred background on profiles and conversation pages

### PR DESCRIPTION
**Pull request by mkody**
Related to #1040

Some screenshots:
- [Profile](https://cloud.githubusercontent.com/assets/843787/24761827/d079fe80-1aec-11e7-9a4a-b1ee0ce70579.png)
- [The "NEXT" button was themed a bit to make it visible in case of light background](https://cloud.githubusercontent.com/assets/843787/24761834/d4cc551e-1aec-11e7-8a83-9af8e41aab10.png)
- [Toots](https://cloud.githubusercontent.com/assets/843787/24761836/d6db64bc-1aec-11e7-8bfc-bf5e57a64362.png)

_Edit: and live [here](https://im-in.space/@kdy) or [here](https://im-in.space/@E1000)._

### CODE REVIEW

**Review by riking — APPROVED** [review]

**Comment by eramdam** [comment]
I'm taking liberties and commenting on this.

- You don't seem to use the prefixed version of `filter`. Some browsers don't support the unprefixed version yet IIRC.
- It doesn't seem like you have a fallback for browsers that just don't support CSS filters altogether. Edge is one of them and probably some mobile users. You should probably use [`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) to detect them and hide the full bleed background image in that case
- Since GIFs are supported in headers, it might be very problematic in terms of performance since CSS filters are very costly in terms of computation in the way they're implemented in browsers as of right now. I know @Gargron has some ideas regarding that issue but that's definitely something to consider.

**Comment by mkody** [comment]
Thanks for the comments!

Except IE, every browser seems to support filters without any prefix. http://caniuse.com/#feat=css-filters 
And you're right, `@supports` should be used! :+1: 

For the gifs in headers, if there's at least a way to only get the first frame, I'm pretty sure that'd do it. Like a `@account.header.url( :original_static )` or something? (I'm not used to Ruby to know how to implement that properly.)

**Comment by Gargron** [comment]
Generating static versions is indeed what I had in mind. A bit worried about using more disk space, but statics would be just a fraction of the original filesize... Also, maybe could only generated static copies for gifs, not other formats - for other formats just link the same file in both original and original_static.

**Comment by Gargron** [comment]
I gave this a go, and it introduces quite a noticeable lag on Firefox/Linux and even Chrome. So even though I added static avatar/header versions just for this to work, it's not looking good right now :/

**Comment by expenses** [comment]
@Gargron Would it be ok to for the instance to generate the static, blurry backgrounds so the browser doesn't need to blur them?

**Comment by mkody** [comment]
I'm a bit surprised for the lag, I didn't notice any, even when resizing, on my old laptop (macOS with Chrome), my desktop Linux or on mobile/tablet (Android).

**Comment by Gargron** [comment]
In the end I think we're fine without this, sorry but thank you for the contribution.

**Pull request closed without merging**
