### PR TITLE
Change to single opt-in during profile setup in onboarding in web UI

### PR DESCRIPTION
**Pull request by Gargron**
Unite `discoverable` and `indexable` settings under a single "Make my profile discoverable" opt-in, add "Recommended" badge and check it by default.

image

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
The translation files need updating.

Design-wise, I don't feel very strongly either way about this, having simple initial presets is good, and these ones make sense. My only concerns are I'm not sure it makes the fact that finer controls are available really stand out, and that re-visiting this doesn't let you recover any finer-grained setting you may have chosen (but this is a really minor thing as you need to manually navigate to the paths to see this screens again)

**Review by ClearlyClaire — APPROVED** [review]

**Comment by joenepraat** [comment]
I thought there was a consensus that the new search feature was opt-in by default. Now it looks like opt-out by default. I suggest to reverse that, incl. the _recommended_ word. 

I would also advise to add the text  'you can fine-tune this in your privacy settings'.

**Comment by ClearlyClaire** [comment]
> I thought there was a consensus that the new search feature was opt-in by default. Now it looks like opt-out by default. I suggest to reverse that, incl. the _recommended_ word.

These settings are still off by default for both old and new users (the screenshot being shown is not the initial state).

> I would also advise to add the text 'you can fine-tune this in your privacy settings'.

I kinda agree, although the text is already pretty long.

**Comment by joenepraat** [comment]
@ClearlyClaire Thank you! That is a relief. I'm absolutely in favour of presets. Years ago I also made the suggestion use presets. Keep up the good work!

**Pull request merged**
