### PR TITLE
Build FFmpeg ImageMagick for make them without x11 dependencies on Docker

### PR DESCRIPTION
**Pull request by sinoru**
## Overview
This PR includes #26861 (Can be merged separately, but requires #26861 first)

FFmpeg and ImageMagick from debian is dependent on X11 server which is unnecessary for the server and mastodon.
So this will compiled it self, and Docker will cache them.

##### Time
3:56.72 total (+01:19.03 total)

###### Base Image
2:04.27 total

###### Main Image
1:52.45 total

##### Size
941.35MiB (-288.8 MiB)

###### Base Image
413.19 MiB

##### Time
2:37.69 total

##### Size
1,230.15MiB

## Alternatives

Might be using official static binaries from them(FFmpeg, ImageMagick). Which is little larger than this PR, but can approach this PR's goal.

### CODE REVIEW

**Comment by shleeable** [comment]
I would be interested in a two stage build. Build the base image with the node/ruby/ffmpeg/imagemagick compiled... and then that is built and uploaded to the hub... then the local image can just build the local environment

**Comment by sinoru** [comment]
> I would be interested in a two stage build. Build the base image with the node/ruby/ffmpeg/imagemagick compiled... and then that is built and uploaded to the hub... then the local image can just build the local environment

Oh, you means two stage for not Dockerfile-level, make a base image separately?

**Comment by shleeable** [comment]
> > I would be interested in a two stage build. Build the base image with the node/ruby/ffmpeg/imagemagick compiled... and then that is built and uploaded to the hub... then the local image can just build the local environment
> 
> Oh, you means two stage for not Dockerfile-level, make a base image separately?

I'm not against it. Considering the ecosystem is a known good.

**Comment by sinoru** [comment]
> > > I would be interested in a two stage build. Build the base image with the node/ruby/ffmpeg/imagemagick compiled... and then that is built and uploaded to the hub... then the local image can just build the local environment
> > 
> > 
> > Oh, you means two stage for not Dockerfile-level, make a base image separately?
> 
> I'm not against it. Considering the ecosystem is known.
> 
> We could take all of the compiling out of the local build.

Okay. I try to make another Dockerfile for base image.
Which will copy ruby and node from official docker image,
compile ffmpeg and imagemagick locally.

And using this image as `FROM` on origial Docker for mastodon. That is your suggestion, right?

**Comment by sinoru** [comment]
Test will be failed due to base image is not available in online. But works on my machine perfectly.

@shleeable How about this? https://github.com/mastodon/mastodon/pull/27098/commits/fae6a999168c296879170337ed0cc06011ec9eee

**Comment by shleeable** [comment]
Let's speak with the others, but I believe this might be a good path to take.

**Pull request closed without merging**
