### PR TITLE
Change example nginx configuration to reduce downtime during server restarts

### PR DESCRIPTION
**Pull request by shleeable**
> Inspired by https://blog.winricklabs.com/(2-08-2020)-fixing-nginx-502-gateway-timeout-with-proxy_pass-during-deployments.html

http://nginx.org/en/docs/http/ngx_http_upstream_module.html

### CODE REVIEW

**Comment by shleeable** [comment]
Inspired by https://blog.winricklabs.com/(2-08-2020)-fixing-nginx-502-gateway-timeout-with-proxy_pass-during-deployments.html

**Comment by shleeable** [comment]
I believe this can be merged any time. Tested.

**Comment by kedamaDQ** [comment]
It works fine on my server.

**Review by Gargron — APPROVED** [review]

**Comment by Gargron** [comment]
Please rename the PR to be [changelog-ready](https://keepachangelog.com/en/1.0.0/)

**Comment by Gargron** [comment]
Please rename the PR to be changelog-ready (add, change, remove, fix, with focus on the effect that either end-users or sysadmins will understand). E.g. "Update nginx.conf for upstream_module" carries no easy to understand meaning. What is upstream_module? Why does it matter? What does "Update" mean, it could mean it was edited, or it could mean a newer version has been pulled from somewhere else. "Change example nginx configuration to reduce downtime during server restarts" would be changelog-appropriate.

**Pull request merged**
