### PR TITLE
Add more explicit explanations about author attribution and `fediverse:creator`

### PR DESCRIPTION
**Pull request by ClearlyClaire**
image

### CODE REVIEW

**Comment by mjankowski** [comment]
There's not really enough room to do this inline, but I wonder if this area could benefit from a link to the announcement blog post for the feature, and/or something on docs site, and/or (when this exists) link to a standards doc or something?

**Comment by trwnh** [comment]
> and/or (when this exists) link to a standards doc

speaking of standards, are we going to revisit or reconsider the concerns raised by the community after this tag was introduced? https://github.com/mastodon/mastodon/pull/30398

**Review by renchap — APPROVED** [review]

**Comment by renchap** [comment]
> speaking of standards, are we going to revisit or consider the concerns raised by the community after this tag was introduced? #30398

We are following the discussions in https://github.com/swicg/activitypub-html-discovery and will add support for the standard once it has been defined.

**Comment by eishiya** [comment]
Having encountered this in the wild before seeing this PR, I was very confused as to what this meant and what it was for. Most often I saw this on links by the author (which I suspect will be the most frequent scenario), so it felt redundant, and the "More" part doesn't go anywhere, so I couldn't tell if this was something added because the user posted it or part of the link card, or what. I was expecting it to perhaps link to other links attributed to the author, but it just goes to their profile - which is sensible given the intent of this PR, but not what the context sets up.

I support attribution like this, but I think the "More from {USER}" text is ambiguous if you don't already know what you're looking at. Perhaps "By {USER}" might be enough, since the name already looks clickable? I don't think there's a need for a half-hearted call to action in there.

**Pull request merged**
