### PR TITLE
Fix incoming status creation date not being restricted to standard ISO8601

### LINKED ISSUE #27639: document_parsing_exception errors from a status with an invalid date
### Steps to reproduce the problem

1. Unclear how we acquired this status, but [this post](https://mk.itzti.li/notes/9la79fmeadxw63t4) arrived in our instance with an invalid timestamp:

```
created_at: Thu, 07 Nov 11968 17:22:13.599000000 UTC +00:00,
updated_at: Sat, 28 Oct 2023 15:09:01.341614000 UTC +00:00,
```

2. since then, a sidekiq job fails once per minute trying to deal with this status:

```
Oct 31 15:05:09 - bundle[3249279]:       `{"type"=>"document_parsing_exception", "reason"=>"[1:62] failed to parse field [last_status_at] of type [date] in document with id '47476'. Preview of field's value: '11968-11-07T17:22:13.599Z'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [11968-11-07T17:22:13.599Z] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}`
```

### Expected behaviour

Sidekiq should be able to deal with whatever statuses it might encounter

### Actual behaviour

Sidekiq dies dealing with this status once per minute

### Detailed description

_No response_

### Mastodon instance

cosocial.ca

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v16.20.2

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #27639

### CODE REVIEW

**Review by renchap — CHANGES_REQUESTED** [review]
Looks good, but could you add a few tests for invalid dates?

**Comment by ClearlyClaire** [comment]
Done!

**Review by renchap — APPROVED** [review]
LGTM.

Maybe we should restrict the year a bit more, as `0..9999` is quite wide and statuses cant have been created before 1900, and 9999 is far away?

But maybe it has some uses, for historical content?

**Comment by mjankowski** [comment]
I think the error in that linked issue is coming from the sidekiq job trying to push a status into elasticsearch, and the error is on the ES side trying to parse the date. I think ruby could parse this as iso8601 and PG could save it as such, and the issue is at the ES indexing level?

It feels sort of weird to modify an incoming reported time ... but on the other hand anything out of this range is almost definitely error data so either rejecting outright or changing like in this PR both seem reasonable given that likely condition.

**Comment by ClearlyClaire** [comment]
Yeah, the error was on Elasticsearch's side, but the thing is, Elasticsearch is just one of the consumers, when we serialize the posts in the REST API, we officially serialize them using ISO 8601, but that does not support years outside the 0-9999 range unless separately specified.

**Comment by ClearlyClaire** [comment]
> Maybe we should restrict the year a bit more, as `0..9999` is quite wide and statuses cant have been created before 1900, and 9999 is far away?
> 
> But maybe it has some uses, for historical content?

I think it's best to be future-proof and also allow people doing silly things as long as it doesn't break stuff.

**Comment by renchap** [comment]
Let's merge it then! 👍

**Comment by joenepraat** [comment]
@ClearlyClaire @renchap Any change this can be released as a hot-fix? It can be manually fixed by going into the database or using the rails console, but that's not for everyone an option I'm afraid.

**Comment by renchap** [comment]
We need to release a 4.2.2 version soon, it should be included

**Comment by joenepraat** [comment]
> We need to release a 4.2.2 version soon, it should be included

Thanks

**Pull request merged**
