### PR TITLE
Change actions in reports to require only one click

### PR DESCRIPTION
**Pull request by Gargron**
- Move "delete posts" action from table header to list of actions
- Duplicate list of actions above and below the table
- Instead of sending user to account action form, buttons (except for "Custom") perform the action with one click
- If the spam category is selected, no e-mail notification is generated (unless through "Custom")
- Increase width of action buttons to accommodate other languages

### CODE REVIEW

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
I understand the reason why you'd not send warnings when the selected reason is “spam”, but I'm not sure I agree with it. In any case, it should be clearly communicated within the interface, which is not currently the case.

I understand why you decided to duplicate the buttons, but it looks [untidy and unprofessional](https://github.com/mastodon/mastodon/pull/11837#issuecomment-531414192). I'd rather have a link instead.
image

Additionally, the increased button width is not great on mobile:
image

**Comment by Gargron** [comment]
> I understand why you decided to duplicate the buttons, but it looks untidy and unprofessional. I'd rather have a link instead.

Buttons as links, or a link to the page section with buttons? A link that scrolls you is still one more click.

**Comment by ClearlyClaire** [comment]
> Buttons as links, or a link to the page section with buttons?
A link to the page section with buttons, yes.

> A link that scrolls you is still one more click.
ok maybe you should put the button every 3 reported toots :thinking:

**Comment by Gargron** [comment]
There are generally two "paths" a report can take: Let's say someone said something threatening in a conversation, and there are 2-3 posts in the report. As a moderator, these posts are central to the report, you need to look at them *and then* make a decision. The other path is someone reports a spammer. It is generally enough to see one post (or just username/bio) to know it's a spammer. Some people find it a good idea to include 40 of the spammer's posts in the report.

In the first path, taking action is relevant below the posts. In the second path, taking action needs to be above the posts.

In the previous report UI, where the buttons were *only* above, the problem still existed because you would scroll to the bottom to check all of the reported posts, *and then* you'd have to scroll back up to make your decision.

So, having quick access above and below the table serves both paths. Maybe an action bar that floats along as you scroll would work better, but that might be trickier to integrate. Alternatively, the presence of the top copy of the bar could depend on the number of reported posts.

As for whether spam reports should generate e-mails: Sending e-mails that contain copies of the spammers' text could trigger spam filters in e-mail providers' servers and affect our sending reputation. There is also the volume concern: A lot of spammers that need to be banned, equals a lot of sending credits.

**Comment by ClearlyClaire** [comment]
> There are generally two "paths" a report can take: Let's say someone said something threatening in a conversation, and there are 2-3 posts in the report. As a moderator, these posts are central to the report, you need to look at them _and then_ make a decision. The other path is someone reports a spammer. It is generally enough to see one post (or just username/bio) to know it's a spammer. Some people find it a good idea to include 40 of the spammer's posts in the report.
> 
> In the first path, taking action is relevant below the posts. In the second path, taking action needs to be above the posts.
> 
> In the previous report UI, where the buttons were _only_ above, the problem still existed because you would scroll to the bottom to check all of the reported posts, _and then_ you'd have to scroll back up to make your decision.
>
> So, having quick access above and below the table serves both paths. Maybe an action bar that floats along as you scroll would work better, but that might be trickier to integrate. Alternatively, the presence of the top copy of the bar could depend on the number of reported posts.

A link to the section either above or below the posts would work as well, and be less confusing and visually jarring.
 
> As for whether spam reports should generate e-mails: Sending e-mails that contain copies of the spammers' text could trigger spam filters in e-mail providers' servers and affect our sending reputation. There is also the volume concern: A lot of spammers that need to be banned, equals a lot of sending credits.

Yes I do understand that. But a moderator shouldn't have to read the PR to know about that behavior.

**Comment by Gargron** [comment]
Link to skip to actions:

image

Description mentions special behaviour for the spam category, added "Mark as resolved" button:

image

Responsive design:

image

**Review by ClearlyClaire — APPROVED** [review]
This looks slightly crowded with the 5 buttons, but this is much better, thank you!

**Pull request merged**
