### PR TITLE
Autofix Rubocop Style/SymbolArray

### PR DESCRIPTION
**Pull request by nschonni**
https://docs.rubocop.org/rubocop/cops_style.html#stylesymbolarray

Didn't test to see if the `EnforcedStyle: brackets` might cause less noise, as I used the default

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Is that a new rule? I'm really not a fan of changing code style project-wise without a good reason, for the following reasons:
- it makes tools like `git blame` less useful
- it creates a lot of conflicts in PRs (I've spent a few hours of each of the past few weeks rebasing stuff)
- more generally, it creates a lot of conflicts in downstreams (I've spent far more time than I'd want dealing with that in glitch-soc lately)

**Comment by ClearlyClaire** [comment]
> No, according to the linked docs, it's been there since Rubodoc 0.9.

But it wasn't enabled in Mastodon's rubocop config until recently, right? I don't remember seeing Rubocop complain about it at any point.

**Comment by nschonni** [comment]
Hard to say. Because Superlinter, and maybe Codeclimate too, only ran on changed files that as Rubocop changed the defaults it wasn't noticed before. Also might have been silent until the `NewCops` was enabled in https://github.com/mastodon/mastodon/commit/19f78ea8fadc4626f7b2db5dbe37accbde6a968c

The CI is running over everything now, so the idea is that any new Rubocop versions/rules can be evaluated as they come

**Comment by ClearlyClaire** [comment]
> Hard to say.

Seems like it was explicitly disabled until very recently in https://github.com/mastodon/mastodon/pull/23629

**Comment by nschonni** [comment]
> > Hard to say.
> 
> Seems like it was explicitly disabled until very recently in #23629

Ah, you're right, I removed all the enable/disables that didn't have any overrides with that one to move them to the TODOs. That would be why it wasn't flagged before

**Comment by ClearlyClaire** [comment]
Yeah, they weren't flagged before because the rule was explicitly disabled. You changed the rules. And I'm not sure I see the point in that. At the very least, changing code style rules should be discussed upfront.

The overhead this introduce will also bite us and forks when we'll have to backport fixes to older releases.

**Comment by nschonni** [comment]
I tried a few settings to see what would give a consistent format, with the least churn on the current code:

<details><summary>EnforcedStyle: bracket</summary>

```
	modified:   app/controllers/api/v1/admin/accounts_controller.rb
	modified:   app/controllers/api/v1/admin/canonical_email_blocks_controller.rb
	modified:   app/controllers/api/v1/admin/domain_allows_controller.rb
	modified:   app/controllers/api/v1/admin/domain_blocks_controller.rb
	modified:   app/controllers/api/v1/admin/email_domain_blocks_controller.rb
	modified:   app/controllers/api/v1/admin/ip_blocks_controller.rb
	modified:   app/controllers/api/v1/admin/reports_controller.rb
	modified:   app/controllers/api/v1/apps/credentials_controller.rb
	modified:   app/controllers/api/v2/admin/accounts_controller.rb
	modified:   app/controllers/follower_accounts_controller.rb
	modified:   app/controllers/following_accounts_controller.rb
	modified:   app/controllers/instance_actors_controller.rb
	modified:   app/controllers/settings/preferences_controller.rb
	modified:   app/helpers/application_helper.rb
	modified:   app/lib/activitypub/tag_manager.rb
	modified:   app/models/account_filter.rb
	modified:   app/models/account_statuses_filter.rb
	modified:   app/models/admin/action_log_filter.rb
	modified:   app/models/admin/appeal_filter.rb
	modified:   app/models/admin/status_filter.rb
	modified:   app/models/announcement_filter.rb
	modified:   app/models/concerns/account_counters.rb
	modified:   app/models/custom_emoji_filter.rb
	modified:   app/models/featured_tag.rb
	modified:   app/models/follow_recommendation_filter.rb
	modified:   app/models/form/admin_settings.rb
	modified:   app/models/import.rb
	modified:   app/models/instance_filter.rb
	modified:   app/models/invite_filter.rb
	modified:   app/models/media_attachment.rb
	modified:   app/models/notification.rb
	modified:   app/models/relationship_filter.rb
	modified:   app/models/report_filter.rb
	modified:   app/models/trends/preview_card_filter.rb
	modified:   app/models/trends/preview_card_provider_filter.rb
	modified:   app/models/trends/status_filter.rb
	modified:   app/models/trends/tag_filter.rb
	modified:   app/models/user_role.rb
	modified:   app/services/report_service.rb
	modified:   lib/mastodon/accounts_cli.rb
	modified:   spec/lib/settings/scoped_settings_spec.rb
	modified:   spec/mailers/notification_mailer_spec.rb
	modified:   spec/models/web/push_subscription_spec.rb
```

</details>

<details><summary>MinSize: 3</summary>

```
	modified:   app/controllers/admin/accounts_controller.rb
	modified:   app/controllers/admin/announcements_controller.rb
	modified:   app/controllers/admin/domain_blocks_controller.rb
	modified:   app/controllers/admin/relays_controller.rb
	modified:   app/controllers/admin/roles_controller.rb
	modified:   app/controllers/admin/webhooks_controller.rb
	modified:   app/controllers/api/v1/accounts_controller.rb
	modified:   app/controllers/api/v1/admin/accounts_controller.rb
	modified:   app/controllers/api/v1/admin/canonical_email_blocks_controller.rb
	modified:   app/controllers/api/v1/admin/domain_blocks_controller.rb
	modified:   app/controllers/api/v1/admin/ip_blocks_controller.rb
	modified:   app/controllers/api/v1/crypto/deliveries_controller.rb
	modified:   app/controllers/api/v1/crypto/keys/uploads_controller.rb
	modified:   app/controllers/api/v1/filters_controller.rb
	modified:   app/controllers/api/v1/statuses_controller.rb
	modified:   app/controllers/api/v2/filters/keywords_controller.rb
	modified:   app/controllers/api/v2/filters_controller.rb
	modified:   app/controllers/auth/registrations_controller.rb
	modified:   app/controllers/filters_controller.rb
	modified:   app/controllers/settings/applications_controller.rb
	modified:   app/lib/feed_manager.rb
	modified:   app/models/media_attachment.rb
	modified:   app/models/report.rb
	modified:   app/models/site_upload.rb
	modified:   app/serializers/rest/notification_serializer.rb
	modified:   db/migrate/20161006213403_rails_settings_migration.rb
	modified:   db/migrate/20161119211120_create_notifications.rb
	modified:   db/migrate/20170112154826_migrate_settings.rb
	modified:   db/migrate/20170905044538_add_index_id_account_id_activity_type_on_notifications.rb
	modified:   db/migrate/20171129172043_add_index_on_stream_entries.rb
	modified:   db/migrate/20180106000232_add_index_on_statuses_for_api_v1_accounts_account_id_statuses.rb
	modified:   db/migrate/20180514140000_revert_index_change_on_statuses_for_api_v1_accounts_account_id_statuses.rb
	modified:   db/migrate/20180929222014_create_account_conversations.rb
	modified:   db/migrate/20190316190352_create_account_identity_proofs.rb
	modified:   db/migrate/20190511134027_add_silenced_at_suspended_at_to_accounts.rb
	modified:   db/migrate/20190820003045_update_statuses_index.rb
	modified:   db/migrate/20200114113335_create_announcement_reactions.rb
	modified:   db/migrate/20200917222316_add_index_notifications_on_type.rb
	modified:   db/post_migrate/20190511152737_remove_suspended_silenced_account_fields.rb
	modified:   db/post_migrate/20200917222734_remove_index_notifications_on_account_activity.rb
	modified:   spec/controllers/api/v1/streaming_controller_spec.rb
	modified:   spec/fabricators/notification_fabricator.rb
```

</details>

<details><summary>MinSize: 4</summary>

```
	modified:   app/controllers/admin/accounts_controller.rb
	modified:   app/controllers/admin/domain_blocks_controller.rb
	modified:   app/controllers/api/v1/accounts_controller.rb
	modified:   app/controllers/api/v1/crypto/deliveries_controller.rb
	modified:   app/controllers/api/v1/crypto/keys/uploads_controller.rb
	modified:   app/controllers/api/v1/statuses_controller.rb
	modified:   app/controllers/api/v2/filters_controller.rb
	modified:   app/controllers/auth/registrations_controller.rb
	modified:   app/controllers/filters_controller.rb
	modified:   app/controllers/settings/applications_controller.rb
	modified:   app/models/report.rb
	modified:   app/serializers/rest/notification_serializer.rb
	modified:   db/migrate/20180106000232_add_index_on_statuses_for_api_v1_accounts_account_id_statuses.rb
	modified:   db/migrate/20180514140000_revert_index_change_on_statuses_for_api_v1_accounts_account_id_statuses.rb
	modified:   db/migrate/20190820003045_update_statuses_index.rb
	modified:   spec/controllers/api/v1/streaming_controller_spec.rb
	modified:   spec/fabricators/notification_fabricator.rb
```

</details>

**Pull request closed without merging**
