### PR TITLE
Get rid of the Content Warning rainbows

### PR DESCRIPTION
**Pull request by ClearlyClaire**
In my opinion, the “correct” fix would be to simply have a “Show more” button just like everywhere else, as initially proposed in #7452, for clarity, consistency, and for the reasons enumerated in #7752.

In the meantime, this PR fixes the most obvious accessibility issues with this joke commit I did not really expect to get merged.

~~~Kept the animated rainbows otherwise because the content warnings don't really stand out, but we could also remove it entirely.~~~

### CODE REVIEW

**Comment by nightpool** [comment]
I would prefer to remove it entirely. aside from accessibility issues, it
makes reading the actual content warning nearly impossible

**Comment by ThibG** [comment]
@nightpool alright, but it doesn't sufficiently stand out to me without it. Would changing the color to `$error-red` be better?

screenshot_2018-08-05 account statuses - thib - dev instance

**Comment by ThibG** [comment]
Or rather `$warning-red`, this seems more appropriate and has slightly higher contrast.

screenshot_2018-08-05 account statuses - thib - dev instance 1

**Comment by smonff** [comment]
Isn't there a `$warning-color` already defined in the Mastodon UI rules? Just asking.

**Comment by smonff** [comment]
I find it appropriate that the $error-red color has been  changed to the $warning-red. 

Then, in term of contrast between background and text, is this red light enough for being used on a dark background? Plus, if you are color blind, you eventually don't see the redness.

**Comment by ThibG** [comment]
I would think that it is enough. As for colorblindness, you're right, you may not see this additional color hint.

I still think the best way to handle this would not be with color, but by adopting the same behavior than everywhere else, i.e., use a button and hide what's behind the CW, but that was rejected last time I proposed it.

**Comment by ThibG** [comment]
*sigh* I can change it back to the default color, but if this color doesn't work, then we have wider issues, it's used in other places.
You want this text to be different than the toot's content because how would you understand that it's the Content Warning otherwise? (No, the “Content Warning” prefix isn't enough, a regular toot without CW could start this way too)

**Comment by dn3s** [comment]
This is based on what i've heard from others talking about the issue on mastodon:

CWs still have use in an admin context. on instances with multiple admins, one can for example delegate reviewing a particular report to another admin if it's a subject that will be harmful to engage in for that particular admin. Even in the case of single-admin instances, admins can choose to review reports based on their content on their own terms instead of having them pop up in their face with no warning.

Obviously the benefits of this are limited as posts being reported were likely not made in good faith, but it's still helpful.

Remember, people with ptsd, photosensitive epilepsy, or a wide variety of mental health issues that benefit from CWs can make great admins, as they are often better equipped to understand the difficulties marginalized users face. We may as well make their experience a bit better.

**Comment by Gargron** [comment]
Okay, can you try using html details/summary tags for this?

<details>
<summary>Like</summary>
<div>This</div>
</details>

I'm just not fond of duplicating JS over so many places nor do I really like the "show more" button styling to be honest even though I came up with it.

**Comment by ThibG** [comment]
@Gargron I can give it a try, but it is apparently unsupported in Edge, so I'm not completely sure how it would look like there.

**Comment by dn3s** [comment]
i'm a little confused by the scope of this discussion. why are we talking about implementation details of CWs here, when that's already been established elsewhere? why not implement CWs in this context as they are everywhere else, and if people don't like the current implementation, have that as a separate discussion? This introduces an unnecessary blocker to fixing the immediate issue.

Is there some reason I'm missing that makes this specific case an ideal place to start rolling out a new CW implementation, and some reason why rolling out that change is relevant to the issue this PR is attempting to fix? Or is there some reason why the current implementation is appropriate on the timeline interface but inappropriate on the admin interface?

**Review by Gargron — APPROVED** [review]

**Pull request merged**
